### ISSUE TITLE
Gradient legends on GR backend

### ISSUE THREAD

**Issue by kescobo** [JuliaPlots/Plots.jl#1004]
I've got another one for you @jheinen :

```julia
using Plots

d=rand(1:10, 100)
scatter(d, zcolor=d, marker=:heat, ms=4)
```

Using GR, the gradient labels go from 0:1 regardless of the underlying data

![gr](https://user-images.githubusercontent.com/3502975/29139830-4f4850e6-7d16-11e7-9ab3-2b2f770dedd1.png)

vs pyplot

![pyplot](https://user-images.githubusercontent.com/3502975/29139849-5ecfb176-7d16-11e7-975d-91c2f088d3ad.png)

**Comment by jheinen** [comment]
Fixed in https://github.com/JuliaPlots/Plots.jl/pull/1005
