### ISSUE TITLE
stephist does not work on the y axis

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1010]
```julia
using Plots; gr()
stephist(randn(1000), orientation = :h)
```
![skaermbillede 2017-08-15 kl 11 36 30](https://user-images.githubusercontent.com/8429802/29310441-03aa639e-81ae-11e7-9dc2-58b460e6de63.png)
ping @oschulz

**Comment by oschulz** [comment]
You can assign it to me - probably won't get to it this week, though.

**Comment by mkborregaard** [comment]
Thanks!

**Comment by rodolfomssouza** [comment]
What happens is that it does not invert the axis scales. So, you need to do it manually, xlims!(), and ylims!().
