### ISSUE TITLE
unicode character for plotly backend

### ISSUE THREAD

**Issue by AStupidBear** [JuliaPlots/Plots.jl#1013]
Look at this example
```julia
using Plots; plotly(); plot(rand(100); title = "≥") |> gui
```
this gives me
![2017-08-16_114729](https://user-images.githubusercontent.com/16422976/29346565-b19535c2-8278-11e7-8fd0-95998a2c6ac9.jpg)

**Comment by fedxa** [comment]
Which version are you using? Works for me on current master (and title is not below the axis, but above the picture...)

**Comment by AStupidBear** [comment]
the current released version

**Comment by AStupidBear** [comment]
Does the master branch support julia-0.5.2?

**Comment by mkborregaard** [comment]
no, only 0.6

**Comment by fedxa** [comment]
Hmm, what browser/system? For me (chromium/Linux/julia-0.6/Plots at master or current release) it works.

**Comment by AStupidBear** [comment]
chrome/win10/julia-0.5.2/Plots at current release

**Comment by mkborregaard** [comment]
Yup, Plots is stuck at 0.11.3 for julia 0.5. There's so much to do on this repo we don't also support legacy julia. This'll possibly change after 1.0 though.
