### ISSUE TITLE
Add :volume seriestype support for PlotlyJS backend

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1016]
I tried with GR, PyPlot and PlotlyJS, all failed... Also tried `:contour3d` but it seems to be pointing to `:volume`?

**Comment by mkborregaard** [comment]
Only GLVIsualize, I think. At least PlotlyJS can do volumes natively, though.

**Comment by juliohm** [comment]
Thank you @mkborregaard, GLVisualize recognized it, however the plot is not looking very nice.

PlotlyJS also supports it? I will rename the issue accordingly...

**Comment by SimonDanisch** [comment]
>however the plot is not looking very nice.

What's the issue?

**Comment by juliohm** [comment]
I don't know if the issue is on my side, but I was expecting to see more color transitions in these cubes:

![cube](https://user-images.githubusercontent.com/3345261/29401291-7c28bab8-82e5-11e7-96b8-ae60e70fda1c.png)

I am still working heavily on the code, so it might as well be a bug on my package. The script to reproduce (requires GeoStats.jl master):

```julia
using GeoStats

geodata = GeoDataFrame(DataFrames.DataFrame(
                                            x=[25.,50.,75.],
                                            y=[25.,75.,50.],
                                            z=[10.,20.,30.],
                                            value=[1.,0.,1.],
                                            value2=[2.,3.,4]), [:x,:y,:z])

domain = RegularGrid{Float64}(100,100,30)

problem = EstimationProblem(geodata, domain, [:value])

solver = Kriging(
    :value=>KrigParam(variogram=GaussianVariogram(range=20.))
)

solution = solve(problem, solver)

using Plots; glvisualize()

plot(solution, size=(1000,500))
```

**Comment by juliohm** [comment]
Nevermind, I changed the range of the variogram model to a larger value and it starts to show more colors. Is there any way to slice or interact with the plot using the glvisualize() backend?

**Comment by juliohm** [comment]
I'm running it in Jupyter, interactivity should work there as well?

**Comment by SimonDanisch** [comment]
Not really. But maybe soon, now that @shashi started helping me out: https://github.com/JuliaLang/IJulia.jl/issues/550

**Comment by juliohm** [comment]
Thanks for your work @SimonDanisch, that would be awesome.

**Comment by juliohm** [comment]
I am closing this one as it is not priority. Looking forward to a solution with Makie.jl :)
