### ISSUE TITLE
pyplot(): zcolor keyword not working with lines

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaPlots/Plots.jl#1021]
I can't make the colorbar to appear with the `plot` command:

`using Plots; pyplot()`
`plot(rand(10,6), zcolor=1:10, colorbar=true, leg=false)`
![wrong](https://user-images.githubusercontent.com/26485264/29460961-e887819a-83f7-11e7-90cd-044acfb4a02b.png)

However, when calling `scatter` it does somehow works (https://github.com/JuliaPlots/Plots.jl/issues/412).

**Comment by mkborregaard** [comment]
What are you expecting to happen?

**Comment by lnacquaroli** [comment]
Good question. Something like this:

![screenshot at 2017-08-18 10-51-30](https://user-images.githubusercontent.com/26485264/29463491-d5187b56-8400-11e7-92a6-10c672553e83.png)

I would like to map the colors of the colorbar to the line series, but I can't make the colorbar to appear when using lines instead of markers. I don't know if I am clear enough.

**Comment by mkborregaard** [comment]
Hm, I see. That's not easy to do. `zcolor` is short for `marker_z`, so it is only meant to affect the color of markers. There is a `line_z` attribute that never really worked. And the automatic color gradients are meant to work within a series, not across it. You can do some more complex things with lines with the `compositeline` recipe in PlotRecipes.

Apart from that, I agree the colorbar should not be suppressed when you ask for it explicitly. That is an unfeature.

**Comment by daschw** [comment]
This is now possible on master with GR with the `line_z` attribute (https://github.com/JuliaPlots/Plots.jl/pull/1110)

**Comment by lnacquaroli** [comment]
Great to hear. Should we close this? The title is on `pyplot` though... Up to you guys.

**Comment by lnacquaroli** [comment]
Awesome work BTW!

**Comment by daschw** [comment]
Thanks, I plan to implement this for pyplot and plotly soon anyways, so we can wait until then with closing.
