### ISSUE TITLE
PlotlyJS: stacked bar charts

### ISSUE THREAD

**Issue by fipelle** [JuliaPlots/Plots.jl#1022]
Hi, 

I am trying to make a stacked bar chart with PlotlyJS. I know it can be done, since PlotlyJS.jl is able to handle this particular type of bar chart (see http://spencerlyon.com/PlotlyJS.jl/examples/bar/). I wonder if this can be done using Plots, since I would much prefer it. Would you please help me out with it?

Thanks

**Comment by mkborregaard** [comment]
It's in StatPlots

**Comment by mkborregaard** [comment]
Here is the docs: https://github.com/JuliaPlots/StatPlots.jl#grouped-bar-plots
