### ISSUE TITLE
How to plot contourf with GR?

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1024]
When I specify the seriestype `:contourf` with PyPlot and PlotlyJS, I get a nice colored contour map:

![pyplot](https://user-images.githubusercontent.com/3345261/29488472-de827a64-84c0-11e7-8f6d-d14179152a81.png)

With GR, the contours don't show up:

![gr](https://user-images.githubusercontent.com/3345261/29488500-42b0feb6-84c1-11e7-8ecd-c282d2f43f90.png)

but I know that GR is capable of drawing these colored contours, see the illustration in the homepage: https://gr-framework.org

**Comment by juliohm** [comment]
cc: @jheinen

**Comment by mkborregaard** [comment]
This looks weird, is it screenshots or based on savefig?

**Comment by juliohm** [comment]
@mkborregaard these are screenshots, and I think I have read other threads for which I don't have the URLs unfortunately where people discuss the difference between heatmaps, contour plots and etc. in GR and other backends. It would be nice to have GR working here, I am trying to rely on it the most in my package and tutorials.

**Comment by mkborregaard** [comment]
Can you post an MWE to replicate? It makes it easier to troubleshoot.

**Comment by juliohm** [comment]
I have one tutorial that is working with the master branch, but it may break soon, as I am trying to transition the problem definitions to a separate package: https://github.com/juliohm/GeoStats.jl/blob/master/examples/EstimationProblems.ipynb

**Comment by jheinen** [comment]
I'm currently busy, but I'll check this ASAP. Kind of a color quantization in GR might help ...

**Comment by jheinen** [comment]
@juliohm : where is `GeoDataFrame` defined?
```julia
# inform the coordinates of the data
geodata = GeoDataFrame(df, [:x,:y])
ERROR: UndefVarError: GeoDataFrame not defined
```

**Comment by juliohm** [comment]
Hi Josef, it should be in GeoStats.jl master branch, I can check it
tomorrow...

**Comment by jheinen** [comment]
I'm already on `GeoStats` master - will try another MWE ...

**Comment by juliohm** [comment]
Sorry, I may have corrupted the master branch with the transitions to
GeoStatsBase.jl. Any plot recipe with contourf reproduces the issue though.
Thank you again for looking into this, I'm going to bed, but will double
check tomorrow morning where the GeoDataFrame ended up.

**Comment by jheinen** [comment]
Color quantization produces pixelated results - we have to implement a dedicated function in GR. So there is no short-time solution - I put it onto our TODO list ;-)

**Comment by juliohm** [comment]
Thank you @jheinen, whenever you find time :-)

**Comment by juliohm** [comment]
I want this feature so much :sob: @jheinen from what I understood there is no function in the GR framework at the moment for filled contour plots, is that correct? I would try to wrap the function myself if it was already there waiting to be called.

**Comment by SimonDanisch** [comment]
The glvisualize backend has it :) admittedly, I only recently got around to create a color legend but only in Makie, though :(

**Comment by juliohm** [comment]
Nice @SimonDanisch, it is great that we have so many options at our disposal. I will switch to Makie when plot recipes are in place and working smoothly. I see the huge benefit of adding interactivity and I am looking forward to see the package mature.

**Comment by aramirezreyes** [comment]
Apparenly this has been resolved in GR
[https://github.com/jheinen/GR.jl/issues/165#issuecomment-438518409](In his issue)
Is there anything that should be done to make it work on Plots.jl?

**Comment by mkborregaard** [comment]
Yes, the Plots GR backend needs to actually call GR's `contourf` function for the `contourf` seriestype. I think @jheinen looked into this?

**Comment by jheinen** [comment]
I made a PR (#1880) to support the new `contourf` function.

**Comment by mkborregaard** [comment]
Awesome!

**Comment by juliohm** [comment]
What problems @jheinen ? They seem to be working wonderfully now :heart:

**Comment by aramirezreyes** [comment]
Thanks for the good work!
