### ISSUE TITLE
gr(): add right and top axis

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaPlots/Plots.jl#1025]
I wonder if there is any way to add the two missing right and top axis when using the gr backend, to have a plot like in pyplot for instance with the boxed area.

**Comment by daschw** [comment]
Not right now. It would be nice to have this option, though.
For GR and GLVisualize this could be implemented quite easy here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/axes.jl#L487 with a new attribute like `draw_axes_border::Bool` Maybe someone can think of a better name.
