### ISSUE TITLE
Allow Date and DateTime as ticks

### ISSUE THREAD

**Issue by nicknack23** [JuliaPlots/Plots.jl#1026]
To pass dates as ticks, you must currently convert to Int. This is very hard to figure out if you are ignorant of the internals of Plots.jl, as I am. Thank you again @daschw for showing me the underlying problem on Gitter.
```
days = Date(2015,1,1):Date(2015,12,31)
tickdays = Date(2015,1,1):Dates.Month(1):Date(2015,12,31)
plot(days, rand(length(days)), xticks = Dates.value.(tickdays))
```
It would be nicer if this worked:
```
days = Date(2015,1,1):Date(2015,12,31)
tickdays = Date(2015,1,1):Dates.Month(1):Date(2015,12,31)
plot(days, rand(length(days)), xticks = tickdays)
```
On a side note, when using the tuple syntax it would be be nice if the format string accepted dates. Here I'm converting DateTime to Date to get rid of the hours. This currently doesn't work.
```
days = DateTime(2015,1,1):DateTime(2015,12,31)
tickdays = DateTime(2015,1,1):Dates.Month(1):DateTime(2015,12,31)
plot(days, rand(length(days)), xticks = (Dates.value.(tickdays), Date.(tickdays)))
```
The error: `ERROR: MethodError: no method matching length(::Date)`.

**Comment by mkborregaard** [comment]
I'd agree that "I wouldn't have figured that out in a million years" isn't the user experience we're aiming at :joy:

**Comment by daschw** [comment]
Weird, `plot(days, rand(length(days)), xticks = (Dates.value.(tickdays), Date.(tickdays)))` works for me.
