### ISSUE TITLE
xticks being cut with GR even with extra margin

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Plots.jl#1028]
With GR, if I do: `plot(1:10,rand(10), right_margin = 10mm)` the `10.0` tick on the x axis get cut, even if I give extra margin

![test](https://user-images.githubusercontent.com/6333339/29497041-54d2e60a-85d8-11e7-806e-04dcf2e57afb.png)

Actually, it seems like, at least on my machine, specifying a margin has no effect wih GR

**Comment by daschw** [comment]
Also:
```julia
using Plots; gr()
plot(["String $i" for i in 1:10], rand(10), xrotation = 90)
```
![gr_x_rotation](https://user-images.githubusercontent.com/16589944/29498132-2898c992-85f6-11e7-86aa-a2d5a495b220.png)

**Comment by jheinen** [comment]
I'll check this. I first have to understand the logic, because I didn't implement this. The original code used `GR.axes()`, which was missing some features and thus had been replaced by pure Julia code ...

**Comment by piever** [comment]
> I'll check this. I first have to understand the logic, because I didn't implement this

Thanks a lot! This margin issue is the only thing blocking me from using GR for paper figures.
I put an attempted solution in #1038 by estimating the dimension of the ticks using  `gr_set_font` and `gr_inqtext` but you're certainly in a much better position to find out what's the cleanest way to do that with GR code. Instead the axis guide (meaning, the label) as well as the title used to get a constant value and I left it that way for now. One important thing that was missing is that the user can specify extra margin in the plot call by giving for example `bottom_margin = 5mm`, which used to be neglected by the GR backend. You can access those values with `sp[:bottom_maring]`where `sp::Subplot`.
