### ISSUE TITLE
grouping seem to spoil zcolor

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Plots.jl#1031]
Potentially related with #962. 
Example:

```
using DataFrames
import RDatasets
using StatPlots
gr()
iris = RDatasets.dataset("datasets","iris");
scatter(iris[:PetalLength], iris[:PetalWidth], zcolor = iris[:SepalLength], group = iris[:Species], layout = 3)
```
gives:

![group](https://user-images.githubusercontent.com/6333339/29516336-ed5d8c92-8667-11e7-9fba-66f87ddba035.png)

whereas

```
plt = plot(layout = 3)
counter = [0]
by(iris, :Species) do dd
    counter[1] += 1
    scatter!(plt, dd[:PetalLength], dd[:PetalWidth], zcolor = dd[:SepalLength], subplot = counter[1])
end
```

gives 
![groupby](https://user-images.githubusercontent.com/6333339/29516383-106e64ae-8668-11e7-98f0-49461c87c23d.png)

I'd be potentially in favor of the proposed improvement in #962: all args of the same length as the series also get split by `group`. If there's consensus that it's the way to go, I can try and implement that.

**Comment by piever** [comment]
Just to clarify: what I'm afraid is happening in the first plot is that only the first 50 values of `zcolor`are being used and repeated in the three plot. Given that the first species has a very narrow distribution of `SepalLength ` here the problem is obvious, but it could lead to subtle mistakes when the problem is not so obvious.

**Comment by mkborregaard** [comment]
I think that's right, and that the solution is the correct one.

BTW, in practice, using `group` should always generate points on the same clims for comparison but I don't think we need to enforce that programmatically - the user can control it with `clims`. And I want to add a recipe to StatPlots anyway that does this and also only has a single colorbar.

**Comment by piever** [comment]
Cool! I'm making progress in fixing this.
I got `scatter(iris[:PetalLength], iris[:PetalWidth], group = iris[:Species], zcolor = iris[:SepalLength], layout = 3)` to produce this:
![group](https://user-images.githubusercontent.com/6333339/29518349-dce6a0ca-8670-11e7-8459-7a333c86103d.png)

I still have a couple of issues: does `clims` really control the limits of the colorbar? In my setup it doesn't actually do anything,  but it's gonna be important in the case where I overlay the different series in the same subplot.

**Comment by mkborregaard** [comment]
There are reports that clims are currently bugged :-/
