### ISSUE TITLE
Error bars interact weirdly with zcolor in GR

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Plots.jl#1032]
GR tries to match the color of the error bars with the color from `zcolor`, but it doesn't quite work (plus, I can't really find the correct attribute to change them to black).
MWE:

`scatter(1:2, [1,1], zcolor = [0,1], xerr = 0.05, markersize = 8, markerstrokewidth= 3)`

![error](https://user-images.githubusercontent.com/6333339/29516808-d9a655d8-8669-11e7-9006-897d066f550a.png)

Maybe a simple solution would be to just plot the error bars of the same color as `markerstroke` ?

**Comment by mkborregaard** [comment]
That's just a big. Error bars get their color from `markerstrokecolor`

**Comment by daschw** [comment]
Closed by #1035
