### ISSUE TITLE
How can I add the string like PM2.5 in gr() with 2.5 is the subscript ，ug m-3.  -3 is Superscript

### ISSUE THREAD

**Issue by nizhizhen** [JuliaPlots/Plots.jl#1051]

**Comment by mkborregaard** [comment]
You use LaTeXStrings to define the latex-string, then pass that to the plot command where you need the text.
<img width="217" alt="skaermbillede 2017-08-29 kl 08 13 26" src="https://user-images.githubusercontent.com/8429802/29806943-0a40f6ca-8c92-11e7-9246-86889dc0ae7e.png">

**Comment by nizhizhen** [comment]
![2017-08-29 15-28-22](https://user-images.githubusercontent.com/19453340/29809443-c424dfde-8cce-11e7-8faa-5f09f608397d.png)

**Comment by nizhizhen** [comment]
sir, thanks for your reply! But things still go wrong, you see  why?
![2017-08-29 15-33-25](https://user-images.githubusercontent.com/19453340/29809600-6b3883c0-8ccf-11e7-8ce4-bf2652a8f859.png)

**Comment by mkborregaard** [comment]
Hard to say - it doesn't look Plots - related.

Also, should the y-argument be a 1-row matrix rather than a vector?

**Comment by nizhizhen** [comment]
When I  input    g=L"sdfsa"    then ,ouput :+1: 
Error displaying LaTeXStrings.LaTeXString: you must implement endof(LaTeXStrings.LaTeXString)

this may something wrong with LaTeXStrings ? what should I do .

**Comment by mkborregaard** [comment]
Well, your string to yaxis does not have an L in front.

**Comment by nizhizhen** [comment]
still error, I want the PM2.5 ,2.5 is the subscript .      I give up  . another help? the legend looks been masked , can I move it upper to close the top.  or  move out of the frames to the right. 
![2017-08-29 17-14-14](https://user-images.githubusercontent.com/19453340/29813897-10d9d9b0-8cde-11e7-8074-6e2a8c632eaa.png)

**Comment by mkborregaard** [comment]
Check this page https://juliaplots.github.io/attributes/ for all the keywords you can use to modify plots. The attribute for legend placement is called "legend". Also, you can use a Vector of `Base.Date`s for the x axis rather than passing a string, that will allow Plots to handle the ticks.

**Comment by nizhizhen** [comment]
^_^，thanks a lot.  I am a fish man ,  would you show me the detail codes about Base.Dates.   e.g. legend=Dates(...)  ?

**Comment by mkborregaard** [comment]
About Dates, read this: https://docs.julialang.org/en/stable/manual/dates
You can simply pass a vector of Dates as `x` to Plots.

**Comment by nizhizhen** [comment]
![2017-08-31 19-23-25](https://user-images.githubusercontent.com/19453340/29920810-e16c2e12-8e81-11e7-9994-a73961a5dc55.png)

sir.  I really can not understand the lower legend, how to move it more close to the top like 100 value. y axis  enough .  can you give me the detail . code ?    e.g.   legend=(.....)

**Comment by mkborregaard** [comment]
I'm sorry but we don't offer very accurate legend placement - just e.g. :topright and so on.Your best bet is to make the plot higher. Agreed, we should offer this. You're welcome to open a new separate feature request issue on that.

**Comment by nizhizhen** [comment]
thank you  sir
