### ISSUE TITLE
Plotting two surfaces together

### ISSUE THREAD

**Issue by albi3ro** [JuliaPlots/Plots.jl#1059]
When I try and plot two surfaces together, one ... gets squished.  That's the best I can describe it.  

Each works independently.  

I've tried with both plotlyjs and gr.

https://www.awesomescreenshot.com/image/2771502/2e87c1d93c5151b983fd64b45fdba700

**Comment by albi3ro** [comment]
Solved.  Just noticed I typed `ky` instead of `ks`. `ky` is a matrix of values where `ks` was the range those the values took on. Oops....

**Comment by mkborregaard** [comment]
😌
