### ISSUE TITLE
PGFPlots install error 

### ISSUE THREAD

**Issue by nizhizhen** [JuliaPlots/Plots.jl#1066]
![2017-09-01 20-06-01](https://user-images.githubusercontent.com/19453340/29969048-0423b374-8f51-11e7-8cdb-a2691d66ff4f.png)

 what is wrong         what should I do  install  the PGFPlots  backend

**Comment by mkborregaard** [comment]
I have no idea. Try opening an issue on PGFPlots.

**Comment by mkborregaard** [comment]
Sorry for being short, but there's really nothing we can do about installation issues with other packages.
By the way, for questions like you have, it is usually much better to go to our friendly gitter chatroom: https://gitter.im/tbreloff/Plots.jl
We tend to use issues on Plots for feature requests and bug reports.
