### ISSUE TITLE
GLVisualize backbend issues of basic plot in Plots.ji

### ISSUE THREAD

**Issue by nizhizhen** [JuliaPlots/Plots.jl#1071]
The guild on Plots.ji wed only have these:
The future: works in progress
GLVisualize
........

the figure below is plotted with GLVisulize backbend in Plots.ji. I . the code is below:

```julia
using Compose,DataFrames,DataFramesMeta,LaTeXStrings

using Plots
glvisualize()
................
c=plot(times,[improvment_pm25,improvment_secondpm25,improvment_so2,improvment_no2],
    marker = (:circle,5, 0.5, ),
    title="(b)",title_location=:topleft,titlefont=Plots.font(11),
    label=["\ PM_2.5","\ Secondary PM_2.5","\ SO_2","\ NO_2"],
    legendfont=Plots.font(7), legend=:right,
    xaxis=("",Plots.font(8)),xrotation=0,
    yaxis=("Improvment (%)",(0,70),0:10:70,Plots.font(8)),
    window_title="sdfd"
)

plot(c, layout=(1), dpi=600, size=(600,600))

savefig("plot.png")
```
the arguments like "dpi=600,size=(600,600):, "legend=:right" seem to been ignored ?

![2017-09-04 22-36-04](https://user-images.githubusercontent.com/19453340/30040379-14ce446a-9211-11e7-9dc1-1decb8a5f68c.png)

**Comment by mkborregaard** [comment]
The `legend` keyword isn't yet implemented for GlVisualize, and with regards to `size` that plotting window is wonky. Do you know you could make the x axis a real time axis with `times = Date(2017, 12, 8):Date(2017,12, 19)`?

**Comment by nizhizhen** [comment]
thanks for your reply ,   while wonky means ？  it can not been modified with length and width?, and de default dpi is so low ,can have any choice to change.?

**Comment by mkborregaard** [comment]
wonky means it does't work very well. It'd be great to develop this backend more for sure. I'll reopen this and add it to the glvisualize issues.

**Comment by nizhizhen** [comment]
thanks,

**Comment by nizhizhen** [comment]
I appreciate this cooperation of GLVisualize and Plots.jl   best wish and pray for you.^_^。

**Comment by daschw** [comment]
Closing, as GLVisualize is no longer supported.
