### ISSUE TITLE
Legend shows lines, not shapes, for :bar plots with pgfplots()

### ISSUE THREAD

**Issue by nizhizhen** [JuliaPlots/Plots.jl#1080]
![2017-09-08 13-50-18](https://user-images.githubusercontent.com/19453340/30197804-b02412ae-949c-11e7-801c-e5c09fe2f3f2.png)
you see,  the legend in (a) is wrong ? , the axis text in (b) should be same as (a), how,

**Comment by mkborregaard** [comment]
Hi, I've changed the title to reflect what I think you mean.
Note that support questions work best on our gitter channel https://gitter.im/tbreloff/Plots.jl .

**Comment by daschw** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/1475
