### ISSUE TITLE
can I have a double y axis ?

### ISSUE THREAD

**Issue by nizhizhen** [JuliaPlots/Plots.jl#1081]
default y axis is on the left of fig.     but  I want  another axis  on the right    .   how

**Comment by nizhizhen** [comment]
in GR()

**Comment by daschw** [comment]
If you really want a second yaxis with another scale that is not possible. If you just want to draw a frame around your axes you can do this with `framestyle = :box`
Note that support questions work best on our gitter channel https://gitter.im/tbreloff/Plots.jl.

**Comment by mkborregaard** [comment]
Just to follow up, you actually can - use the `twinx` function as shown here https://github.com/JuliaPlots/Plots.jl/issues/594

**Comment by daschw** [comment]
Wow, good to know :smile:

**Comment by nizhizhen** [comment]
good to konw
