### ISSUE TITLE
Error saving as SVG  SystemError: opening file tikzpicture.log: No such file or directory

### ISSUE THREAD

**Issue by mohamed82008** [JuliaPlots/Plots.jl#1088]
I get the above error when I try to `plot` using `Plots.jl` with `pgfplots()` as a backend. Any idea what is missing?

**Comment by SebastianM-C** [comment]
I think that this may be because you are missing `pdf2svg`. Did you try to use `plot(...);` and then `savefig`?
This way the PDF will not be converted to SVG for display and it should work even if you don't have `pdf2svg` installed.
