### ISSUE TITLE
show(tuple of plots) sidy by side in jupyter notebook?

### ISSUE THREAD

**Issue by improbable22** [JuliaPlots/Plots.jl#1090]
When making quick plots in Jupyter / IJulia, quite often I'd like to plot a few different things from running the same cell. If I write `plot(::MyData), plot(::MyData)` on the last line then it returns a tuple of `Plots.Plot{...}` rather than drawing them. 

I would like to make this put the two plots side-by-side. This seems to have roughly the effect I'm looking for: 

    import Base.show
    
    function show(io::IO, m::MIME"text/html", tuple::Tuple{Plots.Plot,Vararg{Plots.Plot}})
        inline(plot( tuple... , size=(900,300) ))
    end
    
    plot(rand(20)) , plot(rand(20))

Might this be a useful default behaviour? 

I wrote `size=(900,300)` because `plot(::MyData)` is about half that size. Omitting this it squeezes both plots into the default size rectangle. To be smarter about this, can anyone tell me how to read out the size of the Plots.Plot objects?

**Comment by daschw** [comment]
Essentially you are showing a plot with multiple subplots with this implementation of `Base.show`. You know that you can also achieve this by putting a `plot(...)` around your last line, right?
I'm not really sure if your suggestion would be the desired default behaviour ... I have to think about whether there are any issues with this.
You can access the size of a plot object `p` with `p.attr[:size]`. The default size is `(600, 400)`. If you have more than 3 subplots they are arranged in 2 rows by default. Starting with 7 subplots you have 3 rows by default... This may be something to consider when playing around with the size.

**Comment by improbable22** [comment]
Indeed, I guess this is similar to wrapping `plot( ... , size=(...))` around my last line. Still this would be convenient for me.

Thanks for `p.attr[:size]`. Playing with this, two things are going wrong now. One is that output of `println()` before my `show... inline(plot...` is not printed. The other is that changing the output size seems to cause problems. 

Here are a set of cells which show the problems:

    using Plots 
    println("yes") 
    plot(rand(20), size=(300,200)) ## works fine! 

...

    import Base.show
    function show(io::IO, m::MIME"text/html", tuple::Tuple{Plots.Plot,Vararg{Plots.Plot}})
        inline(plot( tuple... , size=(500,200)))
    end
    
    println("no!") ## does not get displayed, or rather, gets over-written by plot 
    plot(rand(20)) , plot(rand(20)) ## axes clipped to 300-wide box

...

    println("yes") ## is printed
    plot( plot(rand(20)) , plot(rand(20)) , size=(500,200) ) ## same clipping problem 

...

    println("yes")
    plot( plot(rand(20)) , plot(rand(20)) ) ## plots at default size, but clipped to 200-high box?

This clipping of the plot only happens with default `gr()` backend, using `pyplot()` avoids this. Is this a known bug? 

The overwriting of "no!" always happens, and perhaps I just need to say something apart from ` inline(plot(`?

**Comment by daschw** [comment]
This is really weird. Thanks for reporting this!

**Comment by daschw** [comment]
There seems to be something wrong with subplots in IJulia:
![screenshot-2017-9-21 untitled4](https://user-images.githubusercontent.com/16589944/30700815-f4011d5e-9ee8-11e7-916e-ead142f16937.png)
Can anyone reproduce this?
cc: @mkborregaard @piever

**Comment by piever** [comment]
Nope, it works just fine on my machine, I have no idea what it could be.

**Comment by juliohm** [comment]
I can reproduce @daschw , and this issue has been happening for a while with GR. Sometimes my subplots don't show up, just the white canvas, or perhaps a white box in front of the curves blocking the contents.

**Comment by daschw** [comment]
Thanks @juliohm! Do you know if this is only for GR? Is there an open issue for that? Do you know if this really is related to subplots or does it just happen randomly?

**Comment by juliohm** [comment]
I don't have much clue @daschw, it happened many times recently with GR specifically, not sure it is related to subplots, but probably.

**Comment by improbable22** [comment]
For me this is only in GR, and it is the size of the first plot on starting up which sets the subsequent clipping -- I was setting `size=(...)` but it appears that the first sub-plot has the same effect. 

I just tried in "nteract" too, and do not see any clipping there.

**Comment by juliohm** [comment]
@improbable22 could you please rename the title to the original title and open a new issue to track the GR problem? These are two very distinct things that will be addressed.

**Comment by improbable22** [comment]
Sure, done. (I don't think I can make labels.)

**Comment by daschw** [comment]
Any opinions on @improbable22 's proposal [here](https://github.com/JuliaPlots/Plots.jl/issues/1090#issue-258103767) to change show for a tuple of plots in IJulia?

**Comment by improbable22** [comment]
Or indeed, any clues as to how to make it work just for me! My best attempt now uses `display(` but does not seem solid, I guess I don't know what I'm doing really. 

```
using Plots 

import Base.show

function show(io::IO, m::MIME{Symbol("text/plain")}, tuple::Tuple{Plots.Plot,Vararg{Plots.Plot}}) 
    totwidth = sum( p.attr[:size][1] for p in tuple)
    #show(io,m, plot(tuple...,size=(totwidth,300)) )
    #inline(plot(tuple...,size=(totwidth,300)))
    display( plot(tuple...,size=(totwidth,300)) )
end

println("some info")    ## this gets hidden if I use inline(plot...)
plot(rand(20)), plot(rand(20))
```

**Comment by juliohm** [comment]
It is appealing to have tuples being plotted with show, but the extra amount of code required in a practical situation where we have a vector of plots to plot, is just a single `plot(vec...)`. Redefining show may be too restrictive and it is a decision that would definitely be hard revert in the future.

**Comment by daschw** [comment]
Very good point @juliohm !

**Comment by juliohm** [comment]
Also, I like to think of `plot(plts...)` as a composition of small subplots. Tuple don't give this nice interpretation.

**Comment by improbable22** [comment]
My use case is that I was plotting a lot of results from some optimisation, with `plot(::MyType, options)` defined to give a square plot (because this suits the data). Wrapping two such plots with `plot(...)` doesn't preserve the sizes & squareness. Obviously I can write a function but then I have to remember what I called it, and it seemed like it would be convenient just to build this into `show()`, alongside `show(::MyType)`.

But as the default it's not so clear. Printing `(Plot{Plots.GRBackend() n=1}, Plot{Plots.GRBackend() n=1})` isn't all that useful, but I understand about hard to revert features.
