### ISSUE TITLE
Plots refers to old python library , how to change?

### ISSUE THREAD

**Issue by TheMadHatter666** [JuliaPlots/Plots.jl#1093]
I am trying to follow the tutorial, but can't get very far because even the simplest commands error out. It appears that Plots is looking for my python2.7 libraries even though I have Python 3.6 installed (and is the default version on my Mac).  I run 10.9.5.

<img width="912" alt="screen shot 2017-09-17 at 3 11 17 pm" src="https://user-images.githubusercontent.com/31166475/30524509-b9f29f56-9bba-11e7-9026-2d3e14be9732.png">

Thanks for any help.

**Comment by TheMadHatter666** [comment]
I appear to solved this by using the command Pkg.update() and then restarting the kernel.

**Comment by mkborregaard** [comment]
Great.
