### ISSUE TITLE
countoured wind rose plot can been plot? polor coordination

### ISSUE THREAD

**Issue by nizhizhen** [JuliaPlots/Plots.jl#1094]
a powerful plot like this .   help me for detail ?

![2017-09-19 10-29-58](https://user-images.githubusercontent.com/19453340/30573398-3a6fbf30-9d26-11e7-8701-a35eb9087292.png)

**Comment by mkborregaard** [comment]
That's very challenging but you could try something like `contour(x,y,f,fill=true, proj = :polar)`

e.g. this example from https://juliaplots.github.io/examples/pyplot/
```julia
x = 1:0.5:20
y = 1:0.5:10
f(x,y) = begin 
        (3x + y ^ 2) * abs(sin(x) + cos(y))
    end
X = repmat(x',length(y),1)
Y = repmat(y,1,length(x))
Z = map(f,X,Y)
contour(x,y,f,fill=true, proj = :polar)
```
<img width="575" alt="skaermbillede 2017-09-19 kl 08 50 24" src="https://user-images.githubusercontent.com/8429802/30579128-9a6627ee-9d17-11e7-88ec-459bf40ed233.png">
Doesn't work on GR.

**Comment by nizhizhen** [comment]
Pyplot  can not install in my PC ,      could GR can plot above?

**Comment by mkborregaard** [comment]
No, this functionality appears to be broken on GR. You could try one of the other backends, like plotlyjs.
