### ISSUE TITLE
recent savefig problems

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPlots/Plots.jl#1100]
Hi,`
very recently (as of 20 Sep 2017), this gives a problem in IJulia (using Win 7 64, Julia 0.6, all packages updated)
```
using Plots
x = -pi:0.01:pi
y = cos.(x)
plot(x,y)
savefig("MyPlot.pdf")
```
The warning message is 
> SystemError: opening file C:\Users\....

Works fine in a jl file, just not in IJulia.

Paul S

**Comment by daschw** [comment]
Your code works for me on Windows 7:
```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)

julia> Pkg.status.(["Plots", "IJulia"]);
 - Plots                         0.12.4+            master
 - IJulia                        1.6.1
```

**Comment by PaulSoderlind** [comment]
Thanks. If this is hard to replicate, then I better provide some more details.
1. same Julia and package versions as daschw reported.
2. It works (also in IJulia) if I instead do ```savefig("MyPlot.svg")```
3. The error messsage is copied below.
/Paul

> SystemError: opening file C:\Users\PSODER~1\AppData\Local\Temp\jl_B956.tmp.pdf: No such file or directory
> Stacktrace:
>  [1] #systemerror#44 at .\error.jl:64 [inlined]
>  [2] systemerror(::String, ::Bool) at .\error.jl:64
>  [3] open(::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\iostream.jl:104
>  [4] open(::Base.#readstring, ::String) at .\iostream.jl:150
>  [5] _show(::IOStream, ::MIME{Symbol("application/pdf")}, ::Plots.Plot{Plots.GRBackend}) at D:\Julia\Packages\v0.6\Plots\src\backends\gr.jl:1269
>  [6] show(::IOStream, ::MIME{Symbol("application/pdf")}, ::Plots.Plot{Plots.GRBackend}) at D:\Julia\Packages\v0.6\Plots\src\output.jl:208
>  [7] pdf(::Plots.Plot{Plots.GRBackend}, ::String) at D:\Julia\Packages\v0.6\Plots\src\output.jl:25
>  [8] savefig(::Plots.Plot{Plots.GRBackend}, ::String) at D:\Julia\Packages\v0.6\Plots\src\output.jl:123
>  [9] savefig(::String) at D:\Julia\Packages\v0.6\Plots\src\output.jl:125
>  [10] include_string(::String, ::String) at .\loading.jl:515

**Comment by daschw** [comment]
Does it work for other backends than GR?

**Comment by PaulSoderlind** [comment]
Works fine with pyplot()

**Comment by daschw** [comment]
OK, I now have a similar issue with Atom and GR on my Linux machine.
```julia
using Plots; gr()
plot(rand(10))
png("test_gr_saving")
```
works from the REPL. In Atom, however I get:
```julia
SystemError: opening file /tmp/juliaRr6BrQ.png: Datei oder Verzeichnis nicht gefunden
_show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.GRBackend}) at gr.jl:1269
show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.GRBackend}) at output.jl:208
png(::Plots.Plot{Plots.GRBackend}, ::String) at output.jl:8
png(::String) at output.jl:11
(::Atom.##63#66)() at eval.jl:104
withpath(::Atom.##63#66, ::Void) at utils.jl:30
withpath(::Function, ::Void) at eval.jl:38
macro expansion at eval.jl:103 [inlined]
(::Atom.##62#65{Dict{String,Any}})() at task.jl:80
```
Any ideas @jheinen?

**Comment by jheinen** [comment]
I think there is now a conflict with thel `GKS_FILEPATH` environment variable, which is used for the output file names. I probably have to patch both `Plots` and `GR`.

**Comment by jheinen** [comment]
The problem should be fixed in GR master (https://github.com/jheinen/GR.jl/commit/29092f4bf9b057537f6a517bf530ed7501754a30).

**Comment by PaulSoderlind** [comment]
Yes, it seems to work again. Thanks.

**Comment by mkborregaard** [comment]
Perfect.
