### ISSUE TITLE
cannot plot rectangles anymore (PlotlyJS)

### ISSUE THREAD

**Issue by bbrunaud** [JuliaPlots/Plots.jl#1102]
Hello, I had a code plotting a beautiful gantt chart and it stopped working since the last update.

```
using Plots

shape = Plots.Shape([4.0, 5.0, 5.0, 4.0], [2.1, 2.1, 2.9, 2.9])

plot(shape)
```

This code worked and now fails. Error msg:
```

MethodError: no method matching PlotlyJS.GenericTrace(::String; xaxis="x", fill="tozeroy", yaxis="y", x=[0.0, 2.0, 2.0, 0.0, 0.0], showlegend=true, mode="lines", fillcolor="rgba(0, 154, 250, 1.000)", name="y1", line=Dict{Symbol,Any}(Pair{Symbol,Any}(:color, "rgba(0, 0, 0, 1.000)"),Pair{Symbol,Any}(:dash, "solid"),Pair{Symbol,Any}(:width, 1)), y=[0.0, 0.0, 1.0, 1.0, 0.0])
```

I checked out the latest masters from both Plots and PlotlyJS

thanks!

**Comment by apalugniok** [comment]
Hi @bbrunaud ,

I just ran your code in the REPL on the current release versions then Plots on master and PlotlyJS 0.6.4 and lastly both on master. Unfortunately/(or maybe Fortunately? 😆 ) the code you gave above ran without any errors.

**Comment by daschw** [comment]
Hi @bbrunaud, I can't replicate this either. Can you post the full error message?

**Comment by Kelvyn88** [comment]
Please @bbrunaud comment the status of your code. Did you resolve the error? 

Kelvyn
