### ISSUE TITLE
Inconsistent angle unit in polar plot of pgfplots backend

### ISSUE THREAD

**Issue by favba** [JuliaPlots/Plots.jl#1103]
In polar plots as in `plot(theta,r,proj=:polar)` pgfplots expects values of  `theta` in degrees while the other backends expect it in radians.

Example:
```julia
using Plots
pyplot()
th = linspace(0,2pi,128)
r = 1 .+ sin.(th)
plot(th, r, proj=:polar)
```
In other to reproduce the same plot using `pgfplots()` one must use `plot(linspace(0,360,128), r, proj=:polar)` .

**Comment by daschw** [comment]
Thanks a lot for reporting this!
