### ISSUE TITLE
Error bars are on top of points

### ISSUE THREAD

**Issue by nizhizhen** [JuliaPlots/Plots.jl#1106]
![2017-09-23 07-47-15](https://user-images.githubusercontent.com/19453340/30767866-8a8a74b4-a033-11e7-8c36-619415b47896.png)

**Comment by mkborregaard** [comment]
No support questions here, please.

**Comment by piever** [comment]
I'm not sure I understand what is meant with: "error bars are on top of points". Would the ideal solution be to have the marker in front of the error bar? Wouldn't that look strange when the error bar is smaller than the marker and ends up partly hidden from it?

**Comment by mkborregaard** [comment]
Yes, error bars should most definitely be behind markers in scatter plots (and in front for bar plots). IMHO it doesn't look strange when bars are smaller than the marker. Try to google some results or check fig. 2 and 4 here http://science.sciencemag.org/content/early/2013/09/04/science.1241917.full

**Comment by piever** [comment]
I see, so the only difference from the current situation is which one is on top (and why on earth they would be slightly off-centered...)

**Comment by mkborregaard** [comment]
Yes
