### ISSUE TITLE
Replace d by plotattributes

### ISSUE THREAD

**Issue by jw3126** [JuliaPlots/Plots.jl#1107]
# Replace d by plotattributes

The goal is to replace `d` by `plotattributes` inside `@recipes`. See [here](https://github.com/JuliaPlots/RecipesBase.jl/issues/10) for the original issue. Of course that is a change that breaks a lot of packages, so there was a [plan](https://github.com/JuliaPlots/RecipesBase.jl/pull/20) how to coordinate things. I started implementing it, but @mkborregaard wanted to wait [until julia version requirement is bumped to 0.7](https://github.com/JuliaPlots/Plots.jl/pull/929). However I probably won't have time for this when we upgrade to 0.7. So I propose here a better plan, where almost all work can be done now, without breaking anything.

## Step 1
- [x] Allow usage of both `d` and `plotattributes` inside `@recipes`. Without any deprecation warning. 
- [x] Tag a new release for RecipesBase.

I searched all packages that depend on `Plots` or `RecipesBase` and none of them used the word `plotattributes` inside a recipe. So this is a safe step.

## Step 2
- [x] Update `d` to `plotattributes` inside `Plots`.
- [x] Tag a new release for `Plots`.

Doing this after tagging Step 1 is important so all tests can pass.
After this step it is safe to use `plotattributes` instead of `d` in any other package.

## Step 3
PRs to all packages that depend on `Plots` or `Recipes` to replace `d` by `plotattributes`.
While a lot of packages depend on these, only a few are using `d`:

- [ ] DynamicMovementPrimitives
- [ ] ImplicitEquations
- [ ] LPVSpectral
- [x] PlotRecipes
- [x] StatPlots
- [ ] SymPy
- [x] TimeSeries
- [x] ValueHistories

## Step 4
- [ ] When upgrading to julia 0.7 add depwarning for usage of `d`.

## Step 5
- [ ] When upgrading to 1.0 remove `d` altogether.

Do the maintainers of `Plots` agree with this?

**Comment by daschw** [comment]
To me this sounds like a great plan!

**Comment by mkborregaard** [comment]
Yes, sounds good.
