### ISSUE TITLE
Change default view angle for GR backend

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1117]
Compare PyPlot's default:

![screenshot from 2017-09-29 20-22-03](https://user-images.githubusercontent.com/3345261/31042042-0f9b077a-a554-11e7-9fb8-e4bf5d949e92.png)

with GR's default:

![screenshot from 2017-09-29 20-22-13](https://user-images.githubusercontent.com/3345261/31042043-16ec2144-a554-11e7-880f-f78cf422481c.png)

It would be great if GR's dip angle was similar to that of PyPlot.

**Comment by mkborregaard** [comment]
I think this is an issue you could open in GR - I don't think we should add the extra machinery to make this consistent among backends.

**Comment by apalugniok** [comment]
#288 is an old suggestion to add a attribute to control this. The backend specific ways of setting the angle are already given in the issue for PyPlot, PlotlyJS. Maybe it'd be nice to have this and I'd be up for trying to do this.

Also I think GR sets the view angle here https://github.com/JuliaPlots/Plots.jl/blob/bcc2f089be9d453a13aee43287af53f2b290098a/src/backends/gr.jl#L753 ?

**Comment by juliohm** [comment]
Makes sense @mkborregaard , I will close the issue and re-open it in GR or maybe just ping @jheinen ?

**Comment by apalugniok** [comment]
I just checked the line that I linked does exactly what you I think you wanted. Should just be a case of changing the the constant values given to something that matches PyPlot.

**Comment by juliohm** [comment]
That is great @apalugniok , thanks for sharing it. Could we maybe fix it in Plots.jl meanwhile, if at some point GR "fixes" it too, that is perfect.

**Comment by mkborregaard** [comment]
@apalugniok if you are up for this, then great!

**Comment by apalugniok** [comment]
By this do you mean the full #288 or just changing the values for consistency?

**Comment by mkborregaard** [comment]
I mean what you'd like to contribute :-)

**Comment by apalugniok** [comment]
Oh cool, I'll open a quick fix value change PR and then slowly begin to work on the full thing 😄

**Comment by mkborregaard** [comment]
Closed in #1119
