### ISSUE TITLE
How to save an animated gif?

### ISSUE THREAD

**Issue by bensprung** [JuliaPlots/Plots.jl#1118]
Hi, the `@gif` macro works for me, but is there any way to specify where it saves? I'm on Windows and I get a message like

`INFO: Saved animation to C:\Users\Ben\AppData\Local\Temp\jl_9602.tmp.gif`

`savefig `seems to save only the last frame, even if I tell it to do` savefig("mygif.gif")`. 

Thanks!

**Comment by joshday** [comment]
From the docs in https://juliaplots.github.io/animations/, there is a `gif` function for saving an animation.  `savefig` will save the most recent plot, which is why it only saves the last frame.

**Comment by bensprung** [comment]
Oh I see. Thank you.

**Comment by mauriciogforero** [comment]
The link is broken

**Comment by daschw** [comment]
http://docs.juliaplots.org/latest/animations/

**Comment by mauriciogforero** [comment]
Great. Thanks!

**Comment by Vilin97** [comment]
I get an error on Windows when I do gif(anim, file_name). It complains about ffmpeg, specifically, the pallette.bmp file.
