### ISSUE TITLE
GR backend produces gks.svg on current directory

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1121]
Is there any way to avoid this?

**Comment by Non-Contradiction** [comment]
I met the same problem in using GR backend. And the problem seems to be solved by setting `ENV["GKS_FILEPATH"]`.

**Comment by juliohm** [comment]
@jheinen could you please confirm this variable needs to be manually set?

**Comment by juliohm** [comment]
This issue was solved somewhere down the road. Closing it. :+1:
