### ISSUE TITLE
Examples code looks weird in Docs

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/Plots.jl#1125]
As @mkborregaard pointed out in the Gitter channel, the examples code in the PlotDocs looks a little weird (at least in firefox) because some lines are too long (e.g. https://juliaplots.github.io/examples/pyplot/#subplots)
This can be fixed easily by keeping the line length of the examples code in https://github.com/JuliaPlots/Plots.jl/blob/master/src/examples.jl below 90 characters.

**Comment by mkborregaard** [comment]
After that we'll rerun the docs - they need the update :-)

**Comment by dexter816** [comment]
hey ! i want to work on this ,thanks :)

**Comment by mkborregaard** [comment]
Awesome!
