### ISSUE TITLE
Alpha ignored for RGBA images (PyPlot)

### ISSUE THREAD

**Issue by jgbos** [JuliaPlots/Plots.jl#1131]
Plots is ignoring the `alpha` value of an image.  Here is an example:

```julia
colorview(RGBA{Float64}, cat(1, rand(3, 10, 10), fill(0.1, 1, 10, 10)))
```
![index](https://user-images.githubusercontent.com/2148522/31184448-6adbb66a-a8f7-11e7-94c4-72ee34d018d6.png)

```julia
plot(colorview(RGBA{Float64}, cat(1, rand(3, 10, 10), fill(0.1, 1, 10, 10))))
```

![index](https://user-images.githubusercontent.com/2148522/31184469-790873fe-a8f7-11e7-94a1-101a3bd5bab2.png)

```julia
 - Plots                         0.12.4+            master
```
```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by mkborregaard** [comment]
I wonder if this isn't related to https://github.com/JuliaPlots/Plots.jl/issues/959

**Comment by daschw** [comment]
The `alpha` values of the RGBA colors should be considered somewhere here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/pyplot.jl#L732. It seems like imshow can handle RGBAs:
https://matplotlib.org/api/pyplot_api.html?highlight=matplotlib%20pyplot%20imshow#matplotlib.pyplot.imshow

**Comment by apalugniok** [comment]
Adding `alpha(c)` to https://github.com/JuliaPlots/Plots.jl/blob/aa22fd2ff2d569aee9f2862e32153c8ab9682125/src/backends/pyplot.jl#L739 seems to work.
