### ISSUE TITLE
Categorical Heatmaps maximum number of labels

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaPlots/Plots.jl#1140]
I followed this example from the documentation, but have a lot of categories,
```
Heatmap, categorical axes, and aspect_ratio
xs = [string("x",i) for i = 1:10]
ys = [string("y",i) for i = 1:4]
z = float((1:4) * (1:10)')
heatmap(xs,ys,z,aspect_ratio=1)
```

When xs or ys is long, the number of labels shown on the plot is truncated, this would be fine if my labels were interpolatable (like numbers) but they are discrete categories. Is there a way to get all the labels drawn on the figure?

**Comment by mkborregaard** [comment]
Yes, try and follow the directions at the bottom here https://github.com/JuliaPlots/Plots.jl/issues/792

**Comment by jpfairbanks** [comment]
Thanks that works! Followup question, how do I change the font sizes / spacing? I am using the pyplot backend if that is relevant.

**Comment by jpfairbanks** [comment]
tickfont=font(8, "Courier")?

**Comment by jpfairbanks** [comment]
Is there a place in the docs where I could add this?

**Comment by mkborregaard** [comment]
At the moment, most of these things are just documented in https://juliaplots.github.io/attributes - you can find this under "axes" below "magic arguments". But it'd be nice at some point to add some more comprehensive whole pages showing how to do various tasks. 
Are you OK with closing this issue?

**Comment by mkborregaard** [comment]
I've closed it now, but happy to reopen if you'd like me to. Also, if you think the place in the docs should be changed it'd be nice with a suggestion - always a key place to improve!
