### ISSUE TITLE
Plots.jl internal performance and convertToAnyVector

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#1147]
One thing I have been wondering about is whether `convertToAnyVector` is necessary and how much of a performance impact this has. Plots.jl after compilation isn't necessarily slow, but it could be improved and this is probably the biggest offender (maybe the untyped dictionaries being the other). Is there a good way to test how much of an impact this is? And is there a good explanation why it went all the way to untyped?

**Comment by mkborregaard** [comment]
Have you tried profiling precompilation, or is this based on your knowledge that precompilation doesn't run well when types are hard to infer?

@tbreloff is the one to answer the other, important, question.

**Comment by ChrisRackauckas** [comment]
>Have you tried profiling precompilation, or is this based on your knowledge that precompilation doesn't run well when types are hard to infer?

When it can precompile it will precompile for `Any` vectors, so this isn't an issue. It shouldn't change precompilation, just compiled runtime.

**Comment by BeastyBlacksmith** [comment]
that was removed in https://github.com/JuliaPlots/Plots.jl/pull/2511
