### ISSUE TITLE
Two problems with greek letters, using GR

### ISSUE THREAD

**Issue by improbable22** [JuliaPlots/Plots.jl#1150]
Here the title is truncated to "before f", and the space after \beta is swallowed: 
```
using Plots
plot(rand(20), lab="a = \\beta = c", title="before f(\\theta) and after")
```
Added -- this was in IJulia / Jupyter. The space after \beta is fine if I save a PDF, but if I save as SVG then it has the same problem: `savefig("test.svg")`. The truncation of the title however is the same, and only occurs with round brackets.  

The following works, but now title & label are done by Latex, in its usual computer modern font: 
```
plot(rand(20), lab="\$ a = \\beta = c \$", title="\$ \\mathrm{ before \\ }f(\\theta)\\mathrm{ \\ and \\ after} \$")
```
This syntax only seems to work (or be needed) with `gr()`. With background `pyplot()` or `plotly()` I can instead simply type the letters, and this now works:
```
plot(rand(20), lab="a = β = c", title="before f(θ) and after")
```

Aside, perhaps, but how hard would it be to translate "β" into "\\beta" so that GR could take the same input as the others?

**Comment by mkborregaard** [comment]
You mostly need LaTeXStrings to pass LaTeX correctly. I wonder if this is actually missing from the docs?

So,
```julia
using LaTeXStrings, Plots
plot(rand(20), lab=L"a = \beta = c", title=L"before\;f(\theta)\;and\;after")
```

**Comment by mkborregaard** [comment]
If you want a GR-specific change, it may make sense to open the issue on GR? (it could be a Plots-backend thing, though - worth checking)

**Comment by improbable22** [comment]
Thanks, I did also try LaTeXStrings, which is cleaner than what I wrote... but still renders the whole title in Computer Modern, which I'd like to avoid. 

Sorry probably I should have made an issue on GR.jl directly -- I will do that now.
