### ISSUE TITLE
Example 24 markers stuck in xz-plane for GR

### ISSUE THREAD

**Issue by apalugniok** [JuliaPlots/Plots.jl#1152]
The example code from the docs gives this for GR.
```
n = 100
ts = linspace(0,8π,n)
x = ts .* map(cos,ts)
y = (0.1ts) .* map(sin,ts)
z = 1:n
plot(x,y,z,zcolor=reverse(z),m=(10,0.8,:blues,stroke(0)),leg=false,cbar=true,w=5)
plot!(zeros(n),zeros(n),1:n,w=10)
```

![ref24gr](https://user-images.githubusercontent.com/22132297/31338646-0a723ede-acf8-11e7-8412-e0b3f42442c3.png)

The above was made on the current Plots.jl master. I have tried the current release of Plots.jl and there is no change, the same occurs for both the master and release of GR.jl.

**Comment by mkborregaard** [comment]
This appears to have been caused by #1110 . Also, on my system, the gridlines change between green and blue. It's a little strange that this wasn't caught by Travis - I did think we were testing plot 24?

**Comment by apalugniok** [comment]
Removing `zcolor` fixes the markers.

**Comment by mkborregaard** [comment]
@daschw would you be OK with taking a look at this?

**Comment by apalugniok** [comment]
I reset a git branch to just before the #1110 and the issue still persisted but reseting to before 13111b377996961fee5e0ae2943aa7bccf6224b5 and then the issue was gone.

**Comment by daschw** [comment]
I was wondering how #1110 could have caused this because I did not touch markers there. Thanks @apalugniok for the hint.
I can look into this. It's really weird that travis did not fail! We are testing all examples for GR.

**Comment by apalugniok** [comment]
Unfortunately I don't think it's that one reseting to that commit doesn't break anything 😟  For me it breaks on 5f8486536561746b73823065ac033896ed220082.
