### ISSUE TITLE
y_scale works for identity but not work for log10, ln, log2

### ISSUE THREAD

**Issue by gaomrx** [JuliaPlots/Plots.jl#1154]
Using pyplot as the backend here, identity option works fine
![image](https://user-images.githubusercontent.com/6380557/31349324-c574d6d6-acf0-11e7-8b59-9385e713f844.png)

the other y_scale options were working a few days ago 

![image](https://user-images.githubusercontent.com/6380557/31349367-f3e8b4d8-acf0-11e7-93fb-89ce5845da4a.png)

**Comment by gaomrx** [comment]
Here is the remainder of the stack trace
![image](https://user-images.githubusercontent.com/6380557/31349437-47e22a9c-acf1-11e7-8a20-aca4643438b6.png)

**Comment by apalugniok** [comment]
What is the y data like the first two lines look exactly like a negative value is being passed into the `log10()`
```
log10(-1.0)
ERROR: DomainError:
log10 will only return a complex result if called with a complex argument. Try log10(complex(x)).
Stacktrace:
 [1] nan_dom_err at ./math.jl:300 [inlined]
 [2] log10(::Float64) at ./math.jl:419
```

**Comment by gaomrx** [comment]
you are right, some of the values are very tiny but negative, thanks for pointing that out

**Comment by apalugniok** [comment]
Glad it helped 😄
