### ISSUE TITLE
Legends do not reflect all changes for plot/scatter

### ISSUE THREAD

**Issue by tpoisot** [JuliaPlots/Plots.jl#1159]
The following code:

~~~ julia
X = rand((10, 2))
plot(X, c=:grey, marker=([:circle :diamond], 10, stroke(1,:black), :white))
scatter(X, c=:grey, marker=([:circle :diamond], 10, stroke(1,:black), :white))
~~~

will generate these two plots:

![screenshot from 2017-10-10 10-47-33](https://user-images.githubusercontent.com/579329/31393056-cb6d18ce-ada8-11e7-8a8b-e76a9cb35306.png)

![screenshot from 2017-10-10 10-47-48](https://user-images.githubusercontent.com/579329/31393072-d652bef6-ada8-11e7-9626-fb64aab08193.png)

I think that when adding markers to a `plot`, this should be reflected in the legend. My current workaround is to call plot without a legend, then scatter with a legend (but it's not optimal). Or alternatively, when adding line styling information to scatter, it should be reflected in the actual plot. What am I missing?

As a side note, a surprising number of defaults (and behaviors) in `Plots.jl` assume that there will be some color in the plots, which is not true for publication-ready figures.

**Comment by mkborregaard** [comment]
This is fixed on master:
<img width="608" alt="skaermbillede 2017-10-10 kl 16 54 43" src="https://user-images.githubusercontent.com/8429802/31393324-c3bb54a0-addb-11e7-86bd-1d212b528b3f.png">

**Comment by mkborregaard** [comment]
With regards to the defaults, the easiest would be to make a `:nocolor` theme in PlotThemes.jl. It's really easy to define themes if you feel like trying it out. I assume, though, that you'd want the linestyle to change automatically among series once the colors don't? That'd be a bit more involved. Could you open a separate issue for this, possibly on PlotThemes?

**Comment by mkborregaard** [comment]
As a final aside, in my experience the number of journals that don't want colors is (thankfully) dwindling :-)

**Comment by tpoisot** [comment]
I think being able to make good black & white figures is a vastly under-rated skill (but I have read Edward Tufte before Nathan Yau, so...).

I like the idea of themes, and will look a bit more into that. Is it anything like pgfplots "cycles"?
