### ISSUE TITLE
no PyPlot gui in jupyter and Julia 0.6

### ISSUE THREAD

**Issue by carlosbrody** [JuliaPlots/Plots.jl#1165]
I am using jupyter (version 4.1.0), and under a Julia 0.5.2 kernel, the following works fine and brings up the PyPlot gui with a plot in it:

> using Plots
> @printf("VERSION is %s\n", VERSION)
> pyplot()
> Plots.gui(plot(1:0.1:10, sin.(1:0.1:10)))

But when I change kernel to Julia 0.6 and run the exact same code (again, from a Jupyter cell), I get nothing. No error message, no inline plot, no gui, just nothing.

If I run the same code from a Julia 0.6 REPL in the terminal, then I **do** get the gui and the plot.  So it is not just Julia 0.6-- it something specific to the combination of Jupyter and Julia 0.6.

Thanks!!

**Comment by mkborregaard** [comment]
This is due to https://github.com/JuliaPlots/Plots.jl/pull/1030 , which deactivated the pyplot gui in ijulia (the version of Plots running under 0.5.2 is older than this PR). It's possible that this should be reverted or reimplemented if not using the gui is often a problem in jupyter.
