### ISSUE TITLE
GR does not plot data over full width

### ISSUE THREAD

**Issue by dpsanders** [JuliaPlots/Plots.jl#1166]
<img width="696" alt="screen shot 2017-10-11 at 9 53 52 am" src="https://user-images.githubusercontent.com/191822/31448504-3603d436-ae6a-11e7-849a-6a9f467d5b5c.png">

```
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```
```
julia> Pkg.status("GR")
 - GR                            0.23.0
```

**Comment by mkborregaard** [comment]
What's your Plots version - it is reminiscent of https://github.com/JuliaPlots/Plots.jl/issues/1101 which was fixed recently.

**Comment by dpsanders** [comment]
Just updated to `Plots` 0.13.1, but no improvement.

**Comment by mkborregaard** [comment]
Thanks!

**Comment by dpsanders** [comment]
Fixed by the latest GR update!
