### ISSUE TITLE
Unicode fonts on GR-backend

### ISSUE THREAD

**Issue by jaakkor2** [JuliaPlots/Plots.jl#1170]
With Plots.jl 0.13.1, GR.jl 0.24.0, GR.version() 0.27.0 it is great that `yformatter=:scientific` almost works. On Windows I get bad fonts.  Also, axis labels do not show unicode fonts (but can be worked around by `\\mu` for μ, for example.

![gr](https://user-images.githubusercontent.com/7318249/31490210-6ed21230-af43-11e7-8294-43c68e6fccea.png)

```
using Plots
gr()
x = linspace( 0.0,5.0,50 )
plot( plot( x, [ x, x.^2 ], grid = true, lab=[ "foo" "bar" ], color=[ :cyan :purple ], xaxis="Length (μm)", yaxis="y-value", lw=2 ), plot( x, 1e6*[ exp.(x), exp.(x.^2) ], grid = true, lw = 1, yformatter=:scientific, leg = false, yaxis="my yaxis label" ), layout=(2,1) )
```

**Comment by improbable22** [comment]
Perhaps of interest, I had a go at making GR replace β with `\\beta` etc automatically here: https://github.com/jheinen/GR.jl/pull/78 . This could also be done within Plots I'm sure.

**Comment by jaakkor2** [comment]
Closing this issue, as now `yformatter=:scientific` works.  The unicode issue still exist and is open here
https://github.com/JuliaPlots/Plots.jl/issues/791
