### ISSUE TITLE
Weighted histogram is not working

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPlots/Plots.jl#1173]
When trying a command
```julia
histogram(rand(100), weightss=rand(100))
```
I get errors
```
MethodError: no method matching fit(::Type{StatsBase.Histogram{Int64,N,E} where E where N}, ::Tuple{Array{Float64,1}}, ::Array{Float64,1}, ::Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}; closed=:left)
Closest candidates are:
  fit(::Type{StatsBase.Histogram{T,N,E} where E where N}, ::Tuple{Vararg{AbstractArray{T,1} where T,N}}, ::StatsBase.AbstractWeights{W,T,V} where V<:AbstractArray{T,1} where T<:Real, ::Tuple{Vararg{AbstractArray{T,1} where T,N}}; closed) where {T, N, W} at ${HOME}/.julia/v0.6/StatsBase/src/hist.jl:302
  fit(::Type{StatsBase.Histogram}, ::Any...; kwargs...) at ${HOME}/.julia/v0.6/StatsBase/src/hist.jl:352
  fit(::StatsBase.StatisticalModel, ::Any...) at ${HOME}/.julia/v0.6/StatsBase/src/statmodels.jl:92 got unsupported keyword argument "closed"
```
Julia version: 0.6
Plots version: 0.12.3

I have not found any description how it is supposed to work. Intuitively, I expect similar format as matplotlib: https://matplotlib.org/1.3.1/examples/pylab_examples/histogram_demo_extended.html

There are no errors for ``histogram(rand(100), weights)``
But I do not understand the output.

The weights were discussed in the issue #198

**Comment by mkborregaard** [comment]
This is a bug - there's a PR to fix it here: #1174 You could try it out if you can be bothered, or suggest a test? I think we should include the `weights` keyword in one of the histograms in our tests.

**Comment by mmikhasenko** [comment]
I would like to test it but my julia 0.6 conflicts with Plots master. The latter requires Base >= 0.2.3.
What do you mean with suggest test? I can come up a simple practical example where weights are required. Is it what is needed?

**Comment by mkborregaard** [comment]
I don't think it's needed in fact.
Can you say what the issue is with the RecipesBase conflict? That doesn't sound good.

**Comment by mmikhasenko** [comment]
I might have misunderstood error message, I got doing a checkout.
Although, here it is
```
Pkg.checkout("Plots")
INFO: Checking out Plots master...
INFO: Pulling Plots latest master...
WARNING: julia is fixed at 0.6.0-rc2.0 conflicting with requirement for Plots: [0.6.0,∞)
ERROR: fixed packages introduce conflicting requirements for RecipesBase: 
         Plots requires versions [0.2.3,∞) [none of the available versions can satisfy this requirement]
       available versions are 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.1.0 and 0.2.0
```

**Comment by mkborregaard** [comment]
OK, that's because you're not on julia 0.6, but a release candidate. That will prevent you from installing updated versions of Plots (and quite a few other packages I should think). You should update with the binary from here: https://julialang.org/downloads/

**Comment by mmikhasenko** [comment]
It works now, thanks a lot for the quick response.
