### ISSUE TITLE
GR: showing colorbar displaces series_annotations down below plot

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1179]
With GR, activating the colorbar shifts series_annotations outside the subplot pane.
```julia
scatter(1:5, rand(5), series_annotations = text.(1:5), marker_z = 1:5)
```
<img width="595" alt="skaermbillede 2017-10-15 kl 18 17 24" src="https://user-images.githubusercontent.com/8429802/31586772-ec0d80ec-b1d5-11e7-8abb-4f56af77d619.png">

Deactivating the colorbar fixes it.
```julia
scatter(1:5, rand(5), series_annotations = text.(1:5), marker_z = 1:5, colorbar = false)
```
<img width="593" alt="skaermbillede 2017-10-15 kl 18 17 52" src="https://user-images.githubusercontent.com/8429802/31586774-efcadc3e-b1d5-11e7-8592-06109ecbd367.png">

Works on the other backends.

@daschw @jheinen

**Comment by daschw** [comment]
Maybe somehow also related, although not as messed up as your example: Colorbar messes up the aspect ratio:
```julia
x, y = Plots.unzip(Plots.partialcircle(0, 2π, 100))
plot([Shape(x + i, y + j) for i in 0:2:2 for j in 0:2:2], aspect_ratio = true)
```
![gr_aspect_ratio](https://user-images.githubusercontent.com/16589944/31618165-75d261c4-b291-11e7-90b2-381661b3bc65.png)
vs.
```julia
x, y = Plots.unzip(Plots.partialcircle(0, 2π, 100))
plot([Shape(x + i, y + j) for i in 0:2:2 for j in 0:2:2], aspect_ratio = true, fill_z = true)
```
![gr_colorbar_aspect_ratio](https://user-images.githubusercontent.com/16589944/31618190-8df622f4-b291-11e7-81c8-7c77afe5d1e6.png)
