### ISSUE TITLE
Plots generated by Documenter contain GKS warning

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1182]
Could you please confirm I am doing everything correctly?

Check this warning message:

```
GKS: can't open display on ""
     Is your DISPLAY environment variable set correctly?
     Did you enable X11 and TCP forwarding?

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
```
It is present in every plot on my documentation with GR, this is one example: http://juliohm.github.io/GeoStats.jl/latest/plotting.html

**Comment by daschw** [comment]
I wouldn't know, what to do differently. Maybe @jheinen has an idea?

**Comment by jheinen** [comment]
In a headless environment, you probably have to disable graphics output in GR:
```
 ENV["GKSwstype"] = "100"
```
Similar thing had to be done in https://github.com/JuliaPlots/Plots.jl/issues/1076

**Comment by juliohm** [comment]
Indeed @jheinen! I had set the variable on my runtests.jl, but forgot to set it on my docs/make.jl script.
