### ISSUE TITLE
Latex text at y label is not rotated

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPlots/Plots.jl#1191]
```julia
using Plots
gr()
plot(
x->x^3-8*x^2, 0, 10,
  xlab="\$s_{\\pi\\pi}(\\textrm{GeV}^{2})\$",
  ylab="\$\\mathrm{d}\\sigma/\\mathrm{d}s_{\\pi\\pi}\$"
)
```
![test](https://user-images.githubusercontent.com/22725744/31744056-9c32ef8c-b45d-11e7-9164-e6c061ef9201.png)

Although the label ```ylab="d\\sigma / ds_{\\pi\\pi}"``` is aligned correclty it does not look nice enough.
Obviously, font differs from the latex xlabel.

[test.pdf](https://github.com/JuliaPlots/Plots.jl/files/1396454/test.pdf)

**Comment by t-bltg** [comment]
This appear to be fixed.
