### ISSUE TITLE
Font size change leads to font rotation

### ISSUE THREAD

**Issue by y-nkt** [JuliaPlots/Plots.jl#1194]
Dear great developers of Plots.jl,

I tried to change font sizes for GR frontend, but the fonts of xlabel and legend are rotated.
Strangely, the font of ylabel has no problem.
I think this may be a bug. 

Thank you for your support,

Minimum code:
```
using Plots
gr()
fnt = Plots.font("sans-serif", 14.0)

plot(sin, guidefont=fnt, legendfont=fnt )
ylabel!("AAA")
xlabel!("BBB")
savefig("test.png")
```
result:
![image](https://user-images.githubusercontent.com/6076710/31766806-bec4f9e0-b503-11e7-85b5-0916a6cd865e.png)

My env:
Julia v0.60 on Ubuntu 16.04.3 LTS
"Plots"=>v"0.13.1",
"GR"=>v"0.24.0",

**Comment by daschw** [comment]
To change the font size you have to pass an Integer `fnt = Plots.font("sans-serif", 14)`. Floats are interprated as the rotation angle.

**Comment by y-nkt** [comment]
Thank you for your very quick reply. 
Now, I've understood that arguments of Plots.font are classified as types
in components.jl. It helps me a lot!

**Comment by tamasgal** [comment]
Ah, this tricked me actually. I started to write an issue and luckily landed here ;)
