### ISSUE TITLE
plot(img, ylims=(-3,3)) produces unexpected direction

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Plots.jl#1196]
The attached is weird to me that the negative y axis is above the positive y axis. 

<img width="739" alt="untitled" src="https://user-images.githubusercontent.com/1229737/31791618-0f27bcf8-b511-11e7-809d-c0a2d28f6416.png">

Even weirder is that reversing the order of arguments produces something not at all predictable:

<img width="809" alt="untitled 2" src="https://user-images.githubusercontent.com/1229737/31791655-352601b2-b511-11e7-98d2-069f2445546b.png">

In my actual usage case, I'm trying to put a phase portrait of a complex-valued function and so I really want the positive complex plane on top.

**Comment by apalugniok** [comment]
```
plot(img)
```
![light](https://user-images.githubusercontent.com/22132297/31792994-d40699a0-b515-11e7-8d05-35cdb2d745a5.png)
I'd hazard a guess that the img[1,1] element is actually the top left corner of the image. So if the ticks follow the indices of `img` the first case make sense.

Not sure how to get the behaviour you'd like apart from the tedious way of specifying your own ticks 😟

**Comment by dlfivefifty** [comment]
But that behaviour makes it useless for combining background images with plots on top.

**Comment by dlfivefifty** [comment]
I think the `plot(img)` behaviour is fine, but when you specify `xlims` or `ylims` it should do what you tell it to do: `ylims = (-3,3)` means -3 on the bottom and 3 at the top, while `ylims = (700, 0)` should give back the same behaviour as the default.

**Comment by mkborregaard** [comment]
That's how images are defined, though, starting at the upper left corner. Whereas heatmaps start at the lower left corner. The latter is standard everywhere, except for pyplot that transposes matrices in heatmap...
Could you use `yflip = true` on the plots you put on top?

**Comment by mkborregaard** [comment]
You could also perhaps use `twinx()` to put your plot on top on an alternative y axis?

**Comment by apalugniok** [comment]
I tried `yflip = true` and it seems broken but `xflip` works fine.

**Comment by dlfivefifty** [comment]
I know that’s how images are defined, but specifying ylims is telling it to throw out the original coordinate system and use the specified coordinate system.

As it is now, I can’t see any reasonable usage for ylims. Explain to me how you would draw a half circle in the positive y axis on top of an image in the current convention?

**Comment by dlfivefifty** [comment]
A reasonable alternative is to flip the image if ylims is ordered. 

Though this seems unnecessary since specifying ylims is telling Plots to throw out the original coordinate system, so it’s not clear why it would throw out the coordinate system but insist on preserving orientation.

**Comment by mkborregaard** [comment]
I don't feel strongly, my guess is the current is the default behaviour because noone have special-cased ylims for images. If you have a use case you're welcome to put together a PR implementing your suggested behaviour.

**Comment by dlfivefifty** [comment]
I'll put together a pull request. Where are the `yticks` set in Plots.jl?

**Comment by dlfivefifty** [comment]
PS I found a work around:
```julia
plt = plot(img[end:-1:1,:], xlims=(-1,1), ylims=(-1,1))
plt.subplots[1][:yaxis][:flip] = false
plt
```
So I just need to figure out where the flip is set to true, and have it conditional on the ordering of `ylims`.

**Comment by dlfivefifty** [comment]
Is there a way to do set flip to false in a recipe? That would help me at least fix my lecture slides on Monday.

**Comment by mkborregaard** [comment]
Does `yflip := false` not work?

**Comment by dlfivefifty** [comment]
Doesn't look like it.
<img width="802" alt="untitled" src="https://user-images.githubusercontent.com/1229737/31855872-cf290a8e-b6ab-11e7-8034-878d4dc6dfbf.png">

**Comment by mkborregaard** [comment]
Huh, that's annoying. Until we get that looked at, could you use `twinx()`?

```julia
plot(testimage("lighthouse"), axis = false)
plot!(twinx(), cumsum(randn(500)), c = :red)
```
<img width="567" alt="skaermbillede 2017-10-22 kl 11 16 30" src="https://user-images.githubusercontent.com/8429802/31860461-a5169788-b71a-11e7-992d-ad38c0479cb7.png">

**Comment by dlfivefifty** [comment]
Hmm, possibly. For the time being, I'll just change my `@userplot` to a function, and use either `twinx` or the previous work around I found.

**Comment by apalugniok** [comment]
I think this can be closed since limits now crop the image and for plotting data over images you can set `yflip = false` and resize the image as in #1362.
