### ISSUE TITLE
LaTeX label with logarithmic axis

### ISSUE THREAD

**Issue by y-nkt** [JuliaPlots/Plots.jl#1197]
Dear great developers,

I found strange rotation for LaTeX label with logarithmic axis.

How can I resolve this?

```
using Plots
plot(abs.(rand(10)), xlab="\$s_{\\pi\\pi}(\\textrm{GeV}^{2})\$",
              ylab="\$\\mathrm{d}\\sigma/\\mathrm{d}s_{\\pi\\pi}\$")
savefig("test.png")
plot(abs.(rand(10)), xlab="\$s_{\\pi\\pi}(\\textrm{GeV}^{2})\$",
       ylab="\$\\mathrm{d}\\sigma/\\mathrm{d}s_{\\pi\\pi}\$", yaxis = :log10)
savefig("test2.png")
```

test.png:
![test](https://user-images.githubusercontent.com/6076710/31809663-ad7289cc-b5b3-11e7-9a52-45c069917880.png)

test2.png:
![test2](https://user-images.githubusercontent.com/6076710/31809665-b14fae1c-b5b3-11e7-9284-36eaf6b5bc33.png)

My env:
Julia v0.60 on Ubuntu 16.04.3 LTS
"Plots"=>v"0.13.1"

**Comment by BeastyBlacksmith** [comment]
thats fixed at least in Plots1.1.1
