### ISSUE TITLE
Resizing window does not resize plot (using GR backend)

### ISSUE THREAD

**Issue by nouyang** [JuliaPlots/Plots.jl#1200]
Using code

    x = 1:10; y = rand(10,2) # 2 columns means two lines
    plot(x,y)

I get a plot. If I try to resize the window, the window resizes, but the plot does not, and white padding is just added around the plot instead.

### screenshots
gr plot of 2 lines

![gr plot of 2 lines](https://user-images.githubusercontent.com/764681/31864187-339f4d90-b727-11e7-9c96-29e7d238f5be.png)

rescaled window of gr plot of 2 lines

![rescaled window of gr plot of 2 lines](https://user-images.githubusercontent.com/764681/31864177-0968130e-b727-11e7-907b-268bc746e2d1.png)

### system config

ubuntu 16.04, cinnamon windows manager, 
julia version Version 0.6.0

    julia> Pkg.status("Plots.jl")
     - Plots                         0.12.4

**Comment by mkborregaard** [comment]
Yes, this a known issue with GR (not Plots). They're working on fixing it!

**Comment by nouyang** [comment]
Ach, well then. Thanks for the quick response, that's unfortunate. (I'd almost rather have an `rtfm` response).

gr() is noticeably faster than pyplot() for me (maybe, half a second vs 5 seconds, on a very small number of lines, so I will stick with gr() and subscribe to [presumably some issue in the gr github repo]. 

(probably I should just write less ridiculous code anyhow).

**Comment by mkborregaard** [comment]
The fix atm is to use the `size` keyword to get the size you want. It's also more reproducible.

**Comment by nouyang** [comment]
GUI's are convenient though... the use case is, say you are presenting a plot you made to your boss, and they ask "can you resize the window so we can actually see these data points", and then you spend the next 30 seconds trying to find the terminal you spawned the window from... :(

**Comment by mkborregaard** [comment]
Sure.
