### ISSUE TITLE
Hanging gr() window

### ISSUE THREAD

**Issue by nouyang** [JuliaPlots/Plots.jl#1201]
Hi,
When using the gr() backend, I occasionally get a window I cannot seem to close, unless I close out of Julia entirely. (Usually, `closeall()` is sufficient). 

I've tried: `julia > closeall()`, ctrl-w, alt-f4, ctrl-q

![hanging gr() window](https://user-images.githubusercontent.com/764681/31864243-4168ebec-b728-11e7-93e9-2ae7f241f23c.png)

Apologies if this is in the docs somewhere and I missed it. I haven't used the other backends enough to know if I, personally, would experience this in other backends.

Thanks!

**Comment by mkborregaard** [comment]
This is also a GR issue. You could report it on GR.jl, but I believe this is well known as well.

**Comment by nouyang** [comment]
Can do, thanks for lending your gr() expertise!
For my reference
[ [this is a placeholder: I cannot find the specific issue at the moment](https://github.com/jheinen/gr/issues)
