### ISSUE TITLE
scientific format doesn't work from v0.12.3 (GR)

### ISSUE THREAD

**Issue by y-nkt** [JuliaPlots/Plots.jl#1203]
10^i along y axis is not properly formatted from Plots.jl v.0.12.3 (GR).

Please see the following code:

```
using Plots
gr()
plot(abs(rand(10)), yaxis=(:log10, (1e-3,1e3)))
savefig("gr.png")
```

v0.12.2:
![plots_v0 12 2](https://user-images.githubusercontent.com/6076710/31921325-d3304cc8-b8a9-11e7-912e-0665fc780dcf.png)

v0.12.3:
![plots_v0 12 3](https://user-images.githubusercontent.com/6076710/31921333-d7e95764-b8a9-11e7-8e5c-b3a3cc02208e.png)

Thank you for your development,

**Comment by y-nkt** [comment]
I'm very sorry that I missed the following:

"GR no longer automatically handles _ and ^ in texts"
https://github.com/JuliaPlots/Plots.jl/releases/tag/v0.12.3

**Comment by mkborregaard** [comment]
This is a bug created by that change. Thanks for reporting.

**Comment by apalugniok** [comment]
A hacky way would be to add "\\ " to the end of every tick so that it gets dispatched to `GR.textext()` instead of `GR.text()`.

**Comment by mkborregaard** [comment]
not too hacky I think

**Comment by apalugniok** [comment]
I'll try it out and see how it behaves.
