### ISSUE TITLE
savefig produces low quality plots with GR

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1204]
There's probably something wrong with the settings. It is easy to see in all the PlotReferenceImages, e.g. 
![ref15](https://user-images.githubusercontent.com/8429802/31926965-26831d28-b892-11e7-8e50-d89fe9f7d093.png)

cc @jheinen

**Comment by daschw** [comment]
@jheinen do you see a way, how the quality of GR figures, saved with savefig in Plots, could be improved?

**Comment by jheinen** [comment]
@daschw : I made a PR - #1318 should fix the problem

**Comment by jheinen** [comment]
@daschw : It seems that we have to upload new reference images.

**Comment by jheinen** [comment]
@daschw : I implemented the latter (see `PLOTS_TEST` in runtest.jl)

**Comment by mkborregaard** [comment]
Fixed in #1318
