### ISSUE TITLE
marker_z does not work properly for 3D scatter plot

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaPlots/Plots.jl#1205]
Specifying marker colors/shading via marker_z works for 2D scatter plot, but not 3D scatter plot. See, e.g.,
```
scatter(1:10,1:10,marker_z=0.9:-0.1:0.0) # correct with 2D scatter!
scatter(1:10,1:10,1:10,marker_z=0.9:-0.1:0.0) # incorrect with 3D scatter!
```
In 3D, the color bar indicates the range of the z-coordinates, not the marker colors/shading. I want to use colors/shading of the markers according to an input array specified by ```marker_z```, not the z-coordinates of the marker positions. ```surface``` plot with ```fill_z``` does exactly this (although for 3D surface objects, not for 3D scattered points) as we discussed at #640, #641. 
I think this functionality is quite important.
Thanks!
BVPs

**Comment by BoundaryValueProblems** [comment]
In fact, I found that this is a specific problem of the GR backend. I should have added the ```clims``` argument as follows:
```
scatter(1:10,1:10,1:10,marker_z=0.9:-0.1:0.0,clims=(0.0,0.9))
```
Then, it worked as I intended under the pyplot and plotlyjs backends. But it didn't work at all under the gr backend. Hence, this is a GR specific problem again as #1219.

**Comment by mkborregaard** [comment]
It should also work for the other backends without having to use clims.

**Comment by BoundaryValueProblems** [comment]
@mkborregaard you are correct. It should work without specifying clims. That is the case for 2D scatter plot: no need to specify clims. Currently, for 3D scatter plot, the z-coordinates and marker_z color values are still mixed up in pyplot, plotlyjs, and gr. So, I was wrong: it's _not_ a gr specific problem. However, gr backend behaves particularly bad compared to the other two since even with clims, it doesn't work at all.
