### ISSUE TITLE
PlotPane problem

### ISSUE THREAD

**Issue by aarcampos** [JuliaPlots/Plots.jl#1207]
Hi all,

I'm brand new to Julia and Juno. I'm trying to plot a simple linear function but instead the graph showing up in Juno I get a graph in my browser. I see a message saying "PlotPane turned off. The plotly and plotyjs backends cannot render in the PlotPane due to javascript issues".

Could anyone please help me out ?

Peace

**Comment by lnacquaroli** [comment]
Check out the Juno/Atom section to see if it helps: http://docs.juliaplots.org/latest/output/

**Comment by mkborregaard** [comment]
:-O that section of the manual is out-of-date, plotlyjs normally shows wonderfully.
@aarcampos most of the time when people have problems with this it's a version thing. What's `Pkg.status(["Plots", "Juno", "PlotlyJS"])` and `versioninfo()`?

**Comment by daschw** [comment]
@aarcampos I suspect you are using the Plotly backend, which always shows the plots in a browser window (right?). You can check your current backend e.g. with `backend()` after `using Plots`.
Plots supports a variety of other backends (GR, PyPlot, PlotlyJS, ..., see http://docs.juliaplots.org/latest/backends/), which all plot to the Juno plot pane. To use them you have to install them (e.g. `Pkg.add("GR")` and call them after `using Plots` with e.g. `gr()` or `pyplot()`, ...

**Comment by aarcampos** [comment]
@mkborregaard, thank you for your time,  my Pkg.status() and version info are the following:

Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH Haswell)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

Plots                         0.13.1
Juno                          0.3.1 
PlotlyJS                      0.7.0

@daschw, your sugestion has worked for me. Now I get graphs in my plotpane using gr() as my backend. Thank you for this advice!

**Comment by ChrisRackauckas** [comment]
@pfitzseb can this warning get changed to only Plotly? I can't find where it is.

**Comment by ChrisRackauckas** [comment]
Oh, it lives in Plots and this has already been handled on master. I'll close this.
