### ISSUE TITLE
heatmap without a colorbar

### ISSUE THREAD

**Issue by GaborOszlanyi** [JuliaPlots/Plots.jl#1211]
I am using Plots + the included Plotly backend 
with Julia 0.6.0 on Windows.

Whatever I do, the following code produces a colorbar:
```
z = rand(32,32)
heatmap(z, size=(600,600), colorbar=false)
heatmap(z, size=(600,600), colorbar=:none)
```
How can I get a heatmap without a colorbar?

**Comment by apalugniok** [comment]
Thanks for reporting this!

This is not how it should be but `legend = :none` will get rid of the colorbar. 

Issue is that Plots uses the wrong Plotly attribute to hide the colorbar. The correct attribute is currently controlled by `legend`. This is a bug, I'll try to fix this when I get time for now the above should work 😄

**Comment by GaborOszlanyi** [comment]
Thanks for the trick!
And looking forward to the real solution.
