### ISSUE TITLE
PGFPlots legend problem with groupedbar

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaPlots/Plots.jl#1215]
PGFPlots does not correctly show the series in the legend with `groupedbar` from StatPlots.jl. The legend only shows black lines for each series instead of colored rectangles.
Code to reproduce:
```julia
using Plots, StatPlots
pgfplots()
groupedbar(rand(10,3), bar_position = :stack)
```
Output:
![groupedbar](https://i.imgur.com/ApV7A4g.png)

**Comment by mkborregaard** [comment]
It appears pgfplots can do this (from the pgfplots manual)

![skaermbillede 2017-10-31 kl 16 06 54](https://user-images.githubusercontent.com/8429802/32231332-960e4488-be55-11e7-9e16-c2060e8fc8ef.png)

**Comment by mkborregaard** [comment]
Any ideas for how to implement this @pkofod ? :-)

**Comment by pkofod** [comment]
Ill look later tonight.

**Comment by SebastianM-C** [comment]
Thank you very much!
