### ISSUE TITLE
display do not work in script

### ISSUE THREAD

**Issue by jingpengw** [JuliaPlots/Plots.jl#1217]
everything works nicely in IJulia and REPL, but the `display` do not work in script.

this is my little test script
```
using Plots
#pyplot()
#gr()
#plotlyjs()
#pgfplots() not tested due to installation issue
# inspectdr() not tested due to installation issue

p = plot(Plots.fakedata(50,5),w=3)
display(p)
```
I get a warning: `WARNING: _show is not defined for this backend. m=text/plain`
not sure this is related or not.

I am still using Julia 0.5
```
julia> versioninfo()
Julia Version 0.5.2
Commit f4c6c9d (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by mkborregaard** [comment]
There isn't that much we can do to help, current Plots development only targets 0.6 and up. But - 
why do you want to display from a script? Usually display is associated with an interactive session, and scripts are mostly used to create image files (`savefig`).

**Comment by jingpengw** [comment]
OK. BTW, I was plotting 3D objects and IJulia can only display a image. I would like to rotate and play with it.

**Comment by mkborregaard** [comment]
try the plotlyjs backend

**Comment by jingpengw** [comment]
I still get an image, not intractable in Jupyter notebook.

**Comment by mkborregaard** [comment]
Then your best choice is to run the command `gui()` to open a gui window. Plotlyjs and pyplot backends have interactive guis.

**Comment by jingpengw** [comment]
after restart the kernel, plotly backend works! thanks for your help!
