### ISSUE TITLE
IOPub data rate exceeded with GR

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1223]
I used to ignore this error and just try another backend:

```julia
X = rand(3,15000)

scatter(X[1,:], X[2,:], X[3,:])

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
```

but GR is my favorite now and I would like to stick with it as much as possible. The other backends can handle this code in Jupyter, but I think GR interacts with notebooks a little differently. Is there any solution to this issue other than increasing even more my Jupyter limits that are already reasonably large?

**Comment by mkborregaard** [comment]
What are you trying to do - plot points as 15,000 different series? Why not just do `X = rand(15000, 3); scatter(X[:,1], X[:,2], X[:,3])` ?

**Comment by mkborregaard** [comment]
Indeed it is, LOL. I can't reproduce, can you post versioninfo and such?
<img width="604" alt="skaermbillede 2017-11-05 kl 20 27 32" src="https://user-images.githubusercontent.com/8429802/32418317-dae1ba2a-c267-11e7-9f3b-e8b8d9a5d65d.png">

Firefox version 56.0.2 64-bit
```
julia> versioninfo()
Pkg.statasJulia Version 0.6.1
Commit 0d7248e (2017-10-24 22:15 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

julia> Pkg.status.(["Plots", "GR", "IJulia"])
 - Plots                         0.13.1+            master
 - GR                            0.24.0             master
 - IJulia                        1.6.2
```

**Comment by juliohm** [comment]
>Julia Version 0.6.1-pre.0
Commit dcf39a1dda* (2017-06-19 13:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

> - Plots                         0.13.1
> - GR                            0.24.0
> - IJulia                        1.6.2

> Chromium 62.0.3202.75

**Comment by mkborregaard** [comment]
Firefox is the jewel in the crown of open access software.

**Comment by piever** [comment]
I can not reproduce the issue on Chrome either (on a MacOS though). Maybe the issue is that GR's default output format in the notebook is svg, which could be difficult to handle if there are too many points. Have you tried:

```julia
X = rand(3, 15000)
scatter(X[1,:], X[2,:], X[3,:], fmt = :png)
```

?

On my machine both work but the png output displays much more quickly.

**Comment by juliohm** [comment]
Thank you @piever , setting the format to PNG is a valid workaround. Are you using Chrome or Chromium? Perhaps this is an issue with the brand-free version of the browser?

**Comment by juliohm** [comment]
What is your version of Jupyter? Mine is 4.3.0, that can be the issue as well.

**Comment by juliohm** [comment]
See https://github.com/JuliaLang/IJulia.jl/issues/528

**Comment by piever** [comment]
That must be the difference, I'm on Jupyter 5.2

**Comment by juliohm** [comment]
The issue is that I am starting Jupyter from the command line with `jupyter notebook`, not from IJulia. The `IJulia.notebook()` command increases the limit by default.

**Comment by mkborregaard** [comment]
Nice detective work!
