### ISSUE TITLE
"World age" error when calling gui() from a own module using pyplot backend

### ISSUE THREAD

**Issue by wg030** [JuliaPlots/Plots.jl#1231]
I have noticed a strange error when I wrote an own module for creating my plots using the pyplot backend. I can create the plot successfully, but when I try to display it with the gui() function it gives me the error:

> LoadError: MethodError: no method matching getindex(::PyPlot.Figure, ::Symbol)
The applicable method may be too new: running in world age 24139, while current world is 24143.
while loading C:\MyJuliaDir\errtmp.jl, in expression starting on line 20
in MakePlot at errtmp.jl:9
in gui at Plots\src\output.jl:134 <inlined>
in display at Plots\src\output.jl:144 <inlined>
in prepare_output at Plots\src\plot.jl:251
in _before_layout_calcs at Plots\src\backends\pyplot.jl:936

However when I simpliy return my plot object and call the gui() function in the Main module everything works as expected. I have created a minimal working example that reproduces the error which I added for you:
[errtmp.jl.txt](https://github.com/JuliaPlots/Plots.jl/files/1457269/errtmp.jl.txt)

**Comment by mkborregaard** [comment]
Yes, this is the "World age" issue https://github.com/JuliaPlots/Plots.jl/issues/745 which is caused by the way Plots handles supporting PyPlot when you have it installed, without requiring that you install it. 
Instead of `gui()`, would it help to use `display(myplot)`?

**Comment by wg030** [comment]
display does not work either!
