### ISSUE TITLE
Issue with plotlyjs() backend

### ISSUE THREAD

**Issue by Nectarineimp** [JuliaPlots/Plots.jl#1232]
Something is wrong with Plots and the plotlyjs() back end. I've tried this several ways over the last few days and I am certain the error is within Plots.jl.

Error: plot will not appear in Blink window, or plots window in atom. Plot takes a long time to fail. Errors are as follows:

```
Javascript error	JSLoadError: failed to load http://127.0.0.1:4686/plotly-latest.min.js
try_yieldto(::Base.##296#297{Task}, ::Task) at event.jl:189
wait() at event.jl:234
wait(::Condition) at event.jl:27
wait(::Task) at task.jl:181
macro expansion at dynamic.jl:67 [inlined]
(::Atom.##47#51)(::Dict{String,Any}) at eval.jl:44
handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N} where N) at comm.jl:163
(::Atom.##11#13)() at event.jl:73
```

Stack Trace
```

Javascript error	JSLoadError: failed to load http://127.0.0.1:4686/plotly-latest.min.js
in  at base\event.jl:73
in handlemsg at Atom\src\comm.jl:163
in  at Atom\src\eval.jl:44
in macro expansion at Media\src\dynamic.jl:67 <inlined>
in wait at base\task.jl:181
in wait at base\event.jl:27
in wait at base\event.jl:234
in try_yieldto at base\event.jl:189
```

Code:
```
using Plots
plotlyjs()
n = 100
ts = linspace(0,8π,n)
x = ts .* map(cos,ts)
y = (0.1ts) .* map(sin,ts)
z = 1:n
plt = Plots.plot(x,y,z,zcolor=reverse(z),m=(3,0.8,:green,stroke(1)),leg=false,cbar=false,w=2, size=(800,800))
Plots.plot!(plt, zeros(n),zeros(n),1:n,w=3)
```

I have uninstalled julia and reinstalled 0.6.1. I have tested PlotlyJS and it works just fine. Then I tested Plots with the plotlyjs() backend and got the errors above.

**Comment by mkborregaard** [comment]
Ugh, I was hoping this was not Plots. Could you 1) try the plotly() backend? 2) post versioninfo()?

**Comment by mkborregaard** [comment]
On my system:
<img width="1021" alt="skaermbillede 2017-11-10 kl 08 09 54" src="https://user-images.githubusercontent.com/8429802/32646803-a4ded6ee-c5ee-11e7-872b-f66fa58c0a91.png">

Note that plotlyjs in Atom still suffers from https://github.com/JuliaPlots/Plots.jl/issues/1074 making gr work better in Atom at the moment for non-interactive plots.

**Comment by Nectarineimp** [comment]
Yes, no problem. But first, coffee.
On November 10, 2017 at 12:45 AM Michael Krabbe Borregaard <notifications@github.com> wrote:Ugh, I was hoping this was not Plots. Could you 1) try the plotly() backend? 2) post versioninfo()?

**Comment by Nectarineimp** [comment]
I wonder if it is plotting, but scaled down to a single pixel... I will try to get to it this morning. I'm going away this afternoon to a state park and won't be online again until Sunday.
On November 10, 2017 at 2:12 AM Michael Krabbe Borregaard <notifications@github.com> wrote:On my system:

Note that plotlyjs in Atom still suffers from #1074 making gr work better in Atom at the moment for non-interactive plots.

**Comment by Nectarineimp** [comment]
Using plotlyjs and doing ```plot(rand(10, 2), kind=:scattergl)``` fails while ```plot(rand(10, 2), kind=:scatter)``` works, which narrows down the issue to electron and WebGL. I am probably in need of an update to a WebGL driver or something on my Windows 10 machine. Thanks for the help!
