### ISSUE TITLE
Savefig() accumulates all plots in previous iterations

### ISSUE THREAD

**Issue by kadir-gunel** [JuliaPlots/Plots.jl#1233]
Hello,

I am having a problem with the following code.

```julia
using Plots
gr()
for i = 1:40
   plts = []
   for j = 1:6
       x = rand(1:10, 10)
       y = rand(1:10, 10)
       plts = scatter!(x, y)
   end
   savefig(plts, "path/to/directory/"*string(i))
end
```
When I execute this code I expect that each saved plot will be started from scratch in each iteration.  But what happens is that the plts_i is also in plts_i+1. 
Why is this happening? 

B.R.

**Comment by daschw** [comment]
`plot!(x, y)` or `scatter!(x, y)`, `bar!(x, y)` adds a series to the current plot. Hence you are always adding series to the same plot.
What you want to do is probably:
```julia
using Plots
gr()
for i = 1:40
   plts = plot() # Initialize an empty plot
   for j = 1:6
       x = rand(1:10, 10)
       y = rand(1:10, 10)
       scatter!(plts, x, y) # add series to the plot plts
   end
   savefig(plts, "path/to/directory/"*string(i))
end
```

**Comment by kadir-gunel** [comment]
Solved. Thank you!
