### ISSUE TITLE
FFMPEG Error in Windows

### ISSUE THREAD

**Issue by biggsbiggsby** [JuliaPlots/Plots.jl#1239]
There seems to be a problem with `@gif` saving files on windows in the current master version (not sure how to check this version number, but I updated just before posting this...). It works fine on the (older) registered version (0.13.1) however, so it seems to have been broken recently (or something weird is going on for me).

MWE:
```
using Plots; gr(); 
@gif for nn=1:3
    Plots.contour((collect(1:100)*collect(1:100)').^nn)
end
```
I'm getting this error at the point of saving:
```
failed process: Process(`ffmpeg -v 0 -i 'C:\Users\user\AppData\Local\Temp\jl_59F1.tmp/%06d.png' -vf palettegen -y palette.png`, ProcessExited(1)) [1]
    in anonymous at base\<missing>
    in macro expansion at Plots\src\animation.jl:146 <inlined>
    in gif at Plots\src\animation.jl:63
    in #gif#266 at Plots\src\animation.jl:63
    in #buildanimation#269 at Plots\src\animation.jl:75
    in run at base\process.jl:651
    in pipeline_error at base\process.jl:682
```
Thanks

**Comment by mkborregaard** [comment]
That's true. We've changed to ffmpeg, we need to add that as a bindep. For now you can just install ffmpeg to your system

**Comment by biggsbiggsby** [comment]
Thanks for the response. I believe I do have ffmpeg installed:
`ffmpeg -h` in powershell tells me I have `version N-50911-g9efcfbe` installed.
This might be out of date though... I'll try seeing if there is an update.

**Comment by biggsbiggsby** [comment]
This seems to be an issue with the palette generation in animation.jl
Changing the error-referenced section (lines 74-77) to remove the palette generation causes the function to work without error:
```
        # generate a colorpalette first so ffmpeg does not have to guess it
        # run(`ffmpeg -v 0 -i $(animdir)/%06d.png -vf palettegen -y palette.png`)
        # then apply the palette to get better results #don't actually
        run(`ffmpeg -v 0 -framerate $fps -loop $loop -i $(animdir)/%06d.png -y $fn`)
```
I'm not sure what the palette generation problem is, it seems to follow the correct documentation for ffmpeg, but this at least fixed the problem for me...

**Comment by mkborregaard** [comment]
This line was introduced in #1185 by @H-M-H . We may have to revert the PR if this error is observed consistently. The MWE works fine on my system. Could you post your versioninfo()?

**Comment by biggsbiggsby** [comment]
Hmm odd... 
Sure, here's the version info result:
```
Julia Version 0.6.1
Commit 0d7248e2ff* (2017-10-24 22:15 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

**Comment by mkborregaard** [comment]
Mine, for comparison, is
```
Julia Version 0.6.1
Commit 0d7248e (2017-10-24 22:15 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```
Looks like the OS is the essential difference.
@ChrisRackauckas I believe you're the only JuliaPlots member on windows - would you mind trying the MWE in the OP?

**Comment by daschw** [comment]
works for me on
```julia
Julia Version 0.6.1
Commit 0d7248e2ff* (2017-10-24 22:15 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
```

**Comment by biggsbiggsby** [comment]
weird... maybe something with the ffmpeg config?
This is what I have (from `ffmpeg -h`):

`
 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
`

**Comment by daschw** [comment]
I have
```
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfi
g --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libm
p3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --en
able-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --ena
ble-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enabl
e-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
```

**Comment by biggsbiggsby** [comment]
So it turns out the default command saving the palette to a .png file was crashing the ffmpeg process while saving on my computer... having it save the palette to a .gif fixes everything.
I guess there is an issue with the PNG encoder on some computers... I have no idea why, but it might be worth changing if it doesn't create problems for others?

The relevant change is simply:
```
        # generate a colorpalette first so ffmpeg does not have to guess it
        run(`ffmpeg -v 0 -i $(animdir)/%06d.png -vf palettegen -y palette.gif`)
        # then apply the palette to get better results
        run(`ffmpeg -v 0 -framerate $fps -loop $loop -i $(animdir)/%06d.png -i palette.gif -lavfi paletteuse -y $fn`)
```

**Comment by mkborregaard** [comment]
Would you be willing to put that change in a PR?

**Comment by biggsbiggsby** [comment]
Sure, just submitted one (I think at least... this is my first time modifying a repository here, let me know if I did something wrong!)

**Comment by mkborregaard** [comment]
Thanks!
