### ISSUE TITLE
PGFPlots ticks text not calculated correctly for bigger numbers

### ISSUE THREAD

**Issue by Paethon** [JuliaPlots/Plots.jl#1241]
It seems like the text for the tick marks is not calculated correctly for bigger numbers when using PGFPlots as the backend (i.e. if the numbers get big for example 10^4 is shown, but the text for the ticks is not changed).

![screenshot from 2017-11-13 20-25-26](https://user-images.githubusercontent.com/237550/32744835-1c1f6d30-c8b1-11e7-99be-4a9763d7985e.png)

**Comment by apalugniok** [comment]
This could be done by specifying something like `scaled y ticks = false` in the PGFPlots `Axis`. This would always stop this behaviour, if this is something we are fine with I can make a PR.
