### ISSUE TITLE
Matlabplotlib 2.1.0 regonized as Matlabplotlib 0.0.0 => "set_axis_bgcolor" not found

### ISSUE THREAD

**Issue by wg030** [JuliaPlots/Plots.jl#1248]
Hey everybody,
I've just installed the latest versions of Julia and Atom with Juno on an Ubuntu 16.04 LTS PC.
When I wanted to create a plot with the Plots package using the pyplot backend I got the warning
> WARNING: You are using Matplotlib 0.0.0, which is no longer officialy supported by the Plots community. To ensure smooth Plots.jl integration update your Matplotlib library to a version >= 2.0.0

followed by the error

> LoadError: KeyError: key "set_axis_bgcolor" not found
while loading ..../model.jl, in expression starting on line 144
getindex(::PyCall.PyObject, ::String) at PyCall.jl:247
getindex(::PyPlot.Figure, ::Symbol) at PyPlot.jl:68
_before_layout_calcs(::Plots.Plot{Plots.PyPlotBackend}) at pyplot.jl:939
prepare_output(::Plots.Plot{Plots.PyPlotBackend}) at plot.jl:251
display at output.jl:144 [inlined]
gui at output.jl:134 [inlined]
macro expansion at model.jl:158 [inlined]
anonymous at <missing>:?
include_string(::String, ::String) at loading.jl:522
include_string(::Module, ::String, ::String) at Compat.jl:478
(::Atom.##57#60{String,String})() at eval.jl:74
withpath(::Atom.##57#60{String,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
macro expansion at eval.jl:72 [inlined]
(::Atom.##56#59{Dict{String,Any}})() at task.jl:80

My Matplotlib version is the latest (2.1.0), which I installed from source according to the instructions on the official homepage ([https://matplotlib.org/faq/installing_faq.html#install-from-git](https://matplotlib.org/faq/installing_faq.html#install-from-git)). When I type "pip show matplotlib" in the terminal it confirms that the installation was successful showing the exact version number "2.1.0+806.g905465b".

Having looked at the source code of "pyplot.jl" I have figured out that the problem is likely a problem of the PyCall package (or maybe even Matplotlib itself) and not the Plots package itself since the call `PyCall.version` does not yield the right version number of Matplotlib.

However I am posting it here, too, because my quick fix is a slight modification of "pyplot.jl". So what I did to get rid of that error is the following: I simpliy changed the line `const set_facecolor_sym = if PyPlot.version < v"2"` of my local "/home/myusername/.julia/v0.6/Plots/src/backends/pyplot.jl" file to `const set_facecolor_sym = if v"0" < PyPlot.version < v"2"`. Everything works as expected now.

**Comment by wg030** [comment]
This issue has officially been solved now. See [https://github.com/JuliaPy/PyCall.jl/issues/448](url)
So no need for my quick fix anymore.
However right now you have to remove the PyCall package first with `Pkg.rm("PyCall")` and then clone it with `Pkg.clone("PyCall")`.

**Comment by mkborregaard** [comment]
Thanks for the heads up! I'll close this now.
