### ISSUE TITLE
Latex font in axis labels

### ISSUE THREAD

**Issue by ewybo** [JuliaPlots/Plots.jl#1250]
Hi, 
I am wondering how to get the Latex font in the axis labels. 
I don't manage with:
`guidefont = Plots.font()`

With the workaround:
`yaxis = L"\rm{energy}"`
the y-axis label is rotated and comes horizontally in the plot...

**Comment by mkborregaard** [comment]
That's a bug in the gr backend (#1191) - closing this as a duplicate.
