### ISSUE TITLE
PyPlot and PlotlyJS fail to build?

### ISSUE THREAD

**Issue by gaomrx** [JuliaPlots/Plots.jl#1259]
![image](https://user-images.githubusercontent.com/6380557/33144564-7da2cc56-cf8b-11e7-8499-ab12b4f11f4e.png)

Not sure what is happening here. I have PyPlot 2.3.2, Julia version 0.6.0 running on JuliaBox. I have tried removing PyPlot and re-adding it, but the problem persists. Similar case for PlotlyJS. 

![image](https://user-images.githubusercontent.com/6380557/33144695-eef03e7a-cf8b-11e7-800f-8cc631f5ec78.png)

**Comment by mkborregaard** [comment]
Are you in the new juliabox?

**Comment by gaomrx** [comment]
I am using juliabox.com, not the new one at next.juliabox.com

**Comment by mkborregaard** [comment]
hmm, strange. I assume it works in the repl?

**Comment by gaomrx** [comment]
Nothing works in the REPL, this seems to be an isolated case as everything works fine in another account

**Comment by mkborregaard** [comment]
It sounds like your .ji package files are corrupted - on a desktop I'd just clobber the directories manually - not sure how to do that on IJulia. Perhaps ask on Ijulia.jl?

**Comment by gaomrx** [comment]
I was able to reset all the packages and plot again.
