### ISSUE TITLE
Reinterpret -Inf and Inf as NaN

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1261]
Sometimes input arrays have -Inf and Inf in them, which makes Plots throw an error. Sometimes they are produced internally, if someone calls `yscale = :log` and there are zeros in the data. @dpsanders and @StefanKarpinski suggested on Slack that these should be ignored, which would happen automatically if they're converted into NaN. We need to find the right place in the pipeline to do it.

**Comment by mkborregaard** [comment]
I've earlier argued that it is user error to pass an array with 0s in it and expect a log scale to work. What convinced me to try to deal with this is the difficulty, user side, in handling this gracefully as both x and y inputs will need to be reduced to non-0 slots.

**Comment by ma-laforge** [comment]
That seems like a good idea - as long as there is an option for backends to handle these cases themselves (if they can do so elegantly).

Of course, this is more for the cases where it is not Plots.jl itself that throws the errors.

An other option would be implement something like what InspectDR does:

![demo9_export](https://user-images.githubusercontent.com/11205411/33272842-746b4fd8-d359-11e7-8194-db837543153b.png)

InspectDR supports a mode which basically scans through the data before plotting, strips out NaN data, and overlays a "NaN" dataset so the user can see which points are problematic.  This only works if only one of the two (x,y) coordinates is a NaN, though.

**Comment by mkborregaard** [comment]
NaN's are generally handled by the backends - so the idea is to change Inf to NaN for better handling by the backends. Most backends just drop data points where one or both is NaN

**Comment by ma-laforge** [comment]
Fair enough.  Though I believe InspectDR actually handles Inf correctly as well (drawing vertically up to the positive/negative edge of the plot).  That way, when the user zooms out, it always looks as if the line goes off to infinity.

If I forgot to implement it, there is no reason why I cannot make it happen - so it would be nice to have the option of passing off infinite data to the backend (as long as it does not cause Plots.jl itself to crash).
