### ISSUE TITLE
Series labels not working with Plotly

### ISSUE THREAD

**Issue by MFairley** [JuliaPlots/Plots.jl#1264]
`plot(1:n, y, label=["1p", "2p", "3p", "4p"], size=(900, 500))` is giving me labels: "trace 0", "trace 1",...
instead of my desired label.

<img width="1014" alt="screen shot 2017-11-27 at 7 21 50 pm" src="https://user-images.githubusercontent.com/4374785/33301086-95114018-d3a8-11e7-9c29-78500ff59c9e.png">

**Comment by MFairley** [comment]
Removing the commas from label fixes the issue.

**Comment by mkborregaard** [comment]
Most recurrent Plots issue of all time. Most languages think of labels as a property of the legend, we think of it as a property of the series. Closing, as this is really a documentation issue.
