### ISSUE TITLE
pyplot gives pixelated plot on mac OS

### ISSUE THREAD

**Issue by MFairley** [JuliaPlots/Plots.jl#1265]
When I use the pyplot backend on mac OS 10.13.1 on a 5k monitor I get a pixelated plot by default:

<img width="748" alt="screen shot 2017-11-27 at 9 02 40 pm" src="https://user-images.githubusercontent.com/4374785/33303168-561d5b2c-d3b6-11e7-85f3-2f9ef06fdabf.png">

**Comment by mkborregaard** [comment]
And what if you use PyPlot without Plots?

**Comment by MFairley** [comment]
Just checked that PyPlot is also pixelated without Plots. Running `PyPlot.svg(true)` fixes the pixelation. Is there a way to get the svg option with Plots?

**Comment by mkborregaard** [comment]
Awesome!
