### ISSUE TITLE
Contour fill missbehaving

### ISSUE THREAD

**Issue by mauro3** [JuliaPlots/Plots.jl#1267]
Using the pyplot backend, this:
```
Plots.contour(432475.0:25.0:439525.0, 8.675175e6:25.0:8.6857e6, rand(283,422)', fill=true)
```
produces an empty plot with axes and color-axes of the right extent.  Dropping the `fill=true` produces a good plot, also dropping the x and y vectors makes it work.

**Comment by daschw** [comment]
Thanks a lot for reporting!
This was introduced by #1213.

**Comment by mauro3** [comment]
So I should use `fillrange=true`?

**Comment by daschw** [comment]
No, I have a fix, one moment ...

**Comment by daschw** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/1268

**Comment by daschw** [comment]
You could use `contourf` instead, by the way. That should work even without #1268.
