### ISSUE TITLE
Camera angle control not working in PyPlot 3D plots

### ISSUE THREAD

**Issue by ianshmean** [JuliaPlots/Plots.jl#1272]
The camera angle control introduced in #1141 is no longer working in PyPlot. The example given just produces two identical plots

```
using Plots
x = 1:1:10
y = z = rand(10)
p = plot(x, y, [z, z], layout = 2)
plot!(p[1], camera = (20,50))
```
![image](https://user-images.githubusercontent.com/1694067/33445694-a58a813c-d5cb-11e7-8294-175626d9e6df.png)

Should result in:
![image](https://user-images.githubusercontent.com/1694067/33445769-e5d8e8f0-d5cb-11e7-885a-94558b2852d0.png)

**Comment by mkborregaard** [comment]
I get
<img width="596" alt="skaermbillede 2017-11-30 kl 20 10 14" src="https://user-images.githubusercontent.com/8429802/33449933-80547bd6-d60a-11e7-82f1-b16115b29e4f.png">

GR looks slightly broken, though it may be an angle thing:
<img width="597" alt="skaermbillede 2017-11-30 kl 20 10 37" src="https://user-images.githubusercontent.com/8429802/33449972-a3a7991a-d60a-11e7-8120-584b68b2ca75.png">

@apalugniok how does it look for you?
@ianshmean what are your relevant package versions?

**Comment by ianshmean** [comment]
Peculiar, and my plots look like they were rendered with something else. i.e. Lack of tick values, legend, rendering differences.. even if I activate `pyplot()` at the start.

Julia 0.6.2
 - Plots                         0.13.1
 - PyPlot                        2.3.2

**Comment by ianshmean** [comment]
I just updated matplotlib through conda and I now get the right plotting environment, but the camera angle is still wrong 

conda:      4.3.16-py27_0     --> 4.3.30-py27h407ed3a_0
    matplotlib: 2.0.0-np111py27_0 --> 2.0.2-np111py27_0

![image](https://user-images.githubusercontent.com/1694067/33450673-8e054c2c-d5da-11e7-864b-4bdf312e8be2.png)

**Comment by mkborregaard** [comment]
Looks like it's not made it into the release yet. Could you try `Pkg.checkout("Plots")`?

**Comment by ianshmean** [comment]
Ah, yes, that's solved it. Thanks

**Comment by apalugniok** [comment]
@mkborregaard what camera angles did you use? `camera = (20,50)` looks fine to me. GR has always been a bit weird when it gets a really small elevation angle.

**Comment by mkborregaard** [comment]
That's probably it then. I used (20,50)

**Comment by apalugniok** [comment]
Well the images you linked don't look like they have an elevation of 50, they actually match `camera = (20,0)` so I'm hoping it was a typo and not some odd bug.

**Comment by mkborregaard** [comment]
Well now I get 
![skaermbillede 2017-12-04 kl 15 41 59](https://user-images.githubusercontent.com/8429802/33558268-bb5cae22-d909-11e7-8b16-9459da6d269c.png)
so maybe it was a typo...
