### ISSUE TITLE
plotting (x,y) pairs without splitting into x and y

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/Plots.jl#1275]
I'd like to plot an array of points without having to split the array into an x component and y component. As far as I can tell there isn't an interface to support this in `Plots.jl`. Two dimensional objects are interpreted as a collection of y values, with an implicit x value. (I think this is the same behavior as matplotlib)

```julia
using Plots

using GeometryTypes
d = [Point(x, sin(x)) for x=0:.1:2pi] # will plot as a collection of lines
aofa = [[x, sin(x)] for x=0:.1:2pi] # will plot as a collection of lines
di = reinterpret(Float64, d, (length(eltype(d)), length(d))) # will plot as a collection of lines
plot(di[1,:], di[2,:]) # but at least now its easy to turn it into the necessary `x` and `y` pieces.
```

Could there be a new keyword argument like `xy` or `xyz` to interpret 2D structures in this way?

**Comment by mkborregaard** [comment]
Let me first statet that if you just want to plot a sin curve, the easiest is `plot(sin, 0, 2pi)` which will adaptively use the correct number of points. 
If you need to use x,y pairs, the correct way is to use Tuples, not Arrays: `aofa = [(x, sin(x)) for x=0:.1:2pi]`. I think allowing for the use of Arrays-of-Arrays for this might collide with other uses of the construct.

**Comment by goretkin** [comment]
I hadn't thought to use tuples, thanks.

The sine curve was just an example.

**Comment by goretkin** [comment]
Actually, I'm still wondering how to plot a list of `Point` from https://github.com/JuliaGeometry/GeometryTypes.jl. `Point <: AbstractArray` is true, but it would be nice if the two packages worked together.

**Comment by mkborregaard** [comment]
I agree. It should be very easy to write a set of recipes for that package, if they'll take it.
