### ISSUE TITLE
Plot(twinx(), ...) creates ylabel on the wrong side of the plot (left instead of right)

### ISSUE THREAD

**Issue by LotteVictor** [JuliaPlots/Plots.jl#1276]
In my question about visualization on the julia discourse website (https://discourse.julialang.org/t/overlay-plot-with-second-plot-with-second-y-axis-to-the-right/6558) an issue occured that was identified as a bug by @mkborregaard: 
When using `plot(twinx()...)` the ylabel does not appear on the right side (as it should) but on the left side, on top of the original ylabel.

**Comment by PhilipVinc** [comment]
I also bumped into this. I hope someone fixes it..

**Comment by metorm** [comment]
Guys, I am faced with this problem, too.

**Comment by PhilipVinc** [comment]
I would gladly address this if someone pointed me in the right direction. 

Upon inspection, `twinx()` does correctly set the `:ymirror=true` attribute, but it seems that `GR.jl` only mirrors the ticks and not the label.

If you try to run 
```
using Plots
t=collect(1:10);
x=rand(10);
plot(t, x, ymirror=true, ylabel="ylab")
```
you will see that the plot has no mirrored label. Therefore I think that this is a bit of a deeper problem in GR(). 
PyPlot works somewhat fine.

**Comment by mkborregaard** [comment]
It is likely not in GR, but in the backends/gr.jl file of Plots

**Comment by PhilipVinc** [comment]
@mkborregaard  Thanks. You were right: It was a very easy fix. 
It's actually a two line fix. 
Could you point me out towards the best way to commit it back to the community? Should I create a PR?

**Comment by daschw** [comment]
Yes, please submit a PR! If you need guidance, feel free to ask or read http://docs.juliaplots.org/latest/contributing/#git-fu-or-the-mechanics-of-contributing

**Comment by PhilipVinc** [comment]
I submitted a PR. Moreover, I took the liberty of changing the code that computes the padding to add the padding to the side where the label is actually located.

Please let me know if the PR is not well done or if I should do something else.

**Comment by adannenberg** [comment]
Does this now work for others?  It doesn't fully work for me...  When I run 

using Plots
x=1:20
y1=rand(length(x))
y2 = sin.(x)
plot(x,y1,label = "My y1 label", legend = :topleft, ylabel = "the lh y-axis",grid=:off)
plot!(twinx(),y2, label = "my y2 label", legend=:topright, ylabel = "the rh y-axis", grid=:off, xlabel="numbers", color=:red, box=:on)

I get a plot with no label on the right hand y-axis.  I'm not sure if it's off the plot to the right or missing (less likely).  Apologies for not using the "Insert code" tool.  When I used it and previewed this message it seemed to ignore newlines...

**Comment by kosukesando** [comment]
I have a similar problem, where the labels are fine but the ticks for the twinx axis is duplicated on the left side, where I only want it on the right side.
![image](https://github.com/JuliaPlots/Plots.jl/assets/63235669/dcb822e9-4f73-48fb-b650-56395db1199d)
Let me know if I should make a new issue for this.
