### ISSUE TITLE
axis shift/scale when plotting image and scatter

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/Plots.jl#1277]
When plotting an image with some lines on top, the axis of the plot get modified after the addition of scatter points.
Here's an image with a line: 
```julia
img = rand(Gray, 10, 10)
plot(img)
x = [2,4]
y = [4,8]
plot!(x, y)
```
![tmp1](https://user-images.githubusercontent.com/3281957/33544264-69455960-d8da-11e7-8ae2-1076b0485a86.png)
and now let's add a scatter point (I made it half-transparent so you'll see what I mean):
```julia
scatter!(x[1:1], y[1:1], marker=(0.5))
```
![tmp2](https://user-images.githubusercontent.com/3281957/33544342-bc0a0d6c-d8da-11e7-841b-04db93c77283.png)
Note the discrepancy between the location of the pixels, line, and scatter point compared to the previous image.

**Comment by mkborregaard** [comment]
The recalculation of the axes and ticks is expected (we think of it as a feature), and the reason the ticks are different is that adding points to a plot triggers axis widening (on a scatter plot you want space around the points, but on a heatmap you don't want space around the colored boxes). It does seem to play together in a weird way here.

**Comment by yakir12** [comment]
Widening the axes makes sense. But is it possible to widen them without changing the coordinates of where things are? So if the location of a pixel's corner is at (1,1), it should remain (1,1) after altering the axes. This does not seem to be the case here, right?

**Comment by yakir12** [comment]
I tested it with just an array of random floats and heatmap and it works as expected:
![tmp1](https://user-images.githubusercontent.com/3281957/33545096-623d38ba-d8dd-11e7-892e-5058ce8e5e0a.png)
![tmp2](https://user-images.githubusercontent.com/3281957/33545128-73ce7ac6-d8dd-11e7-9ae4-3367853e476a.png)

**Comment by t-bltg** [comment]
The correct way is to specify `widen=false`.
