### ISSUE TITLE
Workaround for `plot_title`

### ISSUE THREAD

**Issue by bisraelsen** [JuliaPlots/Plots.jl#1293]
In the documentation I see that `plot_title` is not yet implemented. In the meantime is there some sort of workaround? I'd like to get a single title for two side-by-side subplots. I think creating a layout with a single wide plot at the top, and using that to make the title might work, but I'll have to get rid of the axes and several other hacks... Is there a better way?

**Comment by bisraelsen** [comment]
FYI, this is what I have done for now:

    l = @layout [a{.1h};grid(1,2)]
    p = plot(layout=l)
    plot!(grid=false,annotation=(0.5,0.5,"Title"),ticks=([]),fgborder=:white,subplot=1)
    plot!(..plot stuff.., subplot=2)
    plot!(...plot stuff., subplot=3)

I would be interested to know if anyone knows of a better approach though.

**Comment by mkborregaard** [comment]
No, that's great. This is perhaps a sligthly more terse syntax
```julia
l = @layout [a{.1h};grid(1,2)]
plot(plot(annotation=(0.5,0.5, "Title"), framestyle = :none), heatmap(rand(20,20)), heatmap(rand(20,20)), layout = l)
```

**Comment by bisraelsen** [comment]
Excellent! `framestyle=:none` is what I wanted. Thanks!
