### ISSUE TITLE
limiting the axis doesn't crop the plotted image

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/Plots.jl#1296]
When plotting an image, and then applying limits on the axis, the image doesn't get affected. 
```julia
h1 = plot(img, title="full")
h2 = plot(img, ylim=(200,300), xlim=(100,200), title="cropped?")
plot(h1, h2, aspect_ratio=1)
```
![bad](https://user-images.githubusercontent.com/3281957/33758490-c6f987bc-dbfe-11e7-9654-e8bcc63d7455.png)
But if we treat the image as a matrix of numbers, then it works (but we loose the original colors).
```julia
bw = Gray.(img)
m = Float64.(bw)
h1 = heatmap(m, title="full")
h2 = heatmap(m, ylim=(200,300), xlim=(100,200), title="cropped!")
plot(h1, h2, aspect_ratio=1)
```
![good](https://user-images.githubusercontent.com/3281957/33758523-df4a31c2-dbfe-11e7-9982-b3c73e945cab.png)

**Comment by samstewart** [comment]
This is related to [this issue](https://github.com/JuliaPlots/Plots.jl/issues/1298).

What is the desired behavior here? I think setting axes limits should *scale* the image, not crop it?

**Comment by yakir12** [comment]
I don't understand why. When plotting an image, then there are usually dimensions associated with the image's axes. Each pixel has a x and y location. If we limit the axis we crop the image.

**Comment by samstewart** [comment]
But the heatmap code automatically chooses the size of the pixels. Shouldn't that depend on the axis limits?

**Comment by daschw** [comment]
I agree with @yakir12 that setting lims should crop the image.

**Comment by samstewart** [comment]
@daschw I'll close the other issue I opened.
