### ISSUE TITLE
`abline` shouldn't update limits

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/Plots.jl#1297]
I think the intent of `abline`, like `hline` and `vline` is to plot a line that spans the plot, but that doesn't update the plot limits beyond what's "necessary". 

```julia
using Plots
@gif for c  = ["plot()", "plot(x->10*sin(x))", "Plots.abline!(10,0)"]
  eval(parse(c))
  title!(c)
end
```
![out](https://user-images.githubusercontent.com/581043/33768449-1806bc52-dbf4-11e7-8092-72cadcadcd4b.gif)

In this case, I think the limits should stay the same after the sinusoid is plotted.

In any case, is there a way to force the limits to stay the same? Or better yet, give a list of invisible points that should be used to update the limits (and if this list is empty, then don't update the limits?) I'm interested in drawing lines that extend beyond the limits, so that when the graph is panned or zoomed, the line appears to extend forever.

**Comment by mkborregaard** [comment]
You can't just set `xlims` and `ylims`?

**Comment by goretkin** [comment]
like `Plots.abline!(1, 0, xlims=xlims(current()), ylims=ylims(current()) )` ? Yes, that's one way to force the limits to stay the same. If there's an abbreviation, I'd like to know.

I opened the issue because I think the current behavior of `abline!` could be improved, especially for lines with high slope.

**Comment by mkborregaard** [comment]
Cool, yeah makes sense. BTW, `xlims()` is sufficient, you don't need `xlims(current())`.

**Comment by mkborregaard** [comment]
#1300

**Comment by goretkin** [comment]
Thanks! And good to know there's a shortcut for getting the plot limits.

In https://github.com/JuliaPlots/Plots.jl/pull/1300#issuecomment-350681081, it was brought up that `vline` and `hline` don't update either (whether panning or adding new data). I was thinking about this too, and whether there's some mechanism for plotting "infinite" objects, like what one would like `hline`, `vline`, and `abline` to be.

matplotlib can do infinite `vline` and `hline` (but not something like `abline`, I think) because it has a separate coordinate system attached to the plot ("axes" here https://matplotlib.org/users/transforms_tutorial.html). So it can plot a line from x_axis=0 to x_axis=1 and it will be an hline. But, again, this doesn't really seem to generalize beyond `hline` and `vline`.
