### ISSUE TITLE
Plotly backend silently ignores bar_width

### ISSUE THREAD

**Issue by joshday** [JuliaPlots/Plots.jl#1303]
`bar_width` appears in the supported arguments in plotly.jl:

https://github.com/JuliaPlots/Plots.jl/blob/f2e2ffa17033145d06166db217b39ce3a45a02a1/src/backends/plotly.jl#L43 

but it appears to get ignored.  I believe the `StatsBase.Histogram` recipe has gaps between bars as a result.  

# Example
```
julia> bar([1, 2, 3], bar_width = [.1, .5, 1])
```
<img width="701" alt="screen shot 2017-12-12 at 1 43 44 pm" src="https://user-images.githubusercontent.com/8075494/33902277-8306b308-df42-11e7-9d1c-899b22ddc5c9.png">

# The Fix
The javascript part is here (https://plot.ly/javascript/bar-charts/#customizing-individual-bar-widths).

I think we just need `d_out[:width] = ...` around the section below?  I don't understand the Plots internals well enough to write what the RHS is, but I'm willing to submit a PR if someone can give me a pointer.

https://github.com/JuliaPlots/Plots.jl/blob/f2e2ffa17033145d06166db217b39ce3a45a02a1/src/backends/plotly.jl#L537-L544

**Comment by mkborregaard** [comment]
Yes, `d_out[:width] = series[:bar_width]` after line 538 should do the trick. Another issue with the bars is also that the black border is not drawn by default on plotly like it is on all the other backends.
