### ISSUE TITLE
PyPlot backend - legend does not reflect linestyles specified for plot

### ISSUE THREAD

**Issue by davidzentlermunro** [JuliaPlots/Plots.jl#1305]
When I plot using PyPlot backend the legend defaults to all sold line style even though I have specified a different style for the plot (dash)

**Comment by mkborregaard** [comment]
MWE:
```
using Plots; pyplot()
plot(randn(10), linestyle = :dash)
```
![test](https://user-images.githubusercontent.com/8429802/33943500-a09102c0-e019-11e7-8c7e-15a7fcd50382.png)
