### ISSUE TITLE
markerstrokecolor=:match not respected by some backends

### ISSUE THREAD

**Issue by baggepinnen** [JuliaPlots/Plots.jl#1334]
Pyplot and GR (at least) backends do not respect the attribute `markerstrokecolor=:match`, in both cases, black markerstrokecolor is used.

```julia
julia> using Plots

julia> pyplot()
Plots.PyPlotBackend()

julia> scatter(randn(10), markerstrokecolor=:match)
```

**Comment by wkearn** [comment]
The [documentation says](http://docs.juliaplots.org/latest/attributes/): 
> Color of the marker stroke (border). `:match` will take the value from `:foreground_color_subplot`.

so what you're seeing is the specified behavior (the marker stroke color matches the foreground color, which is black by default). To illustrate:

```julia
julia> scatter(randn(10),markerstrokecolor=:match, foreground_color_subplot=:green)
```

![plots1334](https://user-images.githubusercontent.com/4359487/34907576-ddd18856-f84e-11e7-8ca2-ce561033419d.png)

Do you want the marker stroke color to match the color of the marker itself? Using `markerstrokecolor=:auto` will give you that:

```julia
julia> scatter(randn(10),markerstrokecolor=:auto)
```

![plots1334-2](https://user-images.githubusercontent.com/4359487/34907609-5e0f558e-f84f-11e7-8bf2-4e495dd715b8.png)

**Comment by daschw** [comment]
I can see, how `markerstrokecolor = :match` is misleading though.

**Comment by JeffFessler** [comment]
Some time ago, `default(markerstrokecolor=nothing)` also worked with GR backend,
but it no longer seems to have any effect.
Fortunately, `default(markerstrokecolor=:auto)` works fine with GR.
