### ISSUE TITLE
alternative extension for tikz plots

### ISSUE THREAD

**Issue by tpapp** [JuliaPlots/Plots.jl#1335]
Saving `savefig("file.tikz")` using the `tex` format would be convenient since it is supported by the [tikzscale](https://www.ctan.org/pkg/tikzscale) LaTeX package, and `.tex` isn't.

My understanding is that adding `"tikz" => tex` to [`_savemap`](https://github.com/JuliaPlots/Plots.jl/blob/1949b6fe0f6afef3b1d7d0e0d39a78510a7966c1/src/output.jl#L69) would accomplish this.

Just wanted to check that this is OK before I submit a PR.

**Comment by mkborregaard** [comment]
:+1: from me - @pkofod any opinions otherwise?

**Comment by pkofod** [comment]
Was this ever followed up upon? This sounds reasonable.

**Comment by mkborregaard** [comment]
Nope, it wasn't followed up on, but I also think it sounds reasonable. @tpapp still up for submitting a PR? :-)

**Comment by tpapp** [comment]
@mkborregaard: sorry, I kind if moved to [PGFPlotsX.jl](https://github.com/KristofferC/PGFPlotsX.jl) for my plotting needs.

**Comment by mkborregaard** [comment]
NO! :-O :cry:
