### ISSUE TITLE
GR subplots do not appear in log-scale

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1338]
Minimum working example:

```julia
using Plots; gr()

plt = plot(layout=6)
for i in 1:6
    plot!(plt[i], [1,2], [1,2], xscale=:log10)
end
plt
```
![download](https://user-images.githubusercontent.com/3345261/34547614-3b722b64-f0b1-11e7-90e4-9aa9ae550b12.png)

**Comment by mkborregaard** [comment]
I wonder if this could be related to https://github.com/JuliaPlots/Plots.jl/issues/1101 ?

**Comment by juliohm** [comment]
Probably related @mkborregaard, thanks for linking the issue.
