### ISSUE TITLE
Transparency and heatmaps

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1342]
Is it possible to get transparency with heatmaps?

```julia
using Plots; gr()

heatmap(rand(100,100), alpha=.1, fillalpha=.1) # none of these attributes work
```

**Comment by mkborregaard** [comment]
I think this is GR issue, have you tried with pyplot?

**Comment by juliohm** [comment]
PyPlot also doesn't make it transparent, maybe the issue is more general.
