### ISSUE TITLE
`linecolor=nothing` overridden by alpha setting

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/Plots.jl#1343]
As far as I can tell, this is not backend dependent. On Plots.jl master `1949b6`

```julia
using Plots

#plotlyjs()
#pyplot()
gr()

combos = map(x->vcat(x...), collect(
  Iterators.product(
    [[], [:alpha=>1.0]],
    [[], [:linecolor=>nothing]],
    #[[], [:linealpha=>0.0]],
    ))[:])

f = plot(;layout=length(combos))
s = Shape([(0.0, 0.0), (1.0, 0.0), (0.5, 1.0)])

for (i, kw) in enumerate(combos)
  t = isempty(kw) ? "no kwargs" : join(["$k=$v" for (k,v) in kw], ", ")
  plt = f.subplots[i]
  title!(plt, t)
  plot!(plt, s; kw..., legend=nothing)
end

display(f)

```
<img width="600" alt="image" src="https://user-images.githubusercontent.com/581043/34657264-68f26e5c-f3f2-11e7-9593-f63f1a46482b.png">

Note that the line appears even though `linecolor=nothing`

(`linealpha=0.0` works correctly, however.)

**Comment by daschw** [comment]
`linecolor = nothing` sets the color to `RGBA(0,0,0,0)`. If you then specify `alpha = 1` this becomes `RGBA(0,0,0,1)` so I'd say this behaviour is expected.

**Comment by goretkin** [comment]
I think then there is the same question that arises in https://github.com/JuliaPlots/Plots.jl/issues/953 : how to handle two alpha specifications?

In any case, this behavior was surprising to me, even though I understand the mechanism you explained. I want the Shape interior to have some `alpha`, and I want l`inecolor=nothing`. I can achieve those two independently. However if I want to combine them, I need to introduce a third keyword, `linealpha`. So the surprising part (to me) is the non-orthogonality.

**Comment by daschw** [comment]
> I want the Shape interior to have some alpha, and I want linecolor=nothing

You can use `fillalpha` to achieve this.
