### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by rofinn** [JuliaPlots/Plots.jl#1346]
It'd be nice to get a new release of Plots.jl with `__precompile__(true)`.

**Comment by mkborregaard** [comment]
Worth a try...

**Comment by mkborregaard** [comment]
Done.

**Comment by rofinn** [comment]
Just noticed it was tagged 0.14.3. Maybe it should be a minor release given that `__precompile__(true)` can significantly change behaviour (and introduce bugs)?

**Comment by mkborregaard** [comment]
Yeah, fair point, I've updated the minor version. It's higly unlikely to introduce bugs, I'd think - I've had precompilation on on my own machine for more than a year without a hiccup.
