### ISSUE TITLE
Plotly annotations misplaced with multiple subplots.

### ISSUE THREAD

**Issue by apalugniok** [JuliaPlots/Plots.jl#1356]
```
plot(rand(10,8), ann = (:bottom_left, :auto), layout = grid(2,2))
```
<img width="588" alt="brokenplotly" src="https://user-images.githubusercontent.com/22132297/34964942-5a0d7380-fa48-11e7-9478-e4ad44f30864.png">

**Comment by daschw** [comment]
Great, thanks!
