### ISSUE TITLE
Plotting specific level(s) for contour lines

### ISSUE THREAD

**Issue by blas-ko** [JuliaPlots/Plots.jl#1357]
Hi! I want to plot contour lines for specific level values! 
As far as I know, you can say how many levels you want plotted 
```julia
using Plots
pyplot()
V(x,y) = x^2 + y^2
x = linspace(-10,10,50)
y = linspace(-10,10,50)
contour(x,y, (x,y)->V(x,y), levels=30)
``` 
![image](https://user-images.githubusercontent.com/8909006/35015805-aaeb4226-fadb-11e7-9c0d-e19aeab5a7ad.png)

I'd like to know if there's a way to plot a contour line for an specific `V` value, such as `V(x,y) = 10` .
I've tried to look in the attributes to see if there was something like
```julia
contour(x,y, (x,y)->V(x,y), level_value=10)
```
but I've got no success in this. 

**Is there any way?** 
Thanks in advance!

**Comment by mkborregaard** [comment]
Just pass a Vector to `levels`.
```julia
contour(x,y,V, levels=[50,120]) #notice you can just pass the V function
```
That's a common ideom in Plots: get different behaviour by passing a different type to the keyword attribute.

**Comment by blas-ko** [comment]
Oh! That works perfectly! 
Sorry for the silly question.
