### ISSUE TITLE
PGFPlotsBackend doesn't render histogram bars for yaxis=:log10 anymore

### ISSUE THREAD

**Issue by tamasgal** [JuliaPlots/Plots.jl#1363]
Today I opened an older Jupyter notebook and after rerunning it I noticed that my histograms with logarithmic y-axes doesn't render correctly anymore.
Since `PGFPlots.jl` has not been changed for I while, I guess there is some change in `Plots.jl` which caused this. No idea where to look, I updated quite a few packages in the last days/weeks :-/

Here is a snippet to reproduce it. A few days/weeks ago the bars were rendered in blue with the default black stroke (when using the default style).

![screen shot 2018-01-18 at 20 40 23](https://user-images.githubusercontent.com/1730350/35117880-54aa16e2-fc90-11e7-9608-59cb312479bf.png)

**Comment by tamasgal** [comment]
Hmmm, the following snippet works. So maybe I just used the wrong method to set the y-scale to log? ;)

![screen shot 2018-01-18 at 21 03 42](https://user-images.githubusercontent.com/1730350/35118791-42fe51a8-fc93-11e7-8f2d-baafafd3d7af.png)

**Comment by pkofod** [comment]
Bump, this seems like `yaxis ` changed behavior here. Was that intentional?

**Comment by daschw** [comment]
I cannot reproduce on current master.

**Comment by BeastyBlacksmith** [comment]
both examples produce the same output with the pgfplotsx backend
