### ISSUE TITLE
Wrong label printed when adding a series

### ISSUE THREAD

**Issue by improbable-22** [JuliaPlots/Plots.jl#1367]
This plots four lines, but the last two are incorrectly labelled "five","six": 
```
using Plots
plot(randn(10,2), lab=["one", "two"])
plot!(randn(10,2) .- 2, lab=["three", "four", "five", "six"]) 
```
Using ` lab=["three", "four"]`, as I did at first, gives an error. 

Using a single string for either of the commands (`lab="one & two"` or `lab="three & four"`) works as expected. 

I have only tried this on GR backend, as I seem to have broken my python installation and unicodeplots doesn't seem to support a vector of labels. REPL and IJulia behave the same. Julia 0.6.0 on Mac OS, and now Plots 0.15.0.

**Comment by apalugniok** [comment]
```
using Plots
plot(randn(10,2), lab=["one" "two"])
plot!(randn(10,2) .- 2, lab=["three" "four"])
```
Will produce what you'd like. 

As for why the way presented does something weird. Plots interprets every column as belonging to a single series. So when you pass a 1 column vector that vector of labels gets copied as the label for each series. 
e.g.
```
using Plots
plot(randn(10,2), lab=["one", "two"])
p = plot!(randn(10,2) .- 2, lab=["three", "four", "five", "six"]) 
p[1][3][:label] # accessing the label for the third series

4-element Array{String,1}:
 "three"
 "four" 
 "five" 
 "six"  
```

GR attempts to access this vector to get a single label using the series index (which causes an error if it's not long enough), PyPlot will interpret the whole vector as the label. 
![example](https://user-images.githubusercontent.com/22132297/35183891-ec8d16ee-fde4-11e7-9b2f-0f686efa568d.png)
I think the PyPlot behavior is more correct given what Plots is (and I guess should be 😆 ) doing. So in my opinion we should make GR behave in line with PyPlot @mkborregaard, @daschw ?

**Comment by improbable22** [comment]
Ah, thank you, I would never have guessed! 

I always forget that vectors are thought of as columns, not just one-index objects... but given that, PyPlot's behaviour makes sense, and agrees with how `plot(::Matrix)` works.

**Comment by daschw** [comment]
PyPlot definitely has the "correct" behaviour, althoug I doubt that passing a Vector of Strings is really is intended in many cases. Maybe we should add a warning, asking the users if they wanted to pass a RowVector.

**Comment by pkofod** [comment]
> PyPlot definitely has the "correct" behaviour, althoug I doubt that passing a Vector of Strings is really intended in many cases. Maybe we should add a warning, asking the users if they wanted to pass a RowVector.

I think it makes most sense to allow a vector to be passed without warning. Either we let the possibility remain, and in that case it would be super annoying to receive a warning if it's intentional, or we make it an error, or we try to convert it ourselves which I think is dangerous.

I vote for enforcing the behavior PyPlot currently has in all backends if possible, or we make it an error to pass a vector. Given the fact that many people seem to forget the whole "series are columns", it might be more pedagogical to simply error here.

**Comment by t-bltg** [comment]
Correct way to plot specified by https://github.com/JuliaPlots/Plots.jl/issues/1367#issuecomment-359171493.
