### ISSUE TITLE
Multiple y axes

### ISSUE THREAD

**Issue by Cody-G** [JuliaPlots/Plots.jl#1372]
Are multiple y axes currently supported by Plots?  I can't seem to find it anywhere.  I mean something like this:

https://plot.ly/python/multiple-axes/

Thanks!

**Comment by lnacquaroli** [comment]
Not sure if they are supported by all backends and to what extent. cf https://github.com/JuliaPlots/Plots.jl/issues/594, https://github.com/JuliaPlots/Plots.jl/issues/1276, https://github.com/JuliaPlots/Plots.jl/issues/1081

**Comment by mkborregaard** [comment]
Should work

**Comment by Cody-G** [comment]
Forgot to say thanks for this!
