### ISSUE TITLE
Plots.jl seems to be broken due to Compat.jl

### ISSUE THREAD

**Issue by timmyfaraday** [JuliaPlots/Plots.jl#1373]
After updating the Plots.jl package, I'm unable to compile it and that seems to be due to the Compat package. 

**
INFO: Precompiling module Plots.
WARNING: Module Compat with uuid 811512619681548 is missing from the cache.
This may mean module Compat does not support precompilation but is imported by a module that does.
ERROR: LoadError: 
Declaring __precompile__(false) is not allowed in files that are being precompiled.
** 

Any fixes in the pipeline or what was the last stable version I can install?

with kind regards,

Tom

**Comment by mkborregaard** [comment]
Plots doesn't use compat. We did turn on precompilation though. That error message should be a one-off - could you try again?

**Comment by timmyfaraday** [comment]
Hi, 
Thank you for the quick response.
I have tried "using Plots" again and I got the same error. After which I removed the Compat package and tried again, giving me a similar error message but now stating another package (StaticArray) is the problem.

Tom

**Comment by timmyfaraday** [comment]
Solved. I tried turning it off and on again and it works again. Sorry for the inconvenience.
