### ISSUE TITLE
savefig issues appear again

### ISSUE THREAD

**Issue by emoszkowski** [JuliaPlots/Plots.jl#1384]
Hi all, 

I"m having some issues with savefig from the REPL. The following code produces empty files with GR and Plotly backends:

```
gr()
x = collect(linspace(1,100))
plot(x,x)
savefig("foo.png")

plotly()
plot(x,x)
savefig("foo.pdf")
```

I'm using Mac and have run Pkg.update. Any thoughts on what's going on here?

**Comment by apalugniok** [comment]
Can't reproduce on GR. For Plotly I get `WARNING: _show is not defined for this backend. m=application/pdf` and an empty `foo.pdf`

**Comment by emoszkowski** [comment]
Just checked again and either I was wrong before or GR fixed itself (sorry!). I get the same warning from Plotly.
