### ISSUE TITLE
Make supported attributes table searchable

### ISSUE THREAD

**Issue by crstnbr** [JuliaPlots/Plots.jl#1387]
The tabular visualization of supported attributes for each backend at http://docs.juliaplots.org/latest/supported/ is really useful. However, unfortunately it is an image and thus not searchable (one can't just CTRL + F and search for an attribute).

I think it would be really convenient to change this. Is it possible to replace the image by a native table?

**Comment by mkborregaard** [comment]
Serendipity: https://github.com/JuliaPlots/PlotDocs.jl/pull/72

**Comment by crstnbr** [comment]
Thanks for changing this.
