### ISSUE TITLE
Labels not hiding when desired

### ISSUE THREAD

**Issue by bensetterholm** [JuliaPlots/Plots.jl#1388]
I would like to generate figures that include some, but not all, plotted elements in the legend.  However, I am having trouble hiding items I do not want to appear in the legend.  With the [PyPlot](https://github.com/JuliaPlots/Plots.jl/files/1704904/pyplot.pdf), [GR](https://github.com/JuliaPlots/Plots.jl/files/1704900/gr.pdf), and [PlotlyJS](https://github.com/JuliaPlots/Plots.jl/files/1704903/plotlyjs.pdf) backends, the labels do not disappear with the keyword `label` set to `false`, `:false`, or `nothing`.  When using the [PGFPlots](https://github.com/JuliaPlots/Plots.jl/files/1704901/pgfplots.pdf) backend, the unwanted labels are gone, but the color of the points corresponds in the legend is incorrect.  Finally, the InspectDR backend errors when I set label to a non-string.  Am I doing this wrong?

~~~julia
using Rsvg, Plots
for backend in [:pgfplots, :pyplot, :gr, :plotlyjs, :inspectdr]
    eval(backend)()
    plot()
    for (j, col) in enumerate([:red, :green, :black, :yellow, :blue])
        scatter!([j], [1], color=col, label="$col")
        scatter!([j], [2], color=col, label=false)
        scatter!([j], [3], color=col, label=:false)
        scatter!([j], [4], color=col, label=nothing)
    end
    savefig("$backend.pdf")
end
~~~

**Comment by mkborregaard** [comment]
set `label = ""` or `primary = `false` for the series you don't want to appear in the legend.
