### ISSUE TITLE
Ribbon + steppost/steppre linetype

### ISSUE THREAD

**Issue by DatName** [JuliaPlots/Plots.jl#1393]
With GR backend, using linetype `:steppost` or `:steppre` with `ribbon` results in a wrong plot:
```
xs = linspace(1,100)
μs = log.(xs)
σs = rand(length(xs))
gr()
plot(plot(xs,μs,ribbon=σs), plot(xs,μs,ribbon=σs, linetype = :steppost), plot(xs,μs,ribbon=σs, linetype = :steppre), layout = (3, 1))
```
![image](https://user-images.githubusercontent.com/3992719/36198898-330e776a-1178-11e8-8d9b-b300ec4f1ae3.png)

**Comment by daschw** [comment]
Thanks a lot for reporting! This should be fixed in #1400
