### ISSUE TITLE
Issues using Plots to make gif

### ISSUE THREAD

**Issue by cmccooey02** [JuliaPlots/Plots.jl#1404]
Im running Julia 0.6 and I am trying to make a gif. This is the code I've run. Everything runs fine until the last line `gif(anim)`. 
`using Plots`
`pyplot(size=(300,200))`
`p = plot([sin,cos], 0, π, lab=[:sin :cos])`
`scatter!(1, lab="")`
`anim = @animate for x in 0:0.1:π`
` p[3] = [x,x], [sin(x),cos(x)]`
`end`
`gif(anim)`

It produces the error 

<img width="704" alt="screen shot 2018-02-21 at 19 17 02" src="https://user-images.githubusercontent.com/34346215/36500856-557fb7a8-173d-11e8-908c-a9ee27ca52ac.png">
Ive tried everything that I can think of, updating packages etc. but it won't work.
I also tried this bit of code 

`using Plots`
`pyplot(size=(300,200))`
`p = plot([sin,cos], 0, π, lab=[:sin :cos])`
`scatter!(1, lab="")`
`anim = @animate for x in 0:0.1:π`
`  p[3] = [x,x], [sin(x),cos(x)]`
`end`
`gif(anim)`

It produces the same error.

**Comment by mkborregaard** [comment]
Do you have ffmpeg installed? 
This might also be a dup of #1392

**Comment by cmccooey02** [comment]
Thanks mkborregaard what you suggested worked. Thanks so much I spent 3 days straight trying to get it to work. I owe you a beer.

**Comment by daschw** [comment]
Many of us owe him a beer 😄
