### ISSUE TITLE
colorbar showing up as a legend

### ISSUE THREAD

**Issue by nassarhuda** [JuliaPlots/Plots.jl#1406]
Essentially, what I need is something like #122 but that's outdated code and I couldn't figure out what needs to change in it so that it produces what I need. Anyway, I tried to do what I need using the colormap keyword and here's a toy example that would allow you to regenerate the figure:

```
using Plots  
pyplot(size=(600,300))  
f = plot()  
for i = 1:length(mapcolors)  
 scatter!(f,rand(10),color = mapcolors[i])  
end  
plot!(f,colorbar=true)    
```
I would have guessed that this should show a colormap, but it doesn't. It shows a legend with the colors.

![colorbar_attempt](https://user-images.githubusercontent.com/12686504/36519988-88cab8be-175c-11e8-891a-cdfbf52bb462.png)

`mapcolors` is an array of RGB values.
For reference, here are the first 20 values:
```
julia> mapcolors[1:20]
20-element Array{ColorTypes.RGB{Float64},1}:
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.619608,0.00392157,0.258824)
 RGB{Float64}(0.661899,0.0508266,0.26882)  
 RGB{Float64}(0.678816,0.0695886,0.272818) 
 RGB{Float64}(0.712649,0.107113,0.280815)  
 RGB{Float64}(0.738024,0.135256,0.286813)  
 RGB{Float64}(0.842445,0.253979,0.307036)  
 RGB{Float64}(0.866282,0.290119,0.297809)  
 RGB{Float64}(0.885352,0.319031,0.290427)  
 RGB{Float64}(0.890119,0.326259,0.288581) 
```
Am I mistaken to assume that this should show a colormap instead of the legend? And is there an easy way to add a colormap to a plot?

Thank you!

**Comment by lnacquaroli** [comment]
I don't see exactly what you would like to do, but https://github.com/JuliaPlots/Plots.jl/pull/1110 might give you a hint?

**Comment by mkborregaard** [comment]
It's easy to implement a colorbar, you need the marker_z argument. But Plots will always stretch colorbars. E.g.
```julia
mapcolors = cgrad([:red, :green, :blue]) #create a custom color gradient if you don't want to use one of the builtin ones
scatter(repeat(1:10, inner = 10), rand(100), marker_z = 1:100, color = mapcolors)
```

**Comment by nassarhuda** [comment]
@mkborregaard Thank you! A slightly different variation of the line you shared worked for me.
@lnacquaroli my issue was that when I use the `colorbar` keyword to show the colorbar, a legend would show up instead, but I was able to fix this by setting `leg=false` and `colorbar=true`. It was just misleading to see the legend of all the colors instead of a colorbar.
