### ISSUE TITLE
horizontal layout issues

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Plots.jl#1412]
On GR, I've found several issues with the horizontal layout, not sure what's going on:

1. `scatter(rand(10), 10*rand(10), dir = :h)`

Here the points are displayed according to the non rotated system and go out of bounds (they don't appear)

2. `density(randn(10000), orientation = :h)` 

For some reason, I get a straight vertical line, which also shows in:

`marginalhist(randn(10000), randn(10000), density = :true)`

And finally [#129](https://github.com/JuliaPlots/StatPlots.jl/issues/129) with `groupedbar`

**Comment by sethaxen** [comment]
This seems to still be the case.

**Comment by sethaxen** [comment]
Just verified that this is also broken for UnicodePlots and Plotly.

**Comment by andreaskoher** [comment]
Thumbs up for this feature :+1: 

I would love to have a horizontal violin plot:

```julia
using StatsPlots
y, z = repeat([1,2,3],outer=100), randn(300)
violin(y,z; orientation = :horizontal)
```
![vertical_violine](https://user-images.githubusercontent.com/18704101/158792285-f0ad5423-b21d-4dc0-bc65-8abd1f4cdfde.png)


```julia
violin(y,z; orientation = :horizontal)
```
![horizontal_violine](https://user-images.githubusercontent.com/18704101/158792315-424b13e2-4a59-4dd8-b16f-a25217c55b25.png)

**Comment by tpgillam** [comment]
For boxplots I added the feature here:

https://github.com/JuliaPlots/StatsPlots.jl/commit/be7f9c03110242707915aaaae8e1e316b179a3d5

Maybe we can just use the same approach for `violin`?
