### ISSUE TITLE
add a dependency on ffmpeg 

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/Plots.jl#1415]
Creating `gif`s requires `ffmpeg`. Right now, any test that involves plotting `gif`s fails on Travis. It would be great to add a dependency on `ffmpeg` to resolve that problem.

**Comment by mkborregaard** [comment]
It's Plots philosophy to support functionality for those users who want it, but stay light by not accumulating dependencies. I'd suggest instead checking for ffmpeg availability and generating an appropriate error message with instructions to install it.

**Comment by yakir12** [comment]
OK. How would one deal with Travis then? I tried adding 
```
addons:
    apt:
        packages:
            - ffmpeg
```
to `.travis.yml` but got `E: Package 'ffmpeg' has no installation candidate`.

**Comment by daschw** [comment]
Apparently `ffmpeg` is not in the official ubunutu trusty repositoriers. Maybe this can help you: https://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/

**Comment by yakir12** [comment]
I'll check it out, but surly someone else needed to include tests for `gif`s in their package?

**Comment by yakir12** [comment]
OK, I simply don't know how to add `ffmpeg` to my Travis run, so I've [asked on discourse](https://discourse.julialang.org/t/how-to-add-ffmpeg-to-travis/9366?u=yakir12). This is clearly a CI question, not an issue. Maybe the answer to my CI question could be added to the documentation of `Plots`.

**Comment by yakir12** [comment]
I'll thus close this now :)

**Comment by yakir12** [comment]
I'm not sure I know what I'm talking about but:
You know how with some packages after we Pkg.add them, there can come up a sudo request in the REPL about some system-wide install? *That* would be a pretty cool solution because the user will hardly need to do anything.

**Comment by pkofod** [comment]
> You know how with some packages after we Pkg.add them, there can come up a sudo request in the REPL about some system-wide install? That would be a pretty cool solution because the user will hardly need to do anything.

across platforms?

**Comment by yakir12** [comment]
right...

**Comment by SimonDanisch** [comment]
I would recommend to depend on VideoIO, which has ffmpeg as a dependency and tries to install it cross platform... Only issue is, that [it doesn't work on 0.6 in a stable way right now](https://github.com/kmsquire/VideoIO.jl/pull/113)... But fixing VideoIO seems to be the right approach for this!

**Comment by yakir12** [comment]
I agree. But that is a dependency Plots.jl might avoid. 

The way I think of this is that this should be an IO issue: Plots create "animations", the user wants to save them as a gif/mp4/webm/wmv etc... 

In a way this is similar to the layering PlotRecipes created: a custom module has its own types, you cerate recipes to tell Plots how to plot them, there should be recipes to how to save them (as in IORecipes)...

**Comment by SimonDanisch** [comment]
That'd be what FileIO does ;) It's just a bit cumversome to hook up ffmpeg!

**Comment by mkborregaard** [comment]
I'm in favour - maybe just wait for 0.7?
