### ISSUE TITLE
heatmap plot function for pgfplots backend

### ISSUE THREAD

**Issue by inarighas** [JuliaPlots/Plots.jl#1421]
hello!

When i call the `heatmap()` function using pgfplots backend i get this error

`The backend must not support the series type Val{:heatmap}, and there isn't a series recipe defined.`

my usage is simple : 

```
Using Plots
pgfplots()
heatmap(matrix)
```

**Comment by mkborregaard** [comment]
Yes, heatmap is not defined for pgfplots. Which is silly because pgfplots itself supports it.

**Comment by daschw** [comment]
For backends that do not support `heatmap` you can use the `plots_heatmap` recipe instead.
```
using Plots
pgfplots()
x = y = linspace(-π, π, 20)
z = cos.(x') .+ sin.(y)
plots_heatmap(z)
```
Performance is not that great for bigger matrices though.

**Comment by BeastyBlacksmith** [comment]
It is implemented for the pgfplotsx-backend
