### ISSUE TITLE
Plotting a polygon with infinite vertices does not plot the polygon

### ISSUE THREAD

**Issue by dpsanders** [JuliaPlots/Plots.jl#1422]
e.g.
```
plot([1, 2, 2, 1], [Inf, Inf, 6, 5], seriestype=:shape, ylim=(-10,10))
```

It should clip the filled polygon to the viewing area.

**Comment by mkborregaard** [comment]
Infinite objects that plot to the plot limits but don't change them are a recurrent feature request (cc @goretkin ) , see e.g. https://github.com/JuliaPlots/Plots.jl/issues/1374, https://github.com/JuliaPlots/Plots.jl/pull/1316 , https://github.com/JuliaPlots/Plots.jl/issues/1297

Could be nice to implement it some way.
