### ISSUE TITLE
Feature request: stacked area plot

### ISSUE THREAD

**Issue by MFairley** [JuliaPlots/Plots.jl#1423]
Would it be possible to create a convenient way to create stacked area plots? E.g. http://johnmyleswhite.github.io/Vega.jl/areaplot.html 

A normalize option would be very useful to create a 100% stacked area plot.

**Comment by mkborregaard** [comment]
I'm pretty sure we have that functionality? Let me check.

**Comment by mkborregaard** [comment]
Could you look at this and say if that comes close or you'd need something else?
https://github.com/JuliaPlots/PlotRecipes.jl#portfolio-composition-maps

**Comment by MFairley** [comment]
Yes, that recipe is working for me. I modified it slightly for my use by switching sx and sy. I also see that PyPlot as a stackplot function but it is not exported by Plots.

**Comment by pkofod** [comment]
> I also see that PyPlot as a stackplot function but it is not exported by Plots.

Plots doesn't really use PyPlot to draw what you see, recipes define the different plots you can chose from.

**Comment by niclasmattsson** [comment]
I need to make stacked area plots too. A simple cut & paste of the recipe linked above into "teststacked.jl" gave me the following error:

```
julia> include("teststacked.jl")
ERROR: LoadError: MethodError: no method matching transpose(::String)
Closest candidates are:
  transpose(::BitArray{2}) at linalg\bitarray.jl:265
  transpose(::Missings.Missing) at C:\Users\niclas\.julia\v0.6\Missings\src\Missings.jl:92
  transpose(::ForwardDiff.Dual{T,V,N} where N where V<:Real) where T at C:\Users\niclas\.julia\v0.6\ForwardDiff\src\dual.jl:166
  ...
Stacktrace:
 [1] _getindex at .\abstractarray.jl:907 [inlined]
 [2] getindex at .\abstractarray.jl:883 [inlined]
 [3] slice_arg(::RowVector{Any,ConjArray{String,1,Array{String,1}}}, ::Int64) at C:\Users\niclas\.julia\v0.6\Plots\src\args.jl:1145
 [4] slice_arg!(::Dict{Symbol,Any}, ::Dict{Symbol,Any}, ::Symbol, ::String, ::Int64, ::Bool) at C:\Users\niclas\.julia\v0.6\Plots\src\args.jl:1157
 [5] _add_defaults!(::Dict{Symbol,Any}, ::Plots.Plot{Plots.GRBackend}, ::Plots.Subplot{Plots.GRBackend}, ::Int64) at C:\Users\niclas\.julia\v0.6\Plots\src\args.jl:1481
 [6] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{PlotRecipes.PortfolioComposition}) at C:\Users\niclas\.julia\v0.6\Plots\src\plot.jl:227
 [7] (::RecipesBase.#kw##plot)(::Array{Any,1}, ::RecipesBase.#plot, ::PlotRecipes.PortfolioComposition) at .\<missing>:0
 [8] #portfoliocomposition#45(::Array{Any,1}, ::Function, ::Array{Float64,2}, ::Vararg{Any,N} where N) at C:\Users\niclas\.julia\v0.6\RecipesBase\src\RecipesBase.jl:363
 [9] (::PlotRecipes.#kw##portfoliocomposition)(::Array{Any,1}, ::PlotRecipes.#portfoliocomposition, ::Array{Float64,2}, ::Vararg{Any,N} where N) at .\<missing>:0
 [10] include_from_node1(::String) at .\loading.jl:576
 [11] include(::String) at .\sysimg.jl:14
while loading C:\Stuff\Julia\teststacked.jl, in expression starting on line 9
```
I'm running Julia 0.6.2 on Windows 10 with updated packages. Any idea as to what the problem may be?

**Comment by niclasmattsson** [comment]
That example results in an error on Julia 0.6.2 (`ERROR: MethodError: no method matching transpose(::String)`). Here's a fix:
```
using PlotRecipes
tickers = ["IBM" "Google" "Apple" "Intel"]
N = 10
D = length(tickers)
weights = rand(N,D)
weights ./= sum(weights, 2)
returns = sort!((1:N) + D*randn(N))

portfoliocomposition(weights, returns, labels = tickers)
```

A suggestion. Stacked area plots have lots of uses outside the world of finance. How about just calling this recipe `stackedarea()` instead of `portfoliocomposition()`? It would make discovery a lot easier for most users.

**Comment by mkborregaard** [comment]
All of those are good ideas :+1: 
Do you feel like trying your hand at updating the recipe and sending a PR with the name and defaults you're suggesting?

**Comment by mariok90** [comment]
In case a simple stackedarea recipe is still needed. This works fine for me:
´´´

@userplot Areaplot
@recipe function f(a::Areaplot)
    data = cumsum(a.args[1], 2)
    seriestype := :line
    fillrange := 0
    @series begin
        data[:,1]
    end
    for i in 2:size(data, 2)
    @series begin
            fillrange := data[:,i-1]
            data[:,i]
        end
    end
end
´´´

**Comment by mbauman** [comment]
Thanks for posting that @mariok90 — I needed this and your recipe was greatly appreciated.  I updated it for 1.0 and added the ability to pass the x-axis as the first argument to `AreaPlot`:

```julia
@userplot AreaPlot
@recipe function f(a::AreaPlot)
    data = cumsum(a.args[end], dims=2)
    x = length(a.args) == 1 ? (1:size(data, 1)) : a.args[1]
    seriestype := :line
    fillrange := 0
    @series begin
        x, data[:,1]
    end
    for i in 2:size(data, 2)
        @series begin
            fillrange := data[:,i-1]
            x, data[:,i]
        end
    end
end
```

Use like `plot(AreaPlot([-5:5, rand(11, 3)]))`.

**Comment by daschw** [comment]
> Use like `plot(AreaPlot([-5:5, rand(11, 3)]))`

or
```julia
areaplot(-5:5, rand(11, 3))
```
(or
```julia
areaplot!(-5:5, rand(11, 3))
```
to add to an existing plot)

**Comment by junglegobs** [comment]
I tried using the `portfoliocomposition` recipe recently and I got the following error:
```julia
julia> using Plots

julia> x = [1 2 3]
1×3 Array{Int64,2}:
 1  2  3

julia> y = rand(3,3)
3×3 Array{Float64,2}:
 0.403945   0.734758  0.702108
 0.480646   0.192144  0.323393
 0.0790197  0.450067  0.812049

julia> portfoliocomposition(x,y)
ERROR: UndefKeywordError: keyword argument dims not assigned
```
Which seems very weird...

I would also like to second the suggestion that `portfoliocompositon` be changed to something more general.

> Use like `plot(AreaPlot([-5:5, rand(11, 3)]))`.

Is this recipe available as part of Plots? Do I need to add a package to use it or currently do I just need to define the above recipe myself?

**Comment by mkborregaard** [comment]
We should just add the AreaPlot as a recipe to Plots.
The error is a pre-post julia-1.0 thing I think.
