### ISSUE TITLE
Runtime Error R6034

### ISSUE THREAD

**Issue by programistawpf** [JuliaPlots/Plots.jl#1424]
![error6034](https://user-images.githubusercontent.com/5564741/37031884-dbb9dddc-2140-11e8-8565-742e9c2302c3.png)
Win7
Paul

**Comment by daschw** [comment]
I'm not sure, but I suppose you are using the `PyPlot` backend, which in the current version is not working properly on Windows.
You can either install and use another backend (e.g. `Pkg.add("GR")`) or pin `PyPlot` to the latest working version `Pkg.pin("PyPlot", v"2.3.1")`.

**Comment by programistawpf** [comment]
yes, pin... helps, it working in gr mode!
Thanks, Paul

**Comment by lnacquaroli** [comment]
(Reported here https://github.com/JuliaPy/PyPlot.jl/issues/334)

I tried yesterday on a Win10 with Anaconda3 and it worked for me after doing `Pkg.update()`.

![plots](https://user-images.githubusercontent.com/26485264/37163920-019bfd1e-22c7-11e8-9a21-a369e3b905ab.png)
![pyplot](https://user-images.githubusercontent.com/26485264/37163922-01ac5ad8-22c7-11e8-94d0-b78dc4489f15.png)

**Comment by programistawpf** [comment]
Version 0.6.2 (2017-12-13 18:08 UTC)
Official http://julialang.org/ release
x86_64-w64-mingw32

julia> using Plots

julia> pyplot()
Plots.PyPlotBackend()

julia> plot(rand(100))
C:\Users\PC\.julia\v0.6\Conda\deps\usr\lib\site-packages\matplotlib\figure.py:418: 
UserWarning: matplotlib is currently
using a non-GUI backend, so cannot show the figure
   "matplotlib is currently using a non-GUI backend, "

julia> Pkg.status("PyPlot")
  - PyPlot                        2.3.1 pinned.3cbfe1a2.tmp


Paul

W dniu 2018-03-08 o 17:52, Leandro Acquaroli pisze:

**Comment by lnacquaroli** [comment]
Note I am using the last PyPlot version though.

**Comment by isentropic** [comment]
@programistawpf is this still a relevant issue?
Feel free to comment and reopen if it is
