### ISSUE TITLE
Unevenly spaced x and/or y displayed as even in heatmap  GR

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/Plots.jl#1428]
Consider plotting a heatmap when the the axes are not evenly spaced:
```julia
using Plots
gr()
x = [1,2,3,4,5]
y = [1,3,5,7,15]
z = x .+ y'
heatmap(x, y, z)
```
wrongly results in:
![screenshot_2018-03-09_22 13 02](https://user-images.githubusercontent.com/3281957/37230264-165a0e14-23e7-11e8-8143-a677abc45569.png)
While the plotly backend correctly results in:
![screenshot_2018-03-09_22 11 39](https://user-images.githubusercontent.com/3281957/37230275-2963bfaa-23e7-11e8-8ce2-069fb88cd04f.png)
(these are screenshots)

**Comment by mkborregaard** [comment]
But is the plotly one really "correct"? What are the borders you'd expect the turnover between categories to correspond to? It doesn't even look like 15 is in the middle on the top category for plotly. I'd say this is a bit hard to define.

**Comment by mkborregaard** [comment]
`histogram2d` which uses some of this functionality assumes that the number is always at the center of the cell

**Comment by mkborregaard** [comment]
But GR's behaviour is clearly wrong:
```
using PlotRecipes
marginalhist(randn(10000), randn(10000), bins = [-4,-2,-1,0,0.5,2,5])
```
<img width="590" alt="skaermbillede 2018-03-10 kl 12 39 54" src="https://user-images.githubusercontent.com/8429802/37241848-3e2bb61c-2460-11e8-9d4b-9b0c7299f178.png">
This looks very wrong, note also the coloring of the marginal histograms
This is completely wrong in Plotly too, it seems the axes become automatically linked:
<img width="620" alt="skaermbillede 2018-03-10 kl 12 41 56" src="https://user-images.githubusercontent.com/8429802/37241866-725cc2be-2460-11e8-85f6-5711e7a18a76.png">

Really terrible.

**Comment by yakir12** [comment]
Yea, I see what you mean about Plotly. I guess I was just checking to see if the colored patches were unevenly sized (which they are). Tricky.

**Comment by aramirezreyes** [comment]
Is there some work going on regarding this behavior?

**Comment by mkborregaard** [comment]
If it's not fixed yet then most likely not. Are you trying to take a look?

**Comment by lmh91** [comment]
At last JuliaCon I talked to @jheinen regarding uneven spaced heatmaps with GR. 
I suggested to take the edges of the 'pixels' for the x and y axes as input.
He added the desired behaviour in GR.jl. Thanks!

```julia
using GR
using StatsBase: midpoints

x_edges = Float64[0, 1, 6, 6.5, 10]
y_edges = Float64[0, 1, 4, 8]
z = midpoints(x_edges) .+ midpoints(y_edges)'

heatmap(x_edges, y_edges, z')
```
![gr_uneven_spaced_heatmap](https://user-images.githubusercontent.com/16963906/67852221-5114ae80-fb0c-11e9-8973-79e000cea051.png)

However, it is not yet integrated into Plots.jl. 
I will try to add it if I find some free time, but I don't have any experience with Plots so far so it might take a while.

**Comment by mkborregaard** [comment]
This definitely used to work in Plots

**Comment by daschw** [comment]
> This definitely used to work in Plots

not for GR, I think.

**Comment by lmh91** [comment]
I think I managed to implement it (See PR #2234). At least for the cartesian case.

```julia
using Plots; gr()
using StatsBase: midpoints

x_edges = Float64[0, 1, 6, 6.5, 10]
y_edges = Float64[0, 1, 4, 8]
x_midpoints = midpoints(x_edges)
y_midpoints = midpoints(y_edges)
z = x_midpoints .+ y_midpoints'

plot(
    heatmap(z', title = "Indices as Midpints"),
    heatmap(x_midpoints, y_midpoints, z', title = "x & y as Midpints"),
    heatmap(x_edges, y_edges, z', title = "x & y as Edges"),
    size = (1200, 300), layout = (1, 3)
)
```
![plots_gr_heatmap_nonuniform](https://user-images.githubusercontent.com/16963906/68021035-9d90f300-fca0-11e9-8c28-aabdf64fb4d2.png)

I think for polar heatmaps this is not yet possible in GR itself.
