### ISSUE TITLE
pyplot() command fails to determine the matplotlib version

### ISSUE THREAD

**Issue by jhrabe** [JuliaPlots/Plots.jl#1432]
using PyPlot works fine but when I try to switch to PyPlot backend in Plots, the following message appears and plotting does not work:

WARNING: You are using Matplotlib 0.0.0, which is no longer officialy supported by the Plots community. To ensure smooth Plots.jl integration update your Matplotlib library to a version >= 2.0.0

The installed version is 2.1.0.  My system is up-to-date Gentoo Linux, Python versions 2.7 and 3.5.

**Comment by daschw** [comment]
This seems to be a https://github.com/JuliaPy/PyPlot.jl issue.
See also: https://github.com/JuliaPlots/Plots.jl/issues/1248 and https://github.com/JuliaPy/PyCall.jl/issues/448
cc: @stevengj

**Comment by jhrabe** [comment]
I don't think the suggested solution (https://github.com/JuliaPy/PyPlot.jl/commit/2476177334dd0640711c2ca5d2c5c6bb0dc3c317) will work on Gentoo.  The version string on my machine is "2.1.0-python3_5" so it would have to be split not just on '.' but also on '-', something like 
parts = split(mvers, ['.', '-'])

**Comment by daschw** [comment]
In any case, this should be solved over at PyPlot.jl. I'm sure that the folks there would be happy about a PR implementing your suggested splitting.

**Comment by stevengj** [comment]
`2.1.0-python3_5` doesn't parse using the built-in `VersionNumber` Julia type, because [underscores aren't allowed in the semver spec](https://semver.org/spec/v2.0.0.html#spec-item-9).

I'm working on a package that implements more permissive parsing of version numbers, which I'm hoping to switch to.

**Comment by stevengj** [comment]
See JuliaLang/METADATA.jl#13863 and https://github.com/stevengj/VersionParsing.jl

**Comment by jhrabe** [comment]
After Pkg.clone("https://github.com/stevengj/VersionParsing.jl"), the PyPlot and Plots work both fine for me.  Thanks!
