### ISSUE TITLE
Categorical scatter plot missing points with ticks=:native on PlotlyJS

### ISSUE THREAD

**Issue by cstjean** [JuliaPlots/Plots.jl#1435]
```julia
plotlyjs()
scatter([1,2,3], ["a", "a", "a"], ticks=:native)
```
![image](https://user-images.githubusercontent.com/8622776/37489129-0d0eb19a-286d-11e8-8911-1ca622ff034a.png)

cc. @apalugniok

**Comment by cstjean** [comment]
And with `pyplot()`, the points are shown, but the axes are both numerical.

**Comment by apalugniok** [comment]
@daschw looks like discrete values doesn't work everywhere 😆. The implementation is a bit hacky as we are using `discrete_values` for the data points but these seems to ignore duplicates. 

PyPlot was doing some odd stuff with categorical axes (see https://github.com/JuliaPlots/Plots.jl/pull/1395#issuecomment-367979328). Also `ticks = :native` was not adding any new behavior when compared to Plots for categorical axes in PyPlot. So we decided not to implement native categorical axes in that case.

**Comment by daschw** [comment]
We could reconstruct the original categorical data using the numerical data and `discrete_values` somehow similar to this:
```julia
xdata = rand(["a", "b", "c"], 10)
ydata = rand(10)
p = scatter(xdata, ydata)
discrete_values = p[1].attr[:xaxis][:discrete_values] # ["a", "b", "c"]
x = p[1][1][:x] # 10-element numerical vector with values (0.5, 1.5, 2.5) corresponding to ("a", "b", "c")
backend_discrete_values = [discrete_values[findfirst(eachindex(discrete_values) .> xi)] for xi in x]
backend_discrete_values == xdata # true
```
Not sure, if this can be used to fix the issue ...
