### ISSUE TITLE
How to move labels to down-right corrner ?

### ISSUE THREAD

**Issue by programistawpf** [JuliaPlots/Plots.jl#1439]
How to move labels to down-right corrner ?
plot!(Ft,title="Model", label="forecast")

now is in up-right part o chart
Paul

**Comment by daschw** [comment]
`legend = :bottomright`

**Comment by daschw** [comment]
Also, for simle questions like this I recommend the Plots.jl Gitter channel https://gitter.im/tbreloff/Plots.jl or the plotting channel(s) in the JuliaLang Slack https://julialang.slack.com/
