### ISSUE TITLE
Problem with changing size of first  for  ...plot(p1,p2)

### ISSUE THREAD

**Issue by programistawpf** [JuliaPlots/Plots.jl#1444]
```julia
julia> p1=plot(rand(5));
julia> plot(p1)
julia> p2=scatter(rand(5,5));
julia> plot(p1,p2) #  is OK
julia> p1=plot!(rand(5));
julia> plot(p1,p2) # here size pf firs plot is changing 
```

Is any idea ?
Paul
![plot_size](https://user-images.githubusercontent.com/5564741/37570775-56756ef8-2af4-11e8-8696-8670bb103f67.png)

**Comment by mkborregaard** [comment]
Do `p1=plot!(rand(5), subplot = 1)` to make sure you only plot to the first subplot.
Also, those Plots look terrible, you should update your Plots and GR versions. This is how it looks for me:
<img width="600" alt="skaermbillede 2018-03-19 kl 10 51 50" src="https://user-images.githubusercontent.com/8429802/37588789-90cbbbce-2b63-11e8-830d-06b12f23b031.png">

**Comment by programistawpf** [comment]
Thanks, but with subplot = 1 is the same :/
next step ?
I have ver 6.0 on Win 7 , after Pkg.update(), how to upgrade GR ?


Paul


using Plots
p1=plot(rand(5));
plot(p1)
p2=scatter(rand(5,5));
plot(p1,p2) #  is OK
p1=plot!(rand(5),subplot = 1);
plot(p1,p2) # here size pf firs plot is changing

W dniu 2018-03-19 o 10:52, Michael Krabbe Borregaard pisze:
