### ISSUE TITLE
GR ignores levels in contourf

### ISSUE THREAD

**Issue by massemanet** [JuliaPlots/Plots.jl#1449]
So this awesome code;
```
using Plots; x = y = linspace(0,1,100)
function plotte(x, y) 
       plot(contourf(x, y, +; levels = collect(linspace(0,2,5))),
            contourf(x, y, +; levels = collect(logspace(-1,0.3,5))),
            size = (800, 400))
       end
gr() ; plotte(x, y)
pyplot() ; plotte(x, y)
```

![screen shot 2018-03-22 at 10 30 16](https://user-images.githubusercontent.com/12678/37762255-0d0f90fc-2dbc-11e8-967f-d996e9062420.png)

gr() version on top. I expected to plots to be more similar. Seems gr() ignores the levels(?)

**Comment by mkborregaard** [comment]
It has to do with the way GR shows contours - it's a GR thing, not Plots.

**Comment by mkborregaard** [comment]
Closing as dup of https://github.com/JuliaPlots/Plots.jl/issues/1024

**Comment by massemanet** [comment]
I don't think it's a dupe (I did look at #1024 before opening this issue).
  The problem here is that the two gr plots should be different from each other, just like the two pyplot plots are.
  the fact that the gr ones are different from the pyplot ones is a dupe.

**Comment by massemanet** [comment]
@mkborregaard can we reopen this? pretty sure it's not a dupe.

**Comment by mkborregaard** [comment]
You're right, sorry I was a bit too fast.

**Comment by mkborregaard** [comment]
Pretty sure it's the same underlying problem/solution though.

**Comment by BeastyBlacksmith** [comment]
should work now
