### ISSUE TITLE
Documentation: setting axis attributes

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#1452]
I couldn't figure out from the documentation how to set attributes on individual axes.
There is a table of Axis attributes and aliases at the [Attributes](http://docs.juliaplots.org/latest/attributes/) page, but it's not clear how to use this information.
Above the table there is a confusing remark "(for example the subplot[:xaxis])" which seems like it might be specific to the pyplot backend.

see [this thread](https://discourse.julialang.org/t/plots-jl-removing-a-single-axis/9897)

**Comment by t-bltg** [comment]
The `Axis` attributes are documented in https://docs.juliaplots.org/latest/generated/attributes_axis/.
