### ISSUE TITLE
How to save png file (no pdf )

### ISSUE THREAD

**Issue by programistawpf** [JuliaPlots/Plots.jl#1455]
Version 0.6.2 (2017-12-13 18:08 UTC)
x86_64-w64-mingw32
Win7

julia> using Plots;gr()
Plots.GRBackend()
julia> plot(rand(10), fmt = :png)
julia> savefig("filename.png")
PNG file is EMPTY
julia> plot(rand(10), fmt = :png)
PDF file is OK
How to save png file ?
Paul

julia> savefig("filename.pdf")

julia>

**Comment by daschw** [comment]
I cannot reproduce this.
Could you provide the output of
```julia
Pkg.status("Plots")
Pkg.status("GR")
versioninfo()
```
?

**Comment by programistawpf** [comment]
julia> Pkg.status("Plots")
  - Plots                         0.16.0+            master

julia> Pkg.status("GR")
  - GR                            0.30.0

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
   OS: Windows (x86_64-w64-mingw32)
   CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
   WORD_SIZE: 64
   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
   LAPACK: libopenblas64_
   LIBM: libopenlibm
   LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
julia> Pkg.status("Plots")
  - Plots                         0.16.0+            master

julia> Pkg.status("GR")
  - GR                            0.30.0

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
   OS: Windows (x86_64-w64-mingw32)
   CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
   WORD_SIZE: 64
   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
   LAPACK: libopenblas64_
   LIBM: libopenlibm
   LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)


W dniu 2018-04-06 o 20:14, Daniel Schwabeneder pisze:
> Pkg.status("Plots")
> Pkg.status("GR")
> versioninfo()
