### ISSUE TITLE
Recipe for StatsBase.Histogram centers on weights, not edges

### ISSUE THREAD

**Issue by pasha2718** [JuliaPlots/Plots.jl#1458]
There appears to be a bug in the recipe that enables a direct `histogram` (or `stephist` or `barhist`) of a `StatsBase.Histogram` object.   When, in Julia 0.62 on Arch Linux, I run `histogram(fit(Histogram, randn(1000))`, the x axis centers around 200.  This turns out to be the center value for the weights, but of course we want the center value of the x axis to be from `edges[1]`, which is zero.  This is true regardless of bins, backend or normalization.  

As a sanity test, `histogram(randn(1000))` works great, centering x on zero.  Thanks for your attention.

**Comment by daschw** [comment]
`plot(fit(Histogram, randn(1000))` should work fine.

**Comment by mkborregaard** [comment]
Can this be closed then?
