### ISSUE TITLE
How to draw an image and heatmap side by side in IJulia

### ISSUE THREAD

**Issue by ereday** [JuliaPlots/Plots.jl#1463]
Hi,

I am trying to display an image a heatmap side by side on the IJulia notebook. I can display the heat map successfully but I have problems with displaying the image and putting it side-by-side. 

The following code works fine to display the heatmap.
```
using Plots
x = rand(3,4)
heatmap(x)
```

To display the image I tried the following but it did not work (no visual output):
```
using Images
plot(load(download("http://farm1.static.flickr.com/64/168461914_afe4852372.jpg")))

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  168k  100  168k    0     0   396k      0 --:--:-- --:--:-- --:--:--  395k
INFO: Precompiling module PlotlyJS.
WARNING: deprecated syntax "inner constructor Client(...) around /home/ec2-user/.julia/v0.6/HttpServer/src/HttpServer.jl:114".
Use "Client{T}(...) where T" instead.
```

So, I wonder how to combine these two and out them side by side ?

**Comment by daschw** [comment]
To plot different plots side by side just put them inside a `plot(...)` call. See http://docs.juliaplots.org/latest/layouts/ if you want to create advanced subplot layouts.

I'm not sure why your image plotting command does not show anything. For me
```julia
using Plots, Images
plotlyjs()
x = rand(3, 4)
img = load(download("http://farm1.static.flickr.com/64/168461914_afe4852372.jpg"))
plot(heatmap(x), plot(img))
```
works in jupyter. You could maybe also try to use `plotly()` instead of `plotlyjs()` or another backend

**Comment by Evizero** [comment]
xpost https://github.com/JuliaImages/Images.jl/issues/710
