### ISSUE TITLE
Position of inset when axis is extended

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPlots/Plots.jl#1468]
The coordinates of the inset box are read from the specified axis range without taking into account adjustments.
![screenshot from 2018-04-03 09-19-29](https://user-images.githubusercontent.com/22725744/38235089-32f80b38-3720-11e8-972c-c6509b0c8fb9.png)

When there is no adjustments of the axis, it works fine, e.g.
```julia
plot(x->sin(x),0, 1, inset=(1,bbox(0,0,0.5,0.5,:left,:bottom)))
```

**Comment by BeastyBlacksmith** [comment]
This seems to be fixed on the current version of Plots. If you still encounter this issue, please reopen.
