### ISSUE TITLE
Surface using hdf5 backend

### ISSUE THREAD

**Issue by goldnd** [JuliaPlots/Plots.jl#1470]
It appears that surfaces don't work with the hdf5 backend.  This example fails:
```julia
using HDF5
using Plots
hdf5()
x = y = linspace(-5, 5, 40)
zs = zeros(0,40)
n = 100
i = 1
f(x,y) = sin(x + 10sin(i)) + cos(y)

# create a plot with 3 subplots and a custom layout
l = @layout [a{0.7w} b; c{0.2h}]
p = plot(x, y, f, st = [:surface, :contourf], layout=l)

Plots.hdf5plot_write(p, "temp.hdf5");
```
with this message:
ERROR: MethodError: no method matching write(::HDF5.HDF5Group, ::String, ::Plots.Surface{Array{Float64,2}})
Closest candidates are:
  write(::Union{HDF5.HDF5File, HDF5.HDF5Group}, ::String, ::Any, ::String, ::Any, ::Any...) at /Users/dect/.julia/v0.6/HDF5/src/HDF5.jl:1576
  write(::AbstractString, ::Any...) at io.jl:152
  write(::IO, ::Any...) at io.jl:286

**Comment by ma-laforge** [comment]
Thanks for letting me know.  I will try to take a look at this in the following few days.

**Comment by ma-laforge** [comment]
@goldnd : Please give PR https://github.com/JuliaPlots/Plots.jl/pull/1480 a try with your configuration.

See comments in PR for more details.
