### ISSUE TITLE
problem with: display(plot(...)) in win 8 and win 10 , sombody use it ?

### ISSUE THREAD

**Issue by programistawpf** [JuliaPlots/Plots.jl#1472]
Win 10, Win 8 Julia 0.6.2 
```
using Plots ; gr()
plot(rand(5))
```  
working ok !
I have problem with :
```
p1=plot(rand(5))
p2=plot(rand(5))
display(plot(p1,p2,layout=(2,1),wsize=(600,600)))
```
No plots, no window. In Win7 is ok!
Somebody using it ?
Paul

**Comment by daschw** [comment]
I cannot reproduce this on Windows 10.
However it is a known issue for GR that, once you close a GKS window, you have to restart julia for the plots to show up again. Could it be that you closed the window?

**Comment by programistawpf** [comment]
No, but maybe on this machine was instaled julia 32 on 64 system , a 
must check it - it was no my machine
Paul

W dniu 2018-04-06 o 18:53, Daniel Schwabeneder pisze:

**Comment by ChrisRackauckas** [comment]
>However it is a known issue for GR that, once you close a GKS window, you have to restart julia for the plots to show up again. Could it be that you closed the window?

That's no longer the case.

**Comment by daschw** [comment]
> That's no longer the case.

For me it is. Do I have to do anything special to avoid this?

**Comment by ChrisRackauckas** [comment]
@jheinen do people have to rebuild to get the new GUI?

**Comment by jheinen** [comment]
Yes - or wait for GR 0.31.0 (this weekend) and `Pkg.update()`

**Comment by daschw** [comment]
```julia
ENV["GRDIR"] = ""
ENV["GKSwstype"]="gksqt"
Pkg.build("GR")
```
today did not solve this for me on Win10, julia 0.6. Am I missing something?

**Comment by daschw** [comment]
Oh, now I tried again and it is solved.
Sorry for the noise.
