### ISSUE TITLE
xlims and xlabel not working in plotlyjs

### ISSUE THREAD

**Issue by leoll2** [JuliaPlots/Plots.jl#1485]
I've already documented the issue [here](https://discourse.julialang.org/t/axes-attributes-labels-limits-not-working-in-3d-plots/10341).

Basically, when using plotlyjs as backend to draw 3d graphs, the xlims and xlabel attributes don't work, although they're supported according to [this list](http://docs.juliaplots.org/latest/supported/).
On the other side, 2d plots work fine.
Here's a picture:

<img src="https://discourse-cdn-sjc1.com/business5/uploads/julialang/original/2X/9/90d8f931a3f4e7de5b3ae29ad49a58691c0de1c0.JPG"></img>

And here's the code to reproduce the issue:

`using Plots

plotlyjs()

x = [2,3,4,1]
y = [8,3,1,2]
z = [4,5,3,4]

p1 = plot(x, y, seriestype=:scatter,
        title="Hello!", xlabel = "xlabel", ylabel="ylabel",
        xlims=(0.0, 6.5), ylims=(0.0,9.0))
p2 = plot(x, y, z, seriestype=:scatter,
        title="Hello!", xlabel="xlabel",ylabel="ylabel", zlabel="zlabel",
        xlims=(0.0, 80.5), ylims=(0.0,9.0), zlims=(0.0,5.0))

`

Finally, I'd like to stress the usefulness of this feature and why it'd be important for me (and others) to fix as soon as possible. I use graphs to dynamically represent an evolving data set (scatter points). Without xlims, it's very hard for me to visualize the fluctuations in the data, since the axes keep re-scaling according to the extremal values in the set.

**Comment by juliohm** [comment]
Not only with `plotlyjs`, the `xlabel` attribute is not working with plot recipes in GR either:

```julia
using Variography

foo = EmpiricalVariogram(eye(3), ones(3))

plot(foo, xlab="foo") # xlab is ignored
```

**Comment by BoundaryValueProblems** [comment]
Using ```scatter``` in 3D as @leoll2 did, ```xlabel, ylabel, zlabel``` work as expected under both pyplot and gr backends, but not under plotlyjs backend at this point. It's quite strange though. It worked in January 2018. I have a script/function to do some 3D scatter plot, and I have a pdf file generated in January 2018, where I could see the plotlyjs backend did correct axis labeling. Now, the same script does not render ```xlabel, ylabel, zlabel``` as I specified. Instead, it shows simply, ```x, y, z``` on the plot. I'm currently using PlotlyJS.jl version 0.10.2 (master) with Plots.jl 0.17.0+ (master).

**Comment by mkborregaard** [comment]
Hm, it looks as if the axis `title` attribute is being correctly set - is there a change to how this is done in plotlyjs? The 3d examples http://spencerlyon.com/PlotlyJS.jl/examples/3d/ only show x, y and z on the axes.

**Comment by BoundaryValueProblems** [comment]
@mkborregaard , I communicated with @sglyon about this problem, and he gave me the following answer at https://github.com/sglyon/PlotlyJS.jl/issues/189 , i.e.,

> After looking at the json generated by Plots.jl , I think the problem is that Plots is setting properties on ```layout.scene.(x|y|z)axis1``` instead of ```layout.scene.(x|y|z)axis``` -- the addition of the ```1``` is messing things up.

Could you or @daschw check if removing ```1``` from the above is possible and solve this problem? I could not nail which file in ```Plots.jl``` sets this. Thanks a lot!

**Comment by mkborregaard** [comment]
That happens here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/plotly.jl#L361-L363
It looks like it happens on purpose, for when there are more than one subplot. Did the plotly specification change?

**Comment by mkborregaard** [comment]
This is apparently due to a change in the plotlyjs specification, where it's only called "xaxis" IF there's only one subplot. Plots' series don't know about subplots, but one solution could be to just always have both keys in there. 
Easy PR I guess.

**Comment by daschw** [comment]
What's the problem with checking  for `length(plt.subplots) > 1`?

**Comment by mkborregaard** [comment]
I guess you could do that, and then revisit if used in `p = scatter(randn(10)); p2 = scatter(randn(20)); plot(p1, p2)`?

**Comment by daschw** [comment]
Ah, ok, will the axes not be updated with `plot(p1, p2)`?

**Comment by mkborregaard** [comment]
I didn't think so but I haven't checked. That would make it easy
