### ISSUE TITLE
Way to make stacked plots with same color and label

### ISSUE THREAD

**Issue by djsegal** [JuliaPlots/Plots.jl#1492]
Let's say you had a plot similar to:

![screen shot 2018-04-21 at 12 29 03 am](https://user-images.githubusercontent.com/3156114/39089244-87d1c2ce-4590-11e8-8682-4710480f0bd0.png)

// this is made by calling `plot!` like ~8 times

------

Is there a way to easily make it so the left and right sets of circles (i.e. the pairs) have matching colors and labels?

(this would be without manually setting color & label arrays)

**Comment by mkborregaard** [comment]
It'd be much easier to comment if you posted the code.

**Comment by djsegal** [comment]
See:

+ https://github.com/djsegal/fusion-binder/blob/master/0_Plasma_Parameters.ipynb

**Comment by mkborregaard** [comment]
It's good practice when asking for coding advice to provide a minimum working example (MWE) that those helping you can copy to their own console and try out in practice. This example is hardly an MWE – so I can't try it out.

But you might attempt `plot!([rrr; NaN; -rrr], [zzr; NaN; zzr])` instead of `plot!(rrr, zzr);plot!(-rrr, zzr)`

**Comment by djsegal** [comment]
Resolved. Closing this.

--------

Start with:

```
using Plots

rr = 1.0
RR = 2.0

aa = linspace(0, 2*pi)
xx = rr * cos.(aa)
yy = rr * sin.(aa)

xx += RR;
```

------

As mentioned in question above, doing:

```
plot(xx,yy)
plot!(-xx,yy)
```

* leads to:

![bad_circles](https://user-images.githubusercontent.com/3156114/39100670-55b84152-465b-11e8-9262-90ab71d24a46.png)

------

Whereas doing something similar to what @mkborregaard suggested gives the proper right result:

```
xx2 = [xx...,NaN,-xx...]
yy2 = [yy...,NaN,yy...]
plot(xx2, yy2)
```

![good_circles](https://user-images.githubusercontent.com/3156114/39100678-7658a7b2-465b-11e8-85b4-0d78b460f6b4.png)

// n.b. the reason the `NaN` is needed is b/c otherwise a line would be drawn connecting the circles

**Comment by mkborregaard** [comment]
Great!
