### ISSUE TITLE
This used to work, but not anymore

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1493]
Could you please explain if anything changed?

```julia
using Plots; gr()

dim, nobs = 2, 50

X = 100*rand(dim, nobs)
z = rand(nobs)

scatter(X[1,:], X[2,:], c=z, label="data")

ERROR: MethodError: no method matching plot_color(::Float64)
Closest candidates are:
  plot_color(::Any, ::Void) at /home/juliohm/.julia/v0.6/PlotUtils/src/colors.jl:15
  plot_color(::Any, ::Number) at /home/juliohm/.julia/v0.6/PlotUtils/src/colors.jl:18
  plot_color(::Symbol) at /home/juliohm/.julia/v0.6/PlotUtils/src/colors.jl:6
```

I've been experiencing many issues with Plots.jl lately. I wonder if we could make more use of visual regression tests whenever a change is made to the codebase.

**Comment by mkborregaard** [comment]
What do you expect that to do? When did it work?
If you're expecting the color of markers to reflect `z`, the Plots syntax has always been `scatter(X[1,:], X[2,:], marker_z=z, label="data")`.

We use VisualRegressionTests as part of our Travis CI system, so all PRs changing syntax or visual appearance of plots must come with an update of the examples and reference images http://docs.juliaplots.org/latest/contributing/#testing
If you've suggestions for improving that it would be interesting.

**Comment by juliohm** [comment]
Interesting, the option `c=z` used to work, it would change the colors of the markers. I will update the examples accordingly to `marker_z`, though this attribute name is not very intuitive to me.

**Comment by mkborregaard** [comment]
You can use the alias `zcolor = z` if you find that more intuitive. The `zcolor` attribute was added in November 2015 and was the official name for the attribute until April 2016, where the main name was changed to `marker_z`. As far as I can tell from the commit history, `color = z` has never worked.
