### ISSUE TITLE
markercolor with vector of colors (pyplot backend)

### ISSUE THREAD

**Issue by rcnlee** [JuliaPlots/Plots.jl#1494]
markercolor with a vector of colors works for ``scatter`` seriestype but not ``line`` or ``path``.  e.g., this doesn't work:
```julia
plot(rand(5),markershape=:rect, seriestype=:path, markercolor=[RGB(r,0.0,1-r) for r in linspace(0.0,1.0,5)])

PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) <type 'exceptions.ValueError'>
ValueError(u'Invalid RGBA argument: [(0.0, 0.0, 1.0, 1.0), (0.25, 0.0, 0.75, 1.0), (0.5, 0.0, 0.5, 1.0), (0.75, 0.0, 0.25, 1.0), (1.0, 0.0, 0.0, 1.0)]',)
  File "/Users/rlee18/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/rlee18/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/figure.py", line 1299, in draw
```

**Comment by mkborregaard** [comment]
what are you expecting it to do? There are no markers with seriestype `:path`

**Comment by rcnlee** [comment]
I was expecting it to produce a line plot with square markers.  Like how it behaves without the markercolor argument, i.e.,
``plot(rand(5),markershape=:rect, seriestype=:path)``
and then markercolor just adjusts the color.

**Comment by mkborregaard** [comment]
Ah, I see what you mean - there's a bug with how pyplot backend deals with colors. Good catch on the difference between seriestypes, that's a good clue for solving it.
