### ISSUE TITLE
Rounded corners with pyplot

### ISSUE THREAD

**Issue by stakaz** [JuliaPlots/Plots.jl#1499]
Hello, when using pyplot I get rounded corners for markers and ugly rounding in errorbars, see the picture.

![screenshot_rounded_corners](https://user-images.githubusercontent.com/998651/39347858-096ac7fa-49f5-11e8-8876-3747e50ecd2c.png)

The code for this is:

```julia
using Plots
pyplot()

default(
markershape = :square,
markersize = 5,
markeralpha = 1.0,
markercolor = :match,
markerstrokewidth = 2,
markerstrokealpha = 1.0,
markerstrokecolor = :auto,
markerstrokestyle = :solid
)

x = [1,2,3,4,6]
y = [0.2,0.4,0.6,0.2,0.8]
yerr = [0.1,0.12,0.14,0.08,0.3]

scatter(x,y,err=yerr,color=:blue)
savefig("test.pdf")
```

Is this a "style" decision and has it something to do with pyplot itself? But with the same matplotlibrc file and using PyPlot I get sharp corners.

Thanks

**Comment by isentropic** [comment]
This pr should fix your issue, additionally the reason why error caps look a little off-center is I believe https://github.com/matplotlib/matplotlib/issues/7233
