### ISSUE TITLE
How to plot a cube in Julia using Plots?

### ISSUE THREAD

**Issue by Graf-Fenryl** [JuliaPlots/Plots.jl#1500]
I am sorry, if this is totally misplaced but I did not find any clue in the docs or the examples.
For example I want to plot a cube with vertices (0,0,0),(0,0,1),(0,1,0),(0,1,1),(1,0,0),(1,1,0),(1,0,1),(1,1,1) such that I get a cube with coloured facets, not just the vertices or lines.
How can I do this?

Just something like this, the facets may have a all the same colour.
![grafik](https://user-images.githubusercontent.com/31442880/39358221-b2e5a10e-4a15-11e8-9581-785066d0bee0.png)

Thanks for your help, I really like the Plots package!

**Comment by milesfrain** [comment]
I've found the easiest way to do this at the moment is with `PlotlyJS`.
Here's the julia code to plot a red unit cube:
```
using PlotlyJS

function mesh_box(l,w,h,x,y,z)
    PlotlyJS.mesh3d(
        x = [x, x+l, x,   x+l, x,   x+l, x,   x+l],
        y = [y, y,   y+w, y+w, y,   y,   y+w, y+w],
        z = [z, z,   z,   z,   z+h, z+h, z+h, z+h],
        i = [0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7],
        j = [3, 3, 5, 5, 6, 6, 3, 3, 5, 5, 6, 6],
        k = [1, 2, 1, 4, 2, 4, 1, 2, 1, 4, 2, 4],
        color = "rgb(200,100,100)",
    )
end

PlotlyJS.plot(
    mesh_box(1,1,1,0,0,0)
)
```

More examples (in python) available here: https://plot.ly/python/3d-mesh/

You could also investigate `ThreeJS`, `Makie`, and `MeshCat`, but I've found those difficult to install in Julia 1.1

**Comment by Graf-Fenryl** [comment]
Thank you very much, that should work as wished =)
