### ISSUE TITLE
Add support for Julia v0.7

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1506]
Could you please help fix this build error in Julia v0.7? I am not sure how to fix it myself.

```julia
ERROR: LoadError: LoadError: TypeError: in SeriesAnnotations, in type definition, expected Type, got typeof(Base.Nullable)
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:314 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1067
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /home/juliohm/.julia/v0.7/Plots/src/Plots.jl:3
 [6] top-level scope
 [7] include at ./boot.jl:314 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1067
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope
 [11] eval at ./boot.jl:317 [inlined]
 [12] top-level scope at ./<missing>:3
in expression starting at /home/juliohm/.julia/v0.7/Plots/src/components.jl:438
in expression starting at /home/juliohm/.julia/v0.7/Plots/src/Plots.jl:157
ERROR: Failed to precompile Plots to /home/juliohm/.julia/compiled/v0.7/Plots.ji.
```

Please let me know if there is a branch with support added.

**Comment by mkborregaard** [comment]
This is due to https://github.com/JuliaLang/julia/pull/23642 i.e. the deprecation of `Nullable`. The fix would seem to be to remove Nullable's throughout on a 0.7-only branch. I've just made one.

When will it be possible to use femtocleaner to do these things automatically?

**Comment by juliohm** [comment]
Thank you @mkborregaard! I checked the branch locally, but still getting the same error. Sorry for the delay to reply, I was in a conference these two last days. Coding during the coffee breaks...

**Comment by mkborregaard** [comment]
Oh I didn't actually do anything I just created the branch. Perhaps it's as easy as find-replacing Nullable{SomeType} to Union{SomeType, Nothing} - I've tried that in #1508 , which you could try to check out?

**Comment by juliohm** [comment]
I pulled the `julia0.7` branch, and patched the last modifications you linked in the PR, but didn't have much success. I will try to export some data and plot Julia v0.6 meanwhile just to get things going during this migration.

**Comment by mkborregaard** [comment]
OK, thanks for giving it a shot

**Comment by ederag** [comment]
What about using the Nullable package https://github.com/JuliaArchive/Nullables.jl ?

**Comment by ederag** [comment]
Sorry, I now see that it was not a mere cleanup of Base, but rather a true deprecation, because of performance issues.

**Comment by RalphAS** [comment]
I have a branch (ras/julia0.7) in my fork (https://github.com/RalphAS/Plots.jl) running under 0.7-alpha, with `gr` and `pyplot` backends on Linux.  (I am using the `julia0.7` branches of `PlotUtils` and `RecipesBase` too.) Since I am working in v0.7 the package management is shaky, so I'm not sure how best to make this useful to the main project.  Can you cherry-pick commits from a fork, or would you like me to attempt a WIP PR?  (looking for advice from @mkborregaard a/o @daschw)

**Comment by vishaluk** [comment]
I got the Julia 9.7 rc2 installed and I am unable to use Plots at all because it gives me the above mentioned error. Is this still an open issue?

**Comment by JeffFessler** [comment]
I just installed the brand new official Julia 0.7 featured on the Julia homepage and got this same error.  It is quite ironic because the "Plots" package is the first one highlighted on Julia's home page!  It is definitely still an open issue!

**Comment by sjmgarnier** [comment]
Same problem as @JeffFessler using the new official Julia 0.7.

**Comment by mkborregaard** [comment]
You're right - the solution for now is `]add Plots#master` but there should be a 0.7 compatible release.
Here's the reason there isn't one yet: Plots has a very extensive test suite that involves quite a lot of packages (that are not dependencies of Plots). If just one of these packages is not yet 0.7 ready, Travis CI will fail for Plots though in fact Plots generally works perfectly - and you can't release a package with failing tests. We're on it.

**Comment by mkborregaard** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16449

**Comment by JeffFessler** [comment]
With both Julia 0.7.0 and 1.0.0,  Plots v0.19.2 seems to be working fine now at least with default gr() backend. Thanks!
