### ISSUE TITLE
Bar plot with strings on x-axis not working

### ISSUE THREAD

**Issue by ezgikurt** [JuliaPlots/Plots.jl#1516]
Hi, I'm trying a basic horizontal bar chart with plotlyjs().
`plot4 = bar(var_names[:,1], averages[:,5:7], orientation = :h)` 
where var_names is a DataArray{Any,2} of strings, but I run into the following error:

`ERROR: In convertToAnyVector, could not handle the argument types: (String,)
 in convertToAnyVector(::String, ::Dict{Symbol,Any}) at C:\Users\ezgik\.julia\v0.5\Plots\src\series.jl:64
 in copy!(::Array{Any,1}, ::Base.Generator{DataArrays.DataArray{Any,1},Plots.##147#149{Dict{Symbol,Any}}}) at .\abstract
array.jl:485
 in convertToAnyVector(::DataArrays.DataArray{Any,1}, ::Dict{Symbol,Any}) at C:\Users\ezgik\.julia\v0.5\Plots\src\series
.jl:55
 in macro expansion at C:\Users\ezgik\.julia\v0.5\Plots\src\series.jl:128 [inlined]
 in apply_recipe(::Dict{Symbol,Any}, ::Type{Plots.SliceIt}, ::DataArrays.DataArray{Any,1}, ::DataArrays.DataArray{Float6
4,2}, ::Void) at C:\Users\ezgik\.julia\v0.5\RecipesBase\src\RecipesBase.jl:238
 in _process_userrecipes(::Plots.Plot{Plots.PlotlyJSBackend}, ::Dict{Symbol,Any}, ::Tuple{DataArrays.DataArray{Any,1},Da
taArrays.DataArray{Float64,2}}) at C:\Users\ezgik\.julia\v0.5\Plots\src\pipeline.jl:73
 in _plot!(::Plots.Plot{Plots.PlotlyJSBackend}, ::Dict{Symbol,Any}, ::Tuple{DataArrays.DataArray{Any,1},DataArrays.DataA
rray{Float64,2}}) at C:\Users\ezgik\.julia\v0.5\Plots\src\plot.jl:171
 in #plot#136(::Array{Any,1}, ::Function, ::DataArrays.DataArray{Any,1}, ::Vararg{Any,N}) at C:\Users\ezgik\.julia\v0.5\
Plots\src\plot.jl:52
 in (::Plots.#kw##plot)(::Array{Any,1}, ::Plots.#plot, ::DataArrays.DataArray{Any,1}, ::DataArrays.DataArray{Float64,2},
 ::Vararg{DataArrays.DataArray{Float64,2},N}) at .\<missing>:0
 in #bar#376(::Array{Any,1}, ::Function, ::DataArrays.DataArray{Any,1}, ::Vararg{Any,N}) at C:\Users\ezgik\.julia\v0.5\P
lots\src\Plots.jl:155
 in (::Plots.#kw##bar)(::Array{Any,1}, ::Plots.#bar, ::DataArrays.DataArray{Any,1}, ::Vararg{Any,N}) at .\<missing>:0
 in _step_expr(::ASTInterpreter.Interpreter) at C:\Users\ezgik\.julia\v0.5\ASTInterpreter\src\ASTInterpreter.jl:629
 in step_expr at C:\Users\ezgik\.julia\v0.5\ASTInterpreter\src\ASTInterpreter.jl:666 [inlined]
 in #finish!#81(::Bool, ::Bool, ::Function, ::ASTInterpreter.Interpreter) at C:\Users\ezgik\.julia\v0.5\ASTInterpreter\s
rc\ASTInterpreter.jl:1720
 in eval_in_interp(::ASTInterpreter.Interpreter, ::Expr, ::JuliaParser.Tokens.SourceExpr, ::String) at C:\Users\ezgik\.j
ulia\v0.5\ASTInterpreter\src\ASTInterpreter.jl:1298
 in eval_code(::ASTInterpreter.InterpreterState, ::String) at C:\Users\ezgik\.julia\v0.5\ASTInterpreter\src\ASTInterpret
er.jl:1529
 in (::ASTInterpreter.##72#78{ASTInterpreter.InterpreterState,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.Abs
tractIOBuffer{Array{UInt8,1}}, ::Bool) at C:\Users\ezgik\.julia\v0.5\ASTInterpreter\src\ASTInterpreter.jl:1654
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at .\LineEdit.jl:1579
 in RunDebugREPL(::ASTInterpreter.Interpreter) at C:\Users\ezgik\.julia\v0.5\ASTInterpreter\src\ASTInterpreter.jl:1693
 in (::Gallium.##114#116)(::#chartsandtablesv2, ::Dict{String,Any}, ::Dict{String,Any}, ::Array{Float64,1}, ::StepRange{
DateTime,Base.Dates.Day}, ::Dict{String,DataArrays.DataArray{Float64,2}}, ::DataArrays.DataArray{Float64,1}, ::DataArray
s.DataArray{Float64,2}, ::DataArrays.DataArray{Float64,2}, ::DataArrays.DataArray{Float64,2}, ::DataArrays.DataArray{Any
,2}, ::DataArrays.DataArray{Float64,2}, ::DataArrays.DataArray{Float64,2}, ::Dict{String,Dict{String,DataArrays.DataArra
y{Float64,2}}}, ::Dict{String,Dict}, ::Dict{String,DataArrays.DataArray{Float64,1}}, ::Dict{String,DataArrays.DataArray{
Float64,2}}, ::Int64, ::Int64) at .\<missing>:0
 in macro expansion; at C:\Users\ezgik\Dropbox\Yeni\julia_deneme\deneme_1.jl:153 [inlined]
 in anonymous at .\<missing>:?
 in include_from_node1(::String) at .\loading.jl:488`

This chart works when I use PlotlyJS package, but I need to use Plots for the rest of the charts.

**Comment by mkborregaard** [comment]
Sorry, but we don't maintain the package for julia 0.5. I'd recommend updating. But the table/missing value support is in StatPlots, not Plots, so you might get this working with `using StatPlots` on 0.5.

 Missing values will be supported by Plots in 0.7, is the plan.
