### ISSUE TITLE
Recipe docs not indented properly

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Plots.jl#1519]
This is what the [recipe docs](http://docs.juliaplots.org/latest/recipes/) look like for me:

![image](https://user-images.githubusercontent.com/734386/39877712-a3e143e6-5444-11e8-84cd-22bda0947c7b.png)

Notice that the "Type Recipes", "Series Recipes", etc. headings are indented too far. Strangely in the raw markdown they look OK and they're rendered correctly in the github rendering. Maybe a problem with Documenter.jl?

**Comment by daschw** [comment]
Thanks for reporting! Whats your opinion on https://github.com/JuliaPlots/PlotDocs.jl/pull/89 as a workaround?

**Comment by ssfrr** [comment]
Yeah, I think I actually like the new subsection version better than the hierarchical bullet lists. :)

-s

**Comment by daschw** [comment]
Fixed by https://github.com/JuliaPlots/PlotDocs.jl/pull/89
