### ISSUE TITLE
pie and heatmap not working

### ISSUE THREAD

**Issue by paulobuchsbaum** [JuliaPlots/Plots.jl#1524]
I've used Gadfly, but after I know Plots, never more! 

Following the examples in the site, I've found 2 bugs

This below code gives an error
```
x = ["Nerds","Hackers","Scientists"]
y = [0.4,0.35,0.25]
pie(x,y,title="The Julia Community",l=0.5)

```
In other example below:

```
xs = [string("x",i) for i = 1:10]
ys = [string("y",i) for i = 1:4]
z = float((1:4) * (1:10)')
heatmap(xs,ys,z,aspect_ratio=1)```

It gives `heatmap not defined`

**Comment by daschw** [comment]
I cannot reproduce any of these errors. Which backend and which Plots version are you using?

**Comment by paulobuchsbaum** [comment]
Sorry for that. 

Today everything works.  I don't know why. 

Plots version `0.17.0` with `GR`. I did not get install `PyPlot` in Julia 0.62
