### ISSUE TITLE
How to make ylabel horizontal?

### ISSUE THREAD

**Issue by jongminyoon** [JuliaPlots/Plots.jl#1527]
How to make ylabel horizontal? Does this functionality exist? 

yrotation only rotates the yticks, not the ylabel.

**Comment by benfolsom** [comment]
Horizontal y-axis labels are very common in published work. It may be worth prioritizing this.

**Comment by isentropic** [comment]
@daschw  I think the relevant attribute is `:guidefontrotation` accodring to my findings, only pgfplot takes use of it. This attribute is forgotten in other backends I think

**Comment by daschw** [comment]
https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/pyplot.jl#L1111 I think here would be the place to start.

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/3529.
