### ISSUE TITLE
Julia Juno Plot Pane Script vs REPL different behavior

### ISSUE THREAD

**Issue by dlwalter** [JuliaPlots/Plots.jl#1532]
Sorry if this has been constantly rehashed but I can't find a solution in the old issues.  Also don't know if this is a Plots.jl issue or a Juno issue.

I'm using julia 0.6.2 and juno 0.2.0 with the gr plots backend.

If I run the following code in the REPL I get the correct plot in the plot pane:

```julia
using Plots
plot(rand(4,4))
```
but if I run that code from a file (ctrl+shift+enter) I get no plot in the plot pane.  Or anywhere.

**Comment by dlwalter** [comment]
I found that in the file I have to run the following code to get a plot in the plot pane
```
using Plots
h = plot(rand(4,4))
display(h)
```

Is this the intended behavior?  The documentation says

> A Plot is only displayed when returned (a semicolon will suppress the return)

but I wasn't suppressing the return in the first example code.

**Comment by BioTurboNick** [comment]
Just saw this issue when looking for something else.

All output is suppressed when running from a file I believe, so this would be expected behavior. Semicolons only suppress output at the REPL.
