### ISSUE TITLE
Dropping coordinate labels

### ISSUE THREAD

**Issue by dsweber2** [JuliaPlots/Plots.jl#1540]
When I use strings as x values and y values, above 16 entries many coordinate labels are dropped. I originally came at this using heatmap, but it also happens in a countour plot. I've tried this in Plotly, pyplot and GR, so I don't think it's a backend issue.

MWE:
```
nExamples = 19; nnames = ["$(k)" for k=1:nExamples]
heatmap(nnames,nnames,randn(nExamples,nExamples))
```

**Comment by daschw** [comment]
```julia
heatmap(nnames,nnames,randn(nExamples,nExamples), ticks = :all)
```
