### ISSUE TITLE
reload("Plots") breaks savefig and prevents backend change

### ISSUE THREAD

**Issue by wfrgra** [JuliaPlots/Plots.jl#1548]
Plotting after reload works, though the backend is reset to GR and trying to change doesn't affect anything, but saving a plot saves the last plot created before the reload. 
```
julia> using Plots
julia> reload("Plots")
julia> plot(rand(5,5))
julia> savefig("test.png")
ERROR: No current plot/subplot
Stacktrace:
 [1] current() at /home/will/.julia/v0.6/Plots/src/plot.jl:15
 [2] savefig(::String) at /home/will/.julia/v0.6/Plots/src/output.jl:125
```
Trying to save with `savefig(new_plt,"name.png")` also fails
```
julia> p = plot(rand(5,5))

julia> savefig(p,"test.png")
ERROR: MethodError: no method matching savefig(::Plots.Plot{Plots.GRBackend}, ::String)
Closest candidates are:
  savefig(::Plots.Plot, ::AbstractString) at /home/will/.julia/v0.6/Plots/src/output.jl:110

```

**Comment by mkborregaard** [comment]
Why do you reload Plots? This is a low priority fix IMHO.

**Comment by wfrgra** [comment]
I've been reloading it as a slightly quicker way of testing my changes to plots. Agree that it's quite low priority, just putting it here to make a record

**Comment by daschw** [comment]
For this purpose I would recommend https://github.com/timholy/Revise.jl 🙂
