### ISSUE TITLE
[PyPlot] Accepting column vectors for labels

### ISSUE THREAD

**Issue by fbruetting** [JuliaPlots/Plots.jl#1550]
That code doesn’t work in PyPlot due to the string vector being a column vector – in GR it works fine:
```julia
using Plots

param = [10; 20]
a = [1 2; 3 4]

plot(a, lab = "Parameter = " .* string.(param))
```

For PyPlot, I have to manually do something like the following, for making it a row vector:

```julia
plot(a, lab = "Parameter = " .* string.(reshape(param, 1, :)))
```

**Comment by t-bltg** [comment]
This is documented: https://docs.juliaplots.org/stable/input_data/#columns-are-series

Use a matrix for your arguments: `param = [10 20]`.
