### ISSUE TITLE
New Issue with surface under plotlyjs

### ISSUE THREAD

**Issue by albi3ro** [JuliaPlots/Plots.jl#1553]
I used to have use surface with plotlyjs to generate my plots.  

Now that I have updated to Julia 0.6.3, certain aspects no longer work.  
This is my script 
`surface(ky,kx,λpa, xticks= (ticks2,labels2),
yticks=(ticks2,labels2),colorbar=false,
xlabel="kx",
ylabel="ky",
zlabel="Energy",
title="Band Diagram")`

And this is what it generates:

![newplot 42](https://user-images.githubusercontent.com/6364575/41140082-7960a9b0-6b26-11e8-8a52-24d7e6dc20e7.png)

As you can see, neither the axis labels nor the ticks display. 

gr also doesn't work.

![badband](https://user-images.githubusercontent.com/6364575/41140434-8a7b7b92-6b28-11e8-92a5-0ee15eb12bb0.png)

Before, the same code (with an extra surface added) was generating 

![energydispersiondm3](https://user-images.githubusercontent.com/6364575/41140235-1c6a9224-6b27-11e8-85c6-0303a14ff5b0.png)

**Comment by daschw** [comment]
Could you try it out on master? I think the plotly issues are fixed in https://github.com/JuliaPlots/Plots.jl/pull/1549 (see also #1485). The 3D support for GR is not that ideal yet. I will tag a release with the plotly fixes this weekend.

**Comment by albi3ro** [comment]
did a checkout and build plotlyjs, and now it seems to work.
