### ISSUE TITLE
GR: heatmap(x,y,z) with z too small

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#1554]
This should probably throw an error:
```
heatmap(1:3,1:2,1:2)
```
However, on GR fills the plot non-deterministically with varying alpha values (uninitialized memory?)
![gr-short](https://user-images.githubusercontent.com/4170948/41205419-c4d9dba6-6cfb-11e8-9b72-2c50833068a7.png)

Also, the shape of `z` seems to be ignored:
```
heatmap(1:3,1:3,[1 2; 3 4])
```
![gr-short-2d](https://user-images.githubusercontent.com/4170948/41205421-c869b638-6cfb-11e8-8070-5ebcd7979a77.png)

(PlotlyJS tries to make sense of the incompatible sizes, but I'm not sure its behavior is really better than throwing an error)

**Comment by t-bltg** [comment]
Fail to reproduce.
