### ISSUE TITLE
yflip=true does not respect axis limits in PlotlyJS

### ISSUE THREAD

**Issue by mbeltagy** [JuliaPlots/Plots.jl#1556]
```julia
using Plots; plotlyjs();
plot(0:0.1:π, sin, ylim=(0.2,0.8))
```
![plotly1](https://user-images.githubusercontent.com/4301151/41297403-596fb3f8-6e5f-11e8-9aec-68c66daf18d8.png)

But after the flip 
```julia
yflip!()
```

![plotly2](https://user-images.githubusercontent.com/4301151/41297419-61b05964-6e5f-11e8-9738-8e19b5110ab0.png)

Notice here the the clipping is gone.

**Comment by apalugniok** [comment]
Seems like the issue is that `yflip` is implemented by using the Plotly `autorange = "reversed"` attribute which overrides the limits. Getting Plotly to switch the max and min limits gives the  correct behaviour. I'll open a PR.
