### ISSUE TITLE
Option fillrange behaves oddly with NaN values in plotted series

### ISSUE THREAD

**Issue by jvkerckh** [JuliaPlots/Plots.jl#1563]
I want to make a plot of two series with the same x-values, and the area between both series filled. for this I use the option fillrange where I put one of the two series.

However, if the series contain NaN values, strange behaviour occurs. For example:
```
using Plots
plot( [ 4, 4, NaN, 4, 4 ], fillrange = [ 2, 3, NaN, 1, 2 ] )
```
I would expect to see two trapezoids: the first one with the parallel sides (1,2)-(1,4) and (2,3)-(2,4), and the second one with parallel sides (4,1)-(4,4) and (5,2)-(5,4).

With the GR backend, I only see the plotted series even though the y-axis is scaled to show the other series as well.

With the Plotly (and PlotlyJS) backend, I see two trapezoids, but the second trapezoid is the same as the first, unlike what I'm expecting.

**Comment by daschw** [comment]
GR, works fine for me:
![gr_fillrange_nan](https://user-images.githubusercontent.com/16589944/41536971-686fd746-7307-11e8-92b2-6025a3d92799.png)

However I can confirm the issues for Plotly(JS). PyPlot also produces two equal trapezoids
