### ISSUE TITLE
Newest version?

### ISSUE THREAD

**Issue by jcrbloch** [JuliaPlots/Plots.jl#1578]
I am using Julia Version 0.6.2 and did a Pkg.update(). That also seemed to update Plots from 0.7 to 0.7.2. However, I see that the latest changes for the pgfplots() backend are not there? How can one get the newest version of Plots in julia in a simple way?

**Comment by daschw** [comment]
`v"0.7.2"` sounds weird did you mean `v"0.17.2"`. The most recent version of Plots (and probably the last for Julia 0.6) is `v"0.17.3"`. This should include all recent changes to `pgfplots()` and you should be able to update with a simple `Pkg.update()`.
