### ISSUE TITLE
PlotlyJS savefig without filename extension causes issue

### ISSUE THREAD

**Issue by Helveg** [JuliaPlots/Plots.jl#1581]
After a call to savefig(plot(rand(5)),"testftile") I get the following message:
```
ERROR: MethodError: no method matching _show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{P
lots.PlotlyBackend})
```
I don't feel like this error correctly emphasizes that the lack of an extension in the filename argument causes it. It seems there's not alot of documentation on MIME types in julia or anything either. I figure that PlotlyJS is expecting an HTML mime object and without the extension the object is cast to the image/png MIME type, but why should the extension so strictly determine the type and cause this error?

**Comment by matthieugomez** [comment]
I obtain the same error even if the filename has an extension, like "testfile.png" or "testfile.jpg"

**Comment by Helveg** [comment]
Have you tried `testfile.html`? I don't remember completely but I think that could maybe help?

**Comment by matthieugomez** [comment]
It works now. I think updating PlotlyJS solved the problem.
