### ISSUE TITLE
Plotly: show datapoints on hover not working anymore

### ISSUE THREAD

**Issue by jvkerckh** [JuliaPlots/Plots.jl#1590]
**Plotly only**

The Plotly functionality that allows you to see the coordinates of the points in a plot when hovering the mouse pointer over it is no longer working. All the other interactivity features still work as intended.

Tested with the following code:
```
using Plots
plotly()
plot( 1:5, size = ( 400, 300 ) )
```
This results in the image below. Normally the coordinates of the point should be displayed near the mouse cursor.
![plotly error](https://user-images.githubusercontent.com/23631966/42260135-86e6247e-7f63-11e8-98af-85a5b78f80da.png)

**Comment by oxinabox** [comment]
A workaround:
pass in the tool tips to the `hover` argument, explictly.

```
using Plots
plotly()
data = 1:5
plt = plot(data; hover=data )
display("text/html", plt)
```

<img width="881" alt="screenshot" src="https://user-images.githubusercontent.com/5127634/51478170-94264200-1d82-11e9-99f2-b96bd84a23ce.png">

**Comment by jmerizalde13** [comment]
Hi, 
I've been working with  Plotly directly on Julia and am trying to get a label on data points in scatter3d that "sticks", similarly to what  hover does but not just for mouse overing. 

This option is available for the scatter plot but not for scatter 3d, which I find lacking.

Hope I can get help on this!

-Jaime

**Comment by Kunz-David** [comment]
Hello,

can hover be made to work in a heatmap?
Some sample code, where it doesn't work:
```julia
tile_size = 4
board_size = 8 # must be even
mini_board = [zeros(tile_size, tile_size) ones(tile_size, tile_size);
              ones(tile_size, tile_size) zeros(tile_size, tile_size)]

chessboard = repeat(mini_board, outer=(convert(Integer,(board_size/2)), convert(Integer,(board_size/2))))
chessboard = repeat(mini_board, outer=(2, 2))

img  = chessboard

using Plots
plotly()

heatmap(img; hover=img)
```

**Comment by JakobAsslaender** [comment]
Hi,
I am having the same issue: The data-hover doesn't work with heat maps. MWP:

```
using Plots
plotlyjs()

x = randn(100,100)
heatmap(x, hover=x)
```

I am assuming this is a bug?

Thanks for your help, everyone!
