### ISSUE TITLE
x-axis labels truncated by default window size

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#1600]
Plots with plotlyjs() is working really well except for minor artifacts that detract from perceived quality.

In the attached screen clip you can see how the bottom of the window cuts through the x-axis tick labels.  You can manually resize the window, but users shouldn't have to do that.

I could not get the bottom_margin argument to take despite trying about 10 ways.  I can't understand the method signatures in the error message.

Any help much appreciated.  I have a "real" project coming up and it will make sense to use Jupyter and possibly host on the web for the client so I'd love to get all of this working.

The chart is created here:

```
            plotlyjs(size=(600,400))
            plt_learning = plot(plotdef["fracright_history"], title="Learning Progress",
                labels=plotdef["plot_labels"], ylims=(0.0, 1.05)) 
            display(plt_learning)
```

One of many ways I tried adding some padding to the bottom:
```
            plotlyjs(size=(600,400))
            plt_learning = plot(plotdef["fracright_history"], title="Learning Progress",
                labels=plotdef["plot_labels"], ylims=(0.0, 1.05), bottom_margin="30px") 
            display(plt_learning)
```

resulting error message:
```
ERROR: LoadError: MethodError: no method matching +(::Measures.Length{:mm,Float64}, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:424
  +(::Measures.Length{U,T} where T, ::Measures.Length{U,T} where T) where U at /Users/lewis/.julia/v0.6/Measures/src/length.jl:28
  +(::Measures.Measure, ::Measures.Measure) at /Users/lewis/.julia/v0.6/Measures/src/operations.jl:41
```
<img width="626" alt="screen shot 2018-07-19 at 1 21 36 pm" src="https://user-images.githubusercontent.com/1149741/42968430-0f39588c-8b58-11e8-9ef2-d22d82c1e927.png">

**Comment by daschw** [comment]
You can do
```
plot(rand(10), margin=5Plots.mm)
```
or
```
using Measures
plot(rand(10), margin=5mm)
```
I agree that the docs need improvement. Pull requests to https://github.com/JuliaPlots/PlotDocs.jl are always welcome!

**Comment by lewisl** [comment]
I did the second as that is a standard approach.  The first is just weird.  Julia should minimize “innovation” in bizarre syntax.  Python got popular for reducing boilerplate and strangeness (and has some of each…).  Julia started down the path of simplicity and obviousness and should stay the course.

I can add a couple of notes to the doc.

**Comment by daschw** [comment]
It's not that we strive for innovation via "bizarre syntax"
See #821 and #855 for the reasons for the current behaviour. If you have a nicer solution we are open for any suggestions.

**Comment by lewisl** [comment]
Using Measurements or importing, say, just mm is not bizarre.  Either are consistent with Julia docs and common usage.  5Plots.mm uses Plots import of measurements, but have you seen that commonly used?  That’s all I meant.

**Comment by daschw** [comment]
Agreed :slightly_smiling_face:  I just wanted two provide both available solutions.

**Comment by daschw** [comment]
I think we could still make `margin` accept `Real`s and use a default unit (`mm`, `pt` or `px`?) in that case. I also kind of like the idea of allowing strings like `"5mm"` or `"2px"`.

**Comment by mkborregaard** [comment]
great idea

**Comment by lewisl** [comment]
This is ancient. I'll give PlotlyJS another try (been using pyplot).  Maybe I'll remember what to do...  Maybe not.  Call it closed as old and not actionable.  Good stuff has happened.
