### ISSUE TITLE
Plot the sol with xscale=:log

### ISSUE THREAD

**Issue by MahdiarSadeghi** [JuliaPlots/Plots.jl#1607]
I want to plot the sol in time log scale and here is the problem:

```
plot(sol[2,:], xaxis=:log) # works, but the x axis would be log of time step number not the actual log(time)

plot(sol, xscale=:log) # crashes Julia with this error: ArgumentError: At least one finite value must be provided to formatter.
```

**Comment by daschw** [comment]
If you could provide a reproducible example it would be easier to find and fix the issue. How do the x values of `sol` look like?

**Comment by MahdiarSadeghi** [comment]
The problem is fixed now. The input of log plot should not start from 0, because it requires the log plot to start from -inf.
