### ISSUE TITLE
Add "hold all" equivalent to the one from Matlab

### ISSUE THREAD

**Issue by djsegal** [JuliaPlots/Plots.jl#1609]
Related to:

https://discourse.julialang.org/t/way-to-get-default-color-order-in-plots-jl/12643/3

// also, a link to the matlab docs for [`hold all`](https://www.mathworks.com/help/matlab/ref/hold.html)

-------

There's probably a way to use the following line to accomplish this feature:

```
get_color_palette(:auto, plot_color(:white), 17)
```

Feel free to close if you don't think it's needed

**Comment by daschw** [comment]
An easier way to get the default color palette:
```julia
using Plots
palette(:default)
```
I can't really see how the `hold all` command frrom matlab fits into the design of Plots, so I hope it's ok, if I close this.

**Comment by djsegal** [comment]
I'm cool with the close, but `hold all` doesn't do what `palette(:default)` does.

+ One keeps the color locked in place until after `hold off`
+ The other resets the color palette to default (going back to `:blue`)

Does that make sense?

**Comment by daschw** [comment]
No, I know that it's not the same, I just wanted to provide an easier alternative to `get_color_palette(:auto, plot_color(:white), 17)`, which you posted above.

**Comment by djsegal** [comment]
Oh, for sure! Thanks for looking into it
