### ISSUE TITLE
using Plots failed in Julia 0.7 official release

### ISSUE THREAD

**Issue by carmagnole** [JuliaPlots/Plots.jl#1621]
julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
WARNING: importing deprecated binding Base.Display into Plots.
WARNING: Base.Display is deprecated, use AbstractDisplay instead.
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/types.jl:9
┌ Warning: Deprecated syntax `try without catch or finally` at /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:310.
└ @ ~/.julia/packages/Plots/V3tQ/src/utils.jl:310
WARNING: importing deprecated binding Base.Void into Plots.
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:262
WARNING: importing deprecated binding Base.e into Plots.
WARNING: Base.e is deprecated, use ℯ (\euler) or `Base.MathConstants.e`
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:355
WARNING: importing deprecated binding Base.Range into Plots.
WARNING: Base.Range is deprecated, use AbstractRange instead.
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:453
WARNING: Base.Range is deprecated, use AbstractRange instead.
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:454
WARNING: importing deprecated binding Base.@printf into Plots.
WARNING: Base.@printf is deprecated: it has been moved to the standard library package `Printf`.
Add `using Printf` to your imports.
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:823
WARNING: Base.Range is deprecated, use AbstractRange instead.
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:849
WARNING: Base.Range is deprecated, use AbstractRange instead.
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:850
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near /Users/ZY/.julia/packages/Plots/V3tQ/src/utils.jl:859
┌ Warning: Deprecated syntax `try without catch or finally` at /Users/ZY/.julia/packages/Plots/V3tQ/src/components.jl:72.
└ @ ~/.julia/packages/Plots/V3tQ/src/components.jl:72
┌ Warning: Deprecated syntax `try without catch or finally` at /Users/ZY/.julia/packages/Plots/V3tQ/src/components.jl:391.
└ @ ~/.julia/packages/Plots/V3tQ/src/components.jl:391
┌ Warning: Deprecated syntax `try without catch or finally` at /Users/ZY/.julia/packages/Plots/V3tQ/src/components.jl:423.
└ @ ~/.julia/packages/Plots/V3tQ/src/components.jl:423
┌ Warning: Deprecated syntax `"begin" inside indexing expression` at /Users/ZY/.julia/packages/Plots/V3tQ/src/components.jl:491.
└ @ ~/.julia/packages/Plots/V3tQ/src/components.jl:491
┌ Warning: `linspace(start, stop, length::Integer)` is deprecated, use `range(start, stop=stop, length=length)` instead.
│   caller = partialcircle(::Float64, ::Float64, ::Int64, ::Float64) at components.jl:61
└ @ Plots ~/.julia/packages/Plots/V3tQ/src/components.jl:61
┌ Warning: `shift!` is deprecated, use `popfirst!` instead.
│   caller = #weave#85(::Array{Array{T,1} where T,1}, ::Function, ::Array{Tuple{Float64,Float64},1}, ::Array{Tuple{Float64,Float64},1}) at components.jl:71
└ @ Plots ~/.julia/packages/Plots/V3tQ/src/components.jl:71
WARNING: importing deprecated binding Base.Nullable into Plots.
ERROR: LoadError: LoadError: TypeError: in SeriesAnnotations, in type definition, expected Type, got typeof(Base.Nullable)
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /Users/ZY/.julia/packages/Plots/V3tQ/src/Plots.jl:3
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:399
 [13] top-level scope at ./none:3
in expression starting at /Users/ZY/.julia/packages/Plots/V3tQ/src/components.jl:438
in expression starting at /Users/ZY/.julia/packages/Plots/V3tQ/src/Plots.jl:157
ERROR: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to /Users/ZY/.julia/compiled/v0.7/Plots/ld3vC.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1185
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834

**Comment by mkborregaard** [comment]
Dup of #1620
