### ISSUE TITLE
wrong colorbar with heatmap

### ISSUE THREAD

**Issue by pawbz** [JuliaPlots/Plots.jl#1640]
Hi, 
A simple plot of homogeneous heatmap on Julia v0.7 with Plots v0.19.0 results in wrong colorbar axis
```julia
using Plots
gr()
heatmap(ones(10,10))
```
![image](https://user-images.githubusercontent.com/11274860/44006214-79b54e38-9e4e-11e8-983b-73a5c8e33875.png)

**Comment by BeastyBlacksmith** [comment]
In Plots1.1.1 that doesn't produce any colorbar

**Comment by t-bltg** [comment]
Seems fixed.
