### ISSUE TITLE
Multiple plots with line_zs add many colorbars

### ISSUE THREAD

**Issue by tkf** [JuliaPlots/Plots.jl#1642]
Here is the problematic example

```julia
using Plots
gr()

ts = range(0, stop=2π, length=50)
zs = 1:10
xs_list = [r .* cos.(ts) for r in zs]
ys_list = [r .* sin.(ts) for r in zs]

# This is what I want to plot:
xs = vcat((vcat(NaN, xs) for xs in xs_list)...)
ys = vcat((vcat(NaN, ys) for ys in ys_list)...)
plt1 = plot(xs, ys, line_zs=repeat(zs, inner=length(ts) + 1), label="")

# It looks like constructing the same plot with plot! produces
# "overdubbed" colorbar:
plt2 = plot()
for (xs, ys, z) in zip(xs_list, ys_list, zs)
    plot!(plt2, xs, ys, line_zs=z, label="")
end

# Trying to make it work by explicitly turning off colorbar.
plt3 = plot()
for (xs, ys, z) in zip(xs_list, ys_list, zs)
    plot!(plt3, xs, ys, line_zs=z, label="", colorbar=:none)
end
plot!(plt3, colorbar=:right)

# This does not work as well:
# plt3 = plot()
# for (i, (xs, ys, z)) in enumerate(zip(xs_list, ys_list, zs))
#     plot!(plt3, xs, ys, line_zs=z, label="",
#           colorbar=i == length(xs_list) ? :right : :none)
# end

# Calling plot once does not fix the issue.
plt4 = plot(xs_list, ys_list, line_zs=reshape(zs, (1, :)), label="")

plt = plot(plt1, plt2, plt3, plt4)
savefig(plt, "fig.png")
```

which outputs

![fig](https://user-images.githubusercontent.com/29282/44016466-edb2f7d2-9e89-11e8-926d-2d352a5882cb.png)

Checked with:

````
(v1.0) pkg> status -m
    Status `~/.julia/environments/v1.0/Manifest.toml`
  ...
  [28b8d3ca] GR v0.32.2
  ...
  [ccf2f8ad] PlotThemes v0.3.0
  [995b91a9] PlotUtils v0.5.1
  [91a5bcdd] Plots v0.19.0
  ...
  [3cdcf5f2] RecipesBase v0.5.0
  ...
````

I can plot what I want with the "NaN trick" but it's very hard to use when I want to define plot recipes for nested structure:

```julia
using RecipesBase

struct Circle
    xs
    ys
    z
end

struct CircleList
    circles
end

@recipe function f(c::Circle)
    line_zs := c.z
    label := ""
    (c.xs, c.ys)
end

@recipe function f(data::CircleList)
    for c in data.circles
        @series begin
            c
        end
    end
end

ts = range(0, stop=2π, length=50)
zs = 1:10
circles = CircleList([Circle(
    r .* cos.(ts),
    r .* sin.(ts),
    r,
) for r in zs])

using Plots
plot(circles)
```

**Comment by mkborregaard** [comment]
Yes, that is the behaviour of Plots. Adding the option for a shared colorbar for all subplots is a great idea, but the user should be able to opt in or out of this.

**Comment by tkf** [comment]
Oh, I didn't mean to ask for colorbar shared between subplots.  First of all, my understanding of "subplot" in Plots.jl is roughtly equivalent to Axes in PyPlot/matplotilb; so, in my example figure above, there are four subplots.  Is that correct?  Then my request is Plots to share colorbar between _lines_.

I guess I wasn't clear.  Look at the tick labels of top left subplot's colorbar:

![image](https://user-images.githubusercontent.com/29282/44018041-472b4742-9e8f-11e8-9d67-0ec56cb48ce2.png)

and compare it to the top right one (and the bottom subplots):

![image](https://user-images.githubusercontent.com/29282/44018051-513ce9b6-9e8f-11e8-8ce7-0f93928ae358.png)

It looks like the top right and bottom subplots all have "overdubbed" colorbar.  Is it expected?

**Comment by mkborregaard** [comment]
Oh you're right, good call. And thanks for the PR!

**Comment by tkf** [comment]
Rereading what I wrote, I realized writing important information in the comment of the code was a terrible idea :)

Anyway, thanks for the quick review of the PR!
