### ISSUE TITLE
Nullable in HDF5 backend

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1645]
I think this should be edited, but not so sure about the expected syntax here. @ma-laforge ?

https://github.com/JuliaPlots/Plots.jl/blob/340cd0a1fe8bdddfb078e9fbd93d8cf4995cb134/src/backends/hdf5.jl#L132

**Comment by ma-laforge** [comment]
It has been a while.  I will check.
Question: is this for 0.7 compatibility?

**Comment by mkborregaard** [comment]
Yes exactly.

**Comment by ma-laforge** [comment]
Ok.  What do I need to do?
I did:
```
] add Plots
```
And:
```
] dev Plots
```

... But I appear to have issues with GR & `deps/plotly-latest.min.js`...

Not sure what to do to start seeing my error...

**Comment by ma-laforge** [comment]
PS: My `Nullable` was added to correspond to the type that was being used in Plots.jl.

Question: What did you use when you migrated to 0.7?  Was it the Nullable in the Nullables.jl package?  Or was it maybe `Union{T, Nothing}`?  Whatever you migrated to is what should be replaced, for example:

```
"NULLABLE" => Union{T, Nothing},
```

Does this help?

**Comment by mkborregaard** [comment]
In the new package ecosystem you need to manually build the packages you develop: `]build Plots`

**Comment by mkborregaard** [comment]
We changed Nullables to `Union{T, Nothing}`

**Comment by ma-laforge** [comment]
I created a fix so that Nullable no longer causes an issue...
https://github.com/JuliaPlots/Plots.jl/pull/1654

...but many data structures changed.  I will have to re-visit this module once things stabilize a bit more.

**Comment by mkborregaard** [comment]
Awesome. I think things are actually stable now.

**Comment by ma-laforge** [comment]
You can close this issue.  The HDF5 "backend" works now.
