### ISSUE TITLE
Main documentation has outdated examples

### ISSUE THREAD

**Issue by mimecuvalo** [JuliaPlots/Plots.jl#1648]
Hiya!
I'm exploring the Plots package but the main landing page's examples seem to be busted. (not sure if it's caused by the 1.0 release).

The page: http://docs.juliaplots.org/latest/
- Lorenz Attractor example, some variable scope problem?
```
ERROR: UndefVarError: y not defined
Stacktrace:
 [1] macro expansion at ./REPL[7]:2 [inlined]
 [2] top-level scope at /Users/mime/.julia/packages/Plots/8Y7Mw/src/animation.jl:155 [inlined]
 [3] top-level scope at ./none:0
```

- "Make some waves" example:
```x = y = linspace(-5, 5, 40)```
ERROR: MethodError: no method matching linspace(::Int64, ::Int64, ::Int64)

Looks like linspace has been replaced by LinRange?

- In the same example:
```ERROR: MethodError: no method matching findfirst(::Array{Plots.Subplot,1}, ::Plots.Subplot{Plots.PyPlotBackend})```

Not sure what that one's about.

**Comment by mkborregaard** [comment]
Thanks for reporting! Yes, those are not run on new versions - the examples at the end are! This would not happen if these, as well as those from the tutorial were built automatically (https://github.com/JuliaPlots/PlotDocs.jl/pull/80).

**Comment by mkborregaard** [comment]
We're a bit under the weather because our Travis test machinery involves packages that are still broken on 1.0...

**Comment by mimecuvalo** [comment]
👍No worries, I can imagine y'all are swamped with the changes.

**Comment by mkborregaard** [comment]
https://github.com/JuliaPlots/PlotDocs.jl/pull/94
