### ISSUE TITLE
pyplot(): KeyError: key "left" not found

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaPlots/Plots.jl#1653]
I get this error after upgrading to julia v1.0, with Plots v0.19.1 and PyPlot v2.6.0.

`using Plots`
`pyplot()`
`julia> plot(randn(10))`
`Error showing value of type Plots.Plot{Plots.PyPlotBackend}:`
`ERROR: KeyError: key "left" not found`

`using PyPlot` directly it does work though.

**Comment by mkborregaard** [comment]
`PyPlot` is working now on 1.0? We haven't been able to test yet.

**Comment by mkborregaard** [comment]
This is because Plots uses PyCall to interact with matplotlib outside of PyPlot. PyCall is not yet 1.0 compliant, but you can resolve this with `]add PyCall#master`.

**Comment by mkborregaard** [comment]
I'll keep this open for a while until PyCall makes a release.

**Comment by lnacquaroli** [comment]
For me this is solved after updating to PyCall v1.18.2.
