### ISSUE TITLE
latexstring not defined w/ savefig/pyplot

### ISSUE THREAD

**Issue by mortenpi** [JuliaPlots/Plots.jl#1659]
I am seeing the following failure on 0.7 (with Plots.jl on current `master`):

```julia
using Plots
pyplot()

plot(1:3)
yaxis!(:log)
savefig("test.png")
```

```
ERROR: LoadError: UndefVarError: latexstring not defined
Stacktrace:
 [1] (::getfield(Plots, Symbol("##470#473")))(::String) at /home/mortenpi/.julia/packages/Plots/LWBTU/src/backends/pyplot.jl:242
 [2] iterate at ./generator.jl:47 [inlined]
 [3] _collect(::Array{String,1}, ::Base.Generator{Array{String,1},getfield(Plots, Symbol("##470#473"))}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at ./array.jl:632
...
```

[Full MWE with manifest etc.](https://gist.github.com/mortenpi/ba618d967d381531f949955754645be5#file-pyplot-latexstrings-error-md)

**Comment by mkborregaard** [comment]
Would you mind trying to explicitly `add` and `using` LaTeXStrings (and then PyCall)?
I think this could be because Plots calls those two packages as well, they are deps of PyPlot but you can't `using` packages that have only been installed as deps on 1.0.

**Comment by mortenpi** [comment]
I have it explicitly `add`ed (otherwise already `pyplot()` doesn't run).  But

```julia
using Plots
using LaTeXStrings
pyplot()
plot(1:3)
yaxis!(:log)
savefig("test.png")
```

still fails with the same error.

I was sniffing around a bit in the code I am wondering whether `@eval Main` is really correct here? Because you would want `latexstring` to be available in the `Plots` module, not in `Main`, no?

https://github.com/JuliaPlots/Plots.jl/blob/2d217edc157afda5112992b82d9d2b707b8b6610/src/backends.jl#L387-L397

**Comment by mkborregaard** [comment]
Yes it makes sense to eval into Plots, not Main, I think. That code is brand new, it was added by @daschw in #1601 . What happens if you eval into Plots instead?

**Comment by mortenpi** [comment]
If I drop `Main` from there it works, but you get a warning about a missing dependency:

```
┌ Warning: Package Plots does not have PyPlot in its dependencies:
│ - If you have Plots checked out for development and have
│   added PyPlot as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Plots
└ Loading PyPlot into Plots from project dependency, future warnings for Plots are suppressed.
```

Maybe the [`labelfunc` that has the `latexstring` calls](https://github.com/JuliaPlots/Plots.jl/blob/9ae22a1ad70bea79a11b41475f47714dad7b7769/src/backends/pyplot.jl#L240-L250) needs a `@require` around it?

**Comment by mkborregaard** [comment]
The warning about the missing dependency is spurious and can be ignored - that's because when you change the imports of a `dev`ed package you need to run `]resolve` under Pkg3.

Let's keep this open even though you made the PR, I'd like to hear @daschw 's opinion about the module to eval into once he gets back from hiking in the mountains :-)

**Comment by mkborregaard** [comment]
What error are you getting? Is this with @mortenpi 's PR checked out?

**Comment by baggepinnen** [comment]
Same error as reported above. I must admit I have not been able to checkout the PR, I can't figure out how to do :/

**Comment by mkborregaard** [comment]
I'd think you should be able to do `add https://github.com/mortenpi/Plots.jl#fix-pyplot-savefig` , then `]free` to get back to the release version.

**Comment by baggepinnen** [comment]
That fixes it! Thanks a lot, I haven't figured out the new `Pkg` fully yet.

**Comment by mortenpi** [comment]
@mkborregaard For what it's worth, I don't think the warning is spurious -- Plots doesn't have PyCall / LaTeXStrings in its dependencies, so you should always get the warning when loading them into the `Plots` module. Requires.jl seems to somehow get around this though.

**Comment by mkborregaard** [comment]
Yes Requires should get around that.
