### ISSUE TITLE
Attributes from PLOTS_DEFAULTS dict are avoided

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaPlots/Plots.jl#1661]
I'm trying to use `PLOTS_DEFAULTS` from `startup.jl` but it doesn't seems to work. It's called and the variables are set, but the plot command doesn't take them into account (I tried the `startup.jl` file with other commands and works fine). REPL gives with same results:

`julia> PLOTS_DEFAULTS = Dict(:linewidth=>5)`
`Dict{Symbol,Int64} with 1 entry:`
`  :linewidth => 5`

Looks it worked but when plotting the line is still with linewidth = 1. Doing 

`using Plots`
`gr(linewidth=5)` 

works though. I'm on Julia 1.0 and Plots v0.19.2

**Comment by mkborregaard** [comment]
Darn. Must be the startup.jl file is implemented differently on 0.7

**Comment by lnacquaroli** [comment]
Maybe I expressed myself incorrectly before, but calling `PLOTS_DEFAULTS = Dict(...)` from REPL also doesn’t work for me (neither from the `startup.jl`). So I guess is not just the startup file in this case, right?

**Comment by mkborregaard** [comment]
huh

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/JuliaPlots/Plots.jl/pull/1667.

**Comment by lnacquaroli** [comment]
This is solved now for me. Maybe wanna close it. Thanks.

**Comment by daschw** [comment]
Thanks!
