### ISSUE TITLE
Problem overlaying a wireframe plot to an existing surface plot in pyplot backend

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaPlots/Plots.jl#1662]
The following very simple MWE worked without any problem earlier this year, but now, I tested this on the following two platforms but neither work anymore:
(1) Julia v0.6.4; Plots.jl v0.17.4; PyPlot.jl v2.6.0; PyCall.jl v1.17.1 (on Windows 10)
(2) Julia v0.7.0; Plots.jl v0.19.2+; PyPlot.jl v2.6.0+; PyCall.jl v1.17.1+ (on Mac OS X 10.11.6)
```
x=range(0.0,1.0,20)
y=range(1.0,2.0,20)
z=randn(20,20)
surface(x,y,z)
wireframe!(x,y,0.01*z,c=:blue)

Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: PyError ($(Expr(:escape, :(ccall(#= /Users/xxx/.julia/dev/PyCall/src/pyfncall.jl:101 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'AttributeError'>
AttributeError('Unknown property vmin',)
  File "/Users/xxx/.julia/packages/Conda/m7vem/deps/usr/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 1921, in plot_wireframe
    linec = art3d.Line3DCollection(lines, *args, **kwargs)
  File "/Users/xxx/.julia/packages/Conda/m7vem/deps/usr/lib/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py", line 206, in __init__
    LineCollection.__init__(self, segments, *args, **kwargs)
  File "/Users/xxx/.julia/packages/Conda/m7vem/deps/usr/lib/python3.6/site-packages/matplotlib/collections.py", line 1252, in __init__
    **kwargs)
  File "/Users/xxx/.julia/packages/Conda/m7vem/deps/usr/lib/python3.6/site-packages/matplotlib/collections.py", line 170, in __init__
    self.update(kwargs)
  File "/Users/xxx/.julia/packages/Conda/m7vem/deps/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 888, in update
    for k, v in props.items()]
  File "/Users/xxx/.julia/packages/Conda/m7vem/deps/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 888, in <listcomp>
    for k, v in props.items()]
  File "/Users/xxx/.julia/packages/Conda/m7vem/deps/usr/lib/python3.6/site-packages/matplotlib/artist.py", line 881, in _update_property
    raise AttributeError('Unknown property %s' % k)
```
Interestingly, if I execute the last line ```wireframe!(...)``` once more, I get the following error:
```
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: MethodError: no method matching getindex(::Base.Generator{Tuple{Int64,Int64},getfield(Plots, Symbol("##259#261")){Float64}}, ::Int64)
```
Also, if I replace the ```surface(...)``` in the above MWE by ```wireframe(x,y,z,c=:red)```, I don't get any error and the resulting plots are all correct.  Thanks for your help!

**Comment by BoundaryValueProblems** [comment]
@mkborregaard , thanks.  I just tested this MWE on Julia v0.6.4 on my MacBook Pro, with older Conda v1.0.0 with python 2.7 and matplotlib that was installed on March 14, 2018. But I got the same error (except somehow instead of ```vmin```, it complains ```vmax```). I am not sure if this matplotlib is really an older one than the one I recently installed using Julia v0.7.0. Do you know how to check the version number of matplotlib? I only use matplotlib under Julia/Plots/PyPlots. So, when I run python on Terminal and try to import matplotlib, it says: ```ImportError: No module named matplotlib```. So, I cannot run: ```>>> matplotlib.__version__``` under python session to check the version number.

**Comment by lnacquaroli** [comment]
If you are able to run `using PyPlot`, then the Matplotlib version number is returned by `PyPlot.version`.

**Comment by BoundaryValueProblems** [comment]
@lnacquaroli , thanks for your help!
@mkborregaard , on my Mac (OS X 10.11.6), under v0.7, the matplotlib version is 2.2.2 while under v0.6.4, it's 2.2.0. So, for those two versions of matplotlib, I have the above same problem. I might be able to find the older one via time machine, but it would take some time...

**Comment by BoundaryValueProblems** [comment]
@mkborregaard , actually, on my Windows 10 machine, the matplotlib is v2.1.0, and still got the same error (with Julia v0.6.4).

**Comment by mkborregaard** [comment]
Hmm it's probably not a version thing then. It's always tricky to find the bug in Plots when the error is thrown from inside Python

**Comment by isentropic** [comment]
@daschw 
I think the problem arises from this:
Doing this,
```
x=range(0.0,1.0,20)
y=range(1.0,2.0,20)
z=randn(20,20)
surface(x,y,z)
```
errors,
but:
```
x=1:1:20
y=1:1:20
z=randn(20,20)
surface(x,y,z)
```
is fine in all backends. Simply put, @BoundaryValueProblems has not input correct input shapes, `x,y` shape should match corresponding `z` shape. Perhaps, there needs to be some shape check beforehand.

**Comment by daschw** [comment]
I think that was old range syntax.
Nevertheless, the issue seems to be resolved:
```julia
using Plots

pyplot()

x = range(0.0, 1.0, length = 20)
y = range(1.0, 2.0, length = 20)
z = randn(20, 20)
surface(x, y, z)
wireframe!(x, y, z, c = :blue)
```
![pyplot_wireframe](https://user-images.githubusercontent.com/16589944/79066363-98a48680-7cb7-11ea-9b42-b1a4fef69150.png)

Thanks for ointing that out!
