### ISSUE TITLE
Why are P2 and P3 exported? 

### ISSUE THREAD

**Issue by improbable22** [JuliaPlots/Plots.jl#1675]
On Julia 0.7, I get an error "ERROR: cannot assign variable Plots.P2 from module Main" when I try to call a plot P2 or P3 in the REPL, instead of just a warning. 

Why is this exported? 

Searching isn't very illuminating. Although one of the examples is in fact doing exactly what I was doing... except with lower-case p3 hence no collision:

https://github.com/JuliaPlots/Plots.jl/search?q=P3&unscoped_q=P3

**Comment by mkborregaard** [comment]
I've no idea why this is exported, and I don't see any good reason it should be.
But - are you not supposed to name your variables in lowercase? :trollface:

**Comment by improbable22** [comment]
Indeed, but sometimes they are big objects which deserve more than a single lower-case letter... 

OK I made a pull request, whose tests fail right now for surely unrelated reasons.

**Comment by mkborregaard** [comment]
Yes, test failures are unrelated.

**Comment by daschw** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/1678
