### ISSUE TITLE
A heatmap with more than 15 categories begins to skip some categories

### ISSUE THREAD

**Issue by swiesend** [JuliaPlots/Plots.jl#1679]
If I want to plot a heatmap with too many categories, then I can't fit them all on the axes.

I think it would be useful to have an option to disable the skipping behavior by default and to enable it if needed.

Is `Plots.jl` doing the skipping part or is it handled automatically by the backend? Just could test it with `gr()`, as `pyplot()` and `plotlyjs()` are currently failing for me.

`pyplot()`
```julia
p = heatmap(xs, ys, z)
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: KeyError: key "set_axis_bgcolor" not found
```
`plotlyjs()`
```julia
Failed to precompile PlotlyJS to /home/sebastian/.julia/lib/v0.6/PlotlyJS.ji.
in plotlyjs at Plots/src/backends.jl:23
in #plotlyjs#456 at Plots/src/backends.jl:23
in backend at Plots/src/backends.jl:185
in _initialize_backend at Plots/src/backends/plotlyjs.jl:31
in require at base/loading.jl:405
in _require at base/loading.jl:497
in compilecache at base/loading.jl:710
```

```julia
cats = 15
xs = [string("x",i) for i = 1:cats]
ys = [string("y",i) for i = 1:cats]
z = float((1:cats) * (1:cats)')
p = heatmap(xs, ys, z)
```
![image](https://user-images.githubusercontent.com/3512490/44308482-10bd8a80-a3b7-11e8-8430-92ea03fb5dac.png)

```julia
cats = 16
xs = [string("x",i) for i = 1:cats]
ys = [string("y",i) for i = 1:cats]
z = float((1:cats) * (1:cats)')
p = heatmap(xs, ys, z)
```
![image](https://user-images.githubusercontent.com/3512490/44308487-259a1e00-a3b7-11e8-8f3b-0cd1dff03c41.png)

Trying to plot 29 categories seems to be impossible:
![image](https://user-images.githubusercontent.com/3512490/44308409-7d378a00-a3b5-11e8-9c58-d6c7d01692bb.png)

Adjusting the tickfont size or setting `xrotation=90` degrees does not help either.
```julia
p = heatmap(header, header, CVIs_M,
    size=(800,800),
    aspect_ratio=1.0,
    xrotation=62,
    tickfont = font(5),
    # guidefont = font(8),
    # legendfont = font(8),
    )
```
![image](https://user-images.githubusercontent.com/3512490/44308527-c557ac00-a3b7-11e8-8948-9c579eecfc95.png)

**Comment by swiesend** [comment]
Uh, I wasn't aware of the [supported attributes](http://docs.juliaplots.org/latest/supported/) section in the documentation! But nevertheless I think this is unexpected behavior.

`xticks` and `yticks` did the job.

```julia

p = heatmap(
    header,
    header,
    CVIs_M,
    size=(800,800),
    aspect_ratio=1.0,
    xrotation=62,
    # tickfont = font(5),
    # guidefont = font(8),
    # legendfont = font(8),
    xticks = 29,
    yticks = 29,
    )
```

![image](https://user-images.githubusercontent.com/3512490/44308801-8546f800-a3bc-11e8-905d-fbd89af56187.png)

**Comment by mkborregaard** [comment]
Plots does the skipping - under the assumption that the default should be to only print as many ticks as can still be done without overlapping, while the user has the option to take control with the ticks argument if they want.

**Comment by swiesend** [comment]
Thank you for your reply. As it is possible to solve the problem I closed the issue.
