### ISSUE TITLE
`spy` function not working on large sparse matrices

### ISSUE THREAD

**Issue by briochemc** [JuliaPlots/Plots.jl#1682]
I'm not sure it has been mentioned here but I could not find a similar previous issue. The `spy` function segment-faults when the size is too big for it (on my system).
MWE that does not work for me (v0.7): 

```julia
using SparseArrays, LinearAlgebra, Plots
n = 10000 # or anything more
A = sprand(n,n,10/n) + sparse(Diagonal(rand(n))) ;
spy(A)
```

The MWE above gives me the following error:

```
signal (11): Segmentation fault: 11
in expression starting at no file:0
```

**Comment by briochemc** [comment]
It would be nice for Julia to be able to replicate this MATLAB snippet:
```MATLAB
n = 1000000 ;
v = ones(n,1) ;
A = sparse(1:n, 1:n, v) ;
spy(A)
```
(Note this plots in a few seconds in MATLAB.)

**Comment by briochemc** [comment]
Yes of course! :) See below:
![screen shot 2018-08-20 at 12 36 25 pm](https://user-images.githubusercontent.com/4486578/44362375-b33c4300-a475-11e8-952a-174d7c31d30f.png)

**Comment by briochemc** [comment]
I should maybe point to some other examples, like
```MATLAB
n = 100000 ;
A = sprand(n, n, 0.1/n) ;
spy(A)
```
which produces something like:
![screen shot 2018-08-20 at 12 42 46 pm](https://user-images.githubusercontent.com/4486578/44362681-8f2d3180-a476-11e8-8df7-0c3f9229512b.png)

**Comment by mkborregaard** [comment]
@briochemc you can try the old implementation of spy here `pkg> add https://github.com/mkborregaard/Plots.jl#old_spy`. It works fairly well for your 100,000 x 100,000 example above, but it does die on the 1,000,000 x 1,000,000 example (which is also a fairly large matrix). Could you try it out and comment? I agree that it should work on as big matrices as possible.

**Comment by briochemc** [comment]
> @briochemc at what dimension does the matrix become too slow to plot? We might check for more than 10,000 or 1,000,000 cells and change the implementation adaptively? Or would it be better to change based on whether the matrix was sparse?

[I don't have time right now but I will try to give a suggestion (I will come back)]
I am not sure but I think it varies. I do think that past 100x100, there is no real need for a heat map. A scatter feels like the better option, and should be super fast and interactive like MATLAB. (i.e., you can zoom in to check the sparsity pattern), right? I guess one solution in Julia is to extract the indices and plot a scatter? Something like
```julia
i, j, v = findnz(A)
scatter(i, j, v)
```
could work, right?

**Comment by mkborregaard** [comment]
Yes in fact that's what the branch I suggested you check out does

**Comment by briochemc** [comment]
@mkborregaard So I tried your old `spy` suggestion and it works (and breaks) like you said. What about `UnicodePlots`'s strategy? It seems to be binning values together when doing a `spy` plot. Could we have a version of `spy` that applies this binning (limited to say 1000x1000 bins)? I also like the red/blue/purple color scheme accoring do positive/negative/both. (If someone wrote such a `spy` function, I suggest calling it `superSpy`, and the documentation would just say "When `spy` does not work, use `superSpy`.")

**Comment by mkborregaard** [comment]
@Evizero do you think that some of UnicodePlots' strategy could be used to help handle massive matrices for spy in Plots?

**Comment by Evizero** [comment]
well the thing unicodeplots does here is abuse the fact that its inherrently a raster plotter. this means the binning to the closest displayable pixel happens "by definition" (for the lack of a better term). because unicodeplots can only set/unset a pixel this works out fine (after a pixel is set it won't be unset, so no matter how lonely and isolated a non-zero value is, it will always be visible). 

I am not sure how to best tackle this with a vector-plotting strategy. maybe plots provides a way to bypass that and go straight to raster? in that case one could just loop through all the non-zero values and set the right pixel if its not set yet. the key here is that its not an average value but a max value. otherwise the zeros will dominate the nonzeros.

**Comment by briochemc** [comment]
I am guessing `UnicodePlots`'s `spy(S)` builds is a "small" matrix (I'll call it `binnedS`) of pixels that are blue/red/purple. Wouldn't `binnedS` be directly usable to create an image using another plotting backend, without the limitation of using Unicode characters? If so, one could have a parameter for increasing the number of bins? This would allow for some clean (publishable?) spy plots, right? (I may be saying things that don't make sense 😄)

**Comment by mkborregaard** [comment]
I've pushed a fix to the old_spy branch that removes the colors. Now displaying the plot is practically instantaneous, but building the plot still takes a lot of time. Will investigate furthere.

**Comment by briochemc** [comment]
Hey @mkborregaard, 

I thought I'd leave my comments here for you to see them without using slack 🙂 I thought it could be a good idea to have some tests with sparse matrices from the [matrix depot](https://matrixdepotjl.readthedocs.io/en/latest/interface.html#interfaces), which comes with a v1.0-compatible [julia package](https://github.com/JuliaMatrices/MatrixDepot.jl) to download and use the matrices! This package works nicely, and it could provide a robust way of testing spy, right? So for example, I got julia to crash with

```julia
using SparseArrays, LinearAlgebra, Plots, MatrixDepot
matrixdepot("TKK/engine", :get) # Download a big matrix
T = matrixdepot("TKK/engine", :r) # Read it into T
T = sparse(T) # convert type of T to non-symmetric (not supported by spy, right?)
spy(T)
```

And this got me the following error:
```bash
2018-09-04 17:22:25.875 julia[69078:6960895] *** Terminating app due to uncaught exception 'GKSTermHasDiedException', reason: 'The connection to GKSTerm has timed out.'
```

(Side note: The conversion to non-symmetric must be doable in a more efficient way, unless `spy` can handle the `Symmetric` type and I misunderstood.)

**Comment by mkborregaard** [comment]
I think you're hitting a connection problem with GR which I'm also having from time to time, but which is not related to spy. `spy` supports anything that supports `findnz` - maybe that could be defined for Symmetric sparse matrices in `SparseArrays`?

**Comment by briochemc** [comment]
@mkborregaard Sorry to bring this up again, but it really bothers me that I cannot use any spy function other than `UnicodePlots`'s. So I apologize but I need to ask again, example in hand. Do you think we could have a binning version that works with any size? See this binning example:
```julia
using SparseArrays, LinearAlgebra, Plots
nmax = 1000 # Define the max number of bins
n = 1000000
T = sprand(n, n, 1/n)
i, j, v = findnz(T)
ibin = ceil.(eltype(i), nmax/n*i)
jbin = ceil.(eltype(j), nmax/n*j)
binnedT = sparse(ibin, jbin, v)
spy(binnedT)
```
Of course I can do that every time I would need it myself, but maybe it would be nice to have a "printable" version of spy that also works for large matrices. A few things to deal with: 
- The labels, which should point to the original indices of the non-binned matrix
- The colormap does not really make sense after binning I think. Maybe juts a black/white or like `UnicodePlots` a blue/purple/red would be better?

**Comment by mkborregaard** [comment]
So if you read my comment above it was that there's a temporary issue with the GR integration for large datasets unrelated to spy. We're working on it, that should be solved at some point. 

But seriously, you have plots with 1e12 points? :-O

Anyway, the GR backend is working on adaptive zoom-based binning that should allow arbitrarily big data sets.

**Comment by mkborregaard** [comment]
That said, you might build a user recipe doing the binning. To get the labels right you'd probably use `xformatter` etc.

**Comment by briochemc** [comment]
> So if you read my comment above it was that there's a temporary issue with the GR integration for large datasets unrelated to spy. We're working on it, that should be solved at some point.

So you are saying that in the near future the same spy plot will not crash Julia? (Hopefully?)

> But seriously, you have plots with 1e12 points? :-O

No I don't think I have anything *that* big. Typically the matrices I use are of size `(n, n)` with `n` ranging from 1e5 to 2e6, and with about 10 to 100 non-zeros per row/column, so about 1e6 to 2e8 non-zeros. (These are `spy`'d fairly quickly in MATLAB 😉)

> Anyway, the GR backend is working on adaptive zoom-based binning that should allow arbitrarily big data sets.

Oh wow that sounds super fancy!

> That said, you might build a user recipe doing the binning. To get the labels right you'd probably use xformatter etc.

Oh yes I am very new to plotting in Julia so I did not even think about recipes! I need to learn how to bake those! 😋 That's a very good point and suggestion, thank you!

**Comment by mkborregaard** [comment]
Yes, there's no reason the plot should crash.

**Comment by briochemc** [comment]
I was just enjoying the Julia v1.6.0 REPL display of sparse matrices and came back to try `spy` again, and I'm not sure this has really been solved? 🤷 

Here is a MWE (Julia v1.6.0, OSX Big Sur v11.2.3):
```julia
using MatrixDepot, SparseArrays, Plots   # MatrixDepot v1.0.3, Plots v1.11.2
M = sparse(matrixdepot("Rothberg/cfd2")) # size about 125k × 125k with ~3M stored entries
spy(M)
```

and outputs this nice `spy` plot (but takes about ***4 minutes*** to do so unfortunately):

<img width="712" alt="Screen Shot 2021-04-07 at 12 30 18 pm" src="https://user-images.githubusercontent.com/4486578/113801953-33398780-979d-11eb-9549-3856e102aa82.png">

and this is not the time-to-first plot issue. For example, running
```julia
plot()
spy(M)
```

right after to test also takes about 4 minutes.

I was expecting `spy` to "just work" today with large sparse matrices 😅 (E.g., hoping the GR backend work on adaptive zoom-based binning was completed and used under the hood.) Am I missing something?
