### ISSUE TITLE
Method error: length(::ColorGradient)

### ISSUE THREAD

**Issue by Nosferican** [JuliaPlots/Plots.jl#1690]
Not sure if the issue is in Plots.jl or RecipesBase.jl.
[See this Discourse post for a case](https://discourse.julialang.org/t/plot-surface-with-methoderror-no-method-matching-length-colorgradient/14011).

**Comment by mkborregaard** [comment]
It's here in Plots. This is the case of singleton objects (the colorgradient) no longer being broadcast as singletons on 0.7. I thought we'd fixed all of those, but for quite a while I suspect we're going to be finding more through reported errors.

**Comment by Nosferican** [comment]
I am updating some code that uses it so I will keep bringing the reports as I find them here. Let me know when patches are available on master and I can give y'all confirmation that it works.

**Comment by daschw** [comment]
I can't reproduce on master

**Comment by Nosferican** [comment]
Fixed on `v"0.19.3"`. Sorry about the noise. Thanks.

**Comment by mkborregaard** [comment]
Awesome, please reopen and report if you do find instances of this. Doing a search for all dots and trying to work out if some of the arguments might be singletons in some contexts is... a bit of work.
