### ISSUE TITLE
Supported Attributes tables in Plots documentation disappeared

### ISSUE THREAD

**Issue by cwb0** [JuliaPlots/Plots.jl#1702]
In Plots documentation no Supported Attributes are enlisted anymore. Instead I’ve got:

# 404

**File not found**

The site configured at this address does not contain the requested file.

**Comment by daschw** [comment]
Thanks for reporting! This should be fixed in https://github.com/JuliaPlots/PlotDocs.jl.

**Comment by daschw** [comment]
See also https://github.com/JuliaPlots/PlotDocs.jl/pull/102#issuecomment-416150981

**Comment by daschw** [comment]
Fixed in https://github.com/JuliaPlots/PlotDocs.jl/pull/103
