### ISSUE TITLE
Unicode Support in Julia 1.0

### ISSUE THREAD

**Issue by danmrc** [JuliaPlots/Plots.jl#1709]
Hi,

I've recently upgraded to Julia 1.0. For some reason, when I use unicode characters (like ã or ç) in the label of a plot, it works in atom, but _doesn't work when you save a png_ . It shows boxes instead of the characters. 

I was only able to test with the gr() - neither plotly, plotlyjs or pgfplots work. I am using a iOS High Sierra.

Thanks in advance

**Comment by mkborregaard** [comment]
Most likely this is a GR issue.

**Comment by mkborregaard** [comment]
Would you mind opening this as an issue on GR? Thanks!
