### ISSUE TITLE
plotattributes change broke plotly(js) backends

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Plots.jl#1713]
```julia
julia> using Plots

julia> plotly()
Plots.PlotlyBackend()

julia> plot(rand(10))
Error showing value of type Plots.Plot{Plots.PlotlyBackend}:
ERROR: UndefVarError: plotattributes not defined
Stacktrace:
 [1] plotly_series(::Plots.Plot{Plots.PlotlyBackend}, ::Plots.Series) at /home/pietro/.julia/packages/Plots/MnXMC/src/backends/plotly.jl:576
```

**Comment by mkborregaard** [comment]
I believe this was fixed in https://github.com/JuliaPlots/Plots.jl/pull/1711  - are you not on master?

**Comment by piever** [comment]
Ups, I'm clearly outdated and missed the closed issue, sorry about the noise! Pulling latest master fixed it. I'm leaving this issue open in case people experience the same problem, at least until we have a release with the fix.
