### ISSUE TITLE
Updated docs for Julia v1.0

### ISSUE THREAD

**Issue by monsij** [JuliaPlots/Plots.jl#1714]
Some commands like `Pkg.add("Plots")` are not working. Instead it can be installed through package repl as `add https://github.com/JuliaPlots/Plots.jl/`.  Could this be a possible area of improvement?

**Comment by mkborregaard** [comment]
Well `]add Plots` works. What is the issue when using `Pkg.add`?

**Comment by eddy-geek** [comment]
FWIW, it works for me. I could install on 1.0 in IJulia with Pkg.add("Plots").
