### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by Nosferican** [JuliaPlots/Plots.jl#1719]
Leaving an issue to track this.

For example, `repmat` is being used still in [examples](http://docs.juliaplots.org/latest/examples/gr/#contours).

**Comment by mkborregaard** [comment]
The examples are in Plots and double as tests. The reason `repmat` still runs is that we run Travis on julia 0.7. Bumping Travis to 1.0 should do the trick - I'll do that today.

**Comment by mkborregaard** [comment]
If you have comments on the doc outside of this, could you open an issue on PlotDocs.jl? Funny enough, we just reorganized our docs yesterday. It might have brought some older material more to the surface...

**Comment by daschw** [comment]
I already fixed the functions in PlotDocs.jl locally. I see if I can manage to open a WIP PR today in the evening. This also needs support PRs on Plots and PlotReferenceImages and, for plotlyjs png saving to work on Plots, we also need https://github.com/JuliaLang/METADATA.jl/pull/17541. Until then I cannot generate PlotlyJS images.

**Comment by mkborregaard** [comment]
Awesome! What's your take on the synchronisation issue I mentioned, do you have a fix for that in there?
