### ISSUE TITLE
Issue with GR plot in Atom

### ISSUE THREAD

**Issue by rveltz** [JuliaPlots/Plots.jl#1727]
Hi,

I would like to plot a layout in Atom. But, if there are too many points, nothing is output. For example, changing (in the following example) 20000 to 200000 outputs nothing in Atom with Julia v0.7, osx.

Is it to be expected?

Thank you for your help.

```julia
gr()
        Plots.plot(layout=(3,1))
        Plots.plot!(rand(20000),subplot=1)
        Plots.plot!(rand(20000),subplot=2)
```

**Comment by mkborregaard** [comment]
I actually currently have this issue in the REPL as well.

**Comment by sosiristseng** [comment]
I also have this issue. Running Win10 and Julia v1.0. However, savefig() works.

**Comment by rveltz** [comment]
Hi,

Any idea where this might be coming from?

**Comment by jheinen** [comment]
I can even plot `Plots.plot!(rand(2000000),subplot=...)` - it's probably a question of memory resources in your host environment. Plotting such amounts of data in a reasonable way requires compressing the dataset into much smaller aggregate arrays and display it as an image. This will be supported in the next major GR release.

**Comment by rveltz** [comment]
But it used to work in Atom / julia v0.6.4 ...

**Comment by jheinen** [comment]
Also 0.6.4 works for me with 2000000 points ...

**Comment by daschw** [comment]
> Well that shows that the error is in the Plots gr backend, not GR itself.

Why? @jheinen used `Plots.plot!(rand(2000000),subplot=...)` and it worked for him on both, 1.0 and 0.6.4. I don't think we can conclude anything from that.

> I wonder if it isn't still the segmentation PR that's increased memory consumption

That was already introduced in Plots 0.17.0 and 0.17.1. Nevertheless, it could still be related. I need to take a closer look, but first I want to finish the docs PRs this weekend.

**Comment by rveltz** [comment]
I see this issue in Atom - Julia v1.0 on OSx.

  [28b8d3ca] GR v0.34.1
  [91a5bcdd] Plots v0.20.2

not in the REPL.

**Comment by daschw** [comment]
I also see it in the REPL.

**Comment by mkborregaard** [comment]
> Why?

Because  he used GR 0.34.1 on both - am I overlooking something?

**Comment by rveltz** [comment]
Does anybody could get his hands on the problem in Atom plotting with GR?

**Comment by BioTurboNick** [comment]
I've encountered this issue as well. Plotting large numbers of points works in external REPL but not in Atom.

Was suggested to me to ping @pfitzseb on this.

May be related: unable to create new plot window with gui(), or when Juno's settings disables the plot plane, within Juno.

**Comment by jheinen** [comment]
Plotting large numbers of points or lines using SVG may cause trouble when rendered within a browser, Atom or nteract. For plain `GR` you should use the new `shade` function or switch to PNG format.

GR 0.36.0 fixes similar problems with the default output (`GKSterm`) on macOS.

For `Plots.jl` I'd recommend to switch to GR 0.36.0, too.

**Comment by BioTurboNick** [comment]
I can confirm that with GR 0.36.0 the Juno plot interface works. Can also confirm that switching back to SVG breaks things with Juno again.  Too bad, because resizable/zoomable plots are good for inspecting positional point data (e.g. single molecule localization microscopy).

However, I could only get the newest  GR version when I switched from the JuliaPro 1.0.1.1 distribution of Julia to a manually downloaded Julia 1.0.2. The former was stuck at 0.34.1 for some reason.

**Comment by jheinen** [comment]
Would be interesting for us to have a concrete example (single molecule localization microscopy). Could you provide a reference to a notebook or Julia script along with the data? Either, the SVG part (in GR) can be further optimized, or, the data can better be displayed using the new `shade` functions, or we/you have to wait for the new GR output capabilities (e.g. JavaScript widget) to be finished.

**Comment by BioTurboNick** [comment]
@jheinen - Sure, I can put something together after the holiday. Perhaps SVG isn't the right answer though; I think it would need to be more like MATLAB where the points stay the same size as you zoom. Unless another backend exists that provides that ability?

We're talking about clusters of points ~100-500 nm in a field ~50 microns across, so being able to zoom in on each one to inspect their structure is helpful, and for comparing the results of filtering/grouping operations on them.

**Comment by jheinen** [comment]
> @jheinen - Sure, I can put something together after the holiday. Perhaps SVG isn't the right answer though; I think it would need to be more like MATLAB where the points stay the same size as you zoom. Unless another backend exists that provides that ability?
> 
> We're talking about clusters of points ~100-500 nm in a field ~50 microns across, so being able to zoom in on each one to inspect their structure is helpful, and for comparing the results of filtering/grouping operations on them.

This is exactly what the new `shade` function in GR provide. You seem to require not just a visual zoom but an aggregation followed by an abstract rendering (as opposed to overplotting) step - that's exactly what the new GR function do.
