### ISSUE TITLE
png and savefig names clash with VegaLite

### ISSUE THREAD

**Issue by jlperla** [JuliaPlots/Plots.jl#1736]
```julia
julia> using Plots

julia> using VegaLite

julia> png
WARNING: both VegaLite and Plots export "png"; uses of it in module Main must be qualified
```
Right now `png` and `savefig` clash.  For the most part, one takes `Plots.jl` types and another takes `VegaLite.jl` types so there is no reason that they can't coexist at all.

Is it possible for you to agree on some sort of `PlotsBase` for shared names to prevent this (and maybe future issues I haven't noticed)?  It might also make coexistence with things like Makie easier.

Also, I am not a big fan of the `png` and `savefig` which do not take the plot as an argument... but maybe that is just me.  VegaLite doesn't do that

**Comment by jlperla** [comment]
@davidanthoff  I am cc:ing you on this as well, instead of posting a separate issue to VegaLite, etc.

**Comment by davidanthoff** [comment]
I'd be happy to just remove those from VegaLite.jl completely, and tell folks to use the FileIO ``save`` function that is reexported from VegaLite.jl instead. That is also what we recommend in the [docs](http://fredo-dedup.github.io/VegaLite.jl/latest/userguide/vlspec.html#Saving-plots-1) currently. But I would want to first know what @fredo-dedup thinks about that, before we go ahead.

Oh, and in case Plots.jl has ``show`` methods for the PNG, SVG, PDF and EPS mime types, it should actually work out of the box with the FileIO ``save`` function right now :) There is nothing VegaLite.jl specific there, it uses the standard julia multimedia display system.

**Comment by mkborregaard** [comment]
We still export those? We should also unexport them IMHO.

**Comment by davidanthoff** [comment]
Alright, VegaLite.jl v0.5.0 no longer exports these functions. Just waiting for the METADATA PR now: https://github.com/JuliaLang/METADATA.jl/pull/17999.
