### ISSUE TITLE
Plotting large BigInts

### ISSUE THREAD

**Issue by bsvh** [JuliaPlots/Plots.jl#1744]
When trying to plot very large numbers, plots error out with an `InexactError` as it tries to convert to an Int64. This happened in every backend that I tried. Plotting using GR itself without Plots.jl works as expected.

**Comment by daschw** [comment]
Could we workaround this with a type recipe for BigInts?

**Comment by mkborregaard** [comment]
What would it do? Divide by some number and adjust the plot axes?
