### ISSUE TITLE
Contour Bite

### ISSUE THREAD

**Issue by iwelch** [JuliaPlots/Plots.jl#1745]
I know this is a nasty example, but is this also a bug or not?

```julia
julia> using Plots
julia> x= [1:5;]; y= [3:9;]
julia> f(x,y) = x^2*sqrt(y);
julia> contour( x, y, f, nlevels=100, width=2, size=[800,480])
julia> savefig("plotting/contour.png")
```

on maxos, this has a "bite" around x=4. y=8.

**Comment by BeastyBlacksmith** [comment]
I can reproduce with the gr backend, but not with pyplot

**Comment by t-bltg** [comment]
Closing in favor of https://github.com/jheinen/GR.jl/issues/501.

**Comment by t-bltg** [comment]
FYI, this is fixed in latest GR version.
