### ISSUE TITLE
multiple surface plots?

### ISSUE THREAD

**Issue by iwelch** [JuliaPlots/Plots.jl#1747]
I hope this is not my misunderstanding.  In the following, I see only the bottom right figure.

```
using Plots
x= [1:5;]; y= [3:9;]; f(x,y)= x^2*sqrt(y);
p1= surface( x, y, f, size=[800,480] ); p2= surface( p1, camera= (20,0) ); p3= surface( p1, camera= (20,50) ); p4= surface( p1, camera= (60,0) );
plot( p1, p2, p3, p4 , layout=4  )
```

(There may also be bugs with the GKSTerm updating.  I sometimes can get GKSTerm to update and sometimes not.  Alternating between typing p1 and p2 does not update, but the surface command itself works.   Or I am doing something else completely wrong?!)

**Comment by mkborregaard** [comment]
That's because it's all the same object, exatly like `x = y = [1,2,3]; y[2]=3; x #[1,3,3]`.
If you want to do that you can wrap the `p1`'s in a `deepcopy`.

**Comment by iwelch** [comment]
thanks.  sorry for the bother.
