### ISSUE TITLE
Error with using Plots command

### ISSUE THREAD

**Issue by anbose** [JuliaPlots/Plots.jl#1753]
Hi everyone,
I have just started learning Julia and faced some issue while using Plots. I am using Julia 1.0.0 on a windows 7 machine. I am posting the picture with the error message. Can anyone tell me what is the issue and how to resolve that?
Thanks in advance

![untitled6](https://user-images.githubusercontent.com/43315603/45710032-25479b00-bb8e-11e8-9f99-6e97da0f71c2.png)

**Comment by daschw** [comment]
Does it help if you build Plots (switch to pkg mode in Julia with `]` and enter `build Plots`)?
