### ISSUE TITLE
Colorbar placement

### ISSUE THREAD

**Issue by briochemc** [JuliaPlots/Plots.jl#1755]
MWE:
```julia
function peaks(x, y)
    z = 3 * (1 - x)^2 * exp(-x^2 - (y + 1)^2)
    z += -10 * (x / 5 - x^3 - y^5) * exp(-x^2 - y^2)
    z += -1/3 * exp(-(x+1)^2 - y^2)
    return z
end

x = range(-3, stop = 3, length = 100)
y = range(-2, stop = 2, length = 80)
levels = collect(-4:0.25:4)
vmin = minimum(levels)
vmax = maximum(levels)

using Plots
pyplot() # Set the backend to PyPlot
plt = contourf(x, y, peaks, levels = levels, clim = (vmin, vmax),
              colorbar_title = "\$\\phi\$",
              colorbar = :right,
              xlabel = "\$x\$",
              ylabel = "\$y\$")
savefig(plt, "test.png")
```
produces the following:

![test](https://user-images.githubusercontent.com/4486578/45737177-6e502b80-bc30-11e8-93c3-d982d6d0ebe9.png)

It seems the colorbar is centered with [the axes + the labels], instead of being aligned (and thus centered) with the axes only. Is it possible to align it with the axes of the plot only like in the example below?

![example](https://i.stack.imgur.com/1CRZW.png)

**Comment by lnacquaroli** [comment]
This is related to `pyplot` as `gr` produces your desired result.

**Comment by briochemc** [comment]
OK I will move the issue to [PyPlot.jl](https://github.com/JuliaPy/PyPlot.jl) 🙂

**Comment by briochemc** [comment]
Actually, `using PyPlot` works fine, so this is related to `using Plots` (reopening).

**Comment by lnacquaroli** [comment]
Yes, I was talking about the pyplot backend inside Plots, not the PyPlot itself. Sorry for the short misleading message before.

**Comment by briochemc** [comment]
I mean I don't mind using `PyPlot` directly but I thought I should point out that colorbar issue here... Is there a place to raise issues for backends rather than packages? (Me still a Julia noob)

**Comment by isentropic** [comment]
@briochemc would you please check out https://github.com/JuliaPlots/Plots.jl/pull/2722 and tell me your review
