### ISSUE TITLE
Pie chart for Dict{AbstractString, Int}

### ISSUE THREAD

**Issue by kescobo** [JuliaPlots/Plots.jl#1759]
I find myself pretty routinely wanted to plot a simple pie chart with the result of `countmap()` from statsbase - basically just a dictionary with Integers as values. I wrote up a simple recipe, and was wondering if there would be interest in including it, and if so, where?

```
@recipe function f(d::Dict{<:AbstractString, Int})
    seriestype := :pie
    xs = ["$k ($(d[k]))" for k in keys(d)]
    srt = sortperm(xs)
    ys = collect(values(d))

    xs[srt], ys[srt]
end
```

So

```
using StatsBase
using Plots

things = rand(["thing1", "thing2", thing3"], 100)

pie(countmap(things))
```

![image](https://user-images.githubusercontent.com/3502975/45961826-766fe880-bfed-11e8-9b6d-5f742c35086f.png)

**Comment by mkborregaard** [comment]
I'm not a fan of locking a recipe on `d::Dict{<:AbstractString, Int}` into showing a pie chart. But could you more generally do 
```julia
@recipe function f(d::Dict{<:AbstractString, T}) where T<:Number
    xs = collect(keys(d))
    srt = sortperm(xs)
    ys = collect(values(d))
    xs[srt], ys[srt]
end
```
which would make sense I think, and then possibly(?) adjust the `pie` series recipe to do the `["$k ($(d[k]))" for k ]` thing when passed a Vector{<:String} as the x argument? Just a suggestion not fully thought through.

**Comment by kescobo** [comment]
That's a good point - I like this compromise, and I think the `keys -> x` `values -> y` mapping for dictionaries makes some sense generically, though I can also see a situation where you have a dictionary of discrete xs that map to vectors or something...
