### ISSUE TITLE
0.7 is using Plots v0.19.3 whereas 1.0 is using Plots v0.20.2

### ISSUE THREAD

**Issue by JeffFessler** [JuliaPlots/Plots.jl#1760]
I am using 0.7 because the deprecation warnings are helpful, but I just noticed that some issues that have been fixed with Plots under 1.0 are still broken in 0.7 because 0.7 is using Plots v0.19.3 whereas 1.0 is using Plots v0.20.2.  (I did ]rm Plots and ]add Plots in both to make sure I was starting fresh).

I am not sure if this is the right forum for asking this question, but does anyone know why 0.7 is using such an older version of Plots?  I would have expected them to be more in sync...

**Comment by mkborregaard** [comment]
Simply because we drop support for older julia versions on principle when a new version comes up. It's a very nice and unintrusive way to ensure that all the components of the juliaPlots ecosystem are in sync (version sync problems, in particular with backends, is one of our biggest headaches).

**Comment by JeffFessler** [comment]
Thanks for the reply.  I thought that 0.7.0 and 1.0.0 were going to be in sync indefinitely (other than deprecation warnings)) but that was probably wishful thinking.  Time to wean from 0.7 then...

**Comment by brenhinkeller** [comment]
Sounds like word from @JeffBezanson is indeed that both versions should be supported together due to the special nature of the 0.7 release.

Is there any technical reason to prevent this? I can testify that I also would have been able to benefit more from the deprecations in 0.7 if Plots worked as well in Atom/Juno in 0.7 as it does in 1.0

**Comment by mkborregaard** [comment]
Yes there's a technical reason, which is that RecipesBase had a major breaking change on the 0.7/1.0 transition. And, 0.7 IS supported, we're just not developing Plots actively for it. If you run into one of those improvements that has come to Plots since the 1.0 update you may notice a difference, though I'm not sure which Juno issue you are referring to.

**Comment by mkborregaard** [comment]
wow, I really don't see why that should happen for the `fmt = :png` case, but I take it you are sure? You only get this with `gr()`, right?

**Comment by brenhinkeller** [comment]
Let me check

**Comment by brenhinkeller** [comment]
Hmm, not even unique to gr(); for me

```
using Plots; plotly(); default(fmt = :png)
plot(1:10,rand(10),seriestype=:scatter)
```
gives

<img width="428" alt="screen shot 2018-10-23 at 4 01 25 am" src="https://user-images.githubusercontent.com/8967875/47356264-60028e80-d678-11e8-9ffe-157239553830.png">

**Comment by brenhinkeller** [comment]
I also get:
<img width="1081" alt="screen shot 2018-10-23 at 4 05 09 am" src="https://user-images.githubusercontent.com/8967875/47356430-e8812f00-d678-11e8-9f5d-25033880bea0.png">

but

```
using Plots; gr(); default(fmt = :png)
h = plot(1:10,rand(10),seriestype=:scatter)
savefig(h,"test.pdf")
```
 is ok (screen is still tiny, but saved pdf is fine)

**Comment by mkborregaard** [comment]
Weird. The plotly error is different, it's just the backend not being fully 1.0 compliant yet.
@pfitzseb do you have any idea what could cause the tiny plot in Juno, backend-independent?

**Comment by brenhinkeller** [comment]
Also tried restarting everything from scratch and trying again in case there was some sort of memory but 
```
using Plots; gr(); default(fmt = :png)
plot(1:10,rand(10),seriestype=:scatter)
```
still gives me tiny-Plots

**Comment by brenhinkeller** [comment]
The size of the tiny-plot also scales with the horizontal (but not vertical) dimension of the plot pane at the time of plotting, so for instance

<img width="195" alt="screen shot 2018-10-23 at 4 34 26 am" src="https://user-images.githubusercontent.com/8967875/47357918-0c467400-d67d-11e8-8d75-3dc79cbecc73.png">
