### ISSUE TITLE
vline! is broken on time axes

### ISSUE THREAD

**Issue by cstjean** [JuliaPlots/Plots.jl#1762]
The y-axis becomes a time-axis when `vline!` has a time argument, even though clearly it shouldn't change:

```julia
using Plots, Dates
gr(format=:png)    # maybe not necessary
plot(DateTime.([2000,2001,2002]), [1,2,3])
vline!(DateTime.([2001]))
```
![image](https://user-images.githubusercontent.com/8622776/46038697-d348cd00-c0d9-11e8-8a02-6dec9045b4fd.png)

**Comment by daschw** [comment]
Thanks for reporting!

**Comment by cpfiffer** [comment]
I'm still having this issue, is there a fix anyone has?
