### ISSUE TITLE
No Bars in Histograms with More Than 1 Million Points

### ISSUE THREAD

**Issue by dtjohnson** [JuliaPlots/Plots.jl#1774]
If I have a histogram with 1,000,000 points or less, it looks fine:
```julia
histogram(randn(1000000), bins=10)
```
![image](https://user-images.githubusercontent.com/218771/46382993-08c25d00-c67c-11e8-99d7-beea0a8c143f.png)

However, once I go above that amount, the bars disappear:
```julia
histogram(randn(1000001), bins=10)
```
![image](https://user-images.githubusercontent.com/218771/46383002-14158880-c67c-11e8-9520-f47a4d79d6cb.png)

This makes the plot very confusing as you can't really see that the data are binned.

**Comment by dtjohnson** [comment]
Ah. Got it to work now.

I find that switchover to be odd though. Shouldn't it be based on the number of bins and not the number of data points?

**Comment by mkborregaard** [comment]
Yeah, agreed. I think it's simply a matter of convenience because currently the histogram type is selected before the auto bin number? But should be straightforward enough to change, if you implement it in a PR we'd most likely merge it.
