### ISSUE TITLE
Julia 1.0 and IJulia:  display does not seem to work

### ISSUE THREAD

**Issue by poldavezac** [JuliaPlots/Plots.jl#1778]
The following code in one IJulia cell will produce 3 plots in Julia v6.1 and none in  Julia v1

```
using Plots
gr() # same problem with pyplot()
for i = collect(1:3)
    display(plot(collect(1:5)))
end
nothing
```

using:
* python 3.6.4
* jupyter_client            5.2.3 
* jupyter_console           5.2.0
* IJulia v1.12.0

**Comment by KenziTrader** [comment]
Same here. It does work correctly and produces three plots in Julia v0.7 (with `gr(fmt=:png)` to get normal size plots).
