### ISSUE TITLE
Is the build script still needed?

### ISSUE THREAD

**Issue by KristofferC** [JuliaPlots/Plots.jl#1783]
The build script at https://github.com/JuliaPlots/Plots.jl/blob/master/deps/build.jl has effectively not been touched for 2 years. Is it still really needed?

**Comment by SimonDanisch** [comment]
Could be removed as part of https://github.com/JuliaPlots/Plots.jl/pull/1777 I guess...

**Comment by mkborregaard** [comment]
Maybe it could be run as part of initialising the `plotly` backend? Removing it would void the  backend, as it doesn't use the Plotly.jl package at all. And some users swear by it.

**Comment by SimonDanisch** [comment]
>Removing it would void the backend

That's why I'd make it part of #1777, since it wouldn't void the backend with my changes - could also do the download thing in the __init__ if required by the ENV.
