### ISSUE TITLE
Supporting minor grid and minor ticks

### ISSUE THREAD

**Issue by greimel** [JuliaPlots/Plots.jl#1794]
Is it the case that `gr()` is the only backend that support minor grids at the moment? Is `backends.jl` the place to look? The only attributes containing `*minor*` are in `gr()`. I tried `pyplot()` and `pgfplots()` seem to ignore `minorgrid = true`.

If minor grids and minor ticks were to be implemented for other backends (and, possibly, in `Makie.jl`), I would like to be able to control major and minor ticks separately. 

In #1788 I implemented two new attributes `foreground_color_tick` and `foreground_color_minor_tick` and incorporated them in the `gr()` backend.

```
plot(rand(10), rand(10), foreground_color_tick = :green, foreground_color_minortick=:red, minorgrid=true)
```
![gr-tick-colors](https://user-images.githubusercontent.com/6280307/47045319-d4c65c00-d192-11e8-9606-2439d9f2925a.png)

I propose to replace the `foreground_color_axis` attribute with these two attributes. (The color of the axis is determined by  `foreground_color_axis`.

Should I extend #1788 to replace `foreground_color_axis`  in the other backends?

**Comment by daschw** [comment]
Minor and major ticks where only implemented some months ago for GR and GLVisualize (they share the same code for drawing segments for axes, grids, ticks, etc.) in https://github.com/JuliaPlots/Plots.jl/pull/1596.
So #1788 cannot really be extended for the other backends, right?

**Comment by daschw** [comment]
I'm sorry, of course `foreground_color_tick` can be extended to the other backends.
