### ISSUE TITLE
Discontinuity points?

### ISSUE THREAD

**Issue by kirtsar** [JuliaPlots/Plots.jl#1804]
I'm trying to draw something like
```
plot(x -> 1/x, -3, 3, ylims = (-10, 10))
```
but there is always distracting vertical line in the discontinuity point.
Are there any methods to deal with it?

**Comment by mkborregaard** [comment]
That's a very good point. The solution would involve inserting an `NaN` value at the discontinuity point in this function https://github.com/JuliaPlots/PlotUtils.jl/blob/master/src/adapted_grid.jl created by @KristofferC , but that function does not presently identify discontinuity points. Ideas welcome.

**Comment by kirtsar** [comment]
My naive approach is to check this array:
```
fs = [NaN; [f(x) for x in xs[2:end-1]]; NaN]
```
for very large "jumps": 
```
abs(fs[2:end] .- fs[1:end-1]) .> boundary
```
I don't know whether it is good or not.

**Comment by KristofferC** [comment]
Stopping the refinement for intervals that are outside the y-limits of the plot would also be good.

**Comment by BeastyBlacksmith** [comment]
I think the issue is, that `adaptive_grid` doesn't hit the discontinuity point exactly.
You can work around, if you know the points before hand by
```julia
 plot(x -> 1/x, -3, 0, ylims = (-10, 10)); plot!(x -> 1/x, 0, 3)
```
