### ISSUE TITLE
`plotlyjs()` fails if `ORCA.jl` is not installed.

### ISSUE THREAD

**Issue by ederag** [JuliaPlots/Plots.jl#1807]
`plotlyjs()` fails if `ORCA.jl` is not installed.
Either from jupyter lab or from the REPL:

```julia
using Pkg
Pkg.add("Plots")
Pkg.add("PlotlyJS")
using Plots
plotlyjs()

ArgumentError: Package ORCA not found in current path:
- Run `import Pkg; Pkg.add("ORCA")` to install the ORCA package.


Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:820
 [2] top-level scope at /home/ederag/.julia/packages/Plots/rmogG/src/backends.jl:575
 [3] eval at ./boot.jl:319 [inlined]
 [4] _initialize_backend(::Plots.PlotlyJSBackend) at /home/ederag/.julia/packages/Plots/rmogG/src/backends.jl:574
 [5] backend(::Plots.PlotlyJSBackend) at /home/ederag/.julia/packages/Plots/rmogG/src/backends.jl:196
 [6] backend(::Symbol) at /home/ederag/.julia/packages/Plots/rmogG/src/backends.jl:209
 [7] plotlyjs() at /home/ederag/.julia/packages/Plots/rmogG/src/backends.jl:29
 [8] top-level scope at In[20]:1
```

It does not seem to be a PlotlyJS issue:
https://github.com/sglyon/PlotlyJS.jl/issues/243#issuecomment-432640719

But after reading the source, it looks like it was never intended to be automatic.
`add_backend` can be used, but only to give informations:
```julia
julia> using Plots
julia> add_backend(:plotlyjs)
┌ Info: To do a standard install of plotlyjs, copy and run this:
└ 
using Pkg
Pkg.add(["PlotlyJS", "Blink", "ORCA"])
import Blink
Blink.AtomShell.install()
```

**Comment by ederag** [comment]
The error is clear, so I'll just report to the tutorial where the Pkg.add("ORCA") is missing.

**Comment by juliohm** [comment]
This issue is quite annoying though, can't we have ORCA installed by default if it is needed for doing plots with Plots.jl + PlotlyJS.jl?

**Comment by mkborregaard** [comment]
which package should install it by default?

**Comment by juliohm** [comment]
Maybe PlotlyJS.jl? I don't understand the relationship between PlotlyJS.jl and ORCA.jl but I think that the use case with notebooks is quite popular. PlotlyJS.jl could depend on ORCA.jl if this is a required dependency for generating plots with Plots.jl in Jupyter notebooks.

**Comment by mkborregaard** [comment]
You could try to open an issue for that on PlotlyJS.jl but I think it's a deliberate design that it doesn't.

**Comment by sglyon** [comment]
I can clarify here.

ORCA.jl is how PlotlyJS.jl saves plots to files (other than html, svg, json).

It has some binary components to it, so to try and forestall potential installation issues I decided to make those features optional and load in the glue code that leverages ORCA.jl via Requires.jl

So, for PlotlyJS.jl direct users they only need to worry about installing ORCA if they want to save pdf/png/jpeg

However, if Plots.jl assumes backends can save to those file types (certainly a sane assumption!), then it makes sense to ensure it is installed when users try to activate the `plotlyjs()` backend here

**Comment by mkborregaard** [comment]
Yes that's pretty much as I thought it were. The issue from the Plots side being that we also depend on all the backends via Require - which does offer a particular challenge when a backend requires more than the core package to run. 
Essentially Plots always relies on the user to install the backend themselves if they want it, and if the backend requires two packages, the user has to install two. That's definitely not so intuitive, but it's hard to see what to do about it Plots side.
For PyPlot we also rely on e.g. PyCall, but since PyPlot imports PyCall we can just fetch it via PyPlot.Pycall. Unfortunately we can't do the same thing here.
