### ISSUE TITLE
Discrete Contour Fill

### ISSUE THREAD

**Issue by jleman** [JuliaPlots/Plots.jl#1809]
I am trying to prepare a filled contour plot with discrete levels. However, it appears that only a continuous gradient is possible (attached example). Is it possible to specify the number of contours and have a solid fill in between levels? On contour plots without fill I see it is possible to specify the number of levels. Can this be done with a filled contour plot?

using Plots
f(x,y) = (3x + y^2) * abs(sin(x) + cos(y))
x = 0:0.1:20
y = 0:0.1:10
z = [f(i,j) for i in x, j in y]'
#plot(x,y,z, st=:wireframe, camera=(45, 50))
contour(x,y,z;fill=true,levels=10)#levels does not change the plot

![continuousfill](https://user-images.githubusercontent.com/44458380/47479927-7a0cb000-d7e3-11e8-9fa7-ebf7fc01da87.png)

I'm looking to do something like this:

![discretefill](https://user-images.githubusercontent.com/44458380/47479943-8a248f80-d7e3-11e8-9206-bfda5b29aed4.PNG)

**Comment by mkborregaard** [comment]
This is because GR does interpolation on contour plots. Try using the pyplot backend instead

**Comment by BeastyBlacksmith** [comment]
works for me on Plots 1.3.5
