### ISSUE TITLE
heat map for 1 vector.

### ISSUE THREAD

**Issue by lazarusA** [JuliaPlots/Plots.jl#1814]
Hi, what is the proper way to plot one vector. In matplotlib is like this 

import matplotlib.pyplot as plt
vector = [0,1,0,5]
plt.imshow([vector], cmap = "Greys");

but with Plots this doesn't seems to work.

**Comment by daschw** [comment]
If you only pass one vector to the a `plot` command in general - in this case `heatmap` - it is interpreted as the `y` value. For `heatmap` however, you want it to be the `z` value. With #1815 you can now achieve this on Plots master either by passing a matrix
```julia
heatmap(reshape(vector, length(vector), 1))
```
or by specifying the `x`, `y` and `z` values:
```
heatmap(eachindex(vector), [1], vector)
```

**Comment by lazarusA** [comment]
Just the first option works, but it's ok, I think it must be the right way to do it. 
![screen shot 2018-10-30 at 7 02 29 am](https://user-images.githubusercontent.com/19525261/47719788-cefc5c00-dc11-11e8-8ef9-3bbb3eaca404.png)
