### ISSUE TITLE
Making Plots load faster

### ISSUE THREAD

**Issue by oschulz** [JuliaPlots/Plots.jl#1825]
I loaded Plots.jl and it's direct and indirect dependencies in various combinations, to get and idea of why Plots takes so long to load. 

[...]

Edit: see more detailed analysis below.

**Comment by SimonDanisch** [comment]
>FixedPointNumbers: 1.31 s

That's suspicious, since it's likely one of the smallest packages here.
A quick test for me on Julia 1.0:
```Julia
julia> @time using FixedPointNumbers
  0.074016 seconds (198.94 k allocations: 13.102 MiB)
```
Any chance you measured something else? Or included precompilation for some packages, while not for others?

**Comment by SimonDanisch** [comment]
Ah `using Pkg` is order dependent, since the most work is likely merging method tables... So when I e.g. load StaticArrays first, the time of loading FixedPointNumbers goes up!

**Comment by oschulz** [comment]
That's what I meant with "it's tricky". Just stumbled on this:

    julia -e '@time import Contour, GR'
      2.134703 seconds
    julia -e '@time import GR, Contour'
      0.546491 seconds

Wouldn't have expected that using order would make such a drastic difference.

**Comment by oschulz** [comment]
Actually, why do we require Contour.jl? I can't see it loaded anywhere in Plots, but maybe I overlooked some indirect load.

**Comment by oschulz** [comment]
# Load time of Plots.jl dependencies

I analysed this in a bit more detail. I successive stripped all code out of Plots, PlotThemes, PlotUtils and RecipesBase. I tested the load time for Plots using

    for i in 1 2 3 4 5; do julia -e '@time import Plots'; done

Here are the resulting average load times:

* Full Plots: 3.5 s
* Empty Plots: 3.2 s
* Empty PlotThemes: 2.9 s
* Empty PlotUtils: 2.1 s
* Empty RecipesBase: 2.1 s

So the net load time caused by the package code is:

* Plots code: 0.3 s
* PlotThemes code: 0.3 s
* PlotUtils code: 0.8 s
* RecipesBase code: 0.0 s :-)

I realize this is a bit simplistic, but not entirely meaningless, I think. What are we doing in PlotUtils that adds almost a second to the load time?

Next, I removed the now empty packages PlotThemes, PlotUtils and RecipesBase from Plots' deps and added their deps explicitly.

* Empty Plots, all deps of Plots package system: 2.1 s

As expected, the same load time as before (all packages empty). Plots now looks like this:

```
module Plots

import Base64, Dates, LinearAlgebra, Pkg, Printf, Random, SparseArrays, Statistics

import Colors
import FixedPointNumbers
import GR
import JSON
import Measures
import NaNMath
import Reexport
import Requires
import Showoff
import StaticArrays
import StatsBase
import UUIDs

end # modules
```

Now the relative time difference when disabling packages one-by-one.

* No Colors: -1.4 s
* No FixedPointNumbers: -0.05 s
* No GR: -0.15 s
* No JSON: -0.1 s
* No Measures: -0.1 s
* No Reexport: -0.0 s
* No Requires: -0.25 s
* No Showoff: -0.0 s
* No StaticArrays: -0.5 s
* No StatsBase: -0.5 s
* No UUIDs: -0.05 s


Of course some of these dependencies depend on each other.

A few cross-checks:

* No Colors, StaticArrays, StatsBase: -1.6 s
* No StaticArrays, StatsBase: - 1.0 s
* No Colors, StatsBase: - 1.15 s
* No Colors, StaticArrays: -1.15 s

We need Colors and StatsBase, and we both use StaticArrays and define recipes for it, so there's probably not much room for improvement regarding package load time at the moment.

However, maybe there's a change of changing something in the code of our packages, especially PlotUtils, to reduce Plots' total load time?

**Comment by timholy** [comment]
I happened to stumble across this. I bet this was caused by invalidation (if you invalidate Pkg or Base code needed to load the next package, you have to wait for that code to recompile). On Julia 1.6 it seems basically fixed:
```julia
tim@diva:~/.julia/dev/PerceptualColourMaps$ time julia-master --startup-file=no -e 'import Contour, GR' 
real	0m0.765s
user	0m0.845s
sys	0m0.212s
tim@diva:~/.julia/dev/PerceptualColourMaps$ time julia-master --startup-file=no -e 'import GR, Contour' 
real	0m0.779s
user	0m0.872s
sys	0m0.200s
```

So perhaps close?

**Comment by mkborregaard** [comment]
Yes seems fair to close

**Comment by oschulz** [comment]
Oh, nice, thanks for the heads-up @timholy !
