### ISSUE TITLE
Histogram with a log scale

### ISSUE THREAD

**Issue by pstaabp** [JuliaPlots/Plots.jl#1833]
First, I wasn't sure if this is a Plots or a StatPlots issue, but here goes: 

Although, one may argue, I shouldn't do the following, but if I
```
histogram(rand(1:1000,100),bins=10,xscale=:log10)
```
there the following error:
```
DomainError with -30.0:
NaN result for non-NaN input.
```

My best guess is that the limits are not chosen to be positive, because if one enters
```
histogram(rand(1:1000,100),bins=10,xscale=:log10,xlim=(75,1500))
```
the results is a reasonable plot.  (I know there can be discussion about whether or not a log scale should be use with a bar plot, but...)

I have tried using log scale with other plots without error, so it may be just the histogram.

**Comment by mkborregaard** [comment]
dup of #833
