### ISSUE TITLE
Error with py_color when using Color Gradient with PyPlots

### ISSUE THREAD

**Issue by mbotkinl** [JuliaPlots/Plots.jl#1834]
When I specify the series color as a Color Gradient, I get an error
```
using Plots; pyplot()
plot(rand(20,5), seriescolor= :RdYlBu)
```

```
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: MethodError: no method matching py_color(::ColorGradient, ::Nothing)
```

This same syntax work for the GR backend of Plots. I am using julia 1.0.1, Plots 0.21.0 and PyPlot 2.6.3

**Comment by mkborregaard** [comment]
I bet this is a matplotlib 3.0 thing

**Comment by mkborregaard** [comment]
On my computer that code snippet segfaults :-O

**Comment by daschw** [comment]
On GR this does not really work either, you get a plot with only red lines. I think what you actually want to do is
```
plot(rand(20, 5), palette = :RdYlBu)
```
right?

**Comment by daschw** [comment]
Still, this should not produce an error like that.

**Comment by mbotkinl** [comment]
Yes, what i really want to do is something like:

`plot(rand(20,5),palette=:RdYlBu,line_z=(1:5)')`

However, `plot(rand(20,5),seriescolor=:RdYlBu,line_z=(1:5)')` works for GR but not pyplot. Not sure if that is the intended behavior or not but figured I would submit the error anyways.

**Comment by daschw** [comment]
Ah now I see, with `line_z` `seriescolor = :RdYlBu` makes sense, I guess. Thanks a lot for reporting!

**Comment by mkborregaard** [comment]
Some more info on the duplicate issue https://github.com/JuliaPlots/Plots.jl/issues/1876

**Comment by BeastyBlacksmith** [comment]
seems to be fixed. Can't reproduce anymore.
