### ISSUE TITLE
Add docs for new image limits format

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Plots.jl#1837]
There appears to be a regression (see previous issue https://github.com/JuliaPlots/Plots.jl/issues/850) but now its impacting both GR and Plotly:
```julia
img = rand(RGB{Float64}, 256, 256)
plot(img;xlims=(-3,3),ylims=(-3,3))
```
no longer rescales the image to be within the prescribed limits.

**Comment by apalugniok** [comment]
As far as I remember that is how I intended it to be done.
