### ISSUE TITLE
non-scientific yformatter option

### ISSUE THREAD

**Issue by Cody-G** [JuliaPlots/Plots.jl#1840]
This came up in #413.  If one wants to avoid automatic scientific notation of y tick labels there doesn't seem to be a way to do so (currently there are only `:scientific` and `:auto` options).  How about we add an option like `yformatter=none` or `yformatter=:nonscientific`?  I don't have any strong opinion about the name of the option.

**Comment by daschw** [comment]
`yformatter = :plain` should do what you want.

**Comment by mkborregaard** [comment]
:-O

**Comment by Cody-G** [comment]
Wow awesome, I had no idea--thanks!
