### ISSUE TITLE
GR doesn't render LaTeX inside other text

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#1842]
This works in the PyPlot backend:
```
plot(rand(10), title="foo \$a\$")
```
but on GR, the title renders as 
![image](https://user-images.githubusercontent.com/4170948/48359411-947ccf80-e6a5-11e8-99c4-d4cb6226f374.png)

**Comment by daschw** [comment]
cc: @jheinen

**Comment by jheinen** [comment]
Right now, LaTeX ($...$) and normal text cannot bei mixed or nested.

**Comment by daschw** [comment]
@jheinen Is there already a way the GR can render something like "foo \$a\$"?

**Comment by t-bltg** [comment]
This seems to work now.
