### ISSUE TITLE
`scatter` & `gr` gives grey (? black?) markers?

### ISSUE THREAD

**Issue by BerntLie** [JuliaPlots/Plots.jl#1845]
One more bug in `gr`... and partly `pyplot`

```julia
using Plots; gr()
Eig=rand(20,2)
scatter(Eig[:,1],Eig[:,2],shape=:x,ms=5,ma=0.6,mc=:rainbow,mz=1:20,label="")
```
gives *black* (or: washed-out black?) and very big markers...
![image|690x478](upload://u2J1iUD0YJUzyzCJRPgODTSsAue.jpeg) 
while using the `pyplot` backend  gives the expected result:
![image|690x463](upload://kNulms1BQnPlDwZ3rQReRWY3M22.png) 

With both `gr` and `pyplot`, I get the following strange warning:
```julia
┌ Warning: rainbow is found in more than one library: misc, colorcet. Choosing misc
└ @ PlotUtils C:\Users\<user_name>\.julia\packages\PlotUtils\GxT73\src\color_gradients.jl:40
```

**Comment by lnacquaroli** [comment]
The warning is just pointing out that the gradient is present in both libraries and by default `Plots` chooses `misc` over `colorcet` http://docs.juliaplots.org/latest/colors/#colorschemes

**Comment by BeastyBlacksmith** [comment]
That is fixed with the new Colorschemes implementation
