### ISSUE TITLE
Asymmetric ribbon is broken

### ISSUE THREAD

**Issue by tbenst** [JuliaPlots/Plots.jl#1849]
Please see: https://gist.github.com/tbenst/576ad23ed67ab695e0e2b4fa8079c944

**Comment by mkborregaard** [comment]
The syntax is `plot(x,y,ribbon=(0.25, 0.5),label="y")`.

**Comment by tbenst** [comment]
Thanks @mkborregaard. Is there a way to use ribbon if the margin does change at each datapoint?

**Comment by mkborregaard** [comment]
you should be able to pass `ribbon = (down, up)` where `down` and `up` are vectors - you just don't need to add them to `y` like you did
