### ISSUE TITLE
Get the plot on the main GUI instead of a different window.

### ISSUE THREAD

**Issue by skanskan** [JuliaPlots/Plots.jl#1852]
Hello.

When I create a plot on VS Code with gr() it pops up a separate window.
I would like to get it on the right side of main GUI like in RStudio instead or even inlined?
I've asked at Julia discourse and @davidanthoff told me 

> Plots.jl apparently is now pushing a display onto the top of the display stack when you load it. That will overwrite the display that VS Code has put there. In my mind that is a bug in Plots.jl, I think it should not push a display onto the top of the stack when it loads, because it breaks things like the VS Code plot pane…
> I think (but am not sure) that we should change the plotting packages so that they don’t put their own display at the top of the display stack, but instead insert it right above the REPL display, in the middle of the stack.

https://discourse.julialang.org/t/plots-different-window-embedded-on-main-gui-or-inlined/17484/4

It would be great if Plots.jl enables the option to solve this situation.

**Comment by mkborregaard** [comment]
@pfitzseb you implemented the current behaviour of plots. What's your take on this?
