### ISSUE TITLE
legendfont does not affect legendtitle

### ISSUE THREAD

**Issue by akazachk** [JuliaPlots/Plots.jl#1856]
Hi all, using the pyplot backend, when I set `legendfont` to some value, it seems to not affect the size of the legend title when one is present. This issue does not arise with the gr backend.

```
using Plots
pyplot()
x = [1,2]
plot(x, legendtitle = "test", legendfont = 3)
```

![legendtitle](https://user-images.githubusercontent.com/4602622/49345470-3cf1d400-f653-11e8-9939-fec3cd5e7747.png)

Also, I guess this may be a separate issue, but is anyone aware whether any other backends (e.g., pgfplots) will support `legendtitle` at some point?

**Comment by Paalon** [comment]
I saw this too when I try to use another font in Plots.jl + pyplot.

```julia
using Plots
pyplot()
f = font(13, "Noto Sans CJK JP")

xs = 1:10
ys = rand(10)
zs = rand(10)

plot(
    xs,
    [ys, zs],
    title = "日本語",
    xlabel = "x軸",
    ylabel = "y軸",
    label = ["テスト y" "テスト z"],
    legendtitle = "テスト",
    titlefont = f,
    tickfont = f,
    guidefont = f,
    legendfont = f
)
savefig("test.png")
```
![test](https://user-images.githubusercontent.com/11065457/55253303-53720a00-5298-11e9-843e-278ac7fbc44d.png)

**Comment by isentropic** [comment]
Try this:
```
plot(x, legendtitle = "It", label="Works! :)",  legendtitlefontsize = 30, legendfontsize=30)
```
![Figure_3](https://user-images.githubusercontent.com/24591123/79865622-6cef7200-8416-11ea-8758-644db3117ef7.png)

@mkborregaard I think it is safe to close this
