### ISSUE TITLE
Scientific formatter fails for very small numbers

### ISSUE THREAD

**Issue by rakhusur** [JuliaPlots/Plots.jl#1858]
```julia
plot(x -> 1e-20*sin(x), ylims = (-1e-20, 1e-20), yformatter = :scientific)
```
produces
![fig](https://user-images.githubusercontent.com/22003125/49375621-260bba00-f705-11e8-86a9-bcf7ca3ddf1c.png)

With an exponent of -10, everything works fine. This happens on all backends and using `yformatter =  string` gives correct results, so the problem seems to be in the scientific formatter.

**Comment by briochemc** [comment]
Maybe this would be solved by https://github.com/JuliaGraphics/Showoff.jl/pull/19?
