### ISSUE TITLE
MethodError: no method matching MethodError(::String)

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Plots.jl#1861]
Looks like recipe appliction is trying to throw `MethodError("msg")` which doesn't exist:

```
MethodError: no method matching MethodError(::String)
Closest candidates are:
  MethodError(::Any, !Matched::Any) at boot.jl:289
  MethodError(::Any, !Matched::Any, !Matched::UInt64) at boot.jl:286
in top-level scope at base/none
in plot at Plots/rmogG/src/plot.jl:51
in #plot#132 at Plots/rmogG/src/plot.jl:57
in _plot! at Plots/rmogG/src/plot.jl:171
in macro expansion at base/logging.jl:307 
in _process_userrecipes at Plots/rmogG/src/pipeline.jl:83
in apply_recipe at RecipesBase/Uz5AO/src/RecipesBase.jl:275
in macro expansion at Plots/rmogG/src/series.jl:253 
in _apply_type_recipe at Plots/rmogG/src/series.jl:197 
in apply_recipe at Plots/rmogG/src/recipes.jl:50
```

The offending line is:

```julia
RecipesBase.apply_recipe(plotattributes::KW, ::Type{T}, plt::AbstractPlot) where {T} = throw(MethodError("Unmatched plot recipe: $T"))
```

Julia 1.0.1
Plots 0.21.0

**Comment by mkborregaard** [comment]
Thanks!

**Comment by mkborregaard** [comment]
Wow, no, one thing is the erroneous error specification, but why is it suddenly thrown all the time?

**Comment by daschw** [comment]
Can you provide an example to reproduce?

**Comment by mkborregaard** [comment]
Well all I know is when I changed MethodError to ArgumentError (the commit I just reverted) it got thrown by 80% of our tests (e.g. number 4).

**Comment by ssfrr** [comment]
This isn't how I was generating it before, but apparently `plot(twinx(), rand(20))` throws this error as well.

**Comment by BioTurboNick** [comment]
I'm got this when I tried to pass through collected `kwars…` from a custom function to `plot()` with a comma instead of a semicolon, fwiw. That is:
```
function foo(; kwargs…)
    plot([1,2,3,4], kwargs…)
end
foo(size = (200,100))
```

In case it helps you track down the source.

**Comment by BioTurboNick** [comment]
What if you did this?

```
RecipesBase.apply_recipe(plotattributes::KW, ::Type{T}, plt::AbstractPlot) where {T} = throw(MethodError(T, "Unmatched plot recipe: $T"))
```
If ArgumentError breaks tests for some reason, this would keep it as a MethodError and it looks like you can pass any arbitrary type to the first argument.

**Comment by mkborregaard** [comment]
Hi @BioTurboNick thanks for the detective work! Do you feel up for the next step - to `]dev` the package locally, change the code as you suggest, and run the tests? If it works it could be your first PR to Plots :-)

**Comment by BioTurboNick** [comment]
Hi @mkborregaard , I'm trying but the tests fail to run at all. "ImageMagick" fails to build because it can't download "https://github.com/SimonDanisch/LibJPEGBuilder/releases/download/v9b/libjpeg.v9.0.0-b.x86_64-w64-mingw32.tar.gz", saying the operation has timed out, and then Gtk fails to precompile, saying it can't load libgobject-2.0.0.

**Comment by BioTurboNick** [comment]
PR #1910 fixes this
