### ISSUE TITLE
secondary y axis title goes in a wrong place

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaPlots/Plots.jl#1863]
```julia
using Plots

plot(rand(10); ylabel="a")
plot!(twinx(), rand(10); ylabel="b")
```

**Comment by BioTurboNick** [comment]
Just came across this looking for how to add a secondary y axis, thought I'd add a picture and clarify that  "wrong place" means it is cut off.

![secondaryaxis](https://user-images.githubusercontent.com/1438610/58924927-aee6cb00-8713-11e9-886e-ed3c46e6c494.png)

**Comment by ssfrr** [comment]
dup of #2205?

**Comment by liupgd** [comment]
If plotly backend is used, the secondary y axis goes to the left. 
Plots.jl version: 1.25.10

![image](https://user-images.githubusercontent.com/3350539/154800667-9d81b09c-93dd-494e-bd1f-7603b7fea1d9.png)

**Comment by BeastyBlacksmith** [comment]
For plotly it is a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2956

**Comment by t-bltg** [comment]
Closed by https://github.com/JuliaPlots/Plots.jl/pull/4488.
