### ISSUE TITLE
Histogram yscale does not start at 0 when using`:log10` 

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaPlots/Plots.jl#1864]
```
using Plots 
using PlotlyJS  
plotly()  # think issue is same with gr()

a = repeat([1], 100)
b = repeat([2], 1_000)
histogram([a; b]; yscale=:log10)
# x-values between 1 and 2 appear to have y-value 5

c = repeat([3], 1_000_000)
histogram([a; b; c]; yscale=:log10)
# y-value appear to start at 500
```
[91a5bcdd] Plots v0.21.0
[f0f68f2c] PlotlyJS v0.12.1
Julia Version 1.0.2, Commit d789231e99
OS: macOS (x86_64-apple-darwin14.5.0)

**Comment by mkborregaard** [comment]
There's something fishy with log scales and histograms

**Comment by t-bltg** [comment]
The `y` value is your number of repeats:
![ddd1](https://user-images.githubusercontent.com/13423344/124646133-90280500-de94-11eb-8012-483e7025f5fc.png)

Is is still an issue ?
