### ISSUE TITLE
Scatter plot fails with 4 points

### ISSUE THREAD

**Issue by nlw0** [JuliaPlots/Plots.jl#1868]
Running the following test code works for 3 and 5, but not with 4 points:

```
using Plots
pyplot()

function myplot(n)
    pts = rand(2,n)
    scatter(pts[1,:], pts[2,:])
end

myplot(3)
myplot(5)
myplot(4)  # fails
 
```   

Result:

> julia> myplot(3)
> 'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
> 
> julia> myplot(5)
> 'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
> 
> julia> myplot(4)
> Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
> ERROR: PyError ($(Expr(:escape, :(ccall(#= /home/user/.julia/packages/PyCall/0jMpb/src/pyfncall.jl:44 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'ValueError'>
> ValueError("'c' argument has 2 elements, which is not acceptable for use with 'x' with size 4, 'y' with size 4.")
>   File "/home/user/.julia/conda/3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1805, in inner
>     return func(ax, *args, **kwargs)
>   File "/home/user/.julia/conda/3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4234, in scatter
>     .format(nc=n_elem, xs=x.size, ys=y.size)

**Comment by mkborregaard** [comment]
Is this on the most current Plots version?

**Comment by nlw0** [comment]
Working on 0.22.0! Sorry.
