### ISSUE TITLE
plot lines with different gradients

### ISSUE THREAD

**Issue by youeh1** [JuliaPlots/Plots.jl#1872]
```julia
curAmps = -1000:100:1000;
totalTime = 400;
curDur = [100,250]./dt;

for curAmp in curAmps
    t,v = resting_membrane_potential(totalTime,curDur,curAmp);
    plot!(t,v,linewidth=1,linecolor = :inferno,levels=curAmp,legend=false)
    
end
```
I would like to draw several lines with a gradient heat map (according to the value of curAmp), but I am not getting there.

May be someone has already asked, but I couldn't find it.
Would you help me to do it?

**Comment by lnacquaroli** [comment]
You might be looking for `line_z` option. See https://github.com/JuliaPlots/Plots.jl/issues/1021 https://github.com/JuliaPlots/Plots.jl/pull/1467

**Comment by youeh1** [comment]
Oh! Thanks.
That's the exact one what I am looking for.
