### ISSUE TITLE
Cannot `plot` one point with `plotlyjs` and `plotly` backends

### ISSUE THREAD

**Issue by getzze** [JuliaPlots/Plots.jl#1887]
Duplicate of part of #1555.
To reproduce:
```julia
using Plots; plotly()  #;plotlyjs()
plot([1], [2])
>>> ERROR: UndefRefError: access to undefined reference
```

There was the same bug using `scatter` (#1503) that was corrected by #1511, but it was not sufficient.
The error comes from function `plotly_series_segments` in https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/plotly.jl, more specifically, in the loop:
```julia
    for (i,rng) in enumerate(segments)
        !isscatter && length(rng) < 2 && continue
```
the segments with size < 2 should not be skipped, this results in an array with `#undef` at this index.

**Comment by getzze** [comment]
removing the line `!isscatter && length(rng) < 2 && continue` solves the problem.

**Comment by snoeyink** [comment]
Also hit this bug.  If all my segments are single points, then I can use seriestype=:scatter and the plot will work, but I'd like single point segments to plot their markershapes, as they do in GR.
