### ISSUE TITLE
New colormaps available!

### ISSUE THREAD

**Issue by kthyng** [JuliaPlots/Plots.jl#1888]
Just a heads up that I've added 4 new colormaps to cmocean that you are welcome to integrate if you're interested. [docs here](https://matplotlib.org/cmocean/)

**Comment by mkborregaard** [comment]
Great, thanks a lot!

**Comment by mkborregaard** [comment]
Closed in https://github.com/JuliaPlots/PlotUtils.jl/commit/431f961e5809e65f36017035462eff65f9f6bbfb
