### ISSUE TITLE
Unsatisfiable requirement

### ISSUE THREAD

**Issue by rna1990** [JuliaPlots/Plots.jl#1897]
Greetings,

I'm new to Julia and wanted to install Plots.jl for the first time, however I keep getting an error message:

![imagen](https://user-images.githubusercontent.com/42617282/51433931-15af9000-1c1c-11e9-8966-7b57490c4efa.png)
 It's about version compatibility of the Cbc library. What could I do to install Plots?

Thank you for your help

**Comment by mkborregaard** [comment]
I don't think this has anything to do with Plots, it's more likely your package manager acting up. Try `rm Cbc`, then manually delete the `.julia/packages/Cbc` folder, then running `resolve`

**Comment by rna1990** [comment]
thank you very much for your help. Sorry for the late reply. Cheers.
