### ISSUE TITLE
use equal aspect ratio by default for images?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaPlots/Plots.jl#1898]
Normally the default aspect ratio behavior is fine, but specifically for `plot(image)` the image gets distorted and doesn't look good, and an equal ratio would make more sense. If there's other stuff in the plot, or an image is added to an existing plot, then it doesn't matter so much. But ideally I think we'd set `aspect_ratio=1` if the plot is created from just an image. Thoughts?

This was mentioned briefly here: https://github.com/JuliaPlots/Plots.jl/issues/1238#issuecomment-348755330

**Comment by mkborregaard** [comment]
I agree

**Comment by JeffBezanson** [comment]
See #952 --- there are many cases (e.g. long series) where `:equal` aspect ratio is really bad. It's a really, really different matter to change the default everywhere than just for images.

**Comment by mkborregaard** [comment]
Yes @juliohm we're not going to make aspect ratio equal by default, there's no general underlying assumption in plotting that the scale of the axes should be the same. It's true that sometimes aspecratio = 1 is the correct representation, but that's best left to the user.
But, I agree we should solve the whitespace issue. It might be easiest to track if you open a new issue.

**Comment by juliohm** [comment]
Thank you all, I take back the idea of `aspect_ratio=:equal` by default for all plot types. I agree it is a good idea to leave it the way it is now.

@mkborregaard I will open another issue regarding the white space :+1:
