### ISSUE TITLE
Erroneous white space in plot layouts when aspect_ratio=:equal

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#1902]
There are many issues regarding `aspect_ratio=:equal`. For example, when we have a layout plot in PyPlot, this is how it looks like:

```julia
pyplot(size=(1000,600))
imgs = [rand(10,10) for i in 1:3]
plot(heatmap.(imgs, aspect_ratio=:equal)..., layout=(1,3))
```
![screenshot from 2019-01-23 21-18-49](https://user-images.githubusercontent.com/3345261/51643773-e74fee80-1f54-11e9-96f5-2d0ff91a14d9.png)

If I try with GR, the colorbar is ok, but there is still a lot of undesired white space:

```julia
gr(size=(1000,600))
imgs = [rand(10,10) for i in 1:3]
plot(heatmap.(imgs, aspect_ratio=:equal)..., layout=(1,3))
```
![screenshot from 2019-01-23 21-20-17](https://user-images.githubusercontent.com/3345261/51643828-1a927d80-1f55-11e9-8474-1869102235fb.png)

Appreciate if you can take a look at this.

_Originally posted by @juliohm in https://github.com/JuliaPlots/Plots.jl/issues/1898#issuecomment-457006133_

**Comment by daschw** [comment]
Isn't this behaviour expected, @juliohm , if you specify the size?

**Comment by juliohm** [comment]
Good question @daschw , I didn't thought about it that way. Makes sense. Should I close the issue?

**Comment by juliohm** [comment]
I was thinking about this issue again today, and was wondering if we could have a `scale` parameter or something that would scale the figure without adding this unnecessary amount of white space? It would be really helpful to have:

```julia
plot(foo, aspect_ratio=:equal, scale=2)
```

where the aspect ratio is preserved in each subfigure, but the whole figure is scaled by a factor of 2.

**Comment by juliohm** [comment]
I think dpi is what I'm looking for then. I'll give it a try and see if the
result looks less filled with whitespace.

**Comment by mkborregaard** [comment]
how do you mean?

**Comment by juliohm** [comment]
I don't know how to use the option `dpi` basically. Given the minimum working example in the beginning of the post, how would you use dpi to increase the figure size without increasing the white space in the borders?
