### ISSUE TITLE
Margin doesn't work in pgfplots?

### ISSUE THREAD

**Issue by irhooper** [JuliaPlots/Plots.jl#1906]
Unless I'm mistaken, changing the margin (or bottom_margin) attribute when using the pgfplots backend doesn't appear to alter anything when I have multiple subplots in a layout? At the moment my grid of plots overlap each other when I have titles on each sub-plot. Any idea how I might fix this? (Other than using a different backend as this isn't really an option because I need the pgfplots style).

Thanks.

**Comment by giadasp** [comment]
I also noticed this issue, even in the examples it seems that also the xrotation doesn't work together with the margins.

**Comment by BeastyBlacksmith** [comment]
that is fixed in the pgfplotsx backend.
