### ISSUE TITLE
Errorbars are not rotated in horizontal bar plot

### ISSUE THREAD

**Issue by johannes-fischer** [JuliaPlots/Plots.jl#1907]
I wanted to attach error bars to a horizontal bar plot, however they seem to be anchored to where the bars would end if the orientation was vertical. Example:
`bar(rand(3), fill=:orange, orientation=:h, xerror=fill(.2,3), xlims=(0,4),ylims=(0,4))`
I've tried GR, PyPlot and Plotly backends.

**Comment by bvolkmer** [comment]
As an addition: If the error type is not compatible with the data type of the other axis, it will fail.

For example: xdata::String and yerror::Float32 will result in:
- Pyplot and plotlyjs will plot no error bars without warning
- gr will fail with `MethodError: no method matching isfinite(::String)`
