### ISSUE TITLE
GR: camera angles outside [0,90] do not work

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#1911]
Camera angles outside of the range 0..90 are not plotted correctly.
If it's the first plot, the z axis scaling is wrong:
```
using Plots
wireframe( 0:10, 0:10, (x,y)->x*y, camera=(130,20) )
```
![image](https://user-images.githubusercontent.com/4170948/52184253-81e3e380-2819-11e9-905d-2fe49c5b2f8e.png)

If it's not the first plot, the last used camera angle is repeated:
```
plts = [wireframe( 0:10, 0:10, (x,y)->x*y, camera=(x,20), title="angle=$x" ) 
        for x in [30,120,60,120,30,-30]]
plot(plts...)
```
![image](https://user-images.githubusercontent.com/4170948/52184262-b2c41880-2819-11e9-8623-5abd2da2c53b.png)

The problem also occurs with the vertical angle, though I suppose angles outside of 0..90 are less useful there.

**Comment by mkborregaard** [comment]
Thanks for reporting! I had noticed this before but embarassingly it seems as if I didn't open an issue. This also means that the "simple is beautiful" gif on the front page of Plots' docs doesn't work with GR!

**Comment by aramirezreyes** [comment]
I think this still happens

**Comment by RodolfoFigueroa** [comment]
Can confirm it still happens.

**Comment by BoundaryValueProblems** [comment]
Yes, this problem has not been resolved. On the other hand, it works under the pyplot backend.
