### ISSUE TITLE
plotlyjs: custom tick labels do not work when supplied as a tuple

### ISSUE THREAD

**Issue by harryscholes** [JuliaPlots/Plots.jl#1918]
```julia
using Plots; plotlyjs()
plot(rand(10), xticks=((1, 10), ("A", "B"))) # works with gr
plot(rand(10), xticks=([1, 10], ["A", "B"])) # works with gr and plotly
```

I believe this comes down to how `AVec` and `TickArgs` are defined:

https://github.com/JuliaPlots/Plots.jl/blob/f2e98acc65c417fce2b8338a3300c9a790f40008/src/types.jl#L5-L8

Two possible fixes:

* Define `AVec` as:
```julia
const AVec{T} = Union{AbstractVector{T}, NTuple{N,T}} where N
```

* Or make 

https://github.com/JuliaPlots/Plots.jl/blob/f905cb957721be871d3fa9c86eea2bdbaefd69a3/src/utils.jl#L434

more flexible, e.g.

```julia
ticksType(ticks::Tuple{T,S}) where {T<:Union{AVec,Tuple},S<:Union{AVec,Tuple}}  = :ticks_and_labels
```

🎉 Both of these now work:

```julia
plot(rand(10), xticks=((1, 10), ("A", "B")))
plot(rand(10), xticks=([1, 10], ("A", "B")))
```

I'm leaning more towards the `AVec` solution, but would be keen to hear what others think. Cheers

**Comment by harryscholes** [comment]
Ticks get added in plotlyjs here:

https://github.com/JuliaPlots/Plots.jl/blob/f905cb957721be871d3fa9c86eea2bdbaefd69a3/src/backends/plotly.jl#L194-L205

**Comment by harryscholes** [comment]
@mkborregaard this follows on from our chat on the plots Slack channel

**Comment by mkborregaard** [comment]
Nice detective work! I'm in favour of the second solution, as it's much less intrusive and more explicit.
