### ISSUE TITLE
GR: filled contours with NaN

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#1920]
```julia
r = -1:0.1:1
ff(x) = x/(1-x)
contour( r, r, (x,y) -> y*ff(x)/ff(x), fill=true )
```
![filled-contour-nan](https://user-images.githubusercontent.com/4170948/52927474-657c9680-3343-11e9-9a6a-f9fe162ad2c4.png)

pyplot backend gets this right:
![contour-nan-pyplot](https://user-images.githubusercontent.com/4170948/52927503-8e049080-3343-11e9-93e4-cbe3b77e8e8c.png)

**Comment by daschw** [comment]
@jheinen can `GR.contour` handle `NaN`s?

**Comment by daschw** [comment]
It seems like there has been an improvement on this issue. It's still not perfect:
![gr_contour](https://user-images.githubusercontent.com/16589944/59556420-876ce980-8fc2-11e9-9aac-7b84c4774e51.png)
