### ISSUE TITLE
subscript with "_" or "^" no longer works in PyPlot

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaPlots/Plots.jl#1929]
Please help me. I'm trying to add a title to a plot using pyplot(). But it has subscripts. The problem is that using Latex generate poor quality fonts. I need a font like Times New Roman so, I decided to use normal string as title="title with subscript".

**Comment by lnacquaroli** [comment]
You can define the font in the matplotlibrc file and pyplot() should take care of it.

**Comment by isentropic** [comment]
Please provide Minimal workign example (MWE) of what you want to achieve.
Pyplot usually behaves good with fonts
