### ISSUE TITLE
pyplot/pycall API updates

### ISSUE THREAD

**Issue by stevengj** [JuliaPlots/Plots.jl#1932]
PyCall 1.90.0 and PyPlot 2.8.0 are now released, which change `o[:foo]` and `o["foo"]` to `o.foo` and `o."foo"`, respectively, for python objects `o`.

The old `getindex` methods still work but are deprecated, so you'll want to put out a new Plots.jl release that uses the new methods and REQUIREs the new versions to avoid having zillions of deprecation messages.

**Comment by mkborregaard** [comment]
Thanks. Yeah, the disadvantage with Plots' conditional package loading is that we can't depend on different versions of the backend packages. So, we'll tag a Plots 0.24.0 with the change, and everyone will just have to update to the newest PyCall and PyPlot versions to use the backend.

**Comment by stevengj** [comment]
You can check for e.g. `isdefined(PyCall, :_setproperty!)` if you want to check explicitly whether the user has a PyCall with JuliaPy/PyCall.jl#517.

**Comment by mkborregaard** [comment]
Ah, that's nice!
I'm not 100% certain this is needed though - I added #1933 for this, but there was only a single place to fix, and `pyplot(); scatter(1:10)` works without deprecation warnings on 
PyCall 1.90.0 and PyPlot 2.8.0 .

**Comment by mkborregaard** [comment]
I'll merge #1933 since it appears harmless. Thanks!

**Comment by stevengj** [comment]
#1933 doesn't close this.  You still have lots of other deprecated usages like `pycolors["LinearSegmentedColormap"][:from_list]` and `pypath["Path"]`.

`o["foo"]` should be replaced with `o."foo"`.

**Comment by mkborregaard** [comment]
Oh :-O on it

**Comment by daschw** [comment]
@stevengj Is there a way to still do something like
```julia
letter = axis[:letter]
lfrom, lto = axis_limits(axis)
ax[Symbol("set_", letter, "lim")](lfrom, lto)
```
with the new API?

**Comment by diegozea** [comment]
I think you can call `getproperty` explicitly in those cases: `getproperty(ax, Symbol("set_", letter, "lim"))`

**Comment by daschw** [comment]
Thanks a lot @diegozea !

**Comment by stevengj** [comment]
Note also that in many of these cases you might want to switch from `a.foo` to `a."foo"` — if you know you want a `PyObject` result, it is faster if you skip the automatic conversion.

**Comment by daschw** [comment]
Thanks!
