### ISSUE TITLE
Julia : ERROR: KeyError: key "set_facecolor" not found

### ISSUE THREAD

**Issue by iamsuddhasattwa** [JuliaPlots/Plots.jl#1935]
I am having trouble running the most basic plotting commands in Julia. I would really appreciate some help on this.

julia> using Plots

julia> x=rand(100);

julia> plot(x)
WARNING: No strict ticks found
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: KeyError: key "set_facecolor" not found

**Comment by mkborregaard** [comment]
What's your versions of Julia, Plots, PyPlots and matplotlib?

**Comment by iamsuddhasattwa** [comment]
Plots 0.11.4
PyPlot 2.3.2
Julia : v"0.5.1-pre+31"

I do not have matplotlib installed.
