### ISSUE TITLE
Change color to a sphere

### ISSUE THREAD

**Issue by astrorCoder** [JuliaPlots/Plots.jl#1946]
Can anyone tell me how is it that you change the color or palette in a surface with Plots.jl? I think I have tried everything in the documentation and it is probably very easy to do, but nothing seems to affect the result of the plot:

`using Plots

n   = 32
pos = 10
rad = 15

plotlyjs()
u = collect(range(0,stop=2,length=n));
v = collect(range(0,stop=1,length=n));
x = pos * ones(n) * ones(n)' + rad * cospi.(u) * sinpi.(v)';
y = rad * sinpi.(u) * sinpi.(v)';
z = rad * repeat(cospi.(v)',outer=[n, 1])
surface(x,y,z, palette=:blues)`

It doesn't matter what arguments I use, this is the output:
![image](https://user-images.githubusercontent.com/38725172/54023805-34e78a00-4196-11e9-8883-7d88525c9edc.png)

Any clue?

Thanks in advance and sorry for the dumb question, I have been using Julia for a couple of weeks now and everything is more difficult for me than it probably should.

**Comment by mkborregaard** [comment]
Have you tried `color = :blues`? (`:Blues` may be nicer but that's beside the point).
`palette` is for the automatic color change of different series.

**Comment by astrorCoder** [comment]
> Have you tried `color = :blues`? (`:Blues` may be nicer but that's beside the point).
> `palette` is for the automatic color change of different series.

**It worked**! The thing is I had tried using 'colors=:red' and things like that with no effect and no errors, but I didn't try using the special arguments in https://docs.juliaplots.org/latest/colors/#colorschemes 
Thanks a lot mkborregaard :+1:
