### ISSUE TITLE
Warnings when using pyplot() backend

### ISSUE THREAD

**Issue by BerntLie** [JuliaPlots/Plots.jl#1954]
I get some warnings when using `pyplot()` as backend for `Plots` in `IJulia` on my laptop:

![image](https://user-images.githubusercontent.com/28146074/54284978-520ac700-45a1-11e9-976f-2d62420c5ce3.png)

**Comment by isaacsas** [comment]
To workaround for now: in the package manager
```
add PyCall@v1.18.5 PyPlot@v2.7.0
pin PyCall PyPlot
```
At least for me that reverted them to a version before the change in API which is causing the warnings.

**Comment by stevengj** [comment]
Duplicate of #1932
