### ISSUE TITLE
Layout bug using PlotlyJS backend

### ISSUE THREAD

**Issue by ferrolho** [JuliaPlots/Plots.jl#1957]
I think there's a bug with the `PlotlyJS` backend when using a layout. Doing this:
```julia
# create a 4x1 grid, and map each of the 4 series to one of the subplots
plot(rand(100, 4), layout = (4, 1))
```
...results in this:
![img](https://i.imgur.com/uXTTjzV.png)

**Comment by daschw** [comment]
dup of #1869
