### ISSUE TITLE
Documentation is unclear on image plotting. 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/Plots.jl#1960]
Per this link: [here](https://github.com/JuliaPlots/Plots.jl/pull/1951)  It is shown we can now plot on images again, but there is no specific reference anywhere where I can see as to what the following components are :  `plot([-π, π], [-1, 1], img[end: -1:1 , : ], yflip = false)`

Since there are no keyword args here, it is hard to see what each part is doing.  Specifically, in regards to what is occurring with `img[end: -1:1 , : ]`...  

What is occurring here? @daschw @mkborregaard I would appreciate the clarification and then I will write it up for the docs and open a pull request.

**Comment by logankilpatrick** [comment]
Also as a quick follow up: this update really is needed. Per the Plots.jl docs, you should be able to specify the xlims and ylims, but if you explicitly reference those as arguments, even with the sample plot at the given address above, it no longer works. Please provide reference as to what the arguments are and what they do.

**Comment by mkborregaard** [comment]
If you read the documentation you will see that all Plots calls has the same signature: 
```
plot([xvalues, ] yvalues [, zvalues] ; attributes...)
```
xvalue, yvalus and zvalues can be any type that has a recipe defined. A full list of attributes (keywords) is included in the documentation.

I'm really not sure what else you expect. If you find an update is "really needed" you can expedit the process by making a PR.
