### ISSUE TITLE
A Plots.jl reference sheet

### ISSUE THREAD

**Issue by sswatson** [JuliaPlots/Plots.jl#1961]
Here's a Plots.jl [cheatsheet](https://github.com/sswatson/cheatsheets/blob/master/plotsjl-cheatsheet.pdf) that shows examples of many of the `seriestype`s, among other things. I'm not sure whether it's worth putting somewhere visible (or, if so, where a good place would be), but I thought I'd share since I've seen several requests for this kind of resource.

**Comment by daschw** [comment]
That's amazing! We could link to it from the Plots.jl README or include it in the docs.

**Comment by mkborregaard** [comment]
I agree, this is really useful and well done.

**Comment by daschw** [comment]
Done in https://github.com/JuliaPlots/PlotDocs.jl/pull/135
