### ISSUE TITLE
I met this error when run this code

### ISSUE THREAD

**Issue by bemoregt** [JuliaPlots/Plots.jl#1967]
Hi, @massemanet @tkf @staticfloat @mortenpi @dpsanders 

I met this error when run this code:
julia> heatmap(log(real(F).+1))

In here, F is a 2d Complex number array, real(F) is a 2d float64 array
I want to plot the logarithm of 2d  image elements.

error is here.

ERROR: MethodError: no method matching heatmap_edges(::Surface{Array{Float64,2}}, ::Symbol)
Closest candidates are:
  heatmap_edges(::AbstractArray{T,1} where T, ::Symbol) at /Users/mun/.julia/packages/Plots/QYETN/src/utils.jl:369
 
What's wrong to me?

Thanks in advance.

**Comment by daschw** [comment]
You are trying to plot a complex matrix with heatmap:
```julia
julia> log(rand(10, 10).+1)
10×10 Array{Complex{Float64},2}:
 -0.0670841+0.554248im      0.811855+0.104371im   -0.279504+0.0439367im  …     0.584087-0.457585im     0.821828+0.297474im     0.322058-0.562051im
  -0.351183+0.769124im      -1.23509+0.314267im     2.11439-0.635091im         0.457724-0.573699im     0.350029-0.036193im    -0.161254-0.247742im
    1.03357+0.561539im    -0.0333547-0.234461im   -0.318828+0.589022im      -0.00822105-0.433367im     0.286603+0.674684im      0.14318-0.925719im
   0.624089-0.383929im        1.2089-0.564994im   -0.821714+1.31478im         -0.165537+0.812031im    0.0862998+0.210556im     0.710475-0.96638im
   0.520788+0.0214781im      -1.0324+0.728915im    0.365776-1.28362im          0.548579+0.189005im      0.59224-1.10513im      0.436636+0.682558im
   0.419777-0.962046im       1.08811-0.501232im    0.298375+0.342953im   …     0.322602+0.615574im     0.126053-0.00487684im   0.285717+0.861958im
   0.416437+0.539266im      0.657466+0.661569im   0.0302676-0.474594im         0.200946-0.096673im  -0.00755331-0.501703im     0.712449-0.589554im
   0.342217-1.08899im        0.63562+0.211063im   -0.067123-0.0624329im       -0.382445+1.77447im      0.198836-1.51113im      0.440265+0.264083im
 -0.0511304+0.00740536im    0.263084-0.738235im    0.666646+0.778144im         0.106892-0.807236im    -0.299144+1.38101im      0.583491+0.190878im
  0.0835619-0.164603im      0.397953+0.0856151im    0.66932-0.590589im         0.708421-0.684226im     0.499588+0.303228im    -0.174859+1.20986im
```
How should complex values be interpreted on a colorscale?
Or maybe you want
```julia
heatmap(log.(real(F).+1))
```
(notice the `.` after `log`)?

**Comment by bemoregt** [comment]
Hi, @daschw 

I fixed it. but not simple ...

using Images, Plots, TestImages, FFTW
methods(TestImages)
aa= testimage("lighthouse")
F= fftshift(fft(Float64.(Gray.(aa))))
heatmap(log.(abs.(F.*F)).+1)

[https://www.facebook.com/photo.php?fbid=2371160543160832&set=gm.595027397642427&type=3&eid=ARCrspEa7dZxrdCX7n6UaEBjRUv3741aKw1aH00AIRoe1nDHjq1333R9KJNWDiLxsE41b98mndyAqq6p&ifg=1](url)

**Comment by diegozea** [comment]
Hi! I see the same problem when trying to use a matrix of categorical variables (strings). It used to work...
