### ISSUE TITLE
How to show Last Value for a Line graph?

### ISSUE THREAD

**Issue by evveric** [JuliaPlots/Plots.jl#1979]
![image](https://user-images.githubusercontent.com/48576985/55460594-ed351080-5624-11e9-9f8e-5c7f4e67c69c.png)

for example like above plot (from Excel), how to make it show the last value of each line?
Thank you

**Comment by mkborregaard** [comment]
You'd use an `annotation`: https://docs.juliaplots.org/latest/examples/gr/#annotations
There isn't an automatic setting.
