### ISSUE TITLE
How to show Y axis on the Right side?

### ISSUE THREAD

**Issue by evveric** [JuliaPlots/Plots.jl#1980]
![image](https://user-images.githubusercontent.com/48576985/55460904-b7dcf280-5625-11e9-89ef-29efca43a94d.png)

like above example. I could not find how to do it from the document / examples. thank you

**Comment by mkborregaard** [comment]
`plot(1:10, ymirror = true)`, see https://docs.juliaplots.org/latest/attributes/ for info on the available attributes.
Short questions like that are better asked at our gitter channel or on the plots-bridged channel of the julia slack.
