### ISSUE TITLE
annotate :color not working

### ISSUE THREAD

**Issue by lazarusA** [JuliaPlots/Plots.jl#1983]
Hi, 
in Julia 1.0.3, using Plots and the gr() backend. The following is not given the color that I want. 

`annotate!(1, 1, latexstring("\\eta_{2}"), :blue)`

any ideas?

**Comment by diegozea** [comment]
If the output colours are black or white, maybe this problem is related to https://github.com/JuliaPlots/Plots.jl/issues/1853

I can not reproduce the problem with Julia 1.1.0, Plots 0.24.0, GR 0.39.1 and LaTeXStrings 1.0.3

Which package versions are you using?

**Comment by daschw** [comment]
dup of #1853
