### ISSUE TITLE
`:line` seriestype does not sort attribute vectors

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1989]
The `:line` seriestype sorts the input data so that `x` is in descending order prior to plotting. However, this does not affect the input arguments.
```julia
using Random, Plots
yold = cumsum(randn(100))
sortind = shuffle(1:100)
x, y = (1:100)[sortind], yold[sortind]
plot(x, y, st = :line, fill = 0, fill_z = y)
```
![Skærmbillede 2019-04-09 kl  10 09 47](https://user-images.githubusercontent.com/8429802/55783856-a7a69680-5aaf-11e9-8b23-6d7c56907ff8.png)

**Comment by daschw** [comment]
```julia
using Random, Plots
x = shuffle(1:10)
y = 1:10
```
Am I understanding the issue correctly that
```julia
plot(x, y, st = :line, fill = 0, fill_z = x)
```
![fill_x](https://user-images.githubusercontent.com/16589944/55787154-f35c3e80-5ab5-11e9-9e8b-379a1010fab6.png)
should have sorted fill colors, while
```julia
plot(x, y, st = :line, fill = 0, fill_z = x)
```
![fill_y](https://user-images.githubusercontent.com/16589944/55787155-f6572f00-5ab5-11e9-82db-93091ba8d66d.png)
should not?

**Comment by mkborregaard** [comment]
sorry I can't see how those lines of code are different :-)

**Comment by daschw** [comment]
With
```
plot(x, y, st = :line, fill = 0, fill_z = y)
```
in your code above, `fill_z = y` in particular, I would expect not to have sorted fill colors. :-)
I just wanted to make sure if I understood correctly.
Anyway, nice catch!

**Comment by daschw** [comment]
Ah, now I get it, I meant
```
plot(x, y, st = :line, fill = 0, fill_z = y)
```
in my second line. Edited

**Comment by mkborregaard** [comment]
Yes, because when you pass in a Vector for things like `fill_z` one value corresponds to the same value in the x and y vector - but once input data gets sorted that correspondence will get lost if not the attribute Vector is sorted too
