### ISSUE TITLE
Unusual character printed when scientific notation used

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaPlots/Plots.jl#1991]
```
scatter(x, y, xaxis=((1000,15000), (1000:7000:15000)))
```

(Using GR), the last scientific notation exponent is replaced by an `â` character.
![labelerror](https://user-images.githubusercontent.com/1438610/55814566-d2e3b280-5abc-11e9-9867-380478225af4.png)

**Comment by asinghvi17** [comment]
Is that supposed to be 10^4?  Maybe GR doesn't support that specific character?

**Comment by BioTurboNick** [comment]
Yes, it is supposed to be a superscript 4.

**Comment by asinghvi17** [comment]
I think this is a symptom of GR generally not having good support for Unicode characters...

**Comment by BioTurboNick** [comment]
This seems to be fixed
