### ISSUE TITLE
Access Ranges from Type Recipe for Periodic Step Function

### ISSUE THREAD

**Issue by pyramids** [JuliaPlots/Plots.jl#1992]
I'm making a type recipe for plotting a custom type representing a periodic step function that (perhaps naturally) isn't handled well by the adaptive function evaluation.

The problem is that I don't know when to stop outputting :path data for this periodic function.

The [documentation](https://docs.juliaplots.org/latest/recipes/#recipe-syntaxrules) explains how to set undefined plot attributes, or how to overwrite possibly defined one, using the `-->` and `:=` syntax. But how to I simply read attributes such as `xlims`? And what is the recommended way to know how far out (i.e. over what range) to include data to be plotted from a type recipe?

**Comment by mkborregaard** [comment]
You can't access xlims in the type recipe unfortunately. I think you'll have to estimate it beforehand. It's a bit hard to give advice on how given the question.
