### ISSUE TITLE
`markersize` has no effect without `marker=:something`

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Plots.jl#1994]
I just tried to add markers to a line plot with:

```julia
using Plots
plot(rand(10), marker=true, markersize=50)
```

Which displays tiny dots for markers. Setting `marker=:circle` instead displayed the markers (thought the color didn't match).

I'm not sure where I got the idea to use `marker=true`, I think I just tried it and it seemed to do something so I assumed it was right. Maybe either have `true` mean a default marker, or have it display a warning?

**Comment by daschw** [comment]
Thanks, fixed in #1995

**Comment by ssfrr** [comment]
awesome, thanks a lot!
