### ISSUE TITLE
MethodError: no method matching _show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PlotlyBackend})

### ISSUE THREAD

**Issue by EldarAgalarov** [JuliaPlots/Plots.jl#2000]
julia> savefig(plot(rand(5)), "test.png")
ERROR: MethodError: no method matching _show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PlotlyBackend})
Closest candidates are:
  _show(::IO, !Matched::MIME{Symbol("text/html")}, ::Plots.Plot) at /home/eldar/.julia/packages/Plots/47Tik/src/output.jl:163
  _show(::IO, !Matched::MIME{Symbol("text/plain")}, ::Plots.Plot) at /home/eldar/.julia/packages/Plots/47Tik/src/output.jl:204
  _show(::IO, !Matched::MIME{Symbol("application/vnd.plotly.v1+json")}, ::Plots.Plot{Plots.PlotlyBackend}) at /home/eldar/.julia/packages/Plots/47Tik/src/backends/plotly.jl:857
  ...
Stacktrace:
 [1] show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PlotlyBackend}) at /home/eldar/.julia/packages/Plots/47Tik/src/output.jl:198
 [2] png(::Plots.Plot{Plots.PlotlyBackend}, ::String) at /home/eldar/.julia/packages/Plots/47Tik/src/output.jl:8
 [3] savefig(::Plots.Plot{Plots.PlotlyBackend}, ::String) at /home/eldar/.julia/packages/Plots/47Tik/src/output.jl:121
 [4] top-level scope at none:0

Julia ver 1.1.0
Plots ver 0.24.0
OS: Ubuntu 19.04

**Comment by daschw** [comment]
You cannot save as png with the plotly backend. Try PlotlyJS, GR, PyPlot or PGFPlots.

**Comment by haotian127** [comment]
> You cannot save as png with the plotly backend. Try PlotlyJS, GR, PyPlot or PGFPlots.

Hi Daniel, the best backends for 3D plotting are ```plotly()``` and ```plotlyjs()```, and since PlotlyJS does not work on Juno/Atom now, is it possible to make ```plotly()``` savefig feasible? Could we reopen this issue? Thanks a lot!

**Comment by daschw** [comment]
PlotlyJS works for me in Juno (just not interactively). What error do you get?

**Comment by haotian127** [comment]
Yes, not interactively and the image looks very blurry for my case.

**Comment by daschw** [comment]
What you see in Juno is the saved png from PlotlyJS (I guess).
If you want, we can re-open, but I don't see png saving for plotly happening anytime soon.

**Comment by haotian127** [comment]
I see. I use ```plotly()``` backend a lot for my research. Please re-open this issue. Thank you very much, Daniel!

**Comment by daschw** [comment]
Fixed in https://github.com/JuliaPlots/Plots.jl/pull/2292
