### ISSUE TITLE
heatmap!() does not work in Plots.jl with gr() backend

### ISSUE THREAD

**Issue by haotian127** [JuliaPlots/Plots.jl#2004]
heatmap!() used to work, so I can add another small heatmap plot on the current plot. Now heatmap!() will erase the previous heatmap plot. Does anyone have the same issue or know the solution of it? Thanks a lot!

```
Plots v0.24.0
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2
```

**Comment by daschw** [comment]
@yha may this be related to #1919?

**Comment by yha** [comment]
I can reproduce this on v0.23.0 and v0.20.0, which are earlier than #1919.

**Comment by daschw** [comment]
OK, sorry for the noise then, and thanks a lot for checking!

**Comment by t-bltg** [comment]
Needs a mwe.
