### ISSUE TITLE
LaTeXStrings doesn't work with gr() backend

### ISSUE THREAD

**Issue by damonturney** [JuliaPlots/Plots.jl#2005]
Mac OS 10.14.2 Mojave with Julia running via Atom Juno, and I've installed MacTeX with dvipng included, so dvipng is installed on my Mac system, and I'm still getting this error:

using Plots
using LaTeXStrings
gr()
plot(1,ylabel=L"")
'sh: latex: command not found
latex: failed to create a dvi file'

and also this fails too

using GR
mathtex(0.5,0.5,"")
'sh: latex: command not found
latex: failed to create a dvi file'

NOTE: I've already done:
Pkg.update("GR")
ENV["GRDIR"]=""
Pkg.build("GR")
but it doesn't help.

latex strings work fine with the pyplot() backend, but I can't use pyplot because it places data markers non-center on the data line, which looks horrible. GR makes much more beautiful plots.

What's this error from?

**Comment by daschw** [comment]
I can't reproduce this issue on windows. I suppose you need a working LaTeX installation for this to work.
```
'sh: latex: command not found
```
looks like your system fails to run LaTeX.

**Comment by damonturney** [comment]
Thanks, yes, you're right, the problem was that I hadn't re-started Atom after install of LaTeX and dvipng.  After I restarted Atom, the code worked.

**Comment by diegozea** [comment]
I got a similar error:
```
sh: 1: dvipng: not found
dvipng: PNG conversion failed
```
when trying to do a LaTeX annotation:
```
annotate!(1.25, 1.25, latexstring("\\eta_{2}"), :red)
```
I solved by installing *dvipng* in *Ubuntu*:
```
sudo apt install dvipng
```

**Comment by Freed-Wu** [comment]
i also met the similar problem.
```
histogram( # noise pdf
	label = [L"\mathscr{R}(n)" L"\mathscr{I}(n)"],
	[
		real(noise(0:t₀:T)),
		imag(noise(0:t₀:T))
	]
)
qt.qpa.xcb: QXcbConnection: XCB error: 146 (Unknown), sequence: 201, resource id: 0,
 major code: 139 (Unknown), minor code: 20
latex: failed to create a dvi file
latex: failed to create a dvi file
```

i have installed texlive and dvipng. it still remain this error.

but
```
histogram( # noise pdf
	label = [L"\mathrm{Re}(n)" L"\mathrm{Im}(n)"],
	[
		real(noise(0:t₀:T)),
		imag(noise(0:t₀:T))
	]
)
```
can output the correct figure.

i don't know why, and i like the first lable more.

**Comment by mahdiarsadeghi** [comment]
I do have a same problem. It is interesting when I use `"\\beta_s"` it works fine but it doesn't work with `"b_s"`. Not sure how to have subscript for non greek letters. This is the error I get when I use `L"x"`:

> sh: latex: command not found
> latex: failed to create a dvi file
