### ISSUE TITLE
Remove icons from legend, i.e. leave legend with text only.

### ISSUE THREAD

**Issue by NaelsonDouglas** [JuliaPlots/Plots.jl#2008]
Im making some plots using those commands below and it results in the plot attached.

I would like to remove the little boxes from the legends and leave it only with pure text.
"1 maxmim"
"2 clustering" and so on, but without the boxes on the left side of each line.

Is there a way to do it?
(I know it's suposed to be colourful, but this plot is going to be paper-printed in black and white.

Thanks in advance.

```julia
outl = true
plots = 0

boxplot(maxmim,label=string(plots+=1)*" maxmim",title="16 nodes",outliers=outl,legend=:topleft,color=:white,ylabel="Seconds")
boxplot!(clustering,label=string(plots+=1)*" clustering",outliers=outl,color=:white)
boxplot!(create_histogram,label=string(plots+=1)*" create_histogram",outliers=outl,color=:white)
boxplot!(testing_model,label=string(plots+=1)*" testing_model",outliers=outl,color=:white)
boxplot!(train_global_model,label=string(plots+=1)*" train_global_model",outliers=outl,color=:white)
boxplot!(local_training,label=string(plots+=1)*" local_training",outliers=outl,color=:white)
boxplot!(elapsed_time,label=string(plots+=1)*" elapsed_time",outliers=outl,color=:white)
```

![8a](https://user-images.githubusercontent.com/8750259/56690441-d3cb3580-66b3-11e9-9165-e842bf7b4d94.png)

**Comment by daschw** [comment]
You could either do something like
```julia
boxplot(randn(10), label = "", c = :white)
boxplot!(randn(100), label = "", c = :white)
boxplot!(randn(1000), label = "", c = :white)
plot!(zeros(0, 3), label = ["1 my first label" "2 my second label" "3 my third label"], c = :white)
```
or have the labels on the axis
```julia
boxplot(["my first label"], randn(10), label = "", c = :white)
boxplot!(["my second label"], randn(100), label = "", c = :white)
boxplot!(["my third label"], randn(1000), label = "", c = :white)
```

For usage questions like this I suggest asking on the [Plots Gitter channel](https://gitter.im/tbreloff/Plots.jl) or on the "Plotting" channel at http://julialang.slack.com, rather than opening an issue.
