### ISSUE TITLE
Negative radius with polar coordinates

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaPlots/Plots.jl#2009]
Negative radii are silently dropped, but the corresponding angle entries are not:

```
julia> plot(rand(200), rand(200) .- 0.5, proj=:polar)
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: BoundsError: attempt to access 105-element Array{Float64,1} at index [1:200]
```

this is with:

```
  [28b8d3ca] GR v0.39.1
  [91a5bcdd] Plots v0.24.0
```

Previously negative radii were handled just fine (e.g., the points were plotted as if the angle was 180° and the radius was positive).  The change happened at some time in the last year I think (this worked fine when I wrote the code ~1 year ago).

**Comment by asinghvi17** [comment]
Same issue with PlotlyJS and PGFplots backends.  Seems like this is in Plots, not backend dependent.

**Comment by daschw** [comment]
I'm not sure if it would be better to drop also the corresponding angles or to restore the old behaviour @kleinschmidt describes. Any opinions?

**Comment by MasonProtter** [comment]
I'd vastly prefer the old behaviour.

**Comment by daschw** [comment]
Should be restored in #2010

**Comment by kleinschmidt** [comment]
Fantastic, thanks for the quick attention.

**Comment by daschw** [comment]
Thanks for reporting!

**Comment by mkborregaard** [comment]
So awesome @daschw
