### ISSUE TITLE
PLOTS_DEFAULT_BACKEND is broken

### ISSUE THREAD

**Issue by slarew** [JuliaPlots/Plots.jl#2012]
I'm using Julia 1.1.0 and have set `ENV["PLOTS_DEFAULT_BACKEND"] = "UnicodePlots"` in `~/.julia/config/startup.jl` with the UnicodePlots package added.  When I run Julia and try to use Plots, I see
```
julia> using Plots
julia> backend()
┌ Warning: You have set `PLOTS_DEFAULT_BACKEND=UnicodePlots` but `UnicodePlots` is not loaded.
└ @ Plots ~/.julia/packages/Plots/47Tik/src/backends.jl:149
Plots.GRBackend()
```
The only fix appears to be to manually call `unicodeplots()` after loading Plots.

Related to #1942.

**Comment by daschw** [comment]
dup of #1942
