### ISSUE TITLE
Will you merge more kernels to Plots, such as Gnuplot, and MathGL?

### ISSUE THREAD

**Issue by Photonico** [JuliaPlots/Plots.jl#2013]
Plots.jl is very convenient for data visualization in Julia. It would be better if it could merge more kernels. For example, I think Gnuplot is better than Matplotlib in the scientific drawing.

**Comment by mkborregaard** [comment]
We don't mind adding new backends, if someone volunteers to maintain it :-)

**Comment by t-bltg** [comment]
First implementation of Gnuplot (Gaston) is now merged: https://github.com/JuliaPlots/Plots.jl/pull/3177.
