### ISSUE TITLE
Colorbar ticks are overridden with pgfplots.

### ISSUE THREAD

**Issue by korsbo** [JuliaPlots/Plots.jl#2015]
The ticks on the colorbar gets normalised to [0, 1] with the PGFPlots backend. 

    pgfplots()
    scatter(1:10, 1:10, zcolor=1:10, ms=10, seriescolor=:viridis)

![demo_pgfplots](https://user-images.githubusercontent.com/16306680/56975194-3155fb00-6b68-11e9-8dba-9af0d40543fd.png)

The other backends 

    gr()
    scatter(1:10, 1:10, zcolor=1:10, ms=10, seriescolor=:viridis)

![demo_gr](https://user-images.githubusercontent.com/16306680/56975219-37e47280-6b68-11e9-836e-b02ffb436654.png)

This is using Plots.jl v0.24.0 and PGFPlots v3.0.3.

**Comment by daschw** [comment]
Thanks for reporting!

**Comment by BeastyBlacksmith** [comment]
This is fixed in the pgfplotsx-backend
