### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by Roger-luo** [JuliaPlots/Plots.jl#2019]
The following is not working (GR subplot example)

```julia
l = @layout()
plot(randn(100, 5), layout=l, t=[:line :histogram :scatter :steppre :bar], leg=false, ticks=nothing, border=:none)
```

**Comment by daschw** [comment]
Huh! It should be
```julia
l = @layout([a{0.1h}; b [c;d e]])
plot(randn(100,5), layout=l, t=[:line :histogram :scatter :steppre :bar], leg=false,
     ticks=nothing, border=:none)
    end)]
```
as in https://github.com/JuliaPlots/Plots.jl/blob/master/src/examples.jl#L180-L190.
I'm not sure, why `[a{0.1h}; b [c;d e]]` is skipped in [generate_markdown](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/src/PlotDocs.jl#L52-L83) in PlotDocs.

**Comment by Roger-luo** [comment]
Thanks!

**Comment by daschw** [comment]
This is fixed by https://github.com/JuliaPlots/PlotDocs.jl/pull/164
