### ISSUE TITLE
Broken figure in documentation

### ISSUE THREAD

**Issue by nlw0** [JuliaPlots/Plots.jl#2021]
The `layout_4.png` figure in the docs seems to have a problem in its rendering. The code works for me, though.
https://docs.juliaplots.org/latest/layouts/
https://raw.githubusercontent.com/JuliaPlots/PlotReferenceImages.jl/master/PlotDocs/layout/layout_4.png
![layout_4](https://user-images.githubusercontent.com/161042/57192308-38498880-6f2f-11e9-88d9-d31375ae2f6e.png)

**Comment by logankilpatrick** [comment]
Opened this issues in the docs repo.

**Comment by logankilpatrick** [comment]
https://github.com/JuliaPlots/PlotDocs.jl/issues/137 see the issue here!

**Comment by logankilpatrick** [comment]
@daschw This seems to be common across many of the figures here : https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/layouts.md

**Comment by daschw** [comment]
Just to understand, what exactly is the issue: Is the figure size to small?

**Comment by logankilpatrick** [comment]
I don't think that is the entire issue since when I ran the code on my machines, the overlap of the axis's was not as extreme as in the docs. I think it's an issue with the way the images are being rendered/deployed.

**Comment by daschw** [comment]
I think that's fixed now, right?

**Comment by daschw** [comment]
Please reopen if you still see an issue.
