### ISSUE TITLE
X-axis at top

### ISSUE THREAD

**Issue by rakeshvar** [JuliaPlots/Plots.jl#2023]
I want the x-axis to be at the center (y=0) but it is coming out at the bottom.
```
using Plots
plotly()
plot([-1, 0, 1], line=(:stem, 2), m=(:red, 3), xticks=1:3, xmirror=true, yaxis=false)
```
![newplot](https://user-images.githubusercontent.com/2840906/57427858-a2398a80-71da-11e9-8a4a-41fb67386d8a.png)

How do I specify that? Thanks.

**Comment by mkborregaard** [comment]
Cross-posted here https://discourse.julialang.org/t/x-axis-at-center-of-plot/24015
