### ISSUE TITLE
"i not defined" in `gr_display` function

### ISSUE THREAD

**Issue by shipengcheng1230** [JuliaPlots/Plots.jl#2026]
Hello, I encounter an error "i not defined" when building doc using `Plots` (v0.25.0) and track it down here:

https://github.com/JuliaPlots/Plots.jl/blob/f742ae4c8850b6d9d665df84f06226882c33be47/src/backends/gr.jl#L858-L866

Should `i` in line 863 be replaced with `legendi`?

Thanks!

**Comment by daschw** [comment]
Yes, do you want to create a PR with this change?

**Comment by shipengcheng1230** [comment]
@daschw The PR is https://github.com/JuliaPlots/Plots.jl/pull/2028
