### ISSUE TITLE
Incorrect placement of labels in layout plot with GR

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#2032]
I always have issues with labels in layout plots, specially when I try to save the figure with `savefig`. is there any quick workaround to save the file without cropping the boundaries of the image?

![falsification](https://user-images.githubusercontent.com/3345261/57974178-9ee89080-798a-11e9-8540-096d7dce0c70.png)

Notice that the bottom xlabel is cut, and the ylabel are misaligned. If I save the figure as SVG the situation is worse.

**Comment by juliohm** [comment]
Regarding the label cut at the bottom, I could workaround it by increasing the figure size. The labels in the vertical axis are still misaligned, but I think I will move on and submit the paper like this.

**Comment by yuvalwas** [comment]
This problem still exists, and I find that sometimes only a drastic change in the figure size and proportions helps. Is there any other solution?

**Comment by BeastyBlacksmith** [comment]
Does increasing the one of the margins help?
E.g.: `bottom_margin = 2Plots.cm` ?

**Comment by yuvalwas** [comment]
> Does increasing the one of the margins help?
> E.g.: `bottom_margin = 2Plots.cm` ?

Yes, thank you!

**Comment by anneaux** [comment]
What about the ylabel alignment?
