### ISSUE TITLE
markerstrokewidth ignored for legend with PyPlot backend

### ISSUE THREAD

**Issue by tamasgal** [JuliaPlots/Plots.jl#2033]
This is related https://github.com/JuliaPlots/Plots.jl/issues/1305

The markerstrokewidth is not propagated to the legend as seen here:

![image](https://user-images.githubusercontent.com/1730350/58080672-e9992100-7bb3-11e9-8390-f7be719b8185.png)

**Comment by isentropic** [comment]
@daschw no longer relevant
![image](https://user-images.githubusercontent.com/24591123/79830573-a60cef80-83e0-11ea-92ae-f08324c36903.png)
