### ISSUE TITLE
`aspect_ratio` does not fully work with pgfplots()

### ISSUE THREAD

**Issue by abhinavd** [JuliaPlots/Plots.jl#2037]
It looks like the pgfplots() backend does not yet properly handle the `aspect_ratio` option.  [#216](https://github.com/JuliaPlots/Plots.jl/pull/216) seems to address this, but one can only switch between the default and the `:equal` settings. I cannot set a desired aspect ratio that's different from these two.
Is there a plan to implement the full feature on pgfplots?

Thanks!

**Comment by nmheim** [comment]
I am having the same problem

**Comment by BeastyBlacksmith** [comment]
It should work with the pgfplotsx backend. Would be good, if someone can confirm

**Comment by nmheim** [comment]
Yes, it work with PGFPlotsX! Thank you! :)

```julia
using Plots
pyplot()

x = rand(10,20)
p = heatmap(x,aspect_ratio=:equal)
display(p)
```
Results in:
![jl_khR5yU](https://user-images.githubusercontent.com/29552345/82120811-06e1da80-9789-11ea-9b0d-b7c81a2e58a7.png)

Just one minor thing is that the y-axis is longer than the grid, which is the same with `gr()`, but with e.g. `pyplot()`

**Comment by BeastyBlacksmith** [comment]
had that discussion on slack not long ago. Good to know that pyplot handles this, meanwhile here is a workaround:
```julia
using Plots
struct MyImage{T}
         array::T
end
@recipe function f(im::MyImage)
         im = im.array
         aspect_ratio --> 1
         xlims --> (1, size(im, 2))
         ylims --> (1, size(im, 1))
         seriestype := :heatmap
         ( im, )
end
plot( MyImage(randn(512,512)))
```
