### ISSUE TITLE
Changing axis scale display

### ISSUE THREAD

**Issue by JuanDiegoDC** [JuliaPlots/Plots.jl#2038]
Hi–

Currently I'm running some simulations and trying to plot some visualizations of these.

The problem I am having is that the x-axis ticks are colliding into one another. The problem can be clearly seen in this example:

<img width="651" alt="Screenshot 2019-05-27 12 13 32" src="https://user-images.githubusercontent.com/33184416/58413501-3891fb00-8079-11e9-9940-339679928634.png">

Might you suggest any solutions to make the x-axis more legible? Is there some way of truncating the x-axis ticks, so that I can get single digits in the ten-thousands scale? For example, "5.0 x 10^3" could be represented as "0.5". 

I have attempted to use the formatter attribute as follows:

xformatter = x -> string(Int(x/1e4))

but I keep getting an "InexactError()" ...

Thanks in advance!

**Comment by mkborregaard** [comment]
There are several possibilities. You can use the `xrotation` keyword to rotate the x axis labels, or the `guidefont` keyword to reduce the font size. You can also pass `xticks` explicitly, as a tuple of ticks and values. Or you can do the sensible thing you are trying and use the `xformatter` keyword. It should probably be `xformatter = x -> string(floor(Int, x/1e4))`, as you can't convert a float to an int without explicitly rounding it.

**Comment by JuanDiegoDC** [comment]
Thank you very much @mkborregaard 

`xformatter = x -> string(floor(Int, x/1e4))` worked as desired. As you mentioned, I overlooked the fact that I can't convert a float to an Int without rounding it..
