### ISSUE TITLE
Tick computation hangs when y-range/y ratio is small 

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#2039]
For example, 
```plot([5, 5+1e-15])``` 
hangs. 
A keyboard interrupt shows that it's in `optimize_ticks_typed`.

**Comment by mkborregaard** [comment]
Could this be from Showoff.jl? That's the package that does the ticks, and it internally casts all values to Float32s in the process.

**Comment by yha** [comment]
It doesn't look like `optimize_ticks_typed` uses Showoff, as far as I can tell. 
And manually casting the values to Float32 helps in this case: `Float32[5, 5+1e-15] == Float32[5,5]` and this plots fine.
