### ISSUE TITLE
GKS error

### ISSUE THREAD

**Issue by GathererA** [JuliaPlots/Plots.jl#2045]
When I attempt the simplest plot in Plots, I get a continual error where a Plots window is opened but nothing is shown, and the following error message is shown:

julia> plot(1)
GKS: Rectangle definition is invalid in routine SET_WS_VIEWPORT
GKS: Workstation window is not within the NDC unit square in routine SET_WS_WINDOW
GKS: Viewport is not within the NDC unit square in routine SET_VIEWPORT

I have built Plots, updated Plots, deleted and reinstalled Plots to no avail

I am running Julia through Atom on a MacBook Pro

**Comment by mkborregaard** [comment]
That error is from GR though. Can you try `ENV["GRDIR"] = ""; ]build GR`?

**Comment by GathererA** [comment]
Amazing, wow, thank you so much

**Comment by mxbi** [comment]
In my case, I got an identical error because I did:

```
plot(..., size=(4, 3))
```
Unlike matplotlib (which uses size in inches), I believe Plots.jl does it in pixels, so the issue is that the plot is too small. Setting `size=(400, 300)` fixed it.

Posting here in case this helps anyone else!
