### ISSUE TITLE
Crashing is common

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#2058]
Note that it is not just me.   Here is another documented example:
```
The Plots package still has some bugs, but it is maturing quickly. The most solid backend seems to be the default gr. Yet, even then, sometimes, GKSTerm on macos suddenly vanishes, and the julia session freezes. Sometimes, you need to refresh GKSTerm with an explicit display(p) (where p is the plot). etc.
```
This is from a nice tutorial website at: http://julia.cookbook.tips/doku.php?id=plotting

Last updated 12/27/2018.  Nothing has changed since then.  Crashes of GKSTerm that kill the Julia session are incessant.

**Comment by mkborregaard** [comment]
That is very interesting - I have that too on my computer, but noone else seem to, and @jheinen has not been able to reproduce. What's your versioninfo? here's mine:
```julia
julia> versioninfo()
Julia Version 1.2.0-rc1.0
Commit 7097799 (2019-05-30 02:22 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 3
```

**Comment by mkborregaard** [comment]
I'd say that the sentence "nothing has changed since then" is needlessly provocative, and also demonstrably untrue. Take a look at the number of commits to Plots since that date.

**Comment by lewisl** [comment]
There is a lot of stuff to be sure. The window management is inconsistent across backends, some of which have no API of their own for window management. I guess it will always be a problem.

I love Plots and will switch back to the PyPlot backend, which has more explicit “figure” management.

It’s frustrating to see so much effort across so many projects, each of which may have significant and possibly unique motivating benefits. But, there is also tons of overlap for the “essentials”. The result is each project is a little or a lot starved for investment. Some consolidation of effort would both enable new capabilities while reducing some duplication on essentials, bug fixing, documentation, platform support and other “taxes.”

- Lewis

On Jun 8, 2019, at 9:19 AM, Michael Krabbe Borregaard <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd say that the sentence "nothing has changed since then" is needlessly provocative, and also demonstrably untrue. Take a look at the number of commits to Plots since that date.

**Comment by lewisl** [comment]
My version info:

Julia Version 1.1.1

Commit 55e36cc (2019-05-16 04:10 UTC)

Platform Info:

  OS: macOS (x86_64-apple-darwin15.6.0)

  CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz

  WORD_SIZE: 64

  LIBM: libopenlibm

  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

Environment:

  JULIA-EDITOR = sublime

What’s surprising is it happens long after the plot was displayed and closed.  It appears that GKSTerm dies and takes down the Julia instance.  J.Heinen refers to some sort of polling that has to be done to keep the window open.  Seems like it would be better to just close GKSTerm gracefully after the user closes the last plot window instance.

How do I set my numthreads?  Is the benefit noticeable.  It’s not like Julia 1.x seems slow—pretty much an overall improvement across the board compared to earlier versions, but hey, speed is speed.

**Comment by jheinen** [comment]
The GKSTerm is "loosely" coupled to the Julia interpreter using `ZMQ` - in earlier times, we used an `NSConnection` for that purpose. The point is, that we had to chose such a method because macOS requires the window context to be created in a **master** thread. Nevertheless, GKSTerm should never crash the interpreter.

In a first step, we will have to reproduce the problem to be able to fix it. How is your workflow? Do you keep the GKSTerm open for minutes, hours, always?

BTW: The situation will become better with the new figure management (WIP) and the native implementation of the missing graphics features (required by Plots). But this will cause a complete rewrite of the backend to eliminate lots of Julia code in the `gr` backend part.

**Comment by jheinen** [comment]
Does this also happen with `JULIA_NUM_THREADS = 0` ?

**Comment by lewisl** [comment]
Thanks for following up.

I don’t have that env variable even set.  What is preferred?

**Comment by lewisl** [comment]
New figure management would be great.  Sorry it is such extensive work (sigh).

Workflow involves some big SparseArrays. They’d be well over 100G as dense arrays, but Julia stays at under 600meg during ML training.  I plot convergence curves for training and test data—not a complex plot.  Then, issue closeall().

Keep working—usually just predictions and other work with the trained weights.  Memory use of Julia stays reasonable (under 1G).  Anywheres from 15’ to 2 hours later, the GKSTerm window hangs and the terminal window in which the Julia REPL is running hangs. Only thing to do is quit terminal, which also shuts down GKSTerm.

It pretty much happens every session working with this application.  I can share the packages loaded if that would help.

It would be great to wrestle the actual cause to the ground.  Ultimately, window/figure management that could close both the plot window and the GKSTerm session would also work.

I think your hunch that it is the polling/messaging between GKSTerm and Julia to keep GKSTerm alive is the culprit.  At some point, the messages don’t get through to Juia. Of course, I don’t need or want GKSTerm to be open (it makes sense to keep it alive waiting for more plots rather than pay the overhead to start it up again), but it can’t be closed programmatically.

Which suggests, hey—if I am done with plotting for a while I should just go close it manually.  ‘doh!

**Comment by EMCP** [comment]
I was experiencing inability to plot on OSX , posted about it on this old issue https://github.com/JuliaPlots/Plots.jl/issues/1865

fresh install here

```
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

```

code that exhibits blank GKSTerm windows crashing and opening is 

```
using Pkg
Pkg.add("Plots")

using Plots
# define the Lorenz attractor
mutable struct Lorenz
    dt; σ; ρ; β; x; y; z
end

function step!(l::Lorenz)
    dx = l.σ*(l.y - l.x)       ; l.x += l.dt * dx
    dy = l.x*(l.ρ - l.z) - l.y ; l.y += l.dt * dy
    dz = l.x*l.y - l.β*l.z     ; l.z += l.dt * dz
end

attractor = Lorenz((dt = 0.02, σ = 10., ρ = 28., β = 8//3, x = 1., y = 1., z = 1.)...)


# initialize a 3D plot with 1 empty series
plt = plot3d(1, xlim=(-25,25), ylim=(-25,25), zlim=(0,50),
                title = "Lorenz Attractor", marker = 2)

# build an animated gif by pushing new points to the plot, saving every 10th frame
@gif for i=1:1500
    step!(attractor)
    push!(plt, attractor.x, attractor.y, attractor.z)
end every 10
```

**Comment by mkborregaard** [comment]
I've answered over there.
@lewisl this seems to have stopped occurring for me - you?

**Comment by lewisl** [comment]
Switched back to pyplot backend to avoid this.  I’ll live GR another try.

**Comment by lewisl** [comment]
Really old and Plots has improved tons. I tend to use mostly with pyplot backend.  So, close because it wasn't really actionable and good things have happened.
