### ISSUE TITLE
colorbar_entry undocumented in attributes docs

### ISSUE THREAD

**Issue by JeffFessler** [JuliaPlots/Plots.jl#2068]
`colorbar_entry` is undocumented in the attributes page
http://docs.juliaplots.org/latest/attributes/

It took me a long time to figure out that it was the solution I needed.
I would have helped by submitting a PR to update the docs but I can't find the source for the docs...

**Comment by mkborregaard** [comment]
Oh, right, thanks. `colorbar_entry` was added in this PR https://github.com/JuliaPlots/Plots.jl/pull/1969 by @yha , and it seems we forgot to add the docs for it. 
The attributes documentation is auto-generated from the data in this file: https://github.com/JuliaPlots/Plots.jl/blob/master/src/arg_desc.jl . A PR would be appreciated.

**Comment by JeffFessler** [comment]
Done, #2069, thanks.
