### ISSUE TITLE
Aspect ratio should adjust lims, not image size?

### ISSUE THREAD

**Issue by kescobo** [JuliaPlots/Plots.jl#2070]
Example:

```
using Plots
x = collect(1:100)
y = rand(100)

plot(x,y, aspect_ratio=1)
```

<img width="655" alt="Screen Shot 2019-06-21 at 2 35 56 PM" src="https://user-images.githubusercontent.com/3502975/59944083-e783e580-9431-11e9-90b2-557f605a6a70.png">

[From discourse](https://discourse.julialang.org/t/proper-use-of-scaling-on-axes-from-ordinations-like-mds-and-pca/24606/11?u=kevbonham), @mkborregaard said:

>BTW I think it’s a bug that Plots adjusts the image size by the aspect_ratio. It should use aspect_ratio to redefine the x and y lims

May affect https://github.com/JuliaPlots/StatsPlots.jl/pull/230

**Comment by mkborregaard** [comment]
This was already fixed in https://github.com/JuliaPlots/Plots.jl/pull/2061

**Comment by kescobo** [comment]
oops, sorry!
