### ISSUE TITLE
twinx() not working with PGFPlots

### ISSUE THREAD

**Issue by dancsi** [JuliaPlots/Plots.jl#2071]
Hello, 
It seems to me that PGFPlots gives an incorrect output when trying to share the same x axis between two plots with `twinx()`. Here is the sample code
```julia
using Plots
pgfplots()
plot(1:10); plot!(twinx(), -(1:10))
```
Here is the output of PGFPlots:
![pgfplots](https://user-images.githubusercontent.com/405156/60018588-109fb280-968c-11e9-8372-3c7dcc0222f3.png)
Here is the generated .tex: [pgfplot.txt](https://github.com/JuliaPlots/Plots.jl/files/3320775/pgfplot.txt)
For reference, here is the correct output from GR:
![gr](https://user-images.githubusercontent.com/405156/60018773-75f3a380-968c-11e9-9533-23846242380b.png)

**Comment by daschw** [comment]
That's messed up. Thanks for reporting!

**Comment by tzxiong** [comment]
I have experienced the same problem today. `twinx()` works fine for `pyplot()` and `gr()` backends, but will black-out the entire background under pgfplots.

**Comment by BeastyBlacksmith** [comment]
This does not become black, but still is messed up in the `pgfplotsx`-backend

**Comment by pjentsch0** [comment]
Any workarounds for this?

**Comment by matthieugomez** [comment]
I'd be interested in a solution too! The `twinx()` issue seems to be checked in the PGFPlotsX meta-issue, but it's still not working for me.

**Comment by IljaK91** [comment]
I have the same problem with the x-axis being not identical for the second plot. Would greatly appreciate a fix :)

**Comment by PythonNut** [comment]
> Any workarounds for this?

I know this is terrible but in the meantime, I just save the `tex` and edit it by hand to make the axes match.

**Comment by BeastyBlacksmith** [comment]
The relevant part for layouting is here
https://github.com/JuliaPlots/Plots.jl/blob/57ba6aa5a99f595db153faecc576b652d58329ca/src/backends/pgfplotsx.jl#L120-L185

**Comment by bhc1010** [comment]
Is there a reason why the right margin of the subplot is being set to `max(sp[:right_margin], 30px)` and not `max(sp[:right_margin], 0px)` ? Changing this fixed the problem for me, but I'm not sure if that creates other issues.

https://github.com/JuliaPlots/Plots.jl/blob/57ba6aa5a99f595db153faecc576b652d58329ca/src/layouts.jl#L776-L787

**Comment by BeastyBlacksmith** [comment]
we'd definitely need to check the other backends, but setting up a PR wouldn't hurt

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/4488.
