### ISSUE TITLE
MATLAB like clabel in contour

### ISSUE THREAD

**Issue by Tagussan** [JuliaPlots/Plots.jl#2084]
Is it possible to plot values on the level lines in contour?
Something like [clabel in MATLAB](https://www.mathworks.com/help/matlab/creating_plots/label-contour-plot-levels.html?requestedDomain=)

**Comment by mkborregaard** [comment]
Yes. This page (https://docs.juliaplots.org/latest/attributes/) in the docs lists `contour_labels` - I'd recommend using Ctrl-F on that page to find things. Usage questions can be directed to https://gitter.im/tbreloff/Plots.jl or the plotting channel on Julia's slack, if you're on there.

**Comment by Tagussan** [comment]
Thank you! I will further questions on gitter.

**Comment by pavanakumar** [comment]
You can pass the parameter `contour_labels=true` inside the `contour(..., contour_labels=true)` function. If the backend supports it then it will display labels.
