### ISSUE TITLE
Latex cropped in png output (GR)

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#2086]
```
plot(rand(4), title="\$ABCD\$", size=(400,400))
```
displayed in Juno or saved as `png`, the title is cropped:

![tmp](https://user-images.githubusercontent.com/4170948/60528049-3ec06a80-9cfc-11e9-852d-3d11aa8ace03.png)
PDF output is fine.
I believe this is a relatively new regression: it affects some of my figures which rendered fine a few months ago.

**Comment by daschw** [comment]
@jheinen is this an issue in Plots or in GR?

**Comment by jheinen** [comment]
This problem is related to the `cairoplugin` in GR (which is used for PNG rendering). We will check this ...

**Comment by daschw** [comment]
Thanks a lot!

**Comment by BeastyBlacksmith** [comment]
Can't reproduce on Plots v1.1.1
