### ISSUE TITLE
pyplot can't plot heatmap properly for large size matrices

### ISSUE THREAD

**Issue by Paalon** [JuliaPlots/Plots.jl#2091]
pyplot backend fails to plot heatmap for large size matrices.
gr backend works fine.

```julia
using Plots
pyplot()
A = rand(200, 200)
heatmap(A)
```
![rand_200_200](https://user-images.githubusercontent.com/11065457/60667004-6998f300-9ea3-11e9-9249-e679cf5ef7a9.png)

```julia
A = rand(400, 400)
heatmap(A)
```

![rand_400_400](https://user-images.githubusercontent.com/11065457/60667038-7ddcf000-9ea3-11e9-9a4a-69ea0145944f.png)

```julia
A = rand(1000, 1000)
heatmap(A)
```
![rand_1000_1000](https://user-images.githubusercontent.com/11065457/60667080-93eab080-9ea3-11e9-8f2e-1ddc82cd240e.png)

The critical value is between 316 and 317.

316
![rand_316_316](https://user-images.githubusercontent.com/11065457/60667128-b8df2380-9ea3-11e9-9324-f709bf92dfed.png)

317
![rand_317_317](https://user-images.githubusercontent.com/11065457/60667134-bbda1400-9ea3-11e9-844e-629e43181aa1.png)

316^2 = 99856 and 317^2 = 100489 so then it seems to have problems when the components are more than 100000.

```juliarepl
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc (2019-05-16 04:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

(v1.1) pkg> st Plots
    Status `~/.julia/environments/v1.1/Project.toml`
  [682c06a0] JSON v0.20.0
  [91a5bcdd] Plots v0.25.2
  [2913bbd2] StatsBase v0.30.0
  [9a3f8284] Random

(v1.1) pkg> st PyPlot
    Status `~/.julia/environments/v1.1/Project.toml`
  [b964fa9f] LaTeXStrings v1.0.3
  [438e738f] PyCall v1.91.2
  [d330b81b] PyPlot v2.8.1
```

**Comment by asinghvi17** [comment]
What happens if you tile the heatmap?  Something like:
```julia
using Plots
pyplot()
data = rand(Float32, 1000, 1000)
sc = heatmap(data[1:end÷2, 1:end÷2])
heatmap!(sc, data[(end÷2 + 1):end, 1:end÷2])
heatmap!(sc, data[1:end÷2, (end÷2 + 1):end])
heatmap!(sc, data[(end÷2 + 1):end, (end÷2 + 1):end])
```

**Comment by asinghvi17** [comment]
This actually produces a problem on GR, where only the last heatmap is actually shown in the plot.  @daschw is my Plots syntax wrong, or is this a bug in Plots/GR?  There were no warnings other than "multiple series share a colorbar".

**Comment by Paalon** [comment]
@asinghvi17 
```julia
using Plots
pyplot()
data = rand(Float32, 316*2, 316*2)
sc = heatmap(1:size(data, 1)÷2, 1:size(data, 2)÷2, data[1:end÷2, 1:end÷2])
heatmap!(sc, (size(data, 1)÷2 + 1):size(data, 1), 1:size(data, 2)÷2, data[(end÷2 + 1):end, 1:end÷2])
heatmap!(sc, 1:size(data, 1)÷2, (size(data, 2)÷2 + 1):size(data, 2), data[1:end÷2, (end÷2 + 1):end])
heatmap!(sc, (size(data, 1)÷2 + 1):size(data, 1), (size(data, 2)÷2 + 1):size(data, 2), data[(end÷2 + 1):end, (end÷2 + 1):end])
```
generates

![test](https://user-images.githubusercontent.com/11065457/61120584-43dda080-a4d8-11e9-8e9c-a92a764b3389.png)

**Comment by asinghvi17** [comment]
OK, so that's one approach to circumventing this issue for the time being...

**Comment by asinghvi17** [comment]
Is it possible to "hijack" `heatmap`, and fragment it into multiple calls to `heatmap` if the dimension of the input matrix is too large?  It's a bit of a hacky solution, but I think it might work.

**Comment by daschw** [comment]
> is my Plots syntax wrong, or is this a bug in Plots/GR?

On first sight I can't see anything wrong with the syntax, so probably a Plots bug.

**Comment by daschw** [comment]
> Is it possible to "hijack" heatmap, and fragment it into multiple calls to heatmap if the dimension of the input matrix is too large?

`heatmap` is not implemented as a recipe but differently for different backends in the respective bakcend code. So I think this would be rather difficult. Does GR also have the large matrix heatmap issue or is it just PyPlot?

**Comment by asinghvi17** [comment]
I think GR is fine as per this issue, no?

**Comment by asinghvi17** [comment]
Perhaps it's possible to special case it and recursively break up the heatmap for the Pyplot backend only?

**Comment by daschw** [comment]
That could be possible.

**Comment by asinghvi17** [comment]
https://github.com/JuliaPlots/Plots.jl/blob/a1182e0ebe5d3bdd1672dda9bad47897b3331536/src/backends/pyplot.jl#L769-L788
seems to be the relevant code.  Unfortunately, I'm not an expert on matplotlib, so someone else may have to take up the actual implementation.

**Comment by daschw** [comment]
Off-topic: How do you reference to/include code as nicely as you did in your post above, @asinghvi17 ?

**Comment by asinghvi17** [comment]
Go to the relevant code in the browser (on the Github interface), select the relevant lines in the sidebar (they should show up in yellow), then click on the `...` to the top let of the selection, and `Copy permalink`.
<img width="653" alt="Screen Shot 2019-07-13 at 4 42 00  13900PM" src="https://user-images.githubusercontent.com/32143268/61170885-2c142400-a58d-11e9-8e48-a3c47ac461ce.png">

**Comment by daschw** [comment]
Thanks!

**Comment by tony-ko** [comment]
Do not know, if this is still a relevant issue (at least it is open), but I don't have any trouble with plotting matrices as big as 10000x10000 in the current version (Julia v1.3.1, PyPlot v2.8.2, Plots v0.29.1)

`using Plots

pyplot()

A = rand(10000, 10000)
out=heatmap(A, dpi = 1200)

savefig(out,"outheat.png")`

![outheat](https://user-images.githubusercontent.com/44169740/74945129-3db58800-5408-11ea-96b6-a36bad677b19.png)

Colorbar is a mess though.
