### ISSUE TITLE
Scatter3d depthshade (pyplot backend)

### ISSUE THREAD

**Issue by CVerbist1** [JuliaPlots/Plots.jl#2092]
In a 3D scatter in base PyPlot you have an option "depthshade" that can be turned on/off. When using Plots, and pyplot as a backend, depthshade seems to be on by default but I couldn't find a way to turn it off. Is this possible to turn off or a possibility to add it? 
![deptshade](https://user-images.githubusercontent.com/22769287/60716395-912da100-9f1f-11e9-9338-7b021947e138.png)

**Comment by SKYnSPACE** [comment]
Me neither. I couldn't find the way to turn that off. Just tricked the plot3d with a dummy value located behind of the scene having marker size 0.

**Comment by isentropic** [comment]
@BeastyBlacksmith  perhaps I could a relevant attribute like :pydepthshade?

**Comment by BeastyBlacksmith** [comment]
Cleanest way would be, if we had https://github.com/JuliaPlots/Plots.jl/issues/2197.

**Comment by isentropic** [comment]
perhaps:
`plot(x1, x2, backendkeyword="parameter=value")`
aliases:
`plot(x1, x2, bk="parameter=value")`  
`plot(x1, x2, backend_keyword="parameter=value")`

**Comment by BeastyBlacksmith** [comment]
Since that is merged, you can now could get a value in the backend code via `get(series[:extra_kwargs], :depthshade, true)`

**Comment by isentropic** [comment]
@CVerbist1 @SKYnSPACE let me know your feedback about this. Refer to https://github.com/JuliaPlots/Plots.jl/pull/2703 and let me know if this is what you wanted
