### ISSUE TITLE
Axis bug introduced recently in GR backend

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#2094]
Without changing any code, my visual regression tests are now failing (again):

### Before:
![hold](https://user-images.githubusercontent.com/3345261/60770203-e0eea280-a0ae-11e9-8906-0f44a62b9679.png)

### After:
![hnew](https://user-images.githubusercontent.com/3345261/60770206-e77d1a00-a0ae-11e9-8f95-91a698fd3f23.png)

In this plot recipe, I set `aspect_ratio=:equal`, and it is clearly not working. Could you please review recent changes in Plots.jl that may have affected this?

Also, does Plots.jl use some sort of visual regression test as well? How these errors are committed to releases without anyone noticing?

**Comment by yha** [comment]
I'm not sure what caused the change, but it doesn't seem related to aspect ratio, since that is actually the same in the "before" and "after" images – it's just the y range that's different.

**Comment by juliohm** [comment]
Thank you @yha for linking the issue. Appreciate if someone can double check to see if that PR introduced the bug.

**Comment by daschw** [comment]
That was introduced by #2061, @juliohm, but on purpose, so I would not consider it a bug. @mkborregaard  and I agreed that `aspect_ratio` should not impact the subplot/axes size. Don't you agree?

**Comment by juliohm** [comment]
Thank you @daschw for pointing out the change. I agree that `aspect_ratio` should not impact the subplot/axes size, but there is no way to enforce the previous behavior where a squared axis (cross-plot with equal range) is indeed a square? Right now the cross-plots in the example above are rectangles even though the x and y axis are nearly equal in length.

In any case I understand the behavior now, trying to convince myself that this is the right thing to do.

**Comment by daschw** [comment]
You can enforce square axes by setting `aspect_ratio = true` and manually setting `xlims` and `ylims` to be the same. `lims = (0.02, 0.18)` or something similar should work in your case (I hope).

**Comment by asinghvi17** [comment]
With reference to this - is there any way to make a plot have some custom visual aspect ratio now that doesn't involve foreknowledge of the limits?

**Comment by daschw** [comment]
No, but this was not possible with `aspect_ratio`'s old behaviour in general either. Do you think that this should be possible with a new attribute? I'm not sure how often this would be used.

**Comment by juliohm** [comment]
Yes, I am closing the issue for now since I can in theory adjust the figure size to obtain squared subplots.
