### ISSUE TITLE
Can we add compat for non-dependencies?

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Plots.jl#2100]
https://github.com/JuliaPlots/Plots.jl/blob/8c2a66b00cf4e5e4bf49cf07ab82f9a43fd7c16c/src/backends/pyplot.jl#L39

This line could conceivably just be put in the `compat` section of Project.toml; can we, and should we?

**Comment by daschw** [comment]
I don't think that's possible, but I'm not sure.

**Comment by asinghvi17** [comment]
After discussion on Slack, no, that's not possible.
