### ISSUE TITLE
Problems with Plot (with Atom/Juno)

### ISSUE THREAD

**Issue by matteobreschi** [JuliaPlots/Plots.jl#2101]
Hi everyone, 

I am starting to code with Julia so I wrote some (really basic) tests and plots, like this one:

using Printf
using Plots
using GR
gr()
default(show = true)

x = collect(1:0.1:50)
y = [xi - xi*cos(xi) for xi in x]

plot(x,y)

However I have a constant error:

`LoadError: UndefVarError: plot not defined
in expression starting at /Users/matteobreschi/Work/JuliaTests/matteo/test1.jl:18
top-level scope at none:0`

I tryed to remore and re-build GR (thorught the GRDIR variable) but actually nothing solve the issue. Do you have any idea ? 

Thanks a lot, i am not confident with Julia yet, 
but I hope someone is able to help me.

Matteo

**Comment by matteobreschi** [comment]
Just as information, I use Atom+Juno as editor and the Stacktrace I have as output is the following:

 [1] top-level scope at none:0
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] exec_options(::Base.JLOptions) at ./client.jl:267
 [6] _start() at ./client.jl:436

**Comment by daschw** [comment]
You probably got a warning like:
```julia
WARNING: both GR and Plots export "plot"; uses of it in module Main must be qualified
```
If you want to plot with Plots, you do not need `using GR`. Otherwise, both Plots and GR export `plot`, and you have to specify which to use by calling `Plots.plot` or `GR.plot`.
Just doing
```julia
using Plots

x = collect(1:0.1:50)
y = [xi - xi*cos(xi) for xi in x]

plot(x,y)
```
should work.

**Comment by matteobreschi** [comment]
Yes , I had also that problem , but even removing GR the error appears . I solved it using `Plots.plot(x,y)`.

Thank you so much
