### ISSUE TITLE
Plots 0.26 on Windows

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPlots/Plots.jl#2103]
on windows 10, user account, 

```using Plots```

gives

```
 Warning: On Windows, creating file symlinks requires Administrator privileges
└ @ Base.Filesystem file.jl:794
```

**Comment by daschw** [comment]
I think this is related to https://github.com/JuliaIO/FFMPEG.jl.
cc: @asinghvi17 
Should I open an issue over there?

**Comment by asinghvi17** [comment]
Possibly it is...feel free to open an issue!

**Comment by BeastyBlacksmith** [comment]
Is this still the case with `_jll`s?

**Comment by asinghvi17** [comment]
No, this should not be a problem anymore.
