### ISSUE TITLE
custom palettes with group and small number of observations per group

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaPlots/Plots.jl#2104]
I encountered the following unexpected behavior: when all the elements of the vector passed to `group=` are unique, all the points are plotted with the same color, but ONLY when a custom palette is supplied. Here's an (annotated) MWE:

```julia
using Colors, Plots

block_pallete = LCHab.(60, 60, range(0, 320, length=25))

x = [1:100;]
y = [1:100;]
block = repeat(1:25, inner=4)

x1 = [1:25;]
y1 = [1:25;]
block1 = [1:25;]

# plot before aggregating plots the rainbow like we asked for:
scatter(x, y, group=block, palette=block_pallete)

# these all plot the points the same color:
scatter(x1, y1, group=block1, palette=block_pallete)
scatter(x1, y1, group=block1, color=(1:25)', palette=block_pallete)

# but using the inherited palette seems to work:
# this plots all different colors (using the default palette)
scatter(x1, y1, group=block1)
# this plots the rainbow as expected:
plot(palette=block_pallete)
scatter!(x1, y1, group=block1)


# this plots two slightly different colors:
scatter(x1, y1, group=[1:24; 24], palette=block_pallete)
# this plots all the same color:
scatter(x1, y1, group=[1; 1:24], palette=block_pallete)

# this works?
x2=[1:50;]
y2=[1:50;]
block2=repeat(1:25, inner=2)
scatter(x2, y2, group=block2, palette=block_pallete)
```

```
    Status `/tmp/Project.toml`
  [5ae59095] Colors v0.9.5
  [a93c6f00] DataFrames v0.19.0
  [28b8d3ca] GR v0.40.0
  [91a5bcdd] Plots v0.26.0
  [f3b207a7] StatsPlots v0.10.2
```

**Comment by asinghvi17** [comment]
For reference, this is what the plots look like:
```julia
using Colors, Plots

block_pallete = LCHab.(60, 60, range(0, 320, length=25))

x = [1:100;]
y = [1:100;]
block = repeat(1:25, inner=4)

x1 = [1:25;]
y1 = [1:25;]
block1 = [1:25;]

# plot before aggregating plots the rainbow like we asked for:
scatter(x, y, group=block, palette=block_pallete)
```
![1](https://user-images.githubusercontent.com/32143268/61711318-68a40480-ad71-11e9-89f7-86cd8f14d84d.png)
```julia
# these all plot the points the same color:
scatter(x1, y1, group=block1, palette=block_pallete)
```
![2](https://user-images.githubusercontent.com/32143268/61711319-693c9b00-ad71-11e9-898f-3b1e994c355d.png)
```julia
scatter(x1, y1, group=block1, color=(1:25)', palette=block_pallete)
```
![3](https://user-images.githubusercontent.com/32143268/61711320-693c9b00-ad71-11e9-9cfb-c57e7151da6f.png)
```julia
# but using the inherited palette seems to work:
# this plots all different colors (using the default palette)
scatter(x1, y1, group=block1)
```
![4](https://user-images.githubusercontent.com/32143268/61711321-693c9b00-ad71-11e9-89c1-1992fc93e59e.png)
```julia
# this plots the rainbow as expected:
plot(palette=block_pallete)
scatter!(x1, y1, group=block1)
```
![5](https://user-images.githubusercontent.com/32143268/61711322-69d53180-ad71-11e9-87e7-d6b8e14095cc.png)
```julia
# this plots two slightly different colors:
scatter(x1, y1, group=[1:24; 24], palette=block_pallete)
```
![6](https://user-images.githubusercontent.com/32143268/61711323-69d53180-ad71-11e9-9c94-f1306b61b2cf.png)
```julia
# this plots all the same color:
scatter(x1, y1, group=[1; 1:24], palette=block_pallete)
```
![7](https://user-images.githubusercontent.com/32143268/61711324-69d53180-ad71-11e9-9649-352ac0a8f147.png)
```julia
# this works?
x2=[1:50;]
y2=[1:50;]
block2=repeat(1:25, inner=2)
scatter(x2, y2, group=block2, palette=block_pallete)
```
![8](https://user-images.githubusercontent.com/32143268/61711326-6a6dc800-ad71-11e9-8f57-df0f753e975a.png)

**Comment by nathancunn** [comment]
I also find this to be a nuisance. It appears to be a design decision though:
> If passed a gradient, it will infinitely draw unique colors from that gradient, attempting to spread them out

From https://docs.juliaplots.org/latest/colors/#misc

**Comment by kleinschmidt** [comment]
The colors aren't a gradient though, they're a vector of colors.

**Comment by nathancunn** [comment]
Ah yes, I'm getting bugged by a slightly different issue, which pertains to gradients and colour specifications. It's evident in your example:

`# this plots all different colors (using the default palette)
scatter(x1, y1, group=block1)`

If you use `palette = :viridis`, for example, here the palette doesn't follow the ordering of the palette but rather tries to reorder the palette to separate similar colours from one another.

**Comment by kleinschmidt** [comment]
Thanks for the fix!
