### ISSUE TITLE
Plot recipe for type is much slower than actual plot command

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#2106]
What is the reason for this recipe to be so slow compared to a direct plot of the coordinates?

```julia
using GeoStatsBase
using Plots

# avoid long times plotting svg
gr(format=:png)

d = RegularGrid{Float64}(100,100,100)
X = coordinates(d)

# works, takes some time but works
@time plot(X[1,:], X[2,:], X[3,:], seriestype=:scatter, size=(800,800))

# does not return, and the plot recipe is effectively doing the same thing
@time plot(d, size=(800,800))
```

If I reduce the grid size to say 10x10x10, the recipe returns as expected. You can find the relevant code here: https://github.com/juliohm/GeoStatsBase.jl/blob/master/src/plotrecipes/domains/regular_grid.jl#L63-L90

In order to reproduce, please install the master branch `GeoStatsBase#master`

**Comment by daschw** [comment]
The only reason I can see for the performance difference are the many individual series added to the plot with `@series`. In the 100x100x100 case you are adding 30000 series. I think the recipe would be faster if instead of the three `@series` loops at the bottom you first constructed `NaN`-separated `x` and `y` values and then added single `@series` instances.
Something like replacing:
```julia
for i in 1:sz[1], j in 1:sz[2]
    @series begin
        seriestype --> :path
        primary --> false
        [or[1]+(i-1)*sp[1],or[1]+(i-1)*sp[1]], [or[2]+(j-1)*sp[2],or[2]+(j-1)*sp[2]], [or[3],or[3]+(sz[3]-1)*sp[3]]
    end
end
```
with
```julia
x = fill(NaN, 3*sz[1], sz[2])
y = fill(NaN, 3*sz[1], sz[2])
z = fill(NaN, 3*sz[1], sz[2])
for i in 1:sz[1], j in 1:sz[2]
    # populate x
    x[3i-2, j] = or[1]+(i-1)*sp[1]
    x[3i-1, j] = or[1]+(i-1)*sp[1]
    # populate y
    y[3i-2, j] = or[2]+(j-1)*sp[2]
    y[3i-1, j] = or[2]+(j-1)*sp[2]
    # populate z
    y[3i-2, j] = or[3]
    y[3i-1, j] = or[3]+(sz[3]-1)*sp[3]
end
@series begin
    primary := false
    seriestype := :path
    reshape(x, :), reshape(y, :), reshape(z, :)
end
```
I know that's a little bit more verbose but it adds one series instead of 10000 in the case of `sz = (100, 100, 100)`.
I have not tested this, it's just a guess.

**Comment by juliohm** [comment]
Thank you @daschw, could you please elaborate on the lines:

```julia
x = fill(NaN, 3*sz[1], sz[2])
y = fill(NaN, 3*sz[1], sz[2])
z = fill(NaN, 3*sz[1], sz[2])
```

What are you trying to do intuitively? Is the `3` general? Assume I have a rectangular grid with `sz[1] != sz[2] != sz[3]`. Also, I updated the recipe to make it cleaner:

```julia
    aspect_ratio --> :equal
    linear = LinearIndices(sz)
    @series begin
      seriestype --> :scatter
      X[1,:], X[2,:], X[3,:]
    end
    for i in 1:sz[1], j in 1:sz[2]
      @series begin
        seriestype --> :path
        primary --> false
        inds = [linear[i,j,k] for k in 1:sz[3]]
        X[1,inds], X[2,inds], X[3,inds]
      end
    end
    for i in 1:sz[1], k in 1:sz[3]
      @series begin
        seriestype --> :path
        primary --> false
        inds = [linear[i,j,k] for j in 1:sz[2]]
        X[1,inds], X[2,inds], X[3,inds]
      end
    end
    for j in 1:sz[2], k in 1:sz[3]
      @series begin
        seriestype --> :path
        primary --> false
        inds = [linear[i,j,k] for i in 1:sz[1]]
        X[1,inds], X[2,inds], X[3,inds]
      end
    end
```

How we can replace these for loops with a single recipe at the end? Ideas?

**Comment by juliohm** [comment]
ping @daschw
