### ISSUE TITLE
Plots slows down entire Jupyter notebook

### ISSUE THREAD

**Issue by Bebotron** [JuliaPlots/Plots.jl#2111]
I have 4 files that I load with readdlm, each about 5~6KB each. When I plot them using Plots (they plot successfully), it slows down the entire notebook. I can basically edit cells for 3 lines (exactly) just fine, and then any more lines are incredibly laggy. Has anyone else experienced this as well? I thought the problem might be readdlm, since that has some issues but only with very large data. My files are not that big and running a cell only loading the data works just fine. Additionally, plotting very simple things also don't cause much of a problem:
```
x = collect(0:0.01:2*pi)
y = sin.(x)
plot(x,y)
```
This doesn't cause any problems. So is it a problem of Plots struggling with larger data?

**Comment by daschw** [comment]
Does it help if you add `default(fmt = :png)` after `using Plots`?

**Comment by Bebotron** [comment]
How interesting, it does fix the problem. However, I am using a dark theme on jupyter, and so I've been using `theme(:juno)`. So if I do this:
```
using Plots
using PlotThemes
theme(:juno)
default(fmt = :png)
```
And this will fix any lag, but will not make the plot axes and labels dark, which makes them hard to read with the dark background. So if I switch the order around to:
```
using Plots
using PlotThemes
default(fmt = :png)
theme(:juno)
```
And now the axes coloring is correct, but the lag is still there. Might there be something in the juno theme that is setting the default formatting?

**Comment by daschw** [comment]
`theme(:juno, fmt = :png)`?

**Comment by Bebotron** [comment]
No that still makes the axes and labeling dark. I'm trying to find the theme files and see if there's something obvious there.

**Comment by daschw** [comment]
Hm the issue here seems to be that setting a fontcolor does not work for GR:
```
plot(rand(10), xguide = "Hello", tickfontcolor = :blue, guidefontcolor = :blue)
```
![gr_fontcolor](https://user-images.githubusercontent.com/16589944/61982579-808fb880-affd-11e9-9827-27f6ae87100a.png)

**Comment by Bebotron** [comment]
Yes, setting `fmt = :png` within the `juno.jl` specifications gives dark axes.

**Comment by daschw** [comment]
When I plot from the REPL setting the font color works:
```
plot(rand(10), xguide = "Hello", tickfontcolor = :blue, guidefontcolor = :blue)
```
<img width="557" alt="gr_fontcolor_repl" src="https://user-images.githubusercontent.com/16589944/61983763-f007a700-b001-11e9-900a-0048779692be.PNG">

When I save this plot as PNG I get

![gr_fontcolor_png](https://user-images.githubusercontent.com/16589944/61983782-fd249600-b001-11e9-8145-4dc13ae57885.png)

That's why setting `fmt = :png` messes up the theme in GR.
cc: @jheinen any ideas?

**Comment by Bebotron** [comment]
Using the pyplot backend works just fine. So in case someone just needs a work-around, just do
```Julia
using Plots
using PlotThemes
theme(:juno)
pyplot()
```
It would be nice if this issue could be fixed for Plots, but for now this is something anyone else who might be experiencing this could use.

**Comment by daschw** [comment]
Saving as SVG should also work, but leads to the original lagging issue in jupyter for plots with a lot of data.

**Comment by jheinen** [comment]
The color problem can (hopefully) be fixed - the SVG problem probably not. What does "a lot of data" mean (MWE)? Plotting millions of points makes only sense when using GR's shading routines.

**Comment by Bebotron** [comment]
In my particular case, I only have 200,000 data points to plot, which definitely isn't much. I don't know at which specific point the plotting starts lagging the entire notebook, but my particular problem can be emulated with the following:
```Julia
using Plots
x = collect(0:1e-4:20)
y = sin.(x)
plot(x, y)
```
After generating this plot, the entire notebook is laggy.

**Comment by jheinen** [comment]
In this case, you should set `gr(fmt=:png)`. Most browsers can't handle such point arrays in SVG.

**Comment by Bebotron** [comment]
Yes, and like we discuss above this fixes the lagging issue, but then the axes coloring doesn't work (remains black).

**Comment by daschw** [comment]
> The color problem can (hopefully) be fixed

The color problem is in GR, not in Plots, right @jheinen ?

**Comment by jheinen** [comment]
I get the same results for `pyplot()` and `gr(fmt=:png)`. Am I missing something?
![Screenshot 2019-08-01 at 10 12 10](https://user-images.githubusercontent.com/5718244/62276664-d7a1ed00-b444-11e9-95b3-d0220724d294.png)

**Comment by daschw** [comment]
```
using Plots
theme(:juno, tickfontcolor = :blue, fmt = :png)
```
**PyPlot**

As shown when plotted from the REPL:
![pyplot_color_repl](https://user-images.githubusercontent.com/16589944/62278420-52b8d280-b448-11e9-9f26-1abd41e10a21.PNG)

As saved with `png(...)`:
![pyplot_color_save](https://user-images.githubusercontent.com/16589944/62278443-6106ee80-b448-11e9-9514-ab70262fa32a.png)

**GR**

As shown when plotted from the REPL:
![gr_colors_repl](https://user-images.githubusercontent.com/16589944/62278484-74b25500-b448-11e9-9cc1-a004ac818979.PNG)

As saved with `png(...)`:
![gr_color_save](https://user-images.githubusercontent.com/16589944/62278518-8693f800-b448-11e9-9d06-49a14dee73a0.png)

Note the tick and legend font colors in the last image.

**Comment by jheinen** [comment]
Strange - that's exactly what i did and which leads to this PNG:
![t](https://user-images.githubusercontent.com/5718244/62279514-8dbc0580-b44a-11e9-9434-a55f52e495b6.png)

**Comment by jheinen** [comment]
```
    Status `/usr/local/lib/julia/environments/v1.1/Project.toml`
  [53c48c17] FixedPointNumbers v0.5.3
  [28b8d3ca] GR v0.41.0 #master (https://github.com/jheinen/GR.jl.git)
  [77ba4419] NaNMath v0.3.2
  [ccf2f8ad] PlotThemes v0.3.0
  [995b91a9] PlotUtils v0.5.8+ #master (https://github.com/JuliaPlots/PlotUtils.jl.git)
  [91a5bcdd] Plots v0.26.0 #master (https://github.com/JuliaPlots/Plots.jl.git)
  [3cdcf5f2] RecipesBase v0.7.0 #master (https://github.com/JuliaPlots/RecipesBase.jl.git)
  [992d4aef] Showoff v0.3.1 #master (https://github.com/JuliaGraphics/Showoff.jl.git)
  [2913bbd2] StatsBase v0.31.0
```

**Comment by jheinen** [comment]
I also tried on Ubuntu 18.04 - same result. I can't reproduce the problem ...

**Comment by daschw** [comment]
I just updated my packages
```
]up
ENV["GRDIR"] = GR
]build GR
```
and now the colors work for me too.
`fmt = :png` also works correctly in IJulia for me now.

Sorry for the noise @jheinen!
@Bebotron If updating and rebuilding GR does not fix the issue for you feel free to reopen.

That large (many data points) svgs slow down the browser is an issue that will not be fixed here.

**Comment by Bebotron** [comment]
So I ran `using Pkg; Pkg.update();` and now I'm getting the error
```
error compiling _plot!: error compiling _display: could not load library "libGR.dll"
The specified module could not be found.
```
I don't think I should reopen the issue since this seems like a completely different problem and technically my original problem was solved using the `pyplot()` backend. This was part of the output after I updated
```
 Installed DataAPI ─────────── v1.0.0
 Installed FixedPointNumbers ─ v0.6.1
 Installed FFMPEG ──────────── v0.2.2
 Installed IJulia ──────────── v1.19.0
 Installed Plots ───────────── v0.26.0
 Installed IterTools ───────── v1.2.0
 Installed StatsBase ───────── v0.32.0
 Installed GR ──────────────── v0.41.0
 Installed GeometryTypes ───── v0.7.5
```
am I missing something? I can go ahead a look this up outside of this thread if it seems like too much of a digression. Thanks for all the help!

**Comment by Bebotron** [comment]
Sorry @jheinen I just saw your solution here https://github.com/JuliaPlots/Plots.jl/issues/1720. Everything works now! Thanks guys!
