### ISSUE TITLE
Plots fails in precompiling

### ISSUE THREAD

**Issue by alirezamecheng** [JuliaPlots/Plots.jl#2112]
Hello 
I updated the package and I get this error in precompiling stage
```julia
julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
ERROR: LoadError: UndefVarError: ffmpeg not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:328 [inlined]
 [7] eval(::Expr) at ./client.jl:404
 [8] top-level scope at ./none:3
in expression starting at /home/ghavami/.julia/packages/FFMPEG/7auNk/src/FFMPEG.jl:58
ERROR: LoadError: Failed to precompile FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a] to /home/ghavami/.julia/compiled/v1.1/FFMPEG/TGvga.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:328 [inlined]
 [11] eval(::Expr) at ./client.jl:404
 [12] top-level scope at ./none:3
in expression starting at /home/ghavami/.julia/packages/Plots/jWNMG/src/Plots.jl:11
ERROR: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to /home/ghavami/.julia/compiled/v1.1/Plots/ld3vC.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
```

**Comment by alirezamecheng** [comment]
It is solved. I just removed the package, executed the garbage collector `gc` and reinstalled the package again and everything seems to work fine. 
I think the `update` command done sth unexpected.

**Comment by VolkerSmits** [comment]
> 
> 
> It is solved. I just removed the package, executed the garbage collector `gc` and reinstalled the package again and everything seems to work fine.
> I think the `update` command done sth unexpected.

Hi,

I tried to follow your instructions to solve the problem, but on my machine it doesn´t solve the problem (Windows 10, Julia 1.1.1). I´m quite a newbie in Julia. So maybe I did something wrong. I removed the package via Pkg.rm("Plots") and run the garbage collecter with GC.gc() and then reinstalled the package with Pkg.add("Plots"). Have I done something wrong?

**Comment by daschw** [comment]
Try to run `Pkg.gc()` instead of `GC.gc()` in the second step. Maybe that helps.

**Comment by VolkerSmits** [comment]
> 
> 
> Try to run `Pkg.gc()` instead of `GC.gc()` in the second step. Maybe that helps.

Thanks. That helped :)

**Comment by brendanjmeade** [comment]
I'm getting the same error:

julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
ERROR: LoadError: UndefVarError: ffmpeg not defined

under Ubuntu 18.04.  I've tried uninstalling and reinstalling with the gc advice given above with no luck.

Julia is very new to me (loving it!) and I'd appreciate any help!

**Comment by asinghvi17** [comment]
What is the output of `]build FFMPEG`?

**Comment by alirezamecheng** [comment]
I write the steps more clear:
in Julia repel:
```julia 
julia> using Pkg
julia> Pkg.rm("Plots")
julia> Pkg.gc()
julia> Pkg.add("Plots")
```
these steps worked for me. Both in windows 10 julia 1.1.0 and linux mint

**Comment by brendanjmeade** [comment]
]build FFMPEG 
 built just fine and fixed this problem.  Thank you very much!  I have a lot to learn.

**Comment by Ernesto3110** [comment]
I did all the steps but still having the problem. Do you know another solution? (W10, Julia 1.1.1)

**Comment by daschw** [comment]
What's the error message you get, @Ernesto3110 ? Also what's the output of `]st -m Plots`?

**Comment by shencebebetterme** [comment]
`julia> using Pkg
julia> Pkg.rm("Plots")
julia> Pkg.gc()
julia> Pkg.add("Plots")`
still has FFMPEG build errors,
however
`julia> using Pkg
julia> Pkg.rm("Plots")
julia> GC.gc()
julia> Pkg.add("Plots")`
gives no error. 
(system: Ubuntu 18.04, Julia 1.1.1)

**Comment by Originofamonia** [comment]
Hello everyone, I encountered the same problem when installing Plots package. It first says build FFMPEG, but then I run "build FFMPEG", I got the following errors:

 Building FFMPEG → `C:\Users\Edward\.julia\packages\FFMPEG\9JQpZ\deps\build.log`
┌ Error: Error building `FFMPEG`:
│ ┌ Error: Download failed: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
│ └ @ Base download.jl:43
│ ERROR: LoadError: failed process: Process(`'C:\Windows\System32\curl.exe' -s -S -g -L -f -o 'C:\Users\Edward\.julia\packages\FFMPEG\9JQpZ\deps\build_Bzip2.v1.0.6.jl' https://github.com/JuliaPackaging/Yggdrasil/releases/download/Bzip2-v1.0.6-2/build_Bzip2.v1.0.6.jl`, ProcessExited(35)) [35]
│
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:813 [inlined]
│  [2] download_curl(::String, ::String, ::String) at .\download.jl:44
│  [3] download(::String, ::String) at .\download.jl:52
│  [4] top-level scope at C:\Users\Edward\.julia\packages\FFMPEG\9JQpZ\deps\build.jl:46
│  [5] include at .\boot.jl:328 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1094
│  [7] include(::Module, ::String) at .\Base.jl:31
│  [8] include(::String) at .\client.jl:431
│  [9] top-level scope at none:5
│ in expression starting at C:\Users\Edward\.julia\packages\FFMPEG\9JQpZ\deps\build.jl:44
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647

Can anyone help me?
Thanks!

**Comment by Flock1** [comment]
> julia> Pkg.rm("Plots")
> julia> GC.gc()
> julia> Pkg.add("Plots")

I have Ubuntu 20.04 and I followed these steps. I am still getting this error:
```
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
Your GR installation is incomplete. Rerunning build step for GR package.
ERROR: LoadError: LoadError: InitError: Evaluation into the closed module `GR` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `GR` with `eval` during precompilation - don't do this.
```
What should I do?

**Comment by ethantsai** [comment]
> [ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
> Your GR installation is incomplete. Rerunning build step for GR package.
> ERROR: LoadError: LoadError: InitError: Evaluation into the closed module `GR` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `GR` with `eval` during precompilation - don't do this.
> ```
> What should I do?

just do `]build GR`

**Comment by jaiswaldeepali27** [comment]
julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

(process:2840): GLib-GIO-WARNING **: 20:02:28.833: Unexpectedly, UWP app `AcerIncorporated.PredatorSenseV30_3.0.3136.0_x64__48frkmn4z8aw4' (AUMId `AcerIncorporated.PredatorSenseV30_48frkmn4z8aw4!CentenialConvert') supports 1 extensions but has no verbs
ERROR: LoadError: LoadError: too many parameters for type
Stacktrace:
  [1] _precompile_()
    @ Plots C:\Users\divya\.julia\packages\Plots\AGxtZ\deps\SnoopCompile\precompile\precompile_Plots.jl:92
  [2] top-level scope
    @ C:\Users\divya\.julia\packages\Plots\AGxtZ\src\precompile_includer.jl:14
  [3] include(mod::Module, _path::String)
    @ Base .\Base.jl:386
  [4] include(x::String)
    @ Plots C:\Users\divya\.julia\packages\Plots\AGxtZ\src\Plots.jl:1
  [5] top-level scope
    @ C:\Users\divya\.julia\packages\Plots\AGxtZ\src\Plots.jl:267
  [6] include
    @ .\Base.jl:386 [inlined]
  [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base .\loading.jl:1235
  [8] top-level scope
    @ none:1
  [9] eval
    @ .\boot.jl:360 [inlined]
 [10] eval(x::Expr)
    @ Base.MainInclude .\client.jl:446
 [11] top-level scope
    @ none:1
in expression starting at C:\Users\divya\.julia\packages\Plots\AGxtZ\src\precompile_includer.jl:9
in expression starting at C:\Users\divya\.julia\packages\Plots\AGxtZ\src\Plots.jl:1
ERROR: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to C:\Users\divya\.julia\compiled\v1.6\Plots\jl_7268.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
   @ Base .\loading.jl:1385
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1329
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1043
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:936
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:923

I got this error
what should i do?
