### ISSUE TITLE
'c' argument issue in pyplot

### ISSUE THREAD

**Issue by agent-007-A** [JuliaPlots/Plots.jl#2113]
the code was very simple for only coloring my dots
i.e., _**plt.scatter(x_values, y_values, c=(0, 0, 0.8), edgecolor='none', **s=40)****_
__
the error comes here

"'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points"

**Comment by agent-007-A** [comment]
from matplotlib.axes._axes import _log as matplotlib_axes_logger
matplotlib_axes_logger.setLevel('ERROR')

resolved with this code adding at the starting of code

**Comment by JackDevine** [comment]
I don't understand what this has to do with Plots.jl. Do you have a piece of code that we can run that will reproduce this bug?
