### ISSUE TITLE
`fillcolor` does not accept floats

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Plots.jl#2114]
Will expand on this by editing the issue later, but `fillcolor` doesn't take Floats, even when a `cgrad` is provided.
```julia
bar(data; fillcolor=rand(10), cgrad=:inferno)
ERROR: MethodError: no method matching plot_color(::Float64)
```
Is this a design decision, or can it be fixed?

**Comment by yha** [comment]
Gradients are specified by `*color`, color values to look up in the gradients by `*_z`:
```
bar( 1:10; fill_z=rand(10), fillcolor=:grays,
           line_z=rand(10), linecolor=:plasma, lw=10 )
```
![image](https://user-images.githubusercontent.com/4170948/62058522-45260180-b22a-11e9-831a-2673a03b2c85.png)

**Comment by asinghvi17** [comment]
Perfect...thanks!  Would be nice to have that schema documented somewhere, I'll look into putting a para in PlotDocs in a week or so.

**Comment by asinghvi17** [comment]
done
