### ISSUE TITLE
Continuous color gradient plotting 

### ISSUE THREAD

**Issue by blas-ko** [JuliaPlots/Plots.jl#2115]
Hello! 

The default behaviour of a `palette` is to separate its colours as most as possible. I know this separation is an intended feature, but I'd like to know how to colour my plots in a continuous fashion so that the transition between the plots looks smooth.      

Here's a little example of what I mean: 
```julia
using Plots # gr

f(x; b) = x.^2 .+ b
x = collect(0:10)
Y = [f(x, b = b) for b in -10:2:10]

plot(Y, palette=:blues, leg=:topleft, tickfont=font(12))
```
which outputs

![image](https://user-images.githubusercontent.com/8909006/62140213-7e21ad00-b2e2-11e9-9439-2cf4435f67da.png)

**Is there a way to colour the line from clear to dark blue (or vice-versa)?**

Thanks, and sorry for the silly question.

**Comment by daschw** [comment]
You can achieve this by adding a `line_z` value to each line, which is a number corresponding to the position along the gradient. By default this comes with a colorbar, which can be avoided with `colorbar = false`.
```julia
plot(Y, color=:blues, line_z=(0:10)', leg=:topleft, tickfont=font(12), colorbar=false)
```
![line_z](https://user-images.githubusercontent.com/16589944/62153233-69eea780-b304-11e9-8ac7-c377547d9e3f.png)

There are no silly questions ;-)

**Comment by blas-ko** [comment]
Awesome! Thanks a lot!!
