### ISSUE TITLE
Plotting in Julia 

### ISSUE THREAD

**Issue by harshal1802** [JuliaPlots/Plots.jl#2116]
I have .nc file from the model output. E.g. after 'using NCDatasets' and 'ds =Dataset("stationll7.nc")', I get this: 
uhh_ergom_split_zoo_zoo   (1 × 1 × 80 × 37987)
    Datatype:    Float32
    Dimensions:  lon × lat × z × time
    Attributes:
     units                = mmol n/m**3
     long_name            = uhh_ergom_split_zoo zooplankton
     valid_min            = 0.0
     valid_max            = 1.0e20
     _FillValue           = -2.0e20
     coordinates          = lon lat z
     cell_methods         = time: point
I like to know how I can create time series in julia with this data.

**Comment by daschw** [comment]
I don't see how this is related to Plots.jl. I suggest asking at https://github.com/Alexander-Barth/NCDatasets.jl.
