### ISSUE TITLE
Can not turn off xlabel? 

### ISSUE THREAD

**Issue by danielchen26** [JuliaPlots/Plots.jl#2117]
when plotting solution from DifferentialEquation.jl. is there a way to turn off xlabel? currently, `t` is always showing for the xaxis

**Comment by JackDevine** [comment]
`xaxis!("")` should solve it.

**Comment by danielchen26** [comment]
That works, thanks   
  

  
  

  
  
>

**Comment by daschw** [comment]
or `xlabel = ""` directly in the `plot` call
