### ISSUE TITLE
Histogram for strings? (categorical)

### ISSUE THREAD

**Issue by Moelf** [JuliaPlots/Plots.jl#2123]
At the moment the following produces an error:
```
using Random
histogram(randstring("abc",12))
```

not even this:
```
using Random, StatsBase
cm = countmap(randstring("ABC", 20) |> collect)
bar(keys(cm) |> collect, values(cm) |> collect)
```

**Comment by daschw** [comment]
Apparently Plots can't handle `Char` input. This should be fixed in #2124, until then you can convert to `String` first:
```julia
bar(string.(collect(keys(cm))), collect(values(cm)))
```

**Comment by Moelf** [comment]
I wonder if we can just make `histogram` works with categorial Arrays, if so, where do we do it. I'm happy to make a PR

**Comment by daschw** [comment]
The relevant code is here
https://github.com/JuliaPlots/Plots.jl/blob/79777adc079cb4811c03d333a348ab03e898103e/src/recipes.jl#L667-L700
and above.
Adding histograms for categorical Arrays is probably just a matter of implementing a method of `_make_hist` for categorical Arrays.
Right, @oschulz?

**Comment by oschulz** [comment]
I think so - however, currently, everything is based on `StatsBase.Histogram`. I don't know if that supports categorical axes (I think not). If not, maybe it would be good to start there and add support for such histograms to `StatsBase` - such a histogram would also be useful in data analysis, not just plotting, I'd guess.

**Comment by yha** [comment]
`StatsBase` already has `countmap` for categorical data. It's not the same as a histogram (there are no bins), and I don't think they should be conflated in `StatsBase`.
Maybe the two two can share the name `histogram` in Plots (and disambiguated based on data type), but I think it would be better to separate them in Plots as well. We could have a general recipe for plotting `AbstractDict{<:Any,<:Real}` as bar plots, which I think is a useful and reasonable default anyway, and then you can do
```
using StatsBase
plot(countmap(data))
```

**Comment by oschulz** [comment]
Yes, that sound very reasonable.

**Comment by mkborregaard** [comment]
I agree it makes sense, people may also want to print the count of numbers.

**Comment by mkborregaard** [comment]
Maybe have a new series recipe called `:counts` that would run the `countmap` automatically and plot the Dict?
