### ISSUE TITLE
savefig appears to miscalculate margins with GR over ssh/without X

### ISSUE THREAD

**Issue by cmcaine** [JuliaPlots/Plots.jl#2127]
Related: #1905

```jl
using Plots
savefig(plot(rand(100)), "plot.pdf")
```

Observe that the left margin is off the page when I run this over ssh (without X)

[plotsjl-plot-without-x.pdf](https://github.com/JuliaPlots/Plots.jl/files/3473327/plotsjl-plot-without-x.pdf)
[plotsjl-plot-with-x.pdf](https://github.com/JuliaPlots/Plots.jl/files/3473328/plotsjl-plot-with-x.pdf)

Running this before making the plot seems to fix it: `ENV["GKSwstype"]="100"`:

[plotsjl-plot-without-x-workaround.pdf](https://github.com/JuliaPlots/Plots.jl/files/3473326/plotsjl-plot-without-x-workaround.pdf)

Current error messages when running without X:

Machine 1:
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

connect: Connection refused
GKS: can't connect to GKS socket application
Did you start 'gksqt'?

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
```

Machine 2:
```
.julia/packages/GR/ZI5OE/src/../deps/gr/bin/gksqt: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
connect: Connection refused
GKS: can't connect to GKS socket application
Did you start 'gksqt'?

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
```

Both are capable of generating plots fine, so these error messages are inappropriate -- should just say it can't find X and shut up.

**Comment by oxinabox** [comment]
This doesn't seem to happen on headless Mac or Windows on GHA.
Posssibly bycause they have X (or equiv).

here is examples for  `heatmap([1 0; 0 1]`

## Headless Linux VM
![image](https://user-images.githubusercontent.com/5127634/108573595-f6a8ee00-730c-11eb-93a1-8c3ce6cffb17.png)

## Local Mac Laptop
(identical to Mac / Windows on GHA)
![image](https://user-images.githubusercontent.com/5127634/108573615-00caec80-730d-11eb-832e-e68dd066fde6.png)

**Comment by t-bltg** [comment]
I cannot reproduce this on a remote machine on `linux`. Does it still occur ?
