### ISSUE TITLE
Hide polar plot radial axis

### ISSUE THREAD

**Issue by ferrolho** [JuliaPlots/Plots.jl#2130]
```julia
Θ = range(0, stop=1.5π, length=100)
r = abs.(0.1 * randn(100) + sin.(3Θ))
plt = plot(Θ, r, proj=:polar, lw=3,
          axis=nothing,
          border=:none,  # Does not seem to make any difference.
          ticks = nothing,
          legend=nothing)
```

![Screenshot from 2019-08-07 20-35-48](https://user-images.githubusercontent.com/4166093/62652292-fa576880-b952-11e9-88e6-76855addc63f.png)

Am I missing the right argument for hiding the radial axis of a polar plot? Thanks!

**Comment by BeastyBlacksmith** [comment]
Late answer, but you are looking for `grid = :none`
