### ISSUE TITLE
Regression in Ribbon Plots (v0.26.0 => v0.26.1)

### ISSUE THREAD

**Issue by arnavs** [JuliaPlots/Plots.jl#2137]
cc @jlperla, @ChrisRackauckas

This code works on `v0.26.0` of the package, but not the latest `v0.26.1`. It looks like the regression is on the tuple of arrays input. 

The bug has downstream implications for, e.g. the ensemble plots in `DifferentialEquations.jl` which depend on this functionality.

```
using Plots, Statistics
sds = [1, 1/2, 1/4, 1/8, 1/16, 1/32]
n = 10
y = [mean(sd*randn(n)) for sd in sds]
errs = (-1.96 * sds / sqrt(n),1.96 * sds / sqrt(n))
plot(y, ribbon = errs)
```

**Comment by yha** [comment]
Note that this code does not produce ribbons on `v0.26.0` either. You probably mean
```
errs = (1.96 * sds / sqrt(n),1.96 * sds / sqrt(n))
```
(both vectors of positive elements).
Looks like I broke this on #2110.
As a workaround for this particular example (same size ribbon on both sides) you can just pass one of the vectors. I will post a PR to fix the two-vector case.

**Comment by arnavs** [comment]
OK, thanks. And you're right, I was just checking if the thing plotted _something_, but that's probably not good enough 😅...
