### ISSUE TITLE
Empty animation error handling

### ISSUE THREAD

**Issue by benchislett** [JuliaPlots/Plots.jl#2138]
I'm not sure how error handling is intended to work Julia libraries, and I'm curious if this is the indended result or if I have found an edge-case.

In short, when you attempt to write a gif of an empty animation, ffmpeg breaks:
```julia
using Plots

anim = @animate for i in []
    heatmap([i i; i i])
end

gif(anim, "/tmp/tmp.gif")
```

Specifically, I got an error code that was difficult to decipher:
```ERROR: failed process: Process(`/home/benchislett/.julia/packages/FFMPEG/9JQpZ/deps/usr/bin/ffmpeg -v 0 -i /tmp/tmp8tf59X/%06d.png -vf palettegen=stats_mode=diff -y /tmp/tmp8tf59X/palette.bmp`, ProcessExited(1)) [1]```

Should Plots check if the animation is empty before writing? If so, should it write an empty gif (can you even do that?), exit peacefully, or throw a custom error?
What's the standard for handling errors such as these in Julia libraries?

**Comment by daschw** [comment]
I think Plots could throw a more descriptive error or at least a warning in that case. Do you feel like submitting a PR?
