### ISSUE TITLE
@gif and @animate macro hygiene

### ISSUE THREAD

**Issue by sefffal** [JuliaPlots/Plots.jl#2143]
Let me preface this by saying thank you to the maintainers of Plots.jl! I've been using it heavily for months and this is really the first issue I've noticed, so thanks for all your hard work.

version: 0.26.1

Currently, if the user has a variable named `frame` defined then the at-gif macro will fail because it tries to use that instead of the Plots.frame function.

Looking at the @gif macro, I think this could be fixed by changing `frame` to `Plots.frame`. This probably applies to the call to `Animation()` as well, and maybe the at-animate macro too.

**Comment by asinghvi17** [comment]
Would be great if you can open a PR for this - seems like a pretty simple fix!  We'd be happy to help if you run into any issues :)

**Comment by sefffal** [comment]
Sounds good, thanks! I’ll take a look and see what I can do.

**Comment by t-bltg** [comment]
Seems fixed.
