### ISSUE TITLE
LaTeX strings for PyPlot ticks

### ISSUE THREAD

**Issue by sswatson** [JuliaPlots/Plots.jl#2147]
Is there a good way to get ticks to display in the PyPlot backend using LaTeX rather than `Showoff`'s unicode strings? I know code for this exists in the GR and PGFPlots backends, but it seems I would have to manually insert it that logic into `pyplot.jl`, which isn't ideal. 

I also considered supplying a function to `formatter` that just chains `showoff` and `convert_sci_unicode` the way it's done in the package code. But that doesn't work because `showoff` takes the whole array of tick values as input, while `formatter` maps over the tick array.

I know that in a pinch I could manually specify the ticks, but I'd like have a solution that just works. For now, I'm using `formatter = :plain` and forgoing scientific notation altogether.

**Comment by benide** [comment]
As long as you have matplotlib set up to use latex (e.g., `text.usetex : True` in your `matplotlibrc`), `formatter = :latex` should now do what you want.

**Comment by sswatson** [comment]
Yes, this is perfect. Thanks!
