### ISSUE TITLE
Getting smooth lines for sinusoidal functions

### ISSUE THREAD

**Issue by juliandemille** [JuliaPlots/Plots.jl#2149]
![2019-08-18-142945_1861x663_scrot](https://user-images.githubusercontent.com/8127111/63228699-a2c3c300-c1c4-11e9-88b0-bfdb8eebf869.png)
Having lines like this is very frustrating for me. Is there any way to have the lines smoothed out, or maybe decrease the step?

**Comment by juliandemille** [comment]
Apparently putting `0, 20` instead of `0:20` makes the line smoother in some way.

**Comment by yha** [comment]
`0:20` represents the series of numbers 0 to 20 _in increments of 1_ (0,1,2...), as you can see by calling `collect(0:20)` (this has nothing do to specifically with `Plots`). So you were explicitly asking to plot the function on the grid 0,1,2,...,20.
On the other hand, `plot(f, 0, 20)` for a function `f` asks `Plots` to automatically determine the grid.
