### ISSUE TITLE
Messy number formatting due to machine precision

### ISSUE THREAD

**Issue by aahaselgrove** [JuliaPlots/Plots.jl#2150]
I was trying to make a plot today with custom axis labels to represent currency, and I noticed that some numbers (for example, 0.6) wouldn't format neatly, and that the issue appears to be related to machine precision. Am I using yformatter incorrectly? These numbers render neatly with the :auto formatter.

I tried to find the code which was computing the axis labels, and think it is [here](https://github.com/JuliaPlots/Plots.jl/blob/cd1ee47acef798e49b003f0ef9699735cab8b825/src/axes.jl#L215). I tried incorporating Showoff.showoff into my formatter but I believe this function only works on arrays.

Plot:
````
using Random
using Plots
pyplot()

Random.seed!(4)
time = 0:20
spend = rand(21)
bar(time, spend,
    title="Spend over time",
    xlabel="Year",
    ylabel="Spend",
    yformatter=y->"\$$y")
````
![Figure_1](https://user-images.githubusercontent.com/2556805/63247884-72a22000-c2a9-11e9-8bbe-9af65705fde5.png)

**Comment by asinghvi17** [comment]
could try `round`?

**Comment by aahaselgrove** [comment]
I’m looking more to address the root cause.

**Comment by aahaselgrove** [comment]
This issue doesn't occur using the default formatter, so it must be doing something additional to prevent the machine precision error

**Comment by daschw** [comment]
This is prevented by using `Showoff.showoff` here:
https://github.com/JuliaPlots/Plots.jl/blob/648f26f075731940fad7319ac1bcef21ed444cc4/src/axes.jl#L211-L233
You can check Showoff code here: https://github.com/JuliaGraphics/Showoff.jl

**Comment by aahaselgrove** [comment]
Yeah I saw that and tried to incorporate Showoff.showoff, but it can only be applied to arrays of numbers, and the formatter is applied to individual tick values. I see some commented code in the else section for applying this function to custom-formatted code, though it seems that this is applied after the formatter, when I feel like it should be applied first (also, of course, it's commented out).

**Comment by asinghvi17** [comment]
You could wrap the number in an array?

**Comment by aahaselgrove** [comment]
I could, but I feel that fixing it in the package would be a better approach. I don't think I'm missing anything obvious in the formatter, in which case I would classify this behaviour as a bug.

**Comment by asinghvi17** [comment]
This is not something that can be fixed in Plots, because you've defined a custom `yformatter` (which returns a String), which Plots doesn't process because it assumes that that is the tick label the user wants.  You'd need to correct your `yformatter` to account for floating-point inaccuracies, but so far as I can tell there's nothing Plots should be doing differently here.

A correct `yformatter` could be as simple as `f = y -> "\$$(round(y; sigdigits=3))"` or something like that, which would do:
```julia
julia> f(1f0)
"\$1.0"

julia> f(1)
"\$1.0"

julia> f(55.5)
"\$55.5"

julia> f(55.5000000002)
"\$55.5"
```

**Comment by aahaselgrove** [comment]
The reason I suggest this is a bug is because floating-point inaccuracies are never desired. For example, plots could do the round. The only reason it doesn't is because this functionality is currently handled by Showoff, but the problem I am experiencing occurs because showoff can't be applied in my case.

**Comment by asinghvi17** [comment]
I think there's a bit of a misunderstanding here - in overriding the `yformatter`, you explicitly provide a string (generated by the function provided to `yformatter`) which you want Plots to use as the tick label directly.  It's not possible to round a string, so unless you do the rounding on your end, you end up with floating point errors.

**Comment by aahaselgrove** [comment]
I understand correctly. What I'm arguing is that the parameter to the yformatter should be rounded before being passed into the formatter, as this results in much cleaner code (one round call in axes.jl rather than one in a majority of existing yformatter lambdas).

Alternatively, optimize_ticks could return rounded ticks (which now seems like the obvious solution), but I can't see where that function is defined.

**Comment by aahaselgrove** [comment]
Opened a separate issue in PlotUtils: https://github.com/JuliaPlots/PlotUtils.jl/issues/66
