### ISSUE TITLE
Unable to resize legend title

### ISSUE THREAD

**Issue by aahaselgrove** [JuliaPlots/Plots.jl#2151]
Today I was looking for an attribute representing the size of the legend title, and was unable to find one - legendfontsize only applies to legend entries. To corroborate this, `Plots.scalefontsizes` scales all fonts except the legend title. Can this be added as a feature? I can't think why it would be the only unscalable font size.

**Comment by mkborregaard** [comment]
It was probably not added when font characteristics were revamped in https://github.com/JuliaPlots/Plots.jl/pull/1255

What happens if you do sth like `legendttitle = text("myawesometitle", 12)`?

**Comment by aahaselgrove** [comment]
I got a text representation of the font object xD

````
using Random
using Plots
pyplot()

Random.seed!(4)
time = 0:20
spend = rand(21)
bar(time, spend,
    title="Spend over time",
    xlabel="Year",
    ylabel="Spend",
    legendtitle=text("Test", 12))
````
![Figure_1](https://user-images.githubusercontent.com/2556805/63402047-fcbec580-c41c-11e9-8c03-ab4a1206489a.png)

**Comment by mkborregaard** [comment]
Thanks for reporting, that's clearly a bug.
