### ISSUE TITLE
wrong image in  tutorial

### ISSUE THREAD

**Issue by HendMahmoud** [JuliaPlots/Plots.jl#2152]
![image](https://user-images.githubusercontent.com/11365124/63335530-d544fb80-c33d-11e9-896e-e74708ebfa50.png)
The image doesn't show what the code does

**Comment by mkborregaard** [comment]
Could yuo provide a little more information? :-D

**Comment by HendMahmoud** [comment]
> Could yuo provide a little more information? :-D
Sorry I published it early by mistake :-D

**Comment by HendMahmoud** [comment]
Thank you for fixing it. :+1: 
best regards
