### ISSUE TITLE
slowdown on 1.2.0

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPlots/Plots.jl#2154]
I’ve tried to narrow down the problem with the slow plots (from Plots.jl) in 1.2.0. After some trial and error I noticed that this works equally fast in 1.1.1 and 1.2.0 (Win 10):
```
using Plots
gr()
x = -3:0.01:3
plot(x,cos.(x))
plot!(x,sin.(x))
```
However, adding the lines
```
title!("plot 1")
xlabel!("x")
ylabel!("function values")
```
almost doubles the time in 1.2.0 (but certainly not in 1.1.1). Using pyplot() instead of gr() gives the same general result. 

EDIT: using the more compact syntax
```
plot(x,cos.(x),
title = "plot 1",
xlabel="x",
ylabel= "function values")
plot!(x,sin.(x))
```
does not give a performance penalty in 1.2.0.

**Comment by daschw** [comment]
That's weird. I can confirm the regression on Win 10.

**Comment by PaulSoderlind** [comment]
There is a fair chance that this goes beyond Win 10. While CoCalc might not be the best platform for benchmarking, a few repeated tries still show a consistent patter:
when
```
plot(x,cos.(x))
plot!(x,sin.(x))
title!("plot 1")
xlabel!("x")
ylabel!("function values")
```
is called, then the first time to plot (with Julia 1.2.0) is 90 seconds or so. Instead, with
```
plot(x,cos.(x),
title = "plot 1",
xlabel="x",
ylabel= "function values")
plot!(x,sin.(x))
```
it is closer to 45 seconds. And, I believe CoCalc is linux based.

**Comment by PaulSoderlind** [comment]
Both approaches (see my 2nd post) appear to be a bit quicker on 1.30-rc2 (on Win10 64), but it is still the case that the the first approach (with `title!()`) takes approximately twice the amount of time compared to the second approach (with `title=` etc)
