### ISSUE TITLE
Specifing colors for 3D data

### ISSUE THREAD

**Issue by kiranshila** [JuliaPlots/Plots.jl#2161]
If I have gridded nxm data for x,y, and z, I can trivially call `surface` on these parameters to plot the corresponding surface. However, I would like the ability to set the color of each point explicitly instead of setting the color based on z. In matlab, I can just pass in a fourth matrix that will be mapped to colors as seen [here ](https://www.mathworks.com/help/matlab/ref/surf.html#bvgppvs-Z). Is this possible to do with Plots.jl? I have been experimenting with the PlotlyJS and PyPlot back ends specifically,

**Comment by daschw** [comment]
Unfortunately that is not possible with Plots right now.

**Comment by kiranshila** [comment]
Sounds good - for anyone who wonders, In `PlotlyJS surface(x=x,y=y,z=z,surfacecolor=colors)`

**Comment by kiranshila** [comment]
Its been a few years since I opened this issue, did this ever get any attention? This behavior is possible in pgfplots, plotly, pyplot, and GR. I'd be happy to work on a PR for this - but I don't want to step on any toes.

**Comment by kiranshila** [comment]
Ah, it seems `fill_z` does it! If this is right, we can close this issue.

**Comment by thisrod** [comment]
Does anyone have a working example of `fill_z`?  I get the following.

                   _
       _       _ _(_)_     |  Documentation: https://docs.julialang.org
      (_)     | (_) (_)    |
       _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 1.6.2 (2021-07-14)
     _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
    |__/                   |
    
    julia> using Plots
    [ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
    
    julia> ax = -3:0.1:3
    -3.0:0.1:3.0
    
    julia> x = [x for x in ax for y in ax];
    
    julia> y = [y for x in ax for y in ax];
    
    julia> z = @. exp(-hypot(x,y)^2);
    
    julia> plot(x, y, z, st=:surface)
    # works
    
    julia> plot(x, y, z, fill_z=z, st=:surface)
    Error showing value of type Plots.Plot{Plots.GRBackend}:
    ERROR: MethodError: no method matching iterate(::RGBA{Float64})
    Closest candidates are:
      iterate(!Matched::Union{LinRange, StepRangeLen}) at range.jl:664
      iterate(!Matched::Union{LinRange, StepRangeLen}, !Matched::Int64) at range.jl:664
      iterate(!Matched::T) where T<:Union{Base.KeySet{var"#s79", var"#s78"} where {var"#s79", var"#s78"<:Dict}, Base.ValueIterator{var"#s77"} where var"#s77"<:Dict} at dict.jl:693
      ...
    Stacktrace:
      [1] first(itr::RGBA{Float64})
        @ Base ./abstractarray.jl:386
      [2] gr_draw_surface(series::Plots.Series, x::Vector{Float64}, y::Vector{Float64}, z::Vector{Float64}, clims::Tuple{Float64, Float64})
        @ Plots ~/.julia/dev/Plots/src/backends/gr.jl:1958
    ...

**Comment by t-bltg** [comment]
https://docs.juliaplots.org/stable/generated/attributes_series/
https://docs.juliaplots.org/stable/gallery/gr/generated/gr-ref056/
