### ISSUE TITLE
Green text is not green with GR

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/Plots.jl#2177]
```julia
using Plots
plot(rand(10), color = :green)
annotate!(5, 0.5, Plots.text("Hello", :green))
```
![gr_green](https://user-images.githubusercontent.com/16589944/64492972-ad7cef80-d27a-11e9-88e3-f8d41b3287b2.png)

It works with red, so this is probably not a Plots issue
```julia
using Plots
plot(rand(10), color = :red)
annotate!(5, 0.5, Plots.text("Hello", :red))
```
![gr_red](https://user-images.githubusercontent.com/16589944/64492974-b2da3a00-d27a-11e9-9a65-94ca52932556.png)

cc: @jheinen

**Comment by asinghvi17** [comment]
Works on my machine now, with the following versions:
```julia
  [28b8d3ca] GR v0.46.0
  [91a5bcdd] Plots v0.28.5 [`../../dev/Plots`]
```
