### ISSUE TITLE
Multiple legend labels with `pyplot()` are misformatted. Works fine under `gr()`

### ISSUE THREAD

**Issue by Krastanov** [JuliaPlots/Plots.jl#2179]
`gr(); plot(rand(10,5),label=[1,2,3,4,5])` results in:

![image](https://user-images.githubusercontent.com/705248/64565513-f0de6900-d321-11e9-929d-608e1fd41123.png)

but with `pyplot(); plot(rand(10,5),label=[1,2,3,4,5])` results in this presumably incorrect behavior:

![image](https://user-images.githubusercontent.com/705248/64565540-fe93ee80-d321-11e9-905c-0e9c1ff7e307.png)

```
PyPlot v"2.8.2"
Plots v"0.26.2"
PyPlot.PyCall.pyimport("matplotlib").__version__ == "3.1.1"
Julia version v"1.4.0-DEV.106"
```

**Comment by JackDevine** [comment]
At first the `pyplot` behaviour seems incorrect, although in some ways it is more correct.

Each line on your plot is a column of your random array and the labels are the corresponding "columns" of the thing that your passed to the `label` argument. When you pass a 5x1 array, there are not enough columns, so `pyplot` repeats the one column that you give it. On the other hand if you did `label=[1 2 3 4 5]` (a 1x5 array), then you have 5 columns of length one, so you get what you expect.

In any case, the backends should display the same thing, so we need to decide which one is "more wrong" and fix that one.

**Comment by daschw** [comment]
IMO pyplot has the correct behaviour.

**Comment by JackDevine** [comment]
Agreed. I am happy to fix this, although I wont have time for a little over 24 hours, so it is quite possible that someone will beat me to it.

I think that whoever does fix this should also have a look at the docs to check if this is discussed. If not, then maybe there is scope for some clarification.
