### ISSUE TITLE
auto yli, xlim, tick spacing?

### ISSUE THREAD

**Issue by maxiloy** [JuliaPlots/Plots.jl#2192]
Hi, i am just starting to code in Julia. I wonder if there is any way i could in Plots to auto y limit, x limit and tick spacing? 

Thank you,

**Comment by mkborregaard** [comment]
Yes that should be automatic. Could you come with a reproducible example (code + end result) and describe what you find missing?

**Comment by mkborregaard** [comment]
If you're just looking for advice I'd suggest you to close this issue, open a Slack account and join julialang.slack.com where you can get advice in real time, rather than filing issues here

**Comment by maxiloy** [comment]
I don't have the example to show but thank you for your tips. will take a look at julialang.slack as suggested. .
