### ISSUE TITLE
Way to pass keywords to the backend

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaPlots/Plots.jl#2197]
It would be nice to have a way to pass backend-specific keywords.
One idea is, to have a `backend_options` keyword that takes a `Dict` or `NamedTuple` that gets passed as keywords to the backend.

**Comment by mkborregaard** [comment]
Do you feel like experimenting with a PR for one of the backends? It's been suggested several times.

**Comment by BeastyBlacksmith** [comment]
I did take a quick look on it, but the backend <-> frontend interface is not as clear-cut, as i had imagined and I get lost in the Plots pipeline quite quickly. So at least till the beginning of next year I won't have time.

**Comment by mkborregaard** [comment]
Have a look how this keyword arg was added and passed through to PyPlot https://github.com/JuliaPlots/Plots.jl/pull/1009/files

**Comment by BeastyBlacksmith** [comment]
Actually I see, that `extra_kwargs` does already exist, it is "just" not passed at the moment.

**Comment by BeastyBlacksmith** [comment]
Maybe it is at the wrong spot though, since it belongs to the `Plot` object, but as far as I can see, the backends operate on the `Subplot` level?

**Comment by mkborregaard** [comment]
I'm not sure what you mean by that?

**Comment by BeastyBlacksmith** [comment]
Let put it as a question: How would a backend query the plotattributes?

**Comment by mkborregaard** [comment]
The backend processes the Plot object and builds up a `series_list` containing the keywords passed to the backend. So I guess the extra_kw args should just be appended to the `series_list` without any transformations.

**Comment by BeastyBlacksmith** [comment]
A bit of a memo to myself :
- extra_kwargs needs to be actually be populated
- this requires different handling of unsupported kwargs, like only checking the Plots specific kwargs and put the rest in extra_kwargs

**Comment by isentropic** [comment]
perhaps:
`plot(x1, x2, backendkeyword="parameter=value")`
aliases:
`plot(x1, x2, bk="parameter=value")`  
`plot(x1, x2, backend_keywords="parameter=value, parameter2=value2")`

**Comment by BeastyBlacksmith** [comment]
I think it would make most sense if you were checkout #2200 and see, if you can make it work for pyplot too
