### ISSUE TITLE
Increasing dpi moves colorbar out of position for PyPlot backend

### ISSUE THREAD

**Issue by jacobcook1995** [JuliaPlots/Plots.jl#2198]
Hi, came across some slightly strange behaviour whilst making heatmap plots. Essentially when I increase the dpi using the GR backend e.g.

```julia
gr(dpi=200)
x = collect(1.0:10.0)
y = collect(1.0:10.0)
z = rand(10,10)
heatmap(x,y,z)
```

I get the expected result (a normal heatmap with double the pixels per inch)

![test2](https://user-images.githubusercontent.com/32497818/65255691-3e16c380-daf6-11e9-98f2-fb10b5d102ea.png)

However when I run identical code using the PyPlot backend,

```julia
pyplot(dpi=200)
x = collect(1.0:10.0)
y = collect(1.0:10.0)
z = rand(10,10)
heatmap(x,y,z)
```

The colorbar of the heatmap has now been shifted into the plotting area.

![test2](https://user-images.githubusercontent.com/32497818/65255845-82a25f00-daf6-11e9-9553-c92482be4e6b.png)

I'm guessing that this isn't intended behaviour but I have no idea what is causing this.

As I'm not trying to produce particularly high quality plots at the moment there's an obvious work round of just using the automatic dpi value, but I was wondering if there might be a more sophisticated work around?

**Comment by daschw** [comment]
Thanks for reporting! That's not the intended behaviour.

**Comment by jacobcook1995** [comment]
Managed to get the figure I wanted in the end by increasing the right margin of the plot, i.e. this

```julia
    pyplot(dpi=200)
    x = collect(1.0:10.0)
    y = collect(1.0:10.0)
    z = rand(10,10)
    heatmap(x,y,z,right_margin=20*mm)
```

produced this

![test](https://user-images.githubusercontent.com/32497818/65617553-dad4d780-dfb4-11e9-80a9-cbabb3ca71a0.png)
