### ISSUE TITLE
twinx @ pyplot: Right margin too small

### ISSUE THREAD

**Issue by fbruetting** [JuliaPlots/Plots.jl#2205]
`Julia v1.1.1`
`Plots v0.26.3`

When I add `twinx` on `pyplot`, and give the second y-axis a name, I see this:
![Bildschirmfoto von 2019-10-01 19-30-55](https://user-images.githubusercontent.com/10520767/65985583-67ced380-e482-11e9-9be3-38d040a4e42f.png)

I have to give the right margin an extra 10mm for the graph to look usable. Even better would be an extra 2mm for all sides, so that there is a little space between the contents and the border. Additionally, the spacing between the second y axis and it’s label could use a bit more space.
```
left_margin		=  2mm,
right_margin	= 12mm,
top_margin		=  2mm,
bottom_margin	=  2mm,
```
![Bildschirmfoto von 2019-10-01 19-30-35](https://user-images.githubusercontent.com/10520767/65985702-9cdb2600-e482-11e9-9131-d5a4dfdf9ddb.png)

**Comment by ssfrr** [comment]
This doesn't seem to be specific to pyplots - I see the same thing using GR

**Comment by t-bltg** [comment]
Closed by https://github.com/JuliaPlots/Plots.jl/pull/4488.
