### ISSUE TITLE
legend = :outerright is missing from the documentation

### ISSUE THREAD

**Issue by feanor12** [JuliaPlots/Plots.jl#2207]
The GR backend has implemented an :outer legend position, which is not reflected in the documentation.

**Comment by tzxiong** [comment]
Is there a horizontal alignment of legend entries rather than the default vertical alignment? I want to put it horizontally in the ":outertop" position.

**Comment by feanor12** [comment]
From a quick glimpse at the gr.jl backend file I would say there should be the options: :outertop, : outerbottom, :outerleft and :outerright.
