### ISSUE TITLE
Image is upside down using Plots.plot

### ISSUE THREAD

**Issue by marshalmace** [JuliaPlots/Plots.jl#2212]
hi Guys,
I am trying to use Plots.plot to save images in REPL on ubuntu. However it always save the picture upside down even if I have not do anything on the image yet.
Please help.

versioninfo()
#Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Celeron(R) CPU G3930 @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

```julia
using Plots,Images
backend()
#Plots.GRBackend()
pic=Images.load(“image_orig.png”);
Plots.plot(pic);
Plots.savefig(“myplot_test.png”)
```
#open the picture of myplot_test.png in browser, the pic is upside down

**Comment by t-bltg** [comment]
Not a mwe, and probably just a misunderstanding of how images are represented using julia arrays.
Open a new issue if needed, and with a proper mwe.
