### ISSUE TITLE
GR: Plot does not fill entire window if plotted to existing window with new `size`.

### ISSUE THREAD

**Issue by lassepe** [JuliaPlots/Plots.jl#2213]
When plotting to a previously opened window with a different size, the plot is displayed in the wrong size (aspect ratio correct but does not fill the entire window)

Minimum working example:

```julia
using Plots
gr()

# scaled correctly
plot(rand(10), size=(800,600)) |> display
# aspect ratio correct but scaled to smaller size:
plot(rand(10), size=(600,800)) |> display
```

This does not happen if the `gui` is closed between the two plot commands but it makes plotting very inconvenient.

Screenshot of the output (plot is displayed correctly when saved with `savefig`)

![snapshot-2019-10-10-11-49-12](https://user-images.githubusercontent.com/10076790/66597555-11355980-eb54-11e9-9e00-961bb8a788b9.png)

**Comment by t-bltg** [comment]
Seems fixed.
