### ISSUE TITLE
markers on `sticks` plot drawn behind and in different color

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Plots.jl#2215]
For `sticks` plots with `marker=true` the marker is drawn in a different color than the sticks, and also seems to be drawn behind the sticks. Also the legend doesn't reflect the markers. My expectation was that these would all behave similarly to `plot` when `marker=true`.

MWE:

```julia
using Plots
plot(plot(randn(16), marker=true),
     sticks(randn(16), marker=true),
     layout=(2,1))
```

Which gives:
![image](https://user-images.githubusercontent.com/734386/66622999-d238ef80-ebb7-11e9-834a-0d7b566098f1.png)

**Comment by t-bltg** [comment]
This seems fixed.
