### ISSUE TITLE
push! does not work for plots with more than 1 COLUMNS of entry

### ISSUE THREAD

**Issue by HaoLi111** [JuliaPlots/Plots.jl#2223]
If we have more than 1 columns with plot()
Then it will return something that distinguish the 2 trajectories by col combinations (each column is 1 trajectory).
For example, something like this
![image](https://user-images.githubusercontent.com/32727671/67131797-901c4780-f262-11e9-8b0d-c6f2d571442b.png)

Is it possible,that when making animation, we append 2 trajectories to a previous plot and do something like
```
plot1=plot3d(...)

@animate for i in ...
    push!(plot1,[1 1.5;2 4],[2 3;2 2],[1 1; 4 7])
end

```
for animations such that it give me a synchronized animation of 2 or more trajectories?
BTW I am starting from this https://www.youtube.com/watch?v=hfBcLHke_ss&t=87s
to make something more complicated.

**Comment by HaoLi111** [comment]
https://youtu.be/vOhMHQlqjJk
So that we can speed this up

**Comment by mkborregaard** [comment]
I think there's a `push!` or `append!` method that allows you to specify the series. It's been a while but have a look in the code.

**Comment by HaoLi111** [comment]
> I think there's a `push!` or `append!` method that allows you to specify the series. It's been a while but have a look in the code.

Thanks. Do you mean 
x = [...], y=[...],z=[...]
?

**Comment by HaoLi111** [comment]
Just curious why appending directly(which seems to be a reasonable syntax) do not work. will try specification

**Comment by HaoLi111** [comment]
push!() will does not accept x=,y=,z=...
One possible way to get around:
```
plot1=plot3d([1 1.5;2 4],[2 3;2 2],[1 1; 4 7])

plot!(plot1,x=[3 1.5;2 4],y=[4 3;2 2],z=[7 1; 4 7])

```

If the documentation changed, this could be the solution to append 3D lines. So if this is the desired way(I don't know), plz close the issue
