### ISSUE TITLE
strange plot sizing with PyPlot backend: macOS Catalina

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#2224]
Just switched to Mac Catalina (v 10.15).

Plots that used to create say a 3" x 5" rect on the screen with size (600,400) come out 1/2" by roughly 1/4".  Sizes over 800 seem to render ok though.   Using dpi=300 makes everything look like it used to.  

I note that gr() backend does not have this issue.

This could have to do with all of the backend problems that matplotlib seems to have of late.

I can easily just add the dpi argument though it makes the charts more backend dependent.

Anyone else seen it?  Can I fix by specifying the matplotlib backend?  Not sure how to do this from within Julia.

Thanks,
Lewis

**Comment by daschw** [comment]
>  Can I fix by specifying the matplotlib backend? Not sure how to do this from within Julia.

I have not tested but you could try to set the `MPLBACKEND` environment variable (https://matplotlib.org/3.1.1/faq/environment_variables_faq.html) with `ENV["MPLBACKEND"] = ...` or use `pygui` (https://github.com/JuliaPy/PyPlot.jl#choosing-a-python-gui-toolkit)

**Comment by lewisl** [comment]
Thanks.  That Julia ENV variable is in the PyPlots doc.  I’ll have to figure out which ones to try.

The dpi argument in Plots does very strange things.

**Comment by lewisl** [comment]
Did a bunch of testing. The problem is the way Plots calls PyPlot.  Using ENV[“MPLBACKEND”] and pygui() works with PyPlot. It appears to do nothing when using the pyplot() backend for Plots.  Getting reasonable sized plots from Plots with pyplot() is tough.

For example, plot(1:5,size(600,600) creates a tall skinny plot, not a square.


Plots.plot(1:5,dpi=100):  tiny little horiz. rectangle



Plots.plot(1:5,dpi=200):  inch and a half high by 3” wide



Plots.plot(1:5,dpi=600):   3” by 5” with very thick lines



So, seems like dpi is being misinterpreted. Higher dpi should result in higher density and smaller plots.





size=(400,400):  a reasonably sized square, but with very fine lines and tiny fonts

size=(600,600): plot is 1” wide by 5” tall!





Plots.plot(1:5,size=(800,600)):  plot is wider than it is high and reasonable size.  Seems like one size dimension has to exceed 800 to get reasonable results.



But, Plots.plot(1:5,size(600,400)) goes back to tiny rectangle.



At this point I think the interaction of Plots and pyplot is too unreliable to use.



So, I either will use gr(), which has window interaction programs as the GTK environment cannot be terminated within Julia—the user must close it themselves or I’ll go back to use PyPlot directly.



I think Plots days of virtualizing multiple plotting packages are over as the backends are too diverse and it is too hard for anyone, especially very busy capable volunteers, to keep up with.  Probably makes more sense to focus on doing an awesome job with one backend/plotting package whose author wants to cooperate with Plots as the frontend.



Love the plots API.  It’s a great idea. Gr and pyplot seem quite good.  But, backend virtualization is perhaps unmanageable now.

**Comment by lewisl** [comment]
Does no one else see this problem?  Will it ever be fixed?
<img width="242" alt="Screenshot 2020-02-14 10 29 10" src="https://user-images.githubusercontent.com/1149741/74557673-7be90e00-4f15-11ea-887a-801b41f6b880.png">

To repro:
```
using Plots
pyplot()
plot(1:5)
```

Is it a confirmed decision that Plots will become the defacto API to GR?  Not a bad decision, just a change.  Let us know.

**Comment by lewisl** [comment]
No one ever commented, which was unfortunate.  But, it is fixed.
