### ISSUE TITLE
Inline animations in Jupyter always displays the first animation

### ISSUE THREAD

**Issue by johanbluecreek** [JuliaPlots/Plots.jl#2239]
I have an issue where inline animations in Jupyter does not update the plot. That is, if I take the example from the [Plots docs](https://docs.juliaplots.org/latest/), The Lorenz attractor, and I change code by removing the `every 10` argument, then I get the animation and it is drawn very slowly, not like in the docs. So I add `every 10` back, and I still get the same animation back, the slow one. I can verify that they are different, because the `tmp.gif` saved is different, it plots fast, as in the docs.

I can even take say
```julia
@gif for i=1:10
heatmap(rand(10,10))
end
```
in a separate Cell, and it will still show the Lorenz attractor.

Since the stable version of `Plots.jl` (v0.27.0) has an issue with displaying inline output of `mp4()` I have also reproduced this on the dev branch (464c0271f026e53037c64a30c3dc3b40e0dd1ec3). And the same problem is present for `mp4()` as with `@gif`.

So, summarised:
* Steps to reproduce:
  - Take the example from [Plots docs](https://docs.juliaplots.org/latest/)
  - Change the plotting in any manner or plot a new animation
  - Only the first animation will be displayed
* Julia version: 1.2.0 (stable official binary)
* `Plots.jl` versions: v0.27.0 and devel (464c0271f026e53037c64a30c3dc3b40e0dd1ec3)
* Back-end: GR
* Functions affected: `mp4()` and `@gif`

I could not find this issue already reported.

**Comment by daschw** [comment]
Thanks for reporting! Reloading the browser tab shows the current image. However, I see that this is not a nice workflow. I have no idea how to fix this within Plots. Any suggestions are very welcome.

**Comment by johanbluecreek** [comment]
Thanks for your reply.

> Reloading the browser tab shows the current image. 

Ah, that is a work-around at least. It does present another issue though: If I make two different animations, it is always the last one made before reloading. It seems to make it impossible to have more than one animation in the notebook at once (unless you have one `@gif` and one `mp4()`, that works.).

How does the embedding into the notebook work? Is it the `tmp.gif`/`tmp.mp4` files that gets embedded? Then could it be that it is not updated because it has the same name? Perhaps generating unique file-names would avoid this? I perhaps have the time to check in a few hours. If that works, I guess it creates an unwanted problem of increasingly more `tmp.*` files...

**Comment by johanbluecreek** [comment]
Yeah, it is a problem of the filename. I have a working branch, let me know if you want it and I'll make the PR.

This means that there is a build-up of temporary files. But I have no idea around it right now... Say we stored previous filename in some way so that it can be removed when a new is plotted, then we get into the issue of only having one animation at a time, despite them perhaps being different animations from different cells. That may be alright, as the file is obviously cached in the browser until it is reloaded. But if you reload the notebook, then all the animations would be gone. Let me know what you think.

**Comment by daschw** [comment]
Sounds great, a PR would be awesome!
I'm also not sure about the build-up of temporary files, but I think it's preferable over relying on browser caching.

**Comment by antoine-levitt** [comment]
Thanks for fixing this! I just had this problem and finally found this thread. Regarding the buildup of temp files, @pfitzseb suggested (on Slack) adding `?$(current_time_stamp)` to the HTML link to prevent the browser from caching it. See eg https://stackoverflow.com/questions/728616/disable-cache-for-some-images. This is both cleaner (avoid temporary files) and more general (it also applies when the user does `gif(anim, "file.gif")`.

**Comment by johanbluecreek** [comment]
@antoine-levitt As said in the commit: I find the solution to work and much better than my own solution. I would be in favour of using this solution instead.

**Comment by mkborregaard** [comment]
@antoine-levitt thanks could you please make a PR then?
