### ISSUE TITLE
Interactive Plots

### ISSUE THREAD

**Issue by aminya** [JuliaPlots/Plots.jl#2246]
Does Plots.jl support interactive features of the backends, such as PyPlot, InspectDR, Makie, etc? Nothing is mentioned inside the documentation.

As an example, something that is done inside MusicVisualizations.jl using PyPlot and PyCall:
```julia
axp, axd = plot_piano_drums(piano, drums; grid = nothing, fi = Inf, st = st)
        axp.set_title("$(trio)_$(piece)_$(task) | init_ibi = $(init_ibi)")

        function onclick(event)
            if event.button == 3 # mouse right click
                println("-------------------")
            elseif event.button == 1 # mouse left click
                x,y,xx,yy = event.x, event.y, event.xdata, event.ydata
                println("$(round(Int, xx)),")
            end
        end

        fig = gcf()
        cid = fig.canvas.mpl_connect("button_press_event", onclick)

```

I was wondering if these features are supported? 

https://github.com/JuliaMusic/MusicVisualizations.jl/issues/5

**Comment by isentropic** [comment]
You could use `Interact.jl` to have something similiar. But plots does not receive callbacks from gui yet.

**Comment by t-bltg** [comment]
Some of them support interactivity. Those who do are mentioned in https://docs.juliaplots.org/stable/backends/#At-a-glance.
