### ISSUE TITLE
error compiling _plot!  could not load library "libGR.so" wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by SebastianCallh** [JuliaPlots/Plots.jl#2255]
On Ubuntu 19.4 with Julia from the binaries released on the official web page I get 

`
error compiling _plot!: error compiling _display: could not load library "libGR.so"/home/seba/.julia/packages/GR/f1Iqi/src/../deps/gr/lib/libGR.so: wrong ELF class: ELFCLASS64
`

when I run `using Plots` after having run `import Pkg; Pkg.add("Plots")`.

Please ask if you need more info on this!

**Comment by daschw** [comment]
Try
```
ENV["GRDIR"] = ""
using Pkg; Pkg.build("GR")
```

**Comment by SebastianCallh** [comment]
The commands passed without error, but did not solve the issue

**Comment by daschw** [comment]
Maybe @jheinen can help here.

**Comment by jheinen** [comment]
Could you please check whether all dependencies are installed? For Ubuntu 18.04, pleaser refer to the [installation](https://gr-framework.org/c.html) section:
```
apt install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5
```
The package names should not have changed significantly compared to the LTS Vwersion ...

**Comment by SebastianCallh** [comment]
Thank you for your response! 

I already have those packages installed, unfortunately. I finally decided to circumvent the issue and run Julia in a docker container, which worked out fine.

**Comment by mattiasvillani** [comment]
Had the same problem as in the original issue. The first suggestion by @daschw solved it for me.
I am on Ubuntu Budgie 20.04 using Atom/Juno.

**Comment by idontgetoutmuch** [comment]
I also experienced this problem
