### ISSUE TITLE
Should not depend on Gtk and Cairo

### ISSUE THREAD

**Issue by ghost** [JuliaPlots/Plots.jl#2263]
Although not a real dependency, the tests of Plots depend on Cairo and Gtk. These packages are 200% broken on a Mac, completely fail to build—and I wouldn't really want anything from the G-land polluting my Mac anyway, even if the build didn't fail—so the tests of Plots fail. In particular, PackageCompiler fails (see https://github.com/JuliaLang/PackageCompiler.jl/issues/271#issuecomment-555575818).  Removing all traces of Gtk from `Project.toml` and `test/runtests.jl` make the tests pass (although PackageCompiler still has other issues).

**Comment by daschw** [comment]
If anyone can provide an alternative implementation for visual regression testing of plots (https://github.com/JuliaPlots/VisualRegressionTests.jl) with a gui without Gtk I'm happy to drop the test dependency.

**Comment by vomout** [comment]
Is there any way to make the test-dependencies platform-dependent? It's pointless to do the tests on Mac because they *will* fail due to Cairo/Gtk build issues.
