### ISSUE TITLE
Multiple `-Inf`s in data can cause problems

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Plots.jl#2265]
I think there's something strange going on with `Inf` handling. I was plotting a vector with some `-Inf`s in it and for some reason only the first half of the plot was plotting. I traced it down to a part of the plot with 2 `-Inf`s with one value in between and I'm seeing weird behavior. It seems like everything after the `-Inf`s is wiped out.

MWE:

```julia
plot([1, 2, -Inf, 4, -Inf, 6, 7], legend=false)
```

gives:

![image](https://user-images.githubusercontent.com/734386/69178872-7c216b00-0ad8-11ea-8b7d-4dddc708a19f.png)

It doesn't seem to do that with `NaN`s, so I think maybe something is happening with the recent change to treat `Inf` as `Nan` (#2236).

```julia
plot([1, 2, NaN, 4, NaN, 6, 7], legend=false)
```

gives what I would expect:

![image](https://user-images.githubusercontent.com/734386/69178895-89d6f080-0ad8-11ea-963f-c9eb3931916c.png)

**Comment by daschw** [comment]
Hm, I can't reproduce your MWE on current master.

**Comment by ssfrr** [comment]
OK, cool. Thanks for checking it out!
