### ISSUE TITLE
Set default dpi to 600

### ISSUE THREAD

**Issue by aminya** [JuliaPlots/Plots.jl#2271]
In 2019, with screens being 1080p or even 4K, the default quality of plots should be increased. I believe we should at least set the default dpi to 600.

**Comment by mkborregaard** [comment]
That's not really how it works though. The dpi maps screen pixels to print pixels, and is unrelated to the screen resolution. The size of plots is given in pixels. Do you mean that the default `size` should be larger than 600 x 400?

**Comment by aminya** [comment]
When a plot is generated the quality of the image is affected by `dpi` keyword argument. I am saying that this should be higher.
```julia
plot( x,y.; dpi =600)
```

**Comment by aminya** [comment]
Now I think if we don't specify the dpi parameter it considers it as 300 or worse as 150

**Comment by mkborregaard** [comment]
You can read our discussion of dpi in some of the other open issues here. It is often a good idea to orient in open issues on a topic before opening a new one.

**Comment by daschw** [comment]
You can always set your default dpi by adding `PLOTS_DEFAULTS = Dict(:dpi => 600)` to your julia startup file.
