### ISSUE TITLE
'clim' breaks contour plot with GR backend

### ISSUE THREAD

**Issue by williamwwang** [JuliaPlots/Plots.jl#2293]
The following code gives me a plot:
`contour(1:10, 1:10, (x,y)->x*y, levels=[10.0])`
but adding clims yields an empty plot:
`contour(1:10, 1:10, (x,y)->x*y, levels=[10.0],clim=(0,1))`
The same thing happens when I set levels to be an integer in GR/Plotly, though it does not happen with PyPlot. Is this a known bug?

**Comment by daschw** [comment]
Well, your data values are between `1` and `100` if you limit the values of the colored lines to be below `1`, it is expected that nothing can be plotted.
Try e.g.
```
contour(1:10, 1:10, (x,y)->x*y, levels=5:5:15, clims = (0, 20))
contour(1:10, 1:10, (x,y)->x*y, levels=10, clims = (50, 70))
```

**Comment by williamwwang** [comment]
I see, I think this is just a difference in how the plotting backends work, since PyPlot would set the colors of values outside (0,1) to 0 or 1, like in Matlab (https://www.mathworks.com/help/matlab/ref/caxis.html ). Thanks!
