### ISSUE TITLE
Pyplot backend generates oversized figure in plot pane of Juno

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaPlots/Plots.jl#2297]
I'm using the latest versions of Julia, Plots, PyPlots, Juno, Atom.
Whenever I plot something under the pyplot backend of Plots.jl with Juno, the output graphics size is way too large for the plot pane of Juno/Atom. I tried various options when I ran ```pyplot()```, e.g., ```pyplot(size=(800,600))```, ```pyplot(dpi=250)```, etc., but nothing has really worked so far.
Then, when I further ran ```using PyPlot``` followed by ```gcf()```, the previous huge graphics is nicely resized at least in my Mac. On the window machine, if I do the same, the previous huge graphics is resized to a tiny size within the plot pane. So, something is wrong here! I would greatly appreciate it if someone could look into this problem. Thanks!

**Comment by BoundaryValueProblems** [comment]
I just want to update this. The situation is the same under Windows 10 machine. All these oversized plots rendered by Plots.jl with pypot backend can be corrected if I run ```using PyPlot``` then ```gcf()```. It would be great if someone can correct this behavior by adding ```gcf()``` explicitly somewhere, perhaps, ```src/backends/pyplot.jl```, which has the following segment:
```
# Create the window/figure for this backend.
function _create_backend_figure(plt::Plot{PyPlotBackend})
    w,h = map(px2inch, Tuple(s * plt[:dpi] / Plots.DPI for s in plt[:size]))

    # # reuse the current figure?
    fig = if plt[:overwrite_figure]
        PyPlot.gcf()
    else
        fig = PyPlot.figure()
        # finalizer(fig, close)
        fig
    end

    # clear the figure
    # PyPlot.clf()
    fig
end
```
But I'm not sure which line I should add ```gcf()```. Perhaps, @daschw or @mkborregaard may know?

**Comment by BoundaryValueProblems** [comment]
@pfitzseb the pyplot backend of Plots.jl has been in the above status for a while. I also found what you wrote in the forum: https://discourse.julialang.org/t/juno-pyplot-doesnt-fit-plots-window/31938
I would greatly appreciate it if you could take a look at this problem. Currently, it is cumbersome to use pyplot backend of Plots.jl under Juno/Atom.

**Comment by pfitzseb** [comment]
What happens if you define
```
Base.showable(::MIME"application/prs.juno.plotpane+html", plt::Plots.Plot) = false
```
I *think* that should work around the issue.

Right now every Plots plot is shown as (what Juno thinks) is HTML (usually just an embedded HTML) because of the original
```
Base.showable(::MIME"application/prs.juno.plotpane+html", plt::Plots.Plot) = showable(MIME"text/html"(), plt)
```
definition. The automatic rescaling doesn't kick in in that case.

**Comment by BoundaryValueProblems** [comment]
@pfitzseb Thanks! For pyplot backend, 
```
Base.showable(::MIME"application/prs.juno.plotpane+html", plt::Plots.Plot) = false
```
works, and it displays figures with correct scale in the Juno plot pane. However, if I keep that state for plotlyjs backend, its interactive panel is gone, and I have to switch back to
```
Base.showable(::MIME"application/prs.juno.plotpane+html", plt::Plots.Plot) = true
```
So, I hope there will be a better solution of this problem.

**Comment by pfitzseb** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/2381 fixes this exact issue :)

**Comment by daschw** [comment]
Thanks @pfitzseb !

**Comment by BoundaryValueProblems** [comment]
Yes, thanks a lot, @pfitzseb, indeed!! All these three common Plots backends work comfortably under Juno/Atom!!

**Comment by BoundaryValueProblems** [comment]
@pfitzseb : After I updated Plots.jl to v0.28.4, this oversized pyplot problem reoccurred!! Could you check what happened?
