### ISSUE TITLE
colorbar ticks

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaPlots/Plots.jl#2308]
I can't find which attribute controls the colorbar ticks. Is there something like `cticks` or `zticks`?

**Comment by daschw** [comment]
No, there is no attribute for controlling the colorbar ticks.

**Comment by etaMet** [comment]
It would be phenomenal to have a handle on the colorbar ticks. Especially for their spacing and their labeling.
Its nice that the `colorgradient` scales. It would be amazing if the labels could be adjusted. 
My use case would be a `heatmap` with 8 order of magnitude on the colorbar.
I am not quite enough in the matter to be able to contribute much with out tight guiding.

**Comment by jamblejoe** [comment]
This would be a great feature!

**Comment by hervasa2** [comment]
I think this feature is really necessary. I was trying to change the tick labels as a workaround for cscale=:log10 not being supported

**Comment by isentropic** [comment]
closed in favor of https://github.com/JuliaPlots/Plots.jl/issues/3174
