### ISSUE TITLE
Extra blank space in engineering notation

### ISSUE THREAD

**Issue by miguelfm** [JuliaPlots/Plots.jl#2316]
Extra blank space appear in tick labels in engineering notation. For instance:
```
using Plots
using Formatting
gr()
x=[0.001,0.1,1]; y=x

scatter(x,y,
    xaxis=:log10,
    xformatter=x->sprintf1("%1.0e",x),
    yformatter=y->sprintf1("%1.0e",y))
```
The y axis format seems to be fine while in the x axis (logarithmic one) an extra blank space appears after "e-". It seems to happen just in the negative exponents only on logarithmic scales.

**Comment by miguelfm** [comment]
Seems to works escaping the "-" . 
```
 if occursin("GR",string(backend()))
     s=replace(s, "-"=>"\\-") # Needed to Escape "-" in GR
 end
```
Is there any easy way to add this to the Plots source code?

**Comment by daschw** [comment]
Thanks for reporting! I proposed a different fix in #2317.

**Comment by miguelfm** [comment]
I'll wait for this to get to the main branch then. Thank you very much!

**Comment by daschw** [comment]
```julia
using Plots, Formatting
x = y = [0.001, 0.1, 1]
scatter(x, y,
    xaxis = :log10,
    xformatter = x -> sprintf1("%1.0e", x),
    yformatter = y -> sprintf1("%1.0e", y),
    xtickfont = 15,
)
```
on master:
![xticks_master](https://user-images.githubusercontent.com/16589944/70604001-14060680-1bf8-11ea-8e19-40f05a01ad89.png)

with this change:
![xticks_fix](https://user-images.githubusercontent.com/16589944/70604023-1cf6d800-1bf8-11ea-92ed-04712ba095f3.png)
