### ISSUE TITLE
pdf, eps, etc. convenience functions not exported

### ISSUE THREAD

**Issue by jiahao** [JuliaPlots/Plots.jl#2319]
The documentation states that

>  Plots offers shorthands like `png(fn)`, etc.

However, it appears that `png()` is the only convenience function that is [exported](https://github.com/JuliaPlots/Plots.jl/blob/2245e572aaf2370224d0f00e78eb156b592eecec/src/Plots.jl#L80), which is confusing for users trying to do `pdf(fn)`.

I assume the intention is to export these functions? If not, having to type `Plots.pdf("plot")` isn't going to save that much over `savefig("plot.pdf")`. But if exported, functions like `pdf()` will clash hard with similarly named functions like `Distributions.pdf`. At any rate, the documentation is not quite consistent with the exported API.

**Comment by mkborregaard** [comment]
Yes, the docs need to be updated, we can't defend exporting `pdf`.

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/PlotDocs.jl/commit/b2b6ca80cb7d19f23b44bda148bcaf6242cb78c2.
