### ISSUE TITLE
Extra space in exponent - GR backend

### ISSUE THREAD

**Issue by miguelfm** [JuliaPlots/Plots.jl#2321]
The value in the exponent for the GR backend is to far away from the base (10). Instead of "1x10^8", "1x10^ 8" is displayed
Is easy to see in this example. Compare the output for the GR backend to the other backends or any other plot tool. Using the GR backend the exponent look almost as a separated number.
```
using Plots
gr() #pyplot() #plotly()
x = y = [1e8, 5e8, 1e9]
scatter(x, y,
    xtickfont = 12,ytickfont = 12)
```
GR backend:
![test](https://user-images.githubusercontent.com/127155/70618822-09f20100-1c14-11ea-95ef-02bee30c231e.png)
Pyplot:
![test_pyplot](https://user-images.githubusercontent.com/127155/70618938-3dcd2680-1c14-11ea-8645-21ba810f92cc.png)
Plotly:
![test_plotly](https://user-images.githubusercontent.com/127155/70619056-8389ef00-1c14-11ea-9c38-b6c8129b2e83.png)

**Comment by BeastyBlacksmith** [comment]
I can't reproduce, please reopen if still present
