### ISSUE TITLE
Some recent update in Plots.jl is causing tests to fail

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#2324]
Many tests on my packages are failing because of some recent update. Basically, the marker is too strong somehow covering the marker color:

![image](https://user-images.githubusercontent.com/3345261/70759501-5b3de580-1d25-11ea-9bf5-4217c491ae5f.png)

The docs are also showing this behavior: https://juliohm.github.io/GeoStats.jl/stable/userguide/#Plotting-solutions-1

Can you please confirm that something changed? Is there a way to be alerted of these breaking changes? An example recipe that I am using: https://github.com/juliohm/GeoStatsBase.jl/blob/master/src/plotrecipes/domains/point_set.jl#L16

**Comment by mkborregaard** [comment]
This could also be a change in GR perhaps?

**Comment by daschw** [comment]
I hope so, I would not now what change in Plots could have caused this. Also, I cannot reproduce the issue. @juliohm for which versions of Plots and GR does this happen?

**Comment by mkborregaard** [comment]
In terms of warning for breaking changes - no, that's a general issue of the ecosystem (https://github.com/JuliaRegistries/RegistryCI.jl/issues/120). That's why Pkg automatically upper bounds packages, but imho not an ideal solution.

**Comment by juliohm** [comment]
Thank you.

Plots v0.28.3
GR v0.44.0
