### ISSUE TITLE
Is it possible to change the order in a violin plot?

### ISSUE THREAD

**Issue by bhvieira** [JuliaPlots/Plots.jl#2331]
MWE:

    violin(repeat(["c", "b", "a"], 10), 1:30)

The order, when you plot that, is actually "abc", not "cba". Can we change that order? I couldn't find an attribute to do that.

**Comment by josephmarturano** [comment]
Are you looking for the attribute `xdiscrete_values`?

`violin(repeat(["c", "b", "a"], 10), 1:30, xdiscrete_values=["c", "b", "a"])`

**Comment by bhvieira** [comment]
Yeah, that's it @josephmarturano , thanks for the help! BTW sorry for posting this here, should've posted it on StatsPlots issue tracker, my mistake.
