### ISSUE TITLE
Package clash Plotly and Plots (Julia 1.2.0)

### ISSUE THREAD

**Issue by crash-crush** [JuliaPlots/Plots.jl#2334]
Hello,

while experiencing different graphic packages I stumbled sometimes into kind of warning. Now I tried to produce it directly. Its a warning dependent on the order of using/importing packages.

Another failure is with two plot identifiers than the shown below with heatmap.

```
using PlotlyJS

julia> using Plotly

julia> using Plots

julia> plot(heatmap(z=rand(100,100)))
WARNING: both Plots and Plotly export "heatmap"; uses of it in module Main must be qualified
ERROR: UndefVarError: heatmap not defined
Stacktrace:
 [1] top-level scope at REPL[4]:1

julia> Plotly.plot(heatmap(z=rand(100,100)))
ERROR: UndefVarError: heatmap not defined
Stacktrace:
 [1] top-level scope at REPL[5]:1
```

How to avoid instead of just using one package ?
Thanks.

**Comment by BeastyBlacksmith** [comment]
First of all I would recommend using the plotly backend of Plots like
```julia
using Plots; plotly()
```
To answer your question. If you load both packages you have to qualify each ambigous call e.g.
```julia
Plotly.plot(Plotly.heatmap(z=rand(100,100)))
```
should work.

**Comment by BeastyBlacksmith** [comment]
please reopen, if it isn't solved.

**Comment by vak** [comment]
please re-open

**Comment by BeastyBlacksmith** [comment]
Can you provide a bit more context? When its about the warning in the OP. That is expected behaviour (of julia in general) and I answered above how to resolve those conflicts.

**Comment by vak** [comment]
please ignore my comment, I got it working with explicitly qualified calls. sorry.
