### ISSUE TITLE
How to generate graphics output in for loop with different backends (gr())

### ISSUE THREAD

**Issue by crash-crush** [JuliaPlots/Plots.jl#2335]
Hello, 

I am trying to generate a runtime graphic.
While the following code runs pretty fast. There is no update to the existing plot?
How could it be fixed:

Here my minimal example:

```
p=heatmap(rand(100,100), aspect_ratio=1)
function loopinglouie1(max_count,n,old_plot)
for x=1:max_count
    
       heatmap!(old_plot,rand(100,100))
       if x==n*50
       m=String(chomp(readline()))
       n=n+1;
       end
end
end
loopinglouie1(200,1,p)
```

Thanks in advance.'
PS: Wrapped into a function to undergo the scope, just a try...

**Comment by BeastyBlacksmith** [comment]
You need to return the plot from your function. So add `return old_plot` before ending the function.

**Comment by BeastyBlacksmith** [comment]
And if you want to display each loop, you need a `display(old_plot)` inside the loop.

**Comment by BeastyBlacksmith** [comment]
If still unclear, please reopen.
