### ISSUE TITLE
Manipulating tick marks using pyplot() without corresponding Plots.jl attributes

### ISSUE THREAD

**Issue by xorJane** [JuliaPlots/Plots.jl#2336]
Per both the `Plots.jl` documentation and some discussion on [Discourse](https://discourse.julialang.org/t/plot-ticks-at-both-top-and-bottom-axis/9550)/[Github](https://github.com/JuliaPlots/Plots.jl/issues/337), it looks like there's not currently a way to add tick marks simultaneously to the top, bottom, left, and right axes (though the `mirror` attribute supports switching between left/bottom tick marks and right/top tick marks).

Since adding tick marks to all sides can be done using `matplotlib` and `PyPlot.jl`, I'm hoping there is a way to do this manually in `Plots.jl` using the `pyplot` backend. To do this, I think I'd need to update the `rcParams` dictionary implemented in `matplotlib`.

With `PyPlot.jl`, the necessary change should look something like

```
rc = PyPlot.matplotlib.rcParams
rc["xtick.top"] = true
rc["xtick.left"] = true
```

However, this isn't working to update my plot using `Plots.jl`. A MWE of what I'm trying is

```
using Plots 
pyplot()
myfig = plot(x -> x, 1:10, framestyle = true, legend = false)
rc = PyPlot.matplotlib.rcParams
rc["xtick.top"] = true
rc["xtick.left"] = true
myfig
```

where I still see tick marks only on the bottom and left axes. Any ideas how to properly access/update `rcParams` using `Plots.jl`, or any other way to add tick marks to all four sides of the frame?

Thank you!

**Comment by isentropic** [comment]
with https://github.com/JuliaPlots/Plots.jl/pull/2858 you could axes the internal RC file and tweak it.
The parameter is `Plots.pyrcparams`

**Comment by isentropic** [comment]
use framestyle=:box
