### ISSUE TITLE
Inbuild decorators for Latex formatted scientific notation

### ISSUE THREAD

**Issue by isentropic** [JuliaPlots/Plots.jl#2342]
Related stuff: #1858 #2042 #2147 

In [this](https://discourse.julialang.org/t/tips-to-create-beautiful-publication-quality-plots/32384/16) discussion, in [this](https://discourse.julialang.org/t/tips-to-create-beautiful-publication-quality-plots/32384/16?u=isentropic) particular post by leandromartinez98, he made a nice way of incorporating latex formatted strings into axis ticks. Could we perhaps have this functionality build in? He has also written the function, which should help

**Comment by benide** [comment]
As I mentioned in one of the issues you linked (#2147), this can be achieved with the PyPlot backend and the formatter I added (#2195). If you add `text.usetex : True` to your `matplotlibrc`, then plot with `formatter = :latex`, you should get the results you're asking for. This is what I'm personally using in my work.

I'm not really a developer, so I probably don't have the skills to help more than this, but I wanted to make sure you were aware that this method exists. It looks far simpler to me than the one from leandromartinez98.

**Comment by isentropic** [comment]
I was meant to say that this should not be limited to pyplot. It should work seamlessly across the board.
