### ISSUE TITLE
Add alias `xrange` for `xlims`

### ISSUE THREAD

**Issue by yuxiliu1995** [JuliaPlots/Plots.jl#2343]
I suggest that `xrange` be an alias for `xlims`, similarly for `yrange`.

**Comment by daschw** [comment]
I think we can add this alias. Do you want to make a PR yourself? The relevant lines of code are https://github.com/JuliaPlots/Plots.jl/blob/master/src/args.jl#L558, https://github.com/JuliaPlots/Plots.jl/blob/master/src/args.jl#L562 and https://github.com/JuliaPlots/Plots.jl/blob/master/src/args.jl#L566.
