### ISSUE TITLE
abnormal behavior when plots really big value with small limits

### ISSUE THREAD

**Issue by zhanglix** [JuliaPlots/Plots.jl#2344]
I need to plot curve with extraordinary large y at some x position.  When I plotted the curve the ylims option to ignore those large position, I got  nothing but axis and label.

```julia
x = 0.:0.1:5.
plot(x, x->exp(exp(x))) # this plots is normal but distorted.
plot(x, x->exp(exp(x)),  ylims=(0., exp(exp(2.1)))) # nothing but the axis is plotted
plot(x, x-> exp(exp(x)) > exp(exp(2.1)) ? exp(exp(2.1)) + 10 : exp(exp(x)) ,  ylims=(0., exp(exp(2.1)))) #this is a workaround 

```

I guess there is something wrong with the way rounding values of y when ylims is involved and the limits is too small compared to max value of y.

**Comment by daschw** [comment]
For me the last two commands above produce the same plot
![ylims](https://user-images.githubusercontent.com/16589944/71885497-c0c19e00-313a-11ea-9c34-7dd8350a5de1.png)
and it looks fine to me. What version of Plots and Julia are you on?

**Comment by zhanglix** [comment]
Sorry for the delay.

I tried it just now at juliabox.com just now. And the issue cab be reproduced with Julia 1.3.1
```lang=juia
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIABOX = true
  JULIA_PKG_SERVER = https://pkg.juliacomputing.com
  JULIA_KERNELS = ['julia-0.6', 'julia-1.0', 'julia-1.0k', 'julia-1.3', 'julia-1.3k']
  JULIA_PKG_SERVER_HOST = pkg.juliacomputing.com
  JULIA = /opt/julia-0.6/bin/julia
  JULIA_PKG_TOKEN_PATH = /mnt/juliabox/.julia/token.toml
  JULIABOX_ROLE = 
  JULIA_NUM_THREADS = 4
```
The output:
![Plots_Issue](https://user-images.githubusercontent.com/8109462/82445702-e04cd800-9ad7-11ea-9a29-c4e5d7110e6b.png)
