### ISSUE TITLE
control the size of colorbars?

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaPlots/Plots.jl#2345]
the widths of my color bars are too large. Is there a way to make them thinner? Or control the relative width to the plot region? When I put multiple plots together the relative widths of color bars also become even larger. Is there a way to fix this ratio in subplots?

**Comment by daschw** [comment]
There is no plot attribute that controls the colorbar width. Especially for the GR backend the automatical positioning and sizing of plot area, colorbars, ticks, axes guides, legends, etc. could be significantly improved, but it's a tricky issue. Any help is welcome and very much appreciated.

**Comment by isentropic** [comment]
@daschw is there a way we could get a `colorbarpadding` and `colorbarwidth` arguments available? pyplot can really use these arguments for optional user colorbar tweaking.

I believe `colorbarpadding` is especially useful as it is hard to determine the right spacing when comes to the 3d plots. Colorbar might overlap with zguidelabel. And it fairly common

**Comment by Gyoshi** [comment]
Since I couldn't find a workaround for sizing the colorbar anywhere else, [here is a hack](https://discourse.julialang.org/t/plots-jl-shared-colorbar-with-subplots/47269/7?u=gyoshi) for adjusting the size/position of a colorbar that works by adjusting the bbox of an invisible inset subplot.

**Comment by t-bltg** [comment]
Fixed by the undocumented `Plots.gr_cbar_width[] = 0.01`.
