### ISSUE TITLE
I was downgraded to 0.27.1 when GR was updated to 0.46

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPlots/Plots.jl#2375]
on 28 Jan 2020, Julia 1.3.1 and 1.4.0-rc1 (on several Win 10 machines)

**Comment by BeastyBlacksmith** [comment]
There was a compatibility issue, please try `Plots#master` or `GR@0.45`.

**Comment by mkborregaard** [comment]
0.46 should work on master yes.

**Comment by PaulSoderlind** [comment]
Thanks.
