### ISSUE TITLE
Error when using 1d title array for plot with subplots

### ISSUE THREAD

**Issue by yanivabir** [JuliaPlots/Plots.jl#2376]
Looking at the layouts example from the docs, this works:

```
l = @layout [  a{0.3w} [grid(3,3)
                         b{0.2h} ]]
plot(
    rand(10,11),
    layout = l, legend = false, seriestype = [:bar :scatter :path],
    title = ["($i)" for j = 1:1, i=1:11], titleloc = :right, titlefont = font(8)
)
```

but giving a 1D array of titles fails:

```
title =  ["($i)" for i=1:11]
```

```
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: MethodError: no method matching occursin(::String, ::Array{String,1})
```

Why is this? What should the dimensions of the title array be, and why can't they be 1D?

Julia 1.2.0
Plots.jl 0.27.1
backend GR

**Comment by mkborregaard** [comment]
Like almost everything in Plots (and indeed the  example above), it goes that **columns are series**. Adding something like a 1-d array implies different semantics, i.e. not one where each value should apply to an individual series (in this case the series are subplots).
