### ISSUE TITLE
legend=:right does not show up in some plots in multiple plot layout

### ISSUE THREAD

**Issue by leandromartinez98** [JuliaPlots/Plots.jl#2377]
```
x = rand(10); y = rand(10);
plot(layout=(2,1))
plot!(x,y,legend=:right,subplot=1)
plot!(x,y,legend=:right,subplot=2)
```

Results in:

![image](https://user-images.githubusercontent.com/31046348/73610075-7bb24f80-45b2-11ea-89de-3aabdf9fd3af.png)

That is, the legend does not appear in the first plot.

The same problem occurs with `:left`, but not with the other options, as `:bottomright`, `:bottomleft`, etc. For those, the legends appear as expected.

**Comment by daschw** [comment]
Thanks for reporting! Also related: https://github.com/JuliaPlots/Plots.jl/issues/2369
