### ISSUE TITLE
Error Bars Throws Error

### ISSUE THREAD

**Issue by caseykneale** [JuliaPlots/Plots.jl#2389]
is plots jl's error bar implementation broken or has it changed and I can't find documentation for it?
found some old code from 2017(risky I know)
scatter(rand(10), yerror = abs.(randn(10)./4), ms = 6)
from: https://github.com/JuliaPlots/ExamplePlots.jl/blob/master/notebooks/errorbars.ipynb
that is throwing an error:

```
MethodError: no method matching error_style!(::Plots.Attr)
Closest candidates are:
  error_style!(!Matched::Dict{Symbol,Any})
```

It was suggested by @asinghvi17  that this may be fixed by the following PR: https://github.com/JuliaPlots/Plots.jl/pull/2388/
But I have not confirmed this.

**Comment by mkborregaard** [comment]
I think this could be the same issue as https://github.com/JuliaPlots/GraphRecipes.jl/issues/93

**Comment by daschw** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/2388 should fix this.

**Comment by caseykneale** [comment]
Fixed! Thanks!!!!
