### ISSUE TITLE
Feature request: Grid/Ticks/Axis in front of data

### ISSUE THREAD

**Issue by rjdverbeek-tud** [JuliaPlots/Plots.jl#2397]
A filled polygon will always plot in front of the grid/ticks/axis. Due to this the grid/ticks/axis will disappear. Even if you don't want that. I can't find any options to indicate that the grid/ticks/axis must be plotted in front of the data.

Feature request: user option to allow grid/ticks/axis be plotted in front of the data

![grid_not_on_foreground](https://user-images.githubusercontent.com/54448042/74274895-280ed700-4d13-11ea-81e4-2e73957ea024.png)

**Comment by mkborregaard** [comment]
Completely unrelated, but do we support plotting polygons with holes now? :-O

**Comment by rjdverbeek-tud** [comment]
These are two separate shape files plotted on top of each other. So this is not a polygon with holes. It just looks like that.

**Comment by rjdverbeek-tud** [comment]
As I realized that this is really an issue with how the GR framework has implemented this, I am closing this issue for now. I have moved the issue to https://github.com/sciapp/gr/issues/103 .
