### ISSUE TITLE
Copy plot

### ISSUE THREAD

**Issue by Wikunia** [JuliaPlots/Plots.jl#2401]
It would be nice to be able to copy a plot such that the copied plot doesn't get modified if the base plot changes. It works with `deepcopy` but maybe that is slower?
`copy(plot())` seemed to worked before #67 but doesn't anymore.

The complete process and error:
```
julia> using Plots
julia> plt = plot()
julia> copy(plt)
ERROR: MethodError: no method matching copy(::Plots.Plot{Plots.GRBackend})
Closest candidates are:
  copy(::Expr) at expr.jl:36
  copy(::Core.CodeInfo) at expr.jl:64
  copy(::BitSet) at bitset.jl:46
  ...
Stacktrace:
 [1] top-level scope at REPL[4]:1
```

**Comment by mkborregaard** [comment]
Deepcopy wouldn't be slower no.

**Comment by BeastyBlacksmith** [comment]
This is not working with `copy` or `deepcopy`?
You should use `deepcopy`
