### ISSUE TITLE
do I get 0.29.1 or 0.28.4?

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPlots/Plots.jl#2406]
(on Julia 1.3.1, Win 10).

If I install DSP and then Plots, then I get 0.28.4. Instead, with the reverse order I end up with 0.29.1. 

(Earlier experimenting suggested that this was related to some sort of conflict between RecipesBase and Polynomials.)

**Comment by daschw** [comment]
That's hopefully fixed by https://github.com/JuliaMath/Polynomials.jl/pull/192.
