### ISSUE TITLE
display() is not defined warning

### ISSUE THREAD

**Issue by nblomberg** [JuliaPlots/Plots.jl#2407]
While using backend PyPlot you get warning on the first run "_display is not defined for this backend." when pyplot() is inside a function. I don't know if this how it is intended to work, but at least the warning could be more helpful.  I have no idea why it has problems with display in particular? 

```
using Plots

function main()
    pyplot()
    a = plot(1:10,1:10)
    display(a)
end
main()
```

This works fine if pyplot() is outside of main().

**Comment by BeastyBlacksmith** [comment]
Note that the following works
```julia
using Plots

function main()
    pyplot()
    plot(1:10,1:10)
end
p = main()
display(p)
```
But you need to return to the toplevel between a backend switch and the display, since the backend initialization is in a different world age otherwise

**Comment by BeastyBlacksmith** [comment]
A second option is to use `Base.invokelatest`
```julia
using Plots

function main()
    pyplot()
    p = plot(1:10,1:10)
    Base.invokelatest(display, p)
end
```
