### ISSUE TITLE
Axes labels are cropped when rendering the figures using github workflows

### ISSUE THREAD

**Issue by tpoisot** [JuliaPlots/Plots.jl#2422]
This might be an edge case, but I suspect it will be increasingly common, so here goes: I use github workflows to render pages including figures fairly frequently, and in all cases, the output of plot is cropped - specifically, the axes labels are incomplete.

See for example the plot in this section: https://poisotlab.github.io/AnalysisOfEcologicalNetworks/chapters/01_counting_things.html#link-species-relationships

Is there a way to fix that without needing to specifiy figure size for every figure?

**Comment by mkborregaard** [comment]
This seems to be a recurrent Documenter issue to do with plot sizes. Did you explicitly set the plot size to something?

**Comment by tpoisot** [comment]
Nope - I also am not using Documenter (I'm using Weave + jekyll)

**Comment by mkborregaard** [comment]
Hm - if you just `savefig("myimage.png")` do you get the cropping as well?
