### ISSUE TITLE
GR scatter points with mismatched markerstroke

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#2425]
Was there some recent change to GR or is my system acting up?
```julia
gr(); scatter(1:10)
```
<img width="589" alt="Screenshot 2020-02-29 at 14 16 53" src="https://user-images.githubusercontent.com/8429802/75608281-67ed0100-5afe-11ea-97d7-b89dddebe303.png">
Check the weird points.

```julia
(@v1.4) pkg> st GR Plots
Status `~/.julia/environments/v1.4/Project.toml`
  [28b8d3ca] GR v0.47.0
  [91a5bcdd] Plots v0.27.1
```

I actually don't know what's holding back my Plots version... But could it be a version mismatch?
@jheinen

**Comment by jheinen** [comment]
GR now supports `setbordercolorind` and `setborderwidth`, which affects marker symbols, rectangles and arcs. For symbols, this means, that it is no longer required (in the `Plots/GR` backend) to draw symbols twice (with different sizes/colors).

**Comment by jheinen** [comment]
But I have no idea, why you get this result!?
<img width="712" alt="Screen Shot 2020-02-29 at 15 15 32" src="https://user-images.githubusercontent.com/5718244/75609138-658ea500-5b06-11ea-92e4-9d0521c57bb2.png">
```
(v1.3) pkg> st Plots
    Status `/usr/local/lib/julia/environments/v1.3/Project.toml`
  [53c48c17] FixedPointNumbers v0.6.1
  [28b8d3ca] GR v0.47.0
  [77ba4419] NaNMath v0.3.3
  [ccf2f8ad] PlotThemes v1.0.1
  [995b91a9] PlotUtils v0.6.3 #master (https://github.com/JuliaPlots/PlotUtils.jl.git)
  [91a5bcdd] Plots v0.29.3
  [3cdcf5f2] RecipesBase v0.8.0
  [992d4aef] Showoff v0.3.1
  [2913bbd2] StatsBase v0.32.1
```

**Comment by daschw** [comment]
I can't reproduce with Plots 0.29.3

**Comment by mkborregaard** [comment]
That's awesome news @jheinen this means we can have hollow points now?
That means it's a version mismatch - is there something wrong in the dep versions for Plots 0.27?
