### ISSUE TITLE
Contour labels are erased by axis flipping

### ISSUE THREAD

**Issue by mrkrause** [JuliaPlots/Plots.jl#2430]
When using the GR Backend, contour labels are correctly plotted until the axes are flipped. Other axis manipulation (e.g., changing the plot limits, either in the call or via xlims!) seem to leave the labels intact.

Here is an example, generated with Plots v0.28.4, GR v0.44.90, and Julia 1.2.0 (via JuliaPro)

Expected output is that the lower-left and upper-right plots have *some* contour labels, even if they're not always in exactly the same position. However, they are completely missing instead. 
![contour_bug_PlotsGR](https://user-images.githubusercontent.com/3977675/75697899-bd9ae800-5c7b-11ea-9994-d5f58aad5f1f.png)

```julia
# Bivariate normal as an example
x = -7:0.05:7
y = x'
z = Matrix{Float64}(undef, length(x), length(y))
@. z = exp(-(x^2 + y^2/6))
levels = [0.0001, 0.01, 0.1]

import Plots
Plots.backend() # GR.backend
p1 = Plots.contour(x,y',z; levels=levels, contour_labels=true, title="No flip")
p2 = Plots.contour(x,y',z; levels=levels, contour_labels=true, title="xflip in call", xflip=true)
p3 = Plots.contour(x,y',z; levels=levels, contour_labels=true, title="Flipped afterward with xflip!")
Plots.xflip!(p3)
p4 = Plots.contour(x,y',z; levels=levels, contour_labels=true, ylims=(-5,5), title="Other axis manipulation")
Plots.xlims!(p4, -8,8)

Plots.plot(p1, p2, p3, p4)
Plots.savefig("/tmp/contour_bug_PlotsGR.png") #Uploaded above
```

I have not tried this with other backends, since it doesn't run with PyPlot (See #2201 )

**Comment by mrkrause** [comment]
The same problem occurs when using GRUtils.jl, another GR wrapper, as shown here: 
![contour_bug_GRUtils](https://user-images.githubusercontent.com/3977675/75709942-a961e580-5c91-11ea-9c10-18c2963c512c.png)

```julia
import GRUtils
f = GRUtils.subplot(1,3,1)
GRUtils.contour(x,y,z, levels=6, majorlevels=3, title="Normal axes")

f= GRUtils.subplot(1,3,2)
GRUtils.contour(x,y,z; levels=6, majorlevels=3, xflip=true, title="xflip in call")

f = GRUtils.subplot(1,3,3)
GRUtils.contour(x,y,z, levels=6, majorlevels=3, title="Flipped afterward")
GRUtils.xflip(true)
```

Consequently, the problem may be upstream in GR framework itself. I'll try to replicate it by calling the C API directly and if so, I'll fill a bug upstream.

**Comment by mkborregaard** [comment]
Great - yes that sounds like it may be upstream

**Comment by daschw** [comment]
cc: @jheinen

**Comment by jheinen** [comment]
The problem has been fixed in GR master. You will have to `ENV["GRDIR"] = ""; ] build GR` to download the latest run-time.

**Comment by mrkrause** [comment]
Here's what I get with Plots.GR.version = "0.47.2.post20", which is perfect. Thanks for sorting that out! 

![contour_bug_PlotsGR](https://user-images.githubusercontent.com/3977675/76113595-70d44b80-5fb2-11ea-82bf-2eb60059a03d.png)

Have a nice weekend!
