### ISSUE TITLE
Erroneous legend line-properties with pgfplotsx()

### ISSUE THREAD

**Issue by korsbo** [JuliaPlots/Plots.jl#2432]
With the pgfplotsx backend, the legend gets messed up when one includes a non-labeled series.

```julia
julia> plot(rand(10,3), label=["1" "" "3"], color=["blue" "red" "green"])
```

Here, the third line, "3", is green, but the legend uses the line properties of the second line and thus calls it red. 

The pgfplotsx backend still has a bunch of bugs, but I do like it and think it will be great when those are ironed out. Thanks and keep up the good work!

**Comment by BeastyBlacksmith** [comment]
Thanks for reporting. And don't hesitate to tell me other bugs, when you find them.

**Comment by korsbo** [comment]
Thanks! :slightly_smiling_face:

**Comment by korsbo** [comment]
Thanks for responding so quickly but the fix did not work for everything. 

```julia
plot(rand(4,4), label=["a" "" "" "c"]);
vline!([1,1]);
plot!(rand(4,1), label="red?", color=:red)
```
The first plot command is now fine, but the last one yields a red line with a non-red legend entry. 

Since I can't re-open the issue I'll take the liberty of pinging  @BeastyBlacksmith

**Comment by BeastyBlacksmith** [comment]
Note that reordering of the commands produces the correct result, so probably a bug in `vline`
```julia
plot(rand(4,4), label=["a" "" "" "c"]);
plot!(rand(4,1), label="red?", color=:red);
vline!([1,1]);
```

**Comment by korsbo** [comment]
I'm not sure where the bug is, but also note:

```julia
plot(rand(4,4), label=["a" "" "" "c"]);
vline!([1,1,1]);
plot!(rand(4,4), label="red?", color=:red)
```

here, the two last red lines are correct but the first two are not.

**Comment by korsbo** [comment]
`vline!([1,1,1])` produces three lines but only one legend entry. The indexing following this command might be a little off.

**Comment by BeastyBlacksmith** [comment]
actually `vline` shouldn't create any legend entries

**Comment by korsbo** [comment]
and yet it does. Also, I don't care about what the default is, but I would prefer if I had the option of creating a legend entry for a `vline`.

**Comment by BeastyBlacksmith** [comment]
Would be nice, if you could try the branch of https://github.com/JuliaPlots/Plots.jl/pull/2449 and report, if it fixes your cases as well.
