### ISSUE TITLE
markerstrokealpha is not applied on the scatter points (pyplot)

### ISSUE THREAD

**Issue by HendMahmoud** [JuliaPlots/Plots.jl#2447]
I'm using `pyplot()` and setted this parameters while calling scatter function `markerstrokealpha = 0`. It is handled in the legend box but not in the scatter points in the plot!
```
using Plots; pyplot()
scatter(x, y, markerstrokealpha = 0)  
scatter!(x2, y2, markerstrokealpha = 0)
```
![image](https://user-images.githubusercontent.com/11365124/76327575-db5af380-62f2-11ea-98cb-f7bb3a19228b.png)

**Comment by isentropic** [comment]
@BeastyBlacksmith this needs closing. I believe it is resolved now
