### ISSUE TITLE
Missing legend picture/icon/series preview for 3D plots

### ISSUE THREAD

**Issue by ferrolho** [JuliaPlots/Plots.jl#2452]
I don't really know what the proper name for this legend component is, but basically every legend usually has: a preview of the line style for its corresponding series, and a text label for that preview. As you can see in the example below, the line style preview is missing from the legend. For me this is an issue for 3D plots only; for 2D plots, the line previews are displaying as expected.

![example](https://user-images.githubusercontent.com/4166093/76613773-b6df6100-6516-11ea-9e3e-c9f73b0f7b74.jpg)

**Comment by BeastyBlacksmith** [comment]
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/1776

**Comment by ferrolho** [comment]
Closing in favor of #1776.
