### ISSUE TITLE
scalefontsizes not scaling all font sizes

### ISSUE THREAD

**Issue by mroavi** [JuliaPlots/Plots.jl#2455]
In the past, a call to `scalefontsizes` would scale all font sizes:
![tmp](https://cloud.githubusercontent.com/assets/933338/19932276/e90443ba-a0e5-11e6-8ecd-a79c2e6d1143.png)

_Originally posted by @tbreloff in https://github.com/JuliaPlots/Plots.jl/issues/560#issuecomment-257878186_

Now it is just scaling a subset of these fonts. Was this change intended? Or is it a bug?

Here is an example of calling `Plots.scalefontsizes(2.0)`:
![image](https://user-images.githubusercontent.com/19517248/76664448-b8477280-6584-11ea-8dcb-6160755118e9.png)

**Comment by daschw** [comment]
That's a bug! However if you want to scale all fonts and lines, you could do
```julia
plot(rand(10), thickness_scaling = 2)
```
![thickness](https://user-images.githubusercontent.com/16589944/76677503-5b24de80-65cf-11ea-9204-c502ad4ce9bc.png)

**Comment by isentropic** [comment]
@daschw can I get assigned to this? I'll follow `thickness_scaling` and try to find the bug

**Comment by daschw** [comment]
Sure
