### ISSUE TITLE
JuliaPlots team members

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#2478]
Friends, 
I've tried to look at the organization we have, which includes quite a few members who have contributed massively, but aren't currently so active. I've made an attempt at doing like they do on Julia itself - by assigning members to teams based on whether they've actually committed to the org in the last year. I might be completely wrong here and don't want to impose anything, so just let me know if it doesn't make sense.

@oschulz @Evizero @ChrisRackauckas @apalugniok @StefanKarpinski does this make sense to you? Or would you like to be listed as active members? Absolutely no slight is intended.

**Comment by ChrisRackauckas** [comment]
Makes sense to me. I'm not very active here anymore, except in docs (the docs are still hosted on my servers)

**Comment by oschulz** [comment]
It's fine if you want to take me out for the time being, I'm afraid I haven't been as active as I should have. I promise I'll still get to work on certains open issues, eventually ... :-)

**Comment by mkborregaard** [comment]
I think it'd be fair to say that anyone in the emeritus group could just request to be transferred back to the active group whenever they feel like diving back in
