### ISSUE TITLE
Gridlines above Plot lines in PGFPlotsX

### ISSUE THREAD

**Issue by theomb21** [JuliaPlots/Plots.jl#2479]
Line plots are in background of gridlines in PGFPlotsX. This deviates from the behavior of the other backends (tested `gr()`, `pyplot()`). Scatter markers are displayed *above* the gridlines. It would be consistent (and probably stylistically favorable) if line plots would also behave like this.

MWE:
```
x = rand(10)

pgfplotsx()
plot(x, grid=(:both, :solid, 6, 1.0), lw=6)
# gridlines are in foreground of lines
scatter(x, grid=(:both, :solid, 6, 1.0), ms=20)
# gridlines are in the background of scatter markers

gr()
plot(x, grid=(:both, :solid, 6, 1.0), lw=6)
# gridlines are in the background
pyplot()
plot(x, grid=(:both, :solid, 6, 1.0), lw=6)
# gridlines are in the background
```

The linewidths and markersizes are adjusted to give a clear picture, but zooming in an output pdf reveals the same behaviour of the plain `plot(rand(10)).

This behaviour of line plots can also be seen in the [tutorial](http://docs.juliaplots.org/latest/generated/pgfplotsx/#pgfplotsx-ref33-1)

Maybe you want to add this to: #2290

**Comment by theomb21** [comment]
I'm using Julia v1.3.1, PGFPlotsX v1.2.5 and Plots v0.29.7

**Comment by BeastyBlacksmith** [comment]
Thanks for pointing out and providing a good MWE. Seems I have to fix the layering
