### ISSUE TITLE
Can't seem to make contour plot of 2D arrays

### ISSUE THREAD

**Issue by cjwyett** [JuliaPlots/Plots.jl#2481]
Python code using pyplot works fine, but when I try and implement in Plots I get an empty grid and the following error message: 

`Arrays have incorrect length or dimension.`

**Working Python code:**
```
from matplotlib import pyplot as plt
A = [[1., 2.], [1., 2.]]
B =  [[1., 1.], [2., 2.]]
C =  [[0.3, 0.4], [0.4, 0.3]]
plt.contour(A,B,C)
```
![image](https://user-images.githubusercontent.com/34195737/76910517-1dada300-68a6-11ea-9f0b-f6faef6f3d35.png)

**Equivalent Julia:**
```
using Plots; gr();

A = [1. 2.; 1. 2.]
B =  [1. 1.; 2. 2.]
C =  [0.3 0.4; 0.4 0.3]

contour(A,B,C)
```
`Arrays have incorrect length or dimension.`

pls help

**Comment by daschw** [comment]
In Plots it would be
```julia
A = 1:2
B = 1:2
C = [0.3 0.4; 0.4 0.3]

contour(A, B, C)
```
or just
```julia
contour(C)
```

**Comment by cjwyett** [comment]
Thank you - apologies for any idiocy - examples just aren't as easy to come by

**Comment by cjwyett** [comment]
Thank you very much
