### ISSUE TITLE
yflip bug with pyplot() and surface()

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaPlots/Plots.jl#2493]
Hi,

I just found a bug when using pyplot() backend. yflip does not works properly. It seems to be linked to x axis. 

`surface(rand(100,100), yflip = true)`

![Case Study 1 - Prueba1](https://user-images.githubusercontent.com/11316335/77128873-73558d00-6a17-11ea-8377-a4a65237a664.png)

`surface(rand(100,100), yflip = false)`

![Case Study 1 - Prueba2](https://user-images.githubusercontent.com/11316335/77128898-88cab700-6a17-11ea-99d9-d1462de9c92d.png)

`surface(rand(100,100), xflip = true)`

![Case Study 1 - Prueba3](https://user-images.githubusercontent.com/11316335/77128905-92ecb580-6a17-11ea-93d2-636125a2f900.png)

Finally, using my own data (101x8000), all the xticks overlaps:

`surface(CSD, yflip = true)`

![Case Study 1 - Prueba3](https://user-images.githubusercontent.com/11316335/77129811-f75d4400-6a1a-11ea-8749-71d62c485456.png)

**Comment by daschw** [comment]
That does not look good, thanks for reporting!

**Comment by isentropic** [comment]
@Kelvyn88 Would you please provide MWE? I cannot reproduce this easily

**Comment by Kelvyn88** [comment]
Seems to work now. 

I reinstalled PyPlot package and libraries with miniconda to get the lastest matplotlib. Maybe it was the solution.

Thanks
