### ISSUE TITLE
Some font attributes aren't kept when used with default()

### ISSUE THREAD

**Issue by czlee** [JuliaPlots/Plots.jl#2496]
When passed to `default()`, the parameters `guidefontsize`, `guidefontcolor`, `tickfontsize` and `tickfontcolor` appear to have no effect.

The attributes `legendfontsize`, `legendfontcolor`, `titlefontsize` and `titlefontcolor` work as expected. The attributes `guidefont` and `tickfont` also work fine, so can be used as a workaround. Also, the parameters work fine when passed directly to `plot()`, it's just `default()` that seems not to like them.

I've tried this with both GR and PyPlot, and they behave the same. I haven't tried other backends. I'm on Julia 1.3.1, JuliaPlots 0.29.7, PyPlot.jl 2.8.2, matplotlib 3.2.0 and I think GR 0.47.0 but I'm not sure how to check that one because I seem to have two, the other being 0.44.0(?)

Minimal example, using GR backend, the plots are screenclips from a Jupyter Notebook, and the font sizes are intentionally ridiculous so it's obvious when they work:
``` julia
using Plots

default(legendfontsize=20, legendfontcolor=:red)
default(titlefontsize=20, titlefontcolor=:red)
default(guidefontsize=20, guidefontcolor=:red)
default(tickfontsize=20, tickfontcolor=:red)

# This is the broken line
# Note that the legend and title are complying, it's just ticks and guides that aren't
plot(1:5, 1:5, title="title", xlabel="x", ylabel="y")
```
![image](https://user-images.githubusercontent.com/1725499/77209898-cfbeb800-6abc-11ea-8661-2d3de7dcebc8.png)
```julia
# Using attributes inline works fine
plot(1:5, 1:5, title="title", xlabel="x", ylabel="y",
     guidefontsize=20, guidefontcolor=:magenta,
     tickfontsize=20, tickfontcolor=:magenta)
```
![image](https://user-images.githubusercontent.com/1725499/77209953-f11fa400-6abc-11ea-99c0-7a315cd15cd7.png)
```julia
# Using `tickfont` and `guidefont` work fine too, so this is a valid workaround
default(tickfont=Plots.font(20, :blue))
default(guidefont=Plots.font(20, :blue))
```
![image](https://user-images.githubusercontent.com/1725499/77209966-fbda3900-6abc-11ea-8002-d689f18460f1.png)

Let me know if I've missed any details that would be helpful. As I said, there's an acceptable workaround, but I thought I should report the issue.

**Comment by czlee** [comment]
Thanks, @daschw!

**Comment by daschw** [comment]
Thanks for reporting!
