### ISSUE TITLE
How to plot an annotation with datetime X

### ISSUE THREAD

**Issue by Ronneesley** [JuliaPlots/Plots.jl#2500]
Hello,

     Using Plots module I have a problem positioning annotations as you can see:

```julia
using Plots
x = 1
plot([x], [1], legend=false)
annotate!([x], [2], Plots.text("Here", 16, :red, :center))
```

![](https://aws1.discourse-cdn.com/business5/uploads/julialang/original/2X/a/ab5f8e6f7931418c59cac626042dcdd1760eef31.png)
 
This works perfectly, positioning an annotation at coordinates (1, 2). But when I work with dates, see:

```julia
using Dates, Plots
x = DateTime(2020, 03, 18)
plot([x], [1], legend=false)
annotate!([x], [2], Plots.text("Here", 16, :red, :center))
```

I got:

```julia
MethodError: no method matching wctondc(::DateTime, ::Int64)
Closest candidates are:
  wctondc(!Matched::Real, ::Real) at /home/user/.julia/packages/GR/tPkHV/src/GR.jl:2579
```

It's not intuitive. Probably I've to convert `x` on `annotate!()`

**Comment by wfrgra** [comment]
This has just been fixed by #2522
