### ISSUE TITLE
Allow :auto for endpoints of limits

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaPlots/Plots.jl#2505]
Would be nice to be able to specify `plot(1:5, ylims=(-5,:auto))`.

**Comment by mkborregaard** [comment]
very! I've often thought that. I've also thought `:centered` or `:symmetric` to have the lims symmetric around 0. And I also think these should all apply to `clims` as well

**Comment by isentropic** [comment]
PyPlot implements this as
```
plt.plot(rand(10))
plt.xlim(right=2)
```
Perhaps, allows users suppy lims as a named tuple?

**Comment by akdor1154** [comment]
This would be useful even if just to let users enforce that their y-axes begin at zero. Unless this is currently possible another way? (framestyle=:origin enforces this on the x-axis too which isn't always appropriate)

**Comment by daschw** [comment]
> Unless this is currently possible another way?

`ylims = (0, Inf)`

**Comment by daschw** [comment]
... or maybe I don't understand what the behavior of `:auto` would be?

**Comment by BeastyBlacksmith** [comment]
> > Unless this is currently possible another way?
> 
> `ylims = (0, Inf)`

That is actually what I was looking for. I'd argue that this is a bit hard to discover, because semantically `Inf` is kind of doing the opposite of what I would naively expect it to do.

**Comment by mkborregaard** [comment]
Yes agreed

**Comment by daschw** [comment]
> semantically Inf is kind of doing the opposite of what I would naively expect it to do

`ylims = (0, NaN)` works too. It would probably not be to hard to also accept `missing`, `nothing`, and/or `:auto`.
