### ISSUE TITLE
Line graph same color with group option

### ISSUE THREAD

**Issue by darrencl** [JuliaPlots/Plots.jl#2527]
Hi, I want to plot a line graph using Plots.jl and having same color of the same group member. Suppose I have this data
```julia
julia> data = [rand(10) for i=1:4];
julia> group = [1,1,2,2];
```
I wanted group 1, that is `data[1:2]` having same color and `data[3:4]` having another same color, which is different with group 1.
Saw there is a group option in plot, but this is not the behavior I want.

The attached below are without `group` option and in comparison, with passing `group=group` option.
![Without group option](https://user-images.githubusercontent.com/21291776/78220790-867f5700-7505-11ea-86b8-7d2002b86c5b.png)
![Line graph with group option](https://user-images.githubusercontent.com/21291776/78220827-98f99080-7505-11ea-96c9-5e3ac164b121.png)

How can I have the same plot as without group (pic1) but with the correct color group in Plots.jl?

FYI, I am using pyplot.

**Comment by mkborregaard** [comment]
Yes the group keyword means something different. In this case `color = group` should work though.

**Comment by daschw** [comment]
Actually for the example above it would be `color = group'`.

**Comment by mkborregaard** [comment]
True, good catch.
Closing this issue as the question was also asked on Slack.

**Comment by darrencl** [comment]
Thanks guys @mkborregaard @daschw .

Is it also possible to change the legend to the color group as well? Instead of showing the individual data like below?

![image](https://user-images.githubusercontent.com/21291776/78308240-52e71000-758b-11ea-8120-ac69d4e2e2dd.png)

**Comment by mkborregaard** [comment]
Not automatically no. This already abuses the Plots syntax a little.
