### ISSUE TITLE
There is an extra space in xlabel and ylabel string?

### ISSUE THREAD

**Issue by UCAStanghe2014** [JuliaPlots/Plots.jl#2529]
```julia
using Plots
using LaTeXStrings
plot(0:2,0:2, xlab = "xlabel: "*LaTeXString("\\gamma+\\alpha^2+1+\\alpha^2"), ylab = "ylabel: "*LaTeXString("1+\\alpha^2+1+\\alpha^2"))
```
get
![QQ截图20200403185935](https://user-images.githubusercontent.com/34116981/78379924-b4e45b80-7605-11ea-845a-fd0ee31f88e5.png)
If try `plot(0:2,0:2,xlab = "xlabel: "*LaTeXString("1+\\alpha^2+1+\\alpha^2"))`, I get
![QQ截图20200403190853](https://user-images.githubusercontent.com/34116981/78379991-ca598580-7605-11ea-8bf7-f0c99963c4c9.png)

**Please keep attention on the xlabel and ylabel. It seems to exist an extra space in the label before first "+".** 
Is it a bug? Julia: Version 1.4.0 (2020-03-21); LaTeXStrings v1.1.0; Plots v0.29.4
Thank you!

**Comment by BeastyBlacksmith** [comment]
I can reproduce this with GR backend, but it is not an issue with `pgfplots/x` backend.
So probably something with the kerning of the new computer modern font in GR? @jheinen

**Comment by jheinen** [comment]
In plain GR, it looks fine:
```julia
using GR
using LaTeXStrings
plot(0:2,0:2,xlabel=L"xlabel: 1+\alpha^2+1+\alpha^2")
```
<img width="712" alt="Screen Shot 2020-04-05 at 12 50 47" src="https://user-images.githubusercontent.com/5718244/78472818-1a3a6880-773c-11ea-9240-3677fccbe953.png">
The new CM fonts are not yet integrated into Plots. I'll try to fix this soon, but I'm currently busy with the new 3D stuff in GR.

**Comment by Moelf** [comment]
is this fixed? Also it looks like LaTeXString label is too close to the tick text, any where I can look to fix it?

**Comment by jheinen** [comment]
In GR you still can't encapsulate LaTeX strings. You could try:
```
plot(0:2,0:2, xlab = L"xlabel: \gamma+\alpha^2+1+\alpha^2", ylab = L"ylabel: 1+\alpha^2+1+\alpha^2")
```
If the strings are too close to the tick text, this can only be changed in `Plots.jl`.

<img width="712" alt="Screen Shot 2020-11-07 at 07 45 30" src="https://user-images.githubusercontent.com/5718244/98434132-3d136d80-20cd-11eb-8588-f8d34d7db92f.png">

**Comment by t-bltg** [comment]
Seems to be fixed.
