### ISSUE TITLE
Can't add Plots package on Julia 1.4

### ISSUE THREAD

**Issue by matrem** [JuliaPlots/Plots.jl#2535]
I'm a beginner to Julia, but following the intro tutorial I can't add Plots (it seems to crashes Julia) :

```
(@v1.4) pkg> add Plots
   Updating registry at `C:\Users\Me\.juliapro\JuliaPro_v1.4.0-1\registries\JuliaPro`
  Resolving package versions...

Julia has exited.
```
Doing this in Atom IDE, REPL command line.

**Comment by daschw** [comment]
I cannot reproduce. Have you tried `pkg> up`?

**Comment by matrem** [comment]
Seems ok :
(@v1.4) pkg> up
   Updating registry at `C:\Users\Me\.juliapro\JuliaPro_v1.4.0-1\registries\JuliaPro`
   Updating `C:\Users\Me\.juliapro\JuliaPro_v1.4.0-1\environments\v1.4\Project.toml`
 [no changes]
   Updating `C:\Users\Me\.juliapro\JuliaPro_v1.4.0-1\environments\v1.4\Manifest.toml`
 [no changes]

**Comment by matrem** [comment]
Do I need administrator privileges for this install? Because my user is not admin.

**Comment by mkborregaard** [comment]
you shouldn't have to no

**Comment by mkborregaard** [comment]
It could be some unlucky interaction with JuliaPro

**Comment by matrem** [comment]
I should try reinstalling Julia only?

**Comment by daschw** [comment]
At least that works for me.

**Comment by matrem** [comment]
After julia pro, nteract uninstall, and only julia installed It's working. Should I put this bug report somewhere else?

**Comment by MoonCoral** [comment]
This happened to me also, but only with the add command. Writing `]add Plots.jl` however worked for reasons unknown.
