### ISSUE TITLE
pgfplotsx legend in outer-position

### ISSUE THREAD

**Issue by matthieugomez** [JuliaPlots/Plots.jl#2549]
Plotting a legend in outer position does not seem to work with `pgfplotsx`
```julia
using Plots
pgfplotsx()
plot(1:10, rand(10))
plot(1:10, rand(10), legend = :outertop)
#> ERROR: The latex command `lualatex jl_7bA9WF.tex` failed
```

**Comment by BeastyBlacksmith** [comment]
Which Plots version is that? I don't get the tex-error, but also not the expected output.
As a workaround you can pass a tuple to `legend` like: `plot(1:10, rand(10), legend = (0.5,1.1))`

**Comment by matthieugomez** [comment]
Thanks!
