### ISSUE TITLE
wrong :letter for some plot recipes

### ISSUE THREAD

**Issue by briochemc** [JuliaPlots/Plots.jl#2555]
There is an issue with `:letter` for some recipes that take a single argument. This is because the data of single-argument plots lives on different axes depending on the plot recipe. For instance:

- `plot(x)`: `x` lives in the *y* axis, `:letter == :y` ✔️ 
- `histogram(x)` or `vline(x)`: `x` lives in the *x* axis, but  `:letter == :y` ✖️  

Maybe there are other similar cases. 

To illustrate this with MWEs, take this recipe, which just displays the `:letter` in the title for `MyType` arrays:
```julia
using Plots, RecipesBase
struct MyType <: Number
    val::Float64
end
value(m::MyType) = m.val
@recipe function f(::Type{T}, m::T) where T <: AbstractArray{<:MyType}
    title --> string(length(m), " ", plotattributes[:letter], "-axis values")
    value.(m)
end
```

Then 
```julia
histogram(MyType.(randn(1000)))
```
gives
![histobug](https://user-images.githubusercontent.com/4486578/78956264-16845880-7b25-11ea-8b87-af2424dd2398.png)

and 
```
vline(MyType.(randn(10))
```
gives
![vlinebug](https://user-images.githubusercontent.com/4486578/78956270-1be1a300-7b25-11ea-863f-1cf280fbe10f.png)

**Comment by daschw** [comment]
Yeah, we should find a general solution for that. Maybe some kind of `switch_axes` trait for seriestypes defined in RecipesBase.
For now a workaround in the recipe would be something like
```julia
switch = get(plotattributes, :seriestype, :path) in (:histogram, :vline)
letter = plotattributes[:letter]
if switch
    letter == :x && (letter = :y)
    letter == :y && (letter = :x)
end
```
Maybe we should rather do this in type recipe processing in Plots, though.

**Comment by briochemc** [comment]
Yes, I imagined I could do something like that but it seems like you'd rather have this been done for all axis-aware type recipes by default, right?

Also, I wanted to get this through you guys because I don't know all the `:seriestype` out there that need that switch. Are `:histogram` and `:vline` the only ones?

**Comment by daschw** [comment]
Yes, thanks for bringing this up! It's probably better if we fix this in Plots.
I think there's also some more histogram-like seriestypes like `:stephist`.

**Comment by briochemc** [comment]
Could you point out to how I could help with this tiny bug?

**Comment by BeastyBlacksmith** [comment]
Wouldn't be the best solution to redirect, e.g. `vline(x)` to `plot(x,[], seriestype=:vline)`?

**Comment by briochemc** [comment]
I'm sorry if this sounds like a dumb question, but could you clarify how one "redirects" `vline(x)`? I think I need a bit of hand-holding! 😅 

Also, are these changes supposed to happen in Plots.jl? If yes in which files? (The code base of Plots.jl is quite large to me so I often get lost looking for things inside of it.) If not should I be looking at RecipesBase or another package?

**Comment by BeastyBlacksmith** [comment]
The `vline` recipe is defined [here](https://github.com/JuliaPlots/Plots.jl/blob/2fb315af0e1772c2c6caba87ccb4720983aee16b/src/recipes.jl#L124) and the shorthand is defined [here](https://github.com/JuliaPlots/Plots.jl/blob/8976fc4ae479b792289ddbfea13662d90a1de5db/src/shorthands.jl#L180).
The `@shorthands` macro expands to something like `vline(args... ;kwargs...) = plot(args... ; seriestype=:vline, kwargs...)` and the issue here is that `plot(x)` is treated like `plot(1:length(x), x)`, so we explicitly need to add a more specific method for the one argument `vline` that passes its data as `x` and not as `y`.
Other workaround might be to simply add `letter := :x` in the `vline`-recipe.
