### ISSUE TITLE
Error building 'GR'

### ISSUE THREAD

**Issue by pramod-dudhe** [JuliaPlots/Plots.jl#2570]
I am trying to use Plots package in Jupyter notebook and because of the error in plotting (could not load library "libGR.dll", The specified module could not be found.), I tried the following:

ENV["GRDIR"]=""
using Pkg
Pkg.build("GR")

And I get the following error:

   Building GR → `C:\Users\Pramod\.julia\packages\GR\ZI5OE\deps\build.log`
┌ Error: Error building `GR`: 
│ ERROR: LoadError: UndefVarError: installed not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\Pramod\.julia\packages\GR\ZI5OE\deps\build.jl:8
│  [2] include(::String) at .\client.jl:439
│  [3] top-level scope at none:5
│ in expression starting at C:\Users\Pramod\.julia\packages\GR\ZI5OE\deps\build.jl:7
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892

I am getting the above error only when I am using Jupyter notebook and I don't face any issue when I am using Atom IDE for plotting using Plots package. Please help.

Thanks.

**Comment by asinghvi17** [comment]
This is an upstream issue in GR.  @jheinen, `Pkg.installed` is deprecated in 1.4.  https://github.com/jheinen/GR.jl/blob/master/deps/build.jl#L36 is where it seems to be used.

**Comment by jheinen** [comment]
Did you `] up GR`?

**Comment by pramod-dudhe** [comment]
I have installed GR using Pkg.add("GR") in jupyter notebook and then using Pkg.build("GR").

**Comment by jheinen** [comment]
Unfortunately, I could not reproduce the problem. There must be some "old" GR installation lying around. I'd suggest to remove the GR directory under `packages` before `] add GR`.
<img width="977" alt="Screen Shot 2020-04-13 at 11 53 34" src="https://user-images.githubusercontent.com/5718244/79112240-66aa2780-7d7e-11ea-909f-177d6898f31d.png">

**Comment by pramod-dudhe** [comment]
The weird thing is: I am able to build GR in Atom or when I run the code from Juila, I am facing the issue when I try to use Jupyter notebook! And deleting GR and reinstalling it doesn't help either.

**Comment by jheinen** [comment]
So you are using a separate Julia distribution for Jupyter!?

**Comment by pramod-dudhe** [comment]
What do you mean? I didn't get that.

**Comment by jheinen** [comment]
You can check it by comparing `Sys.BINDIR` and/or `versioninfo()`.

**Comment by pramod-dudhe** [comment]
I am getting the same output for all three - Atom, Julia console, and Jupyter
"C:\\Users\\Pramod\\AppData\\Local\\Programs\\Julia\\Julia-1.4.0\\bin".

If Jupyter doesn't work, I will use Atom IDE, I think it will suffice my purpose for now. Thanks for all the help!

**Comment by jheinen** [comment]
And `using GR` in Jupyter doesn't work?

**Comment by pramod-dudhe** [comment]
When I run the following:
using Plots
using GR
plot(randn(10))

I get the following error:

WARNING: both Plots and GR export "plot"; uses of it in module Main must be qualified
UndefVarError: plot not defined

Stacktrace:
 [1] top-level scope at In[3]:1

**Comment by jheinen** [comment]
You can't use both GR and Plots at the same time. I just wanted to find out, whether you can import GR and plot something, e.g.:
```
using GR
plot(randn(10))
```

**Comment by pramod-dudhe** [comment]
When I use 'using GR', I get the following error:

┌ Info: Precompiling GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71]
└ @ Base loading.jl:1260
┌ Warning: Package GR does not have UUIDs in its dependencies:
│ - If you have GR checked out for development and have
│   added UUIDs as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with GR
└ Loading UUIDs into GR from project dependency, future warnings for GR are suppressed.

**Comment by jheinen** [comment]
Did you try `] resolve` or `] add GR`

**Comment by pramod-dudhe** [comment]
I get the same error that I started with:

 Installed GR ─ v0.41.0
   Updating `C:\Users\Pramod\Desktop\quantecon-notebooks-julia\Project.toml`
 [no changes]
   Updating `C:\Users\Pramod\Desktop\quantecon-notebooks-julia\Manifest.toml`
 [no changes]
   Building GR → `C:\Users\Pramod\.julia\packages\GR\ZI5OE\deps\build.log`
┌ Error: Error building `GR`: 
│ ERROR: LoadError: UndefVarError: installed not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\Pramod\.julia\packages\GR\ZI5OE\deps\build.jl:8
│  [2] include(::String) at .\client.jl:439
│  [3] top-level scope at none:5
│ in expression starting at C:\Users\Pramod\.julia\packages\GR\ZI5OE\deps\build.jl:7
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892

**Comment by jheinen** [comment]
GR v0.41.0 is from July 2019 - this can't work. You will have to update GR: `] up GR`

**Comment by BeastyBlacksmith** [comment]
Probably some dependency in that project file is holding the update back and jupyter might activate that environment by default.
A general update via `]up` might fix this. Otherwise try
```
]rm GR
pkg> add GR@0.48
```
to see which package is preventing the update.

**Comment by pramod-dudhe** [comment]
Updating GR worked! Thanks @jheinen for all the help!

**Comment by manuzrpEd** [comment]
I get the following error when I try to update:

`ERROR: The following package names could not be resolved:
 * GR (28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71 in manifest but not in project)`

Any help/ideas?

**Comment by manuzrpEd** [comment]
Solved:

`Pkg.add("GR")`

worked for me.
