### ISSUE TITLE
ylabel rotation with PyPlot

### ISSUE THREAD

**Issue by JackDunnNZ** [JuliaPlots/Plots.jl#2573]
The PyPlot backend doesn't seem to be rotating the y label correctly:

```julia
using Plots
Plots.pyplot()
plot(1:10, 1:10, ylabel="abcdefg")
```

![image](https://user-images.githubusercontent.com/4717044/79126615-4d00e400-7d6e-11ea-8bc5-c66112c577e6.png)

This is with Plots v1.0.9, on v0.29.9 the label is rotated correctly

**Comment by isentropic** [comment]
Do you mean the going over the y axis?

**Comment by JackDunnNZ** [comment]
Sorry, here's how it is in v0.29.9:

![image](https://user-images.githubusercontent.com/4717044/79135534-783eff80-7d7d-11ea-8f3d-e806e4690bae.png)

It also has the correct rotation when using GR in v1.0.9:

![image](https://user-images.githubusercontent.com/4717044/79135924-1c28ab00-7d7e-11ea-9393-f0e6b259c9d6.png)

Although I'm not sure what is going on with the font compared to how it was in v0.29.9:

![image](https://user-images.githubusercontent.com/4717044/79135652-b2a89c80-7d7d-11ea-9f99-d22b90e04673.png)

**Comment by isentropic** [comment]
Yeah, rotation only works with pyplot, and it has been only added in https://github.com/JuliaPlots/Plots.jl/releases/tag/v1.0.9

Unfortunately, I'm really unfamiliar with GR to able to fix it.

**Comment by isentropic** [comment]
Oh, I understand what you mean. It is rotated without the specification of the attribute like: `"yguidefontrotation=45"`
@daschw Perhaps you could help. Maybe the default value for the font rotation is not processed in the pipeline so that it is interpreted as no rotation by default for pyplot.

**Comment by isentropic** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/2565 This needs to be taken off then

**Comment by JackDunnNZ** [comment]
Thanks, that makes sense. Yes it looks like the default is now being interpreted as "no rotation" somehow

**Comment by isentropic** [comment]
I can send a quickfix (dirtyfix) to this by,


by adding this: 
```
axis[:yguidefontrotation] = axis[:yguidefontrotation]  + 90
```
somewhere before
https://github.com/JuliaPlots/Plots.jl/blob/bf849d90a75ecaf5785ca2dfa1e346321f4bbbdc/src/backends/pyplot.jl#L1116

Pyplot needs to have `:yguidefontrotation => 90` not `0` as is processed by pipeline

**Comment by daschw** [comment]
You can just replace the line with
```julia
pyaxis."label"."set_rotation"(90 + axis[:guidefontrotation])
```
no?

**Comment by isentropic** [comment]
> You can just replace the line with
> ```julia
> pyaxis."label"."set_rotation"(90 + axis[:guidefontrotation])
> ```
> no? 

Oh, I tried that, then X axis has wrong default rotation

**Comment by daschw** [comment]
Not sure if you also have to check if the subplot is 3D. then you would not want to rotate `y` but `z` guides.

**Comment by isentropic** [comment]
@JackDunnNZ Would you mind checking the master branch of Plots to see if the issue is still present?

**Comment by JackDunnNZ** [comment]
Thanks for the quick fix, it looks good to me now!
