### ISSUE TITLE
Allow list of colors to be passed to hline function

### ISSUE THREAD

**Issue by djsegal** [JuliaPlots/Plots.jl#2576]
Right now this only produces red lines (i.e. no green ones):

```
scatter(rand(100))
hline!([0.5,0.25,0.75], color=[:red, :green, :green])
```

---

This can be seen here:

![Screen Shot 2020-04-13 at 1 02 47 PM](https://user-images.githubusercontent.com/3156114/79156158-3dda6000-7d87-11ea-9884-7a816c5a386b.png)

**Comment by mkborregaard** [comment]
In Plots, columns are series. So to add several series with different attributes use a row vector.
```julia
hline!([0.5 0.25 0.75], color=[:red :green :green])
```
<img width="591" alt="Screenshot 2020-04-14 at 10 39 24" src="https://user-images.githubusercontent.com/8429802/79204048-3b860d80-7e3c-11ea-85c4-b7c078148e70.png">

**Comment by djsegal** [comment]
thanks!
