### ISSUE TITLE
twiny() ?

### ISSUE THREAD

**Issue by jenfenghsu** [JuliaPlots/Plots.jl#2579]
Is it possible to have similar hack as twinx() to have secondary x-axis on top of the plot? This can be useful when displaying the same curve with alternative units. See below for example. Or, any suggestion to achieve the same in Julia Plots? Thanks!
![image](https://user-images.githubusercontent.com/12201322/79241438-0e882980-7e41-11ea-9d4d-8cfef7e3a4bf.png)

My minimal example code with PyPlot package (but I'd very much love to continue using Plots):
```julia
fig, ax1 = PyPlot.subplots(num="Temperature Dependence",figsize=(10,6),facecolor="0.98")

ax1.set_xlabel("Temperature (°C)", fontsize=20)
ax1.set_ylabel("Response", fontsize =20)
x = collect(0:0.1:100)
y = 0.1 .* x .^ 2 - 5 .* x .+ 8
ax1.plot(x, y, lw=1., label="Object 1") 
ax1.legend(loc="best")
ax1.grid(true)

ax2 = ax1.twiny()
ax2.set_xlabel("Temperature (°F)", fontsize =20)
ax2.plot(x .* 9/5 .+ 32, y, lw=0.) # Ghost plot to show scale

PyPlot.show()
```

**Comment by feanor12** [comment]
I found some code for twiny here :
https://stackoverflow.com/questions/64176617/julia-two-x-axes-for-plot-of-same-data
