### ISSUE TITLE
clims in pgfplotsx heatmap

### ISSUE THREAD

**Issue by korsbo** [JuliaPlots/Plots.jl#2582]
```julia
using Plots
pgfplotsx()
heatmap(rand(3,3), clims = (0., 100.))
```

Here, I would expect everything to be essentially black since the data is smaller than one. The colours are however spanning the full colour range. It looks lively, but it is not representing the data in a way that I would consider accurate.

I'm using `v1.0.9`. 

Thanks!

**Comment by daschw** [comment]
Thanks for reporting!
If you need this until we find a fix for it you can use
```julia
plots_heatmap(1:3, 1:3, rand(3,3), clims = (0, 100))
```
Note that at the moment `plots_heatmap` requires specifying x and y input too.

**Comment by korsbo** [comment]
Thanks, I have already solved my immediate problem by manual inkscape tweaking but I tried your method too. It seems to fix this issue but it gets wonky with the colorscale. The plot is using something that looks like inferno while the colorscale bar is using my specified viridis.
