### ISSUE TITLE
Intended behavior of `thickness_scaling` for `markersize`

### ISSUE THREAD

**Issue by isentropic** [JuliaPlots/Plots.jl#2592]
Currently, this
```
pyplot()
scatter(rand(3), thickness_scaling=3)
```
![image](https://user-images.githubusercontent.com/24591123/79519952-56e95680-8090-11ea-9f46-e78a24c93bc8.png)

``` 
gr()
scatter(rand(3), thickness_scaling=3)
```
Produces different output in gr and pyplot

![image](https://user-images.githubusercontent.com/24591123/79519896-2d302f80-8090-11ea-89de-d2ab0f132ba6.png)
Also legend box is slightly differently shaped. GR: sharp rectangle, PyPlot: circle corners

Things that are different:

1. Tick marks (small indents at ticks)
    1. gr: have equal thickness with axes spine
    2. pyplot: seemingly unscaled

2. Markerstrokewidth
    1. gr: unscaled
    2. pyplot: upscaled thickness

3. Markerstrokewidth in the legend
    1. gr: unscaled
    2. pyplot: unscaled

4. Markersize both in the legend and ax
    1. gr: unscaled
    2. pyplot: unscaled

I want to fix these issues in PyPlot (I am inept at GR). Let me know what should be the desired outcome.

Additionally, increasing markersize does not increase the markersize in the legend, which I think needs to be implemented too, or given additional argument to accoun for this.

**Comment by isentropic** [comment]
Perhaps, @daschw could clarify this?

**Comment by daschw** [comment]
IMO tick marks and marker strokes should be scaled everywhere (legend and axis).
I think markersizes should be upscaled with thickness scaling, but I'm not sure about that.
@mkborregaard I remember you have already put a lot of thought into marker sizes. What do you say?

**Comment by isentropic** [comment]
I think for now, I'll try get there tick marks and markerstroke fixed for pyplot

**Comment by mkborregaard** [comment]
I think markersizes should stay constant, but markerstrokes should clearly scale. So I think the pyplot behaviour is more correct here

**Comment by isentropic** [comment]
> 
> 
> I think markersizes should stay constant, but markerstrokes should clearly scale. So I think the pyplot behaviour is more correct here

I think we need a argument for `legendmarkersize` and `legendmarkerwidth`.

On top of this, I believe that many arguments need to have their  corresponding `legend<component_property>`  if we want to rework legends. The pipeline should provide these too, or else there is no way to specify the markersize in the legend. Additionally the legendbox size needs to be adjusted if markersize in the legend is too big.

**Comment by isentropic** [comment]
It should not be very difficult to duplicate common arguments and have `legend <markerstrokealpha>` (and alike) right?
Having explicit arguments for legends too, would let users tweak legends a lot better, if backends and the pipeline do not do it well automatically

**Comment by daschw** [comment]
Hi, sorry for my late reply. To be honest I'm not really convinced that we should introduce that many new attributes. The Plots philosophy has always been to provide a convenient common interface to different backends for intuitive plotting. For more detailed technical tweaking of plots we usually recommend the users to use the backend directly.
IMO having nice consistent defaults (sensibly mapping the style of the markers in the plots) is the way to go here. I don't know how common the desire to tweak the markersize in legend is among users and I'm not sure if that justifies the additional development burden of implementing and maintaining it on all backends, adding docs etc.

**Comment by isentropic** [comment]
@daschw @mkborregaard your points are very much valid, but a common (I think) use case is then limited.
I, for example, very much like `thickness_scaling` so that the plots could be presented in a slideshow and the audience can then see ticks and the legend. Making larger-scale plots is a very common need for anyone who uses Plots.jl on a daily basis.

Here is what I mean.
![Figure_3](https://user-images.githubusercontent.com/24591123/79777126-c2257800-8371-11ea-9e62-7ff6b71200bf.png)
I can neither manually adjust the marker size in the legend nor it scales automatically. I cannot make the legend marker clearly visible. 

I only see 2 solutions:
1. Make legend marker size adjustable by hand
2. It should scale automatically

**Comment by daschw** [comment]
IMO it should scale automatically up to a certain maximal value.

**Comment by daschw** [comment]
I'm still not convinced that markersizes in the plot should not scale automatically with thickness scaling. Linewidths do, so why not markersizes, @mkborregaard ?

**Comment by mkborregaard** [comment]
I am swayed by your arguments :-)

**Comment by isentropic** [comment]
> IMO it should scale automatically up to a certain maximal value.

I think it should scale at the same pace as the legend box scales, regardless of the marker size on the plot itself.

**Comment by daschw** [comment]
> I think it should scale at the same pace as the legend box scales, regardless of the marker size on the plot itself.

OK, that's probably better.

**Comment by jamblejoe** [comment]
@daschw I think effectively we would introduce only one more attribute by adding `legendmarkersize`, etc, because they are just `legend` + plain attribute, which (most) people already came across. Further, the naming for legend attributes already follows these conventions. Why not go down that road a little further.

The default behaviour should be that the legend markers scale the same as the markers in the plot. But this is right now not the case, as was pointed out already.

To convince that people are interested in such features, I added some links to discourse posts (including my own):
https://discourse.julialang.org/t/adjusting-markers-in-legend/38042
https://discourse.julialang.org/t/plot-pyplot-marker-size-inside-the-legend/30454
https://discourse.julialang.org/t/changing-size-of-markers-in-legend-with-plots/15520
https://discourse.julialang.org/t/modifying-legend-markersize-linelength-of-a-plots-pyplot-plot-after-creation/36723

**Comment by daschw** [comment]
Thanks a lot for this list of related posts. If there is so much demand for `legendmarkersize` I'm willing to reconsider.

> we would introduce only one more attribute by adding legendmarkersize, etc, 

What do you mean by etc?

**Comment by jamblejoe** [comment]
We have series attributes regarding markers: 
markeralpha, markercolor, markershape, markersize, markerstrokealpha, markerstrokecolor, markerstrokestyle, markerstrokewidth - which could be of use in the legend as well. As @isentropic pointed out, they could have corresponding legend attributes, as
legendmarkeralpha, legendmarkercolor, legendmarkersize, etc.

I can not see use cases for all of them, but changing the size of markers and changing the strokes seem to be needed.

**Comment by daschw** [comment]
I would not add more than `legendmarkersize`. I don't see when having a different color or shape than in the plot would be useful.

**Comment by jamblejoe** [comment]
That is a good point, What about the strokes?

**Comment by isentropic** [comment]
See, https://github.com/JuliaPlots/Plots.jl/pull/2616
I think we can just not allow users to tweak with the legendmarker size and width at all. But instead, let it scale with the legendbox size accordingly. 
Users can always modify markersize in the actual plot, it does not need to be scaled automatically, but it would too be a nice feature.
