### ISSUE TITLE
regression with annotate! and backend GR

### ISSUE THREAD

**Issue by oheil** [JuliaPlots/Plots.jl#2601]
Fix https://github.com/JuliaPlots/Plots.jl/commit/87b220e7473387626c44b044db55ecb410a0047d
of issue https://github.com/JuliaPlots/Plots.jl/issues/2487
brings a regression:
annotate!(x,y,t)
doesn’t work anymore, one must use:
annotate!((x,y,t))
See discussion
https://discourse.julialang.org/t/plots-annotate/37784

**Comment by daschw** [comment]
That's fixed in #2597

**Comment by djsegal** [comment]
What version does this start working again in?

Thanks for the quick fix tho!!

**Comment by daschw** [comment]
1.0.12
