### ISSUE TITLE
error on 1st attempt to install&use

### ISSUE THREAD

**Issue by rryi** [JuliaPlots/Plots.jl#2609]
Hello, 

I just tried to start with Plots. System Win10, CPU Pentium Gold, Julia 1.0.5.
Reproducing: add Pllots, then using Plots. Following the log. Hope it helps.

(v1.0) pkg> add Plots
  Updating registry at `C:\Users\RR\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Measures ────────── v0.3.1
 Installed Tokenize ────────── v0.5.8
 Installed Parsers ─────────── v1.0.2
 Installed Tables ──────────── v1.0.4
 Installed CSTParser ───────── v2.2.1
 Installed AbstractTrees ───── v0.3.3
 Installed Plots ───────────── v1.0.13
 Installed Colors ──────────── v0.12.0
 Installed MacroTools ──────── v0.5.5
 Installed FFMPEG ──────────── v0.2.4
 Installed StringDistances ─── v0.6.4
 Installed ColorTypes ──────── v0.10.2
 Installed RecipesPipeline ─── v0.1.4
 Installed DataStructures ──── v0.17.13
 Installed GeometryTypes ───── v0.8.2
 Installed JuliaFormatter ──── v0.3.9
 Installed BinDeps ─────────── v1.0.1
 Installed NaNMath ─────────── v0.3.3
 Installed Showoff ─────────── v0.3.1
 Installed DataAPI ─────────── v1.2.0
 Installed FixedPointNumbers ─ v0.8.0
 Installed PlotThemes ──────── v1.0.3
 Installed CodeTracking ────── v0.5.9
 Installed RecipesBase ─────── v1.0.0
 Installed Cassette ────────── v0.3.3
 Installed StatsBase ───────── v0.33.0
 Installed URIParser ───────── v0.4.1
 Installed PlotUtils ───────── v0.6.5
 Installed FlameGraphs ─────── v0.2.2
 Installed Contour ─────────── v0.5.2
 Installed GR ──────────────── v0.48.0
  Updating `C:\Users\RR\.julia\environments\v1.0\Project.toml`
  [91a5bcdd] + Plots v1.0.13
  Updating `C:\Users\RR\.julia\environments\v1.0\Manifest.toml`
  [1520ce14] ↑ AbstractTrees v0.3.2 ⇒ v0.3.3
  [9e28174c] ↑ BinDeps v1.0.0 ⇒ v1.0.1
  [00ebfdb7] ↑ CSTParser v2.2.0 ⇒ v2.2.1
  [7057c7e9] ↑ Cassette v0.3.1 ⇒ v0.3.3
  [da1fd8a2] ↑ CodeTracking v0.5.8 ⇒ v0.5.9
  [3da002f7] ↑ ColorTypes v0.9.1 ⇒ v0.10.2
  [5ae59095] ↑ Colors v0.11.2 ⇒ v0.12.0
  [d38c429a] + Contour v0.5.2
  [9a962f9c] ↑ DataAPI v1.1.0 ⇒ v1.2.0
  [864edb3b] ↑ DataStructures v0.17.10 ⇒ v0.17.13
  [c87230d0] + FFMPEG v0.2.4
  [53c48c17] ↑ FixedPointNumbers v0.7.1 ⇒ v0.8.0
  [08572546] ↑ FlameGraphs v0.2.0 ⇒ v0.2.2
  [28b8d3ca] + GR v0.48.0
  [4d00f742] + GeometryTypes v0.8.2
  [98e50ef6] ↑ JuliaFormatter v0.3.6 ⇒ v0.3.9
  [1914dd2f] ↑ MacroTools v0.5.4 ⇒ v0.5.5
  [442fdcdd] + Measures v0.3.1
  [77ba4419] + NaNMath v0.3.3
  [69de0a69] ↑ Parsers v0.3.12 ⇒ v1.0.2
  [ccf2f8ad] + PlotThemes v1.0.3
  [995b91a9] + PlotUtils v0.6.5
  [91a5bcdd] + Plots v1.0.13
  [3cdcf5f2] + RecipesBase v1.0.0
  [01d81517] + RecipesPipeline v0.1.4
  [992d4aef] + Showoff v0.3.1
  [2913bbd2] + StatsBase v0.33.0
  [88034a9c] ↑ StringDistances v0.6.3 ⇒ v0.6.4
  [bd369af6] ↑ Tables v1.0.3 ⇒ v1.0.4
  [0796e94c] ↑ Tokenize v0.5.7 ⇒ v0.5.8
  [30578b45] ↑ URIParser v0.4.0 ⇒ v0.4.1
  Building GR ────→ `C:\Users\RR\.julia\packages\GR\yMV3y\deps\build.log`
  Building FFMPEG → `C:\Users\RR\.julia\packages\FFMPEG\guN1x\deps\build.log`
  Building Plots ─→ `C:\Users\RR\.julia\packages\Plots\KVYUB\deps\build.log`

julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

julia> 
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6b6496af -- jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1191
in expression starting at no file:0
jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1191
emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1774
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
wsitem at C:\Users\RR\.julia\packages\Atom\cYxbS\src\workspace.jl:22
wsitem at C:\Users\RR\.julia\packages\Atom\cYxbS\src\workspace.jl:19
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1809
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
#239 at C:\Users\RR\.julia\packages\Atom\cYxbS\src\workspace.jl:12
_collect at .\generator.jl:47
map at .\array.jl:561 [inlined]
workspace at C:\Users\RR\.julia\packages\Atom\cYxbS\src\workspace.jl:12
#236 at C:\Users\RR\.julia\packages\Atom\cYxbS\src\workspace.jl:2
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1809
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
handlemsg at C:\Users\RR\.julia\packages\Atom\cYxbS\src\comm.jl:168
unknown function (ip: 000000000211B1D3)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1809
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:556
#19 at .\task.jl:259
unknown function (ip: 000000000211948A)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\task.c:268
Allocations: 190329592 (Pool: 190267778; Big: 61814); GC: 445

Julia has exited.
Press Enter to start a new session.

**Comment by isentropic** [comment]
This looks like some administrator/RR user permission issue. Perhaps try doing these with higher priveledges? Or the other way around

**Comment by rryi** [comment]
I overcame the issue by deleting .julia folder in user home directory, and adding all packages again.

I discovered some days later more problems with "using SomePackage" in the Atom/Juno REPL, Now I suspect the error here falls into that category, which has nothing to do with Plots, but an update of Juno.

I suppose it was related to this bug:

https://discourse.julialang.org/t/crash-while-loading-any-package-in-repl-in-juno/34870

see also 

https://github.com/JunoLab/Juno.jl/issues/570

which has a stack trace starting very similar.

So I think we should close this bug.
