### ISSUE TITLE
Changes to `default()` make going back to default impossible

### ISSUE THREAD

**Issue by nilshg** [JuliaPlots/Plots.jl#2610]
MWE:

```
julia> using Plots
julia> plot(rand(10, 2)) # two colours
julia> default(linecolor = 1)
julia> plot(rand(10, 2)) # one colour
julia> default()
julia> plot(rand(10, 2)) # still one colour
```

There doesn't seem to be a way to get back to an automatic color cycling after `default(linecolor)` has been set.

**Comment by daschw** [comment]
`Plots.reset_defaults()` does what you want, but we should document (and maybe export) this.

**Comment by daschw** [comment]
No, I think we should rather change `default` to behave the way you expected.

**Comment by daschw** [comment]
What would you expect the linewidth to be after
```julia
default(linewidth = 2)
default(linecolor = :black)
```
1 or 2?

**Comment by mkborregaard** [comment]
2

**Comment by daschw** [comment]
OK, so we should only reset the defaults if no kwarg is passed to `default` then.
