### ISSUE TITLE
Legend placing by legend=(x,y) not documented

### ISSUE THREAD

**Issue by jamblejoe** [JuliaPlots/Plots.jl#2613]
Hi,
the possibily to place legends by specifying coordinates is not documented. Further, it should be documented which corner of the legend is placed at (x,y), where the origin (0,0) is placed and in which direction the axis point. This is definitely too much for the table of the subplot attributes. Where should this information go?

Thanks so far the awesome work in this package!

**Comment by daschw** [comment]
I would just add it to the table, since this is the place where probably most people look for attributes documentation. Furthermore, this would also make it available in `plotattr`.
The place to add it would be here https://github.com/JuliaPlots/Plots.jl/blob/master/src/arg_desc.jl#L92.

**Comment by BeastyBlacksmith** [comment]
fixed by: https://github.com/JuliaPlots/Plots.jl/pull/2614
