### ISSUE TITLE
titlelocation not recognised alias for title_location

### ISSUE THREAD

**Issue by jamblejoe** [JuliaPlots/Plots.jl#2615]
Hi,
Shouldn't titlelocation be an alias for title_location? Or even more: shouldn't titlelocation be the standard (documentation-wise)? This would be consistent with: titlefontcolor, titlefontcolor, titlefonthalign, titlefontrotation, titlefontsize, titlefontvalign.

**Comment by daschw** [comment]
Yes, that would be more consistent. Thanks for the hint! At least we should have an alias titlelocation.
