### ISSUE TITLE
3D Subplot with 2D subplots has messed up layout for Plotly/PlotlyJS backend (3D plot appears in the center)

### ISSUE THREAD

**Issue by ElectronicTeaCup** [JuliaPlots/Plots.jl#2617]
**Describe the bug**

When I make subplots with a 3D plot, it becomes centralized in the collated output. It seems like PlotlyJS isn't inherently the problem(?) ([issue](https://github.com/sglyon/PlotlyJS.jl/issues/321)).
```
a = plot(rand(10))
b = plot(rand(10))
c = plot(rand(10))
d = plot(rand(10), rand(10), rand(10))

plot(a, b, c, d)
```
![image](https://user-images.githubusercontent.com/31346583/79767762-173d9b80-832a-11ea-9a43-683596a221a3.png)

**Version info**

Please provide the following:

1. output of julia command `versioninfo()`
```
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, broadwell)
```

2. Output running the following in Julia 0.7 or greater: `using Pkg; pkg"status"` (if you are on Julia 0.6 or earlier run `Pkg.status()`)
```  [c52e3926] Atom v0.12.10
  [94b1ba4f] AxisKeys v0.1.2
  [5ae59095] Colors v0.12.0
  [8f4d0f93] Conda v1.4.1
  [717857b8] DSP v0.6.4
  [31c24e10] Distributions v0.23.2
  [ccffbfc1] EDF v0.1.2
  [7a1cc6ca] FFTW v1.2.0
  [28b8d3ca] GR v0.48.0
  [6a3955dd] ImageFiltering v0.6.11
  [e5e0dc1b] Juno v0.8.1
  [23992714] MAT v0.7.0
  [442fdcdd] Measures v0.3.1
  [356022a1] NamedDims v0.2.21
  [47be7bcc] ORCA v0.3.1
  [5fb14364] OhMyREPL v0.5.5
  [f0f68f2c] PlotlyJS v0.13.1
  [91a5bcdd] Plots v1.0.11
  [438e738f] PyCall v1.91.4
  [295af30f] Revise v2.6.1
  [f3b207a7] StatsPlots v0.14.5
  [44d3d7a6] Weave v0.9.4
  [10745b16] Statistics
```

**Comment by daschw** [comment]
Thanks for reporting!

**Comment by dstorti** [comment]
I ran into the same problem today. Any chance someone has a fix for this in the works? (I put in a few blank plots so the relevant 2D plot was pushed off to the side and does not overlap with the central 3D plot but that is a very limited workaround.)
