### ISSUE TITLE
[BUG] errors in the scatterbins

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPlots/Plots.jl#2630]
```julia
plot(layout=grid(1,3), size=(1000,300),
    plot(1:11, 2:2:20,                        st=:scatterbins, lab=""),
    plot(1:11, 2:2:20, xerror = fill(0.5,10), st=:scatterbins, lab=""),
    plot(1:11, 2:2:20, xerror = fill(1.0,10), st=:scatterbins, lab="")
)
```
![image](https://user-images.githubusercontent.com/22725744/80284794-f5c12300-8720-11ea-8429-7034573d6922.png)
 - Errors do not appear at the first plot despite `xerror` specified in the recipe
https://github.com/JuliaPlots/Plots.jl/blob/master/src/recipes.jl#L537
 - It is asymmetric at the second and the third plot
 - something wierd is going on with the bin after the last.
The plot is also weird, but in a different way, if x is `1:10`.

### Backends

This bug occurs on

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |   x  |     |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: `  [91a5bcdd] Plots v1.0.14 `
Output of `versioninfo()`:
```
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\mikha\AppData\Local\atom\app-1.45.0\atom.exe"  -a
  JULIA_NUM_THREADS = 2
```

**Comment by mmikhasenko** [comment]
could be relevant:
```julia
@recipe function f(::Type{Val{:errorhist}}, x, y, z)
    h = Plots._make_hist((y,), plotattributes[:bins], normed = plotattributes[:normalize], weights = plotattributes[:weights])
    edge = collect(h.edges[1])
    x := Plots._bin_centers(edge)
    y := h.weights
    xerror := diff(edge)/2
    seriestype := :scatterpath
    ()
end
plot(layout=grid(1,2), size=(650,300),
    plot(rand(100), bins=10,              seriestype=:errorhist, lab=""),
    plot(rand(100), bins=10, xerror=true, seriestype=:errorhist, lab="") # true is not allowed value (does not matter what you specify)
)
```
![image](https://user-images.githubusercontent.com/22725744/80285142-37eb6400-8723-11ea-9624-1c18e47714c7.png)

I really do not understand what is going on with this recipe

**Comment by mmikhasenko** [comment]
@BeastyBlacksmith thanks for looking at it.
Is it really a bug in backends? Do you know of any recipe where `xerror/yerror` work?

**Comment by BeastyBlacksmith** [comment]
Ah, you are right, sorry. It is more likely the recipe

**Comment by BeastyBlacksmith** [comment]
Can you explain/show what the correct ouput would look like?

**Comment by mmikhasenko** [comment]
Yes, thanks for asking,
As far as I see from the code
https://github.com/JuliaPlots/Plots.jl/blob/master/src/recipes.jl#L537
the `scatterbins` should produce something like this:

![image](https://user-images.githubusercontent.com/22725744/80586879-ef2ef600-8a15-11ea-9c2d-2fbd9cd2eff4.png)



My hope was to extend it adding `yerror` and get this

![image](https://user-images.githubusercontent.com/22725744/80586835-d8889f00-8a15-11ea-9e7c-ff9a7354a303.png)
```julia
let # errrohist recipe
    h = Plots.StatsBase.fit(Plots.StatsBase.Histogram, rand(1000), 0:0.1:1)
    yerror = sqrt.(h.weights)
    ylim = (0, max((h.weights .+ yerror)...))
    scatter(Plots._bin_centers(h.edges[1]), h.weights,
        xerror=Plots.diff(h.edges[1])/2,
        ylim=ylim)
end
```

**Comment by BeastyBlacksmith** [comment]
> Does it appear in any tests?
Unfortunately not.

**Comment by BeastyBlacksmith** [comment]
> `plot(rand(100), bins=10, xerror=true, seriestype=:errorhist, lab="") # true is not allowed value (does not matter what you specify)`

You are right, that whatever you pass as `xerror` will be ignored, since it is set in the recipe with `:=`.

**Comment by mmikhasenko** [comment]
> > `plot(rand(100), bins=10, xerror=true, seriestype=:errorhist, lab="") # true is not allowed value (does not matter what you specify)`
> 
> You are right, that whatever you pass as `xerror` will be ignored, since it is set in the recipe with `:=`.

 - Do you understand why when nothing is passed the plot looks different?
 - Do you understand exactly is happening when the option `xerror` is passed, i.e. why there are two types of markers, what are the blue scattered points?

> There is a good blog post about recipes [here](https://daschw.github.io/recipes/#how_do_recipes_actually_work)

Thanks for the link, I saw it and liked it very much. I hope to come back to it for details at some point.

**Comment by BeastyBlacksmith** [comment]
Relatet: https://github.com/JuliaPlots/Plots.jl/blob/8976fc4ae479b792289ddbfea13662d90a1de5db/src/recipes.jl#L816

**Comment by BeastyBlacksmith** [comment]
I can't see anything wrong with the recipe itself so more likely a bug in the recipe pipeline itself. @daschw do you have an idea what is wrong here?

**Comment by BeastyBlacksmith** [comment]
FWIW: It is symmetric for`xerror` above 10

**Comment by mmikhasenko** [comment]
I have found something relevant:
 - There is a special series type for `xerror` where `xerror` arguments are processed by converting scatter points to the line segments. 
https://github.com/JuliaPlots/Plots.jl/blob/8976fc4ae479b792289ddbfea13662d90a1de5db/src/recipes.jl#L1056
```julia
h = plot(1:10, rand(10), xerror=fill(0.5, 10), st=:xerror)
h[1][1][:x] # [NaN, 0.500, 1.50, NaN, 1.50, 2.50, NaN, 2.50, 3.50, NaN, ...]
```
 - I am wondering if this always has to be done, i.e. the xerror arguments needs to be recognized and processed.
 - this conversion is not applied once the xerror are assigned in the series recipe as above
https://github.com/JuliaPlots/Plots.jl/issues/2630#issuecomment-619406170

**Comment by BeastyBlacksmith** [comment]
Good spot.
Please try out https://github.com/JuliaPlots/Plots.jl/pull/2665 and check if it is doing what it should.

**Comment by mmikhasenko** [comment]
right, I will check asap

I wrote something similar for my `errorhist`.
```julia
@recipe function f(::Type{Val{:errorhist}}, x, y, z)
    h = Plots._make_hist((y,), plotattributes[:bins], normed = plotattributes[:normalize], weights = plotattributes[:weights])
    edge = collect(h.edges[1])
    centers = Plots._bin_centers(edge)
    dx = Plots.diff(h.edges[1])/2
    x := centers
    y := h.weights
    seriestype := :scatter
    @series begin
        seriestype := :xerror
        xerror --> dx
        yerror --> sqrt.(h.weights)
        (centers, h.weights)
    end
    @series begin
        seriestype := :yerror
        yerror --> sqrt.(h.weights)
        (centers, h.weights)
    end
    ()
end
plot(randn(1000), bins=40, seriestype=:errorhist, lab="data") # I do now want to say m=(3,:black,stroke(:black,1))
```
![image](https://user-images.githubusercontent.com/22725744/80964277-dc9b2f00-8e10-11ea-8077-e11a45473f6e.png)

The only problem with it is default colors.

**Comment by BeastyBlacksmith** [comment]
That's https://github.com/JuliaPlots/Plots.jl/issues/2429 ._.
You can work around as @daschw showed in the discourse thread, but eventually it should be fixed.

**Comment by mmikhasenko** [comment]
Thank you for the references. I have never used `line_z` option. Interesting.

However, if I got it right, here the problem is slightly different: there are just three series (`xerror`, `yerror`, and `scatter`) and they are colored according to the palette incrementing the color index.

If I can say in recipe, use the same "color of the current order from the palette" for all three series, it would solve my remaining problem. Would you know how to reference this color in `linecolor :=`?

**Comment by BeastyBlacksmith** [comment]
Currently there is no nice way of doing this.
You can access the plot object via `plotattributes[:plot_object]` and get the information you need for that somehow, but there may be dragons on the way.
I strongly suggest to instead just set a default color via `seriescolor --> :black` and then you can override it at the call site if you need a different color.

**Comment by mmikhasenko** [comment]
ok, thanks a lot! just confirm that `scatterhist` works now.
```julia
plot(randn(1000), st=:scatterhist)
``` 
![image](https://user-images.githubusercontent.com/22725744/80991512-76c29d80-8e38-11ea-96b1-4ba750abd883.png)
just color of the error bars is awkward as we already discussed.

**Comment by daschw** [comment]
Doesn't `primary := false` in an `@series` block help with not changing the series color?

**Comment by mmikhasenko** [comment]
Aha! 👍 it does, just the order should be the opposite.
green is the color that comes somewhat before the first color in the palette, blue.

The colors would be correct if `primary := false` for the main series and `primary := true` for @series macro. However, I think there should be a proper way to do it.

**Comment by mmikhasenko** [comment]
it seems to be a common problem,
```julia
plot(1:10, 2:2:20, st=:scatterpath)
```
![image](https://user-images.githubusercontent.com/22725744/81009941-cc597300-8e55-11ea-8caa-3983d1d11341.png)
