### ISSUE TITLE
[BUG]Can't use Plots package in Jupyterlab but can use in REPL

### ISSUE THREAD

**Issue by CearthCao** [JuliaPlots/Plots.jl#2632]
Please search existing issues to avoid duplicates.
When I use Plots in jupyter, every time I got a FFMPEG problem, but in REPL, I can plot everything
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version:
Backend  version:
Output of `versioninfo()`:

**Comment by BeastyBlacksmith** [comment]
What is the version of your jupyter kernel and the one of your REPL version?
