### ISSUE TITLE
[BUG] clibrary() function disappeared between Plots 1.0.14 and 1.1

### ISSUE THREAD

**Issue by JeffFessler** [JuliaPlots/Plots.jl#2634]
Please search existing issues to avoid duplicates.

## Details

The function `clibrary()` seems to have disappeared between Plots 1.0.14 and 1.1 yet I can't find any discussion of it in issues or PRs and the documentation still refers to it:
https://docs.juliaplots.org/latest/colors/#

I've tested it with gr (default) only.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.1

Backend  version: whatever is the default with 1.1 because I have tested in this after a fresh "activate ." with just `add Plots@1.0` vs `add Plots`

Output of `versioninfo()`:

Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8

**Comment by BeastyBlacksmith** [comment]
That is expected. That function was reexported from PlotUtils and got deleted in https://github.com/JuliaPlots/PlotUtils.jl/pull/87.
And with 1.1.0 we moved all the color related functionality to ColorSchemes.jl

**Comment by JeffFessler** [comment]
I see.  Thanks for the pointer.
I had searched the PRs for Plots.jl, but not the PRs for PlotUtils.jl.
(I wonder if there is a way to search all the packages below JuliaPlots at once.)
I guess the main remaining issue is updating the docs.  I would offer to help but I don't understand colors well enough to do it properly.

**Comment by daschw** [comment]
Docs will be updated soon.

**Comment by daschw** [comment]
http://docs.juliaplots.org/latest/generated/colorschemes/

**Comment by JeffFessler** [comment]
And now I can just use `color=:hsv` without needing `clibrary` or `ColorGradient` etc. - Yay!

**Comment by daschw** [comment]
Glad to hear it's useful!

**Comment by daschw** [comment]
Btw, if you have suggestions for the colorschemes section in the docs, input is very welcome. That's just my first quick write-up, so let me know if anything is unclear.

**Comment by isentropic** [comment]
Docs looking really good @daschw ! Especially the heatmap.
