### ISSUE TITLE
z-axis guidefontrotation only works for short labels

### ISSUE THREAD

**Issue by ric-cioffi** [JuliaPlots/Plots.jl#2641]
I was very happy to see #2565, but I noticed that on a surface plot it only works for very short labels (this doesn't seem to be an issue in 2D). MWE:

```
using Plots
pyplot()

#this works
plot(rand(10), rand(10), rand(10), st = :surface, zguide = "Da", zguidefontrotation = 90)

#this doesn't
plot(rand(10), rand(10), rand(10), st = :surface, zguide = "Daaaaaa", zguidefontrotation = 90)
```

**Comment by isentropic** [comment]
![image](https://user-images.githubusercontent.com/24591123/80447851-8f711600-8955-11ea-96eb-7e50ff99b22a.png)
What is the issue?

**Comment by ric-cioffi** [comment]
Maybe 90 is an unfortunate rotation as it is not obvious what is the correct angle. Let's try with 180.

---
When I run this: 
```
plot(rand(10), rand(10), rand(10), st = :surface, zguide = "aaaa", zguidefontrotation = 180)
```
I get
![correct](https://user-images.githubusercontent.com/24350113/80504252-e15b7100-8940-11ea-85cc-ad3e50059bbe.png)

While, running this (adding one extra ```a``` to the zguide)
```
plot(rand(10), rand(10), rand(10), st = :surface, zguide = "aaaaa", zguidefontrotation = 180)
```
gets me
![wrong](https://user-images.githubusercontent.com/24350113/80504274-e7e9e880-8940-11ea-9d14-b42eda17875f.png)

---
This  does not seem to happen with a 2D plot, as the latter seems to be adding extra padding next to the axis to accommodate a larger label.

**Comment by isentropic** [comment]
I completely baffled by this, do you know if this happens in pure pyplot?

**Comment by ric-cioffi** [comment]
No idea, I've never used pure PyPlot so I'm not even sure what the syntax would be

**Comment by ric-cioffi** [comment]
Actually, the problem doesn't have anything to do with `guidefontrotation`. It looks like it just cannot write a long-enough label on the z-axis
```
plot(rand(10), rand(10), rand(10), st = :surface, zguide = "aaaa")
```
![correct](https://user-images.githubusercontent.com/24350113/80534009-8b9cbe00-896c-11ea-9aee-d2623615eb69.png)

```
plot(rand(10), rand(10), rand(10), st = :surface, zguide = "aaaaa")
```
![wrong](https://user-images.githubusercontent.com/24350113/80534031-96efe980-896c-11ea-88fb-90b1453a93f9.png)

**Comment by isentropic** [comment]
@ric-cioffi Please check out the #2667 and please provide some feedback on the implementation. To do so you would need to clone the fork and test this

**Comment by ric-cioffi** [comment]
Awesome. Thanks a lot!

It's working great for me.
