### ISSUE TITLE
[BUG] Plots + PlotlyJS + LaTeX

### ISSUE THREAD

**Issue by otobrzo** [JuliaPlots/Plots.jl#2642]
## Details
I love PlotlyJS interactivity mainly in Jupyter notebook or VS Code Plot pane, on the other hand, I had always problems with latex in labels.

Recently, I noticed that in one of my julia environment (Julia 1.3.1, jupyter 2.0.0, plotly extension) the LaTeX rendering in Jupyter notebook just works

```julia
using Plots, LaTeXStrings

fontt = Plots.font("arial", 12)

plotlyjs(guidefont=fontt, xtickfont=fontt, 
   ytickfont=fontt, legendfont=fontt, lw = 2, size=(600,400));

p = plot(rand(10))
p = xlabel!("\$\\alpha \\, F_\\mathrm{test}\$")
p = ylabel!(L"\Gamma^2")

plot(p)
```
![Unknown](https://user-images.githubusercontent.com/16555995/80463236-3777e680-8938-11ea-955c-338a10dc778a.png)

Generally,  I always got (in other jupyters, VS Code plot pane, etc.) st like this

![Unknown-2](https://user-images.githubusercontent.com/16555995/80463338-5eceb380-8938-11ea-9d32-e26335ee47c5.png)

In that specific jupyter notebook I was able to save it to PDF but with wrong LaTeX rendering.

I saved the figure to html format and again the LaTeX rendering did not work.
To get the LaTeX rendering to work I needed to follow instructions [here](https://github.com/plotly/plotly.js/blob/master/dist/README.md#to-support-mathjax ) 

Original HTML HEAD was

```html
<head>
        <title>Plots.jl</title>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
```

the working html head follows:
```html
<head>
         <title>Plots.jl</title>
         <meta http-equiv="content-type" content="text/html; charset=UTF-8">
         <script src="mathjax/MathJax.js?config=TeX-AMS-MML_SVG"></script>
         <script>
            window.PlotlyConfig = {MathJaxConfig: 'local'}
         </script>
         <script src="plotly.js"></script>
</head>
```
but you need to download plotly.js and mathjax locally (or link the header to web)

### Versions

Plots.jl version: Plots v1.1.1
Backend  version: PlotlyJS v0.13.1, WebIO v0.8.13
Output of `versioninfo()`: 

Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)

**Comment by paulnakroshis** [comment]
How does one upgrade plotlyjs in Julia to 2.6.3? My version in Julia 1.7 is PLotlyJS v0.18.8
I'd love to have the LaTeX integration fix! :-)
