### ISSUE TITLE
[BUG] Surface + PyPlot + Themes

### ISSUE THREAD

**Issue by atgmello** [JuliaPlots/Plots.jl#2647]
## Details

`surface` plots using `pyplot` backend plus `:bright`, `:vibrant` or `:mute` themes causes jumbled plot colors.

```julia
import Plots
Plots.pyplot()
Plots.theme(:vibrant)
x = collect(-10:10)
y = collect(-10:10)
z = (x,y) -> (x-y)^2
Plots.surface(x,y,z)
```

![bug](https://user-images.githubusercontent.com/4420461/80528788-de767580-896c-11ea-83fe-dd9ca0612572.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |   x  |
pyplot       |  x   |     |
plotly       |     |   x  |
plotlyjs     |     |   x  |
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.1.2 [91a5bcdd]
Output of `versioninfo()`:

```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 16
```

**Comment by isentropic** [comment]
@atgmello I advise against using these themes (:bright, :vibrant or :mute) in general 

And perhaps we have to deprecate them as they are not even themes, but just colormaps @daschw ?

I suggest using this
```
surface(x,y,z, c=:balance)
```
![image](https://user-images.githubusercontent.com/24591123/80995777-c4132f00-8e79-11ea-9f66-1118f2e26243.png)

For more details, go to http://docs.juliaplots.org/latest/generated/colorschemes/

![image](https://user-images.githubusercontent.com/24591123/80995683-9e862580-8e79-11ea-82de-5965da34f0bf.png)

**Comment by atgmello** [comment]
Yeah, this is enough for what I need! Thanks for the tip @isentropic .
