### ISSUE TITLE
[BUG] seriestype=:shape does not treat vector of colors correctly

### ISSUE THREAD

**Issue by natschil** [JuliaPlots/Plots.jl#2649]
## Details
When using `seriestype=:shape`, the color/fillcolor/alpha used is the first one in the vector. Here is a minimal non-working example:
```
Plots.plot([[1.0,2.0,3.0],[4.0,5.0,6.0]],[[1.0,3.0,4.0],[8.0,9.0,11.0]],seriestype=:shape
	,fillcolor=[:green,:blue])
```
![output](https://user-images.githubusercontent.com/3118879/80655285-8d56a680-8a7e-11ea-8420-ed001164ea45.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |  x   |     |
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: v"0.29.9"

Backend  version: GR v"0.48.0"

Output of `versioninfo()`:
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

**Comment by BeastyBlacksmith** [comment]
For that you need to use a row vector:
```julia
Plots.plot([[1.0,2.0,3.0],[4.0,5.0,6.0]],[[1.0,3.0,4.0],[8.0,9.0,11.0]],seriestype=:shape
	,fillcolor=[:green :blue])
```
Note the space.
