### ISSUE TITLE
Axis tick labels in scientific format throws GKS unicode error 

### ISSUE THREAD

**Issue by karenml** [JuliaPlots/Plots.jl#2654]
Using default GR backend for Plots. I get an error when my axis tick labels are in scientific format. I get "GKS: character ignored due to unicode error"
`plot([1000000*x for x in 1:10], xlabel=L"\mathrm{Re}", ylabel=L"\mathrm{Im}")
title!(L"\lambda_{\alpha,\omega, z_{0}}")`
<img width="691" alt="Screenshot 2020-04-30 at 14 40 30" src="https://user-images.githubusercontent.com/9300157/80717249-9718f200-8af0-11ea-9710-0ee7ec4fcabc.png">

What I've tried so far is:
- updated all packages and consequently built IJulia again
- uninstalled everything, then reinstalled, updated and built again
- installed new version of Julia, so I'm now in Julia 1.4.1
- ENV["GRDIR"] = ""; ]build GR

and it still doesn't work

**Comment by daschw** [comment]
Does `ENV["GKS_ENCODING"] = "utf-8"` help?

**Comment by karenml** [comment]
> Does `ENV["GKS_ENCODING"] = "utf-8"` help?

Just tried it and I still get the above error

**Comment by karenml** [comment]
Sorry @daschw, you were right. I found this https://github.com/JuliaPlots/Plots.jl/issues/791#issuecomment-619243302
You have to set the variable before using Plots:
`ENV["GKS_ENCODING"] = "utf-8"`
`Using Plots`
<img width="467" alt="Screenshot 2020-05-01 at 09 01 39" src="https://user-images.githubusercontent.com/9300157/80791756-87e68280-8b8a-11ea-8b5f-ba8e07d7e40c.png">

**Comment by daschw** [comment]
Glad you could fix it!
