### ISSUE TITLE
Switch to GeometryBasics?

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Plots.jl#2656]
The Makie ecosystem has made that switch, it might be useful for Plots to do so also.  The API is mostly the same.

**Comment by daschw** [comment]
You mean instead of GeometryTypes?

**Comment by asinghvi17** [comment]
Yep, I happened to come across some GeometryTypes code when looking through Plots.

**Comment by daschw** [comment]
I think it's only for a `GeometryTypes.Point` recipe. Plots does not really depend on GeometryTypes in the code, we just have the dependency to support plotting `Point`s.

**Comment by mkborregaard** [comment]
Yes but it should be `GeometryBasics.Point` today. The geometry ecosystem is being refactored.

**Comment by mkborregaard** [comment]
I think the JuliaGeometry guys should send PRs to packages depending on GeometryTypes to update though. We don't need two different implementations of `Point` in the ecosystem...

**Comment by jeremiedb** [comment]
@daschw Any update on that end? My understanding is that `GeometryTypes` is being deprecated in favor of `GeometryBasics`, so it should be possible to simply drop dependence on it. 
I was actually looking to use the Bezier Curve functionality: https://github.com/JuliaPlots/Plots.jl/blob/17acb456538ced66ec8c2a1c054e221c72b747e6/src/components.jl#L732, 
It looks like BezierCurve is the only component in the package that depends on `GeometryTypes`.
