### ISSUE TITLE
[BUG] LaTeXStrings displayed in low quality with GR backend

### ISSUE THREAD

**Issue by mroavi** [JuliaPlots/Plots.jl#2660]
## Details
LaTeXStrings are displayed in low quality when using GR as backend and a theme other  than `:default`:
```julia
using Plots, LaTeXStrings
gr() ; theme(:juno)
plot(sin, title=L"F(\omega) = \int \! f(t)e^{-j \omega t}\mathrm{d}t", label=L"F(\omega)")
```
![image](https://user-images.githubusercontent.com/19517248/80824793-7085b480-8bdf-11ea-9149-e9b925f83c6c.png)

```julia
using Plots, LaTeXStrings
gr() ; theme(:solarized)
plot(sin, title=L"F(\omega) = \int \! f(t)e^{-j \omega t}\mathrm{d}t", label=L"F(\omega)")
```
![image](https://user-images.githubusercontent.com/19517248/80824843-83988480-8bdf-11ea-9672-89f850119a7c.png)

The strings seem to be displayed fine with with the `:default` theme:
```julia
using Plots, LaTeXStrings
gr() ; theme(:default)
plot(sin, title=L"F(\omega) = \int \! f(t)e^{-j \omega t}\mathrm{d}t", label=L"F(\omega)")
```
![image](https://user-images.githubusercontent.com/19517248/80824926-aa56bb00-8bdf-11ea-83e2-cb70cafb655c.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |  x   |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: v0.29.7
Backend  version: v0.47.0
Output of `versioninfo()`:
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 4

**Comment by daschw** [comment]
I think that's fixed in the current release. Could you try updating Plots?

**Comment by mroavi** [comment]
I wasn't aware I was running such an old version of Plots.jl. You are right, this works fine with the latest version.
