### ISSUE TITLE
How to save html file from plotly but also never open it in browser

### ISSUE THREAD

**Issue by zamlz** [JuliaPlots/Plots.jl#2664]
I can't seem to find a way to generate a plot with the plotly backend and then save the html file into a specific file. More importantly, I don't want it to open up the browser everytime, is there a way I can disable that?

**Comment by BeastyBlacksmith** [comment]
you can use `;` to suppress the display.
```julia
using Plots
plotly()
plot(1:5);
savefig("test.html")
```

**Comment by BeastyBlacksmith** [comment]
If that didn't work please report back

**Comment by zamlz** [comment]
Thank you, that did work. I didn't expect the semicolon would be able to
suppress it. I was under the impression that it suppressed console output
from commands. Very cool feature indeed.
