### ISSUE TITLE
[FR] Creating MATLAB Plotting Backend for Plots

### ISSUE THREAD

**Issue by RoyiAvital** [JuliaPlots/Plots.jl#2672]
MATLAB has interactive abilities in its `Figure` window which I can't reproduce in Julia.
How easy it is to walk through the pixels value of mapped image, jump across points in scatter, zoom in and & out, etc...

Just like we have a backend for Matplotlib using `PyPlot` which uses `PyCall` can we have `MatlabPlot` using [`MATLAB.jl`](https://github.com/JuliaInterop/MATLAB.jl)?

**Remark**  
I'd be happy to know I'm wrong and there is such capability.
I tried `PyPlot`, and `Plots` and the closest I got is using `PlotLy` through `PyCall`. Yes I still find MATLAB's figure element to be more reactive for exploration of the data.

**Comment by mkborregaard** [comment]
I don't think anyone in the JuliaPlots org are likely to devote the work it takes to a build and maintain a backend for matlab. I'd suggest you use https://github.com/JuliaInterop/MATLAB.jl to call Matlab from Julia.
