### ISSUE TITLE
[BUG] Reversed palettes don't work after update to Julia 1.4.1 on Win10

### ISSUE THREAD

**Issue by Eben60** [JuliaPlots/Plots.jl#2674]
## Details
trying to use `seriescolor=:YlOrRd_r` or `:RdYlGn_r` results in:
`ERROR: LoadError: Unknown color: RdYlGn_r`
`:YlOrRd` or `:RdYlGn` are OK

The problem didn't occure on the same computer with Julia 1.3.0 and doesn't occure on a Mac with Julia 1.4.1

**EXAMPLE**

```
using Plots
gr()
sz=10
ar = zeros(sz,sz)
for i in 1:sz, j in 1:sz
    ar[i,j]=round(sqrt((i)*(j))*0.5)
end
heatmap(ar, seriescolor=:RdYlGn_r) # ERROR

```
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |  x   |     |
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: 1.2.2
Backend  version: GR 0.49.1
Output of `versioninfo()`:
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\eben60\AppData\Local\atom\app-1.46.0\atom.exe"  -a
  JULIA_NUM_THREADS = 4

**Comment by daschw** [comment]
Yes, the palette integration has changed a little. You can use e.g. `cgrad(:YlOrRd, rev = true)`, see http://docs.juliaplots.org/latest/generated/colorschemes/.

**Comment by Eben60** [comment]
**daschw** , thank you for your advise - it works.
