### ISSUE TITLE
Warnings for moved recipes check Main only

### ISSUE THREAD

**Issue by pearlzli** [JuliaPlots/Plots.jl#2678]
I'm developing a module Foo that is `using` both Plots and StatsPlots, and in it I have a function `my_boxplot` which calls `boxplot`. If I run

```
using Foo
my_boxplot()
```

then I get the following warning because I haven't also run `using StatsPlots`.

https://github.com/JuliaPlots/Plots.jl/blob/3d693d88e07b0d61c7f501cfe1b65baaabe57337/src/args.jl#L1113-L1115

Can this warning be turned off if StatsPlots is already being used by the module?

**Comment by mkborregaard** [comment]
could it work to express your code as recipes instead?

**Comment by daschw** [comment]
I think we can remove this warnings generally, no? These seriestypes are in StatsPlots for a very long time now.

**Comment by pearlzli** [comment]
@mkborregaard Unfortunately, I still get the warning when I use a recipe instead.

MWE: I use `Pkg.generate` to make a new package called Foo and `Pkg.add` Plots and StatsPlots as dependences. I change the contents of src/Foo.jl to

```
module Foo

using Plots, StatsPlots

@userplot MyBoxplot

@recipe function f(p::MyBoxplot)
    @assert length(p.args) == 2
    x, y = p.args

    seriestype := :boxplot
    title --> "My Boxplot"
    x, y
end

end # module
```

Then I run

```
(v1.3) pkg> activate .
Activating environment at `~/Desktop/Foo/Project.toml`

julia> using Foo
[ Info: Precompiling Foo [4d9c1f16-99de-4079-a5d7-6a6f8588457e]

julia> Foo.myboxplot(repeat([1,2,3], outer = 100), randn(300))
┌ Warning: seriestype boxplot has been moved to StatsPlots.  To use: `Pkg.add("StatsPlots"); using StatsPlots`
└ @ Plots ~/.julia/packages/Plots/V8QVi/src/args.jl:1114
```

**Comment by mkborregaard** [comment]
Looks like @daschw has solved it :-)

**Comment by mkborregaard** [comment]
But btw `using RecipesBase` should be sufficient, and just remind people to be loading StatsPlots to use it. That's the intention of the warning - so that users of your recipe will be told to load StatsPlots.

**Comment by pearlzli** [comment]
Thanks!

**Comment by daschw** [comment]
So I decided not to remove the warning. I really recommend the suggestion of @mkborregaard to not depend on Plots and StatsPlots in your module, only on RecipesBase:
```julia
module Foo

using RecipesBase

@userplot MyBoxplot

@recipe function f(p::MyBoxplot)
    @assert length(p.args) == 2
    x, y = p.args

    seriestype := :boxplot
    title --> "My Boxplot"
    x, y
end

end # module
```
```julia
using Foo, StatsPlots

myboxplot(...)
```

**Comment by pearlzli** [comment]
Sure, sounds good. Is there anywhere I can read about the philosophy behind not adding Plots and StatsPlots as package dependencies? (In my case, I'm developing a module of which I'm also the only user.)

**Comment by isentropic** [comment]
In my opinion, it does not to be a module if you are the only user, if you want all to use all the packages, then have like `include("mymainfile.jl")` that includes the rest of your files. In opinion having a module for personal project only makes it more difficult with exports and namespaces
