### ISSUE TITLE
[BUG] group and error bar not working together in new version

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaPlots/Plots.jl#2686]
```
xs = collect(1:100)
μs = log.(xs)
σs = rand(length(xs))
scatter(xs,μs,grid=false,yerror=(σs,σs),group=xs)
```
This code works perfect fine before I update (can't remember which version was using). Now it keeps reporting 

```
MethodError: no method matching split_attribute(::Symbol, ::Array{Float64,1}, ::Array{Int64,1})
Closest candidates are:
  split_attribute(::Any, ::Any, ::AbstractArray, !Matched::Any) at C:\Users\JD\.julia\packages\RecipesPipeline\2pkja\src\api.jl:34
  split_attribute(::Any, ::Any, !Matched::Tuple, !Matched::Any) at C:\Users\JD\.julia\packages\RecipesPipeline\2pkja\src\api.jl:36
  split_attribute(!Matched::Plots.Plot, ::Any, !Matched::Plots.SeriesAnnotations, !Matched::Any) at C:\Users\JD\.julia\packages\Plots\V8QVi\src\pipeline.jl:52
```
However, it works if not using `group`
```
scatter(xs,μs,grid=false,yerror=(σs,σs))
```
or if only use one vector for error bar
```
scatter(xs,μs,grid=false,yerror=σs,group=xs)
```
Problems with the new version?

**Comment by JianghuiDu** [comment]
OK, just tried version 1.0.0. No problem there.

**Comment by JianghuiDu** [comment]
Why closed? It worked on 1.0.0 but not recent versions... Are there already solutions? I didn't find that.

**Comment by BeastyBlacksmith** [comment]
A sorry, I misread that. I thought it failed on a version older than 1.0.0

**Comment by BeastyBlacksmith** [comment]
Can you try passing a vector of tuples rather than a tuple of vectors?

**Comment by JianghuiDu** [comment]
Vector of tuples work! So something must have changed... And in the docs it is still `AbstractVector or 2-Tuple of Vectors`.

**Comment by BeastyBlacksmith** [comment]
should be fixed
