### ISSUE TITLE
Colorbar issue for  side by side contours plot with Plotly.

### ISSUE THREAD

**Issue by kruxigt** [JuliaPlots/Plots.jl#2691]
Hi!

When using Plotly as backend and try to plot two contour plots side by side, each with its own colorbar, the two colorbars seem to appear on top of each other. 

The same behaviour/bug can even be seen on the [Plotly example page](http://docs.juliaplots.org/latest/generated/plotly/#plotly-ref22-1).

Can I do something to fix this or will it be fixed in upcoming updates of the library?

**Comment by BeastyBlacksmith** [comment]
If you have experience with plotly we welcome PRs.
I don't know of anyone actively working on the plotly-backend at the moment

**Comment by kruxigt** [comment]
Which backend would you say is the most actively used one for scientific
work?

**Comment by BeastyBlacksmith** [comment]
We don't have statistics. For sure the gr-backend is the most used, since it os the default. pgfplotsx and pyplot are the ones with the most recent development. Just give it a try. Switching backends is easy to do.

**Comment by kruxigt** [comment]
I started out trying Pyplot (coming from Python before Julia for same kind
of work) then tried GR and then Plotly and stuck with it since it seemed to
work out best for me at that time ( 6-12 months ago). Maybe I should give
outer backends a go again.
