### ISSUE TITLE
Backend  mess again

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#2698]
For months I've been getting this warning in both the REPL and Jupyter when doing plots using the pyplot backend:
```
Warning: _display is not defined for this backend.
└ @ Plots ~/.julia/packages/Plots/zOV0T/src/output.jl:194
```
I haven't done anything about it because just running the plot again always solves it, but I don't know why it is happening.
In Juno, the problem is more severe because I also get this:
```
julia> cumplot(series,38015,geo=geo)
sys:1: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```
cumplot is a function that creates the plot. This problem does NOT occur in the REPL or in Jupyter, but does in Juno/Atom.

In my matplotlibrc file I have:
```
backend :  Qt5agg   
```

For some reason, this is degenerating to Agg.

The plots API doesn't let me see what backend pyplot thinks it is actually using so I can't tell if my Python install is messing up or not.

Some kind of passthrough to PyPlot of literal commands would help here because the dependency stack is pretty deep: plots, PyPlot.jl, Python, matplotlib, Qt,...

**Comment by isentropic** [comment]
Does pure `pyplot` work for you?

**Comment by BeastyBlacksmith** [comment]
> Some kind of passthrough to PyPlot of literal commands would help here

That should be possible when https://github.com/JuliaPlots/Plots.jl/issues/2648 gets implemented for the pyplot-backend.

**Comment by lewisl** [comment]
Nice!  Look forward to it.  PyPlot improved its passthrough so this should be doable.

**Comment by lewisl** [comment]
I’ve tried to focus on “one way” whether it’s the best way or not—for my own depth of practice and for consistency in my own code.

I’ll give it a shot because it may help understand whether the problem is in pyplot or plots.

**Comment by lewisl** [comment]
I still get this when I use a function that does a plot via a complex module:

```
┌ Warning: _display is not defined for this backend.
└ @ Plots ~/.julia/packages/Plots/Vfmes/src/output.jl:194
```
In the REPL, I cannot reproduce it.  It is a lot of work to redo the module to use pyplot as the plot is non-trivial to create.
I've looked at the sequence in the src of plots.  Here is the function where the error occurs:
```
function _display(plt::Plot)
    @warn("_display is not defined for this backend.")
end
```
So, something when the plt is a typeof(Plot).
There is only one caller of this function, which creates a new method for display:
```
function Base.display(::PlotsDisplay, plt::Plot)
    prepare_output(plt)
    _display(plt)
end
```
This is only called by a method for gui and I do use gui because it seems like the only way to get the plot to reliably appear when the code runs from the REPL though documentation says that is unnecessary. This aspect of all Julia plotting, regardless of package, seems to be very inconsistent.  That method is:
```
gui(plt::Plot = current()) = display(PlotsDisplay(), plt)
```
This gets called in two methods here:
```
_do_plot_show(plt, showval::Bool) = showval && gui(plt)
function _do_plot_show(plt, showval::Symbol)
    showval == :gui && gui(plt)
    showval in (:inline, :ijulia) && inline(plt)
end
```

And that's where it all stops.  The problem occurs in the REPL and Jupyter.  I don't expect anyone to diagnose my plot code, but here it is, below.  I am going to try moving ```pyplot()``` to immediately following ```using Plots```. And, I'll try again without explicitly calling ```gui()```.

Will report back...

```
function cumplot(series, locale, plcols=[unexposed, infectious, recovered, dead]; days="all",geo=[])

    pyplot()
    theme(:ggplot2, foreground_color_border =:black, reuse = false)

    !(typeof(plcols) <: Array) && (plcols = [plcols])

    # the data
    n = size(series[locale][:cum],1)
    days = days == "all" ? (1:n) : days
    cumseries = series[locale][:cum][days, [map2series[i][total] for i in plcols]]

    # labels and annotations
    labels = [titlecase(condnames[i]) for i in plcols]
    labels = reshape([labels...], 1, length(labels))
    people = series[locale][:cum][1, map2series[unexposed][total]] + series[locale][:cum][1,map2series[infectious][total]]
    cityname = !isempty(geo) ? geo[geo[:,fips] .== locale, city][1] : ""
    died = series[locale][:cum][end, map2series[dead][total]]
    infected = series[locale][:cum][1,map2series[unexposed][total]] - series[locale][:cum][end,map2series[unexposed][total]]
    firstseries = plcols[1]
    half_yscale = floor(Int, maximum(series[locale][:cum][:,map2series[firstseries][total]]) * 0.7)
 

    # the plot
    plot(   days, cumseries[days,1:end], 
            size = (700,500),
            label = labels, 
            lw=2.3,
            title = "Covid for $people people in $cityname over $n days\nActive Cases for Each Day",
            xlabel = "Simulation Days",
            ylabel = "People",
            legendfontsize = 10,
            reuse = false
        )
    annotate!((6,half_yscale,Plots.text("Died: $died\nInfected: $infected", 10, :left)))
    gui()
end
```

**Comment by lewisl** [comment]
So, invoking ```pyplot()``` in the file that contains the module definition has no effect on code that is included from a different source file. Apparently(?) the pyplot() request must be in at least one included source file to be "seen."  That is sort of strange.  Makes it seem like code in a module is a bit of a noop.

So, I got the default gr() backend, which looks absolutely fine but doesn't not support "close"--not ever for years. So, I won't use it.  Note that a gr() request does NOT occur anywhere--so I am just getting gr as the default backend for Plots. 

So, I'll try another random place for the pyplot() request.

**Comment by lewisl** [comment]
So this is interesting. Right after the above, because Revise is running (yeah!), I deleted the pyplot() at the top of the included file and put it back into the function (which I pasted above). 

The first time pyplot was invoked (each time I quit Julia, start Julia, using <mypackage>) AFTER plots had successfully plotted with gr, the plot was created with pyplot without the _display warning.  This makes me suspect that this has something to do with Plots startup and not with pyplot.

**Comment by BeastyBlacksmith** [comment]
This is a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2407. For now, it is not recommended to put the backend switching methods like `pyplot()` inside functions, but only put them in top level code.

**Comment by lewisl** [comment]
OK.  Good advice.  It didn’t seem to work in a source file.  But, I will experiment some more.

**Comment by lewisl** [comment]
This problem went away.  It turns out I must have pyplot() in a function or it doesn't work. Putting it into the module definition does not work.  Put it at the top of a source file included in the module doesn't work. I tried both of the latter.

But, I wonder if it had nothing to do with the problem.  Somewhere along the way some other changes made in plots or pyplot took care of it.  First time plots now work in both the repl and Jupyter without the _display error.  Plots v1.2.6 and PyPlot v2.9.0

You are right that it was a dupe of #2407 (I feel slightly less nooby that someone else found it sooner!).  I suspect you can try to repro #2407 and it will be gone, too.  Might be worth looking at commits to see what might have been the change that solved it.
