### ISSUE TITLE
Aspect ratio and label outside plot

### ISSUE THREAD

**Issue by cossio** [JuliaPlots/Plots.jl#2701]
```julia
plot(identity, 0, 1, xlim=(0,1), ylim=(0,1), label="sin and many many many long words",
    legend=:outerbottomright, aspect_ratio=1)
```

![image](https://user-images.githubusercontent.com/10637482/81857369-7a55d300-9562-11ea-9fee-a7cb1d29cf7d.png)

Is there a way to set an aspect ratio that only considers the space of the plot itself? Here it seems to be considering also the space taken by the label which falls outside the plot, and the result is not good.

**Comment by BeastyBlacksmith** [comment]
I would say this is an issue with the `outer` legend implementation of the GR-backend, since PyPlot and PGFPlotsX doesn't show this behaviour

**Comment by luboshanus** [comment]
Anything new on this? 

Related to https://github.com/JuliaPlots/Plots.jl/issues/3371

**Comment by t-bltg** [comment]
What about adding a newline in the label ?

```julia
using Plots; gr()

plot(
  identity, 0, 1, xlim=(0, 1), ylim=(0, 1),
  label="sin and many many\n many long words",
  legend=:outerbottomright, aspect_ratio=1
)
png("label")
```
![label](https://user-images.githubusercontent.com/13423344/124649980-7b01a500-de99-11eb-902c-a36ceb8a8527.png)

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/4496.
