### ISSUE TITLE
[BUG] GR error with Latex strings, pyplot crash.

### ISSUE THREAD

**Issue by pcjentsch** [JuliaPlots/Plots.jl#2715]
This might be two different bugs, but they all appeared at roughly the same time.

First, GR gives plotting errors when using strings with latex in them.

```
julia> using Plots
julia> plot([1,2],title = "test \$\\alpha\$")       
GKS: Rectangle definition is invalid in routine SET_VIEWPORT

```

The following crashes the REPL, it appeared after I installed StatsPlots, but has persisted with a reinstall of Plots and removal of StatsPlots.

```
julia> using Plots
julia> pyplot()
Plots.PyPlotBackend()
julia> plot([1,1])
```
VScode outputs
```
The terminal process terminated with exit code: 3221225477
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x   |     |
pyplot       |    x  |     |
plotly       |      |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: v1.3.0
Backend  version: PyPlot v2.9.0, not sure how to get GR version
Output of `versioninfo()`:
```
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz    
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\peter\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS = 4
```

**Comment by BeastyBlacksmith** [comment]
I can't reproduce the PyPlot crash in the REPL, so might be an iteraction with VSCode
