### ISSUE TITLE
[BUG] ColorGradient can not be constructed in Plots.

### ISSUE THREAD

**Issue by babaq** [JuliaPlots/Plots.jl#2716]
```julia
using Plots
ColorGradient() # MethodError: no constructors have been defined for ColorGradient
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: Master
Backend  version:
Output of `versioninfo()`: 

Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)       
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\fff00\AppData\Local\atom\app-1.47.0\atom.exe"  -a
  JULIA_NUM_THREADS = 4

**Comment by babaq** [comment]
ok, it seems that the `ColorGradient` is a abstract type now, so the old `ColorGradient` in v1.0.x should be `ContinuousColorGradient` ?

**Comment by daschw** [comment]
I recommend to use `cgrad` to define colorgradients http://docs.juliaplots.org/latest/generated/colorschemes/#ColorGradient-1
