### ISSUE TITLE
[BUG] GR latex incorrect label offset

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPlots/Plots.jl#2720]
```julia
using Plots
using LaTeXStrings
plot(
    plot(rand(100),rand(100), xlab="x lab", ylab="x lab"),
    plot(rand(100),rand(100), xlab=L"x lab", ylab=L"x lab")
    )
```
![image](https://user-images.githubusercontent.com/22725744/82440832-41a38580-9a9d-11ea-80b3-a29602d7a269.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |  x   |

### Versions

Plots.jl version: `1.3.0`
Backend  version: `0.49.1`
Output of `versioninfo()`:
```julia
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\mikha\AppData\Local\atom\app-1.46.0\atom.exe"  -a
  JULIA_NUM_THREADS = 2
```

**Comment by songhanzhang** [comment]
I have the same issue. Also, the Times font looks incompatible with the tick numbers.

**Comment by t-bltg** [comment]
Cannot reproduce.

**Comment by mmikhasenko** [comment]
Confirm. Fixed meanwhile

**Comment by t-bltg** [comment]
No effort bug fixes are kindof :sunglasses: .
