### ISSUE TITLE
[FR] Relative coordinates for annotate

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPlots/Plots.jl#2728]
It would be extremely useful to have a way to specify annotation coordinates in percent.
```julia
annotate!( [ (relativex(x), relativey(y), text) ] )
```
I have several plots with different coordinates but the same additional labels added by `annotate!`,
it is quite tedious to align them manually.

Relative coordinates work nicely already for `inset=(1,bbox(x,y,wx,wy))`.
It uses `make_measure_hor/vert` [function](https://github.com/JuliaPlots/Plots.jl/blob/master/src/layouts.jl#L125)
I could not identify quickly where `w` and `h` are coming from there.

**Comment by mmikhasenko** [comment]
Is there a way to access the extrema of the x and y-axis before the backend is called?
```
 xlims = extrema(plot!()[1][1][:x])
 ylims = extrema(plot!()[1][1][:y])
``` 
works only alter the plot has been displayed

**Comment by mmikhasenko** [comment]
there is also `axis_limits`
```julia
    xlims = extrema(Plots.axis_limits(subplot, :x))
    ylims = extrema(Plots.axis_limits(subplot, :y))
```
but I do not know how to provide the `subplot`. `plot!()[1]` would not work

**Comment by BeastyBlacksmith** [comment]
there is `Plots.ylims` and `Plots.xlims`, but I also found that sometimes it is neccessary to display or save the plot before I got the correct value.

**Comment by mmikhasenko** [comment]
> there is `Plots.ylims` and `Plots.xlims`
it is not clear to which subplot it belongs to. Is there a way to return a specific subplot?

**Comment by BeastyBlacksmith** [comment]
you can just pass the subplot that you want the limits of

**Comment by mmikhasenko** [comment]
> you can just pass the subplot that you want the limits of

You mean to `axis_limits`? for sure, that is clear. What is still unclear to me is which method would return me a subplot I need. (before displaying)

**Comment by BeastyBlacksmith** [comment]
```julia
julia> plot(1:5);

julia> p = plot(1:5);

julia> Plots.xlims(p)
(0.88, 5.12)

julia> Plots.ylims(p[1]) # limits of subplot
(0.88, 5.12)
```

**Comment by mmikhasenko** [comment]
thanks
```julia
let
    p = plot(
        plot(rand(100)),
        plot(rand(200))
        )
    Plots.xlims(p[1]),  Plots.xlims(p[2])
end # ((-1.97…, 103…), (-4.97, 206…))
👍 
```

**Comment by mmikhasenko** [comment]
Perhaps, can be (should) be done more elegangly, but here is a working example
```julia
function relative(f, r; sp)
    p = plot!()
    lims = f(p[sp])
    return lims[1] + r * (lims[2]-lims[1])
end
relativex(r; sp::Int=1) = relative(Plots.xlims, r; sp=sp)
relativey(r; sp::Int=1) = relative(Plots.ylims, r; sp=sp)
#
let
    p = plot(layout = grid(1,2), frame=:box)
    plot!(sp=1, rand(100), lab="")
    plot!(sp=2, rand(200), lab="")
    Plots.xlims(p[1]),  Plots.xlims(p[2])
    annotate!(sp=1,[(relativex(0.03; sp=1), relativey(0.95; sp=1), text("Cats&Dogs", :left))])
    annotate!(sp=2,[(relativex(0.03; sp=2), relativey(0.95; sp=2), text("Cats&Dogs", :left))])
end0
```
![image](https://user-images.githubusercontent.com/22725744/82699499-140d3680-9c6d-11ea-8ab3-c080158e6846.png)

**Comment by mmikhasenko** [comment]
It would be nice to grab `sp` argument at the pipeline avoiding explicit passing.
Also, the shortening of `relative` would be handy.

**Comment by BeastyBlacksmith** [comment]
What about this?
```julia
function relative(p::Plots.Subplot, rx, ry)
               xlims = Plots.xlims(p)
               ylims = Plots.ylims(p)
               return xlims[1] + rx * (xlims[2]-xlims[1]), ylims[1] + ry * (ylims[2] - ylims[1])
end
p = plot(plot(rand(100)), plot(rand(200)), legend = false, layout = grid(1,2), frame=:box);
annotate!(sp=1, relative(p[1], 0.03, 0.95)..., text("Cats&Dogs", :left))
annotate!(sp=2, relative(p[2], 0.03, 0.95)..., text("Cats&Dogs", :left))
```

**Comment by mmikhasenko** [comment]
Even better, thanks!
Any idea on how to hide p[1], taking it from `sp=1`?

**Comment by BeastyBlacksmith** [comment]
That is not possible without modifying Plots

**Comment by mmikhasenko** [comment]
I am asking about modifying plots.
The closest thing I found in the current code is `stroke()`. It is converted to `struct` and parsed on the pipeline. Quite complicated, wondering if there are easier ways.

**Comment by BeastyBlacksmith** [comment]
That would be the way to go. Implement different coordinate system structs, give them a keyword and convert to data coordinates before passing to the backend.

**Comment by anneaux** [comment]
Hi! How can one access the x/y-lims after the subplot has been fitted into the layout? Because then obviously sometimes they change, but the Plots.Subplot.ylim values stay they same. Here's a MWE, based on @BeastyBlacksmith version:

```
function relative(p::Plots.Subplot, rx, ry)
   xlims = Plots.xlims(p)
   ylims = Plots.ylims(p)
   return xlims[1] + rx * (xlims[2]-xlims[1]), ylims[1] + ry * (ylims[2] - ylims[1])
end
p = plot(plot(rand(10) .* 15, aspect_ratio = :equal), plot(rand(10) .* 10, aspect_ratio = :equal), legend = false, layout = grid(1,2), frame=:box);
annotate!(sp=1, relative(p[1], 0.03, 0.95)..., text("Cats&Dogs", :left))
annotate!(sp=2, relative(p[2], 0.03, 0.95)..., text("Cats&Dogs", :left))
```
(Note the equal aspect ratio)
![plot](https://user-images.githubusercontent.com/50271588/124715018-c7cd9600-df02-11eb-86a8-66d5e45d3922.png)

**Comment by mmikhasenko** [comment]
What is about calling?
```
   xlims = Plots.xlims(p)
   ylims = Plots.ylims(p)
``` 
Does not it give the correct values?

**Comment by anneaux** [comment]
Not really... I changed rand(10) to rand(11) for the second subplot (to better distinguish), and I get the following values:

Plots.xlims(p) = (0.73, 10.27)
Plots.ylims(p) = (1.4338199065613908, 15.005412785910782)

Plots.xlims(p[1]) = (0.73, 10.27)
Plots.ylims(p[1]) =(1.4338199065613908, 15.005412785910782)

Plots.xlims(p[2]) = (0.7, 11.3)
Plots.ylims(p[2]) = (1.0585894577718158, 7.1805929051730875)

...so, it seems xylims(p) just give the values of the first subplot.

**Comment by mmikhasenko** [comment]
ok, I think it is intended behavior. But now you have the way to access the subplot ranges.
That solves your original question if I understood it correctly. Otherwise please explain.

Btw, you can post questions at slack helpdesk/plots.

**Comment by anneaux** [comment]
What I want is just that the annotation is placed at the position relative to the "real" (final, after the layouting happens) axis limits ;-)  
When looking at the picture I posted, you see that the yaxis for the second plot does not only go from ~1 to ~7 (as ylims(p[2]) says), but from somwhere ~-1 to ~13. I assume this is due to the layout and the equal aspect ratio. My wish would be to have the annotation for subplot 2 somewhere around (3,12), so that it matches with the annotation of subplot 1.

**Comment by mmikhasenko** [comment]
ah, sorry, now I see what you mean, but I cannot reproduce the problem (Julila 1.6, Plots v1.16.4)
```
![image](https://user-images.githubusercontent.com/22725744/124727034-9fe42f80-df0e-11eb-92ed-2caf44247a5a.png)
```

**Comment by anneaux** [comment]
hmmm.... I just updated, so I have Julia v1.6.1 and Plots v1.18.0 now, but the problem remains. I use the default GR backend and savefig.
But, if my eyes don't lie, in your plot also the annotations on subplot 1 and 2 are not perfectly at the same height?! For me it seems, on subplot 2 it's slightly lower (?)

**Comment by t-bltg** [comment]
Current workaround for #3633 :

```julia
relative(p::Plots.Subplot, rx, ry) = begin
  Plots.prepare_output(p.plt)  # account for :equal aspect_ratio
  xlims = Plots.xlims(p)
  ylims = Plots.ylims(p)
  return xlims[1] + rx * (xlims[2] - xlims[1]), ylims[1] + ry * (ylims[2] - ylims[1])
end
p = plot(plot(rand(10) .* 15, aspect_ratio=:equal), plot(rand(10) .* 10, aspect_ratio=:equal), legend=false, layout=grid(1, 2), frame=:box)
annotate!(sp=1, relative(p[1], .03, .95)..., text("Cats&Dogs", :left))
annotate!(sp=2, relative(p[2], .03, .95)..., text("Cats&Dogs", :left))
```

**Comment by t-bltg** [comment]
With https://github.com/JuliaPlots/Plots.jl/pull/3634 in master, the syntax for relative coordinates is now `NTuple{dim}`:
```julia
annotate!((rel_x, rel_y), text)
```
