### ISSUE TITLE
[BUG] spy only working for sparse matrices

### ISSUE THREAD

**Issue by jamblejoe** [JuliaPlots/Plots.jl#2730]
## Details

Is the following intendend behaviour?
```
julia> spy(sparse([1 2; 3 4]))

julia> spy([1 2; 3 4])
ERROR: MethodError: no method matching findnz(::Array{Float64,2})
Closest candidates are:
  findnz(::SparseArrays.AbstractSparseMatrixCSC{Tv,Ti}) where {Tv, Ti} at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\SparseArrays\src\sparsematrix.jl:1423
  findnz(::SparseVector{Tv,Ti}) where {Tv, Ti} at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\SparseArrays\src\sparsevector.jl:737
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |  x  |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: v1.2.2

**Comment by BeastyBlacksmith** [comment]
The fix would be to add a method to `findnz` for dense matrices (without type piracy).

**Comment by jamblejoe** [comment]
But isn't this function defined in `SparseArrays`? Should another method `findnz(::AbstractArray)` be defined in `Plots.jl`?

**Comment by BeastyBlacksmith** [comment]
Thats right, that function needs two methods:
```julia
Plots.findnz(a::SparseArray) = SparseArrays.findnz(a)
Plots.findnz(a::AbstractArray) = ...
```

**Comment by jamblejoe** [comment]
Sorry, to bother you. I quickly read the Julia style guide on type piracy. Does your code snippet already avoid type piracy? 

And how would you make `findnz` visible? By 
```
import SparseArrays.findnz
```
?

**Comment by BeastyBlacksmith** [comment]
> Sorry, to bother you. I quickly read the Julia style guide on type piracy. Does your code snippet already avoid type piracy?
> 

Type piracy would be if I added a `SparseArrays.findnz(a::AbstractArray)`.
> And how would you make `findnz` visible? By
> 
> ```
> import SparseArrays.findnz
> ```
> 
> ?
`findnz` is already exported by `SparseArrays`, no? We just need to qualify all calls inside Plots, since we now have two `findnz`s in the namespace.

**Comment by jamblejoe** [comment]
> Type piracy would be if I added a SparseArrays.findnz(a::AbstractArray).

This finally makes sense to me. Thank you!

> findnz is already exported by SparseArrays, no? 

Yes, you are right.

> We just need to qualify all calls inside Plots, since we now have two findnzs in the namespace.

Ok

**Comment by jamblejoe** [comment]
@BeastyBlacksmith Where would one put such functionality? In the corresponding section `recipes.jl`? around line 1390

**Comment by BeastyBlacksmith** [comment]
I would put it in `utils.jl`, but if its only used in that recipe, than putting it there is also fine

**Comment by jamblejoe** [comment]
@BeastyBlacksmith Sorry for bothering you with this. I defined `findnz` for an abstract array and implemented:
```
Plots.findnz(A::SparseArray) = SparseArrays.findnz(A)

# fallback function for finding non-zero elements of non-sparse matrices
function Plots.findnz(A::AbstractArray)
    keysnz = findall(!iszero, A)
    rs = [k[1] for k in keysnz]
    cs = [k[2] for k in keysnz]
    zs = A[keysnz]
    rs, cs, zs
end
```

When I use `Plots` now, it can not find `SparseArrays`. How do I fix it correctly. In `Plots.jl`, the function `findnz` is imported like this
```
import SparseArrays: findnz
```

**Comment by BeastyBlacksmith** [comment]
it cannot find `SparseArryays` or `SparseArray`? If the latter is the case qualify it, i.e. `Plots.findnz(A::SparseArrays.SparseArray) = SparseArrays.findnz(A)`

**Comment by BeastyBlacksmith** [comment]
@jamblejoe can you open a PR with what you got so far?

**Comment by jamblejoe** [comment]
@BeastyBlacksmith 
>it cannot find SparseArrays or SparseArray? 

The first is the case
