### ISSUE TITLE
A Positive "Issue"

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#2738]
I just wanted to leave a positive comment.

I've been using Plots with Plotthemes very heavily for the past 2 months. When I started, I noticed that Plots was working better than the last time I had used it some 6 months ago. That was nice.

Over the ensuing 2 months, it has gotten noticeably better yet again. My only 2 issues were fixed if not noted in release notes/commits--that's ok, I noticed. Performance of loading and startup and other package hygiene has improved.

Keep up the good work.  Stay focused on very few backends and form a partnership with the developers/maintainers of those packages.

And even though you must do "cool", make sure there is a lot for researchers and paper publishers.

**Comment by isentropic** [comment]
Perhaps you like to drop another post at https://julialang.zulipchat.com/#narrow/stream/225583-appreciation
That thread is all about appreciating Julia and its packages. Thank you again for your warm message.
