### ISSUE TITLE
'c' argument looks like a single numeric RGB or RGBA sequence

### ISSUE THREAD

**Issue by mi44164** [JuliaPlots/Plots.jl#2749]
error is below
'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.

#Visualising the training set results

**from matplotlib.colors import ListedColormap
X_set, Y_set = X_train, Y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() -1, stop = X_set[:, 1].max() +1, step = 0.01),
                     np.arange(start = X_set[:, 0].min() -1, stop = X_set[:, 1].max() +1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(Y_set)) :
    plt.scatter(X_set[Y_set == j, 0], X_set[Y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
    plt.title('Logistic Regression (Training set)')
    plt.xlabel('Age')
    plt.ylabel('Expected salary')
    plt.legend()
    plt.show()**

**Comment by timholy** [comment]
Why are you posting Python matplotlib issues to the Julia Plots repository? Julia is a different programming language from the one you're using.

**Comment by BeastyBlacksmith** [comment]
Please report your issue here: https://github.com/matplotlib/matplotlib/issues
