### ISSUE TITLE
GR very slow to plot heatmaps with unevenly spaced data

### ISSUE THREAD

**Issue by rafaqz** [JuliaPlots/Plots.jl#2759]
## Details

Heatmaps like this take ages to render, which makes GR unusable for plotting projected spatial data:

```julia
heatmap(log.(1:500), log.(1:400), rand(400, 500))
```
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |   x  |
plotly       |     |   x  |
plotlyjs     |     |  x   |
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: Plots v1.3.6
Backend  version (`]st -m`): GR v0.49.1
Output of `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 6
```

**Comment by isentropic** [comment]
To be more accurate, this is not :logscale plot, this is just unevenly spaced data in this case

**Comment by rafaqz** [comment]
Thats what I mean by non-linear axes

**Comment by BeastyBlacksmith** [comment]
what is the timing of that heatmap call compared to another backend?

**Comment by rafaqz** [comment]
Well `@time` doesn't really work for this as it's async, but with a stopwatch it's 28 seconds for `gr()`, and unmeasurablly fast with `pyplot()` and `plotly()`

**Comment by rafaqz** [comment]
Maybe 28 seconds to load  (every time) on a very good CPU should have a "bug" label.

**Comment by BeastyBlacksmith** [comment]
It is functional. It is just very slow.
