### ISSUE TITLE
[BUG] Pkg dependency?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaPlots/Plots.jl#2773]
I was wondering what the dependency on Pkg is for, so I tried removing `using Pkg` from backends.jl, and everything still seems to work. I didn't test everything of course, so I'm not sure, but is this still needed?

**Comment by BeastyBlacksmith** [comment]
Only trace of Pkg used in the past that I found is this: https://github.com/JuliaPlots/Plots.jl/pull/446

**Comment by mkborregaard** [comment]
I think this could go yes.
