### ISSUE TITLE
Plots.jl Latex issue, and not appearing if saved

### ISSUE THREAD

**Issue by joshua-benabou** [JuliaPlots/Plots.jl#2774]
Plotting in Julia has been a pain for me thus far. I do

    using Plots.jl

Initially the plotting was fine, even with latex expressions. However, something must have changed (I don't know what), and now when I wish to plot something with latex expression in the axis or title, for example:

    plot(
        p1,p2,
        layout=layout,
        link=:y,#aligns y-axis gridlines
        size = (800, 400),
        xtickfontsize=15,ytickfontsize=15, 
        xlab="s " *L" [h^{-1}Mpc]", 
        ylab=L"|x_s^2\xi_l^{bisector ,(2)}(s)/\xi_l^{pp}(s)|")

I get the error message:

    latex: major issue: So far, no MiKTeX administrator has checked for updates.
    latex: failed to create a dvi file

Furthermore, my plots are not longer being shown in Jupyter notebook (although I save them, and when I look at what was saved, the plots are there, although with messed up Latex).

Is there any easy fix for this? 

I have tried using PyPlots (and PyCall to call it from python) but seem to have an issue importing that. For now I would prefer to stick with pure Julia plotting libraries, and be able to use them with latex.

**Comment by BeastyBlacksmith** [comment]
You might try out this: https://tex.stackexchange.com/questions/530420/how-to-get-rid-of-pdflatex-major-issue-so-far-no-miktex-administrator-has-che
Also be aware that all Plots backends are wrappers around foreign language plotting packages. The only pure julia plotting package I know of is Gadfly.jl

**Comment by BeastyBlacksmith** [comment]
I'm closing this, since there is little we can do about it.
