### ISSUE TITLE
[FR] Regression in `using` time

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPlots/Plots.jl#2782]
I benchmarked Plots 1.4.0 with various versions of Julia for precompile, using (in a new session), and then producing a plot. At [some point we had lower times](https://github.com/JuliaPlots/Plots.jl/pull/2250#issuecomment-553461417).

Probably the precompile lines need a refresh - with all the new work that has been done. Maybe we should focus on 1.5.

```
              precompile  using    plot 
1.2.0            107         6       3
1.3.1            130         9       3
1.4.2            120        11       3
1.5-beta         144         8       2
1.6-master       120         7       2
```

**Comment by BeastyBlacksmith** [comment]
Would it be possible to generate the precompile files at build time, such that they don't get outdated?

**Comment by BeastyBlacksmith** [comment]
New timings in https://github.com/JuliaPlots/Plots.jl/pull/2835#issuecomment-652289782
