### ISSUE TITLE
[BUG] Fixing the extras building on 1.0.5

### ISSUE THREAD

**Issue by aminya** [JuliaPlots/Plots.jl#2789]
This can be fixed by using proper compat deps

## Details
- one of the `[extras]` is using Cairo on Windows-Julia 1.0.5, which is not recommended!
https://github.com/JuliaPlots/Plots.jl/runs/757342396

- one of the `[extras]` is using HomeBrew on MacOS-Julia 1.0.5, which again, is not recommended!
https://github.com/JuliaPlots/Plots.jl/runs/757342396

cc: @giordano You were looking into this once

**Comment by BeastyBlacksmith** [comment]
Fixed by dropping 1.0 support
