### ISSUE TITLE
[BUG] 3D subplot doesn't work for Plotly/PlotlyJS backend.

### ISSUE THREAD

**Issue by terasakisatoshi** [JuliaPlots/Plots.jl#2790]
## Details

The following code creates only 1 figure rather than getting two figures 

```julia
using Plots
plotly()

p1 = scatter3d(rand(3),rand(3),rand(3),title="p1",color=:red)
p2 = scatter3d(rand(3),rand(3),rand(3),title="p2",color=:blue)

plot(p1, p2, layout=grid(1,2))
```

![image](https://user-images.githubusercontent.com/16760547/84733132-6295c280-afd8-11ea-95a0-9e1a76537f3f.png)

On the other hand, if I adopt gr/pyplot as backend, it works that I expected

![image](https://user-images.githubusercontent.com/16760547/84733259-baccc480-afd8-11ea-9f0f-51189460943a.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pyplot       |     |   x  |
plotly       |    x |     |
plotlyjs     |  x   |     |
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version:Plots v1.3.7
Backend  version (`]st -m`):
Status `~/.julia/environments/v1.4/Project.toml`
```
  [58dd65bb] Plotly v0.3.0
  [f0f68f2c] PlotlyJS v0.13.1
```

Output of `versioninfo()`:

```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = subl
```

**Comment by terasakisatoshi** [comment]
If I call `PlotlyJS` directly, it works.

```
using PlotlyJS

t1 = scatter3d(x=rand(3),y=rand(3),z=rand(3))
t2 = scatter3d(x=rand(3),y=rand(3),z=rand(3))
p1=plot(t1)
p2=plot(t2)

p = [p1 p2]
p
```

![image](https://user-images.githubusercontent.com/16760547/84733523-6d048c00-afd9-11ea-8b94-a16767604a29.png)

**Comment by isentropic** [comment]
This is sort of limitation/drawback of plotly. There's not a lot we can do
