### ISSUE TITLE
zlabel cannot be defined in a 3D plot

### ISSUE THREAD

**Issue by songhanzhang** [JuliaPlots/Plots.jl#2812]
When I plot a 3D scatter, it works normally except from the definition of zlabel. Does anyone know how to define it? Usually we use zlabel(‘xxx’) in Matlab, but is there differences for the case in Julia? Thank you!

![image](https://user-images.githubusercontent.com/67284799/85559807-a2098200-b65c-11ea-8439-81f3afdab861.png)

![image](https://user-images.githubusercontent.com/67284799/85559841-aa61bd00-b65c-11ea-8088-d85a680366fe.png)

Win 10
Julia 1.4.1
Atom

**Comment by mkborregaard** [comment]
why don't you just specify all of those as keywords to the first plot call?

**Comment by songhanzhang** [comment]
> why don't you just specify all of those as keywords to the first plot call?

Thanks for the suggestion. I will try this later.

**Comment by songhanzhang** [comment]
> why don't you just specify all of those as keywords to the first plot call?

I have tried the suggestion you provided. The text can indeed appear at the z axis. However, the position is too much close to the axis.

![fig_test_kw3D](https://user-images.githubusercontent.com/67284799/85940513-72ee5b80-b94f-11ea-90d0-89b21c8befb4.png)

I think this might be another issue. Is it possible to manually adjust the position of the labels? Thank you!
