### ISSUE TITLE
[FR] Enable axis manipulation for matrix plots

### ISSUE THREAD

**Issue by TorkelE** [JuliaPlots/Plots.jl#2814]
I have the following matrix of colors:
```julia
using Plots
test = fill(RGB{Float64}(1,1,1),3,3);
test[1,1] = RGB{Float64}(0,0,0); test[1,2] = RGB{Float64}(0,0,0.5); test[1,3] = RGB{Float64}(0,0,1);
test[2,1] = RGB{Float64}(0.5,0,0); test[2,2] = RGB{Float64}(0.5,0,0.5); test[2,3] = RGB{Float64}(0.5,0,1);
test[3,1] = RGB{Float64}(1.0,0,0); test[3,2] = RGB{Float64}(1.0,0,0.5); test[3,3] = RGB{Float64}(1.0,0,1);
plot([1,2,3],[1,2,3],test)
```
This gives a plot like
![matrix_plot_1](https://user-images.githubusercontent.com/18099310/85718168-294f0800-b6e6-11ea-8ecd-4f2bf5626a21.png)

Now imagine if I would want to flip the y-axis, so that the element `[1,1]` is in the bottom left corner. Intuitevely one would want to do so through
```julia
plot([1,2,3],[3,2,1],test)
```
this, however, gives a weird result:
![matrix_plot_2](https://user-images.githubusercontent.com/18099310/85718569-8d71cc00-b6e6-11ea-8691-46af3b4a89d9.png)

Furthermore, say that I want a different scale of one axis, e.g.
```julia
plot([1,2,3],[0.1,0.2,0.3],test)
```
this also compresses that axis:
![matrix_plot_3](https://user-images.githubusercontent.com/18099310/85718699-ab3f3100-b6e6-11ea-9607-b0f9b583911f.png)
making the figure unreadable. It would be very useful to be able to re-scale the axis, without warping the figure itself.

All these tests are made using Plots 1.3.6.

**Comment by daschw** [comment]
The kwargs `yflip = false` for the first plot and `aspect_ratio = :none` for the last should handle this.

**Comment by TorkelE** [comment]
That worked wonders! Thanks a lot.
