### ISSUE TITLE
[FR] Is this warning really appropriate?

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#2820]
Whenever I call a plot recipe twice that uses a colorbar by default, I get this warning:

![image](https://user-images.githubusercontent.com/3345261/85921325-f164d380-b851-11ea-899f-d58a08e9e868.png)

I wonder if this is something that could be fixed? To me it seems like we should be able to plot multiple series on a scene and get the colorbar updated? Is the warning just reflecting a missing implementation?

**Comment by mkborregaard** [comment]
It's nice enough with the information, but it could be an `@info` and less defensively phrased (keeping just the first sentence)

**Comment by juliohm** [comment]
Is it something that is not amenable to fix? The way that series get plotted one after another inhibits the update of the colorbar in the current design, is that it?

**Comment by daschw** [comment]
Maybe we could check if the two series share the same color gradient and omit the warning/info in that case.

**Comment by juliohm** [comment]
That seems reasonable and very useful to have.

**Comment by juliohm** [comment]
Another warning that could go away:

![image](https://user-images.githubusercontent.com/3345261/85929199-41ab5800-b889-11ea-97f1-45bf83381b72.png)

**Comment by isentropic** [comment]
Perhaps these warnings should be handled by Plots, not backends? If we were to cross check the series range and colorbar, it can only be checked in Plots

**Comment by juliohm** [comment]
I think a quick removal of the warnings would already be an improvement. They are not helping much.

**Comment by isentropic** [comment]
We cannot just remove the warnings, if this gets unnoticed it might produce wrong plots I think. For now, it could be changed to @info but that is it

**Comment by juliohm** [comment]
These two warnings show up in this tutorial: https://www.youtube.com/watch?v=Ee8K2Dxp-2k

The second warning could be removed without problems in my opinion. People will notice the issue with polar grid labels anyways.

**Comment by yha** [comment]
> Maybe we could check if the two series share the same color gradient and omit the warning/info in that case.

The check does exist in the code, but stopped working because comparison of color gradients was broken in the transition to `ColorSchemes`. Should be fixed now on `PlotUtils` master (JuliaPlots/PlotUtils.jl#99).
I still think this should be a warning and not `@info`, because it means the colorbar is probably wrong. Once comparison of gradients works correctly, I can't think of a scenario where this warning is emitted and the plot is actually correct.

**Comment by juliohm** [comment]
Closing as no longer valid.
