### ISSUE TITLE
[BUG] both GR and PlotlyJS export "plot"; uses of it in module Main must be qualified warning

### ISSUE THREAD

**Issue by el-oso** [JuliaPlots/Plots.jl#2822]
## Details
After compiling Plots using PackageCompiler with GR and PlotlyJS backends I get the warning and error:

`create_sysimage([:WebIO, :Plots, :PlotlyJS, :GR, :DifferentialEquations], sysimage_path="sys_plots.so", precompile_execution_file="precompile_plots.jl")
`

WARNING: both GR and PlotlyJS export "plot"; uses of it in module Main must be qualified
ERROR: UndefVarError: plot not defined

For example:
```
julia> @time plot(x, sin.(x))
WARNING: both GR and PlotlyJS export "plot"; uses of it in module Main must be qualified
ERROR: UndefVarError: plot not defined
Stacktrace:
 [1] top-level scope at ./timing.jl:174 [inlined]
 [2] top-level scope at ./REPL[5]:0

```

Plots.plot() works fine

### Backends
GR and PlotlyJS

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   X  |     |
pyplot       |     |     | X
plotly       |     |     | X
plotlyjs     |   X  |     |
pgfplotsx    |     |     | X
inspectdr    |     |     | X

### Versions

Plots.jl version: v1.4.4
Backend  version (`]st -m`):
```
 [f0f68f2c] PlotlyJS v0.13.1
[28b8d3ca] GR v0.50.1

```
Output of `versioninfo()`:
```
Julia Version 1.5.0-rc1.0
Commit 24f033c951 (2020-06-26 20:13 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 1700 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_NUM_THREADS = 16
  JULIA_EDITOR = atom  -a
```

**Comment by el-oso** [comment]
`create_sysimage([:WebIO, :Plots, :DifferentialEquations], sysimage_path="sys_plots.so")`

Works fine too

**Comment by BeastyBlacksmith** [comment]
That is quite expected. You need to qualify in your `precompile_plots` file which package should get the unqualified `plot` name.
If you added `PlotlyJS` and `GR` only to have them as backend for Plots, I would suggest to use either `import GR, PlotlyJS` or `using GR: GR`, `using PlotlyJS: PlotlyJS` in your precompile file.

**Comment by el-oso** [comment]
I tried both options and neither worked for me. This is my `precompile_plots.jl` script:

```
using Plots
import GR # or  using GR: GR
import PlotlyJS # or using PlotlyJS: PlotlyJS

gr()
p = plot(rand(5), rand(5))
display(p)

plotlyjs()
p = plot(rand(5), rand(5))
display(p)
```

And this is my make file:
```

using PackageCompiler
create_sysimage([:WebIO, :Plots, :PlotlyJS, :GR], sysimage_path="sys_plots.so", precompile_execution_file="precompile_plots.jl")
```
What am I missing?

**Comment by BeastyBlacksmith** [comment]
Late answer, but
```
using Plots
import GR # or  using GR: GR
import PlotlyJS # or using PlotlyJS: PlotlyJS

gr()
p =Plots.plot(rand(5), rand(5))
display(p)

plotlyjs()
p = Plots.plot(rand(5), rand(5))
display(p)
```
should work.
