### ISSUE TITLE
[BUG] Plots in the Atom PlotPane differ from saved plots

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaPlots/Plots.jl#2824]
## Details

The `showjuno` method changes the size of the plot for displaying in the atom plot pane. This can cause differences with more complex layouts.
Is there any way to scale the output graphic instead of changing the size before producing the output graphic?
CC: @pfitzseb

**Comment by pfitzseb** [comment]
Juno's plot pane should scale down plots automatically now, so you could try to remove the code that changes the plot size here. With a bit of luck everything should still work ok.
