### ISSUE TITLE
[BUG] `label=0` produces no legend, whereas `label=1` does

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/Plots.jl#2834]
## Details
It seems that `0` is used as a sentinel value somewhere. 

`Plots.plot(rand(100); label=1)` plots a legend with label 1
`Plots.plot(rand(100); label=0`) plots no legend.
`Plots.plot(rand(100); label="0"`) plots a legend with label 0.

I think it is good style to ensure the label is a string, but I'd say this is a bug since some values are converted to strings, and others are not.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |x
plotly       |  x   |     |
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: Plots v1.5.0
Backend  version (`]st -m`): GR v0.50.1
Output of `versioninfo()`:
```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 4
  JULIA_BASE_PATH = /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/base
  JULIA_STDLIB_PATH = /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib
```

**Comment by isentropic** [comment]
I think it due to 0 being interpreted as false and 1 true. False stands for no legend. So I think this is an expected behaviour

**Comment by goretkin** [comment]
That means somewhere there's a comparison with `false` instead of using it in a boolean context:

```julia
julia> 0 == false
true

julia> 0 ? true : false
ERROR: TypeError: non-boolean (Int64) used in boolean context
Stacktrace:
 [1] top-level scope at none:0
```

So that should be fixable. e.g.

```julia
julia> isfalse(x::Bool) = !x
isfalse (generic function with 1 method)

julia> isfalse(x) = false
isfalse (generic function with 2 methods)

julia> isfalse(0)
false

julia> isfalse(false)
true
```

**Comment by isentropic** [comment]
Thanks for pointing this out, I'll see about this soon

**Comment by daschw** [comment]
To be fair though, the documentation for label says:

Attribute | Aliases | Default | Type | Description
-- | -- | -- | -- | --
label | lab, labels | `AUTO` | String type | The label for a series, which appears in a legend.  If empty, no legend entry is added.

So we support string types, not integers. Nevertheless, parsing `0` as `"0"` would be an improvement.
