### ISSUE TITLE
[BUG] Ribbons with pgfplotsx not working with layouts

### ISSUE THREAD

**Issue by jlperla** [JuliaPlots/Plots.jl#2852]
## Details
The generated documentation for ribbons with pgfplotsx *does not* generate a layout.  See http://docs.juliaplots.org/latest/generated/pgfplotsx/#pgfplotsx-ref37-1   where only has one panel

vs.  something like GR which prperly shows the 4 panels: http://docs.juliaplots.org/latest/generated/gr/#gr-ref37-1

It is easy to reproduce, but to copy the existing docs code, try
```julia
plot(plot(0:10; ribbon = (LinRange(0, 2, 11), LinRange(0, 1, 11))), plot(0:10; ribbon = 0:0.5:5), plot(0:10; ribbon = sqrt), plot(0:10; ribbon = 1))
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     X|
pyplot       |     |     |X
plotly       |     |    |X
plotlyjs     |     |    |X
pgfplotsx    |    X |     |
inspectdr    |     |     |X

### Versions
I tried on master, but issue 
Plots.jl version: Plots v1.5.3 #master (https://github.com/JuliaPlots/Plots.jl.git)
Backend  version (`]st -m`):  PGFPlotsX v1.2.8 #master (https://github.com/KristofferC/PGFPlotsX.jl.git)
Output of `versioninfo()`:
```
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = "C:\Users\jlperla\AppData\Local\Programs\Microsoft VS Code\Code.exe"
```

**Comment by BeastyBlacksmith** [comment]
That's still an open bullet in https://github.com/JuliaPlots/Plots.jl/issues/2290.

The issue is that I used the `fillbetween` library for that which uses layered plotting which breaks layouting.
The solution is to remove that code and rely on the fillrange conversion of Plots.
