### ISSUE TITLE
setting BigFloat bounds for yaxis, as yaxis = (:log10, (1e-1000,Inf)) does not work?

### ISSUE THREAD

**Issue by emca1** [JuliaPlots/Plots.jl#2856]
I need to visualize the behavior of some sequences converging to zero.
I cannot do that in current version of Plots, as  I get an error for the code

p=plot(x, px, yaxis = (:log10, (1e-1000,Inf)))

as the 'y' bounds must be representable as Float64 (min. is around 1e-300).

**Comment by BeastyBlacksmith** [comment]
Plots.jl is not a native plotting library and as such cannot support arbitrary precision.
You might have better luck with Gadfly.jl
