### ISSUE TITLE
[BUG] Weights seem to be wrapping around when plotting histogram

### ISSUE THREAD

**Issue by jenfenghsu** [JuliaPlots/Plots.jl#2860]
## Details
There seem to be a artificial tail at the right end, rising to the first weight value (10).  Does anyone has experienced this or has a way to step around?  Here are some notes/observations:

- Edges (edg) are generated by fit(Histogram, cts, closed=:left) function
- Same behavior for both simple plot and histogram
- Does change when the first value is changed

Thanks!

![image](https://user-images.githubusercontent.com/12201322/87348624-0fedee80-c523-11ea-8f79-51809562f8b2.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | X
pyplot       |  X   |     |
plotly       |     |     | X
plotlyjs     |     |     | X
pgfplotsx    |     |     | X
inspectdr    |     |     | X

### Versions

Julia => v"1.4.1"
  "Plots"            => v"1.0.14"
  "PyPlot"           => v"2.9.0"

**Comment by isentropic** [comment]
Try steppost or steppre as given in the available plotting series

**Comment by jenfenghsu** [comment]
Thanks!  Shifting between steppost and steppre gave me a better idea of how the data was taken to plot the histogram.  I ended up  putting the edges into an array, and deleting the last value to avoid the wrapping.
