### ISSUE TITLE
[BUG] Wrong image limits in PyPlot backend

### ISSUE THREAD

**Issue by Vectornaut** [JuliaPlots/Plots.jl#2864]
When I plot an image with `plot(x_mesh, y_mesh, image)`, the PyPlot backend gets the image limits wrong. This misaligns the image with anything plotted over it. I wonder if this might be a side effect of bug-fix #2226.

GR (correct limits) | PyPlot (wrong limits) |
---|---|
![gr](https://user-images.githubusercontent.com/12519587/87676326-c3035580-c778-11ea-8a3b-bdbd57623529.png) | ![pyplot](https://user-images.githubusercontent.com/12519587/87676366-d1ea0800-c778-11ea-997a-de745ad9c990.png) |
`test(gr)` | `test(pyplot)` |

These examples come from the code below.

### Example code

```
using Plots

function colorize(t)
  u = tanh(2t)
  if u < 0
    return RGB(1, 1+u/4, 1+u)
  else
    return RGB(1-u, 1-u/2, 1-u/2)
  end
end

function test(backend)
  backend()
  
  mesh = LinRange(0, 1, 100)
  image = [colorize(y - x^2) for y in mesh, x in mesh]
  image_plot = plot(mesh, mesh, image)
  
  knots = LinRange(0, 1, 10)
  scatter_plot = scatter!(image_plot, knots, knots.^2, legend = false)
  
  savefig(scatter_plot, string(backend, ".png"))
end
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x  |
pyplot       |  x  |     |
plotly       |     |     |  x
plotlyjs     |     |     |  x
pgfplotsx    |     |     |  x
inspectdr    |     |     |  x

### Versions

Plots.jl version:

* Plots v1.5.4

Backend  version (`]st -m`):

* PyPlot v2.9.0
* GR v0.50.1

Output of `versioninfo()`:
```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by BeastyBlacksmith** [comment]
You could try to get Plots v0.28.1 running to test, but its probably a bit difficult, because there were no upper bounds back then..
