### ISSUE TITLE
PGFPlotsX fails to render the LaTeX subscript `_` after assigning the plot to a variable

### ISSUE THREAD

**Issue by szcf-weiya** [JuliaPlots/Plots.jl#2875]
Work with Plots.jl v1.3.6, LaTeXStrings v1.1.0, PGFPlotsX v1.2.6 in Julia1.4.0, I found that,
```julia
using Plots
using LaTeXStrings
pgfplotsx()
plot(1:10, label = L"y_1") # the output figure is OK
# But
p = plot(1:10, label = L"y_1") # the output is also OK
# But if  I type
p # the subscript is not rendered, as shown in the following figure
# then
plot(p, p2) # would be problematic, where p2 is another plotted figure
```
![image](https://user-images.githubusercontent.com/13688320/88446142-30d70d80-ce5a-11ea-99e5-469fe713fd79.png)
Repeat the procedure for `gr()` backend, no such issue. And I also test it for the superscripts `^` in PGFPlotsX, no similar issue.

**Comment by BeastyBlacksmith** [comment]
Thats fixed on newer versions of Plots. See https://github.com/JuliaPlots/Plots.jl/issues/2780

**Comment by szcf-weiya** [comment]
Thanks!

**Comment by putianyi889** [comment]
I'm experiencing the same issue again. Subscripts don't work while superscripts work. Didn't have this problem a month ago.

**Comment by BeastyBlacksmith** [comment]
What are your versions?

**Comment by putianyi889** [comment]
Plots1.25.4
PGFPlotsX1.4.1

**Comment by BeastyBlacksmith** [comment]
I can't reproduce, what code are you running?

**Comment by putianyi889** [comment]
`plot(1:10,xlabel="\$a_a\$")`

**Comment by BeastyBlacksmith** [comment]
You need to use `LaTeXStrings` like
`plot(1:10, xlabel= L"a_a")`

**Comment by putianyi889** [comment]
alright... thanks
