### ISSUE TITLE
[BUG] Series restricted to a single marker

### ISSUE THREAD

**Issue by mzgubic** [JuliaPlots/Plots.jl#2876]
## Details

```
using Plots
xs = [1, 2, 3]
ys = [2, 3, 2.4]
markers = [:x, :hexagon, :none]
plot(xs, ys, markershape=markers)
```

Produces 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/15211548/88452427-e2783d80-ce5e-11ea-92a4-fb7055f299ac.png">
(desired) on v0.29.9

and 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/15211548/88452450-0b98ce00-ce5f-11ea-8fc0-752818beb119.png">
(buggy) on v1.5.6

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version:
1.5.6 vs 0.29.9

Backend  version (`]st -m`):
  [28b8d3ca] GR v0.48.0

Output of `versioninfo()`:
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)

**Comment by BeastyBlacksmith** [comment]
Can confirm. It worked on 1.5.1 though.

**Comment by isentropic** [comment]
Works fine in pyplot but not in GR for me

**Comment by briochemc** [comment]
FWIW, it works for me with Julia v1.6.0 and Plots v1.11.2 (backend: GR v0.57.3) on OSX
<img width="712" alt="Screen Shot 2021-04-15 at 10 22 05 pm" src="https://user-images.githubusercontent.com/4486578/114868241-0c342300-9e39-11eb-83fe-f6cb08832bcf.png">
