### ISSUE TITLE
[FR] Should legend=true be the default? 

### ISSUE THREAD

**Issue by cjwyett** [JuliaPlots/Plots.jl#2879]
Most plots have no legend. When there is a legend it is not usually labelled with the default y1, y2, ... yn. Developers mostly label legends themselves, so minimal effort is spared by keeping the legend on. 

It can get quite tiresome writing `legend = false` everywhere. Should this be the default instead?

**Comment by BeastyBlacksmith** [comment]
Changing defaults is a breaking change, so if this would change than for Plots 2.0.

**Comment by isentropic** [comment]
Just add `legend = false` entry in your (startup)[
] jl file.

**Comment by cjwyett** [comment]
Thanks for the tip @isentropic !

**Comment by isentropic** [comment]
No prob, I also suggest to select a better default palette like :seaborn_deep, or ggplots palette, if you are not a fan of the small font sizes, change them up a bit. A 10 line default formatting can give you vastly better visual experience
