### ISSUE TITLE
Dissappearing extra_kwargs upon replot using pgfplotsx [BUG]

### ISSUE THREAD

**Issue by korsbo** [JuliaPlots/Plots.jl#2884]
## Details

Re-plotting using `plot!` does not retain all elements of the plot. 

```julia
# This works fine:
plot(x->x, -1:1; add = raw"\node at (0,0.5) {\huge hi};", extra_kwargs = :subplot)

# Now the node disappears:
plot!()
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    | x    |     |
inspectdr    |     |     |

### Versions

Plots.jl version: 1.5.7
Backend  version (`]st -m`): PGFPlotsX 1.2.8
Output of `versioninfo()`:

Thanks!

**Comment by BeastyBlacksmith** [comment]
Can you check https://github.com/JuliaPlots/Plots.jl/pull/2885?
