### ISSUE TITLE
[BUG] Using pyplot backend and matplotlibrc with `text.usetex : True`, #2858 breaks tick labels

### ISSUE THREAD

**Issue by benide** [JuliaPlots/Plots.jl#2889]
## Details

My matplotlibrc contains the line `text.usetex : True`. I don't totally understand what #2858 did, but tick labels are broken for me now. Tick labels are correct when just using the PyPlot package.

The first problem is just that it's not using Computer Modern (or Latin Modern) on the ticks, which makes me think it's not even necessarily calling LaTeX. Output of `plt1 = plot(1:5, title = "Test plot 1"); png(plt1, "test1")`:
![test1](https://user-images.githubusercontent.com/19765016/89239691-e37c3e00-d5c7-11ea-99c4-bb52ae543e7d.png)

A further problem, it's just not parsing things correctly somehow as can be seen in the output of `plt2 = plot(1:5, title = "Test plot 2", xticks = ([2,4], ["two", "four"])); png(plt2, "test2")`:
![test2](https://user-images.githubusercontent.com/19765016/89239727-00187600-d5c8-11ea-9a3f-0e3ef4437f1f.png)

(my apologies to @isentropic, I wasn't around when you asked for feedback on this PR)

### Backends

PyPlot

### Versions

Plots.jl version: 1.5.6 and 1.5.7
Backend  version (`]st -m`): PyPlot v2.9.0
Output of `versioninfo()`:
```
Julia Version 1.5.0-rc1.0
Commit 24f033c951 (2020-06-26 20:13 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
```

**Comment by isentropic** [comment]
First, you should use the exported rc file under `Plots.pyrcparams` not yours.

If you want to get serif fonts, do 
```julia
plot(1:5, title = "Test plot 1")

plot(1:5, title = "Test plot 1", fontfamily="Serif")
```
and do not touch the `usetex`. This should cover most of the needs for users, instead of manually tweaking rc don't you think?

Else,
`text.usetex : True` turns on system latex which I personally do not recommend, as pyplot has its own latex renderer.

**Comment by isentropic** [comment]
Regarding the strings as ticklabels, I cannot be sure if it is the same issue

**Comment by isentropic** [comment]
If you desire serif fonts in math then,
```
Plots.pyrcparams["mathtext.fontset"]="dejavuserif"
plot(1:5, title = raw"Test plot 2 $\alpha+\beta$", xticks = ([2,4], ["two", "four"]), fontfamily="Serif")
```
Should get you covered.

**Comment by isentropic** [comment]
I'm also waiting for this https://github.com/matplotlib/matplotlib/issues/17906 to resolved, then perhaps we will get a better solution to this. As currently, it is merely a hack

**Comment by benide** [comment]
> Regarding the strings as ticklabels, I cannot be sure if it is the same issue

Ah. Well, this bug was introduced in 1.5.6, but maybe not from that PR. Might have to see what else was in that release.

As for the rest, I attempted it to no avail. I renamed my matplotlibrc to get it out of the way, used "cm" instead of "dejavuserif" as mentioned [here](https://matplotlib.org/3.3.0/tutorials/text/mathtext.html). Here's the code and output:
```julia
using Plots; pyplot()
Plots.pyrcparams["mathtext.fontset"] = "cm"
plt3 = plot(1:5, title = "Test plot 3", fontfamily = "Serif")
png(plt3, "test3")
```
![test3](https://user-images.githubusercontent.com/19765016/89250406-b25d3700-d5e2-11ea-9003-783f9a7e3056.png)

So, this doesn't actually work.

> This should cover most of the needs for users, instead of manually tweaking rc don't you think?

Well, my short dotfile was working for me, so I'm not sure I agree. I seem to recall a few years ago that other people were pleasantly surprised when it worked (though that was with PyPlot.jl, not Plots.jl). I'd expect there are still others around who use it.

For now I'll pin 1.5.5.

**Comment by isentropic** [comment]
What is wrong with the plot you produced

**Comment by isentropic** [comment]
I think I didn't understand your needs. Your feedback and workflow is much appreciated to know.

The reasoning behind this PR was to have fontfamily just work

**Comment by benide** [comment]
I'm not looking merely for serif, but for computer (or Latin) modern. I'm looking for it to mesh seamlessly into LaTeX documents. Just using `text.usetex : True` is the trivially correct way to do it in my mind (especially since a custom preamble is also easy, and you can make it match whichever journal you're writing for, and matplotlibrc can be used in a local directory per project).

I'll post an example of what it looks like with `text.usetex : True` in 1.5.5 tomorrow (when I'm back at the computer) to show you the difference.

**Comment by benide** [comment]
Using Plots.jl 1.5.5, matplotlibrc with `text.usetex : True`, and the following Julia code, I get something that can be embedded into a [LaTeX generated PDF](https://github.com/JuliaPlots/Plots.jl/files/5023025/test.pdf) very nicely.
```julia
using Plots; pyplot()
default(linewidth = 1, titlefontsize = 11, guidefontsize = 10, grid = false, framestyle = :box)
plt = plot(rand(5), title = "Title", xlabel = "axis", size = (250, 200))
Plots.pdf(plt, "test")
```

From this, hopefully you can see what I'm talking about. The font used in the text and figure are absolutely identical by necessity since they're both generated via LaTeX, and this is exactly why I use the PyPlot backend for generating figures for publication.

**Comment by Diaga** [comment]
@benide 
> A further problem, it's just not parsing things correctly somehow as can be seen in the output of plt2 = plot(1:5, title = "Test plot 2", xticks = ([2,4], ["two", "four"])); png(plt2, "test2"):


For your second problem of incorrect labels, the labels have to be enclosed with "$".
In your case:
```julia
plt2 = plot(1:5, title = "Test plot 2", xticks = ([2,4], ["\$two\$", "\$four\$"])); png(plt2, "test2")
```

For linking, why this happens:
https://github.com/JuliaPlots/Plots.jl/issues/2890

**Comment by benide** [comment]
@Diaga interesting. I checked and `xticks = ([2,4], ["two", "four"])` works as expected in Plots.jl 1.5.5 and not in 1.5.6, both *without* my matplotlibrc. What is being solved with this change in 1.5.6? It feels like a lot of breaking changes for a patch release. Of course, this one in particular has the easy solution you mentioned so while it's breaking, it wouldn't hold me back from upgrading. It's the other part that is forcing me to pin 1.5.5.

**Comment by isentropic** [comment]
The reason to enclose every single tick label with `$\mathregular{1.5}$` was to have scientific exponents look consistent with plain formatting. Standard pyplot does not do it, and I can understand why because of Locator and Formatter objects in matplotlib. PyPlot handles each case individually. 
Here in Plots, since Plots.jl calculates tick locations and tick labels, in order to achieve consistencty, I thought it would be best to enclose all tick labels with `$\mathregular{1.5}$`

Right now, if Plots decides the tick labels, it would be [enclosed](https://github.com/JuliaPlots/Plots.jl/blob/c4a64351ca4e67a97a79b640d3cd0461b3cce044/src/backends/pyplot.jl#L1132) with `$\mathregular{ ... }$. And the reason for this choice was [this](https://github.com/matplotlib/matplotlib/issues/17906).

Perhaps my mistake of the implementation was to explicitly turn off [tex]. @benide would you please fork and see what happens if [this line](https://github.com/JuliaPlots/Plots.jl/blob/c4a64351ca4e67a97a79b640d3cd0461b3cce044/src/backends/pyplot.jl#L1127) was commented out? If this solves all your issues whilst retaining the current behavior we could all be happy.

**Comment by isentropic** [comment]
Beware that using `tex` is not really a standard advised option, because internal pyplot tex renderer does the job very well without external dependencies. While I understand your needs, please understand that cutting out optional dependencies and making things work out as you'd expect them to work (e.g. setting serif font changes tick label font to serif too) should be the top priority of Plots. Perhaps @daschw has some comments on this

**Comment by benide** [comment]
> @benide would you please fork and see what happens if this line was commented out? If this solves all your issues whilst retaining the current behavior we could all be happy.

Doing this causes LaTeX errors. Using `ticks = false`, everything works. There's something about the way this handles tick labels that is not compatible with LaTeX.

> Beware that using tex is not really a standard advised option, because internal pyplot tex renderer does the job very well without external dependencies.

I'm not sure why you keep bringing this up. You've seen that in my case, using LaTeX does precisely the right thing with no fuss, and without I have no idea how to get equivalent results. Those results include not just serif as you keep mentioning, but specifically Computer Modern, *or any other font defined by a LaTeX preamble provided by a journal*. Not all journals have the same relevant packages and options in their preamble, and I like that with PyPlot I can very easily just match my matplotlibrc preamble and be done with it.

> ...cutting out optional dependencies and making things work out as you'd expect them to work (e.g. setting serif font changes tick label font to serif too) should be the top priority of Plots.

The dependency you're talking about is requiring LaTeX when the user specifies LaTeX as the renderer. I do not think this is an unreasonable dependency.

**Comment by isentropic** [comment]
@benide checkout the PR.
If it resolves your issue, would you please document your latex+pyplot workflow in the [docs](http://docs.juliaplots.org/latest/backends/#[PyPlot](https://github.com/stevengj/PyPlot.jl))? I think some users might appreciate your solution with latex fonts. I 

Perhaps add a section `latex workflow` under the pyplot [docs](http://docs.juliaplots.org/latest/backends/#[PyPlot](https://github.com/stevengj/PyPlot.jl)). Perhaps you have more to add?

**Comment by isentropic** [comment]
Additionally, I'd like to ask you to tone your requests in a more friendly and encouraging way. Blatant criticism would not get your issue resolved any faster. Most of us have a day job which is completely unrelated to Plots

**Comment by benide** [comment]
I'd be happy to document the workflow. I'll check the PR tomorrow, and hopefully get to the documentation this weekend.

I do apologise for my tone. Perhaps I should have been more clear: I don't (or, "didn't" as the case may be) need it done quickly. In fact, I was intending to offer to do it if we had gotten to a point where we agreed on what the problem actually was. I didn't see much point in trying to mess with the code if none of the devs actually even agreed that I had a valid problem. From my point of view, the first time I realized you even thought there was something that might need solving was an hour ago when you put up this new PR.

Hopefully you see where I'm coming from here, but even if you do not, my apologies.
