### ISSUE TITLE
[BUG] LaTeX tick labels break GR window

### ISSUE THREAD

**Issue by gustaphe** [JuliaPlots/Plots.jl#2895]
## Details
Running `plot([1,2],[3,4],formatter=:latex)` or even `plot([1,2],[3,4],xticks=([1.5],["\$a\$"]))` successfully formats the labels as LaTeX, but shows no plot. Afterwards, the window is somehow ruined, so consecutive calls to `plot()` also fail (often more catastrophically), needing a `closeall()` call (not just closing the windows manually) to reset to working order.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |  x   |
plotly       |     |  x   |
plotlyjs     |     |   x  |
pgfplotsx    |     |   x  |
inspectdr    |     |   x  |

### Versions

Plots.jl version: 1.5.8
Backend  version (`]st -m`): 0.51.0
Output of `versioninfo()`: 
```
Julia Version 1.5.0
Commit 96786e22cc* (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, haswell)
```

**Comment by gustaphe** [comment]
Clearer demonstration of the issue:
```julia
pl=plot(
       plot(1:2,xformatter=:plain),
       plot(1:2,xformatter=:latex),
       plot(1:2,xformatter=:plain),
       plot(1:2,xformatter=:latex),
       )
```
Gives this image:
![grbug](https://user-images.githubusercontent.com/6677110/90258444-e0dfdb00-de48-11ea-96ff-ea9739a531f1.png)

Note that everything after the call with a `:latex` axis is messed up. After this, just running
```julia
pl
```
will then show all four as empty like the two lower in the picture above.
```julia
closeall()
pl
```
once again gives the entire picture above (i.e. un-messes up the first subplot).

**Comment by gustaphe** [comment]
Oh, I saw a detail that I'd missed before: In the plot window itself (it gets cropped out during `savefig`), there is actually what looks like the two missing axes in the far top right corner:
![image](https://user-images.githubusercontent.com/6677110/90259887-0a9a0180-de4b-11ea-95b9-6e223b9e96ad.png)
Looks like something happens to the coordinate system for plotting.

**Comment by gustaphe** [comment]
I am also able to reproduce this on Windows with versioninfo
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
and Plots.jl version 1.5.9

**Comment by jgidi** [comment]
Hello!, thanks for reporting this bug. I want to add that this problem is also produced when LaTeX strings are passed as `xticks`. For example, the snippet
```julia
using Plots

plot(sin,
     xlim = (0, pi),
     xticks = ([pi/2, pi], ["pi/2", "pi"])
     )
```
works as expected, but changing the ticks as in
```julia
using Plots

plot(sin,
     xlim = (0, pi),
     xticks = ([pi/2, pi], ["\$ \\pi/2 \$", "\$ \\pi \$"])
     )
```
reproduces the same bug you described before and produces the following image:
![test](https://user-images.githubusercontent.com/12598495/90294821-5a7dc600-de55-11ea-8e4d-6c0d5cff2b92.png)

However, note that the LaTeX ticks are processed and appear correctly. I also tried using LaTeXStrings, and the result is the same.

Cheers, and thanks in advance!

### Versions
From `versioninfo()`:
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
From `]st -m`:
```
[28b8d3ca] GR v0.51.0
[91a5bcdd] Plots v1.5.8
```

**Comment by gustaphe** [comment]
Seems to have been solved. Not sure what commit to credit, but thanks!
