### ISSUE TITLE
[BUG] Heatmap axis label broken on PyPlot

### ISSUE THREAD

**Issue by daisy-iai** [JuliaPlots/Plots.jl#2896]
## Details

Plotting heatmaps with pyplot backend does not show the vertical axis label correctly. Here is a minimal example:
```
using Plots
pyplot()
varnames = string.("X", 1:10)
values = rand(10, 10)
heatmap(1:10, varnames, values)
```
![tmp](https://user-images.githubusercontent.com/64980452/89531953-058be100-d7bf-11ea-94a4-c28ce19a4f4f.png)

I have tested it directly with `PyPlot.jl` and it works.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |   x  |
pyplot       |  x   |     |
plotly       |     |   x  |
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: v1.5.8
Backend  version (`]st -m`): PyPlot v2.9.0
Output of `versioninfo()`:
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_HOME = /usr/local/bin/julia1.5
```

Also tested in Linux with both `PyPlot.pygui(false)` and `PyPlot.pygui(true)` and the issue is there as well.

**Comment by isentropic** [comment]
Can't reproduce 
![image](https://user-images.githubusercontent.com/24591123/95037199-244a1d80-0705-11eb-8aa8-51c35102ce7c.png)
