### ISSUE TITLE
[BUG] GR backend hangs when plotting in Julia v1.5

### ISSUE THREAD

**Issue by jonniedie** [JuliaPlots/Plots.jl#2907]
## Details
`plot` command hangs indefinitely with GR backend in Julia v1.5. This happens in both VSCode and the default standalone Julia REPL.
```julia
julia> using Plots

julia> plot(rand(100))
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |  x  |
plotly       |     |  x  |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version:   1.5.8
Backend  version (`]st -m`):   0.51.0
Output of `versioninfo()`:
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by BeastyBlacksmith** [comment]
Did you try rebuilding the GR library?

**Comment by jonniedie** [comment]
I ran `(@v1.5) pkg> build GR` and relaunched the REPL, but that didn't change anything.
