### ISSUE TITLE
[FR] lims with range silently ignored

### ISSUE THREAD

**Issue by ckoe-bccms** [JuliaPlots/Plots.jl#2914]
Hello everybody,

I could not find a matching existing issue, there is some overlap with the feature request in [2687.](https://github.com/JuliaPlots/Plots.jl/issues/2687)

I would like to suggest that this
```
plot(0:10, sin.(0:10), ylims=(-1:1.5))
```
should at least give a warning. At the moment ylims is silently ignored. Using a tuple of course fixes the problem. Alternatively, allowing a range would also be fine from my perspective. Perhaps this even extends to other keyword arguments which might be ignored silently ?

Coming from gnuplot muscle memory kicked in and I needed to look a the code for some time to see my mistake.

Thank you very much for considering this !

Best Regards

**Comment by Moelf** [comment]
I tried to work on this in:
https://github.com/JuliaPlots/Plots.jl/blob/b8222b46fe81d638e7dc569012db0a03e4b20bc7/src/axes.jl#L35

but realized this function actually does NOTHING? I commented out the function body and nothing is broken... somehow

**Comment by daschw** [comment]
It's only called when you use the magic `axis` attribute, like `plot(rand(10), xaxis = (:red, :flip, 1:10))`.

**Comment by Moelf** [comment]
I should at least say that:
```
julia> (-1:1.5)
-1.0:1.0:1.0
```
which means it will goes to `(-1, 1)` rather than `(-1, 1.5)`.

**Comment by daschw** [comment]
> I should at least say that:
> 
> ```
> julia> (-1:1.5)
> -1.0:1.0:1.0
> ```
> 
> which means it will goes to `(-1, 1)` rather than `(-1, 1.5)`.

Considering this potential cause of confusion, and the fact that we would have to break the current interface (http://docs.juliaplots.org/latest/attributes/#magic-arguments clearly states that a range as axis argument should be interpreted as ticks and not as lims. See also https://github.com/JuliaPlots/Plots.jl/pull/3025#issuecomment-703153097) I'm rather reluctant to introduce this change.
