### ISSUE TITLE
[FR] remove ORCA.jl bindings in favor of Kaleido support built in to PlotlyBase.jl

### ISSUE THREAD

**Issue by sglyon** [JuliaPlots/Plots.jl#2921]
Hi Team,

I recently released PlotlyBase 4.0, which adds built in support for plotly's new C++ based static image exporter called kaleido. 

This will replace the former ORCA.jl project I had worked on.

I'd love to get this integrated here, but it has been so long since I've contributed to Plots.jl I'm not sure the best way to do this.

Do we need to keep the `backends/orca.jl` code around and issue deprecation warnings?

Thanks

**Comment by daschw** [comment]
I don't think we need to keep `backends/orca.jl` around. Currently it is used to add png saving support for the plotly backend (a backend without other julia dependencies.
Currently, when `plotly()` is loaded we inform the users that they need to load ORCA for png saving in https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends.jl#L373. We could just replace this with an info saying that for png saving they should use the `plotlyjs()` backend.

In the longer term we might think of dropping the plotly code and implementing everything via the PlotlyJS/PlotlyBase API. The distinction between plotly and plotlyjs in Plots.jl is confusing anyway. It's just nice to have a second backend (default GR + zero dependency plotly) that is usable with just Plots in the Project.toml.

**Comment by sglyon** [comment]
Ok thank you for clarifying. 

Would it be beneficial for Plots.jl to either:

(1) depend on PlotlyBase.jl (very light dependencies)

or 

(2) Create a Kaleido.jl standalone package that could be a drop-in (but much more reliable) replacement for ORCA.jl?

**Comment by daschw** [comment]
I think I would rather not add a new direct dependency for a backend-specific package. I am not sure how this affects Plots package load time which is quite a critical factor these days.

I am also not sure if it is necessary to create a Kaleido.jl standalone package. For the `plotlyjs()` backend code we already have access to PlotlyBase via PlotlyJS. If we want to continue supporting png for the `plotly()` backend we can replace `backends/orca.jl` with a conditionally loaded `backends/plotlybase.jl` or `backends/kaleido.jl`. Are there any advantages of a standalone Kaleido.jl in your opinion?

**Comment by sglyon** [comment]
This makes sense. 

I think replacing backends/orca.jl with backends/plotlybase.jl is a good option.

There is chatter over in the kaleido main repo that it could be used for other "save web stuff to files" use cases beyond plotly, but that is just an idea for now. I think until this happens there isn't much value in a Kaleido.jl (and maybe not even after that)

**Comment by BoundaryValueProblems** [comment]
@daschw and @sglyon: if we really do not need to use ORCA.jl under the plotlyjs backend, then it would be good to remove the dependency in `src/backends.jl` along with removing `src/backends/orca.jl`. In `src/backends.jl`, the function `_initialize_backend(pkg::PlotlyJSBackend)` contains the following lines:
```
function _initialize_backend(pkg::PlotlyJSBackend)
    @eval Main begin
        import PlotlyJS, ORCA
        export PlotlyJS
    end
end
```
Hence, if one removes the ORCA.jl package, and try to use plolyjs backend, it generates an error saying that ORCA.jl still needs to be added.
As for the plotly backend, it also depends on ORCA.jl, but as @daschw suggested, it would be good to revise the comment before removing the ORCA dependency in `src/backends.jl`
```
function _initialize_backend(pkg::PlotlyBackend)
    try
        @eval Main begin
            import ORCA
        end
    catch
        @info "For saving to png with the Plotly backend ORCA has to be installed."
    end
end 
```
Thanks!
