### ISSUE TITLE
[BUG] Update precompiles

### ISSUE THREAD

**Issue by ma-laforge** [JuliaPlots/Plots.jl#2926]
I recently sync-d my fork with Plots.jl in order to create a PR.

Now, I keep getting: `[AUTO] Update precompile` PRs from `github-actions`.

Is there a way to disable this?? I don't see info on how to stop these PRs from reaching my fork.

**Comment by daschw** [comment]
cc: @aminya How does the recommended workflow with SnoopCompileBot look in that case?
Also we keep getting these PRs that update the apple precompile files only (e.g. #2929). I thought you already fixed this issue.

**Comment by aminya** [comment]
You can remove the following.
```yaml
on: 
 - push
```

There is no other way to shut the bot down. None of the other Julia bots do. TagBot, CompatHelper, etc all run on the forks too.

**Comment by aminya** [comment]
> Also we keep getting these PRs that update the apple precompile files only (e.g. #2929). I thought you already fixed this issue.

Could you close that PR and delete the branch, and delete the old files too just in case? I tested this many times and it works for me! 

https://github.com/aminya/Plots.jl/pull/19/files

**Comment by ma-laforge** [comment]
> @aminya You can remove the following.

Sorry @aminya. Was that comment to me? Are you suggesting I remove that statement or .yml file on my end?

That's perfectly acceptable to me, I just am not certain if that's what you are saying.

**Comment by ma-laforge** [comment]
### Alternative
If I remove the [master] branch completely, do I still get these PRs?

Because that might actually be less confusing overall.

**Comment by aminya** [comment]
> > @aminya You can remove the following.
> 
> Sorry @aminya. Was that comment to me? Are you suggesting I remove that statement or .yml file on my end?
> 
> That's perfectly acceptable to me, I just am not certain if that's what you are saying.

Yes. I should have tagged you. That statement specifies the triggers. Change it based on your needs. But remember if you change the code you will probably need to update the precompiles
