### ISSUE TITLE
Line widths in legend should mach plot for line plots [BR]

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaPlots/Plots.jl#2927]
## Details
If I do `using Plots; plot(cos,lw=6,label="cos");plot!(sinc,lw=1,label="sinc")`

The line widths used in the plot, used to distinguish the two curves (very useful for asymptotics, here at x->0), do not appear in the legend. 

<img width="580" alt="Screen Shot 2020-08-24 at 10 03 13 AM" src="https://user-images.githubusercontent.com/24194258/90989901-0f9c4500-e5f1-11ea-8ef8-6b555428560b.png">

This might not be best reported as a "bug" as it may be intentional and geared towards plots involving point data, where the line thickness doesn't do much work. Here, I am referring to strict line plots, where line thickness is a useful distinction.

I have also tested on `pgfplotsx`, and the "bug" doesn't occur, giving the desired result:

<img width="670" alt="Screen Shot 2020-08-24 at 11 19 41 AM" src="https://user-images.githubusercontent.com/24194258/90991239-bdacec80-e5fb-11ea-95f2-48b06e7a8c94.png">

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     | x
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     | x    | 
inspectdr    |     |     | x

### Versions

Plots.jl version:
(@v1.5) pkg> st Plots
Status `~/.julia/environments/v1.5/Project.toml`
Backend  version (`]st -m`):
(@v1.5) pkg> st -m GR
Status `~/.julia/environments/v1.5/Manifest.toml`
  [28b8d3ca] GR v0.51.0

  [91a5bcdd] Plots v1.6.0
Output of `versioninfo()`:
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

**Comment by BeastyBlacksmith** [comment]
Same cause as https://github.com/JuliaPlots/Plots.jl/issues/2951

**Comment by putianyi889** [comment]
pyplot() has the same problem.

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/4530.
