### ISSUE TITLE
Error about savefig

### ISSUE THREAD

**Issue by Freed-Wu** [JuliaPlots/Plots.jl#2938]
## Details

This issue is the continuance of #791 

# Reproduce Procedure

```julia
#!/usr/bin/env julia
# export GKS_ENCODING=utf-8
# julia: 1.4.0
# Plot.jl: 0.29.1
# sci-visualization/gr: 0.50.0-r1
using Plots
xlabel!("你好")
```
![Screenshot from 2020-08-28 22-44-19](https://user-images.githubusercontent.com/32936898/91625593-308edc80-e9db-11ea-8d32-cc3390c5b063.png)

This is correct. However.

```julia
savefig("a.pdf")
```
![Screenshot from 2020-08-28 22-44-31](https://user-images.githubusercontent.com/32936898/91625602-384e8100-e9db-11ea-99f2-d6b01abbcbd9.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

**Comment by krynju** [comment]
Note that it happens with some Polish letters like ś ć ą, but not with ó for example.
Also only appears for me with the .pdf format, others are fine

**Comment by Zitzeronion** [comment]
Has there been any progress on this lately?
It's a pitty would really love to have .pdf pictures for vector graphics.

**Comment by luboshanus** [comment]
I have the same issue with "-" dash as minus on yaxis when saving as 'pdf'. Using Palatino font.
<img width="503" alt="Screen Shot 2021-06-03 at 17 31 20" src="https://user-images.githubusercontent.com/2473206/120671332-92600380-c491-11eb-934e-0469e8e099c4.png">

**Comment by jerlich** [comment]
I still have this issue. My workaround was to save as SVG and then cover the SVG to PDF.

**Comment by BeastyBlacksmith** [comment]
Can you recreate the issue with GR alone?

**Comment by jerlich** [comment]
I am not sure what you mean by "with GR alone". Do you mean not using Julia ? Or not using plots.jl?

**Comment by Zitzeronion** [comment]
Probably the later one.
`using GR`
instead of
`using Plots`

**Comment by t-bltg** [comment]
Should be reported to GR.
