### ISSUE TITLE
Vspan messes up the Y-axis when using Dates on the X-axis[BUG]

### ISSUE THREAD

**Issue by IljaK91** [JuliaPlots/Plots.jl#2939]
## Details

I had the same problem as in the following post
https://discourse.julialang.org/t/vspan-vertical-scale-wrong-when-using-dates-as-x-axis/31904

MWE taken from the post

```
using Plots, Dates
gr()

y=[1.0*i*i for i in 1:10]
x=[Date(2019,11,i) for i in 1:10]

rx=[x[3],x[5]]

p = plot(x,y, label="y", title="Vspan problem with dates")
vspan!(p, rx, label="", alpha=0.2)
```
![grafik](https://user-images.githubusercontent.com/13484803/91642692-a9b71f80-ea2d-11ea-902a-f547ce3bb4dd.png)

Curiously, if you add a `vline!` afterward, it resolves the problem.

```
using Plots, Dates
gr()

y=[1.0*i*i for i in 1:10]
x=[Date(2019,11,i) for i in 1:10]

rx=[x[3],x[5]]

plot(x,y, label="y", title="Vspan problem with dates")
vspan!(rx, label="", alpha=0.2)
vline!(rx, label="", alpha=0.0)
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: 1.6.0
Backend  version (`]st -m`): GR v0.51.0
Output of `versioninfo()`: 
```
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = "C:\Users\Ilja\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS = 4
```

**Comment by BeastyBlacksmith** [comment]
Unfortunately https://github.com/JuliaPlots/Plots.jl/pull/2979 seems to have made things worse...
