### ISSUE TITLE
[BUG] incorrect marker size

### ISSUE THREAD

**Issue by LaurentPlagne** [JuliaPlots/Plots.jl#2951]
## Details
The marker size in the legend does not match the marker size in the curve (too big).

MWE:

```julia
using Plots
pyplot()

n = 100
x = 1:n
y = rand(n)
p = plot(x, y, linewidth=2, marker=:circle, markercolor="white")

savefig(p, "toto.png")`
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x    |     |
pyplot       |   x  |     |x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: 1.5.8

Output of `versioninfo()`:
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by BeastyBlacksmith** [comment]
this got intentionally changed in https://github.com/JuliaPlots/Plots.jl/pull/2643 and discussed in the references therein
