### ISSUE TITLE
[BUG] Removing minor ticks does not work

### ISSUE THREAD

**Issue by sverek** [JuliaPlots/Plots.jl#2952]
## Details
Removing minor tick marks with 
minorticks=false
does not work. Could not find any way to do it.

### Backends
This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     | x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |   x  |     |
inspectdr    |     |     |x

### Versions

Plots.jl version: v1.6.2#master
Backend  version (`]st -m`): v1.2.10
GR v0.51.0
PGFPlotsX v1.2.10
Output of `versioninfo()`:
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by daschw** [comment]
Could you provide a MWE? What does removing minor ticks mean?
```julia
plot(rand(5), minorticks = true)
plot!(minorticks = false)
```
works for me.

**Comment by sverek** [comment]
I wanted to remove all ticks (the actual small "lines", but not the "label" of the ticks)  This was my workaround in the end plot!(foreground_color_axis=:white, tick_direction=:out)

**Comment by t-bltg** [comment]
Probably fixed by https://github.com/JuliaPlots/Plots.jl/pull/4528.
