### ISSUE TITLE
[BUG] Plots.jl does not select plotly backend in empty environment

### ISSUE THREAD

**Issue by fonsp** [JuliaPlots/Plots.jl#2957]
## Details

In an empty/clean package environment, Plots.jl should select `plotly` as the default environment, right? It seems like GR is always selected as the default, but this means that Plots.jl does not work "out of the box" for new users:

```julia
] add Plots
using Plots
plot(1:3)
```
on a new linux computer will complain that GR is not installed.

Here is a more detailed REPL session describing the problem: (I have truncated/deleted output for some calls for readability)
```julia
julia> import Pkg

julia> Pkg.activate(mktempdir())
 Activating new environment at `/tmp/jl_iwUXFh/Project.toml`

julia> # We are now in a clean environment, which is close to the setup for new Julia users

julia> Pkg.add(Pkg.PackageSpec(name="Plots", rev="master"))

julia> # I used #master since this is a github issue, but the same happens with the default `Pkg.add("Plots")`

julia> Pkg.status()
Status `/tmp/jl_iwUXFh/Project.toml`
  [91a5bcdd] Plots v1.6.3 #master (https://github.com/JuliaPlots/Plots.jl.git)

julia> import Plots

julia> Plots.backend()
Plots.GRBackend()

julia> Plots.backends()
9-element Array{Symbol,1}:
 :pyplot
 :unicodeplots
 :plotly
 :plotlyjs
 :gr
 :pgfplots
 :pgfplotsx
 :inspectdr
 :hdf5

julia> ENV["PLOTS_DEFAULT_BACKEND"]
ERROR: KeyError: key "PLOTS_DEFAULT_BACKEND" not found

julia> p = Plots.plot(1:3)
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: could not load library "libGR.so"
libGR.so: cannot open shared object file: No such file or directory

julia> repr(MIME"text/html"(), p)
ERROR: could not load library "libGR.so"
libGR.so: cannot open shared object file: No such file or directory
```

I see the appeal of making GR the default, but in that case GR should come pre-installed with Plots.jl, right?

### Backends

NaN

### Versions

Plots.jl version: `master`
Backend  version (`]st -m`): NaN
Output of `versioninfo()`:
```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by mkborregaard** [comment]
Plots did change to having GR as the default, and it is a direct dependency, so it should be installed with Plots. I think sometimes on Linux there are some installation issues with the dependencies of GR https://gr-framework.org/julia.html#installation
@jheinen can you comment?

**Comment by jheinen** [comment]
In principal the installation issues for GR should be solved. There are, however, Linux flavours that are not supported. I think, we will never be able to support all of them, if you look at [this](https://en.wikipedia.org/wiki/List_of_Linux_distributions) list.

**Comment by mkborregaard** [comment]
So this sounds like a `wontfix`? Or could GR give an install message warning about this?
@fonsp are you using some arcane distro? I guess supporting debian/ubuntu and arch/manjaro would already go very far?

**Comment by fonsp** [comment]
Ah I completely misinterpreted the error message, thanks for including these changes already!

I'm using WSL2 (Ubuntu 20) on Windows 10.

The strange thing is that it works if I run Plots in my global environment, but it does not work in a new environment with only Plots installed. I will compare environments myself and get back to you!
