### ISSUE TITLE
Detailed control of looks

### ISSUE THREAD

**Issue by pkofod** [JuliaPlots/Plots.jl#296]
To make themes look exactly like their targets (ggplot2 for example) more detailed control of the looks of plots is needed. For example, I need to change the line width and style of the grid lines. What is the plans regarding such detailed control of the appearance of plots in Plots?

**Comment by tbreloff** [comment]
Similar to how foreground colors have cascading defaults set to 'match', I
think I'll probably change border, grid, tick lines, etc to be a
Plots.Stroke, which defaults to match. So 'grid_stroke_vertical' would
match 'grid_stroke' by default, which would match 'foreground_stroke'. The
associated color args would become aliases to the appropriate stroke arg.
You would be able to pass any valid inputs to the 'stroke' method, and the
remainder would get defaults.

Then we just need to support everything in the backends...

**Comment by pkofod** [comment]
Originally I was weary of even asking because of the whole 5 backend do it in 7 different ways ;)

**Comment by daschw** [comment]
closing via #1006
