### ISSUE TITLE
Example for trigonometric functions for PGFPlotsX uses unicode in labels which doesn't seem to work

### ISSUE THREAD

**Issue by KristofferC** [JuliaPlots/Plots.jl#3005]
http://docs.juliaplots.org/latest/generated/pgfplotsx/#pgfplotsx-ref42

<img width="661" alt="Screenshot 2020-09-25 at 08 24 28" src="https://user-images.githubusercontent.com/1282691/94233765-b897d180-ff08-11ea-9172-5553cc2d36e6.png">

maybe the label should be changed to `raw"$\sin(\theta)$"`?

**Comment by BeastyBlacksmith** [comment]
The examples are built from `examples.jl` for every backend and I'm not sure that passing raw latex strings as labels and legend entries is supported by the other backends.

The philosophy is, that users should pass `LaTeXStrings` if they want latexstrings. In this case there are two options from my point of view:
- when sanitizing the strings also replace unicode characters with their latex equivalent ( I vaguely remember there was a function for that in some package which I can't find right now )
- change the preamble to get the fontencoding correctly

In addition to this the titlefont does not get picked up. I haven't been working with different fonts in the same latex document yet.

**Comment by KristofferC** [comment]
> The examples are built from examples.jl for every backend and I'm not sure that passing raw latex strings as labels and legend entries is supported by the other backends.

Yeah, I guess it's hard when different backends support different functionalities but there is still a desire to have common examples. I thought `lualatex` should support Unicode but like you say maybe one needs to set some encoding.

**Comment by gustaphe** [comment]
> ( I vaguely remember there was a function for that in some package which I can't find right now )

[Latexify.jl](https://github.com/korsbo/Latexify.jl) does this,
```julia
julia> latexify("sin(θ)")
L"$\sin\left( \theta \right)$"
```
