### ISSUE TITLE
Feature Request: Guides for Layouts 

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#301]
It would be nice to set axis labels / guides on subplots. An example use case would be when multiple graphs have the same axis'. Currently, adding `xguide` or `yguide` kwargs to a `plot(plot1,plot2,...)` does nothing. The way to have a single label in those situations is to add the label to the middle one, which can look kind of funky as shown in the example.

![guidetest](https://cloud.githubusercontent.com/assets/1814174/15807622/a6b7f23e-2b17-11e6-8fec-473a073f68c9.png)

**Comment by tbreloff** [comment]
This sort of stuff isn't well supported by most backends, but I do think
it's possible now that I have more control over positioning. The misaligned
axes are a bug... I think there's an open issue for that.

**Comment by tbreloff** [comment]
> which can look kind of funky as shown in the example

FYI this should be fixed now:

![tmp](https://cloud.githubusercontent.com/assets/933338/15954180/f779c6d8-2ea1-11e6-9c4a-2d46f7fa7fc6.png)

See also #285

**Comment by tbreloff** [comment]
I renamed this, because what would really be nice is to add nicely centered guides to any part of the layout tree, so that if you had a grid of facets next to a big single graph, you could still have guides that apply to the facet grid.  Thinking something like this (but generic):

![tmp](https://cloud.githubusercontent.com/assets/933338/15954294/3bd64ff8-2ea3-11e6-91be-75f341e2ef9f.png)

**Comment by ChrisRackauckas** [comment]
That looks great. That type of axis titling is really hard to do with other plotting packages, and so I think this feature is really starting to put Plots.jl at the lead. 

I think a more intuitive or easier way to invoke this would be if you could directly add an axis label to a plot of plots. So in your example if I could make plots `p1`, `p2`, and `p3`, be the `a`, the grid, and the `b` plots, then I would find calling

```
plot(p1,p2,p3,layout=@layout[a b; c], yguide=["","FACET GUIDE",""])
```

really intuitive (if it also had xguide and title, and a way to add a "super title").

**Comment by ChrisRackauckas** [comment]
I think the last thing that is necessary for scientific publication for these complicated layouts (though not entirely related to guides) is if there was a way to add "specifier" annotations to subplots. That's not the right word, but I mean a quick way of adding "(A)", "(B)", "(C)" to that plot you made, so that way they are easily referenced in the caption. Unless I am mistaken, right now you can do this by adding annotations and manually placing them (and re-adjusting margins), but this is common enough that some plotting package should really bake it into the subplotting routines.

Most people I know actually do these two additions in Illustrator after plotting because it can be difficult to do with other plotting packages (or they have to [modify/mangle some solution from StackExchange](http://stackoverflow.com/questions/22508590/enumerate-plots-in-matplotlib-figure)).

**Comment by tbreloff** [comment]
Note that you can already get pretty close to this (at least in pyplot):

![tmp](https://cloud.githubusercontent.com/assets/933338/15954676/ee8a86d8-2ea7-11e6-931a-a07b37a1f6f9.png)

**Comment by ChrisRackauckas** [comment]
Adding the annotations via titles looks great, but I'd like to see that done at a higher level as well, like 

```
plot(p1,p2,p3,layout=@layout[a b; c], yguide=["","FACET GUIDE",""],title=["(A),"(B)","(C)"],titleloc=:right,supertitle="A Few Random Plots")
```

**Comment by tbreloff** [comment]
Yeah I agree... certainly doable, but might require a bit of effort.  It's on the list.

**Comment by mauro3** [comment]
It would also be good to be able to add a title to a composite plot, and only one: `plot(plot(1:3), plot(1:3), title="asd")` should just add one title at top-middle.

(Then do the annotations differently with a specific command.)

**Comment by anriseth** [comment]
Has something along the lines of supertitle been added for any of the backends?

**Comment by juliohm** [comment]
I have the same question as @anriseth, supertitle is missing.

**Comment by mkborregaard** [comment]
This'd be really nice to have - it would also be the first step to implement something like facets, i.e. subplots where axes are linked by definition and the colorscale is the same (using only one colorbar)

**Comment by t-bltg** [comment]
Implemented:

```julia
julia> using Plots
julia> plotattr("plot_title")
Whole plot title (not to be confused with the title for individual subplots).

Aliases: (:plot_titles, :plottitles).

Type: AbstractString.

`Plot` attribute
```
