### ISSUE TITLE
[BUG] axis=false on GR does not turn off tick labels

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#3019]
## Details
e.g., `plot(rand(4),yaxis=false)` shows tick labels for the y axis.
Observed on 1.6.7 and 1.6.8. I'm pretty sure it's a new regression.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |  x   |
plotly       |     |     | x
plotlyjs     |     |  x   |
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.6.7 1.6.8
Backend  version (`]st -m`): 0.52.0
Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```

**Comment by BeastyBlacksmith** [comment]
Would be good to know on what version it was different

**Comment by jjstickel** [comment]
I also came across this today. Adding `yticks=false` is a workaround.
