### ISSUE TITLE
[BUG] Heatmap edges not working

### ISSUE THREAD

**Issue by myrddin89** [JuliaPlots/Plots.jl#3028]
## Details

The following snippet results in an error when using Plots with GR. This used to work in Plots 1.6.5 but fails from 1.6.6. 
This is relevant when the axes should be at the center of the image.

```julia
using Plots; gr()

img = rand(6,8)

rows, cols = size(img)

xs = (0:cols) .- cols / 2 
ys = (0:rows) .- rows / 2

plot(xs, ys, img; st = :heatmap, color = :grays, ratio = 1)
```

This fails with:

```
ERROR: LoadError: Length of x & y does not match the size of z.
Must be either `size(z) == (length(y), length(x))` (x & y define midpoints)
or `size(z) == (length(y)+1, length(x)+1))` (x & y define edges).
```

PlotlyJS, instead, seems to deal only with midpoints. The code above places the axis center in the “wrong” place with `plotlyjs()`, which corresponds to interpreting `xs` and `ys` as midpoints.

Thanks for any help!

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     |x
plotly       |     |     |x
plotlyjs     |     |  x   |
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: 1.6.6 - 1.6.8
Backend  version (`]st -m`): GR v0.52.0
Output of `versioninfo()`:

```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_NUM_THREADS = 16
```

**Comment by daschw** [comment]
I think you are confusing x and y input. `plot(ys, xs, img; st = :heatmap, color = :grays, ratio = 1)` works.

**Comment by myrddin89** [comment]
Well, now I am confused!

Please, refer to the docs and the example for [heatmaps](http://docs.juliaplots.org/latest/generated/gr/#gr-ref28) in GR. Also, it seems that the default for `plot` when no axis ranges are provided (that is `plot(img; st=:heatmap, color=:greys, ratio=1)` in the example above), is to interpret columns of the matrix as the x-axis and rows as the y-axis, with `img[1,1]` representing the bottom-left corner.

Yes, swapping `xs` with `ys` it appears to work, but then the error message is confusing.
This behaviour is also inconsistent among backends: I tried that with PlotlyJS and the image is just stretched, so maybe this is just conveniently supported by GR (and should be mentioned in the docs)?

In any case, `plot(xs, ys, img; st = :heatmap, color = :grays, ratio = 1)` used to work correctly prior to 1.6.6 and now it works only when midpoints are given. I do not know if this is actually a problem in GR itself, though.

**Comment by daschw** [comment]
> Please, refer to the docs and the example for heatmaps in GR. Also, it seems that the default for plot when no axis ranges are provided (that is plot(img; st=:heatmap, color=:greys, ratio=1) in the example above), is to interpret columns of the matrix as the x-axis and rows as the y-axis, with img[1,1] representing the bottom-left corner.

You are right, sorry, I was confusing positional input. I will try to find when this regression was introduced.
