### ISSUE TITLE
[FR] savefig to stdout

### ISSUE THREAD

**Issue by myrddin89** [JuliaPlots/Plots.jl#3029]
Currently `savefig` only accepts a filename, maybe it can be useful in some situation to have `savefig` accept also an `IO` object so that it would be possible to send the output to stdout. This would match also the behaviour of `savefig` in `matplotlib`.

**Comment by t-bltg** [comment]
Use `show(io, plt)` instead.

**Comment by myrddin89** [comment]
Thanks, that should do it!
