### ISSUE TITLE
[BUG] wrong z-coordinate in scatter3d and plot3d with pyplot backend

### ISSUE THREAD

**Issue by siddino** [JuliaPlots/Plots.jl#3036]
## Details
using Plots

-> wrong z-coordinate
pyplot() 
pls=plot3d([0,1,2,3],[0,1,4,9],[0,1,4,9], markershape=:auto,markersize=5)
display(pls)
 <img width="486" alt="plot3d" src="https://user-images.githubusercontent.com/45201906/95102672-f4fed500-0733-11eb-85de-562efdb6d2c6.png">

pls2=scatter3d([0,1,2,3],[0,1,4,9],[0,1,4,9])
display(pls2)
<img width="483" alt="scatter3d" src="https://user-images.githubusercontent.com/45201906/95102667-f3351180-0733-11eb-978b-a23a1914a12d.png">

-> correct z-coordinate
gr()
pls3=scatter3d([0,1,2,3],[0,1,4,9],[0,1,4,9])
display(pls3)

<img width="528" alt="scatter3d gr backend" src="https://user-images.githubusercontent.com/45201906/95102660-f03a2100-0733-11eb-846f-02e4f2997f24.png">

  "Juno"             => v"0.8.4"
  "Plots"            => v"1.6.8"
  "PyPlot"           => v"2.9.0"
  "Atom"             => v"0.12.23"

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   | x |
pyplot       |  x |     |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version:
Backend  version (`]st -m`):
Output of `versioninfo()`:
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

**Comment by fhagemann** [comment]
I have experienced the same issue. It seems to have been introduced with Plots version v1.6.1.

```julia 
using Plots; pyplot()
plot([1,2,3],[1,3,2],[2,3,1], label = "Line")
scatter!([1,2,3],[1,3,2],[2,3,1], label = "Scatter")
```

Output with Plots v1.6.0
![Plots_1 6 0](https://user-images.githubusercontent.com/30291312/96923518-b0a06280-14b1-11eb-844d-ecdaf837574c.png)

Output with Plots v1.6.1
![Plots_1 6 1](https://user-images.githubusercontent.com/30291312/96923534-b72eda00-14b1-11eb-8bdb-f220208ebbc3.png)

PyPlot version is v2.9.0
