### ISSUE TITLE
[BUG] Plotly backend with marker not picking up color of line (and not showing second data point marker)

### ISSUE THREAD

**Issue by ElectronicTeaCup** [JuliaPlots/Plots.jl#3042]
## Details
Using the plotly backend when I make a simple line and add markers, the first marker is colored, the second is missing and the rest are black:

`plot(rand(10), marker=5, widen=true)`

![image](https://user-images.githubusercontent.com/31346583/95209331-892b7380-07ea-11eb-973c-3c812ed35874.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     | x    |
pyplot       |     |  x   |
plotly       |  x   |     |
plotlyjs     |     |     |x
pgfplotsx    |     | x    |
inspectdr    |     | x    |

### Versions

Plots.jl version: 
v1.6.7
Backend  version (`]st -m`): 
PlotlyBase v0.4.1
Output of `versioninfo()`:
```
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\asimd\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS =
```

**Comment by daschw** [comment]
That's already fixed in Plots 1.6.9 (https://github.com/JuliaPlots/Plots.jl/pull/3039).
