### ISSUE TITLE
[BUG] `legendtitle` is unused by plotly backend

### ISSUE THREAD

**Issue by joshday** [JuliaPlots/Plots.jl#3045]
## Details

See the Plots docs at http://docs.juliaplots.org/latest/generated/plotly/#plotly-ref12.

I would have made a PR but the legend code for plotly looks nontrivial.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |x
pyplot       |     |     |x
plotly       |  x   |     |
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: latest

**Comment by daschw** [comment]
I tried to fix this in #3046, but no luck so far...

**Comment by isentropic** [comment]
`legendtitle` is not in the supported arguments [table](http://docs.juliaplots.org/latest/generated/supported/) anyways, so this should be closed. We can't introduce issues for each unsupported arg for each backend.

**Comment by BeastyBlacksmith** [comment]
AFAICT this is fixed
