### ISSUE TITLE
[BUG] PLOTS_DEFAULTS not setting theme

### ISSUE THREAD

**Issue by jonniedie** [JuliaPlots/Plots.jl#3053]
## Details
Setting `const PLOTS_DEFAULTS = Dict(:theme => :juno)` in my `startup.jl` file before bringing in Plots doesn't set the theme like it should. Same thing with setting that value manually (i.e. not in the startup file) before importing Plots. Should this be an `ENV` thing instead of a `const` variable?

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |  x   |     |
plotly       |  x   |     |
plotlyjs     |  x   |     |
pgfplotsx    |     |     | x
inspectdr    |  x   |     |

### Versions

Plots.jl version: `v1.6.8`
Backend  version: N/A
Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by BeastyBlacksmith** [comment]
`:theme` is just not a plot attribute, you could call `theme(:juno)` in your startup file, but you 'd have to load Plots for that.

**Comment by jonniedie** [comment]
It [looks like](https://github.com/JuliaPlots/Plots.jl/blob/2ef13c19ea5f407fe686c4eaa7cfd784fde52d6c/src/init.jl#L17) it should be. And apparently it [used to be work](https://discourse.julialang.org/t/how-to-set-juno-as-the-default-plots-theme-during-startup/14971/2?u=jonniedie) too.

**Comment by jonniedie** [comment]
For right now, I have a Requires.jl statement in my startup file to achieve it, but that isn’t ideal.

**Comment by BeastyBlacksmith** [comment]
You are right, would be good to know what the last version was where it worked

**Comment by BeastyBlacksmith** [comment]
I think it is related to https://github.com/JuliaPlots/Plots.jl/commit/bbdf1dcc0e8d3ac9d0cd7b181a11ed56e09ee049 in that the call to `default` overrides the `theme` call, would be good to have a unit test for this. CC: @daschw
