### ISSUE TITLE
lens! of contour plots always have a colorbar

### ISSUE THREAD

**Issue by michakraus** [JuliaPlots/Plots.jl#3072]
## Details

I am trying to create an inset plot next to the parent plot. When the parent plot contains a contour plot, the inset plot always has a colorbar, which cannot be switched off by setting `colorbar=false` to either the inset or the parent plot. With Plotly(JS), the inset plot also has a legend which does not disappear when setting `legend=:none`.

```julia
using Plots
x = LinRange(-1, +1, 100)
y = LinRange(-2, +2, 120)
p = [x[i]^2 + y[j]^2 for i in eachindex(x), j in eachindex(y)]
plot(legend=:none, layout=(1,2))
plot!(subplot=2, legend=false, grid=false, foreground_color_subplot=:white)
contour!(x, y, p')
scatter!([0.5], [0.0])
lens!([0.4,0.6], [-0.1,+0.1], inset=(1, bbox(1.2, 0, 1, 0.5)))
```

![inset_plot](https://user-images.githubusercontent.com/21168502/96254841-3e61e680-0fb6-11eb-9868-db2b5990775a.png)

I am not sure if the way I am doing this is appropriate, but the observed behaviour is independent of the placement of the inset plot. 

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotly       |  x   |     |
plotlyjs     |  x   |     |
pgfplotsx    |  x   |     |
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.6.12
Backend  version (`]st -m`): GR v0.52.0, Plotly v0.3.0, PlotlyJS v0.14.0, PGFPlotsX v1.2.10
Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

**Comment by BeastyBlacksmith** [comment]
Thanks for reporting. `lens!` is fairly new and not very battle tested.
You don't get the colorbar with a normal inset plot.
