### ISSUE TITLE
[BUG] Some histograms have no fill

### ISSUE THREAD

**Issue by biona001** [JuliaPlots/Plots.jl#3078]
On one specific data (1.8 million float64s), my histogram is created without fill:
```julia
using Plots, DelimitedFiles
snpscores = readdlm("snpscores.txt");
histogram(snpscores, bins=10)
```
<img width="922" alt="Screen Shot 2020-10-17 at 6 53 18 PM" src="https://user-images.githubusercontent.com/16760873/96356956-2bc8d980-10aa-11eb-8bd9-26684cd72e99.png">

Usually my histograms are all filled, but it's not in this case and I can't figure out how to fill it. 

[snpscores.txt](https://github.com/JuliaPlots/Plots.jl/files/5396967/snpscores.txt) (8.4 MB)

Plots.jl version:
```julia
(@v1.5) pkg> status Plots
Status `~/.julia/environments/v1.5/Project.toml`
  [91a5bcdd] Plots v1.6.8
```

**Comment by isentropic** [comment]
Please provide the backends where the big occurs

**Comment by mkborregaard** [comment]
This is not a bug, it's intended behavior: https://github.com/JuliaPlots/Plots.jl/blob/master/src/recipes.jl#L775

See discussion here https://github.com/JuliaPlots/Plots.jl/pull/787#issuecomment-299807886 and below
The solution is to use `barhist` rather than `histogram` if you always want fill.

**Comment by biona001** [comment]
I see. Sorry for the confusion.
