### ISSUE TITLE
heatmap for unicodeplots backend [FR]

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaPlots/Plots.jl#3099]
In `UnicodePlots.jl`, there is a `heatmap()` command that seems to work well, but is absent from `Plots.jl`:

```julia
julia> heatmap([x^2+y^2 for x in LinRange(-10,10,100), y in LinRange(-10,10,100)])
ERROR: The backend must not support the series type Val{:heatmap}, and there isn't a series recipe defined.
```

Is it possible to add it?

**Comment by BeastyBlacksmith** [comment]
Most likely, the unicode backend haven't been touched for quite a while
