### ISSUE TITLE
[BUG] Rendering of scatterplot with a vector of colors is really slow after some update

### ISSUE THREAD

**Issue by VPetukhov** [JuliaPlots/Plots.jl#3117]
After some of the updates, rendering `scatter` with individual color per point got really slow. When I run normal scatter for 20000 points it takes less than a second. But when I add vector with colors it takes 25 seconds.

## Details

The code to reproduce:

```julia
import Plots
n_cols = 20000;
Plots.scatter(1:n_cols, rand(n_cols), format=:png)
```

and 

```julia
Plots.scatter(1:n_cols, rand(n_cols), color=["red" for  i in 1:n_cols], format=:png)
```

It already was on v1.6.10, then I updated to v1.7.3, and it's still there. I don't remember what version I had before (most probably something above 1.3), but there I was able to plot hundreds of thousands of points.

I didn't test it previously on PyPlot backend, but now there is still huge drop in performance after adding `color`. It works almost immediately on 5k points without colors and around 20 seconds with colors.

**UPDATE:** just checked that v1.6.0 works fine on both GR and PyPlot, while 1.6.1 is broken.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |  x  |     |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.6.10 or v1.7.3
Backend  version (`]st -m`): GR v0.52.0, PyPlot v2.9.0
Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by fedario** [comment]
Can confirm, same for me.

Can I do something to help to resolve this?

**Comment by mkborregaard** [comment]
Does the same happen if you wrap the color vector in `cgrad`?

**Comment by fedario** [comment]
> Does the same happen if you wrap the color vector in `cgrad`?

If I understand cgrad correctly, it's for color gradients, while I required "categorical colors", which is why I used the `distinguishable_colors` function and created an array containing the colors for each of my categorical observations like this:

```Julia
palette = distinguishable_colors(11)[2:end]
colors = map(i -> getindex(palette, i + 1), cpu(train_y));
```

This took a while, but was only necessary once, maybe this is related to this issue?
I have since switched to Makie.jl, which suited my use case (creating a 10k+ frame animation, each containing 60k colored points) much better.

**Comment by mkborregaard** [comment]
Nice. The ideomatic way of doing that in Plots is to supply a grouping variable to `group` and then specifying a color for each series:
```julia
palette = distinguishable_colors(11)[2:end]
plot(x, y, group = cpu(train_y), palette = palette)
```

**Comment by VPetukhov** [comment]
@mkborregaard , thanks for the suggestion! However, in my case, each point has an individual color, estimated by a complex algorithm. So it's important to have a full vector of colors, instead of a palette. And if I use 
```julia
Plots.scatter(p_df.x, p_df.y, color=Plots.cgrad(p_df.color, categorical=true), format=:png)
```
it colors all points with the first color from the whole `p_df.color` vector. While if I create a palette each point belonging to its own category, the code shows a warning and works even slower than with the original solution:
```julia
Plots.scatter(p_df.x, p_df.y, groups=1:size(p_df, 1), palette=p_df.color, format=:png)
```

**Comment by VPetukhov** [comment]
For others facing this issue, switching to [Makie.jl](https://github.com/JuliaPlots/Makie.jl) might be a good idea. [VegaLite](https://github.com/queryverse/VegaLite.jl) and [Winston](https://github.com/JuliaGraphics/Winston.jl/) also have this functionality and work much faster than Plots.jl, but they have their own problems.

**Comment by yha** [comment]
I believe this can be closed, since the overhead of a color vector is much smaller now (after #3320):
```
using Plots
using BenchmarkTools

n_cols = 20000;
plt1 = scatter(1:n_cols, rand(n_cols), format=:png)
plt2 = scatter(1:n_cols, rand(n_cols), color=["red" for  i in 1:n_cols], format=:png)

@benchmark display(plt1)
```
```
BenchmarkTools.Trial: 
  memory estimate:  29.48 MiB
  allocs estimate:  481191
  --------------
  minimum time:     313.642 ms (0.00% GC)
  median time:      331.131 ms (0.00% GC)
  mean time:        330.324 ms (0.65% GC)
  maximum time:     361.019 ms (2.39% GC)
  --------------
  samples:          16
  evals/sample:     1
```
```
@benchmark display(plt2)
```
```
BenchmarkTools.Trial: 
  memory estimate:  50.42 MiB
  allocs estimate:  1253529
  --------------
  minimum time:     404.532 ms (0.00% GC)
  median time:      479.271 ms (0.00% GC)
  mean time:        475.915 ms (0.32% GC)
  maximum time:     523.968 ms (3.19% GC)
  --------------
  samples:          11
  evals/sample:     1
```
