### ISSUE TITLE
[BUG] Quiver not working

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#3119]
## Details

The quiver plot doesn't seem to be working. I searched several posts online, and issues on GitHub, and couldn't figure out why. Perhaps it is time to add a simple example to the docs?

Here is my attempt to plot two arrows at (0,0) and (1,1) pointing to each other:

```julia
using Plots

x = [0,1]
y = [0,1]
u = 0.2*[1,-1]
v = 0.2*[1,-1]

plot(x, y, quiver=(u,v))
```
![image](https://user-images.githubusercontent.com/3345261/98171404-73cf6500-1ece-11eb-8c2d-d2a0d6d5374d.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: v1.7.3
Backend  version (`]st -m`): GR v0.52.0
Output of `versioninfo()`:

**Comment by daschw** [comment]
```julia
plot(x, y, quiver=(u,v), st=:quiver)
```
or
```julia
quiver(x, y, quiver=(u,v))
```

**Comment by juliohm** [comment]
Thank you! And how we can define a @series recipe to be a quiver?

```julia
@series begin
  seriestype --> :quiver
  # how to specify x, y, u, v?
end
```

**Comment by daschw** [comment]
```julia
@series begin
    seriestype := :quiver
    quiver := (u, v)
    x, y
end
```
