### ISSUE TITLE
[BUG] ylims option in GR makes the plot disappear

### ISSUE THREAD

**Issue by Dictino** [JuliaPlots/Plots.jl#3120]
```julia
using Plots
gr()
plot([1,2,3,10^18],ylims=(0,10))
```

Shows **noting**.  

![image](https://user-images.githubusercontent.com/2601677/98224084-54c6e680-1f53-11eb-93a2-3f5e250f2fbb.png)

It works fine with other backends like plotly or pyplot(). It also works if ylims is not present or if 10^18 is replaced by a smaller number like  10^17. 

### This bug occurs on:
 
Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |    |  x   |
plotly       |    |  x   |
plotlyjs     |    |  x  | 
pgfplotsx    |     |     | x
inspectdr    |     |     | x 

### Versions

Plots v1.7.3
GR v0.52.0

Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)

More details and  discussion here https://discourse.julialang.org/t/problem-with-ylims-in-plots/49542

**Comment by Dictino** [comment]
It works fine in a Linux VM so it could be an issue of GR on Windows 10 only...

```julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

**Comment by t-bltg** [comment]
Cannot reproduce.

**Comment by Dictino** [comment]
This bug has disappeared in new versions.
