### ISSUE TITLE
[BUG] Strange behavior when plotting the same subplot multiple times in one layout

### ISSUE THREAD

**Issue by fredcallaway** [JuliaPlots/Plots.jl#3123]
## Details
MWE:
```
f1 = plot([1,2])
f2 = plot([1,3])
plot(f1, f2, f1)
```
This specific case produce f1 and f2 just once each, on the diagonal. In more complex cases, we see highly irregular behavior. I think the simplest fix is to add a check for this case and throw an error, to save future users from the long and painful journey that brought me here.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |  x   |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, goldmont)

**Comment by DanielReedOcean** [comment]
Presumably, [this StackOverflow question](https://stackoverflow.com/q/65556392/1552004) is another example of the same issue.

**Comment by BeastyBlacksmith** [comment]
I can't reproduce this on Plots v1.27.4
