### ISSUE TITLE
[BUG] mp4/mov animations can't be opened with QuickTime or Safari

### ISSUE THREAD

**Issue by navidcy** [JuliaPlots/Plots.jl#3135]
## Details
When I make mp4/mov animations they don't play neither with Quicktime nor with Safari browser.

```
julia> anim = @animate for j in 1:10; heatmap(rand(20, 20)); end
Animation("/var/folders/1z/s8gw4q055514jw75ztnclx4h0000gn/T/jl_rqCc1c", ["000001.png", "000002.png", "000003.png", "000004.png", "000005.png", "000006.png", "000007.png", "000008.png", "000009.png", "000010.png"])

julia> mp4(anim, "test.mp4")
┌ Info: Saved animation to
└   fn = "/Users/navid/Research/FourierFlows/GeophysicalFlows.jl/test.mp4"
Plots.AnimatedGif("/Users/navid/Research/FourierFlows/GeophysicalFlows.jl/test.mp4")
```

<img width="843" alt="Screen Shot 2020-11-11 at 4 09 22 pm" src="https://user-images.githubusercontent.com/7112768/98771378-6d923900-2438-11eb-8a41-d7bb0c876ea9.png">

<img width="416" alt="Screen Shot 2020-11-11 at 4 09 04 pm" src="https://user-images.githubusercontent.com/7112768/98771385-6ff49300-2438-11eb-9dd5-318cf1f0fc77.png">

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x   |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version:
Backend  version (`]st -m`):
```
[28b8d3ca] GR v0.53.0
[d2c73de3] GR_jll v0.52.0+0
```
Output of `versioninfo()`:
```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1* (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 12
```

**Comment by liasiegelman** [comment]
Hi @navidcy I believe ffmpeg choose the default encoding of yuv422p (which is not compatible with quicktime) instead of yuv420p. I think they need to add something like -pix_fmt yuv420p to line 101 here https://github.com/JuliaPlots/Plots.jl/blob/master/src/animation.jl

Meanwhile here's a fix that worked for me 
ffmpeg -i input.mp4 -vf format=yuv420p output.mp4

**Comment by navidcy** [comment]
Oh! That's great!..... I spend a lot of time playing around with different encodings and couldn't figure it out! I'll give it a go...
