### ISSUE TITLE
[BUG] Nonuniform polar heatmaps in GR are displayed as if the axes were uniform

### ISSUE THREAD

**Issue by fhagemann** [JuliaPlots/Plots.jl#3149]
## Details

I have been trying to plot polar heatmaps with non-uniform axes with Plots.jl.
In my specific case, I have axes with differently high tick densities, so here a generic example:
```julia
using Plots
θ = π .+ 2*asin.(vcat(-(1:-0.001:0).^4,(0.001:0.001:1).^4))
r = sqrt.(0:1:100)
```
where the `θ` axis has a high tick density around `π`:
![TickDensity](https://user-images.githubusercontent.com/30291312/99105831-82f79680-25e3-11eb-8038-b266a581a996.png)

When plotting a heatmap, for example
```julia
heatmap(θ,r,r.*cos.(2θ'), projection = :polar)
```

- In `pyplot`, it gives:
![NUpolar_PyPlot](https://user-images.githubusercontent.com/30291312/99105196-61e27600-25e2-11eb-9500-b5748fe32c90.png)
which (except for the hole in the middle) is what I would expect.

- In `gr`, it gives:
![NUpolar_GR](https://user-images.githubusercontent.com/30291312/99105202-6444d000-25e2-11eb-9132-31ae46810217.png)
which does not agree with the expected outcome. I assume that the heatmap is displayed as if the axes were uniform, effectively stretching the points in regions with high density of axis ticks and compressing it in regions with low axis ticks.

This seems to be related with #1428.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x  |     |
pyplot       |     | x  |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: 
`Plots v1.9.0`

Backend  version: 
`GR v0.53.0`, `PyPlot v2.9.0`

Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = /user/.julia:
  JULIA_NUM_THREADS = 4
  JULIA_PKGDIR = /user/.julia
  JULIA_PKG_DEVDIR = /user/.julia/dev
  JULIA_CXX_RTTI = 1
```

**Comment by hervasa2** [comment]
I have also run into this issue.
