### ISSUE TITLE
Add attribute to scale entire plot (and it's attributes) proportionally to the size

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/Plots.jl#3153]
It would be interesting to have a flag that could be set allowing the user to scale all scalable attributes of a plot with a single argument. That way, you don't need to set the font, line width, etc. manually when you make your plot size larger or smaller.

**Comment by daschw** [comment]
There is the `thickness_scaling` attribute:
```julia
plot(rand(10, 3), xguide="xguide", yguide="yguide", title="title")
```
![thickness_scaling_1](https://user-images.githubusercontent.com/16589944/99194531-2da4bc00-2780-11eb-89df-fbaddde28a04.png)
```julia
plot(rand(10, 3), xguide="xguide", yguide="yguide", title="title", thickness_scaling=1.5)
```
![thickness_scaling=1 5](https://user-images.githubusercontent.com/16589944/99194552-3e553200-2780-11eb-8cc4-4f3ede91e1a7.png)

**Comment by charlesbrodhead3** [comment]
Thanks.  That works well for me, especially on higher resolution displays.
For the non-experts among us, the following can be used to apply to all plots:
`default(size=(1200,800),thickness_scaling=2)`
