### ISSUE TITLE
[BUG] Colorbar flows partially outside the figure when specifying xticks in pyplot backend

### ISSUE THREAD

**Issue by tzxiong** [JuliaPlots/Plots.jl#3155]
## Details

MWE:
```
using Plots; pyplot()
contour([3 2 3;1 2 3;5 6 7],colorbar=true)
contour([3 2 3;1 2 3;5 6 7],xticks = [1,5,2.0,2.5],colorbar=true)
```
The first figure is the correct one:

![Screen Shot 2020-11-16 at 12 26 38 AM](https://user-images.githubusercontent.com/55631424/99215977-7cfbe400-27a2-11eb-86cb-ddd275b1d667.png)

The second figure is missing the right part of the colorbar. Upon further investigation, whenever I specify the largest xtick to also be the largest value of the x-axis, I got the correct colorbar, but if the xticks are all within the interval of the x-axis, specifying xticks can produce the following figure:

![Screen Shot 2020-11-16 at 12 26 25 AM](https://user-images.githubusercontent.com/55631424/99215965-740b1280-27a2-11eb-8faf-7a89405713f9.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | x
pyplot       |  x   |     |
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: [91a5bcdd] Plots v1.6.7
Backend  version (`]st -m`): [d330b81b] PyPlot v2.9.0
Output of `versioninfo()`:
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, cascadelake)

**Comment by BeastyBlacksmith** [comment]
You should be able to workaround by increasing the `right_margin`

**Comment by tzxiong** [comment]
Thanks, though it 'll be even better to know why it behaves like this. The change is quite subtle and I didn't notice until proofreading the draft of the paper :)
