### ISSUE TITLE
Problem with heatmap contour

### ISSUE THREAD

**Issue by bdas123** [JuliaPlots/Plots.jl#3156]
Right now only the maximum value of y (r) is taken into account.

I am getting the above error when trying to use the heatmap polar. 

```julia
heatmap(delta, theta, reshape(tensile_strength_mpa_normal_fault_values, length(theta), length(delta)), proj =:polar, color=:coolwarm)
```

**Comment by BeastyBlacksmith** [comment]
can you provide an example that can be run?
