### ISSUE TITLE
[BUG] Angstrom symbol not appearing with PGFPlotsX

### ISSUE THREAD

**Issue by gdbeck** [JuliaPlots/Plots.jl#3161]
## Details

The Angstrom symbol is suddenly not appearing when using PGFPlotsX.  It works fine with GR:

```
using Plots
using LaTeXStrings

gr()
plot(rand(10),xaxis=(L"\AA"),yaxis=(L"\Omega"))
```

<img width="668" alt="Screen Shot 2020-11-23 at 9 22 14 AM" src="https://user-images.githubusercontent.com/20192704/99994073-668af500-2d6d-11eb-9c97-d390fd06f3c3.png">

But with PGFPlotsX the Angstrom symbol does not appear:

```
pgfplotsx()
plot(rand(10),xaxis=(L"\AA"),yaxis=(L"\Omega"))
```

<img width="819" alt="Screen Shot 2020-11-23 at 9 23 24 AM" src="https://user-images.githubusercontent.com/20192704/99994199-8f12ef00-2d6d-11eb-8b5b-b9754771cc98.png">

Other mathematical symbols seem to work as expecyed.  I'm using LaTeXStrings in the example above but the behavior does not change if I use:

`plot(rand(10),xaxis=("\$\\AA\$"),yaxis=("\$\\Omega\$"))`

Could it have something to do with the fact that the Angstrom symbol is an accented symbol?

I am using Julia 1.5.0 with Plots v1.9.1 and PGFPlotsX v1.2.10.  It was working for me as of Plots v1.4.1 and PGFPlotsX v1.2.6.

Thanks as always for your help!

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pyplot       |     |  x   |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |  x   |     |
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.9.1
Backend  version (`]st -m`): PGFPlotsX v1.2.10
Output of `versioninfo()`:  Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = atom  -a

**Comment by BeastyBlacksmith** [comment]
My guess is, that `\AA` is not supposed to be used in math-mode. You can get the symbol with
`plot(rand(10),xaxis=("\\AA"),yaxis=(L"\Omega"))`

**Comment by gdbeck** [comment]
Thanks for your reply!  I agree that `\AA` should normally not be in math mode.  In previous plots I had been using commands like
`plot(rand(10),xaxis=(L"\lambda_{\rm rest}~(\rm \AA)"),yaxis=(L"\Omega"))`
to get the Angstrom symbol to appear correctly.  This no longer works, but your method is a good work-around.  Thanks again!

**Comment by BeastyBlacksmith** [comment]
Other options that should work are
`plot(rand(10),xaxis=(L"\mathrm{\AA}"),yaxis=(L"\Omega"))` and `plot(rand(10),xaxis=(L"\text{\AA}"),yaxis=(L"\Omega"))`

**Comment by gdbeck** [comment]
That's what I thought too!  These are similar to the approach I used previously (using `\rm{}`) and now neither works for me.  Using `\text{}` throws a LaTeX error that may relate to my LaTeX installation, but `\mathrm{}` produces no error and still does not show the Angstrom symbol under `pgfplotsx()`.  With `gr()`, in contrast, `L"\mathrm{\AA}"` produces a non-italicized Angstrom symbol as expected.  As I mentioned, this was working under previous versions of Plots and/or PGFPlotsX.

**Comment by BeastyBlacksmith** [comment]
Can you say which version worked?

**Comment by BeastyBlacksmith** [comment]
I confirm, that the `mathrm` doesn't work, but you can use `plot(rand(10),xaxis=(L"\mbox{\AA}"),yaxis=(L"\Omega"))`.

For `text` to work you need to call `push!(Plots.PGFPlotsX.DEFAULT_PREAMBLE, raw"\usepackage{amsmath}")` before.

**Comment by gdbeck** [comment]
That's perfect, and I see that both of those work.  Thanks again!  I'm making plots for publication and this is a big help.
