### ISSUE TITLE
[BUG] Session breaks after setting invalid :log axis (GR)

### ISSUE THREAD

**Issue by hexaeder** [JuliaPlots/Plots.jl#3163]
### Details
I've tried to set `yaxis=:log` on an data series with positive and negative values. This might be an invalid use of logarithmic axis. The bug is that i had to restart the Julia session afterwards because something broke.
```julia
using Plots
x = [1,2,3]
y = [-2,2,3]
plot(x,y)
plot!(yaxis=:log)
```
gives the error:
```
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/3Ttrk/src/ticks.jl:283
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/3Ttrk/src/ticks.jl:283
```
From now on, every plot command gives
```
GKS: Rectangle definition is invalid in routine SET_VIEWPORT
```
and the resulting plots are broken (shifted viewport, no ticks, ...). I had to restart the the Julia session to make it work again.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |     |x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: `1.9.1`
Backend  version (`]st -m`): `0.53.0`
Output of `versioninfo()`:
```Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by bdeonovic** [comment]
I'd like to see this addressed. Restarting session is really painful.
