### ISSUE TITLE
[BUG] DPI setting should not affect SVG output?

### ISSUE THREAD

**Issue by fonsp** [JuliaPlots/Plots.jl#3192]
This figure is tiny for some reason (this bug happens sometimes, I don't know when exactly):

![image](https://user-images.githubusercontent.com/6933510/102523420-cf793a80-4097-11eb-9fd3-2522c04d23b3.png)

This is the generated SVG:
![image](https://user-images.githubusercontent.com/6933510/102523650-23841f00-4098-11eb-826b-65acf8a43448.png)

But when I set the dpi to 300:
![image](https://user-images.githubusercontent.com/6933510/102523708-3565c200-4098-11eb-8e6c-681e2e3f213d.png)

The images scaled up. This fixed my issue, but _a DPI setting should not affect the physical image dimensions_. Right?

(The default DPI is 96, which is correct, but the scaling is wrong.)

![image](https://user-images.githubusercontent.com/6933510/102523584-06e7e700-4098-11eb-8f56-e5e7016fd293.png)

**Comment by fonsp** [comment]
Today I set the DPI to 300 to fix the scaling issue, it worked, but when I relaunched the notebook, the plots are enormous:

<img src="https://user-images.githubusercontent.com/6933510/105765068-1d674500-5f58-11eb-90fe-4616dccabfb9.png" width=500>

Generated SVG:

![image](https://user-images.githubusercontent.com/6933510/105765385-a5e5e580-5f58-11eb-8d72-f6cabc804b44.png)


In this case, _I set the DPI and size explicitly_, so how can there still be scaling issue?

**Comment by BeastyBlacksmith** [comment]
Is that only GR or also other backends?

**Comment by fonsp** [comment]
I should add that this issue is about GR with `text/html` output. Since https://github.com/fonsp/Pluto.jl/pull/1090 we use `image/svg+xml` by default inside Pluto.jl, which prevents some of the scaling issues. You have to add `plot(...) |> PlutoUI.as_html` to force the HTML output to reproduce this issue.

I did not check other backends yet, but this issue only concerns backends that output SVG.

**Comment by fonsp** [comment]
I guess my issue boils down to this question:

What should the `dpi` kwarg do? Should `plot(...; size=(100,100), dpi=50)` produce the same SVG image as `plot(...; size=(100,100), dpi=300)`, since SVG is not rasterized?

**Comment by BeastyBlacksmith** [comment]
That is a very good question and I am happy to discuss this on monday, but I'd say so.

**Comment by BeastyBlacksmith** [comment]
There was some discussion about it in https://github.com/JuliaPlots/Plots.jl/issues/733
