### ISSUE TITLE
[BUG]Plots too small with GR backend in Pluto

### ISSUE THREAD

**Issue by dav2017** [JuliaPlots/Plots.jl#3198]
## Details
I get very small plots with the Plots GR backend, see picture below.
Pluto v0.12.17, Plots v1.9.1 and GR v0.49.1
It may be related to this previous issue: https://github.com/JuliaPlots/Plots.jl/issues/3133

![image](https://user-images.githubusercontent.com/33750504/102774354-1c585c00-438b-11eb-9257-ccfcdd4f12ba.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |   x  |
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: 1.9.1
Backend  version (`]st -m`): GR 0.49.1
Output of `versioninfo()`:
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 12

**Comment by BeastyBlacksmith** [comment]
Can you try GR v0.53?

**Comment by dav2017** [comment]
With GR v0.53 the problem is gone.
GR was downgraded for some other dependence a while ago, but I can keep it at v0.53

**Comment by BeastyBlacksmith** [comment]
I guess we should have dropped compat for older versions of GR, when #3133 was fixed

**Comment by FelixBenning** [comment]
![grafik](https://user-images.githubusercontent.com/29106652/102905526-949a4c80-4473-11eb-8bae-14898a711363.png)

what am I doing wrong?

**Comment by feanor12** [comment]
As a fast workaround `plot(rand(10),fmt=:png)` worked for me. Is seems to only effect the SVG output.

**Comment by BeastyBlacksmith** [comment]
Probably the update downgrades again

**Comment by dav2017** [comment]
I forced GR version 0.53 with the following command which, as a consequence, downgraded other packages:
`Pkg.add(PackageSpec(name="GR", version="0.53"))`

**Comment by jonniedie** [comment]
I'm still having this issue. Is there a reason this is closed?

**Comment by BeastyBlacksmith** [comment]
On which Version of Plots and GR?

**Comment by jonniedie** [comment]
Plots: v1.18.2
GR: v0.57.5
Plots.GR: v0.57.3 <-- Not sure why this is happening when I'm explicitly importing GR at a later version
