### ISSUE TITLE
[BUG] Colors are not assigned to pie chart properly

### ISSUE THREAD

**Issue by bvilmann** [JuliaPlots/Plots.jl#3214]
## Details
Colors are not assigned to pie chart properly.

This:
```
pie(rand(3),
    color=[:blue :green :red]
    )
```

Plots this:
![grafik](https://user-images.githubusercontent.com/50515426/103885899-fea42a00-50e0-11eb-8741-c365f22cf737.png)

Regarding a [closed issue](https://github.com/JuliaPlots/Plots.jl/issues/723), I am using the correct syntax for assigning colors.

Taken into account that I am new to Julia and Plots, I looked in the [source](https://github.com/JuliaPlots/Plots.jl/blob/f478a649a0922d57c6338fd854742b3c3bf6a5e5/src/recipes.jl#L925) and found that the recipe does not handle any input colors:
```
@recipe function f(::Type{Val{:pie}}, x, y, z)
    framestyle --> :none
    aspect_ratio --> true
    s = sum(y)
    θ = 0
    for i in eachindex(y)
        θ_new = θ + 2π * y[i] / s
        coords = [(0.0, 0.0); partialcircle(θ, θ_new, 50)]
        @series begin
            seriestype := :shape
            label --> string(x[i])
            x := first.(coords)
            y := last.(coords)
        end
        θ = θ_new
    end
end
@deps pie shape
```
Is this part of the problem or lies this elsewhere?

I would happily implement changes but I need some supervision for this.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |  x   |     |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: `1.10`
Backend  version (`]st -m`):
Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA = C:\Users\Benjamin\AppData\Local\Programs\Julia 1.5.2
  JULIA_EDITOR = "C:\Users\Benjamin\AppData\Local\atom\app-1.53.0\atom.exe"  -a
  JULIA_NUM_THREADS = 2
```

**Comment by nick4f42** [comment]
It should now work with a vector of colors like `[:red, :green, :blue]`.

Passing a row vector `[:red :green :blue]` still makes the pie entirely red but I think that's expected since each column corresponds to a series and a pie plot is only one series.
