### ISSUE TITLE
[BUG] markershape = :star5 doesn't work.

### ISSUE THREAD

**Issue by FaidonKourounakis** [JuliaPlots/Plots.jl#3215]
Simplest example:

```julia
using Plots

plotly()
plot([1,2,3], seriestype=:scatter, markershape=:star5)
```
Creates plot with circles instead of stars.

- rect works
- star5/6/7/8 similarly don't work

Using the latest version of plots (with plotly)

**Comment by t-bltg** [comment]
Not supported (see `src/backends.jl`).
