### ISSUE TITLE
Unicode error with PGFPlotsX [BUG] 

### ISSUE THREAD

**Issue by RaulDurand** [JuliaPlots/Plots.jl#3219]
## Details

Using Plots with PGFPlotsX backend I get strange substitutions for some characters in the tex file. For example, this code
```julia
  plot(
        title = "Interpolação polinomial"
    )
  savefig("fig.tex")
```
generates a file fig.tex that contains:
```latex
\begin{axis}[point meta max={nan}, point meta min={nan}, legend cell align={left}, 
title={Interpola$ç$$ã$o polinomial} ...
```
As can be seen, in the title, some characters as **ç** and **ã** get surrounded by $. The resulting file cannot be included in the main tex file since I get errors like the one below when I try to compile with pdflatex.
```
Command \c invalid in math mode.
```

Is this a bug? Is there any setting in Plots.jl to left the title text without modification?

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     | x   | 
pyplot       |     |  x  | 
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |  x  |     |
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.10.1
Backend  version (`]st -m`): v1.2.10
Output of `versioninfo()`: Julia Version 1.5.1

**Comment by BeastyBlacksmith** [comment]
Honestly thats an issue of `Latexify` to work around you can wrap yout title in `LaTeXString`:
```
  plot(
        title = LaTeXString("Interpolação polinomial")
    )
```
