### ISSUE TITLE
[BUG] Plot size in 1.6beta in Pluto

### ISSUE THREAD

**Issue by clad26** [JuliaPlots/Plots.jl#3222]
## Details
The size of plots in GR backend in Pluto, are oddly small(specifically, for svg, it works fine for png)

### Backends

This bug occurs on
Any plot using svg and GR. Example: plot(rand(10), rand(10))

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  ✔  |     | 
pyplot       |     |     | ✔
plotly       |     |     | ✔
plotlyjs     |     |     | ✔
pgfplotsx    |     |     | ✔
inspectdr    |     |     | ✔

### Versions

Plots.jl version:   [91a5bcdd] Plots v1.10.1
Backend  version (`]st -m`):   [28b8d3ca] GR v0.49.1
Output of `versioninfo()`:
Julia Version 1.6.0-beta1
Commit b84990e1ac (2021-01-08 12:42 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)

 Pluto version:   [c3e4b0f8] Pluto v0.12.18

![Screenshot from 2021-01-12 00-41-26](https://user-images.githubusercontent.com/51269425/104294364-16b2e980-54e5-11eb-8f77-ee093e6a8d3b.png)

**Comment by daschw** [comment]
This is because you are not using the latest GR version. Some other dependencies in your Project avoid the update.
You could try
```julia
julia> ]

pkg> add GR@0.53
```
to find out more about the conflicts.

**Comment by clad26** [comment]
Thanks!
I guess updating did the job
It downgraded HTML.jl thought

**Comment by daschw** [comment]
Great, I think with the next release GR will be compatible with HTTP.jl 0.9 (https://github.com/jheinen/GR.jl/commit/209dddb0c77aabcf9ac807e9c46144214733f98d)
