### ISSUE TITLE
Legend labels require a 1xN array and will not accept size Nx1 or N[FR]

### ISSUE THREAD

**Issue by lyndond** [JuliaPlots/Plots.jl#3230]
The `label` arg expects the labels arranged as a row vector, or else you get something that looks like this:

<img width="668" alt="Screen Shot 2021-01-19 at 11 18 19" src="https://user-images.githubusercontent.com/8090896/105067198-78c39f80-5a4d-11eb-9bc7-b3f06d268b99.png">

```Julia
A = [1 2 3; 4 5 6]
x = 1:2
labels = 1:3
plot(x, A, label=labels) # produces plot above

# but this works (below)
plot(x, A, label=labels')
```
<img width="650" alt="Screen Shot 2021-01-19 at 11 59 19" src="https://user-images.githubusercontent.com/8090896/105067559-ca6c2a00-5a4d-11eb-9b4b-3ba7165fa321.png">

**Comment by t-bltg** [comment]
Duplicate of https://github.com/JuliaPlots/Plots.jl/issues/4199.

This is documented: https://docs.juliaplots.org/dev/input_data/#columns-are-series.
