### ISSUE TITLE
[BUG] lens! lines are not plotted correctly when using logarithmic xscale

### ISSUE THREAD

**Issue by oskarddfa** [JuliaPlots/Plots.jl#3241]
## Details
Using the lens! recipe with a logarithmic scaled x-axis renders wrongly. 

```julia
plot(1:30,1:30, xscale=:log10)
lens!([1.,10.],[1.,10.], inset=(1, bbox(0.1, 0.1, 0.4, 0.4)))
```
![Wrong plotted line](https://user-images.githubusercontent.com/11228525/105699924-64c5e500-5f08-11eb-8fa5-d49fb9b05e74.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x    |     |
pyplot       |   x  |     |
plotly       |   x  |     |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: 
`v1.10.1`

Backend  version (`]st -m`): 
```
GR v0.53.0
Plotly v0.3.0
PyPlot v2.9.0
```
 
Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by BeastyBlacksmith** [comment]
What is wrong about the xaxis?
