### ISSUE TITLE
problem with surface using pgfplotsx () [BUG]

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaPlots/Plots.jl#3248]
## Details
```
x = Measurement.(10 * sort(rand(10)), rand(10))
y = Measurement.(10 * sort(rand(10)), rand(10))
z = Measurement.(10 * sort(rand(10)), rand(10))

surface(x,y,surf)
```

! Package pgfplots Error: No such element: \pgfplotsarrayselect-1\of{pgfpl@cm@p
lots1@X}.

See the pgfplots package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.401 \end{axis}

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pyplot       |     |   x  |
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    | x    |     |
inspectdr    |     |     |x

### Versions

Plots.jl version: 1.10.1
Backend  version (`]st -m`): 1.2.10
Output of `versioninfo()`:
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by daschw** [comment]
Firstly, I don't really understand how you want to plot a surface with three vectors as input. For surface you usually use one of the following:
```julia
surface(z::Matrix)
surface(x::Vector, y::Vector, z::Matrix) # with matching dimensions
surface(x::Vector, y::Vector, f::Function) # where f takes two scalars as input and returns one scalar
```
Secondly, the recipes for Measurements are implemented in the Measurements.jl package, and (looking at https://github.com/JuliaPhysics/Measurements.jl/blob/master/src/plot-recipes.jl) there are no plot recipes for Measurements and 3D plots.

**Comment by Kelvyn88** [comment]
Firstly, I only wanted to run the example provided in the Plots examples for PGFPlotsX. 


Secondly, there is a working example for PyPlot, GR. Booth functions takes two scalars as input and returns one scalar. 

```
using Plots, LaTeXStrings, LinearAlgebra
pgfplotsx()

booth(x) = (x[1]+2x[2]-7)^2 + (2x[1]+x[2]-5)^2

x1 = -20:0.5:20
x2 = -20:0.5:20

plot!(x1,x2, (x1,x2)-> booth([x1,x2]), st=:surface)
```

**Comment by daschw** [comment]
OK, I see, so the issue is not related to Measurements. Sorry, I misunderstood. `surface` does not seem to work for pgfplotsx() at all:
```julia
using Plots
pgfplotsx()
surface(rand(10, 10))
```
fails with the same error.
Thanks for reporting!

**Comment by Kelvyn88** [comment]
Thanks. Documentations says that surface is available for pgfplotsx, but there is a problem. Contour, contour3d and heatmap works properly!
