### ISSUE TITLE
heatmap() is producing empty plots 

### ISSUE THREAD

**Issue by mahdiarsadeghi** [JuliaPlots/Plots.jl#3256]
```
using Plots
plotly()

xs = [string("x", i) for i = 1:10]
ys = [string("y", i) for i = 1:4]
z = float((1:4) * reshape(1:10, 1, :))
heatmap(xs, ys, z, aspect_ratio = 1)
```

<img width="814" alt="Screen Shot 2021-01-28 at 13 25 24" src="https://user-images.githubusercontent.com/39443607/106182009-4a8c4100-616c-11eb-9c11-42c08b9ee1f5.png">

**Comment by daschw** [comment]
Works fine for me:
![Screenshot_20210128_210618](https://user-images.githubusercontent.com/16589944/106192690-d32ad180-61ac-11eb-84ab-cf5f178f7271.png)
What version of Plots are you using?

**Comment by daschw** [comment]
Please let me know if the issue still persists for you.
