### ISSUE TITLE
[BUG] surface not working with PyPlot or PGFPlots backend

### ISSUE THREAD

**Issue by RodolfoFigueroa** [JuliaPlots/Plots.jl#3259]
## Details
When trying to use the `surface` method with the PyPlot backend, the error `KeyError: key :cbar_width not found` is thrown.

For completeness, I also added the bug with PGFPlots, already reported in #3248.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     | X    |
pyplot       |   X  |     |
plotly       |     | X    |
plotlyjs     |     |  X   |
pgfplotsx    | X    |     |
inspectdr    |     |     |X

### Versions

Plots.jl version: 1.10.2
Backend  version (`]st -m`):
- Pyplot: 2.9.0
- PGFPlotsX: 1.2.10

Output of `versioninfo()`:
```
Julia Version 1.5.3
Commit 788b2c77c1* (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, skylake)
```

**Comment by simz089s** [comment]
Not sure if related but I get the same error `KeyError: key :cbar_width not found` when setting the `zcolor` parameter in 3D plots with PyPlot backend. Happened after upgrading from Plots.jl 1.10.4 to 1.10.5 .

```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
