### ISSUE TITLE
[FR] Use existing limits

### ISSUE THREAD

**Issue by gustaphe** [JuliaPlots/Plots.jl#3269]
```julia
x = [3.1, 3.2, 3.3];
y = x.^2;
plot(x,y,st=:scatter) # Sets xlim to something like (3,3.4)
plot!(x->x^2) # changes xlim to (-5,5)
```
I quite often want to plot a (e.g. fitted) function together with the existing plot, without updating the limits. I could fetch the current limits by entering the axis list and reusing those, but something like `plot!(..., xlim=:reuse)` or `xlim=(:reuse,:reuse)` would be really nice.

**Comment by daschw** [comment]
Actually,  your suggestion should be the default behavior.

**Comment by gustaphe** [comment]
Awesome. Come to think of it, the keyword version would still be useful for plotting other things together with existing plots. Also for recipes, `xlim -> :keep` seems like it would be a pretty powerful tool.
