### ISSUE TITLE
Citation information for Researchers. [FR]

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaPlots/Plots.jl#3275]
Please search existing issues to avoid duplicates.

**Comment by mkborregaard** [comment]
Right now you just have to cite the github page I think. @daschw should we get a zenodo citable doi at least?

**Comment by DhruvaSambrani** [comment]
While I definitely feel you should have a zenodo doi, even if you don't have a doi, you could have a simple citation line like 

```
Julia: A Fresh Approach to Numerical Computing. Jeff Bezanson, Alan Edelman, Stefan Karpinski, Viral B. Shah. (2017) SIAM Review, 59: 65–98.
```

Best however would be a bibtex entry, so researchers can just copy paste it!

**Comment by mkborregaard** [comment]
That reference you posted is to a published paper though.

**Comment by BeastyBlacksmith** [comment]
I set up the DOI and probably there will be a paper later this year
