### ISSUE TITLE
[BUG] ymirror=true does not work with the pyplot backend

### ISSUE THREAD

**Issue by churli** [JuliaPlots/Plots.jl#3297]
## Details
Using the pyplot backend I cannot manage to have the y-axis on the right.

MWE:
```julia
using Plots; pyplot()
plot(rand(100), ymirror=true)
```
This just outputs a plot with the y-axis on the left, as if `ymirror=false`.  
The problem also affects plots with 2 different y-axes via `twinx()`: in this case both axes end up superimposed on the left and I could not find a way to get a nice plot with 2 different y-axes.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pyplot       |  x   |     |
plotly       |     |     |  x
plotlyjs     |     |     |  x
pgfplotsx    |     |     |  x
inspectdr    |     |     |  x

### Versions

Plots.jl version: `v1.10.4` (latest)
Backend  version (`]st -m`): `v2.9.0`(latest)
Output of `versioninfo()`:
> Julia Version 1.5.3
> Commit 788b2c77c1 (2020-11-09 13:37 UTC)
> Platform Info:
>  OS: macOS (x86_64-apple-darwin18.7.0)
>  CPU: Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
>  WORD_SIZE: 64
>  LIBM: libopenlibm
>  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by isentropic** [comment]
I will fix this soon, by mistake it was taken out recently

**Comment by churli** [comment]
Thanks for your quick reply @isentropic !
Could you please point me to the right file/function so that I can work around it while waiting for the fix?

Thanks!

**Comment by isentropic** [comment]
The changes introduced here
https://github.com/JuliaPlots/Plots.jl/commit/62af64f08abd89ef90fdb5921839245617419a41

The plan was to separate xymirror somewhere else, as it only works for 2d plots in pyplot

**Comment by isentropic** [comment]
@chfin please check out the PR. Before it gets merged, would you please perform some graphical tests and attach your findings in the PR. 
Test some of the commands and attach screenshots of behavior before and after the PR, please?

Attributes in mind:
```
(x)ymirror
framestyle=(:box, :axes, :semi) # I guess of other framestyles mirroring is ill defined, so don't bother checking those
twinx()
```

**Comment by isentropic** [comment]
And would you please let me know if it now behaves the way you expect it to or not?

The reason why it was deleted at some point, is that the behavior was largely inconsistent with GR backend, so I decided to remove it altogether.

**Comment by isentropic** [comment]
fixes merged and released feel free to reopen if does not work

**Comment by churli** [comment]
I would just like to confirm that it works as expected now.
Thanks again!
