### ISSUE TITLE
[FR] Expose additional keyword arguments for pyplot hexbin

### ISSUE THREAD

**Issue by sethaxen** [JuliaPlots/Plots.jl#3301]
Currently PyPlot is the only backend that supports  the series type `:hexbin`. Right now it doesn't offer much customization. Here are the defaults

```julia
using Plots; pyplot()
x, y = randn(10_000), randn(10_000)
hexbin(x, y; bins=50)
```
![tmp](https://user-images.githubusercontent.com/8673634/107992980-bc4af400-6f8e-11eb-8701-74202104bf27.png)

Empty bins are still shown, and we can't remove the hexagon border. Setting `linewidth=0` produces
```julia
hexbin(x, y; bins=50, linewidth=0)
```
![tmp3](https://user-images.githubusercontent.com/8673634/107993442-498e4880-6f8f-11eb-8f03-f32c0e76c8de.png)

But calling `PyPlot.hexbin` directly using the arguments `edgecolors="face"` and `mincnt=1` is much cleaner:

```julia
Plots.PyPlot.hexbin(x, y; gridsize=50, mincnt=1, edgecolors="face")
Plots.PyPlot.show()
```
![tmp2](https://user-images.githubusercontent.com/8673634/107993030-da185900-6f8e-11eb-9413-c80e2c804727.png)

It would be nice to have these arguments exposed somehow. Currently the `extra_kwargs` machinery seems to be not used for PyPlot.

**Comment by BeastyBlacksmith** [comment]
One might draw inspiration from https://github.com/JuliaPlots/Plots.jl/pull/2703 on how to implement this
