### ISSUE TITLE
[BUG] Bad values with yscale=:log10 break follow-up plots in GR

### ISSUE THREAD

**Issue by mortenpi** [JuliaPlots/Plots.jl#3321]
## Details

Plotting bad (negative) values while `yscale=:log10` is set with the GR backend breaks the GR output also for future (valid) plots. For an MWE, trying to render the two following plots, this happens:

```
julia> plot(1:-0.01:-1, yscale=:log10)
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/es5pb/src/ticks.jl:283
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/es5pb/src/ticks.jl:283
```

![plot1](https://user-images.githubusercontent.com/147757/109086849-34749f00-7771-11eb-910b-c7d804cb37c8.png)

```
julia> plot(1:10)
GKS: Rectangle definition is invalid in routine SET_VIEWPORT
```

![plot2](https://user-images.githubusercontent.com/147757/109086860-36d6f900-7771-11eb-8188-c728736c7719.png)

Note the missing tick labels etc.

Other notes:

* I also tried PyPlot, where the first plot just throws an error, and the second plot is fine. I would actually expect GR to simply throw an error as well for the first plot, but instead it actually tries to render it.
* I usually run into this issue in vscode, where I accidentally plot rubbish (e.g. pass negative values to a log plot) and then all the following plots are not rendering correctly. The only way to get Plots working again is to restart the Julia session (or change backends; but if you change back to GR, it's still broken). **For this, as a workaround, is there any way to reset the GR backend or something along those lines?**
* Looks similar to #2872, but definitely still occurs.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     | x    |
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: master (v1.10.5+)
Backend  version (`]st -m`): GR v0.54.0, GR_jll v0.53.0+0
[Full MWE manifest](https://gist.github.com/mortenpi/71c28d07357c7bd463a6ad6f7340d19c#file-manifest-toml)
Output of `versioninfo()`:

```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

**Comment by t-bltg** [comment]
@mortenpi, we discussed this in https://github.com/JuliaPlots/Plots.jl/pull/3601, closing.

**Comment by mortenpi** [comment]
I would advocate for re-opening this. The follow-up plots are still breaking even on the latest master.

On another related note, the new warning

```
┌ Warning: Invalid negative or zero value 0.0 found at series index 101 for log10 based yscale
└ @ Plots ~/.julia/packages/Plots/igCxX/src/utils.jl:92
```

seems to be printed for each problematic value? So when I run `plot(1:-0.01:-1, yscale=:log10)` I literally get a hundred of them. Do you reckon it might make sense to print the warning once per `plot` call?

**Comment by t-bltg** [comment]
> I would advocate for re-opening this. The follow-up plots are still breaking even on the latest master.
> 
> On another related note, the new warning
> 
> ```
> ┌ Warning: Invalid negative or zero value 0.0 found at series index 101 for log10 based yscale
> └ @ Plots ~/.julia/packages/Plots/igCxX/src/utils.jl:92
> ```
> 
> seems to be printed for each problematic value? So when I run `plot(1:-0.01:-1, yscale=:log10)` I literally get a hundred of them. Do you reckon it might make sense to print the warning once per `plot` call?

Do you care about the indices at where this occurs or not ?

**Comment by t-bltg** [comment]
> I would advocate for re-opening this. The follow-up plots are still breaking even on the latest master.

Sorry, I was too quick when cleaning up issues. I see now what you meant by saying "breaking" GR.

**Comment by t-bltg** [comment]
@mortenpi, btw I see that you are on Linux. Any reason for not using `ENV["GKSwstype"] = "x11"` instead of using the buggy GKS QtTerm ? That what I use on my Ubuntu.

**Comment by mortenpi** [comment]
Hmm. As for the "why", I am just running with the defaults and they seem to work most of the time :smile: I do set `GKSwstype=100` when running non-interactively though (on CI and when generating heaps of plots in a script) because it's much faster that way.

However, I don't think it's relevant for this? First, in the REPL I get a `GKS: X11 support not compiled in
` warning with `x11` and no window pops up. Secondly, the follow-up plots are still broken (while I can't see them interactively, I can `savefig` them):

```
julia> ENV["GKSwstype"]
"x11"

julia> plot(1:-0.01:-1, yscale=:log10)
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/n4I4Q/src/ticks.jl:295
GKS: X11 support not compiled in
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/n4I4Q/src/ticks.jl:295
┌ Warning: Invalid negative or zero value 0.0 found at series index 101 for log10 based yscale
└ @ Plots ~/.julia/packages/Plots/1miUQ/src/utils.jl:92

julia> plot(1:20)
GKS: Rectangle definition is invalid in routine SET_VIEWPORT
```

**Comment by t-bltg** [comment]
> Hmm. As for the "why", I am just running with the defaults and they seem to work most of the time

Ok, thanks for the heads up.

> GKS: X11 support not compiled in

I forgot I compiled my own GR against x11.
