### ISSUE TITLE
Titles get repeated in "nested plots"

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaPlots/Plots.jl#3342]
Nested plots with a single title result in all plots having the same title. I believe this could be a bug. An MWE follows:

```julia
julia> using Plots

julia> plot(
               scatter(rand(10), rand(10), label=:none, xlabel="x", ylabel="p"),
               plot(
                       plot(1:20, rand(20), label="x", xlabel="t"),
                       plot(1:30, rand(30), label="p", xlabel="t"),
                       layout=(2, 1),
               ),
               layout=(1, 2),
               title="Hello world!",
       )

julia> savefig("hello-world.png")
```

![hello-world](https://user-images.githubusercontent.com/37125/110346488-5e9a4c80-800e-11eb-9625-e9495a4fb84d.png)

### Versions

```julia
julia> versioninfo()
Julia Version 1.4.1
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen 5 1600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)
Environment:
  JULIA_NUM_THREADS = 12

(@v1.4) pkg> st Plots
Status `~/.julia/environments/v1.4/Project.toml`
  [91a5bcdd] Plots v1.6.12
```

**Comment by mkborregaard** [comment]
I understand this is unexpected, it is not a bug. It's just a consequence of the absence of global tiltles in Plots, and that attributes added to the outer `plot` call gets applied to all the subplots (with the exception of size and layout).

**Comment by schneiderfelipe** [comment]
> I understand this is unexpected, it is not a bug. It's just a consequence of the absence of global tiltles in Plots, and that attributes added to the outer `plot` call gets applied to all the subplots (with the exception of size and layout).

Interesting, I didn't know that (thanks for the clarification, by the way). Is there a way of adding a title to the outer plot only? The following does not work either (same result as the above):

```julia
julia> using Plots

julia> p = plot(
               scatter(rand(10), rand(10), label=:none, xlabel="x", ylabel="p"),
               plot(
                       plot(1:20, rand(20), label="x", xlabel="t"),
                       plot(1:30, rand(30), label="p", xlabel="t"),
                       layout=(2, 1),
               ),
               layout=(1, 2),
       )

julia> title!(p, "Hello world!")
```

**Comment by mkborregaard** [comment]
No, a supertitle is one of the most requested features though. Some people add an invisible subplot across the top and give that a title, though that is rather hacky of course.

**Comment by BeastyBlacksmith** [comment]
> No, a supertitle is one of the most requested features though.

`plot_title` is now implemented.
