### ISSUE TITLE
[FR] Support Revise.jl workflow with backends/ files

### ISSUE THREAD

**Issue by isentropic** [JuliaPlots/Plots.jl#3345]
Currently Revise does not update files under backend directory. The reason could be that the backends are imported in a hacky way. That is why Revise does not track those files. Perhaps we could have a developer mode when all files are included?

**Comment by timholy** [comment]
If you're using `@require`, Revise should track them ([350 lines of tests say so](https://github.com/timholy/Revise.jl/blob/e4503d3381e4068fb5d11a065c28001c0e038d50/test/runtests.jl#L3296-L3534)). There's even a separate ["LikePlots" test](https://github.com/timholy/Revise.jl/blob/e4503d3381e4068fb5d11a065c28001c0e038d50/test/runtests.jl#L2697-L2740).

But of course there may be bugs or limitations, so a good MWE would be appreciated.

**Comment by isentropic** [comment]
It is hard to come up with MWE, as once it used to work, now it does not for me. Perhaps @BeastyBlacksmith or @daschw can comment on their experience?

For example with PyPlot,
the inclusion line is [here](https://github.com/JuliaPlots/Plots.jl/blob/060162c35667bdd6cd1d018acc0cf2e67d2bb741/src/init.jl#L68)
The relevant structs are constructed via [macro](https://github.com/JuliaPlots/Plots.jl/blob/060162c35667bdd6cd1d018acc0cf2e67d2bb741/src/backends.jl#L23)
and those structs are initialized shortly after [here](https://github.com/JuliaPlots/Plots.jl/blob/060162c35667bdd6cd1d018acc0cf2e67d2bb741/src/backends.jl#L250)

So I believe compile time it is impossible to know the needed structs

Also the order of file inclusion is given [here](https://github.com/JuliaPlots/Plots.jl/blob/060162c35667bdd6cd1d018acc0cf2e67d2bb741/src/Plots.jl#L209)

I honestly don't know how Revise magically works, but this is the way how backend files are included. MWE is difficult to come up with, as I do not understand what would be important

**Comment by isentropic** [comment]
@timholy I know you must be busy, but would you please take a quick look at this problem? I'm having this issue with multiple julia versions with different machines. For me, non-backend code (files in `/src/*.jl`) are tracked perfectly, but the files in `backends/*.jl` are not. 

This realyl hurts at least my workflow where have to spend ~30sec waiting everytime when I try to edit something in a backend and test it out.

**Comment by isentropic** [comment]
I think that backend structs initialized with a macro could be a problem. I mentioned the culprints in the comment above

**Comment by isentropic** [comment]
The issue has been confirmed with optional backends. For example "src/pyplot.jl, pgfplotsx.lj" do not work

**Comment by aloy1496** [comment]
Yes
