### ISSUE TITLE
Combining aspect_ratio with legend=:outertopright is not correct with GR [BUG] 

### ISSUE THREAD

**Issue by sefffal** [JuliaPlots/Plots.jl#3348]
## Details

Setting the legend position to `:outertopright` leads `aspect_ratio` to be incorrect with the GR backend. In the example below, plot `one` is squashed along the x-axis to make room for the legend.

Example:
```
theme(:dao) # occurs with :default as well
gr()
x = [-1, 1, 1, -1, -1]
y = [-1, -1, 1, 1, -1]
one = plot(x, y, legend=:outertopright, aspect_ratio=1, title="One")
two = plot(x, y, legend=:none, aspect_ratio=1, title="Two")
```
![image](https://user-images.githubusercontent.com/7330605/111053693-d082f380-845d-11eb-97f7-111f01126b46.png)
![image](https://user-images.githubusercontent.com/7330605/111053694-d7116b00-845d-11eb-98db-f4582f548beb.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |     | x
plotly       |     |  x  |
plotlyjs     |     |     | x
pgfplotsx    |     |  x  | 
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.10.6
Backend  version (`]st -m`): GR v0.55.0 (master)
Output of `versioninfo()`: 
```
Julia Version 1.6.0-rc2
Commit 4b6b9fe4d7 (2021-03-11 07:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 1
  JULIA_EDITOR = "C:\Users\William\AppData\Local\Programs\Microsoft VS Code\Code.exe"
```

**Comment by daschw** [comment]
Thanks for reporting!
