### ISSUE TITLE
Histogram with weights - unexpected output

### ISSUE THREAD

**Issue by jo-fleck** [JuliaPlots/Plots.jl#3349]
I am inspecting the difference between a weighted and unweighted distribution using weights. The weights are frequency weights with values [32, 16263] with a median of 1341.

I compute means of the weighted and unweighted distributions as 
```
mean(dist_data)
mean(dist_data, fweights(dist_data_weights))
```
and get 64122.80 and 63667.44 respectively.

However, when I plot 
```
histogram(dist_data, title = "Comparing Distributions", label = "unweighted", α = 0.3, bin = 100)
histogram!(dist_data, fweights(dist_data_weights), label = "weighted", α = 0.3, bin = 100)
```
I get the picture below - the weighted distribution is compressed and scrambled in the tiny peak on the left.

![histogram_weights](https://user-images.githubusercontent.com/25301265/111065131-75cab580-84b8-11eb-95ef-ed421e9b6d69.png)

(I get the same picture when I use `weights`, `aweights` or `pweights`.)

Many thanks for looking into this!

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.9.1
Backend  version (`]st -m`): GR v0.53.0
Output of `versioninfo()`:
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2

**Comment by daschw** [comment]
I think weights have to be provided as a kwarg, like
```julia
histogram!(dist_data, weights=fweights(dist_data_weights), label = "weighted", α = 0.3, bin = 100)
```

**Comment by jo-fleck** [comment]
Many thanks! That's it.

I am a bit surprised that my approach fails silently (without warning/error). Also, afaik the syntax for other functions accepting weights is as I assumed, e.g. `mean(x, weights(w))`

Is there a reason for this behavior and syntax?

Again thanks for helping!

**Comment by mkborregaard** [comment]
By design Plots always tries to convert the data you add to a numeric vector. That's what allows the package to be so flexible in plotting. 
It's true that StatsBase and some derived packages use dispatch on positional arguments for weights. However, Plots uses keyword arguments for anything that modifies the plot, and positional arguments for data you want to plot, throughout. Internal consistency in Plots is more important than consistency with some other statistical packages for a single argument.

**Comment by jo-fleck** [comment]
Thanks for the detailed explanation. I think adding another example like this to the histogram doc would help to clarify. (I can open a PR if you think it's useful.)

`histogram([1,2,1,1,4,3,8],bins=0:8,weights=weights([4,7,3,9,12,2,6]))`

**Comment by mkborregaard** [comment]
Yes, great!

**Comment by jo-fleck** [comment]
I found the doc here: https://github.com/JuliaPlots/Plots.jl/blob/master/src/shorthands.jl

What's the preferred PR workflow for Plots.jl? (Do I fork the repo and then PR against master?)

**Comment by mkborregaard** [comment]
Isn't it already here? https://docs.juliaplots.org/latest/generated/plotly/#plotly-ref15

**Comment by jo-fleck** [comment]
Sorry, I had not seen this before - my bad. But I actually meant the doc you get with 
```
? 
histogram
```

**Comment by mkborregaard** [comment]
Ah yes, I see. Yes then you fork and PR on Plots master

**Comment by jo-fleck** [comment]
Done

https://github.com/JuliaPlots/Plots.jl/pull/3353
