### ISSUE TITLE
[FR] Install Plots.jl without GR

### ISSUE THREAD

**Issue by melonedo** [JuliaPlots/Plots.jl#3361]
GR is a rather heavy backend, and it has a custom building step, which makes it not very easy to install. Installing Plots is also complicated by this. Can I install a "bare-bone" Plots without custom default backends other than GR?

**Comment by mkborregaard** [comment]
Unfortunately no - this was discussed heavily in the past, where it came with no backend by default, but onboarding of new users was complicated by this. In the end it was decided to include GR by default. I'm not sure how it would work in practice to allow this option.

**Comment by melonedo** [comment]
It seems that installation is no longer an issue.
