### ISSUE TITLE
[BUG] Data hover in heatmap - Plotly(JS) backends

### ISSUE THREAD

**Issue by JakobAsslaender** [JuliaPlots/Plots.jl#3363]
Hi,
when using PlotlyJS as a Plots backend, the data hover does not work with heatmaps, while it does work with line-plots. This stands in contrast to using the PlotlyJS package directly, where the data hover works. 

## Details
MWE plotlyjs backend (does not work): 
`using Plots`
`plotlyjs()`
`x = randn(100,100)`
`heatmap(x, hover=x)`

it works neither with, nor without the `hover=x`

<img width="591" alt="image" src="https://user-images.githubusercontent.com/51003502/112025186-4eed2e80-8b0b-11eb-8f9e-d53e5bfa154e.png">

MWE plotly backend (does not work): 
`using Plots`
`plotly()`
`x = randn(100,100)`
`heatmap(x, hover=x)`

<img width="594" alt="image" src="https://user-images.githubusercontent.com/51003502/112025626-bc995a80-8b0b-11eb-8a9c-258cde7d2975.png">

MWE PlotlyJS directly (does work): 
`using PlotlyJS`
`x = randn(100,100)`
`plot(heatmap(z=x))`

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/51003502/112026079-39c4cf80-8b0c-11eb-8abb-a98a292e73d3.png">

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | x
pyplot       |     |     | x
plotly       |   x  |     |
plotlyjs     |  x   |     |
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: [91a5bcdd] Plots v1.11.0

Backend  version (`]st -m`):
[f0f68f2c] PlotlyJS v0.14.1
[58dd65bb] + Plotly v0.3.0

Output of `versioninfo()`:
Julia Version 1.5.4
Commit 69fcb5745b (2021-03-11 19:13 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  JULIA_NUM_THREADS = 4

Thanks for your help, everyone!

**Comment by bencherian** [comment]
I don't know enough about how this works to say how this relates to the correct solution, but you can workaround this issue by commenting out the call to `plotly_hover!` in on line 659 of backends/plotly.jl. I'm sure this breaks the the ability to add custom tooltips for the other plot types.

**Comment by BeastyBlacksmith** [comment]
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/3051

**Comment by JakobAsslaender** [comment]
Closing this issue because it's a duplicate.
