### ISSUE TITLE
[BUG] Colorbar Is Missing When Plotting Geometries

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaPlots/Plots.jl#3368]
## Details

When plotting geometries, the colorbar does not show up even with `colorbar=true` explicitly.I was chatting with @mkborregaard today about what I thought was just a gripe (:grapes:) about this being an implementation quirk. Instead, it was actually a bug I discovered and he wanted me to open the issue!

Here is the code to reproduce the error

```julia
using DataFrames
using Plots
using Shapefile
using ColorSchemes

states = Shapefile.Table("cb_2018_us_state_5m.shp") |> DataFrame
skip = ["02", "15", "60", "66", "69", "72", "78"]
filter!(row -> !(row[:STATEFP] in skip), states)
sort!(states, [:GEOID])

rand_vals = [rand() for _ in 1:length(states.geometry)]

c_values = ColorSchemes.get(ColorSchemes.colorschemes[:seismic], rand_vals)

choropleth = plot(states.geometry, axis = ([], false), title = "Random Plot"; fillcolor = permutedims(c_values), colorbar = true)
```

The associated shapefile is located in this zip here: https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_state_5m.zip

Please let me know if you want me to test anything here - thanks for the great package and great work so far! :smile: 

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  X   |     |
pyplot       |     |     | X
plotly       |     |     | X
plotlyjs     |     |     | X
pgfplotsx    |     |     | X
inspectdr    |     |     | X

### Versions

Plots.jl version: v1.11.0
Backend  version (`]st -m`): [d2c73de3] GR_jll v0.53.0+0
Output of `versioninfo()`:
```
Julia Version 1.6.0-rc3
Commit 23267f0d46 (2021-03-16 17:04 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = nvim
```

**Comment by daschw** [comment]
I would use `fill_z` for this:
```julia
using DataFrames
using Plots
using Shapefile

states = Shapefile.Table("cb_2018_us_state_5m.shp") |> DataFrame
skip = ["02", "15", "60", "66", "69", "72", "78"]
filter!(row -> !(row[:STATEFP] in skip), states)
sort!(states, [:GEOID])

n = size(states, 1)
plot(states.geometry, fill_z=rand(1, n), title="My title", cbar=true, color=:seismic)
```
![shapes](https://user-images.githubusercontent.com/16589944/112309713-f4d3a100-8ca3-11eb-9442-9e66962af6de.png)

**Comment by mkborregaard** [comment]
ahh, I didn't realize the code said `fillcolor` not `fill_z` :-D

**Comment by TheCedarPrince** [comment]
Perfect @mkborregaard and @daschw ! Since I hadn't really seen this documented anywhere in the ecosystem, could I add a docs PR somewhere with this as an example?

**Comment by daschw** [comment]
Sure, that would be great. I'd say either somewhere at http://docs.juliaplots.org/latest/colors/ or at http://docs.juliaplots.org/latest/attributes/ would be the right place.

**Comment by TheCedarPrince** [comment]
Hey @daschw - before I create this PR, what is fill_z exactly doing? I was a bit confused about `fill_z` versus `fillcolor`.

**Comment by mkborregaard** [comment]
automatically reinterprets a vector of numbers on a color scale and adds a colorbar for the mapping

**Comment by daschw** [comment]
`marker_z` and `line_z` does the same thing for marker color and line color.
