### ISSUE TITLE
[FR] Legend marker padding and legend size/proportion using `gr`

### ISSUE THREAD

**Issue by luboshanus** [JuliaPlots/Plots.jl#3371]
Hi,

I am using `gr()` to plot scatter and I'd like to have legend at positions `:outerright` or `:outerbottom`. There are several issues I am having and it does not look nice. See screenshots.

First, increasing `size` of the plot and `dpi` space around `marker` is increasing and causes really unused space in the plot - in both situations. In the situation with `:outerbottom` the legend is far far below the plot. Also, it would be great to have labels in a line not only in a column. To say, that `layout of labels` is `(1,3)` not `(3,1)`, for example.

I'm just looking for padding and margin of legend and label markers in legend. Thanks a lot!

```
scatter(rand(100,3), marker=(7, [:hexagon :circle :square], 0.5), legend=:outerright, size=(1000,500), dpi=120)
```
![Screenshot 2021-03-24 at 16 07 06](https://user-images.githubusercontent.com/2473206/112337703-72a4a600-8cbe-11eb-9aa6-9539eb9e64d8.png)

```
scatter(rand(100,3), marker=(7, [:hexagon :circle :square], 0.5), legend=:outerbottom, size=(1000,500), dpi=120)
```
![Screenshot 2021-03-24 at 16 07 40](https://user-images.githubusercontent.com/2473206/112337715-759f9680-8cbe-11eb-880c-3686273fb9ad.png)

The Plots version I have is
```
[91a5bcdd] Plots v1.10.2
```

**Comment by t-bltg** [comment]
@luboshanus does https://github.com/JuliaPlots/Plots.jl/pull/3598 fix this ?

**Comment by t-bltg** [comment]
Horizontal legend supported in https://github.com/JuliaPlots/Plots.jl/pull/4496.
Padding fixed in there as well.
