### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aramirezreyes** [JuliaPlots/Plots.jl#3372]
## Details

Issue shown in Slack thread:

This piece of code used to work in 1.10.6 but it no longer works on 1.11.0

```
julia> using Plots; gr()
julia> x = collect(1:3)
julia> all_nan = [NaN, NaN, NaN]
julia> plot(x, all_nan)
```

I may be related to this pull request.
https://github.com/JuliaPlots/Plots.jl/pull/3320/

It seems like a weird use case but I think it can count as a breaking change?

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     |x
plotly       |     |     |x
plotlyjs     |  x   |     |
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: v1.11.0
Backend  version (`]st -m`): 
GR v0.55.0
PlotlyJS v0.14.1

Output of `versioninfo()`:
versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = /Applications/Emacs.app/Contents/MacOS/Emacs "$@"

**Comment by yha** [comment]
Fixed a while ago by #3468
