### ISSUE TITLE
[BUG] GKS Error When Using Custom ColorScheme with `cgrad` and `palette`

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaPlots/Plots.jl#3373]
## Details

Hi all! Thanks for the great work on this package! I ran into an issue when trying to implement my own custom colorscheme for Plots.jl.

I have the following ColorScheme:

```julia
using Colors
using ColorSchemes
colors = ColorScheme([
	RGB{Float64}(179, 211, 217),
	RGB{Float64}(125, 189, 210),
	RGB{Float64}(0, 143, 180),
	RGB{Float64}(0, 111, 145),
	RGB{Float64}(0, 62, 79),
	])
```

Which I then convert to a ColorGradient

```julia
custom_colors = cgrad(colors, rand_values)
```

All is working and the Colorgradient gets created. However, when I plot doing the following:

```julia
plot(
    states.geometry,
    fill_z = permutedims(rand_vals),
    title = "My Pretty Plot,
    cbar = true,
    color = custom_colors,
    axis = false,
    ticks = false,
    size = (1800, 1000),
    rightmargin = 30px,
    titlefontsize = 20,
)
```

I get this weird read out:

```
...
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
GKS: Colour is invalid in routine SET_COLOR_REP
...
```

Unfortunately, it fills my entire REPL and I cannot get anything else being outputted. I have also confirmed this same behavior with `palette`. 

What is going on here? Thanks for the help! 

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |    X  |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version:   [91a5bcdd] Plots v1.11.0
Backend  version (`]st -m`):   [28b8d3ca] GR v0.55.0
Output of `versioninfo()`:

```
Julia Version 1.6.0-rc3
Commit 23267f0d46 (2021-03-16 17:04 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by kimikage** [comment]
I haven't run the reproduction code, is this an issue regarding the invalid (out-of-range) colors?

> `RGB{Float64}(179, 211, 217),`

Did you mean `RGB{Float64}(179 / 255, 211 / 255, 217 / 255)`?

In any case, this seems to leave room for improvement in error handling.

**Comment by kimikage** [comment]
IMO, this is a matter that should be warned about in `cgrad` and `palette`, not in ColorTypes.jl.

Note that `RGB(179, 211, 217)` throws an error, because the default eltype for `RGB` is `N0f8` (`<:FixedPoint`), and the `FixedPoint` has priority in the promotion rule between `Integer`s and `FixedPoint`s. In other words, the error is a more user-friendly version of the `InexactError` or `DomainError`, and is not a warning about not normalizing to [0, 1] itself.

Also, since in the promotion rule between `N0f8` and `Float64`, `Float64` has priority, and `Float64` can represent all integers in [0, 255] exactly, there is no reason to throw an error in the type system.  And range checking in the color type constructors can cause non-negligible slowdowns in image processing, so we don't want to do it.

**Comment by cormullion** [comment]
I think a ColorScheme.jl scheme can hold any type of color, but when you eventually get round to calling `Colors.weighted_color_mean()` it expects the colors to be [0-1]. It would be possible to prevent the creation of colorschemes with non-[0-1] values, perhaps, by adding a check in ColorSchemes.jl...

**Comment by TheCedarPrince** [comment]
Oh my gosh. 😂 That was totally me forgetting how to program. Thanks @kimikage and @cormullion! I can't believe it was as simple as dividing the colors by 255. That could be a good checking PR for ColorSchemes.jl. I will check in with them on that. Thanks and I am closing this issue. 😄
