### ISSUE TITLE
Failed to add Plots.jl on Julia 1.6.0

### ISSUE THREAD

**Issue by james-a-mcmanus** [JuliaPlots/Plots.jl#3386]
## Details
I've recently tried to add plots on the new version of julia (1.6.0). Trying to add Plots.jl results in a large number of dependencies that fail to precompile:
![image](https://user-images.githubusercontent.com/47943540/112700501-358b1000-8e86-11eb-8052-793c3e5bb202.png)

When i run `using Plots`, this results in a number of LoadErrors.
The first of which is here:

```
ERROR: LoadError: LoadError: InitError: could not load library "/home/james/.julia/artifacts/a720905290c81768185376a3ab5842c296b4cef8/lib/libbz2.so"
/home/james/.julia/artifacts/a720905290c81768185376a3ab5842c296b4cef8/lib/libbz2.so: cannot open shared object file: No such file or directory
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:114
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:114
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/WnWcZ/src/products/library_generators.jl:63 [inlined]
  [4] __init__()
    @ Bzip2_jll ~/.julia/packages/Bzip2_jll/aAOqr/src/wrappers/x86_64-linux-gnu.jl:8
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:674
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:760
  [7] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:998
  [8] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:914
  [9] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:901
 [10] include(mod::Module, _path::String)
    @ Base ./Base.jl:386
 [11] top-level scope
    @ ~/.julia/packages/JLLWrappers/WnWcZ/src/toplevel_generators.jl:170
 [12] include
    @ ./Base.jl:386 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1213
 [14] top-level scope
    @ none:1
 [15] eval
    @ ./boot.jl:360 [inlined]
 [16] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [17] top-level scope
    @ none:1
during initialization of module Bzip2_jll
in expression starting at /home/james/.julia/packages/FreeType2_jll/K7fyn/src/wrappers/x86_64-linux-gnu.jl:4
in expression starting at /home/james/.julia/packages/FreeType2_jll/K7fyn/src/FreeType2_jll.jl:2
```
The others that fail to load are:
- FreeType2_jll
- libas_jll
- ffmpeg_jll
- ffmpeg
- Plots

### Backends
Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x (i think?)   |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |

Backend  version (`]st -m`):
[d2c73de3] GR_jll v0.56.1+0

Output of `versioninfo()
- Julia Version 1.6.
- Commit f9720dc2eb (2021-03-24 12:55 UTC)
- Platform 
    - OS: Linux (x86_64-pc-linux-gnu)
    - CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    - WORD_SIZE: 64
    - LIBM: libopenlibm
    - LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

How would I go about inspecting why these dependencies fail to load? is there a log file i can access somewhere?

Many thanks in advance,
James

**Comment by charlesbrodhead3** [comment]
If a direct solution to your problem can't be found, I'd suggest saving a backup of your .julia directory and then rebuild it from scratch using your Manifest.toml and Project.toml.  Julia v1.6's parallel precompiling has sped up this process immensely.

**Comment by haotian127** [comment]
Got the same error!

```
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2
```

**Comment by james-a-mcmanus** [comment]
> If a direct solution to your problem can't be found, I'd suggest saving a backup of your .julia directory and then rebuild it from scratch using your Manifest.toml and Project.toml. Julia v1.6's parallel precompiling has sped up this process immensely.

I tried this and this fixed the problem, many thanks for your help.
