### ISSUE TITLE
[BUG] x and y keywords no longer work

### ISSUE THREAD

**Issue by charlesbrodhead3** [JuliaPlots/Plots.jl#3389]
## Details
In contrast to the documentation: [https://docs.juliaplots.org/latest/input_data/#Inputs-are-arguments,-not-keywords](url)

`plot(1:10,rand(10))` works as expected.

`plot(x = 1:10, y = rand(10))` however, shows an empty plot (equivalent to plot() output).

If you could take a look it would be much appreciated.

### Backends
This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |     |  x
plotly       |     |     |  x
plotlyjs     |     |     |  x
pgfplotsx    |     |     |  x
inspectdr    |     |     |  x

### Versions

Plots.jl version: Plots v1.11.0
Backend  version (`]st -m`): GR v0.55.0
Output of `versioninfo()`: 
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32) >> Windows 10
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by daschw** [comment]
We could easily fix this by checking for `args` in `_plot!`. However, I think I'd probably probably prefer changing the docs here and specifically only supporting the the interface `plot(args...; kwargs...)` without additional kwargs for `x`, `y` and `z`. To be honest, I wasn't even aware we claimed to support this. What are your opinions here @isentropic @yha @mkborregaard ?

**Comment by charlesbrodhead3** [comment]
Removing mention of it from the documentation would be fine by me to not complicate the codebase.  
(I was running old code, which is how I noticed that it had changed).

Let me know.  I'm happy to raise a pull request with your desired changes.

**Comment by yha** [comment]
I tested it on `Plots` 1.0.0 now and it doesn't work there either. So I agree we can simply drop it from the docs.
