### ISSUE TITLE
[DOC] Error in the "Input Data" Section on Documentation (Wrong Example Code)

### ISSUE THREAD

**Issue by RoyiAvital** [JuliaPlots/Plots.jl#3401]
The current documentation on the [Input Data Section](http://docs.juliaplots.org/latest/input_data/) mentions:

![image](https://user-images.githubusercontent.com/7347975/113105794-aa55a580-920a-11eb-9726-9dae5f437290.png)

Namely, one could expect `plot(x = 1:10, y = rand(10))` to work.
Yet on Julia 1.6 and the latest version (To the least) it won't work (No error, just blank result):

![image](https://user-images.githubusercontent.com/7347975/113106001-e852c980-920a-11eb-9e2c-2bff2d58a140.png)

It is either not updated documentation or the option isn't implemented well.

**Comment by BeastyBlacksmith** [comment]
Thats changed
