### ISSUE TITLE
[BUG] bar plots have multiple legend entries

### ISSUE THREAD

**Issue by fph** [JuliaPlots/Plots.jl#3404]
## Details
When using `pgfplotsx`, `groupedbar` plots have multiple copies of the same legend entry:
```
using Plots
using StatsPlots
pgfplotsx()
groupedbar(rand(4,4))
```
![img](https://i.imgur.com/sKZ1jKi.gif)

16 legend entries are visible instead of 4 only with `gr`.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     | X  | 
pyplot       |     |     | X
plotly       |     |     | X
plotlyjs     |     |     | X
pgfplotsx    |  X  |     | 
inspectdr    |     |     | X

### Versions

Plots.jl version: 1.11.2
Backend  version (`]st -m`): 1.2.10
Output of `versioninfo()`:
```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = /home/sad/.julia
  JULIA_NUM_THREADS = 2
  JULIA_EDITOR = atom  -a
  JULIA_PKG_SERVER = pkg.juliahub.com
  JULIA_LOAD_PATH = /home/sad/.julia/environments/JuliaPro_v1.5.3-1:@:@v#.#:@stdlib
```

**Comment by fph** [comment]
#3125 seems related, but apparently that was fixed by updating, while this is not.

**Comment by pstaabp** [comment]
This is also on the `bar` function as well: 

```
using Plots, PGFPlotsX
pgfplotsx()
bar(1:10,rand(1:10,10))
```

I'm running Julia 1.6.0 with Plots v1.11.2 and PGFPlotsX v1.2.10

**Comment by fph** [comment]
I can reproduce what @pstaabp reported. It did not occur to me to try this simpler example.

**Comment by pstaabp** [comment]
Even though it appears that this was fixed in version 1.12.0, I'm still seeing the same results in the latest version (1.13.2) of Plots.jl . I reran the same code above and still see a label in the legend for each bar.

**Comment by pstaabp** [comment]
A typo on the version above, but this is still the case in version 1.14.0.  Can this be reopened? The code
```
using Plots, PGFPlotsX
pgfplotsx()
bar(1:10,rand(1:10,10))
```
produces the following plot:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/879338/118142056-04d04d00-b3d8-11eb-91dc-4cc658f97279.png">

**Comment by BeastyBlacksmith** [comment]
related: https://github.com/JuliaPlots/StatsPlots.jl/issues/446

**Comment by PToTheK** [comment]
Its also the same behaviour for the function `histogram`.
With `gr()`it works fine, but with `pgfplotsx()` one gets similar pictures as shared above.
