### ISSUE TITLE
[BUG] ticks won't work correctly with \n with pyplot backend

### ISSUE THREAD

**Issue by vancleve** [JuliaPlots/Plots.jl#3418]
## Details

With the `pyplot` backend, Plots.jl surrounds tick labels with `\mathregular` which breaks adding `\n` to tick labels. For example,

```
using Plots 
import PyPlot
pyplot()

x = 1:5; 

p = plot(x, x, xticks=(x, ["$i\ntext" for i in x]))
```
produces
![image](https://user-images.githubusercontent.com/1442334/113528042-70c7c600-958d-11eb-9aa5-d8c72eb852ea.png)

whereas I can easily plot the labels correctly directly using `PyPlot.jl`:
```
PyPlot.plot(x, x)
PyPlot.gca()."xaxis"."set_ticks"(1:5)
PyPlot.gca()."xaxis"."set_ticklabels"(["$i\ntext" for i in x])
```
produces
![image](https://user-images.githubusercontent.com/1442334/113528205-eb90e100-958d-11eb-9469-bb60650dbd7f.png)

Should `\mathregular` always be wrapping normal text???

(tagging @isentropic from here: https://github.com/JuliaPlots/Plots.jl/issues/2890#issuecomment-668956523)

### Versions

Plots.jl version: v1.11.2
PyPlot.jl: v2.9.0
Output of `versioninfo()`:
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)

**Comment by isentropic** [comment]
Perhaps we need an extra kwarg to avoid this surrounding, I added a new subplot extrakw for pyplot for this purpose:
```
x = 1
p = plot(x, x, xticks=(x, ["$i\ntext" for i in x]), rawticklabels=true, extra_kwargs=:subplot)
```
that bypasses the `\mathregular` padding. More about extra_kws here http://docs.juliaplots.org/latest/input_data/#extra_kwargs

**Comment by isentropic** [comment]
Currently, this change is on the master branch only. However, I think this has been a long-desired feature. Would you perhaps mind documenting this to http://docs.juliaplots.org/latest/backends/#[PyPlot](https://github.com/stevengj/PyPlot.jl)?
Basically, create a short section for extra_kwargs that we are tracking for the pyplot backend.

**Comment by vancleve** [comment]
> Would you perhaps mind documenting this to [http://docs.juliaplots.org/latest/backends/#[PyPlot](https://github.com/stevengj/PyPlot.jl)](http://docs.juliaplots.org/latest/backends/#%5BPyPlot%5D(https://github.com/stevengj/PyPlot.jl))? Basically, create a short section for extra_kwargs that we are tracking for the pyplot backend.

Yes, happy to do that.

**Comment by isentropic** [comment]
@vancleve checkout thePR

**Comment by vancleve** [comment]
> @vancleve checkout thePR

ah, looks great! should close this issue, yes!
