### ISSUE TITLE
[BUG] Colorbar doesn’t reflect ColorGradient scale as specified in cgrad(…, scale = ) -works on gr

### ISSUE THREAD

**Issue by casasgomezuribarri** [JuliaPlots/Plots.jl#3420]
## Details

I have built the following composite plot:

```julia
# Data
x = rand([1, 2, 3, 4, 5], 50)
y = rand(50)
z = rand(50)

# Vector with labels to show on hover
hovector = []
for i in 1:length(x)
    label = "$(x[i]), $(y[i]), $(z[i])"
    push!(hovector, label)
 end

# Frequency histograms and blank plot for top right corner
plotly()
x_hist = Plots.plot(x,
    st = :histogram,
    nb = 50,
    leg = false,
    yguide = "Frequency",
    xticks = false,
    guide_position = :left,
    color = RGB{Float64}(0.031,0.318,0.612))
y_hist = Plots.plot(y,
    st = :histogram,
    nb = 50,
    leg = false,
    color = RGB{Float64}(0.031,0.318,0.612),
    yticks = false,
    xguide = "Frequency",
    orientation = :h)
blank = Plots.plot(grid = false, showaxis = false)

# Main plot
bubblecolor = cgrad(:inferno, scale = :exp)
bubbles = Plots.plot(x, y, st = :scatter,     
    marker_z = z,
    ms = 10,
    hover = hovector,
    color = bubblecolor, 
    label = nothing,
    cb = false)

# Workaround for title (plot_title not currently implemented, see http://docs.juliaplots.org/latest/generated/attributes_plot/)
title = Plots.plot(ones(3), line = nothing, size = (600, 80),
    grid = false, showaxis = false, leg = false,
    annotations=(2, 1.5, "Main Title"))

# Merge plots
l = @layout [x_hist              blank
            bubbles{0.8w,0.8h}   y_hist]
plots = Plots.plot(x_hist, blank, bubbles, y_hist, 
        layout = l, link = :both,
        size = (700, 500))
superplot = Plots.plot(title, plots, layout = grid(2,1,heights=[0.1,0.9]))

# Add colorbar
Plots.plot!([0], [0], zcolor=[NaN], cbtitle="Intensity", leg = false,
        clims = extrema(z),
        color = bubblecolor,
        background_color_subplot=:transparent,
        markerstrokecolor=:transparent, framestyle=:none, 
        cb = :right,
        inset=bbox(0.1, 0, 0.05, 0.9, :center, :right), 
        subplot=6)
```
which gives me:

![image](https://user-images.githubusercontent.com/71462845/113583949-e49aba80-95ef-11eb-98d0-79417cbd74fe.png)

My question is related to the last block `# Add colorbar` (note the color gradient `bubblecolor` defined just under `# Main plot`). I am using an exponential scale for my color gradient to make lower Intensity values stand out more clearly -darkly-, and although this is reflected in the color of the bubbles themselves, the colorbar still shows the default linear scale of the `:inferno` color gradient. This obviously affects the readability of the main scatter.

If I change the line where `bubblecolor` is defined to
```julia
bubblecolor = cgrad(:inferno, rev = true, scale = :exp)
```
then I get:

![image](https://user-images.githubusercontent.com/71462845/113584238-4529f780-95f0-11eb-9aed-e5299b68b45a.png)

So, the `color` attribute in the last block is sensitive to changes in `rev` within `cgrad`, but not `scale`. Is this an expected limitation, or am I doing something wrong?

PS: Any idea why the `cbtitle` “Intensity” doesn’t show up? This is less of an issue but would be great to be able to include it.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pyplot       |    |     | error
plotly       |   x  |     |
plotlyjs     |  x   |     |
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version:
Backend  version (`]st -m`):
Output of `versioninfo()`:

**Comment by hervasa2** [comment]
I have also found this same bug. The colorbar in pyplot() does not respect the cgrad scale. This however works in gr().
This used to work in v1.10.2. I noticed the bug once I upgraded to v1.16.4.
An example follows:
`pyplot()`
`A = rand(0:10,10,10)`
`grad = cgrad(:inferno, scale =:log)`
`heatmap(A, c = grad)`
<img width="400" alt="Screen Shot 2021-06-09 at 8 18 51 PM" src="https://user-images.githubusercontent.com/41748838/121407807-000fa200-c960-11eb-9468-739e5732da6b.png">
`grad2 = cgrad(:inferno, scale =:exp)`
`heatmap(A, c = grad2)`
<img width="400" alt="Screen Shot 2021-06-09 at 8 19 09 PM" src="https://user-images.githubusercontent.com/41748838/121407821-0271fc00-c960-11eb-83b7-02b8d632ce82.png">

And now in **gr()**
`gr()`
`heatmap(A, c = grad)`
<img width="400" alt="Screen Shot 2021-06-09 at 8 22 14 PM" src="https://user-images.githubusercontent.com/41748838/121408369-a360b700-c960-11eb-9c59-e1717e9021c3.png">
`heatmap(A, c = grad2)`
<img width="400" alt="Screen Shot 2021-06-09 at 8 22 22 PM" src="https://user-images.githubusercontent.com/41748838/121408398-a8be0180-c960-11eb-9782-95b0526063e5.png">

**Comment by fhagemann** [comment]
This bug was introduced [from v1.10.5 to v1.10.6](https://github.com/JuliaPlots/Plots.jl/compare/v1.10.5...v1.10.6),  so I guess that its source is either commit https://github.com/JuliaPlots/Plots.jl/commit/d59f6c96d535e809ce83a99738545a898a68c250 or  commit https://github.com/JuliaPlots/Plots.jl/commit/100da5ccae266c258174cd24a254650b49d969fd.

I hope that this is useful for someone. I'm lacking the experience to judge which line might be the source of the problem...

**Comment by schustermartin** [comment]
I encountered this as well!

**Comment by isentropic** [comment]
I'm aware of the logscale problem, though I need help.
https://github.com/JuliaPlots/Plots.jl/pull/3432

**Comment by isentropic** [comment]
let's focus on this in https://github.com/JuliaPlots/Plots.jl/issues/3174
