### ISSUE TITLE
[BUG] bar plot with String x and series_annotation fails

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#3433]
## Details
```
bar(["x","y"], [3,4], series_annotations=["x","y"])
```
fails. The error is different on each backend.
It works with `plot`, and with numerical x axis.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |  x   |     |
plotly       |  x   |     |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.11.2
Backend  version (`]st -m`): GR 0.57.1
Output of `versioninfo()`:
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by gustaphe** [comment]
In general, I think `Plots.process_annotation` should apply type recipes for `xs` and `ys`. Currently it's hard coded to convert `TimeType` objects, but nothing else.
