### ISSUE TITLE
[BUG] bar() and box() plots not working

### ISSUE THREAD

**Issue by sindresops** [JuliaPlots/Plots.jl#3434]
## Details
After updating from Julia 1.5, StatsPlots 0.13.x and PlotlyJS 0.13.x, I can no longer get bar() and box() plots to work with the Plotly backends.
This works
`	using Plots, StatsPlots;
	gr();
	bar([(1,4),(2,5),(3,6)])`

This does not work
`	using Plots, StatsPlots;
	plolyjs();
	bar([(1,4),(2,5),(3,6)])`

and returns
`Failed to show value:

UndefRefError: access to undefined reference

getindex@array.jl:801[inlined]
iterate@array.jl:777[inlined]
show_json(::JSON.Writer.PrettyContext{IOBuffer}, ::JSON.Serializations.StandardSerialization, ::Vector{Any})@Writer.jl:293
#show_json#3@Writer.jl:325[inlined]
print(::IOBuffer, ::Vector{Any}, ::Int64)@Writer.jl:347
var"#sprint#385"(::Nothing, ::Int64, ::typeof(sprint), ::Function, ::Vector{Any}, ::Vararg{Any, N} where N)@io.jl:105
sprint@io.jl:101[inlined]
json@Writer.jl:366[inlined]
plotly_series_json@plotly.jl:903[inlined]
plotly_html_body(::Plots.Plot{Plots.PlotlyJSBackend}, ::Nothing)@plotly.jl:951
plotly_html_body@plotly.jl:926[inlined]
html_body@plotlyjs.jl:35[inlined]
var"#standalone_html#360"(::String, ::typeof(Plots.standalone_html), ::Plots.Plot{Plots.PlotlyJSBackend})@web.jl:7
standalone_html(::Plots.Plot{Plots.PlotlyJSBackend})@web.jl:7
_show@plotlyjs.jl:37[inlined]
show(::IOContext{IOBuffer}, ::MIME{Symbol("text/html")}, ::Plots.Plot{Plots.PlotlyJSBackend})@output.jl:215
show_richest(::IOContext{IOBuffer}, ::Any)@PlutoRunner.jl:629
var"#sprint_withreturned#28"(::IOContext{Base.DevNull}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::Plots.Plot{Plots.PlotlyJSBackend})@PlutoRunner.jl:568
format_output_default(::Any, ::Any)@PlutoRunner.jl:492
#format_output#17@PlutoRunner.jl:509[inlined]
formatted_result_of(::Base.UUID, ::Bool, ::Nothing)@PlutoRunner.jl:425
top-level scope@none:1`
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |    x |
pyplot       |     |     |
plotly       |   x  |     |
plotlyjs     |   x  |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: v1.11.2
Plotlyjs.jl version: 0.14.1
StatsPlots.jl version: v0.14.19

Output of `versioninfo()`:
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, icelake-client

**Comment by metab0t** [comment]
42b3c5625f0de2c1012d0478ca007e83a51284a9
It seems that this commit causes `plotly_series(p)` returns arrays containing `undef` in the end, because `attr_index` of all `segments` are 1
@yha would you love to look into this issue?
