### ISSUE TITLE
[BUG] Labels out of order

### ISSUE THREAD

**Issue by baggepinnen** [JuliaPlots/Plots.jl#3440]
## Details
The following code produces labels on the wrong places, I expected `Series 1` to be placed on the second plot, not the last
```
plot(layout=(7,1))
plot!(
    reshape(1:60, 10,6),
    sp = (2:7),
    title = "",
    ylabel = ["Series $i" for i in (1:6)'],
)
```
![newplot](https://user-images.githubusercontent.com/3797491/114995502-2d7b2a80-9e9e-11eb-9262-abff905aec4e.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotly       |   x  |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

(@v1.6) pkg> st Plots
      Status `~/.julia/environments/v1.6/Project.toml`
  [91a5bcdd] Plots v1.11.2

(@v1.6) pkg> st Plotly
      Status `~/.julia/environments/v1.6/Project.toml`
  [58dd65bb] Plotly v0.3.0

julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = code
  JULIA_PKG_PRECOMPILE_AUTO = 1

**Comment by gustaphe** [comment]
Can reproduce in other backends too ( `GR`, `pyplot` and `inspectdr`, others not tried). `title` and `xlabel` show the same issue. `label` does not. The difference is probably between series attributes and subplot attributes.
