### ISSUE TITLE
Plot labels only accepts certain types

### ISSUE THREAD

**Issue by JackKenney** [JuliaPlots/Plots.jl#3442]
## Details

These two plots should have the same labels, but don't:

This one has the same label `["0", "1"]` for both lines:
```
julia> plot(rand(10,2), labels=[0,1])
```
![Screenshot from 2021-04-17 22-34-09](https://user-images.githubusercontent.com/8908922/115132321-269f0580-9fcd-11eb-9abc-0522bc64aa92.png)

These both have the labels 0 and 1 for the two lines that are plotted.
```
julia> plot(rand(10,2), labels=[0,1]')
julia> plot(rand(10,2), labels=[0 1])
```
![Screenshot from 2021-04-17 22-34-24](https://user-images.githubusercontent.com/8908922/115132333-30c10400-9fcd-11eb-9861-de8e42f257d4.png)

The second is clearly expected behavior so I'm submitting the first as a bug. From what I can tell, it's a Vector vs Matrix type difference. Seems like Vectors aren't supported?

Could be a good Docs feature request if it's difficult to implement for some reason. It was very hard to find the right method.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version:  v1.11.1
Backend  version (`]st -m`): GR v0.55.0

Output of `versioninfo()`:
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 3960X 24-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
Environment:
  JULIA_NUM_THREADS = 40

**Comment by gustaphe** [comment]
This is not a bug, [columns are series](http://docs.juliaplots.org/latest/input_data/#columns-are-series).

**Comment by isentropic** [comment]
Thanks for explaining this @gustaphe
