### ISSUE TITLE
[BUG] LaTeX's lower indices in the legend are not shown correctly (with PGFPlotsX)

### ISSUE THREAD

**Issue by zhiyuanzhai** [JuliaPlots/Plots.jl#3450]
## Details

The lower indices on the axes are shown as normal, but the ones in the legend are shown as some kind of raw code instead of lower indices.

For example: 
![example](https://user-images.githubusercontent.com/37478391/115835310-b4a14300-a448-11eb-85db-b4aef942a9ab.png)

```Julia
using Plots; pgfplotsx()
plot(1:20, rand(20,2), ,label=[raw"$y_1$" raw"$y_2$"], xlabel=raw"$x$", ylabel=raw"$y_i$")
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | x
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |  x  |     |
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.12.0
Backend  version (`]st -m`): `PGFPlotsX v1.2.10`
Output of `versioninfo()`:
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 6
  JULIA_PKG_SERVER = https://pkg.julialang.org
```

**Comment by BeastyBlacksmith** [comment]
Please use  `LaTeXStrings` to prevent sanitazition

**Comment by zhiyuanzhai** [comment]
OK maybe that's where the problem is...
