### ISSUE TITLE
[BUG] empty scatter plot produces empty legend entry (GR)

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#3452]
## Details
```
Plots.scatter([],[])
```
On GR, the legend includes an entry for the series, with no marker showing.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |  x  |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: master
Backend  version (`]st -m`): GR 0.55.0
Output of `versioninfo()`:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by t-bltg** [comment]
This appears to be fixed (marker showing).
