### ISSUE TITLE
[BUG] pyplot() backend with usetex="true" not working

### ISSUE THREAD

**Issue by zejian-li** [JuliaPlots/Plots.jl#3460]
## Details
Minimal non-working example:

`using Plots; pyplot()`
`PyPlot.rc("text",usetex="true")`    
`plot(1:10)`

This produces the error 
PyError ($(Expr(:escape, :(ccall(#= C:\Users\zejia\.julia\packages\PyCall\BD546\src\pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'RuntimeError'>
RuntimeError("latex was not able to process the following string:\nb'$\\\\\\\\mathregular{2}$'\n\nHere is the full report generated by latex:\nThis is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/W32TeX) (preloaded format=latex)\r\n restricted \\write18 enabled.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | x
pyplot       |   x  |     |
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: v1.13.2
Backend  version (`]st -m`):  PyPlot v2.9.0
Output of `versioninfo()`: 
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by isentropic** [comment]
Use this
```
using Plots; pyplot()
Plots.pyrcparams["text.usetex"] = true
plot(1:10, rawticklabels=true, extra_kwargs=:subplot)
```
Would you please help documenting this extra_kwarg for pyplot? This was already mentioned in https://github.com/JuliaPlots/Plots.jl/issues/3418 but never documented

**Comment by isentropic** [comment]
Please comment in the linked issue for further discussion
