### ISSUE TITLE
[BUG] GKS: Rectangle definition is invalid in routine SET_VIEWPORT

### ISSUE THREAD

**Issue by ptoche** [JuliaPlots/Plots.jl#3461]
I have just installed the latest Julia, after removing my old ``.julia`` and with new versions of ``Plots`` and ``GR`` I'm getting 

    julia> plot(x -> x, 0, 1)
    GKS: Rectangle definition is invalid in routine SET_VIEWPORT

    julia> Pkg.status("Plots")
          Status `~/Julia/workspace/Project.toml`
      [91a5bcdd] Plots v1.13.2 `https://github.com/JuliaPlots/Plots.jl.git#master`

    julia> Pkg.status("GR")
          Status `~/Julia/workspace/Project.toml`
      [28b8d3ca] GR v0.57.4
  
    julia> versioninfo()
    Julia Version 1.6.1
    Commit 6aaedecc44 (2021-04-23 05:59 UTC)
    Platform Info:
      OS: macOS (x86_64-apple-darwin18.7.0)
      CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-11.0.1 (ORCJIT, haswell)

**MacOS BigSur 11.2.3**

I have done ``Pkg.update()``  and ``Pkg.resolve()``. Anything else I can try? Thanks!

**Comment by ptoche** [comment]
In an environment with nothing but ``Pkg.add("Plots")`` there is no problem. So it's some sort of package conflict. Any suggestions on how to find out the source of the problem? Thanks.

**Comment by t-bltg** [comment]
```julia
(@v1.6) pkg> build GR
```
