### ISSUE TITLE
[BUG] suppress window on `savefig` (GR, macOS)

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/Plots.jl#3464]
I thought I had come across this issue before, but I couldn't find it by searching. If it does exist, my apologies, and I hope this gives more keywords for a search to find.

## Details
```julia
julia> import Plots

julia> plt = Plots.plot();

julia> Plots.savefig(plt, mktemp()[1] * ".png")
```

causes a new window to momentarily appear

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |   x  |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: `  [91a5bcdd] Plots v1.13.2`
Backend  version (`]st -m`): `  [28b8d3ca] GR v0.57.4`
Output of `versioninfo()`:
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = vscode
```

**Comment by t-bltg** [comment]
Use `ENV["GKSwstype"] = "nul"`.

See https://discourse.julialang.org/t/deactivate-plot-display-to-avoid-need-for-x-server/19359
