### ISSUE TITLE
[BUG] precompiling Plots.jl crashes in Julia 1.6.1 on Windows 10

### ISSUE THREAD

**Issue by YKamer** [JuliaPlots/Plots.jl#3467]
Hello I am a total noob in Julia so I don't know how to fill in the bug report table properly. 
Here is the gist of it:  after issuing the "using Plots" command on version 1.6.1 the compilation crashes.  I switched to version 1.4.2 and it works. Attached is a link containing the the bug report.
https://discourse.julialang.org/t/just-downloaded-julia-want-to-add-plots-package-all-i-get-is-crashes/60426/7?u=zamazalotta

**Comment by fgasdia** [comment]
After restarting my computer I deleted the `.julia` folder again and this time I was able to add and precompile Plots successfully.

**Comment by YangYuebao** [comment]
> After restarting my computer I deleted the `.julia` folder again and this time I was able to add and precompile Plots successfully.

Mine also crashed on 1.7.0-beta2 version. I deleted .julia like you, and then Plots could be precompiled, but I need to download all other packages again. 

Some thing wrong happened to my internet when I add Plots for the first time, and then when I tried to precompile, Julia mentioned me to check for duplicate calls to include.
