### ISSUE TITLE
[BUG] LaTeX String inappropriately escaped in legend entry

### ISSUE THREAD

**Issue by avonmoll** [JuliaPlots/Plots.jl#3486]
## Details

The `label` string sometimes include inappropriate escape characters. Interestingly, the `xguide` behavior is correct/as expected. For example, the following line

```julia
plot(rand(10), xguide=latexstring("x_{i,j}")*" $(rand())", label=latexstring("A_{i,j}")*" $(rand())")
```
Produces

![image](https://user-images.githubusercontent.com/4260850/117824291-5d6ae300-b23c-11eb-8d34-6ea076ec70b5.png)

But, when the `latexstring` is not concatenated with another string, the label appears properly:

```julia
plot(rand(10), xguide=latexstring("x_{i,j}"), label=latexstring("A_{i,j}"))
```

![image](https://user-images.githubusercontent.com/4260850/117824628-a6bb3280-b23c-11eb-8f42-e8bd2bf63acb.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | x
pyplot       |     | x    |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |  x   |     |
inspectdr    |     |     |x

### Versions

Plots.jl version:1.14.0
Backend  version (`]st -m`): PGFPlotsX 1.2.10
Output of `versioninfo()`:
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_GR_PROVIDER = GR
```

**Comment by BeastyBlacksmith** [comment]
It is the same as https://github.com/JuliaPlots/Plots.jl/issues/3450. Multiplying a `LaTeXString` with a `String` returns a `String` and thus the sanitation kicks in.
That it works this way for the x-Axis is a bug.
You can get what you want (I think) with
```julia
plot(rand(10), xguide=latexstring("x_{i,j}")*" $(rand())", label=latexstring(latexstring("A_{i,j}")*" $(rand())"))
```
