### ISSUE TITLE
[BUG] StatsPlots groupedbar with negative values

### ISSUE THREAD

**Issue by rmarto** [JuliaPlots/Plots.jl#3499]
Groupedbar does not stack bars when values are negative. Could you please help solve this issue?
Here's a simple example:
`
ctg = repeat(["Category 1", "Category 2"], inner = 5)
nam = repeat("G" .* string.(1:5), outer = 2)
groupedbar(nam, -rand(5, 2), group = ctg, bar_position = :stack) 
`

**Comment by lobingera** [comment]
Cannot reproduce

![a](https://user-images.githubusercontent.com/5199059/118689977-e28b6480-b807-11eb-9eea-79fbca12e9e8.png)

**Comment by rmarto** [comment]
Thanks. It doesn't work on my end. Here's what it looks like (tried with gr, pyplot, and pgfplotsx backends). Category 1 and Category 2 are summed, but both look orange. Any suggestion on how to overcome this?
Many thanks.

![fig](https://user-images.githubusercontent.com/42483896/119402054-5d41fd00-bcaa-11eb-8f3f-e90a5553ed76.png)
