### ISSUE TITLE
[BUG] xscale=:ln not working as intended

### ISSUE THREAD

**Issue by gertvv** [JuliaPlots/Plots.jl#3502]
## Details

![image](https://user-images.githubusercontent.com/80785/118374126-b9c25f80-b5ba-11eb-8e49-63a742bdba25.png)

I don't think xscale=:ln is working as expected, see the above annotated screenshot. The first plot is use a linear scale, the second I have manually logged the points, the third is using xscale=:ln, and the fourth xscale=:log.

I would have expected the tickmarks on the :ln plot to be evenly spaced, as they are on the :log plot.

I brought this up for discussion on Gitter a few days ago, but it seems completely dead. If so, you might want to remove the link from the documentation.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x   |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: Plots v1.13.2
Backend  version (`]st -m`): GR v0.57.4
Output of `versioninfo()`:
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)

**Comment by t-bltg** [comment]
@gertvv , `:ln` is not supported by `gr` (see https://docs.juliaplots.org/latest/generated/supported/#Scales), do you get this warning ?

```julia
┌ Warning: scale ln is unsupported with Plots.GRBackend().  Choose from: [:identity, :log10]
└ @ Plots [...]/src/args.jl:1260
```

**Comment by gertvv** [comment]
I didn't think I did, but... I did this in a Pluto notebook, and I've just re-run it, and turns out the warning went to the Julia console where Pluto was started rather than appearing in the notebook. I wonder if that's by design (I would certainly prefer if the warning had appeared in the notebook). In any case looks like this is not an issue with Plots.jl - thanks!
