### ISSUE TITLE
[BUG] InexactError in pyplot-backed heatmap with a zero matrix.

### ISSUE THREAD

**Issue by remy-luisant** [JuliaPlots/Plots.jl#3509]
Two similar issues, but neither seems to be this exact one. (#3426 and #3331)

## Details
`using Plots`
`pyplot()`
`heatmap(zeros(20, 20))`

>Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
>ERROR: InexactError: check_top_bit(UInt64, -9223372036854775481)
>Stacktrace:
>  [1] writefixed (repeats 5 times)
>    @ ./ryu/Ryu.jl:76 [inlined]
>  [2] format_fixed
>    @ ~/.julia/packages/Showoff/wogB3/src/ryu.jl:30 [inlined]

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | x
pyplot       |  x   |     |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: Plots v1.11.2
Backend  version (`]st -m`): PyPlot v2.9.0
Output of `versioninfo()`:
Julia Version 1.6.1
Commit 6aaedecc44* (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.1.0 (ORCJIT, skylake)

**Comment by lobingera** [comment]
Cannot reproduce in Plots v1.15

**Comment by remy-luisant** [comment]
I can confirm, it got fixed by then. I didn't realize how old of a setup I'm running. Apologies for the noise.
