### ISSUE TITLE
[BUG] `Plots` doesn't handle vectors of `Shape`s

### ISSUE THREAD

**Issue by B-LIE** [JuliaPlots/Plots.jl#3516]
## Details
The following code works with `Plots` vs. 1.0.0, but not in v. 1.14.0 and later:
```julia
import Plots as plt
ang = range(0, 2π, length = 60)
ellipse(x, y, w, h) = plt.Shape(w*sin.(ang).+x, h*cos.(ang).+y)    # Returns a Shape object
myshapes = [ellipse(x,rand(),rand(),rand()) for x = 1:4]
plt.plot(myshapes)
```
The problem appears to be related to "unpacking" a *vector* of shapes... the following *does* work in the current version of `Plots`:

```julia
plt.plot()
for s in myshapes
    plt.plot!(s)
end
plt.plot!()
```

### Backends
Tested both with `GR` and `PyPlot` on Julia v. 1.6.0 and `Plots` v. 1.15.1

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |   x  |     |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.15.1
Backend  version (`]st -m`):  `PyPlot` v. 2.9.0, `GR` v. 0.57.4
Output of `versioninfo()`:
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-9900T CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by BeastyBlacksmith** [comment]
`git bisect` says, that a359f21325a18d448b3b0731d74ee07b21c95ea5 is the commit that broke this
