### ISSUE TITLE
The legend of histogram is duplicated

### ISSUE THREAD

**Issue by fanyuan-lab** [JuliaPlots/Plots.jl#3521]
I am trying to plot a histogram with backends: pgfplotsx(), but I find the label for histogram is duplicated according to the number of bins. It is really weird. For example, the example: histogram(randn(1000), bins = :scott, weights = repeat(1:5, outer = 200)) in the document. You will see multiple y1 in the legend.

**Comment by fanyuan-lab** [comment]
> which version of Plots do you use?

Plots v1.15.0 and macOS Big Sur 11.3.1. If possible, you could try this example. Thanks a lot.

**Comment by fanyuan-lab** [comment]
PGFPlotsX v1.2.10

**Comment by BeastyBlacksmith** [comment]
That should be fixed on 1.15.1

**Comment by fanyuan-lab** [comment]
> That should be fixed on 1.15.1

Many thanks.
