### ISSUE TITLE
[FR] Remove lines at colorbar related to contours

### ISSUE THREAD

**Issue by ccmejia** [JuliaPlots/Plots.jl#3522]
Dear all,
I was wondering if could be possible to remove or hide the lines (at the colorbar) related to contours.

Here an example code to:

```julia
using Plots

x = y = range(-5, 5, length = 256)
x = x' .* ones(length(x)); y = ones(length(y))' .* y;
z = exp.(-x.^2-y.^2);
p1 = heatmap(z, colorbar_title = L"$ |U(x, y)| $"); 
contour!(z, c=:grays, levels = 0.0:0.05:0.5) 
```

Thanks in advanced,
Crist.

**Comment by t-bltg** [comment]
You can use `contour!(z, c=:grays, levels=0.:.05:.5, colorbar_entry=false)`, it'd be nice if it were documented somewhere.

@SimonDanisch, where can this go in the docs ?

**Comment by BeastyBlacksmith** [comment]
I'd say this [is already in the docs](https://docs.juliaplots.org/latest/generated/attributes_series/)

**Comment by t-bltg** [comment]
> I'd say this [is already in the docs](https://docs.juliaplots.org/latest/generated/attributes_series/)

I need new glasses :laughing:

**Comment by BeastyBlacksmith** [comment]
Probably another case of https://github.com/JuliaPlots/Plots.jl/issues/2337

**Comment by ccmejia** [comment]
> You can use `contour!(z, c=:grays, levels=0.:.05:.5, colorbar_entry=false)`, it'd be nice if it was documented somewhere.
> 
> @BeastyBlacksmith, where can this go in the docs ?

It works! 
Thank you.
