### ISSUE TITLE
[BUG] skipmissing not supported

### ISSUE THREAD

**Issue by knuesel** [JuliaPlots/Plots.jl#3528]
## Details

(This is related to https://github.com/JuliaPlots/Plots.jl/issues/1706)

For example `scatter(skipmissing([1.0, 2.0, missing, 1.0]))` fails with `Cannot convert Base.SkipMissing{Vector{Union{Missing, Float64}}} to series data for plotting`.

Generally `skipmissing` is not required but it seems odd to see this fail.

Also I stumbled on this while trying to make a histogram, e.g. `histogram([1.0, 2.0, missing, 1.0])` and without `skipmissing` it fails with `no method matching AbstractFloat(::Type{Union{Missing, Float64}})`.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |     | x
plotly       |  x  |     |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.15.2
Backend  version (`]st -m`): GR 0.52.0
Output of `versioninfo()`:

```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by BeastyBlacksmith** [comment]
I'd say this is missing functionality rather than a bug, but would be nice to have.
What is working is `scatter(collect(skipmissing([1.0, 2.0, missing, 1.0])))

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/4482.
