### ISSUE TITLE
[BUG] Error when plotting small (<1e-15) but non-zero data

### ISSUE THREAD

**Issue by olof3** [JuliaPlots/Plots.jl#3549]
## Details

mwe
```julia
v = [1e-16,  1.1e-16]
plot(v)
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: InexactError: check_top_bit(UInt64, -9223372036854775481)
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     |x
plotly       |  x   |     |
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: v1.12.0
Backend  version (`]st -m <backend(s)>`): GR v0.57.4, PlotlyBase v0.4.3
Output of `versioninfo()`:
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by BeastyBlacksmith** [comment]
That works for me on Plots 1.16.2

**Comment by olof3** [comment]
Works for me too if upgrading to Plots v1.15.2.
