### ISSUE TITLE
"Images with custom axes" example creates wrong axis when using the pyplot backend

### ISSUE THREAD

**Issue by wg030** [JuliaPlots/Plots.jl#3580]
I was trying to reproduce the "Images with custom axes" example from the official documentation, when I figured that it creates some strange behaviour using the pyplot backend:
So, just taking the original code yields the same result as give in the documentation. However using the following slightly modified code for use with the pyplot() backend does not create the right axis:

```julia
using Plots
using TestImages
pyplot()
img = testimage("lighthouse");
plot([-π, π], [-1, 1], reverse(img, dims = 1), yflip = false, aspect_ratio = :none)
plot!(sin, -π, π, lw = 3, color = :red)
```

The result will be a plot which has as a x-axis  with the intervall [-2π, 2π] and a y-axis with the intervall [-2,2]. It's completley unclear to me why the pyplot backend doubles the values given in the command.

Altough it is extremley easy to quickfix this problem with the command
```julia
Plots.plot([-π/2, π/2], [-1/2, 1/2], reverse(img, dims = 1), yflip = false, aspect_ratio = 2)
```
I don't think that this can be considered a good solution.

**Comment by t-bltg** [comment]
This needs to be fixed (inconsistency):

https://docs.juliaplots.org/dev/gallery/gr/generated/gr-ref051/#gr_demo_51
https://docs.juliaplots.org/dev/gallery/pyplot/generated/pyplot-ref051/#pyplot_demo_51

**Comment by t-bltg** [comment]
This will be fixed by https://github.com/JuliaPlots/Plots.jl/pull/4542.
