### ISSUE TITLE
[BUG] create animation fails

### ISSUE THREAD

**Issue by francispoulin** [JuliaPlots/Plots.jl#3583]
## Details

When I try and create any animation, like the one on the following site, I get an error.

```
Stacktrace:
  [1] pipeline_error
    @ ./process.jl:525 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:440
  [3] run
    @ ./process.jl:438 [inlined]
  [4] (::FFMPEG.var"#4#6"{Cmd})(command_path::String)
    @ FFMPEG ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:112
  [5] (::JLLWrappers.var"#2#3"{FFMPEG.var"#4#6"{Cmd}, String})()
    @ JLLWrappers ~/.julia/packages/JLLWrappers/bkwIo/src/runtime.jl:49
  [6] withenv(::JLLWrappers.var"#2#3"{FFMPEG.var"#4#6"{Cmd}, String}, ::Pair{String, String}, ::Vararg{Pair{String, String}, N} where N)
    @ Base ./env.jl:161
  [7] withenv_executable_wrapper(f::Function, executable_path::String, PATH::String, LIBPATH::String, adjust_PATH::Bool, adjust_LIBPATH::Bool)
    @ JLLWrappers ~/.julia/packages/JLLWrappers/bkwIo/src/runtime.jl:48
  [8] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [9] invokelatest
    @ ./essentials.jl:706 [inlined]
 [10] #ffmpeg#7
    @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/executable_generators.jl:7 [inlined]
 [11] ffmpeg
    @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/executable_generators.jl:7 [inlined]
 [12] #exe#2
    @ ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:111 [inlined]
 [13] ffmpeg_exe
    @ ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:123 [inlined]
 [14] buildanimation(anim::Animation, fn::String, is_animated_gif::Bool; fps::Int64, loop::Int64, variable_palette::Bool, verbose::Bool, show_msg::Bool)
    @ Plots ~/.julia/packages/Plots/FKcum/src/animation.jl:96
 [15] #gif#238
    @ ~/.julia/packages/Plots/FKcum/src/animation.jl:64 [inlined]
 [16] top-level scope
    @ REPL[20]:1
```
https://docs.juliaplots.org/latest/animations/

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     |  x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version: v1.16.5
Backend  version (`]st -m <backend(s)>`): GR v0.57.5
Output of `versioninfo()`: 

```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)
Environment:
  EBVERSIONJULIA = 1.6.0
  JULIA_DEPOT_PATH = :
  EBROOTJULIA = /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0
  EBDEVELJULIA = /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0/easybuild/avx2-Core-julia-1.6.0-easybuild-devel
  JULIA_LOAD_PATH = :
```

**Comment by glwagner** [comment]
Can you post the minimal example that produces this error?

**Comment by francispoulin** [comment]
The example that is found at the following link has exactly the same problem, and is completely Oceananigans independent.

https://docs.juliaplots.org/latest/animations/

I'm going to talk to the people who maintain the serve and see if they can help tweek things so that they work.

**Comment by glwagner** [comment]
Ok, then this?

```julia
using Plots

@userplot CirclePlot
@recipe function f(cp::CirclePlot)
    x, y, i = cp.args
    n = length(x)
    inds = circshift(1:n, 1 - i)
    linewidth --> range(0, 10, length = n)
    seriesalpha --> range(0, 1, length = n)
    aspect_ratio --> 1
    label --> false
    x[inds], y[inds]
end

n = 150
t = range(0, 2π, length = n)
x = sin.(t)
y = cos.(t)

anim = @animate for i ∈ 1:n
    circleplot(x, y, i)
end
gif(anim, "anim_fps15.gif", fps = 15)
```

**Comment by francispoulin** [comment]
Yes, that is exactly what I tried.  And when I had the `ENV` command that you suggested, I get the following error.

```
julia> gif(anim, "anim_fps15.gif", fps = 15)
/home/fpoulin/.julia/artifacts/7f40eeb66d90d3026ae5fb68761c263b57adb840/bin/ffmpeg: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0/bin/../lib/julia/libstdc++.so.6)
ERROR: failed process: Process(`/home/fpoulin/.julia/artifacts/7f40eeb66d90d3026ae5fb68761c263b57adb840/bin/ffmpeg -v 16 -i /tmp/jl_x0J28n/%06d.png -vf palettegen=stats_mode=diff -y /tmp/jl_x0J28n/palette.bmp`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:525 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:440
  [3] run
    @ ./process.jl:438 [inlined]
  [4] (::FFMPEG.var"#4#6"{Cmd})(command_path::String)
    @ FFMPEG ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:112
  [5] (::JLLWrappers.var"#2#3"{FFMPEG.var"#4#6"{Cmd}, String})()
    @ JLLWrappers ~/.julia/packages/JLLWrappers/bkwIo/src/runtime.jl:49
  [6] withenv(::JLLWrappers.var"#2#3"{FFMPEG.var"#4#6"{Cmd}, String}, ::Pair{String, String}, ::Vararg{Pair{String, String}, N} where N)
    @ Base ./env.jl:161
  [7] withenv_executable_wrapper(f::Function, executable_path::String, PATH::String, LIBPATH::String, adjust_PATH::Bool, adjust_LIBPATH::Bool)
    @ JLLWrappers ~/.julia/packages/JLLWrappers/bkwIo/src/runtime.jl:48
  [8] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [9] invokelatest
    @ ./essentials.jl:706 [inlined]
 [10] #ffmpeg#7
    @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/executable_generators.jl:7 [inlined]
 [11] ffmpeg
    @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/executable_generators.jl:7 [inlined]
 [12] #exe#2
    @ ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:111 [inlined]
 [13] ffmpeg_exe
    @ ~/.julia/packages/FFMPEG/OUpap/src/FFMPEG.jl:123 [inlined]
 [14] buildanimation(anim::Animation, fn::String, is_animated_gif::Bool; fps::Int64, loop::Int64, variable_palette::Bool, verbose::Bool, show_msg::Bool)
    @ Plots ~/.julia/packages/Plots/FKcum/src/animation.jl:96
 [15] #gif#238
    @ ~/.julia/packages/Plots/FKcum/src/animation.jl:64 [inlined]
 [16] top-level scope
    @ REPL[10]:1
```

**Comment by BeastyBlacksmith** [comment]
what happens is that ffmpeg looks for glibc 2.18, but can't find it. Are you on a musl based machine?

**Comment by francispoulin** [comment]
Thanks @BeastyBlacksmith for the information.  I don't know what a musl based machine is so I can't say.  But this is a Compute Canada server that runs ubuntu, but not sure how to describe it in detail.  Sorry.

**Comment by BeastyBlacksmith** [comment]
What might help is to run `Pkg.instantiate()` after you logged in to the server, so you get the correct artifacts for that machine.

**Comment by francispoulin** [comment]
Thanks. I did `instantiate` and unforotunately that didn't seem to help at all.  When I checked the status of the packages nothing seemed to have a problem before or after.  

I did check that ffmpeg is installed on the system but I don't know if julia is able to use it without a problem.  Is there a simple test for ffmpeg in julia that I could try, which might help to isoalte the problem a little more?

**Comment by BeastyBlacksmith** [comment]
a minimal test would be ``run(`ffmpeg --version`)``

**Comment by BeastyBlacksmith** [comment]
That said, Plots.jl shouldn't use the systems ffmpeg, but the artifact provided by `FFMPEG.jl`.
I think the problem is, that you install that on a machine, that has glibc, then log onto the server, which either doesn't have glibc or an incompatible version and thus get the error.
@giordano is that possible?

**Comment by francispoulin** [comment]
Very nice @BeastyBlacksmith , thanks!

Below is the result.  Good news is that it seems to find some libraries.  Maybe more good news is that this yields an error.  Incidently, when I try the same command outside of julia I get the same thing but without the error.

Any idea what I could try next?
```
julia> run(`ffmpeg --version`)
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.3.0 (Gentoo 9.3.0 p2)
  configuration: --prefix=/cvmfs/soft.computecanada.ca/gentoo/2020/usr --libdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64 --shlibdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64 --docdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/share/doc/ffmpeg-4.2.2/html --mandir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/share/man --enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ --ar=x86_64-pc-linux-gnu-ar --optflags='-O2 -pipe -march=nocona -mtune=generic -O2 -ftree-vectorize -fno-math-errno -pipe' --disable-static --enable-avfilter --enable-avresample --disable-stripping --disable-optimizations --disable-libcelt --disable-indev=v4l2 --disable-outdev=v4l2 --disable-indev=oss --disable-indev=jack --disable-outdev=oss --enable-bzlib --disable-runtime-cpudetect --disable-debug --disable-gcrypt --disable-gnutls --disable-gmp --enable-gpl --disable-hardcoded-tables --enable-iconv --disable-libtls --disable-libxml2 --enable-lzma --enable-network --disable-opencl --disable-openssl --enable-postproc --disable-libsmbclient --enable-ffplay --enable-sdl2 --disable-vaapi --disable-vdpau --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-zlib --disable-libcdio --disable-libiec61883 --disable-libdc1394 --disable-libcaca --disable-openal --enable-opengl --disable-libv4l2 --disable-libpulse --disable-libdrm --disable-libjack --disable-libopencore-amrwb --disable-libopencore-amrnb --disable-libcodec2 --disable-libdav1d --disable-libfdk-aac --enable-libopenjpeg --disable-libbluray --disable-libgme --disable-libgsm --disable-libaribb24 --disable-mmal --disable-libmodplug --disable-libopus --disable-libilbc --disable-librtmp --disable-libssh --disable-libspeex --disable-libsrt --enable-librsvg --disable-ffnvcodec --enable-libvorbis --disable-libvpx --disable-libzvbi --disable-appkit --disable-libbs2b --disable-chromaprint --disable-cuda-llvm --disable-libflite --disable-frei0r --disable-libfribidi --enable-fontconfig --enable-ladspa --disable-libass --disable-libtesseract --disable-lv2 --enable-libfreetype --disable-libvidstab --disable-librubberband --disable-libzmq --disable-libzimg --disable-libsoxr --enable-pthreads --disable-libvo-amrwbenc --enable-libmp3lame --disable-libkvazaar --disable-libaom --disable-libopenh264 --disable-libsnappy --enable-libtheora --disable-libtwolame --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-neon --disable-vfp --disable-vfpv3 --disable-armv8 --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu --disable-altivec --disable-amd3dnow --disable-amd3dnowext --disable-aesni --disable-avx --disable-avx2 --disable-fma3 --disable-fma4 --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-xop --cpu=nocona --disable-doc --disable-htmlpages --enable-manpages
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Unrecognized option '-version'.
Error splitting the argument list: Option not found
ERROR: failed process: Process(`ffmpeg --version`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:440
 [3] run(::Cmd)
   @ Base ./process.jl:438
 [4] top-level scope
   @ REPL[1]:1
```

**Comment by BeastyBlacksmith** [comment]
> Very nice @BeastyBlacksmith , thanks!
> 
> Below is the result. Good news is that it seems to find some libraries. Maybe more good news is that this yields an error. Incidently, when I try the same command outside of julia I get the same thing but without the error.
> 
> Any idea what I could try next?
> 
> ```
> julia> run(`ffmpeg --version`)
> ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
>   built with gcc 9.3.0 (Gentoo 9.3.0 p2)
>   configuration: --prefix=/cvmfs/soft.computecanada.ca/gentoo/2020/usr --libdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64 --shlibdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64 --docdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/share/doc/ffmpeg-4.2.2/html --mandir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/share/man --enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ --ar=x86_64-pc-linux-gnu-ar --optflags='-O2 -pipe -march=nocona -mtune=generic -O2 -ftree-vectorize -fno-math-errno -pipe' --disable-static --enable-avfilter --enable-avresample --disable-stripping --disable-optimizations --disable-libcelt --disable-indev=v4l2 --disable-outdev=v4l2 --disable-indev=oss --disable-indev=jack --disable-outdev=oss --enable-bzlib --disable-runtime-cpudetect --disable-debug --disable-gcrypt --disable-gnutls --disable-gmp --enable-gpl --disable-hardcoded-tables --enable-iconv --disable-libtls --disable-libxml2 --enable-lzma --enable-network --disable-opencl --disable-openssl --enable-postproc --disable-libsmbclient --enable-ffplay --enable-sdl2 --disable-vaapi --disable-vdpau --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-zlib --disable-libcdio --disable-libiec61883 --disable-libdc1394 --disable-libcaca --disable-openal --enable-opengl --disable-libv4l2 --disable-libpulse --disable-libdrm --disable-libjack --disable-libopencore-amrwb --disable-libopencore-amrnb --disable-libcodec2 --disable-libdav1d --disable-libfdk-aac --enable-libopenjpeg --disable-libbluray --disable-libgme --disable-libgsm --disable-libaribb24 --disable-mmal --disable-libmodplug --disable-libopus --disable-libilbc --disable-librtmp --disable-libssh --disable-libspeex --disable-libsrt --enable-librsvg --disable-ffnvcodec --enable-libvorbis --disable-libvpx --disable-libzvbi --disable-appkit --disable-libbs2b --disable-chromaprint --disable-cuda-llvm --disable-libflite --disable-frei0r --disable-libfribidi --enable-fontconfig --enable-ladspa --disable-libass --disable-libtesseract --disable-lv2 --enable-libfreetype --disable-libvidstab --disable-librubberband --disable-libzmq --disable-libzimg --disable-libsoxr --enable-pthreads --disable-libvo-amrwbenc --enable-libmp3lame --disable-libkvazaar --disable-libaom --disable-libopenh264 --disable-libsnappy --enable-libtheora --disable-libtwolame --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-neon --disable-vfp --disable-vfpv3 --disable-armv8 --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu --disable-altivec --disable-amd3dnow --disable-amd3dnowext --disable-aesni --disable-avx --disable-avx2 --disable-fma3 --disable-fma4 --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-xop --cpu=nocona --disable-doc --disable-htmlpages --enable-manpages
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libavresample   4.  0.  0 /  4.  0.  0
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> Unrecognized option '-version'.
> Error splitting the argument list: Option not found
> ERROR: failed process: Process(`ffmpeg --version`, ProcessExited(1)) [1]
> 
> Stacktrace:
>  [1] pipeline_error
>    @ ./process.jl:525 [inlined]
>  [2] run(::Cmd; wait::Bool)
>    @ Base ./process.jl:440
>  [3] run(::Cmd)
>    @ Base ./process.jl:438
>  [4] top-level scope
>    @ REPL[1]:1
> ```

Okay its ``run(ffmpeg -version`)`` .__.

**Comment by francispoulin** [comment]
Ah, thanks.  That seems to work better.  No error.  But if `Plots.jl` isn't supposed to be using this version of ffmpeg then I suppose this isn't reallyl helping?

Incidently, I don't see that FFMPEG is in my list of installed libraries but I presume it is part of `Plots.jl`?

```
julia> run(`ffmpeg -version`)
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.3.0 (Gentoo 9.3.0 p2)
configuration: --prefix=/cvmfs/soft.computecanada.ca/gentoo/2020/usr --libdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64 --shlibdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64 --docdir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/share/doc/ffmpeg-4.2.2/html --mandir=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/share/man --enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ --ar=x86_64-pc-linux-gnu-ar --optflags='-O2 -pipe -march=nocona -mtune=generic -O2 -ftree-vectorize -fno-math-errno -pipe' --disable-static --enable-avfilter --enable-avresample --disable-stripping --disable-optimizations --disable-libcelt --disable-indev=v4l2 --disable-outdev=v4l2 --disable-indev=oss --disable-indev=jack --disable-outdev=oss --enable-bzlib --disable-runtime-cpudetect --disable-debug --disable-gcrypt --disable-gnutls --disable-gmp --enable-gpl --disable-hardcoded-tables --enable-iconv --disable-libtls --disable-libxml2 --enable-lzma --enable-network --disable-opencl --disable-openssl --enable-postproc --disable-libsmbclient --enable-ffplay --enable-sdl2 --disable-vaapi --disable-vdpau --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-zlib --disable-libcdio --disable-libiec61883 --disable-libdc1394 --disable-libcaca --disable-openal --enable-opengl --disable-libv4l2 --disable-libpulse --disable-libdrm --disable-libjack --disable-libopencore-amrwb --disable-libopencore-amrnb --disable-libcodec2 --disable-libdav1d --disable-libfdk-aac --enable-libopenjpeg --disable-libbluray --disable-libgme --disable-libgsm --disable-libaribb24 --disable-mmal --disable-libmodplug --disable-libopus --disable-libilbc --disable-librtmp --disable-libssh --disable-libspeex --disable-libsrt --enable-librsvg --disable-ffnvcodec --enable-libvorbis --disable-libvpx --disable-libzvbi --disable-appkit --disable-libbs2b --disable-chromaprint --disable-cuda-llvm --disable-libflite --disable-frei0r --disable-libfribidi --enable-fontconfig --enable-ladspa --disable-libass --disable-libtesseract --disable-lv2 --enable-libfreetype --disable-libvidstab --disable-librubberband --disable-libzmq --disable-libzimg --disable-libsoxr --enable-pthreads --disable-libvo-amrwbenc --enable-libmp3lame --disable-libkvazaar --disable-libaom --disable-libopenh264 --disable-libsnappy --enable-libtheora --disable-libtwolame --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-neon --disable-vfp --disable-vfpv3 --disable-armv8 --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu --disable-altivec --disable-amd3dnow --disable-amd3dnowext --disable-aesni --disable-avx --disable-avx2 --disable-fma3 --disable-fma4 --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-xop --cpu=nocona --disable-doc --disable-htmlpages --enable-manpages
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
Process(`ffmpeg -version`, ProcessExited(0))
```

**Comment by BeastyBlacksmith** [comment]
It should be in your `Manifest.toml`
you can check via `pkg> st -m FFMPEG`

**Comment by giordano** [comment]
> @giordano is that possible?

Yes, but I'm confused, we should support glibc down to v2.12 on x86_64 platforms

**Comment by francispoulin** [comment]
Thanks.  I checked and it says no Matches.  I haven't needed to install FFMPEG before but do you think I should install it and then try it again?

**Comment by giordano** [comment]
How did you install Julia?

**Comment by francispoulin** [comment]
> How did you install Julia?

Actually, I didn't.  The server has a module called `julia/1.6.0` that I loaded.  If you think that it's better that I install my own version of julia then I can certainly give that a try.  

One issue is that I want to have CUDA aware MPI and the people who maintian the server have been very good at helping me build this with their version of julia. If I build my own then I suppose I could be on my own, but it might be worth trying just to see if this problem goes away.

@giordano : What do you suggest?

**Comment by BeastyBlacksmith** [comment]
Can you check which version of glibc is on the server via `ldd --version`?

**Comment by francispoulin** [comment]
Happy to check this.  The output is below

```
$ ldd --version
ldd (Gentoo 2.30-r8 p10) 2.30
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by giordano** [comment]
What's the output of
```
$ /lib64/libc.so.6
```
?

**Comment by francispoulin** [comment]
Copied below

```
$ /lib64/libc.so.6 
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-39).
Compiled on a Linux 3.10.0 system on 2020-03-31.
Available extensions:
	The C stubs add-on version 2.1.2.
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
	RT using linux kernel aio
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

**Comment by giordano** [comment]
This is the libc being used, the one that is complaining that it doesn't know the version 2.18.  Can you please also show the output of
```
realpath /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0/bin/../lib/julia/libstdc++.so.6
nm /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0/bin/../lib/julia/libstdc++.so.6 | grep GLIBC_
```

**Comment by francispoulin** [comment]
Certainly.

From the first I get

```
/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0/lib/julia/libstdc++.so.6
```
From the second, there is no output, which I guess means it didn't find anything?

**Comment by giordano** [comment]
Well, that's not really possible.  Do you get anything with just
```
nm /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0/bin/../lib/julia/libstdc++.so.6
```
It should be a quite long list of symbols.  If not, is
```
nm -D /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0/bin/../lib/julia/libstdc++.so.6
```
any different?

**Comment by francispoulin** [comment]
Yes, both give a long list of symbols.  

Below is a larger set than the one that you tried as I removed the `_` at the end.

```
$ nm /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/julia/1.6.0/bin/../lib/julia/libstdc++.so.6 | grep GLIBC
0000000000000000 A GLIBCXX_3.4
0000000000000000 A GLIBCXX_3.4.1
0000000000000000 A GLIBCXX_3.4.10
0000000000000000 A GLIBCXX_3.4.11
0000000000000000 A GLIBCXX_3.4.12
0000000000000000 A GLIBCXX_3.4.13
0000000000000000 A GLIBCXX_3.4.14
0000000000000000 A GLIBCXX_3.4.15
0000000000000000 A GLIBCXX_3.4.16
0000000000000000 A GLIBCXX_3.4.17
0000000000000000 A GLIBCXX_3.4.18
0000000000000000 A GLIBCXX_3.4.19
0000000000000000 A GLIBCXX_3.4.2
0000000000000000 A GLIBCXX_3.4.20
0000000000000000 A GLIBCXX_3.4.21
0000000000000000 A GLIBCXX_3.4.22
0000000000000000 A GLIBCXX_3.4.23
0000000000000000 A GLIBCXX_3.4.24
0000000000000000 A GLIBCXX_3.4.25
0000000000000000 A GLIBCXX_3.4.26
0000000000000000 A GLIBCXX_3.4.27
0000000000000000 A GLIBCXX_3.4.28
0000000000000000 A GLIBCXX_3.4.3
0000000000000000 A GLIBCXX_3.4.4
0000000000000000 A GLIBCXX_3.4.5
0000000000000000 A GLIBCXX_3.4.6
0000000000000000 A GLIBCXX_3.4.7
0000000000000000 A GLIBCXX_3.4.8
0000000000000000 A GLIBCXX_3.4.9
```

**Comment by giordano** [comment]
I'm not really sure what's going on there, but you should have way more symbols containing the `GLIBCXX` tag.  Also, the [official binaries](https://julialang.org/downloads/) of Julia should come with libstdc++ from GCC 9.1, which corresponds to `GLIBCXX_3.4.26`, you have up to `GLIBCXX_3.4.28`, which is GCC 10.

My educated guess is that Julia was compiled with easybuild with a version of GCC built against a newer version glibc, but the same version of glibc isn't available at runtime thus causing you troubles.

If you use the official binaries of Julia you shouldn't have any of these issues, as we build everything with glibc 2.12 for x86_64.

**Comment by francispoulin** [comment]
Thanks @giordano for your insights.  It is greatly appreciated.

I looked a bit more deeply and the server is running CentOS 7.  

I agree that given the folder structure, they used easybuild to install julia, because it was convenient for them.  

On my local machine, I am running ubuntu, which I installed using the standard `apt` and I do have a lot of stuff there.

Do you think I should just build my own version of julia?  I did it on my desktop and can try on the server with the same modules that I loaded before, but without julia of course.

I guess this might be a problem for the easybuild version of Julia but not sure whether contacting them would bear any more fruit.

**Comment by giordano** [comment]
No, I'm trying to suggest to use the [official binaries](https://julialang.org/downloads/).  No need to build anything

**Comment by francispoulin** [comment]
Ah, sorry that I misunderstood.  I see that I can install it for me only so I will try that right now.  I will let you know how it goes.

**Comment by francispoulin** [comment]
I can confirm that when I use the julia 1.6.1 binary I can successfully run the example mentioned above.  

I will try and set things up to make things MPI aware like the whole system and hope this works.

I guess it's good that I learn to download my old binaries, that way I can use stable versions and have more control as to what I'm doing.

Thank you everyone for the help!

**Comment by chris-revell** [comment]
I seem to be having the same issue: the code hangs indefinitely on calling the `gif()` function, and killing the program produces very similar errors to above. Unfortunately reinstalling Julia from binaries has not helped for me.

**Comment by giordano** [comment]
Can you please open a new issue?  You'll need to provide some more information though, like

* actually show the full error message, including full stacktrace (if it looks meaningless to you, it may be useful to who wants to help you)
* operating system
* if Linux, what's the value of the `LD_LIBRARY_PATH` environment variable inside Julia, if macOS wat's the value of the `DYLD_FALLBACK_LIBRARY_PATH` environment variable

**Comment by chris-revell** [comment]
Will do
