### ISSUE TITLE
Add to plot without mutating it [FR]

### ISSUE THREAD

**Issue by azev77** [JuliaPlots/Plots.jl#3593]
Currently
```julia
using Plots;
xg = 0.01:0.01:10.0;

p0 = plot(xg, sin, legend=:topleft)
p0 = plot!(p0, xg, cos)

p1 = plot!(deepcopy(p0), xg, log)
p2 = plot!(deepcopy(p0), xg, sqrt)
p3 = plot!(deepcopy(p0), xg, tan)
```

It would be nice to add to `p0` without mutating it or creating a subplot. 
Something like: `plot(p0, xg, log) =  plot!(deepcopy(p0), xg, log)`
In the source code:
https://github.com/JuliaPlots/Plots.jl/blob/1523ef67d5c0367a42fb9589e8857833cb639ca4/src/plot.jl#L94
Maybe add something like:
`plot(plt1::Plot, ...; kw...) = plot!(deepcopy(plt1), ...; kw...)`

**Comment by BeastyBlacksmith** [comment]
That is reasonable, do you mind opening a PR?
