### ISSUE TITLE
[BUG] GR error message when y=0 and yaxis=:log10

### ISSUE THREAD

**Issue by mortenpi** [JuliaPlots/Plots.jl#3594]
The following snippet

```julia
plot(
    1:5, [1,2,0,4,5],
    m = [:utriangle, :dtriangle, :utriangle, :dtriangle, :dtriangle],
    yaxis = :log10, ylims = (1e-1, 1e1),
)
```

will produce a warning in the terminal when rendering with GR:

```
GKS: Number of points is invalid in routine POLYLINE
```

The plot is fine (with a missing data point at `x = 3`, where the `y` value is `0` and therefore can't be displayed on a log scale). At a glance, looks similar to #2735, but I think it's unrelated to that.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |  x   |
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

I tested the latest master for both Plots and GR, but it is also present in recent releases. Full MWE environment [in this gist](https://gist.github.com/mortenpi/e272da48dd248f3ea0891bb4c03f3289).

Plots.jl version: v1.16.7
Backend  version (`]st -m <backend(s)>`): GR v0.57.5
Output of `versioninfo()`:

**Comment by t-bltg** [comment]
Happens also on octave with zero valued data:
```bash
$ octave --eval 'loglog(1:5, [1 2 0 4 5]); ylim([1e-1 1e1]); saveas(1, "a.png")'
warning: axis: omitting non-positive data in log plot
warning: called from
    __plt__>__plt2vv__ at line 500 column 10
    __plt__>__plt2__ at line 247 column 14
    __plt__ at line 112 column 18
    loglog at line 65 column 10
```
![foo](https://user-images.githubusercontent.com/13423344/124275607-0cdc7b80-db43-11eb-9657-da5ae5f3d694.png)

The question is, what should to do with undefined behavior ?

**Comment by mortenpi** [comment]
It's a fair point that this is a case of slightly garbage input. I would make the argument that Plots should check for this, issue its own warning (which would actually say what the problem is, something like "`0 value passed for a log plot, removing points`") and then sanitize the data so that GR wouldn't print any warnings of its own.

The main problem I see here is that the message from GR is pretty useless. I ran into this with a notebook where I generate heaps of plots from a dataset. Every now and then this error would pop up, polluting the output. When digging into this my initial guess was that something had broken in the Plots/GR global state because I am generating many somewhat complex plots. It took some effort to figure out that it was simply because of passing zeros to `plot` -- I had not realized that my data can even contains zeros every now and then.

**Comment by t-bltg** [comment]
I've pushed a PR proposing a fix, which shows the index and the serie at which the invalid data is found.
I agree that this is a job for the high level `Plots.jl` and not for the lower level backend.
However, I don't think that we should sanitize the data: it is the responsibility of the user not to feed invalid data (since again this is undefined behavior, and fixing undef is arbitrary and thus subject to debate).

**Comment by mcabbott** [comment]
I think plots uses `NaNMath.log` and thus ought to pass GR NaN/Inf values, not negative/zero ones. 
```julia
julia> NaNMath.log.(-1:2)
4-element Vector{Float64}:
 NaN
 -Inf
   0.0
   0.6931471805599453
```
The warning from GR is only when you have both a line and a list of custom markers. Maybe that's a clue as to how it evades NaNMath in this particular case? In other cases, GR seems happy:
```julia
julia> plot(
           1:5, [1,2,0,4,5],
           m = :utriangle,  # line + one marker, no warning
           yaxis = :log10, ylims = (1e-1, 1e1),
       )
┌ Warning: Invalid negative or zero value 0.0 found at series index 3 for log10 based yscale
└ @ Plots ~/.julia/packages/Plots/AJMX6/src/utils.jl:95

julia> scatter(
           1:5, [1,2,0,4,5],
           m = [:utriangle, :dtriangle, :utriangle, :dtriangle, :dtriangle],   # many markers, no line, no warning
           yaxis = :log10, ylims = (1e-1, 1e1),
       )
┌ Warning: Invalid negative or zero value 0.0 found at series index 3 for log10 based yscale
└ @ Plots ~/.julia/packages/Plots/AJMX6/src/utils.jl:95

julia> plot(  # original case above
           1:5, [1,2,0,4,5],
           m = [:utriangle, :dtriangle, :utriangle, :dtriangle, :dtriangle],
           yaxis = :log10, ylims = (1e-1, 1e1),
       )
┌ Warning: Invalid negative or zero value 0.0 found at series index 3 for log10 based yscale
└ @ Plots ~/.julia/packages/Plots/AJMX6/src/utils.jl:95
GKS: Number of points is invalid in routine POLYLINE
```
The warning added in  #3601 is much less targeted. Should plots give warnings on all missing points, like `plot([1,2,Inf,2,1])`, or is skipping points on a log scale more dangerous? It is quite noisy to do this for every series of every plot on which they are skipped.
