### ISSUE TITLE
[BUG] PGFPlotsX backend, plot!(p,tex_output_standalone = true) does not work

### ISSUE THREAD

**Issue by sverek** [JuliaPlots/Plots.jl#3600]
## Details
When using PGFPlotsX backend I can no longer make it output a standalone .tex-file, by
```
plot!(p,tex_output_standalone = true)
```
which used to work. The value
```
p.attr[:tex_output_standalone]
```
is still false.

However, using 
```
p.attr[:tex_output_standalone]=true
```
achieves it.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |  x   |     |
inspectdr    |     |     |

### Versions

Plots.jl version: v1.16.7
Backend  version (`]st -m <backend(s)>`): v1.3.0
Output of `versioninfo()`:
Julia Version 1.7.0-beta2
Commit b570546b68 (2021-06-20 06:31 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)

**Comment by BeastyBlacksmith** [comment]
The reason is that you now hit https://github.com/JuliaPlots/Plots.jl/blob/0ca5bc91243b77bcf5294e983b445141d995fd50/src/plot.jl#L95 while earlier you'd hit https://github.com/JuliaPlots/Plots.jl/blob/0ca5bc91243b77bcf5294e983b445141d995fd50/src/plot.jl#L189

**Comment by sverek** [comment]
Thanks! :)
