### ISSUE TITLE
[BUG] Incremental compilation broken

### ISSUE THREAD

**Issue by pdeffebach** [JuliaPlots/Plots.jl#3624]
## Details

I can't seem to use Plots `1.18.0`. It gives the following error

```
julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
Your GR installation is incomplete. Rerunning build step for GR package.
ERROR: LoadError: LoadError: InitError: Evaluation into the closed module `GR` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `GR` with `eval` during precompilation - don't do this.
```

This happens on a fresh session, when I don't think I have anything that would mess with precompilation. 

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x    |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`): 0.57.5

Output of `versioninfo()`:

```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_DEVDIR = /home/peterwd/Documents/Development
  JULIA_EDITOR = subl
```

**Comment by pdeffebach** [comment]
`] build GR`  seems to have fixed this

**Comment by t-bltg** [comment]
`]build Plots` ?

**Comment by pdeffebach** [comment]
Update: neither `] build Plots` nor `] build GR` work. 

And when I try to plot, it hangs indefinitely. Seems to get messed up regardless of version, though. Still narrowing that down.

**Comment by t-bltg** [comment]
Please provide a mwe containing what you are trying to plot.

**Comment by pdeffebach** [comment]
just `plot(rand(10), rand(10))`, my go-to for testing plotting.

**Comment by pdeffebach** [comment]
I'm nuking `.julia` and running `] instantiate` to see what happens.

**Comment by pdeffebach** [comment]
Things appear to work after that. No sure what that means all things considered. Let me know what more information to provide.

**Comment by t-bltg** [comment]
Sometimes a fresh start is necessary :wink: 

If it works can we close ?

**Comment by pdeffebach** [comment]
Let me keep this open a bit because I'm not sure what triggered the error. It was working fine until it wasn't. Maybe it will break again in an informative way. Will close in a few days if all is working.

**Comment by t-bltg** [comment]
> Let me keep this open a bit because I'm not sure what triggered the error.

Most certainly the update to Plots `1.18.0` which was released yesterday.

**Comment by newptcai** [comment]
I have the same problem after updating to Plots v1.19.2.
`build GR` seems to resolve it.
