### ISSUE TITLE
Incorrect color assignment for grouped variables. 

### ISSUE THREAD

**Issue by itsdfish** [JuliaPlots/Plots.jl#3630]
In the center plot where a=2, the sloped line should be black and the flat line should be red, as when a=1 and a=3. This might be related to this [issue](https://github.com/JuliaPlots/StatsPlots.jl/issues/442). Please fix this as soon as possible, as it is producing incorrect/misleading results. 

```julia
using StatsPlots, DataFrames

df = DataFrame(
        a = repeat(1:3,inner=4),
        b = repeat(["low","high"], inner=2, outer=3),
        c = repeat(1:2, outer=6),
        d = [1,1,1,2,
             2,2,2,4,
             3,3,3,6]
)

@df df plot(:b, :d, group=(:c, :a), legend=false, layout=(1,3), 
    ylims=(0,6), grid=false, ylabel="d", color=[:darkred :black], 
    title=["a=1" "a=2" "a=3"], xlabel="b", size=(600,200))
```

Version
```
Julia 1.6.1
[91a5bcdd] Plots v1.12.0
[f3b207a7] StatsPlots v0.14.19
```
![temp](https://user-images.githubusercontent.com/9677184/116240743-2b348e00-a732-11eb-8a69-41773b3cff3b.png)

**Comment by itsdfish** [comment]
Thank you for transferring this issue.

**Comment by BeastyBlacksmith** [comment]
I'd say this is expected and documented behaviour, since it colors the series alternating red and black, its just that the series order is as shown in [this example](https://docs.juliaplots.org/latest/generated/gr/#gr-ref17).

You can get the result you want by using 
`color = [:red :red :red :black :black :black]`

**Comment by itsdfish** [comment]
Thanks for pointing out the solution. 

At one point, it was possible to specify the color with `color=[:red,:black]`. I assumed it was an error because I could not locate the change. Nonetheless, I want to point out that it is not clear to the user how to assign the colors based on numerical indices. I can only imagine this would be even more challenging with more factors, more levels within factors, and more noise in the patterns. Is there a good way to apply the correct color scheme?

**Comment by t-bltg** [comment]
Solution given in https://github.com/JuliaPlots/Plots.jl/issues/3630#issuecomment-876251594.
