### ISSUE TITLE
When using rotation the ticks are cropped

### ISSUE THREAD

**Issue by joaogui1** [JuliaPlots/Plots.jl#3631]
When using the `rotation=90` keyword in plots the ticks are cropped.
```Julia
using StatsPlots
a = rand(10, 2)
boxplot(a, x_ticks=(1:3, ["abcat a", "abcat b"]), xrotation = 90)
```
REPL:
![image](https://user-images.githubusercontent.com/13261989/99240120-cbc57000-27da-11eb-9d9a-4d51fc4c594c.png)
Dragging the frame doesn't help
![image](https://user-images.githubusercontent.com/13261989/99240281-0929fd80-27db-11eb-8c98-04375593e856.png)
Same problem in Pluto:
![image](https://user-images.githubusercontent.com/13261989/99191605-6f1b7400-274c-11eb-9c06-d77cf05da54f.png)
And in Jupyter:
![image](https://user-images.githubusercontent.com/13261989/99240358-252d9f00-27db-11eb-9e45-ee54448643d2.png)

**Comment by mkborregaard** [comment]
Yes, margins don't know anything about ticks, because text sizes can vary among backends. I guess it could give a qualified guess though, when margins are set to the default value.

**Comment by BeastyBlacksmith** [comment]
You can work around by setting e.g. `bottom_margin = 5Plots.cm` though

**Comment by joaogui1** [comment]
Thanks for the tip @BeastyBlacksmith
