### ISSUE TITLE
[FR] In addition to OHLC bars - may we include candlestick bars as well

### ISSUE THREAD

**Issue by flare9x** [JuliaPlots/Plots.jl#3637]
Basically candlestick plot uses OHLC data only it 'shades' the space between open and close as below:

![image](https://user-images.githubusercontent.com/23480124/125148618-5e63a800-e0f9-11eb-98d4-19db84eb79c0.png)

if close < open = down market bar or BLACK shaded (other color set by user) :: shade space between open and close

if close > open = up market bar or WHITE shaded (other color set by user) :: shade space between open and close

if close == open = unchanged or a Black (no color) :: assign open and close price (basically will look like a OHLC bar this one as below) 

![image](https://user-images.githubusercontent.com/23480124/125148753-12653300-e0fa-11eb-8baf-3e4ce7650b64.png)

Would be a nice addition

**Comment by t-bltg** [comment]
Something like that ?
![ohlc-1](https://user-images.githubusercontent.com/13423344/125158876-0d44ca00-e174-11eb-9cca-d80212dbee02.png)

**Comment by flare9x** [comment]
Yes exactly!

**Comment by t-bltg** [comment]
Here is a simple patch:
```diff
--- a/Plots/ldLtW/src/recipes.jl	2021-07-11 02:47:33.835214279 +0200
+++ b/Plots/ldLtW/src/recipes.jl	2021-07-11 02:50:42.632407972 +0200
@@ -1532,6 +1532,31 @@
     x_out, y_out
 end
 
+rectangle(w, h, x, y) = Shape(x .+ [0, w, w, 0], y .+ [0, 0, h, h])
+
+function get_xy_s(o::OHLC, x, xdiff)
+    xl, xm = x - xdiff, x
+    open, close = min(o.open, o.close), max(o.open, o.close)
+    x1, y1 = coords(rectangle(0, open - o.low, xm, o.low))
+    x2, y2 = coords(rectangle(2xdiff, close - open, xl, open))
+    x3, y3 = coords(rectangle(0, o.high - close, xm, close))
+    ox = [x1..., NaN, x2..., NaN, x3...]
+    oy = [y1..., NaN, y2..., NaN, y3...]
+    ox, oy, o.close < o.open
+end
+
+function get_xy_s(v::AVec{OHLC}, x = eachindex(v))
+    xdiff = 0.1 * ignorenan_mean(abs.(diff(x)))
+    x_out, y_out = zeros(0), zeros(0)
+    X_out, Y_out = zeros(0), zeros(0)
+    for (i, ohlc) in enumerate(v)
+        ox, oy, cond = get_xy_s(ohlc, x[i], xdiff)
+        nanappend!(cond ? x_out : X_out, ox)
+        nanappend!(cond ? y_out : Y_out, oy)
+    end
+    (x_out, y_out), (X_out, Y_out)
+end
+
 # these are for passing in a vector of OHLC objects
 # TODO: when I allow `@recipe f(::Type{T}, v::T) = ...` definitions to replace convertToAnyVector,
 #       then I should replace these with one definition to convert to a vector of 4-tuples
@@ -1553,13 +1578,29 @@
     x, OHLC[OHLC(t...) for t in ohlc]
 
 @recipe function f(x::AVec, v::AVec{OHLC})
-    seriestype := :path
-    get_xy(v, x)
+    # seriestype := :path
+    # get_xy(v, x)
+    seriestype := :shape
+    a, b = get_xy_s(v, x)
+    @series begin
+        a
+    end
+    @series begin
+        b
+    end
 end
 
 @recipe function f(v::AVec{OHLC})
-    seriestype := :path
-    get_xy(v)
+    # seriestype := :path
+    # get_xy(v)
+    seriestype := :shape
+    a, b = get_xy_s(v)
+    @series begin
+        a
+    end
+    @series begin
+        b
+    end
 end
 
 # the series recipe, when passed vectors of 4-tuples

```

Mwe:
```julia
using Plots; gr()
using Random; Random.seed!(1234)

n = 20
hgt = rand(n) .+ 1
bot = randn(n)
openpct = rand(n)
closepct = rand(n)
y = OHLC[
  (
    openpct[i] * hgt[i] + bot[i],
    bot[i] + hgt[i],
    bot[i],
    closepct[i] * hgt[i] + bot[i],
  ) for i ∈ 1:n
]
ohlc(y, label=["↓" "↑"])
png("ohlc")
```
![ohlc-1](https://user-images.githubusercontent.com/13423344/125179923-01005180-e1f4-11eb-87c2-bbe114124c8a.png)

**Comment by flare9x** [comment]
Works here - thanks :)

**Comment by t-bltg** [comment]
If you have time to properly integrate this through a PR that'll be great.

**Comment by flare9x** [comment]
K i tested normal OHLC bars and using new patch for candlestick OHLC - currently **all** OHLC defaults to candlestick OHLC.

**Comment by t-bltg** [comment]
> K i tested normal OHLC bars and using new patch for candlestick OHLC - currently **all** OHLC defaults to candlestick OHLC.

Well yes, I wrote this patch in `5min`. You'll need to rework it, maybe through an option, to be able to get the two behaviors.

**Comment by flare9x** [comment]
yes another argument to pass then can differentiate between the two.
