### ISSUE TITLE
[FR] highlight bars (like a marker type effect - opacity color)

### ISSUE THREAD

**Issue by flare9x** [JuliaPlots/Plots.jl#3639]
```julia
n = 20
hgt = rand(n) .+ 1
bot = randn(n)
openpct = rand(n)
closepct = rand(n)
y = OHLC[(openpct[i] * hgt[i] + bot[i], bot[i] + hgt[i], bot[i], closepct[i] * hgt[i] + bot[i]) for i = 1:n]
ohlc(y)
```

checked through attributes, i see markers but is there a way to color specific bars at defined index positions? Say i color these 2x bars yellow at x axis index position 11 and 15 for output:

![image](https://user-images.githubusercontent.com/23480124/125201822-5a897000-e236-11eb-9a6b-21867b3adc79.png)

colors: green, red, yellow, blue etc etc.... color bars at specified x axis index position. 
opacity of color highlight - 0 to 100% scale perhaps

**Comment by isentropic** [comment]
I doubt that this would be possible, I suggest you make a personal recipe for this.

**Comment by flare9x** [comment]
Perhaps rectangle shape in this case or fit the highlight to the bar outer dimensions and color

**Comment by t-bltg** [comment]
With a bit of a hack, this works:

```julia
using Plots; gr()

n = 20
hgt = rand(n) .+ 1
bot = randn(n)
openpct = rand(n)
closepct = rand(n)
y = OHLC[(openpct[i] * hgt[i] + bot[i], bot[i] + hgt[i], bot[i], closepct[i] * hgt[i] + bot[i]) for i ∈ 1:n]

m = 9  # ohlc generates 9 segments per value
c = [:black for _ ∈ 1:m*n]

for i ∈ (4, 10)
  c[(i-1)*m:i*m] .= :red
end

ohlc(y, seriescolor=c)
png("ohlc")
```
