### ISSUE TITLE
[BUG] Plots.jl suddenly fails in a CI workflow.

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaPlots/Plots.jl#3650]
## Details

Suddenly,
```
plot(1:15, 1:2:30, title="My Title", xlabel="x", ylabel="y")
```
gives an error in CI:
```
Writing plot images for JDS_plot_line_
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)
connect: Connection refused
GKS: can't connect to GKS socket application


signal (11): Segmentation fault
in expression starting at none:1
gks_drv_socket at /home/runner/.julia/artifacts/75b9879cb8ff826ca29a851cd915598194856459/lib/libGR.so (unknown line)
gks_ddlk.isra.0 at /home/runner/.julia/artifacts/75b9879cb8ff826ca29a851cd915598194856459/lib/libGR.so (unknown line)
gks_open_ws at /home/runner/.julia/artifacts/75b9879cb8ff826ca29a851cd915598194856459/lib/libGR.so (unknown line)
initgks at /home/runner/.julia/artifacts/75b9879cb8ff826ca29a851cd915598194856459/lib/libGR.so (unknown line)
gr_setcharheight at /home/runner/.julia/artifacts/75b9879cb8ff826ca29a851cd915598194856459/lib/libGR.so (unknown line)
setcharheight at /home/runner/.julia/packages/GR/aYvdc/src/GR.jl:1630
unknown function (ip: 0x7fe9e842693f)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#gr_set_font#380 at /home/runner/.julia/packages/Plots/S2aH5/src/backends/gr.jl:390
unknown function (ip: 0x7fe9e8426121)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
gr_set_font at /home/runner/.julia/packages/Plots/S2aH5/src/backends/gr.jl:389
_update_min_padding! at /home/runner/.julia/packages/Plots/S2aH5/src/backends/gr.jl:760
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
iterate at ./generator.jl:47 [inlined]
_collect at ./array.jl:691
unknown function (ip: 0x7fe9e841f645)
collect_similar at ./array.jl:606 [inlined]
map at ./abstractarray.jl:2294 [inlined]
```

Could be related to https://github.com/JuliaPackaging/Yggdrasil/pull/3349.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     |
plotly       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

See https://github.com/JuliaDataScience/JuliaDataScience/blob/main/Project.toml.

Failing run: https://github.com/JuliaDataScience/JuliaDataScience/runs/3094158493
Successful run (2 days ago): https://github.com/JuliaDataScience/JuliaDataScience/runs/3076631808

**Comment by rikhuijzer** [comment]
I did a diff over the package versions from the CI logs and got:

package | pass version | fail version
--- | --- | ---
Plots | 1.19.1 | 1.19.2
GR | 0.57.5 | 0.58.0
OffsetArrays | 1.10.2 | 1.10.3
StaticArrays | 1.2.6 | 1.2.7
GR_jll | 0.57.3+0 | 0.58.0+0

**Comment by rikhuijzer** [comment]
My bad. I forgot to set the environment variable `GKSwstype` to `nul`. For some reason, it worked without that variable on GR 0.57 and failed on GR 0.58.

**Comment by blegat** [comment]
> My bad. I forgot to set the environment variable `GKSwstype` to `nul`. For some reason, it worked without that variable on GR 0.57 and failed on GR 0.58.

Would it be possible to throw an error explaining that `GKSwstype` should be set to `nul` ? I have the feeling that a segfault is always a bug, even if the user didn't provide the right input.
