### ISSUE TITLE
PlotlyJS .png savefig issue: WARNING: could not import PlotlyBase.savefig into PlotlyJS

### ISSUE THREAD

**Issue by Boomer91** [JuliaPlots/Plots.jl#3703]
```julia
julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

julia> plotlyjs()
[ Info: Precompiling PlotlyJS [f0f68f2c-4968-5e81-91da-67840de0976a]
WARNING: could not import PlotlyBase.savefig into PlotlyJS
Plots.PlotlyJSBackend()

julia> p = plot(randn(10));

julia> savefig(p, "test.html")

julia> savefig(p, "test.png")
ERROR: MethodError: no method matching savefig(::IOStream, ::PlotlyJS.SyncPlot; format="png")
Closest candidates are:
  savefig(::IO, ::PlotlyBase.Plot; width, height, scale, format) at C:\Users\cyrieln\.julia\packages\PlotlyJS\gzO4g\src\kaleido.jl:138
Stacktrace:
 [1] _show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PlotlyJSBackend}) at C:\Users\cyrieln\.julia\packages\Plots\OchXa\src\backends\plotlyjs.jl:28
 [2] show at C:\Users\cyrieln\.julia\packages\Plots\OchXa\src\output.jl:215 [inlined]
 [3] png(::Plots.Plot{Plots.PlotlyJSBackend}, ::String) at C:\Users\cyrieln\.julia\packages\Plots\OchXa\src\output.jl:7
 [4] savefig(::Plots.Plot{Plots.PlotlyJSBackend}, ::String) at C:\Users\cyrieln\.julia\packages\Plots\OchXa\src\output.jl:124
 [5] top-level scope at REPL[7]:1
```

Libraries:

```julia
(@v1.5) pkg> st
Status `C:\Users\cyrieln\.julia\environments\v1.5\Project.toml`
  [ad839575] Blink v0.12.5
  [336ed68f] CSV v0.8.5
  [5ae59095] Colors v0.12.8
  [861a8166] Combinatorics v1.0.2
  [a93c6f00] DataFrames v1.2.1
  [31c24e10] Distributions v0.24.18
  [e30172f5] Documenter v0.27.5
  [35a29f4d] DocumenterTools v0.1.13
  [e2685f51] ECOS v0.12.3
  [60bf3e95] GLPK v0.14.12
  [c91e804a] Gadfly v1.3.3
  [5c1252a2] GeometryBasics v0.3.13
  [7073ff75] IJulia v1.23.2
  [c601a237] Interact v0.10.3
  [4076af6c] JuMP v0.21.8
  [a975b10e] Mux v0.7.6
  [d96e819e] Parameters v0.12.2
  [f0f68f2c] PlotlyJS v0.18.1
  [91a5bcdd] Plots v1.19.3
  [d330b81b] PyPlot v2.9.0
  [a223df75] Reactive v0.8.3
  [295af30f] Revise v3.1.17
  [90137ffa] StaticArrays v1.2.8
  [0f1e0344] WebIO v0.8.15
```

**Comment by t-bltg** [comment]
Could not reproduce the warning. Do you have `PlotlyBase` installed (in `] st -m`) ?

**Comment by t-bltg** [comment]
As a matter of fact, something is odd with plotly, as examples are not generated: http://docs.juliaplots.org/latest/generated/plotly.
I can link that to https://github.com/JuliaPlots/Plots.jl/runs/3181948251#step:6:1243, which looks similar to your issue.

**Comment by Boomer91** [comment]
I do:

What does -m do?

```
(@v1.5) pkg> st -m
Status `C:\Users\cyrieln\.julia\environments\v1.5\Manifest.toml`
  [ccf2f8ad] PlotThemes v2.0.1
  [995b91a9] PlotUtils v1.0.11
  [a03496cd] PlotlyBase v0.8.1
  [f0f68f2c] PlotlyJS v0.18.1
  [91a5bcdd] Plots v1.19.3
```

Interesting indeed..

**Comment by t-bltg** [comment]
`st -m` is a shorthand to `status --manifest` (see [here](https://pkgdocs.julialang.org/v1.1/managing-packages)) which show all the packages installed, not just those you explicitly added via `] add <some-package>`.

**Comment by t-bltg** [comment]
I see, this commit is responsible: https://github.com/sglyon/PlotlyBase.jl/commit/36acad687b67ed2c6e1c7d61295d817b2f283485.

**Comment by sglyon** [comment]
ahh whoops! This was my fault.

The savefig functionality was moved from PlotlyBase into PlotlyJS

I forgot to export `savefig` from PlotlyBase when I made teh change. Everything will currently work if you call `PlotlyJS.savefig`, but I will publish a release real quick that exports the function again

**Comment by t-bltg** [comment]
Seems like https://github.com/JuliaPlots/Plots.jl/blob/914ea027d0d93d785d38cda8e10e999d1e63be6b/src/backends/plotlyjs.jl#L28 is broken as well, should we instead use `plotlyjs_syncplot(plt).plot` ?.

**Comment by sglyon** [comment]
Sorry for the breaks I was careful to follow semver and move from PlotlyBase 0.7.X to 0.8.X when I made the change -- still frustrating.

I would think that the line you just linked to should still work. PlotlyJS now contains the savefig code that used to live in PlotlyBase

**Comment by t-bltg** [comment]
> I would think that the line you just linked to should still work. PlotlyJS now contains the savefig code that used to live in PlotlyBase

No, it fails building the docs:
```julia
┌ Warning: failed to run `@example` block in src/backends.md:129-132
│ ```@example backends
│ plotlyjs(); backendplot(n = 2) # hide
│ png("backends_plotly") # hide
│ ```
│   c.value =
│    MethodError: no method matching savefig(::IOStream, ::PlotlyJS.SyncPlot; format="png")
│    Closest candidates are:
│      savefig(::IO, ::PlotlyBase.Plot; width, height, scale, format) at /home/tb/.julia/packages/PlotlyJS/gzO4g/src/kaleido.jl:138
└ @ Documenter.Expanders ~/.julia/packages/Documenter/R2HVS/src/Expanders.jl:591
```

**Comment by sglyon** [comment]
ahh thanks for the traceback. Will get that fixed up and in the pending release (I'll have the release PR opened up in next 10 minutes)

**Comment by sglyon** [comment]
Done: https://github.com/JuliaRegistries/General/pull/41793
