### ISSUE TITLE
The issue has been confirmed with optional backends. For example "src/pyplot.jl, pgfplotsx.lj" do not work

### ISSUE THREAD

**Issue by aloy1496** [JuliaPlots/Plots.jl#3705]
The issue has been confirmed with optional backends. For example "src/pyplot.jl, pgfplotsx.lj" do not work

__Originally posted by @isentropic in https://github.com/JuliaPlots/Plots.jl/issues/3345#issuecomment-874458248__

**Comment by t-bltg** [comment]
Why open another issue since https://github.com/JuliaPlots/Plots.jl/issues/3345 is still open ?

**Comment by isentropic** [comment]
Let's move this discussion to https://github.com/timholy/Revise.jl/issues/636 for visibility

**Comment by isentropic** [comment]
@aloy1496 please post in the Revise repo for this to get attention. This has been bothering me for long too.

**Comment by isentropic** [comment]
The link I provided
