### ISSUE TITLE
@aloy1496 please post in the Revise repo for this to get attention. This has been bothering me for long too.

### ISSUE THREAD

**Issue by aloy1496** [JuliaPlots/Plots.jl#3706]
@aloy1496 please post in the Revise repo for this to get attention. This has been bothering me for long too.

__Originally posted by @isentropic in https://github.com/JuliaPlots/Plots.jl/issues/3705#issuecomment-888157906__

**Comment by t-bltg** [comment]
Per https://github.com/JuliaPlots/Plots.jl/issues/3705#issuecomment-888157906.
