### ISSUE TITLE
[BUG] scatter plot ignores alpha

### ISSUE THREAD

**Issue by mcabbott** [JuliaPlots/Plots.jl#3753]
## Details

Scatter plots seem to ignore `alpha` for me, example below. Line plots are fine.

This is on an M1 mac, with the native Julia nightly. 

~~I am today unable to get Plots + GR working at all on Julia 1.6 + rosetta, although at some point I thought I managed, perhaps with a particular older version pinned.~~ Edit: from here https://github.com/JuliaLang/julia/issues/36617#issuecomment-812408248, `] add Plots@1.11.1` is one version which works under rosetta, for which this problem does *not* occur. I can't run that version natively, though.

```
Plots.plot(rand(30,5), alpha=0.5, line=10)  # this has opacity

Plots.scatter!(30*rand(30), rand(30), ms=50*rand(30), alpha=0.5, c=rand(1:3, 30))  # this does not
```

<img width="712" alt="Screenshot 2021-08-15 at 17 18 03" src="https://user-images.githubusercontent.com/32575566/129493196-269fdc30-7f48-4070-b798-5880216ce588.png">

Edit -- The problem also doesn't show up in the saved PNG file:
```
savefig("scatter_test.png")  # this file has transparency, correctly
savefig("scatter_test.pdf")  # likewise fine.
```

It does not occur when using GR directly:
```
using GR

GR.scatter(rand(30), rand(30), 4000*rand(30), rand(1:50:250, 30), alpha=0.5)  # works fine
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |     | x
plotly       |     |  x  |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
inspectdr    |     |     | x

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`):
```
(jl_HQfA5O) pkg> st
      Status `/private/var/folders/yq/4p2zwd614y59gszh7y9ypyhh0000gn/T/jl_HQfA5O/Project.toml`
  [28b8d3ca] GR v0.58.1
  [91a5bcdd] Plots v1.20.1
```
Output of `versioninfo()`:
```
julia> versioninfo()
Julia Version 1.8.0-DEV.322
Commit e87e30c0e3 (2021-08-09 11:15 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.6.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by BeastyBlacksmith** [comment]
FWIW that code is fine on Ubuntu20.04

**Comment by mcabbott** [comment]
It also seems fine when I save to disk. I've edited text above to mention this.

**Comment by t-bltg** [comment]
I can't reproduce on `GKS term` (which is the `OP` issue).

**Comment by mcabbott** [comment]
Works for me locally too, Plots v1.36.2. Thanks for checking, I had forgotten about this issue.
