### ISSUE TITLE
[FR] don't crash if X server not available

### ISSUE THREAD

**Issue by RibeiroAndre** [JuliaPlots/Plots.jl#3760]
Please search existing issues to avoid duplicates.
Hello!
If I try to plots something when ssh'd into a Linux machine without an X server, Julia crashes (using GR, which is default).
It would be great if Plots could check for that and just issue a warning to switch to UnicodePlots or something.
Thanks!

**Comment by BeastyBlacksmith** [comment]
Does it crash on display? Because I think you should be able to write plots to disk even with GR.

**Comment by RibeiroAndre** [comment]
Here's an example error:
```
julia> using Plots

julia> plot(rand(3),rand(3));

julia> savefig("tmp.png");
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

connect: Connection refused
GKS: can't connect to GKS socket application

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
```
This time it didn't crash. I'm not sure why sometimes it crashes and sometimes it doesn't.

**Comment by BeastyBlacksmith** [comment]
Ah, right, I think you need `ENV["GKSwstype"] = "100"` for that.

**Comment by t-bltg** [comment]
See https://discourse.julialang.org/t/deactivate-plot-display-to-avoid-need-for-x-server/.

**Comment by RibeiroAndre** [comment]
Is there a way I can auto-detect if there's an X server? That way I can check that in my scripts and if there isn't one, I can run that.
Thanks!

**Comment by t-bltg** [comment]
> Is there a way I can auto-detect if there's an X server? That way I can check that in my scripts and if there isn't one, I can run that.
> Thanks!

```bash
$ compgen -e SSH_
SSH_AUTH_SOCK
SSH_CLIENT
SSH_CONNECTION
```

Something like this:
```julia
!any(map(x->x ∈ keys(ENV), ("SSH_CLIENT", "SSH_TTY", "SSH_CONNECTION", "SSH_AUTH_SOCK"))) && get!(ENV, "GKSwstype",  "nul")
```

**Comment by RibeiroAndre** [comment]
Nice! Thanks! I ended up using this:
```
"SSH_CONNECTION" in keys(ENV) ? unicodeplots() : nothing
```

I leave it up to you guys if you want to keep this open or not, since it would still be nice to get a better error message when a plot doesn't work due to X server.

**Comment by t-bltg** [comment]
> I leave it up to you guys if you want to keep this open or not, since it would still be nice to get a better error message when a plot doesn't work due to X server.

That's a `GR` thing, not `Plots`.
