### ISSUE TITLE
`contour` does not plot over the whole domain

### ISSUE THREAD

**Issue by francispoulin** [JuliaPlots/Plots.jl#3762]
## Details

I am trying to plot an array using `contour` and it does not seem to plot all the contours, but `contourf` does.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: v1.20.1
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) W-2295 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cascadelake)

I have defined the following array:
```julia
A = [0.0  0.015625   0.0625     0.140625   0.25      0.390625  0.5625    0.765625  1.0
                     0.0  0.0156245  0.0624991  0.140624   0.249999  0.390624  0.562499  0.765624  1.0
                     0.0  0.0156115  0.0624769  0.140596   0.249969  0.390596  0.562477  0.765612  1.0
                     0.0  0.0154144  0.0621382  0.140172   0.249517  0.390172  0.562138  0.765414  1.0
                     0.0  0.0136686  0.0590821  0.136326   0.2454    0.386305  0.559039  0.763605  1.0
                     0.0  0.0        0.0433791  0.115757   0.222958  0.364983  0.541832  0.753504  1.0
                     0.0  0.0        0.0        0.0548146  0.150001  0.292113  0.48115   0.717113  1.0
                     0.0  0.0        0.0        0.0        0.0       0.14888   0.348769  0.632475  1.0
                     0.0  0.0        0.0        0.0        0.0       0.0625    0.25      0.5625    1.0
                     0.0  0.0        0.0        0.0        0.0       0.14888   0.348769  0.632475  1.0
                     0.0  0.0        0.0        0.0548146  0.150001  0.292113  0.48115   0.717113  1.0
                     0.0  0.0        0.0433791  0.115757   0.222958  0.364983  0.541832  0.753504  1.0
                     0.0  0.0136686  0.0590821  0.136326   0.2454    0.386305  0.559039  0.763605  1.0
                     0.0  0.0154144  0.0621382  0.140172   0.249517  0.390172  0.562138  0.765414  1.0
                     0.0  0.0156115  0.0624769  0.140596   0.249969  0.390596  0.562477  0.765612  1.0
                     0.0  0.0156245  0.0624991  0.140624   0.249999  0.390624  0.562499  0.765624  1.0]
```
When I try plotting `plt = contour(A')` I get the following plot entitled `contour.png`.  It seems to be missing stuff at the top, which is included in the `contourf` version.  Is this a bug? 
![contourf](https://user-images.githubusercontent.com/8239041/130681126-355a28c0-7f2c-4e13-82ba-fb9318db040f.png)
![contour](https://user-images.githubusercontent.com/8239041/130681127-fc55522c-7ebf-4071-81b1-357ed8202c36.png)

**Comment by t-bltg** [comment]
Closing in favor of https://github.com/jheinen/GR.jl/issues/503 (this is a low-level backend issue).
