### ISSUE TITLE
[BUG] PGFPlotsX backend handles some preamble options incorrectly 

### ISSUE THREAD

**Issue by BambOoxX** [JuliaPlots/Plots.jl#3771]
## Details

`PGFPlotsX` backend does not apply correctly some preamble modifications. 
Note that the same issue (see https://github.com/KristofferC/PGFPlotsX.jl/issues/277) does not happen when `PGFPlotsX` is directly used.

See this example
```julia
using Plots; pgfplotsx()

# reference plot
plt1 = plot(rand(10)) #<-- gives 1st picture
savefig(plt1,"1.png")

# plot with modified fonts
push!(PGFPlotsX.CUSTOM_PREAMBLE,raw"\usepackage{newtxtext,newtxmath}")
plt2 = plot(rand(10)) # <-- gives 2nd picture (font is correctly changed)
savefig(plt2,"2.png")

# plot with custom dimensions
push!(PGFPlotsX.CUSTOM_PREAMBLE,raw"\pgfplotsset{every axis/.append style={width = 7cm, height = 4cm, scale only axis}}")
plt3 = plot(rand(10)) #<-- gives 3rd picture (but output size is incorrect)
savefig(plt3,"3.png")
```
Picture 1
![1](https://user-images.githubusercontent.com/42067365/130953585-7c50bd14-b0d5-45fb-9178-5e9bd5c281b5.png)

Picture 2
![2](https://user-images.githubusercontent.com/42067365/130953604-86f6fda1-0a32-4cbb-9499-c02cddde86d0.png)

Picture 3
![3](https://user-images.githubusercontent.com/42067365/130953614-916e3a11-e50b-4b9d-9008-4d9f121a044d.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |    x |
pyplot       |     |   x  |
plotly       |     |  x   |
plotlyjs     |     | x    |
pgfplotsx    |   x  |     |
inspectdr    |     |x     |

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:

**Comment by BeastyBlacksmith** [comment]
You could try to convert at the call site like this
```julia
using Plots
w = round(7Plots.cm / Plots.px)
h = round(4Plots.cm / Plots.px)
plot(rand(10), size=(w, h))
```
