### ISSUE TITLE
[BUG] Recent update causes angled axis labels to be mis-positioned

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaPlots/Plots.jl#3776]
## Details
![image](https://user-images.githubusercontent.com/1438610/131175725-687bf82d-24bb-45a6-8814-9b454451a800.png)

It looks like the tick labels are being rotated around their center, but not offset like they used to be.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     | x
plotly       |   x*  |     | 
plotlyjs     |     |     | x 
pgfplotsx    |     |     | x
inspectdr    |     |     | x

* plotly crashes in `Plots.tick_padding` with `ERROR: MethodError: no method matching length(::Date)` within a call to `maximum`

### Versions

Plots.jl version: 1.21.1
Backend  version (`]st -m <backend(s)>`): 0.58.1
Output of `versioninfo()`:
```
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =
```

**Comment by BioTurboNick** [comment]
45 and higher seems to be fine. Lower than 45 has the problem.

**Comment by t-bltg** [comment]
I still have to think what we should do here.

**mwe**
```julia
using Measures, Random, Dates, Plots
Random.seed!(2018)

main() = begin
  days = 31
  position = cumsum(randn(days))
  x = Date(2018, 1, 1):Day(1):Date(2018, 1, 31)
  ticks = [x[i] for i in 1:5:length(x)]

  for θ in (10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 75)
    plot(x, position,
      xlabel = "Date",
      ylabel = "Position",
      title = "Track of random walker",
      xticks = ticks,
      xrotation = θ,
      bottom_margin = 15mm,
      left_margin = 5mm)
    png("bug-$θ")
  end
  return
end
```

**Comment by BioTurboNick** [comment]
I'll give it some thought.

**Comment by BioTurboNick** [comment]
What if it uses any angle other than 0, 90, 180, 270 positions the corner at the tick? 
![image](https://user-images.githubusercontent.com/1438610/131237615-b38774b8-237e-4132-b630-56ea5fcbfaf4.png)

**Comment by t-bltg** [comment]
Isn't that what's currently done ?

I was thinking of maybe increasing offset based on rotation: https://github.com/JuliaPlots/Plots.jl/blob/8b6073c08806c371e76d065bc7e7da282bbfcb11/src/backends/gr.jl#L1564

**Comment by BioTurboNick** [comment]
What's currently being done is switching between centering the tick on the middle of the top, to centering the tick on the middle of the side. Like so:
![image](https://user-images.githubusercontent.com/1438610/131257608-c66c0b47-687b-40e7-820a-e8577b04156f.png)

**Comment by t-bltg** [comment]
Ha yeah, wrote this PR 2 months ago and already forgot what I did :laughing:.

Some possible fix:
```julia
trigger(rot) = abs(sind(rot)) < .25 ? 0 : sign(rot)
```

**Comment by BioTurboNick** [comment]
There's probably a simpler way to write this but this is a little more general for all rotations I think:

```
rot = axis[:rotation] % 360
    if letter === :x || (RecipesPipeline.is3d(sp) && letter === :y)
        if -90 < rot < 90 || rot < -270 || rot > 270
            valign = axis[:mirror] ? :bottom : :top
        elseif abs(rot) % 90 == 0 # -270, -90, 90, 270
            valign = :vcenter
        else
            valign = axis[:mirror] ? :top : :bottom
        end

        if 0 < rot < 360
            halign = axis[:mirror] ? :left : :right
        elseif abs(rot) % 180 == 0 # -180, 0, 180, 360
            halign = :hcenter
        else
            halign = axis[:mirror] ? :right : :left
        end
    else
[...]
```

**Comment by BioTurboNick** [comment]
Suggest this modification to look at y axis and mirrored axes simultaneously.

```
main() = begin
  days = 31
  position = cumsum(randn(days)) .* 10000
  x = Date(2018, 1, 1):Day(1):Date(2018, 1, 31)
  ticks = [x[i] for i in 1:5:length(x)]

  for mir ∈ [true, false]
  for θ ∈ 0:10:120
    plot(
      x, position,
      xlabel = "Date",
      ylabel = "Position",
      title = "Track of random walker",
      xticks = ticks,
      xrotation = θ,
      yrotation = θ,
      xmirror = mir,
      ymirror = mir
    )
    png("bug-$θ-$mir")
  end
  return
end
```

**Comment by t-bltg** [comment]
> There's probably a simpler way to write this but this is a little more general for all rotations I think:

Looks good, explicit is sometimes more readable. Can you make a PR out of it ?

Suggested changes writing `if` clauses:
```julia
valign = if -90 < rot < 90 || rot < -270 || rot > 270
    axis[:mirror] ? :bottom : :top
elseif abs(rot) % 90 == 0 # -270, -90, 90, 270
    :vcenter
else
    axis[:mirror] ? :top : :bottom
end

[...]
```

**Comment by BioTurboNick** [comment]
I'm not sure how the reference images work, where do I start with that?

**Comment by t-bltg** [comment]
> I'm not sure how the reference images work, where do I start with that?

See https://github.com/JuliaPlots/PlotReferenceImages.jl#installation.
And then https://github.com/JuliaPlots/PlotReferenceImages.jl#usage.

Submit a PR to https://github.com/JuliaPlots/PlotReferenceImages.jl with the modified reference images.
