### ISSUE TITLE
[FR] Pass along additional PyPlot args (markevery)

### ISSUE THREAD

**Issue by gzheng92** [JuliaPlots/Plots.jl#3785]
PyPlot has additional arguments that `Plots.jl` doesn't seem to support.  In particular, I'd like to be able to use the `markevery` optional argument from PyPlots.  As an example:

```
using Plots
using PyPlot
pyplot()
# default(fontfamily="cmr10")

xVec = 0.0:0.01:1.0
Plots.plot(xVec, exp.(xVec), markevery = 0.2, marker=(6,2), legend=false)

PyPlot.figure();
PyPlot.plot(xVec, exp.(xVec), markevery = 0.2, marker=(6,2))
PyPlot.gcf()
```

There should only be 5 marked points, but `Plots` marks every data point.

**Comment by isentropic** [comment]
Please provide some docs, about this keyword from matplotlib, and given enough upvotes we can consider this

**Comment by gzheng92** [comment]
Here is the gallery from matplotlib explaining use cases of markevery: https://matplotlib.org/stable/gallery/lines_bars_and_markers/markevery_demo.html

Reading through, it's very "loose" about what the cases do, to the point that implementing it exactly in Plots for other backends seems excessive.  But for the case of pyplot's backend, can it just be passed along?

**Comment by isentropic** [comment]
I think it is best not to consider this, if you need it badly, you could write a recipe, that would skip a few points, or just preprocess your data manually.
