### ISSUE TITLE
[BUG] Scatter has problems with scalar data

### ISSUE THREAD

**Issue by BambOoxX** [JuliaPlots/Plots.jl#3792]
## Details

For some reason, I may need to plot some scalar data using `scatter` in 2D and 3D. 
However, with the following examples I get either an empty plot or a failure. 
```julia
using Plots
scatter(1,2,3) # <-- shows and empty plot with 3 legends
scatter(1.,2.,3.) # <-- fails with message "ERROR: Cannot convert Float64 to series data for plotting"
scatter([1],[2],[3]) # <-- works as expected (but is cumbersome)
```
This seem to lie before backend action.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |x
plotly       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
inspectdr    |     |     |x

### Versions

Plots.jl version: 1.21.3
Backend  version (`]st -m <backend(s)>`): N/A
Output of `versioninfo()`:
>Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, tigerlake)

**Comment by BeastyBlacksmith** [comment]
Same as https://github.com/JuliaPlots/Plots.jl/issues/2129
