### ISSUE TITLE
xaxis=false or showxaxis=false does not seem to work anymore [BUG?]

### ISSUE THREAD

**Issue by Marco-Congedo** [JuliaPlots/Plots.jl#3798]
## Details

I used to use argument `xaxis=false` in `Plot`, but it does not seem to work anymore once i upgraded **Plots.jl**.
I have tried `showxaxis=false` and it doesn't make it either.

### Backends

GR

i didn't test the other backends, but i'd like to use GR

### Versions

Plots.jl version: Plots v1.21.3
Output of `versioninfo()`: 1.6.2

**Comment by BeastyBlacksmith** [comment]
it should be `xshowaxis` I think

**Comment by Marco-Congedo** [comment]
I tried and it does not work either

**Comment by BeastyBlacksmith** [comment]
It works for me, what do you expect it to do?
![xshowaxis](https://user-images.githubusercontent.com/18145188/132766175-2d97ab8a-f1c3-4937-bb69-99cd465a19a2.png)

**Comment by Marco-Congedo** [comment]
Not to show the number 1, 2, ... on the xaxis, but still to show the axxis line. This is what `xaxis=false` was doing before.

**Comment by BeastyBlacksmith** [comment]
You can get that meanwhile with `xticks = nothing`

**Comment by Marco-Congedo** [comment]
OK thanks

**Comment by BeastyBlacksmith** [comment]
> This is what `xaxis=false` was doing before

Do you happen to know on which Version that was?

**Comment by Marco-Congedo** [comment]
Uhm, sorry i don't have the version in mind.
It was at least 3 months old, maybe more.
I was running julia v1.4.2
