### ISSUE TITLE
[FR] Load and edit old plots

### ISSUE THREAD

**Issue by casasgomezuribarri** [JuliaPlots/Plots.jl#3799]
I'm pretty sure this is not possible right now... Please someone correct me if I'm wrong.

It is very annoying to go and check your saved plots from the last session only to realise there is a typo in one of the axis labels, the legend, or the title. It would be great to be able to save the plots in a format that also stores the instructions for creating them, so that they can be retrieved and modified.

I use Julia for data science. A feature like this would allow me, for example, to train several instances of a model saving the coefficient plots for all of them; and then come back later, recover all those plots and superpose them to get an average coefficient plot.

**Comment by isentropic** [comment]
This is already the case, as far as I know

**Comment by isentropic** [comment]
```
p = plot(...)  # old plot
p2 = plot(...) # new plot
display(p) # recover the old one
```

**Comment by isentropic** [comment]
And then, you could explicitly `plot!(p, ....)` to modify it

**Comment by isentropic** [comment]
2 options
1. serialize your plots object into a file along the image,
2. Use some graphical editing like gimp

**Comment by isentropic** [comment]
Better yet, keep the data in a file and keep the script to plot the graph. This is not something Plots should do

**Comment by BeastyBlacksmith** [comment]
Also check out the hdf5 backend

**Comment by t-bltg** [comment]
You cannot modify the final `png`. You have to store the intermediate `Plots` object.
@isentropic is right this is a [`Serialization`](https://docs.julialang.org/en/v1/stdlib/Serialization/) job:

Session 1
```julia
$ julia
julia> using Plots, Serialization
julia> p = plot([1, 2])
julia> serialize("/tmp/foo", p)
```

Session 2
```julia
$ julia
julia> using Plots, Serialization
julia> p = deserialize("/tmp/foo")
julia> Plots.CURRENT_PLOT.nullableplot = p  # optionally set the current plot
julia> savefig(p, "/tmp/foo.png")
```

Bu keep in mind that this reuses your old data. Keep data separate from the plotting script, and rerun the plotting script on new data when your model has produced new data.
