### ISSUE TITLE
[BUG] `backend` keyword has no effect

### ISSUE THREAD

**Issue by fonsp** [JuliaPlots/Plots.jl#3805]
## Details

What does the `backend` kwarg to the `plot` call control? I tried setting it to `"gr"`, `"GR"` and `gr` (the function), but nothing changes the backend used to display the output.

I am looking for a way to create a plot that will display in one backend, while keeping the default backend as-is.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     |     |
plotly       |  x  |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
inspectdr    |     |     |

### Versions

Plots.jl version: `v1.21.3`
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`: Julia 1.6.1

**Comment by BeastyBlacksmith** [comment]
Where did you get the impression from, that `backend` is a valid plot atrribute? You can see here, that it is treated as an extra_kwarg
```julia
julia> plot(1:10, backend=:gr) |> show
Plot{Plots.PGFPlotsXBackend() n=1}
Captured extra kwargs:
  Series{1}:
    backend: gr
```
The only function I know that accepts the `backend` keyword is `with` like
```julia
with(backend=:gr) do
 plot(1:5)
end
```

**Comment by fonsp** [comment]
Ah thanks! It did not throw an error, which made me think that the kwarg was supported, but not working.

**Comment by mkborregaard** [comment]
Plots by design never errors on wrong keywords. That allows graceful recipe handling.
