### ISSUE TITLE
[BUG] Keyword labelfontsize stopped working in version 1.22

### ISSUE THREAD

**Issue by fzierler** [JuliaPlots/Plots.jl#3823]
## Details

On version 1.22.0 the keyword "labelfontsize" stopped working and the second line in the MWE errors with `Unknown key: labelfontsize` . Previously (for example in version 1.21.3) the following adjusted the fontsize of the x- and y-labels.
```julia
using Plots
gr(labelfontsize=20)
scatter(rand(10),rand(10),xlabel="test")
```
When the keyword is used like `scatter(rand(10),rand(10),xlabel="test",labelfontsize=20)`, it is just ignored. I assume this is related to the recent changes in #3803 ?

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotly       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |  x   |     |
inspectdr    |     |     | x

### Versions

Plots.jl version: 1.22.0
Backend  version (`]st -m <backend(s)>`): GR v0.58.1
Output of `versioninfo()`:
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 4

**Comment by bernd1995** [comment]
Indeed you are right. The mentioned PR added only aliases for the separate `x`, `y` and `z` names like `xguidefontsize` but not for the one that is not specific to any axis. Should be a quick fix.
