### ISSUE TITLE
Categorical color palettes

### ISSUE THREAD

**Issue by axsk** [JuliaPlots/Plots.jl#383]
While the current gradient palettes `:inferno, :heat, :blues` are suited to plot sequential data, reflecting their ordererd structure, I propose adding additional "categorical" (name suggestions are welcome) palettes with presets of distuingishable colors.

Here are some suggestions that I stumbled upon looking for such palettes two years ago.
- Few (from Stephen Few, Show Me the Numbers)

![](http://67.media.tumblr.com/05de3c2f86260222f3fe2625396518a3/tumblr_inline_n8cnu0cwRy1sjw4gh.png)
- Set3 (from http://colorbrewer2.org) 

![](http://65.media.tumblr.com/a996c28c335f1d5b86c00d980a20dfb5/tumblr_inline_n8cnufTr061sjw4gh.png)
- Paired (from http://colorbrewer2.org) 

![](http://65.media.tumblr.com/1a26c63e4de693bd5dc86fadd9cbc0ce/tumblr_inline_n8cnu8DT1r1sjw4gh.png)
- Munsell interpretation of the [Twenty-Two Colors of Maximum Contrast by K. L. Kelly](http://www.iscc.org/pdf/PC54_1724_001.pdf)

![](http://67.media.tumblr.com/7f5254a1f2c390068c39762b7c23d7fd/tumblr_inline_n8cnuioX3O1sjw4gh.png)

The RGB values can be found in this [gist](https://gist.github.com/axsk/84e736e46cb5b0af3f4a).

Does anyone know if there are copyrights on colors?

Edit: Concerning the API I would suggest just adding new symbols for the palettes to the palette kwarg, i.e. `plot(..., palette=:set3)`. Given `n` series, I think these should get mapped to the first `n` sequential colors of the palette, since I consider the correct/distuingishable ordering to be the task of the palette (and as far as I remember above palettes took this into account)

**Comment by tbreloff** [comment]
I certainly like the idea of having some pre-defined palettes available.  We do have to be weary of copying without a proper license.  (yes, palettes can be copy-protected)

There are already several sources of "distinguishable palettes".  I think I'd like to make sure those can easily be used, and if we have pre-defined ones we could store in a Dict.

So the logic would be roughly:

```
if haskey(_categorical_palettes, v)
    # force color list
elseif # v is a color vector
    # force color list
elseif haskey(_gradients, v)
    # build palette from gradient
else
    # do the "distinguishable_colors method"
end
```

**Comment by mkborregaard** [comment]
I have opened an issue for enhanced color suppor in PlotUtils (where I think this stuff belongs) https://github.com/JuliaPlots/PlotUtils.jl/issues/3 . That issue is for gradients, but I agree that other sequential palettes also belongs naturally here, as part of color libraries (PR here https://github.com/JuliaPlots/PlotUtils.jl/pull/5) .
With regards to @axsk question of copyright, many gradients come with a reasonably permissive license, but most require attribution. Putting gradient libraries such as colorbrewer in PlotUtils allows the license to be displayed there.

**Comment by mkborregaard** [comment]
Closed in favour of https://github.com/JuliaPlots/PlotUtils.jl/issues/3
