### ISSUE TITLE
matplotlib version requirements

### ISSUE THREAD

**Issue by oschulz** [JuliaPlots/Plots.jl#3833]
Plots now requires matplotlib >= v3.4.0 which is new than the current version shipped with Anaconda (matplotlib v3.3.4). One of our students ran into trouble with that today - if possible, we should try not to requrire versions that exceed a current Anaconda distro in the future, since many users do use Plots/PyCall with a separate Anaconda (which may be on shared storage on larger compute systems, so users also can't always update packages themselves).

**Comment by t-bltg** [comment]
Introduced by https://github.com/JuliaPlots/Plots.jl/pull/3793.

**Comment by isentropic** [comment]
@oschulz So, #3793 was introduced to combat this version mismatch. Now we've decided to have Plots support what is offerred by the anaconda, and its 3.4.2 right now

**Comment by isentropic** [comment]
See for yourself 
https://github.com/JuliaPlots/Plots.jl/blob/4d40bae9cc669bafcc06e80ad24acc0b5e187fd8/src/backends/pyplot.jl#L28

**Comment by isentropic** [comment]
Since it is a student you are dealing with, a fool proof solution is to ask them to reinstall Julia

**Comment by oschulz** [comment]
> Now we've decided to have Plots support what is offerred by the anaconda, and its 3.4.2 right now

You can get v3.4.2 via conda (anaconda repo)

https://anaconda.org/anaconda/matplotlib

but the official Anaconda distribution still comes with v3.3.4.

https://docs.anaconda.com/anaconda/packages/py3.8_linux-64/

Many users will use the "stock"/"official" Anaconda release, without manual upgrades.

> Since it is a student you are dealing with, a fool proof solution is to ask them to reinstall Julia

He's been doing Julia for years and is quite competent when it comes to package management. :-)

We do use central Anaconda installs, since we don't want every user to fill up their NFS homedir with the same 2GB of Anaconda - it's actually in a container, to allow for fast software distribution on our CephFS cluster storage (keeps metadata lookup on the clients with Singularity SquashFS images). The situation is similar on larger computing sites with shared/distributed file systems: Users are typically discouraged from installing stuff like Anaconda in their home dirs - instead, central installations (sometimes specially optimized on supercomputers) are provides via "modules" or containers.

#3793 is certainly important and we shouldn't revert it. For the future I would suggest that we be a bit more conservative though and not go beyond what the latest official Anaconda distro installs.

**Comment by oschulz** [comment]
CC  @daschw

**Comment by isentropic** [comment]
I understand this, but I thought it's more appropriate to support what Conda.jl provides. Your average novice user doesn't know what maplotlib version he's running or if it's Conda.jl or not

**Comment by isentropic** [comment]
Simple instructions are to update conda JL and rebuild. I feel it's most valuable to get out of the way and adhere to defaults. Power user like yourself can figure the issue right away, and should understand why we should focus on supporting only conda.jl version

**Comment by isentropic** [comment]
Regarding being conservative, i think supporting only the latest stale matplotlib is fairly conservative. And I mean full support, I'm sure versions > 3.0 work just fine except for a few minor features.

**Comment by t-bltg** [comment]
> Many users will use the "stock"/"official" Anaconda release, without manual upgrades.

Especially true for students which usually enter into the `Python` / `Julia` world at this stage, and for which the notion of compiler, dependencies, shared libraries is vague.

> We do use central Anaconda installs, since we don't want every user to fill up their NFS homedir with the same 2GB of Anaconda

This is an argument, IMO `conda` installs usually eat up more space compared to `julia`.

> Regarding being conservative, i think supporting only the latest stable matplotlib is fairly conservative.

Supporting a `latest` version is not what I'd call conservative.

> It's version you get doing pip install of matplotlib

The package handling with `Python` can become tricky (hence the number of handlers: `pip`, `conda` (`condaforge`, `anaconda` repos), `poetry`,`conan` or might require more rights, ...). In my experience breaking a `conda` installation with updates happens frequently.

> For the future I would suggest that we be a bit more conservative though and not go beyond what the latest official Anaconda distro installs.

I think it's something reasonable to ask, and I believe we should follow this guideline in the future.

**Comment by oschulz** [comment]
> Power user like yourself can figure the issue right away

But power users would still like to be able to use the current version of Plots in environments where it's preferable to use a system-wide anaconda installation (for example because user-level installs can be slow on compute clusters, since network/cluster file systems don't perform well when accessing large numbers of small files) :-)

In such environments, software containers or other deployment forms will be updated when there's a new Anaconda release, but not when there's a Julia Plots.jl release.

**Comment by isentropic** [comment]
I'm a little confused about conda and Anaconda. Doesn't [this](https://anaconda.org/conda-forge/matplotlib) page mean that currenly anaconda provides 3.4.3?

Anyways, I'm strongly in favor to primarily support what Conda.jl offers, just for the sake of new users who have no idea what is conda python or mpl. More knowledgable people will figure out how to install appropriate mpl version

**Comment by isentropic** [comment]
I see that you agree that Plots.jl should support what is offered by Conda.jl. Regarding the new features, I agree that we should hold off to offer a wider range of supported mpl versions. Your message is noted for future upgrades
