### ISSUE TITLE
[BUG] Makers always on top

### ISSUE THREAD

**Issue by fredifqh** [JuliaPlots/Plots.jl#3842]
## Details

I am doing two plots in one. First I do a scatter plot (background) and then a scatter plot with error bars. The figure show the plot, but the error bar is shown behind the background scatter plot.

### Backends

This bug occurs on 

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotlyjs     |     |     |
pgfplotsx    |  x |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version: Plots v1.22.1
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by BeastyBlacksmith** [comment]
Thats just how pgfplots does its rendering, it always puts markers on top. I don't think there is anything I can do about it
