### ISSUE TITLE
Plots look very small on HiDPI screens

### ISSUE THREAD

**Issue by ma-sadeghi** [JuliaPlots/Plots.jl#3850]
Both the window size and the font size appear to be too small on 4K screens. Is there a settings that I can change? Thanks! Here's a screenshot:
![image](https://user-images.githubusercontent.com/14086031/134967348-db48f7dc-c3e3-42da-b093-23f1ea16e7da.png)

**Comment by BeastyBlacksmith** [comment]
you can think of putting
```julia
using Plots
default(size=(1200,800))
```
in your `startup.jl`

**Comment by ma-sadeghi** [comment]
@BeastyBlacksmith Great thanks! that increase the window size, but the font size is still small, is there a settings for that too?

**Comment by BeastyBlacksmith** [comment]
You can add `scalefontsizes(2)`

**Comment by isentropic** [comment]
You could also add 

`default(size=(1200,800), thickness_scaling=2)`

**Comment by ma-sadeghi** [comment]
Thanks so much! It worked just fine! There's only one remaining issue: when I change the default settings to `(1200,800), thickness_scaling=2`, plots look just fine on `GKS QtTerm`, but they look massive in vscode's Plots panel, and vice versa (using  `Plots.jl`'s default settings, plots look fine in vscode's Plots panel, but tiny on `GKS QtTerm`). Is there a way to make it consistent?

**Comment by BeastyBlacksmith** [comment]
In the vscode extension you can add `--startup-file=no` to `julia.additionalArgs`

**Comment by ma-sadeghi** [comment]
Thanks. That could work, but I do want vscode to load the startup file as I have other stuff in there.

**Comment by BeastyBlacksmith** [comment]
```julia
if !@isdefined VSCodeServer
    default(...)
end
```

**Comment by ma-sadeghi** [comment]
I tried it but it seems that `VSCodeServer` is loaded after `startup.jl` :disappointed:, but thanks for your effort anyway.

**Comment by BeastyBlacksmith** [comment]
You might have more luck in the `vscode` channel on the julia slack
