### ISSUE TITLE
[BUG] using vline results in wrong ylim

### ISSUE THREAD

**Issue by Volker-Weissmann** [JuliaPlots/Plots.jl#3866]
## Details
```julia
using Plots
p = plot()
vline!(p, [2])
plot!(p, [1,2,3], [-0.1, -0.2, -0.3])
savefig(p, "bug.pdf")
```
![bug](https://user-images.githubusercontent.com/39418860/136299323-4257ee99-b736-486c-98d6-2080d5a26032.png)

The y-axis goes from -0.35 to 2, but it should go from -0.35 to 0. If you swap the order of the `vline!` and the `plot!` call, it works.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x    |     |
pyplot       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: Plots v1.15.2
Backend  version (`]st -m <backend(s)>`):  GR v0.57.4
Output of `versioninfo()`:
```
Julia Version 1.6.3
Commit ae8452a9e0* (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Comment by Volker-Weissmann** [comment]
I could also guess that the origin was vline defaulting to [1,2].
I can't tell you how to fix the bug, without knowledge about Plots.jl architecture.

**Comment by pablosaa** [comment]
I found an apparently new bug using vline and DateTime format in the x-axis: 
`plot(rs[:time], tir[:IRT], size=(800,300))`
![image](https://user-images.githubusercontent.com/24556480/217926409-dd862767-3b2f-4339-b3a7-5f08378f39ce.png)

but when adding a vline as :
`vline!([DateTime(2020,4,15, 12)])`
it changes the y-axis label as shown below:
![image](https://user-images.githubusercontent.com/24556480/217926498-45620fd0-d3fc-4b23-9ff8-9e87c7189ee4.png)

I can confirm that I've worked with vline() and DateTime as x-axis data format regularly before and it used to work flawlessly before updating Plots.jl to v1.38.4 , for Julia Version 1.8.0

**Comment by t-bltg** [comment]
Could you please open a new issue ?

**Comment by AraujoH** [comment]
I'm facing the same issue @pablosaa is facing. Adding a `vline!` with `DateTime` x-axis results in a change of values in the y-axis.

**Comment by pablosaa** [comment]
> I'm facing the same issue @pablosaa is facing. Adding a `vline!` with `DateTime` x-axis results in a change of values in the y-axis.

@AraujoH you might want to update Plots.jl to version 1.38.16 or the latest 1.38.17, where that issue has been solved.
