### ISSUE TITLE
[BUG] Can't plot two vectors at the same when one only has missing elements 

### ISSUE THREAD

**Issue by eirikbrandsaas** [JuliaPlots/Plots.jl#3867]
## Details
```julia
using Plots
# Plot missings
x = 1:3
y1 = [1,1,2]
y2 = [missing,missing,missing]
Y = [y1 y2]

plot(x,y1)
plot(x,y2)
plot!(x,y1)
plot(x,[y1 y2]) # fails
plot(x,Y) # fails
```
Note the weird thing that it works when you do it with the `plot!()` syntax, but not if you plot them at the same time. The last two gives `ERROR: MethodError: convert(::Type{Union{}}, ::Float64) is ambiguous. Candidates:`

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x    |     |
pyplot       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version:` [91a5bcdd] Plots v1.22.2`
Backend  version:` 28b8d3ca] GR v0.59.0`
Output of `versioninfo()`: 
```Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_DEPOT_PATH = /sftwr/user-pkg/m1eeb00/julia
  JULIA_PKG_SERVER = pkg.julialang.org
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 6
  JULIA_BINDIR = /apps/julia/current/bin/frb
```

**Comment by t-bltg** [comment]
Can't reproduce anymore.
