### ISSUE TITLE
[BUG] animation displayed wrong marker color

### ISSUE THREAD

**Issue by comphilano** [JuliaPlots/Plots.jl#3871]
## Details

The color of markers is supposed to be red instead of black.  It's only happening in the animation when the GIF is created. The images in the temporary directory are still corrected.

```julia
using Plots
using Random 

n = 5

mypoint = (rand(1:10, n), rand(1:10, n))
mybool = []

push!(mybool, BitVector(undef, n))
push!(mybool, bitrand(n))

anim = @animate for v in mybool
    scatter(mypoint, markersize=10, c = map(x -> x ? :red : :green, v))
end

gif(anim, "point.gif", fps=1)
```

![Alt Text](https://media.giphy.com/media/6sSNMEVWMFRcvV0Jlv/giphy.gif)
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: Plots v1.22.4
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:

Julia Version 1.6.2
Commit 1b93d53fc4* (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, ivybridge)

**Comment by nick4f42** [comment]
I checked, and the palette that's created in the temporary directory does only have green and gray colors. [This line](https://github.com/JuliaPlots/Plots.jl/blob/b959e64b9c189c1e5383582f7d1963a27e76c975/src/animation.jl#L101) makes the palette with ffmpeg, setting the option `palettegen=stats_mode=diff`. Creating the palette with `stats_mode=full` ([the default](https://ffmpeg.org/ffmpeg-filters.html#palettegen-1)) seems to fix the issue. Is there a strong reason why `stats_mode` should stay on `diff`?

**Comment by BeastyBlacksmith** [comment]
As far as I can tell this was done in https://github.com/JuliaPlots/Plots.jl/pull/1242. I think its fair to change, if we solve the issue at hand with it.
