### ISSUE TITLE
[BUG] Plots.jl requiring UnicodePlots.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#3877]
I am really confused but can you please explain why UnicodePlots.jl is now a dependency?

```julia
 Warning: Error requiring `UnicodePlots` from `Plots`
│   exception =
│    LoadError: UndefVarError: UserColorType not defined
```

Who is maintaining Plots.jl and making such decisions?

**Comment by t-bltg** [comment]
> Why is it an optional dependency? I know it is loaded with Requires.jl but why? Why people need UnicodePlots.jl in Plots.jl?

It's a [backend](http://docs.juliaplots.org/latest/generated/unicodeplots/), as `GR` or `PyPlot` are (see http://docs.juliaplots.org/latest/backends/).

**Comment by t-bltg** [comment]
> I'm assuming the error above and warning is not related to this dependency cycle then. I'll try to find out why UnicodePlots.jl is at an old version.

Try:
```julia
(@v1.6) pkg> add UnicodePlots@2
```
, and it will show you which package is preventing the upgrade, if any.
