### ISSUE TITLE
GR dependency conflicts

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#3892]
## Details
GR sees a conflict between the QTCore library it puts into Julia artifacts and the same library installed by miniconda as part of miniconda Python. Note that the message only appears once at the first plot. The first plot appears correct. Subsequent plots are created without repeating the message. So even if the choice is undetermined, Plots or GR rolls their dice and makes a choice that works.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x    |     |
pyplot       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version:  v1.22.6
Backend  version (`]st -m <backend(s)>`):  gr v0.61.0
Output of `versioninfo()`:
```
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by lewisl** [comment]
Below is an example of the output this produces. Note that both this version of Python and Plots with GR are installed with Pkg and Conda (in the case of Python and matplotlib and all its many dependencies). So, this is results from following the prescribed way of installing everything.

```
objc[35895]: Class RunLoopModeTracker is implemented in both /Users/lewis/.julia/conda/3/lib/libQt5Core.5.9.7.dylib (0x18b124a80) and /Users/lewis/.julia/artifacts/d594d9e68b9d104aaf1a41d933728d2dad54c869/lib/QtCore.framework/Versions/5/QtCore (0x1b1ff9aa8). One of the two will be used. Which one is undefined.
objc[35895]: Class QCocoaPageLayoutDelegate is implemented in both /Users/lewis/.julia/conda/3/lib/libQt5PrintSupport.5.9.7.dylib (0x18bfdfef0) and /Users/lewis/.julia/artifacts/d594d9e68b9d104aaf1a41d933728d2dad54c869/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x1b1124480). One of the two will be used. Which one is undefined.
objc[35895]: Class QCocoaPrintPanelDelegate is implemented in both /Users/lewis/.julia/conda/3/lib/libQt5PrintSupport.5.9.7.dylib (0x18bfdff40) and /Users/lewis/.julia/artifacts/d594d9e68b9d104aaf1a41d933728d2dad54c869/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x1b11244f8). One of the two will be used. Which one is undefined.
```

**Comment by isentropic** [comment]
What about standalone `GR`? Does it display the same error?
