### ISSUE TITLE
Gaston backend fails to plot simple example

### ISSUE THREAD

**Issue by zornsllama** [JuliaPlots/Plots.jl#3913]
## Details

I have tried to plot the example given in the Plots.jl documentation for the Gaston backend. This throws two warnings and an error stating the key :legend is not found.

`using Plots; gaston();
 plot(1:10)`

Error message and traceback:
┌ Warning: Keyword argument fillcolor not supported with Plots.GastonBackend().  Choose from: Set([:yticks, :top_margin, :lims, :group, :background_color, ... :connections])
└ @ Plots ~/.julia/packages/Plots/LSKOd/src/args.jl:1608
┌ Warning: Keyword argument markerstrokecolor not supported with Plots.GastonBackend().  Choose from: Set([:yticks, :top_margin, :lims, :group, :background_color, ... :connections])
└ @ Plots ~/.julia/packages/Plots/LSKOd/src/args.jl:1608
Error showing value of type Plots.Plot{Plots.GastonBackend}:
ERROR: KeyError: key :legend not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:482 [inlined]
  [2] getindex(dd::RecipesPipeline.DefaultsDict, k::Symbol)
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/Bxu2O/src/utils.jl:18
  [3] getindex(sp::Plots.Subplot{Plots.GastonBackend}, k::Symbol)
    @ Plots ~/.julia/packages/Plots/LSKOd/src/args.jl:1838
  [4] gaston_set_legend!(axesconf::Vector{String}, sp::Plots.Subplot{Plots.GastonBackend}, any_label::Bool)
    @ Plots ~/.julia/packages/Plots/LSKOd/src/backends/gaston.jl:508
  [5] gaston_parse_axes_args(plt::Plots.Plot{Plots.GastonBackend}, sp::Plots.Subplot{Plots.GastonBackend}, dims::Int64, any_label::Bool)
    @ Plots ~/.julia/packages/Plots/LSKOd/src/backends/gaston.jl:434
  [6] gaston_init_subplot(plt::Plots.Plot{Plots.GastonBackend}, sp::Plots.Subplot{Plots.GastonBackend})
    @ Plots ~/.julia/packages/Plots/LSKOd/src/backends/gaston.jl:167
  [7] gaston_init_subplots(plt::Plots.Plot{Plots.GastonBackend}, sps::Matrix{Any})
    @ Plots ~/.julia/packages/Plots/LSKOd/src/backends/gaston.jl:140
  [8] _before_layout_calcs(plt::Plots.Plot{Plots.GastonBackend})
    @ Plots ~/.julia/packages/Plots/LSKOd/src/backends/gaston.jl:31
  [9] prepare_output(plt::Plots.Plot{Plots.GastonBackend})
    @ Plots ~/.julia/packages/Plots/LSKOd/src/plot.jl:217
 [10] display(#unused#::Plots.PlotsDisplay, plt::Plots.Plot{Plots.GastonBackend})
    @ Plots ~/.julia/packages/Plots/LSKOd/src/output.jl:147
 [11] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:328
...
`

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |   x  |     |

### Versions

Plots.jl version: 
  [91a5bcdd] Plots v1.23.2

Backend  version (`]st -m <backend(s)>`):
  [4b11ee91] Gaston v1.0.4

Output of `versioninfo()`:
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by isentropic** [comment]
Can report if standalne gaston works fine?

**Comment by zornsllama** [comment]
> Can report if standalne gaston works fine?

Hi, yes. Standalone Gaston seems to work fine.

**Comment by isentropic** [comment]
It must be that the latest update with legends was breaking
I will try to get this soon

**Comment by BeastyBlacksmith** [comment]
Yeah, that PR predated the Gaston backend https://github.com/JuliaPlots/Plots.jl/commit/1fe9a9f536b25d86598da478ec137dd1cdc161e3 fixed this
