### ISSUE TITLE
[BUG] Latex no longer rendering with v1.23.5

### ISSUE THREAD

**Issue by ConnectedSystems** [JuliaPlots/Plots.jl#3925]
## Details
Not sure what happened but latex is no longer rendering correctly for me with GR, both with and without LaTeXStrings

```julia
using Plots, LaTeXStrings

# These all produce the same result
plot(1:1000, yscale=:log10, title="\$x^{10}\$")

plot(1:1000, yscale=:log10, title=L"x^{10}")

plot(1:1000, yscale=:log10, title=latexstring("x^{10}"))
```

![image](https://user-images.githubusercontent.com/4075136/140259260-e25c7d9d-5860-44ce-b1f0-d44d265fd60c.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: v1.23.5
Backend  version (`]st -m <backend(s)>`):  GR v0.62.1
Output of `versioninfo()`:

Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by ConnectedSystems** [comment]
Update

Works as expected under Plots v1.23.2 and GR v0.61.0

**Comment by BeastyBlacksmith** [comment]
@jheinen can you have a look?

**Comment by jheinen** [comment]
Please ensure that you are really using `GR.jl` 0.62.1 and the `GR` run-time 0.62.0 (`GR.version()`).

**Comment by ConnectedSystems** [comment]
If I update to Plots.jl v1.23.5, the `GR.jl` is 0.62.1, but running `GR.version()` returns `0.58.1`

If I downgrade to v1.23.2 and GR v0.61.0 and call `GR.version()`, it also gives "0.58.1".

**Comment by jheinen** [comment]
Once you have updated to `GR.jl` v0.62.1, could you please try `ENV["GRDIR"]=""; ] build GR` ?

**Comment by ConnectedSystems** [comment]
```julia
pkg> update

Updating registry at `C:\[...]\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Installed PDMats ─ v0.11.3
Updating `C:\[...]\Project.toml`
  [91a5bcdd] ↑ Plots v1.23.2 ⇒ v1.23.5
Updating `C:\[...]\Manifest.toml`
  [28b8d3ca] ↑ GR v0.61.0 ⇒ v0.62.1
  [90014a1f] ↑ PDMats v0.11.2 ⇒ v0.11.3
  [91a5bcdd] ↑ Plots v1.23.2 ⇒ v1.23.5
  [1cfade01] + UnicodeFun v0.4.1

# restarted REPL here

julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

julia> ENV["GRDIR"]=""; 

julia> ]build GR
   Building GR → `C:\[...]\GR\SOvTP\deps\build.log`

julia> plot(1:1000, yscale=:log10, title="\$x^{10}\$")  # still same issue

# restarted REPL again

julia> using Plots

julia> GR.version()
"0.58.1"

julia> ENV["GRDIR"]
""

```

**Comment by jheinen** [comment]
Could you please enable debugging and show the `build.log` file?
```
% env JULIA_DEBUG=GR julia
] build GR
```

**Comment by jheinen** [comment]
If you are using BinaryBuilder, you should also ensure, that `GR_jll` is up-to-date.

**Comment by ConnectedSystems** [comment]
Hi @jheinen 

I assume `% env JULIA_DEBUG=GR julia` is linux specific?

I did:

```bash
julia> ENV["JULIA_DEBUG"] = "GR"
] build GR
Building GR → `C:\[...]\GR\SOvTP\deps\build.log`
```

Contents of the indicated file is:

```
┌ Info: Creating depsfile. GR provider is BinaryBuilder
│   provider = "BinaryBuilder"
└   depsfile = "C:\\[...]\\.julia\\packages\\GR\\SOvTP\\deps\\deps.jl"
```

Not sure if how I set that env variable is correct though.

**Comment by jheinen** [comment]
Then you should update `GR_jll`, too (should be 0.62.0).

**Comment by ConnectedSystems** [comment]
Sorry, could you provide some more direction on how to do that? I don't have GR_jll directly installed in this environment, although I understand its a dependency of Plots.jl

running `] update GR_jll` simply raises a `package names could not be resolved` error.

**Comment by ConnectedSystems** [comment]
I tried:

```bash
] rm Plots

] add Plots GR GR_jll
pkg> add Plots GR GR_jll
  Resolving package versions...
Updating `C:\[...]\Project.toml`
  [28b8d3ca] + GR v0.62.1
  [d2c73de3] + GR_jll v0.58.1+0
No Changes to `C:\[...]\Manifest.toml`

pkg> update
   Updating registry at `C:\[...]\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
No Changes to `C:\[...]\Project.toml`
No Changes to `C:\[...]\Manifest.toml`

pkg> update GR_jll@0.62.0
   Updating registry at `C:\[...]\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
No Changes to `C:\[...]\Project.toml`
No Changes to `C:\[...]\Manifest.toml`

**Comment by jheinen** [comment]
One of your packages prevents the update of `GR_jll`. Unfortunately, I can't reproduce this on our systems ...

**Comment by BeastyBlacksmith** [comment]
Could also be an outdated registry

**Comment by ConnectedSystems** [comment]
> Could also be an outdated registry

As I can tell Plots.jl is the only package depending on GR_jll. 

I've also created an empty project and installed Plots, and only Plots, and get the same behavior - GR_jll stays at 0.58.1

**Comment by jheinen** [comment]
As a workaround, you could use "our" binaries:
```julia
ENV["JULIA_GR_PROVIDER"] = "GR"
] add Plots
] add GR
```
and then check if everything is up-to date:
```julia
using GR
check_for_updates()
```

**Comment by ConnectedSystems** [comment]
Hi @jheinen 


```
(plot_test) pkg> remove Plots GR LaTeXStrings

julia> ENV["JULIA_GR_PROVIDER"] = "GR"
] add Plots
] add GR

julia> GR.check_for_updates()
An update is available: GR v0.62.0. You're using GR v0.58.1.
true

(plot_test) pkg> st -m GR_jll
Status `C:\programs\ownCloud\projects\hydro_projects\plot_test\Manifest.toml`
  [d2c73de3] GR_jll v0.58.1+0

(plot_test) pkg> update GR
   Updating registry at `C:\[...]\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
No Changes to `C:\[...]\plot_test\Project.toml`
No Changes to `C:\[...]\plot_test\Manifest.toml`

julia> ENV["JULIA_GR_PROVIDER"]
"GR"

(plot_test) pkg> st -m GR
Status `C:\programs\ownCloud\projects\hydro_projects\plot_test\Manifest.toml`
  [28b8d3ca] GR v0.62.1

(plot_test) pkg> st -m GR_jll
Status `C:\programs\ownCloud\projects\hydro_projects\plot_test\Manifest.toml`
  [d2c73de3] GR_jll v0.58.1+0

julia> GR.check_for_updates()
An update is available: GR v0.62.0. You're using GR v0.58.1.
true
```

Am I doing something wrong?

**Comment by jheinen** [comment]
I guess some dependency prevents the update of `Plots.jl`. Could you try to add `Plots`, `GR` and `LaTeXStrings` in a newly created fresh environment? I'd assume, that works and then you'll have to check the other deps.

**Comment by ConnectedSystems** [comment]
Unfortunately this is in a new environment created specifically for this issue.

Let me try on a completely different computer and see if I get the same behavior though.

**Comment by jheinen** [comment]
Is there an existing GR installation on you computer (`$HOME/gr`, `/usr/local/gr`, `/usr/gr`)? What's the value of `ENV["GRDIR"]`?

**Comment by t-bltg** [comment]
Cannot reproduce.
