### ISSUE TITLE
[BUG] Legend in Scatter Plot with small `markersize` is scaled wrong

### ISSUE THREAD

**Issue by roflmaostc** [JuliaPlots/Plots.jl#3945]
Hi!

The following

```
scatter(randn((10,)), randn((10,)), markersize=0.1)
```
results in broken legends:

![](https://felix.sumpi.org/Screenshot_2021-11-18_18-50-17.png)

and
```
scatter(randn((10,)), randn((10,)), markersize=0.01)
```
![](https://felix.sumpi.org/Screenshot_2021-11-18_18-50-32.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |  x   |     |
plotlyjs     |     |  x   |
pgfplotsx    |    |  x   |

Didn't test further

### Versions
```
  [8314cec4] PGFPlotsX v1.4.1
  [91a5bcdd] Plots v1.23.6
  [d330b81b] PyPlot v2.10.0
```

```
julia> versioninfo()
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by isentropic** [comment]
This is not really a bug, but perhaps we should not allow markersizes less than 1, the backend is trying to draw a tiny markersize (less than a pixel) which results in such a singularity.

```
scatter(rand(10), markersize=1, msw=0)
```
works very well for me
