### ISSUE TITLE
[BUG] Using Plots with plotly backend only shows white.

### ISSUE THREAD

**Issue by chrisoffner** [JuliaPlots/Plots.jl#3967]
## Details
When I use Plots with the plotly backend, I get only a white area. It works fine if I use `gr()` instead, see image:
![](https://i.imgur.com/N78lhme.jpg)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pyplot       |     |     | x
plotlyjs     |  x   |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: v1.24.4
Backend  version (`]st -m <backend(s)>`): v0.18.8
Output of `versioninfo()`:
```
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.1.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```

What can I do to make this work?

**Comment by BeastyBlacksmith** [comment]
Can you try Plots v.1.24.3 ?

**Comment by chrisoffner** [comment]
@BeastyBlacksmith Sorry for the beginner question but how do I do that? I tried
```julia
]rm Plots
]add Plots@1.24.3
```
and `Pkg.status()` then shows me
```
  Status `~/.julia/environments/v1.7/Project.toml`
  [b8a86587] NearestNeighbors v0.4.9
  [58dd65bb] Plotly v0.4.1
  [a03496cd] PlotlyBase v0.8.18
  [f0f68f2c] PlotlyJS v0.18.8
  [91a5bcdd] Plots v1.24.3
  [c3e4b0f8] Pluto v0.17.2
  [7f904dfe] PlutoUI v0.7.21
  [37e2e46d] LinearAlgebra
  [10745b16] Statistics
```
but when I run `Pluto.run()` I still get

```
From worker 3:	      Status `/private/var/folders/52/7c2g08dx6k1fjgr5f5c3h9mr0000gn/T/jl_96XgPH/Project.toml`
      From worker 3:	  [91a5bcdd] Plots v1.24.4 ❗️
      From worker 3:	  [44cfe95a] Pkg
      From worker 3:	[ Info: For saving to png with the Plotly backend PlotlyBase has to be installed.

```

**Comment by chrisoffner** [comment]
When I instead use the REPL and do
```julia
julia> import Pkg; Pkg.status()
      Status `~/.julia/environments/v1.7/Project.toml`
  [b8a86587] NearestNeighbors v0.4.9
  [58dd65bb] Plotly v0.4.1
  [a03496cd] PlotlyBase v0.8.18
  [f0f68f2c] PlotlyJS v0.18.8
  [91a5bcdd] Plots v1.24.3
  [c3e4b0f8] Pluto v0.17.2
  [7f904dfe] PlutoUI v0.7.21
  [37e2e46d] LinearAlgebra
  [10745b16] Statistics

julia> using Plots; plotly()
Plots.PlotlyBackend()

julia> plot([1,2,3], [1,4,9])
```
I do get a browser window that shows me a functioning plot:

<img width="752" alt="Screenshot 2021-12-01 at 19 09 51" src="https://user-images.githubusercontent.com/18167754/144289686-b9ba83a0-cbbc-4f0b-a3b9-83af346f008a.png">

**Comment by t-bltg** [comment]
@jks-liu, can you check if this a regression induced by https://github.com/JuliaPlots/Plots.jl/pull/3958 ?

**Comment by chrisoffner** [comment]
Okay, when I force my Pluto notebook to use Plots v1.24.3 it works as expected. It does seem like v1.24.4 is the culprit here.

**Comment by jks-liu** [comment]
I'll check this.
