### ISSUE TITLE
[FR] xlims [ ] or () 

### ISSUE THREAD

**Issue by bienpierre** [JuliaPlots/Plots.jl#3986]
Dear all,

First of all, thanks for the great work about Plots.jl.

I did not find the difference between [ ] or ( ) with xlims. 

I performed the comparison, one plot with [ ] and the second with ( ):

![plots_Fr](https://user-images.githubusercontent.com/50803547/145054958-77871ecb-cf92-47fd-a483-f4a128fe8e52.png)

The results are
p1) xlims = [-2, 2]: ![p1](https://user-images.githubusercontent.com/50803547/145055361-f7ad95ef-8f59-4892-9814-19cd17e8370d.png)

p2) xlims = (-2, 2): ![p2](https://user-images.githubusercontent.com/50803547/145055381-08ed1022-eef5-45e2-b0a1-5eb1564a0444.png)

xlims = [-2, 2] is accepted but the result is vague. 
Why does xlims is allowed with [ ] and not returning an error?

Regards

code: 
```

using Plots
gr()

x = randn(1000);
y = randn(1000);

x1 = sort(x, rev = true);
y1 = sort(y, rev = true);

minimum(x1)
maximum(x1)

p1 = plot(x1,y1, legend = :false, xlims = [-2,2])
	        xgrid!(p1, :on, :black, 5, 0.4)

savefig("./p1.png")


p2 = plot(x1,y1, legend = :false, xlims = (-2,2))
	        xgrid!(p2, :on, :black, 5, 0.4)

savefig("./p2.png")
```

**Comment by BeastyBlacksmith** [comment]
It seems to me like `xlims = [-2,2]` behaves like `xlims = (-2,2), widen = true`

**Comment by BeastyBlacksmith** [comment]
The behaviour should now that https://github.com/JuliaPlots/Plots.jl/pull/3989 is merged be consistent
