### ISSUE TITLE
[BUG] can't display dollar currency symbol as y-axis label 

### ISSUE THREAD

**Issue by mdkeehan** [JuliaPlots/Plots.jl#3991]
## Details
When I run the following code:
```julia
using Plots
plot(rand(3,5),ylabel="profits \$")
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error
```
while the euro unicode symbol will work beautifully
```
plot(rand(3,5),ylabel="profits €")
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     |x
plotlyjs     |     |   x  |
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version:
Plots v1.25.1

Output of `versioninfo()`:
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by mdkeehan** [comment]
Some more experiments:
```julia
julia> plot(rand(3,5),ylabel=raw"profits $")
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error

julia> plot(rand(3,5),ylabel=raw"profits $")
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error
ERROR: syntax error

julia> GR.plot(rand(3,5),ylabel=raw"profits $")
ERROR: syntax error
ERROR: syntax error

julia> GR.plot(rand(3,5),ylabel="profits \$")
ERROR: syntax error
ERROR: syntax error

julia> GR.plot(rand(3,5),ylabel=raw"profits $")
ERROR: syntax error
ERROR: syntax error
```
A work around was too embed unusual unicodes characters that look like dollars but I then run into fonts supporting glyph problems. 
It looks like Plots "interpolates" 5 times while calling GR directly interpolates only twice.

**Comment by mdkeehan** [comment]
plottlyjs() works correctly.
```julia
julia> plotlyjs()
Plots.PlotlyJSBackend()

julia> plot(rand(3,5),ylab="profits \$")

julia> gr()
Plots.GRBackend()
```

**Comment by BeastyBlacksmith** [comment]
@jheinen: Anything we can do about it?

**Comment by jheinen** [comment]
Right now (with the GR development branch), the only workaround is to use `plot(rand(3,5),ylab="profits \$\$")`. I have to admit, that looks odd. I (have to) think of something better.

**Comment by ShuhuaGao** [comment]
When some more words follow `\$`, then no error is reported. However, the dollar symbol is not rendered and disappears.
```julia
using Plots
plot(rand(3,5),ylabel="profits \$/kWh", size=(500, 200))
```
![temp](https://user-images.githubusercontent.com/20141984/148681563-251efa95-6160-44b1-9fa7-23654a57b5b0.png)

In the above, it seems that "kWh" was treated as in an equation environment.

As @jheinen  mentioned, `plot(rand(3,5),ylabel="profits \$\$/kWh", size=(500, 200))` works well.

**Comment by jheinen** [comment]
This problem is fixed in the GR development tree. We will tag a new GR release ASAP.

**Comment by t-bltg** [comment]
Fixed by https://github.com/sciapp/gr/commit/f37dfaaf67ce7512a2ceb2d8d88c64465c4fca35.

**Comment by mcmuffin6o** [comment]
So how do I put dollar signs in axis labels now that this is "fixed"? As of now, `xlabel=raw"$t$ (seconds)"` produces some LaTeX-ified t followed by " (seconds)". I want a literal "$t$ (seconds)" as plaintext so that I can save the figure as svg with `fontfamily=""` so that I can typeset the axis labels when I include the svg in my LaTeX document.
