### ISSUE TITLE
Discussion on naming for 3D series recipes

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#400]
Spurred on by #392 and jheinen/GR.jl#31, Tom and I had a long discussion in the Gitter about the definitions of "surface" and "mesh". Let me try to summarize it here:
- In Tom's view, a surface has an axis where there are no overlaps. For example, a 3D surface is made by points (x,y,z) where each (x,y) has exactly 1 z, i.e. (x,y)->z
- These trisurf plots require that once specify the triangular mesh whenever the region is not convex. An example is given in #392. 
- I was pointing out that one common use for these is in [finite element methods](https://en.wikipedia.org/wiki/Finite_element_method). There are multiple Julia projects, such as [DifferentialEquations.jl](https://github.com/ChrisRackauckas/DifferentialEquations.jl), [JuliaFEM](http://www.juliafem.org/), [EllipticFEM](https://github.com/gerhardtulzer/EllipticFEM.jl), [HPFEM](https://github.com/pjabardo/HPFEM.jl), etc. for finite elements (and many more packages like [Fenics](https://fenicsproject.org/) in C/Fortran). In these examples, what's usually plotted is a solution over a mesh. For example, a 2D finite element method uses a trisurf to plot a 2D mesh with 1D solutions (x,y)->z, such as the charge density at each point, or the protein concentration at each point.
- The common naming scheme then has an issue when going to 4D: in MATLAB a 2D mesh with 1D solution is plotted with trisurf, but a 3D mesh with a 1D solution, though very similar, is plotted with [tetramesh](http://www.mathworks.com/help/matlab/ref/tetramesh.html).
- There is a difference between the underlying structure and the representation for it. The 2D mesh + 1D solution can be represented as a surface, though other representations such as a heatmap or wireframe are sensible. 
- For these reasons, it may be sensible to abstract this away from just "trisurf" to some kind of plotting of meshes.
- This doesn't handle all cases of meshes. All of this discusses cases where the number of nodes in a mesh is 1 more than the dimension. For example, a triangle is defined by 3 points, so a 2D mesh can be represented by a matrix with rows `[node1 node2 node3]` where each node is given by `(x,y)`. If one supplies a mesh like this and a value `z` for each node, this gives a 3D structure (x,y)->z which satisfies Tom's definition of "surface". However, if the nodes themselves are triangles in 3D space (x,y,z), then this is a different kind of mesh where the "exactly 1 z per (x,y)" may not be satisfied (the surface of a sphere).

What's the most sensible way to organize the plotting of these 3D structures denoted by triangular meshes? I am not set on any definition, just bringing up common uses, previous implementations, and how they relate.

**Comment by mkborregaard** [comment]
@ChrisRackauckas is this issue still live?

**Comment by ChrisRackauckas** [comment]
I don't think so, if Plots.jl wants to follow the naming scheme that other plotting packages use here.

**Comment by mkborregaard** [comment]
You don't think it's live or you don't think it can be closed?

**Comment by ChrisRackauckas** [comment]
What do you think here? I thought Plots.jl should use `surface` and `trisurf` the same way that things like PyPlot, Plotly, GR, etc. use it, but Tom disagreed and said that the explicit use of triangles in things like FEM plots:

https://github.com/JuliaPlots/Plots.jl/issues/392#issuecomment-234579313

shouldn't be called a `trisurf` and is instead a form of a `surface` (though I will point out that the underlying PyPlot etc. commands will be `trisurf` calls). Your call on whether this is important or should be done.

**Comment by mkborregaard** [comment]
I'd need a bit of time to read up on it. Currently I'm just doing a tally of open Plots issues. Thanks for responding :-)
