### ISSUE TITLE
Colorbar location is too far for 3D plots under pyplot backend

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaPlots/Plots.jl#4017]
I am wondering whether we can control the location of placing a colorbar in any 3D plots under the pyplot backend. I want to move the colorbar a bit to the left so that the ticks and numbers of the colorbar are visible. This problem does not happen in the GR and plotlyjs backends. My setup is the latest ones of all these packages, i.e., Julia: v1.7.1; Plots: v1.25.3; PyPlot: v2.10.0. 
As @BeastyBlacksmith suggested in https://discourse.julialang.org/t/colorbar-cutoff-in-plots-jl-with-pyplot/48178  the following command: ` plot(..., right_margin = 3Plots.mm)`, but for this 3D plot, this trick  does not work. This only shifts the main figure to the left without moving the colorbar location.

Here is a MWE:
```
x = y = collect(range(-π, π, length = 100))
fn(x, y) = begin
    3 * exp(-(3x^2 + y^2)/5) * (sin(x+2y))+0.1*randn(1)[1]
end
surface(x, y, fn, c=:viridis)
```
Here is the actual figure.
![plot_2](https://user-images.githubusercontent.com/2894576/147479850-1e5ec246-fe8d-4ac7-a2a2-607eb174face.png)

**Comment by isentropic** [comment]
I added a new extra kw for 3d colorbar control
`surface(x, y, fn, c=:viridis, extra_kwargs=Dict(:subplot=>Dict("3d_colorbar_axis" => [0.85, 0.1, 0.03, 0.8]) ) )` should be slightly better

**Comment by isentropic** [comment]
Do you mind documenting this here?
https://docs.juliaplots.org/latest/backends/#[PyPlot](https://github.com/stevengj/PyPlot.jl)

**Comment by BoundaryValueProblems** [comment]
@isentropic , thanks a lot for your help. But it changed almost nothing in my case. The colorbar location did not change.

**Comment by isentropic** [comment]
Those are just matplotlib bounding  boxes passed directly (without Plots auto-resizing)
Something like in here https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subplots_adjust.html#sphx-glr-gallery-subplots-axes-and-figures-subplots-adjust-py
```
rect[left, bottom, width, height]
```
    The Axes is built in the rectangle rect. rect is in Figure coordinates.
taken from here https://matplotlib.org/stable/api/axes_api.html#inheritance

**Comment by BoundaryValueProblems** [comment]
@isentropic , thanks a lot! I just added the section in the Plots document as you suggested, and generated my pull request: https://github.com/JuliaPlots/PlotDocs.jl/pull/265 
Please check the contents and revise it if necessary.
Thanks a lot!

**Comment by isentropic** [comment]
No problem! For pyplot, you could mention me to add more as long as someone is willing to do docs
