### ISSUE TITLE
[BUG] Missing coordinates in PyPlot gui window

### ISSUE THREAD

**Issue by marlloseff** [JuliaPlots/Plots.jl#4019]
## Details
The coordinates (x,y) are not indicated when using Plots; pyplot().
![g2786](https://user-images.githubusercontent.com/33531557/147680712-dced805a-67e0-43b8-9e0a-5219567fa907.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |   x  |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version: v1.25.3 (several previous versions)
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:
Julia Version 1.7.1  (several previous versions)
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
OS: Linux (x86_64-pc-linux-gnu)
CPU: Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

**Comment by marlloseff** [comment]
Using only PyPlot, the coordinates are shown. However, using Plots; pyplot(); the coordinates are missing.

`
# file 1 - example 1

using PyPlot

function test()
	x = range(-π, π, length=100)
	plot(x, sin.(x)) # ok, show coordinates
end

test()


# file 2 - example 2

using Plots; pyplot()

function test()
	x = range(-π, π, length=100)
	plot(x, sin.(x)) # missing coordinates
end

test()
`

**Comment by isentropic** [comment]
It is not a Plots bug, rather a decision to provide custom ticks. Use `ticks=:native` to overcome this, reopen if persists

**Comment by marlloseff** [comment]
> It is not a Plots bug, rather a decision to provide custom ticks. Use `ticks=:native` to overcome this, reopen if persists

It works! Since you are showing x=,y= you could show the values of x and y by default, this is always useful.
