### ISSUE TITLE
[BUG] c=:black doesn't work in contour under pyplot backend

### ISSUE THREAD

**Issue by laughingrice** [JuliaPlots/Plots.jl#4020]
## Details

With the contour function under the PyPlot backend, the c=:black (line color) option throws an error. It works fine in GR and PlotlyJS, and also works under the plot function with the PyPLot backend, so I'm guessing there is a different line color selection path between contour and plot

code to replicate:

```julia
x = LinRange(-1,1,1000);
contour(x.^2 .+ x'.^2, c=:black)
```

works as expected under the GR and PlotlyJS backend, but throws the following error with the PyPlot backend: 

```julia
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: MethodError: no method matching get_colorscheme(::RGBA{Float64})
Closest candidates are:
  get_colorscheme(::PlotUtils.AbstractColorList) at /Users/micha/.julia/packages/PlotUtils/xekml/src/colorschemes.jl:4
  get_colorscheme(::AbstractVector{var"#s33"} where var"#s33"<:Colorant) at /Users/micha/.julia/packages/PlotUtils/xekml/src/colorschemes.jl:303
  get_colorscheme(::AbstractVector{T} where T) at /Users/micha/.julia/packages/PlotUtils/xekml/src/colorschemes.jl:304
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pyplot       |   x  |     | 
plotlyjs     |     |  x   |
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: 1.25.4
Backend  version (`]st -m <backend(s)>`): 2.10.0
Output of `versioninfo()`:

Julia Version 1.6.5
Commit 9058264a69* (2021-12-19 12:30 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by isentropic** [comment]
I don't think this is a bug at all. It is strange that GR allows it, cause its clearly not the right thing to plot contour using only a single color.
Look at https://docs.juliaplots.org/latest/generated/colorschemes/
You want to use:
`contour(x.^2 .+ x'.^2, cgrad=:grays) # or contour(x.^2 .+ x'.^2, c=:grays)`

**Comment by isentropic** [comment]
I'm not sure why GR even allows it in the first place, but hey I guess some people want the gradient from a single color?
