### ISSUE TITLE
Broken Pipe: Plotting with Julia Version 1.7.1 (2021-12-22)

### ISSUE THREAD

**Issue by Wintereinbruch** [JuliaPlots/Plots.jl#4024]
Before I give up on Julia within the first hour.

Has this been solved: https://github.com/JuliaPlots/Plots.jl/issues/2451

I installed Julia and experience the same problem (M1 MacBook Pro).

Not a very good start if I am honest:

julia> using Plots

julia> x = 1:10; y = rand(10);

julia> plot(x, y)

julia> plot(x, y)

julia> plot(x, y)
send: Broken pipe
send: Broken pipe
send: Broken pipe

julia> plot(x, y)

julia> plot(x, y)

julia> plot(x, y)
send: Broken pipe
send: Broken pipe
send: Broken pipe

julia> plot(x, y)

julia> plot(x, y)

julia> plot(x, y)
send: Broken pipe
send: Broken pipe
send: Broken pipe

julia> plot(x, y)

julia> plot(x, y)

...

**Comment by Wintereinbruch** [comment]
**Also matplotlib is not working:**

Plots.PyPlotBackend()

julia> plot(rand(4,4))
┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = npyinitialize() at numpy.jl:67
└ @ PyCall ~/.julia/packages/PyCall/L0fLP/src/numpy.jl:67
sys:1: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

julia> plot(rand(4,4))
sys:1: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

1. **And nothing from here works**: https://github.com/JuliaPy/PyPlot.jl/issues/418

2. **Then there is this discussion:** https://discourse.julialang.org/t/non-gui-backend-so-cannot-show-the-figure/28445 

But conda cannot install pyqt5: conda install -c dsdale24 pyqt5

_If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that._

**Is plotting with Julia possible at all?**

**Comment by Wintereinbruch** [comment]
Conda is able to install pyqt5 for Python > 3:

conda install -c conda-forge pyqt

But still Julia doesn't do anything:

julia> using PyPlot

julia> pygui(true)
true

julia> plot(rand(4,4))
4-element Vector{PyCall.PyObject}:
 PyObject <matplotlib.lines.Line2D object at 0x13f7bf430>
 PyObject <matplotlib.lines.Line2D object at 0x13f7bf460>
 PyObject <matplotlib.lines.Line2D object at 0x13f7bf580>
 PyObject <matplotlib.lines.Line2D object at 0x13f7bf6a0>

julia> plt.show()
sys:1: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

**Comment by Wintereinbruch** [comment]
**To be fair here:**

saving a figure would work (https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so):

julia> plt.savefig("./name.png")

**Comment by Wintereinbruch** [comment]
I give up.

Plotting doesn't work.  A total mess.

Good luck getting the Python data science community to switch over to Julia:

julia> ENV["PYTHON"]="/opt/anaconda3/bin/python"
"/opt/anaconda3/bin/python"

julia> using Pkg

julia> Pkg.add("PyCall")
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [438e738f] + PyCall v1.93.0
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`
Precompiling project...
  46 dependencies successfully precompiled in 27 seconds (84 already precompiled)

julia> Pkg.add("PyPlot")
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`

julia> using PyPlot
[ Info: Installing PyQt5 via the Conda pyqt package...
[ Info: Running `conda install -y pyqt` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyqt

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


ERROR: InitError: failed process: ... "DISPLAY=/private/tmp/com.apple.launchd.DXxZWQyDrJ/org.xquartz:0", ... "OPENBLAS_MAIN_FREE=1", "PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:531 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:446
  [3] run
    @ ./process.jl:444 [inlined]
  [4] runconda(args::Cmd, env::String)
    @ Conda ~/.julia/packages/Conda/1403Y/src/Conda.jl:130
  [5] add(pkg::String, env::String; channel::String)
    @ Conda ~/.julia/packages/Conda/1403Y/src/Conda.jl:223
  [6] add (repeats 2 times)
    @ ~/.julia/packages/Conda/1403Y/src/Conda.jl:222 [inlined]
  [7] pyimport_conda(modulename::String, condapkg::String, channel::String)
    @ PyCall ~/.julia/packages/PyCall/L0fLP/src/PyCall.jl:713
  [8] pyimport_conda
    @ ~/.julia/packages/PyCall/L0fLP/src/PyCall.jl:707 [inlined]
  [9] find_backend(matplotlib::PyCall.PyObject)
    @ PyPlot ~/.julia/packages/PyPlot/XaELc/src/init.jl:91
 [10] __init__()
    @ PyPlot ~/.julia/packages/PyPlot/XaELc/src/init.jl:193
 [11] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
 [12] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
 [13] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
 [14] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
 [15] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
during initialization of module PyPlot

caused by: PyError (PyImport_ImportModule

The Python package PyQt5 could not be imported by pyimport. Usually this means
that you did not install PyQt5 in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the PyQt5 module, you can
use `pyimport_conda("PyQt5", PKG)`, where PKG is the Anaconda
package that contains the module PyQt5, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'PyQt5'")

Stacktrace:
  [1] pyimport(name::String)
    @ PyCall ~/.julia/packages/PyCall/L0fLP/src/PyCall.jl:550
  [2] pyimport_conda(modulename::String, condapkg::String, channel::String)
    @ PyCall ~/.julia/packages/PyCall/L0fLP/src/PyCall.jl:708
  [3] pyimport_conda
    @ ~/.julia/packages/PyCall/L0fLP/src/PyCall.jl:707 [inlined]
  [4] find_backend(matplotlib::PyCall.PyObject)
    @ PyPlot ~/.julia/packages/PyPlot/XaELc/src/init.jl:91
  [5] __init__()
    @ PyPlot ~/.julia/packages/PyPlot/XaELc/src/init.jl:193
  [6] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
  [7] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
  [8] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
  [9] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
 [10] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997

julia> pyimport_conda("PyQt5", PKG)
ERROR: UndefVarError: pyimport_conda not defined
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1

julia> using Conda
 │ Package Conda not found, but a package named Conda is available from a registry. 
 │ Install package?
 │   (@v1.7) pkg> add Conda 
 └ (y/n) [y]: y
   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [8f4d0f93] + Conda v1.6.0
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`

julia> Conda.add("PyQt5")
[ Info: Running `conda install -y PyQt5` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyqt5

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


ERROR: failed process: ... "OPENBLAS_MAIN_FREE=1", "PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:531 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:446
 [3] run
   @ ./process.jl:444 [inlined]
 [4] runconda(args::Cmd, env::String)
   @ Conda ~/.julia/packages/Conda/1403Y/src/Conda.jl:130
 [5] add(pkg::String, env::String; channel::String)
   @ Conda ~/.julia/packages/Conda/1403Y/src/Conda.jl:223
 [6] add (repeats 2 times)
   @ ~/.julia/packages/Conda/1403Y/src/Conda.jl:222 [inlined]
 [7] top-level scope
   @ REPL[9]:1

**Comment by isentropic** [comment]
I mean you can't sh*t on people who've maintaining this thanklessly and expect prompt 1to1 person helping you while running tier 3 Julia support platform (m1 Mac). 

Your current attitude wouldn't solve your problem. I say if you don't like it don't use it.

**Comment by Wintereinbruch** [comment]
Good morning

Great attitude from the Julia community. It is called ’supercilious behaviour’.

Blaming me and claiming I am not interested in a solution.

It is actually true: the Julia community seems to be quite hostile (I am not the first one who received this kind of attitude). Over Xmass I read quite a few posts (but didn’t have enough data left on my pay as you go abroad to download and install Julia) which now confirms my observation. Came back two days ago and thought ‘hey let’s install Julia’.

If you think this helps Julia adoption. More power to you.

I will stick with Python.



Regards,
Siegfried

**Comment by Wintereinbruch** [comment]
I deleted my response as this should go on private email communication and will lead to nothing.

It would really help if there is a clear communication that (Julia) plotting is obviously not supported on the OSX platform.

**Comment by mkborregaard** [comment]
I am on a Mac (currently M1) and have used Plots essentially flawlessly for years.
@Wintereinbruch which julia version are you using? You should probably still be using the "Intel or Rosetta" binary from the julia download page, as the ARM architecture is not yet supported natively on many of the binary dependencies used by e.g. conda.

**Comment by Wintereinbruch** [comment]
Hi

I admit I haven’t fully tested Julia but base Julia  seems to be working. Also the ’time to the first plot’ wasn’t too bad. Nothing like what is written on the net. My main development machine is not my Macbook (it is Linux at work) but I often test things on my Macbook because our Linux work environment is heavily controlled (I cannot easily install new software).

I downloaded Julia 1.7.1 (2021-12-22) for Apple M1 and when I start Julia I see the following:

Last login: Wed Jan  5 20:54:04 on ttys007
exec '/private/var/folders/w9/gklj07416x9g3wmt5_4f4p840000gn/T/AppTranslocation/71FE7ED0-BAF0-4F7D-9C0F-EFFF1420ACEE/d/Julia-1.7.app/Contents/Resources/julia/bin/julia'
(base)  ~ % exec '/private/var/folders/w9/gklj07416x9g3wmt5_4f4p840000gn/T/AppTranslocation/71FE7ED0-BAF0-4F7D-9C0F-EFFF1420ACEE/d/Julia-1.7.app/Contents/Resources/julia/bin/julia'
 

The Python is:

Python 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin


And my system:

MacBook Pro 13”,  M1 processor, macOS Big Sur 11.6.1

Actually I am not planning to use Julia in the REPL. I will use Julia from the command line and write code in Emacs. Most of the plots will be saved to files. I never use Python or Jupiter interactively (sometimes for testing short numpy constructs and very rarely for making live plots). But even using Python from the command line (e.g. python foo.py) it often helps during the development process to see plot output on the screen.

**Comment by mkborregaard** [comment]
Yeah, try going here https://julialang.org/downloads/#current_stable_release and downloading the binary called "macOS x86 (Intel or Rosetta)".
Adapting to new processor architectures are always a massive challenge for open-source community projects - julia will get there (https://github.com/JuliaPackaging/Yggdrasil/issues/2763) but it takes time.

**Comment by isentropic** [comment]
I suggest you to just use a different backend like plotly or even unicode:
https://docs.juliaplots.org/latest/backends/

**Comment by Wintereinbruch** [comment]
Hi: I will report back here how things are going on OSX. Will try it out over the coming weekend.

**Comment by Wintereinbruch** [comment]
This is for the Julia "macOS x86 (Intel or Rosetta)" 64-bit version.

(See at the end where I tested it on PyPlot and Plots).

I haven't tested it with the Julia M1 version because there is only one ~/.julia directory and they might mess up (as the old saying goes: never touch a working system).

My system:

1. MacBook Pro 13", M1, 2020, macOS BigSur 11.6.1
2. Python 3.8.8, [Clang 10.0.0 ], Anaconda, Inc. on darwin
3. Terminal Version 2.11 (440)

What I did:

1. Deleted my old  Julia directory in my home directory: "rm -r  ~/.julia"
2. Downloaded "macOS x86 (Intel or Rosetta)" from: https://julialang.org/downloads/
3. I then started Julia and my Terminal with Julia popped up
4. I found the following command here (https://github.com/JuliaPy/PyPlot.jl/issues/219) and typed it off: 

julia> ENV["PYTHON"]=""; Pkg.build("PyCall");using PyPlot

This as far as I understand will link from your local conda Python distribution to Julia.

(It could well be the case you have to add a few more packages but you then follow what Julia tells you on the Julia command line).

A few observations:

The following works without "broken pipes" error messages:

julia> using PyPlot
julia> dat = rand(10)
julia> plot(dat)
┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = npyinitialize() at numpy.jl:67
└ @ PyCall ~/.julia/packages/PyCall/L0fLP/src/numpy.jl:67
qt.qpa.drawing: Layer-backing can not be explicitly controlled on 10.14 when built against the 10.14 SDK
1-element Vector{PyCall.PyObject}:
 PyObject <matplotlib.lines.Line2D object at 0x167e16d30>

julia> plot(dat)
julia> plot(dat)


Note: The above warning only appears the first time round.

Now, you have to close Julia and start it again for testing the following. It seems to me you cannot load two Plot versions at the same time (plotting wouldn’t work at all):

julia> using Plots
julia> data = rand(10)
julia> plot(data)

It will plot. But if you close the plotting window and plot again it will result in "broken pipe" error messages. One way of avoiding the 'broken pipe error message'  would be using closeall() in front of the plot command:

julia> closeall(); plot(dat)

Also note: "using PyPlot" will result that the plot is send to the Matplotlib plotting window as fare as I can tell. The "using Plots" will plot in a "GKS QtTerm" output window (I have no idea what that is and where it comes from).

Next step will be trying to produce plot output to files by using Julia from the bash command line in script mode.

**Comment by Wintereinbruch** [comment]
Although it would still be important to understand what the following means:

┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = npyinitialize() at numpy.jl:67
└ @ PyCall ~/.julia/packages/PyCall/L0fLP/src/numpy.jl:67
qt.qpa.drawing: Layer-backing can not be explicitly controlled on 10.14 when built against the 10.14 SDK
1-element Vector{PyCall.PyObject}:
 PyObject <matplotlib.lines.Line2D object at 0x167e7fd30>

>

**Comment by Wintereinbruch** [comment]
I post it here maybe someone with macOS/OS X woes finds it useful: plotting in Julia script mode.

The following would also work from the command line on my M1 Macbook (see my Macbook systems specifications a few posts above):

testplot.jl:

using PyCall
@pyimport matplotlib.pyplot as plt
@pyimport numpy as np
x = np.linspace(0, 2*np.pi, 1000)
y = np.sin(3*x + 4 * np.cos(2*x))
plt.plot(x, y, color="red", linewidth=2.0, linestyle="--")
plt.title("A sinusoidally modulated sinusoid")
plt.show()
#or use: plt.savefig(“./test.png”)

And then in bash or Terminal the command line:

julia testplot.jl

I haven’t played around with speeding it up. But it only takes 3 seconds from firing it off at the command line and until the plot appears on the screen. Not too bad actually. Again nowhere near as bad as it is claimed (time for the first plot to materialise) on the all knowing internet.

>
