### ISSUE TITLE
How to extract subplot from a plot?

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaPlots/Plots.jl#4045]
I have a plot `p` containing 2 subplots. I want to modify the second subplot later in a function. How can I extract and display the subplot? I tried `p[2]` which shows `Subplot{2}`, but I don't know how to extract and modify it.

**Comment by iabraham** [comment]
I was wondering if this feature was ever added (and is maybe undocumented as of yet?). There are use cases: [for example](https://stackoverflow.com/q/75843396/6395452).

**Comment by t-bltg** [comment]
Is https://github.com/JuliaPlots/Plots.jl/blob/master/src/plot.jl#L274-L283 sufficient ?

**Comment by iabraham** [comment]
Indeed! Can't believe didn't think of trying that.
