### ISSUE TITLE
[BUG] x and y seem to get switched around in recipe

### ISSUE THREAD

**Issue by cjwyett** [JuliaPlots/Plots.jl#4047]
```julia
struct MyType
    x::Vector{Float64}
    y::Vector{Float64}
end

@recipe function mytypeplot(::Type{T}, mytype::T) where T <: MyType
    mytype.x, mytype.y
end

mytype = MyType([-2., -1., 0., 1., 2.], [1., 2., 3., 4., 5.])

plot(mytype, label="@recipe")
plot!(mytype.x, mytype.y, label="plot()")
```

I would expect the final 2 lines to plot the same thing. Only I get this:

 
![plot](https://user-images.githubusercontent.com/34195737/150094296-1a65b1cf-eb9c-4ed7-80d2-2d99839ed144.png)

**Comment by BeastyBlacksmith** [comment]
You should use a user recipe with the signature
```julia
@recipe function mytypeplot(mytype::T) where T <: MyType
    mytype.x, mytype.y
end
```
In the type recipe you have there the y-values are discarded, since it expects a single type whose recipe will be called  and in your case, that is the standard recipe thats used for e.g. `plot([-2, 1, 0, 1, 2])`
