### ISSUE TITLE
[FR] Filling horizontal regions across whole vertical axis range

### ISSUE THREAD

**Issue by tpgillam** [JuliaPlots/Plots.jl#4051]
I was looking to achieve something very similar to [this example from matplotlib](https://matplotlib.org/stable/gallery/lines_bars_and_markers/fill_between_demo.html#selectively-marking-horizontal-regions-across-the-whole-axes), whereby one can shade some horizontal extent.

I came up with the following:

```julia
function fill_xrange!(xmin, xmax; kwargs...)
    ymin, ymax = ylims()
    result = plot!([xmin, xmax], [ymin, ymin]; fillrange=[ymax, ymax], lw=0, kwargs...)
    ylims!((ymin, ymax))
    return result
end
```

... but this only is guaranteed to work if it is the last thing to be plotted (and even then it requires the rather dubious call to `ylims!` to undo the automatic zooming-out that will occur)

Is something better possible with the existing `Plots.jl` API, or would additional functionality be required?

(I marked this as a 'feature request', as I think even if it is possible, it'd be a useful example to add to the documentation!)

**Comment by BeastyBlacksmith** [comment]
You can get rid of the `ylims!` call if you add `widen = false` to the `plot!` call

**Comment by tpgillam** [comment]
Thanks! 

Is there also a way to change y range such that adapts if the axes were to widen through a subsequent `plot!` call? (I guess this is what the matplotlib example is trying to do by specifying the y extent in axes frame of reference, rather than the data frame of reference)

**Comment by BeastyBlacksmith** [comment]
I just rediscovered `vspan` which should give you that
```julia
julia> vspan([1,2])

julia> plot!(-5:5)
```

**Comment by tpgillam** [comment]
That looks ideal, thank you.

I notice that I can't find a reference to `vspan` or `hspan`  in the documentation — I'd be happy to make a short PR & example demonstrating its use, if you could indicate whereabouts would make most sense please?

**Comment by BeastyBlacksmith** [comment]
Easiest would probably to add an example in https://github.com/JuliaPlots/Plots.jl/blob/master/src/examples.jl.
A bit more effort would be to create an overview page of all recipes defined in Plots.jl

**Comment by tpgillam** [comment]
I don't have time to make an overview page of everything sadly (although this does sound like it'd be a great thing to have). Have just made a PR to add a small example for now.
