### ISSUE TITLE
[BUG] series_annotation does not slice correctly

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaPlots/Plots.jl#4073]
## Details

This shouldn't happen
```julia
using Plots
plot(rand(4,4), layout = 2, series_annotations = [1 2; 3 4])
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: type Array has no field baseshape
Stacktrace:
  [1] getproperty(x::Vector{Plots.SeriesAnnotations}, f::Symbol)
    @ Base ./Base.jl:42
  [2] series_annotations_shapes!(series::Plots.Series, scaletype::Symbol)
    @ Plots ~/.julia/packages/Plots/YAlrZ/src/components.jl:507
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: 1.25.7
Backend  version (`]st -m <backend(s)>`): 0.63.1

**Comment by nick4f42** [comment]
If anyone needs a quick workaround, you can replace `series_annotations=[1 3; 2 4]` with `permutedims([[1,2],[3,4]])`. I actually found this in `test/test_components.jl`. This doesn't work if you want to change the font or marker shape though.

I think I have the issue fixed, but I want to verify what behavior is expected with more complex arguments for `series_annotations`.

For example,
```jl
series_annotations = (["x", "y"], [10, 20], :hexagon)
```
Currently, this gives hexagon annotations "x" (with fontsize 10) and "y" (with fontsize 20) for every series. For multiple series, sensible ways of passing the data might be a tuple of matrices or a matrix of tuples:

1)
```jl
series_annotations = (["x" "a"; "y" "b"], [10 3; 20 4], [:hexagon :circle])
```
2)
```jl
series_annotations = [ (["x", "y"], [10, 20], :hexagon) (["a", "b"], [3, 4], :circle) ]
```
Should we support 1, 2, or both?

**Comment by BeastyBlacksmith** [comment]
I am in favor of option 2 here
