### ISSUE TITLE
[FR] Enable precompilation for nightly 

### ISSUE THREAD

**Issue by KristofferC** [JuliaPlots/Plots.jl#4079]
Developers of Julia use the time to load and create the first plot as a way of measuring latency. If the precompilation is not active on nightly that means that it will look like something has regressed even when this would not be the case if precompilation was available.

**Comment by t-bltg** [comment]
I'll have a look into that.

**Comment by t-bltg** [comment]
I am reopening this since `CompileBot` fails to update the precompilation files on nightly (job hangs), although I can generate them locally.

**Comment by timholy** [comment]
One option is to just skip the bot and move https://github.com/JuliaPlots/Plots.jl/blob/master/deps/SnoopCompile/precompile_script.jl into the definition of `Plots` itself.
