### ISSUE TITLE
[BUG] image tick positions drifting/ misplaced

### ISSUE THREAD

**Issue by sefffal** [JuliaPlots/Plots.jl#4087]
## Details
Tick positions for images are not placed correctly, at least with GR. The first pixel has a tick on the left, but the last pixel has it's tick on the right.  Between them, the ticks transition from one side of the pixels to the other.

First, here is a plot using heatmap that has the correct pixel locations:
```julia
heatmap(randn(10,15),ticks=1:15,color=:grey)
```
![image](https://user-images.githubusercontent.com/7330605/152051838-935a7ac2-ed3a-403f-a874-951ba0fb8639.png)

And an image series that does not:
```julia
plot(Gray.(randn(10,15)),ticks=1:15)
```
![image](https://user-images.githubusercontent.com/7330605/152051897-4de06a12-54ac-43b6-bee8-3bac2fa19a32.png)

Finally, here is an image of the same code using plotly thanks to @BioTurboNick where everything works as expected:
![image](https://user-images.githubusercontent.com/7330605/152052310-b86f8042-64e1-4679-bac3-cccc5c538f7f.png)

I came across this while working on AstroImages.jl. For us, getting ticks in the right portion of the pixel is important.
Happy to look into this myself if someone can point me in the right direction.

Thanks!

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotlyjs     |     | x    |
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: v1.25.4
Backend  version (`]st -m <backend(s)>`): GR v0.63.1
Output of `versioninfo()`:
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4

**Comment by BeastyBlacksmith** [comment]
Probably plotly is using the Plots recipe to use a heatmap for images, while GR has a dedicated implementation

**Comment by t-bltg** [comment]
> Happy to open a new issue if that's preferred.

Please do.
