### ISSUE TITLE
Display images on hover

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#409]
We can edit the hover text by passing in the `hover` attribute to a plot. I wonder how difficult it is to display an image on hover instead of text?

This feature would be extremely useful to people working with projections of objects onto the plane. Each dot is usually associated to an object (e.g. hand-written character, photograph, 3D shape) and being able to interactively see what is the object using the mouse would be awesome.

**Comment by tbreloff** [comment]
Sounds cool. I have no idea how feasible it is!

**Comment by juliohm** [comment]
What about the simpler solution in which we have two subplots side by side: the point cloud in the left and the a placeholder for the current image in the right. Is there a way to interactively retrieve the index of the point under the mouse and display/update the image in the right subplot?

**Comment by tbreloff** [comment]
Again very cool.  I highly doubt that this type of functionality will be built in to Plots.  However what we'd really like is a generic way to register arbitrary callbacks on hover (not just "display some text").  This functionality will vary a ton between backends.

**Comment by juliohm** [comment]
Totally agree, having just a way of registering callbacks would allow users to do fancy stuff with Plots regardless of the backend.

**Comment by tbreloff** [comment]
@simondanisch has been hard at work. Start the hype train...

https://vimeo.com/180199787

**Comment by juliohm** [comment]
That is awesome!!! This is gonna be incredibly useful to my research @tbreloff , thank you very much!

How can I use it? Some documentation already available? I also noticed that Plots.jl dropped Julia v0.4, I need to update to Julia v0.5 soon just because of this feature now.

**Comment by tbreloff** [comment]
I have no idea how to use it! Only @simondanisch holds the keys.

**Comment by juliohm** [comment]
He has the source code on the video, I just downloaded it, will try to play later when I get some work done in Julia v0.4. Unfortunately I cannot upgrade now because of other dependencies.

**Comment by juliohm** [comment]
What is the best current way to do this within `Plots.jl`?

**Comment by juliohm** [comment]
Closing this one as I think it will be part of Makie.jl
