### ISSUE TITLE
[BUG] legendfontsize not remembered anymore

### ISSUE THREAD

**Issue by schillic** [JuliaPlots/Plots.jl#4098]
## Details

There is a regression in v1.23.6 I think. The following two ways to change the legend font size used to work in v1.23.5.

```julia
using Plots

plot([1], [1], lab="R", legendfontsize=20)  # still works fine

plot(legendfontsize=20)  # first only set font size
plot!([1], [1], lab="R")  # plot! forgets font size in new version
```

### Backends

I only tried `GR` but kept the same version in both cases (v1.23.5 and v1.23.6).

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |  x | 
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: v1.23.6 and newer (I also tried the current v1.25.8)
Backend  version: `GR` v0.62.1 in both cases
Output of `versioninfo()`:
```
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, broadwell)
```

**Comment by BeastyBlacksmith** [comment]
I can reproduce this on GR, but not on PyPlot.
Also its not that the setting gets overridden or something as we can see here
```julia
julia> plot(legendfontsize=20)[1][:legend_font_pointsize]
20

julia> plot!([1], [1], lab="R")[1][:legend_font_pointsize]
20
```
@isentropic might this be related to #3855 ?

**Comment by isentropic** [comment]
The relevant PR is https://github.com/JuliaPlots/Plots.jl/pull/4055/files the changes were minimal, do you that's the version?

**Comment by schillic** [comment]
> * this change was introduced in https://github.com/JuliaPlots/Plots.jl/releases/tag/v1.25.7

Then it should not be that change because I see this behavior with v1.23.6 already.

**Comment by BeastyBlacksmith** [comment]
Seems it was me in e9ae75dfa49af60166cf586212de580f86d67957
