### ISSUE TITLE
[FR] UnitfulRecipes.jl as dependency?

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#4114]
Could this package be a dependency or maybe be ported fully to Plots.jl? I don't think users would complain about the additional Unitful.jl dependency in Plots.jl?

Can we get a all-batteries-included experience in terms of units without forcing users to load UnitfulRecipes.jl manually?

**Comment by BeastyBlacksmith** [comment]
Personally I am in favor of this. It should be noted that this adds ~0.2 seconds of using time making it ~3s in total for Plots on my machine.
@briochemc what is your opinion on this?

**Comment by briochemc** [comment]
Sorry for the delay, for some reason I did not get notified of this... 

I'm also in favor of this but I would like to note that there are a few rough edges that have not been ironed out (yet?) in UnitfulRecipes.

Pinging @jw3126 and @gustaphe too :)

**Comment by jw3126** [comment]
Thanks, @juliohm for bringing this up! To me the question really is how often do people want unitful plotting. Personally, I use it quite a bit, but it might be that 99.9% of julia users don't. I really have no idea. Can one get insight into this? Is there telemetry info about how often Plots.jl + Unitful.jl is simultaneously installed or something like that?

**Comment by juliohm** [comment]
Unitful.jl is a super lightweight dependency and I wonder if it wouldn't be
much easier for *end users* to just have these recipes added here.
Alternatively if they are just recipes, they could go into Unitful.jl
directly?

Em seg., 7 de mar. de 2022 04:43, Jan Weidner ***@***.***>
escreveu:

**Comment by jw3126** [comment]
> Unitful.jl is a super lightweight dependency

It does add 0.2s load time, I would not call this super lightweight.

> I wonder if it wouldn't be much easier for *end users* to just have these recipes added here.

I fully agree it would be very nice for end users if unitful plots worked out of the box. Probably many users of Plots + Unitful are not even aware that they can work together nicely.

**Comment by jw3126** [comment]
> Alternatively if they are just recipes, they could go into Unitful.jl
directly?

This is a very good suggestion. I imagine that most Plots.jl users don't use Unitful.jl, but that many (most?) Unitful.jl users also use Plots.jl .

**Comment by mkborregaard** [comment]
Yes that seems like the right design

**Comment by gustaphe** [comment]
Not sure `Unitful` will want to pull in even `RecipesBase` as a dependency, they are (rightfully) very proud of their light weight. I don't have a strong opinion on any of the options, I've gotten used to
```
using Unitful, Plots, UnitfulRecipes, Latexify, UnitfulLatexify
```

The best thing would of course be if the idea of native `Requires` actually happens.

**Comment by BeastyBlacksmith** [comment]
Would be good to hear the opinion of @ajkeller34 and @sostock
