### ISSUE TITLE
scatter3d camera angle limitations in GR

### ISSUE THREAD

**Issue by nlw0** [JuliaPlots/Plots.jl#4118]
Is this a limitation in GR itself? It seems strange that at least the azimuthal angle does not run from 0 to 360. With PyPlot it works at least.

https://github.com/JuliaPlots/Plots.jl/blob/e31d05682006b05eafd6be8ed25d449c4ef224c7/src/backends/gr.jl#L1438

**Comment by hurricane007** [comment]
Yes it's the limitation in GR
