### ISSUE TITLE
[FR] Font scaling with PGFPlotsX

### ISSUE THREAD

**Issue by hkraus94** [JuliaPlots/Plots.jl#4120]
Hi. I was trying out the PGFPlotsX backend to create plots for my LaTeX document.

My goal was to use `Plots.jl` with a different backend to interactively view my data and then use PGFPlotsX to save it as a `.tikz` file. My hope was that the scaling of fonts should be done in the LaTeX document. However, it seems that `savefig` exports a bunch of font and fontsize settings. It appears that the setting of width and height additionally affects the font sizes.

Is this the intended behavior of `savefig`? Are there any ways to store the figure without explicitly setting font sizes? If not, should that be a part of `Plots.jl`?

**Comment by BeastyBlacksmith** [comment]
Thats expected bahaviour and the only way right now to get rid of it is to postprocess the file, like
```julia
using Plots
pgfplotsx()
plot(1:5, title = "TESDT"); savefig("test.tikz")
strs = readlines("test.tikz")
open("test_rmed.tikz", "w") do io
        for line in strs
          println(io, replace(line, r"{\\fontsize.*\\selectfont}" => "{}")
       end
end
```

**Comment by BeastyBlacksmith** [comment]
Actually thanks to @willtebbutt since https://github.com/JuliaPlots/Plots.jl/pull/3154 its also possible to pass `nothing` to the fonts whose size should be determined by the document
