### ISSUE TITLE
[BUG]  "Send: no error" display when reopen a plot.

### ISSUE THREAD

**Issue by hungpham3112** [JuliaPlots/Plots.jl#4152]
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  X |     |
pyplot       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`): v1.27.0
Output of `versioninfo()`:
```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
```

I'm using REPL for learning script.

```julia
using Plots
x = (1:10, 2:20); y = rand(10, 20)
plot(x, y)
```
 After 3.928409 seconds compilation times and 10 seconds after that, the plot displayed.
Then I closed the plot and reopened it again and saw:
```julia
julia> plot(x, y)
send: No error
send: No error
```
I tried to reopen it second time and finally it worked. Is it a bug or expected behavior? How just to show the plot like normal but not show "send: No error"? Thanks for your help.

**Comment by t-bltg** [comment]
This should be reported to `GR.jl` or https://github.com/sciapp/gr.
