### ISSUE TITLE
Docs: Search results are hard to interpret for common search terms

### ISSUE THREAD

**Issue by IanButterworth** [JuliaPlots/Plots.jl#4157]
For `title`. Repetition and lack of a singular result that appears to match well.

<img width="1219" alt="Screen Shot 2022-03-27 at 8 38 31 PM" src="https://user-images.githubusercontent.com/1694067/160308575-7bb282cc-310e-44d1-b095-fe114563e7fe.png">

For `scatter`. I would've expected there to be a dedicated section on scatter plots?

<img width="1017" alt="Screen Shot 2022-03-27 at 8 41 16 PM" src="https://user-images.githubusercontent.com/1694067/160308680-84edf11a-d919-45a0-9da6-2c42270d8702.png">

**Comment by IanButterworth** [comment]
Also `padding`. The results don't seem to make sense

<img width="826" alt="Screen Shot 2022-03-27 at 9 40 36 PM" src="https://user-images.githubusercontent.com/1694067/160312391-28eb96b7-4654-4915-91b2-2057df77509f.png">

**Comment by BeastyBlacksmith** [comment]
For `scatter` and `padding` its just that we don't have sections for these. But I agree it would be nice, to only show the result of one example page in the results, but I don't know if you can register custom filters for the Documenter search

**Comment by t-bltg** [comment]
Seems to be a side effect of adding gallery https://github.com/JuliaPlots/PlotDocs.jl/pull/256:

search for `title`:
**1.25**
https://docs.juliaplots.org/v1.25/search/?q=title: Number of results: 53


**1.27**
https://docs.juliaplots.org/v1.27/search/?q=title: Number of results: 155

cc @johnnychen94 who might know how to tackle this.

**Comment by IanButterworth** [comment]
Also note that the backend contexts on the search results are lost on 1.27

**Comment by johnnychen94** [comment]
We might need to separate into the main doc and the gallery doc into two repositories and two Documenter builds.

- main doc: https://docs.juliaplots.org/v1.27
- gallery doc: https://docs.juliaplots.org/gallery/v1.27

with link `https://docs.juliaplots.org/v1.27/gallery` points to `https://docs.juliaplots.org/gallery/v1.27`.

**Comment by johnnychen94** [comment]
It is for the main doc, but you can still search the demos in the gallery doc. But TBH, I don't think it's more useful than a plain "Ctrl-F" search in the gallery doc.

**Comment by t-bltg** [comment]
For a beginner, it's mandatory to be able to land on the examples when issuing a `ctrl+f`. IMO, splitting into 2 docs is only gonna increase complexity.

**Comment by IanButterworth** [comment]
As an aside, if it helps, for julia base docs, google analytics was used to figure out the common search terms. It might be worth doing something similar to aid typical users searches, which are hard to gauge when you're a package developer IMO

**Comment by t-bltg** [comment]
Searching for `show_empty_bins`: `14` results with gallery duplicates down to `3` with no duplicates.
