### ISSUE TITLE
[BUG] Unable to use both error bars and zcolor on scatter plot.

### ISSUE THREAD

**Issue by thompsonmj** [JuliaPlots/Plots.jl#4186]
## Details
Using the same command from [#1032](https://github.com/JuliaPlots/Plots.jl/issues/1032), I can't have both `xerr` or `yerr` attributes and `zcolor`:

`scatter(1:2, [1,1], zcolor = [0,1], xerr = 0.05, markersize = 8, markerstrokewidth= 3)`

`ERROR: BoundsError: attempt to access 2-element Vector{Int64} at index [3]`

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |   x  |     | 
plotlyjs     |     |     | x 
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: `v1.27.6`
Backend  version (`]st -m <backend(s)>`):
`GR v0.64.2`
`PyPlot v2.10.0`
Output of `versioninfo()`:
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

**Comment by BeastyBlacksmith** [comment]
While this bug should get fixed a quick workaround is to give values for the errorbar-caps explicitly, like
`scatter(1:2, [1,1], zcolor = [0,1,0,0,1,1], xerr = 0.05, markersize = 8, markerstrokewidth= 3)`
