### ISSUE TITLE
Keyword argument fillstyle not supported with Plots.GRBackend()

### ISSUE THREAD

**Issue by bkamins** [JuliaPlots/Plots.jl#4190]
When I run code:
```
histogram(rand(1000); fillstyle= :/)
```
I get warning:
```
┌ Warning: Keyword argument fillstyle not supported with Plots.GRBackend().
```
but actually `fillstyle` is respected by GR backend.

**Comment by bkamins** [comment]
Thank you!

**Comment by BeastyBlacksmith** [comment]
Thanks for reporting 🙂

**Comment by bkamins** [comment]
It was reported by a reviewer of https://github.com/bkamins/JuliaForDataAnalysis/blob/main/ch13.jl 😄.
