### ISSUE TITLE
Aspect Ratio Not Working [BUG]

### ISSUE THREAD

**Issue by chelseas** [JuliaPlots/Plots.jl#4201]
## Details
I am trying to use `aspect_ratio=:equal` but it doesn't seem to be doing anything ...?

Code:
```
plot(range(-1, stop=1, length=31) , zeros(31), color=:blue, aspect_ratio=1.0)
```
or 
```
plot(range(-1, stop=1, length=31) , zeros(31), color=:blue, aspect_ratio=:equal)
```
Result:
![image](https://user-images.githubusercontent.com/14879690/167588220-bd44a052-ab02-4f1a-ad71-1174ab35cc86.png)

### Backends
Plotly and GR

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     |x
plotly        | x  |     |
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version:   [91a5bcdd] Plots v1.29.0
Backend  version (`]st -m <backend(s)>`):
  [28b8d3ca] GR v0.64.2
Can't find plotly version
Output of `versioninfo()`:
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 4800H with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)

**Comment by BeastyBlacksmith** [comment]
If you compare it to the version without `aspect_ratio = 1` you will see a difference. What is the output you would expect instead?

**Comment by chelseas** [comment]
I would expect the squares on the grid are square instead of rectangular.

**Comment by chelseas** [comment]
Oh I'm sorry you're right this is silly of me. The grid is not square and that threw me off.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eduardkieser** [comment]
This does not seem to work on my setup.
Julia 1.9.4
Plots v1.39.0
PlotlyJS v0.18.12
```
using Plots
plotly()  
xs = [1,2,3, 4]  
ys = [10,20,30, 40]  
scatter(xs, ys, aspect_ratio=1)  
```

I can pass any number as well as `:equal` to the aspect_ratio argument without any affect on the plot.
