### ISSUE TITLE
[FR] Control of cross marker thickness

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaPlots/Plots.jl#4209]
It looks like there used to be an option to have both "skinny" crosses and regular marker-shaped crosses, but I seem to only be able to generate skinny crosses.

I don't mind that the cross marker is skinny by default, but I'd still like the line thickness to be controllable. `markerstrokewidth` could work for that, or the thickness could just be proportional to the size, rather than a fixed width.
![image](https://user-images.githubusercontent.com/1438610/169344503-9e8cbb3b-61ea-459f-be79-da1781fda4cc.png)

**Comment by BeastyBlacksmith** [comment]
@jheinen is it possible to change the linewidth for these markers in GR?

**Comment by jheinen** [comment]
I'm back in office on Monday. I will check this - I think it should be possible ...

**Comment by BeastyBlacksmith** [comment]
Correct

**Comment by jheinen** [comment]
@BeastyBlacksmith : I will fix it ASAP and let you know. The changes will not require any modifications to `Plots.jl` but a new GR run-time.

**Comment by t-bltg** [comment]
Seems fixed:
```julia
using Plots
scatter(1:2, markerstrokewidth=4, marker=:cross)
```
