### ISSUE TITLE
[BUG] permute=(:x, :y) interpeted as (:y, :x)

### ISSUE THREAD

**Issue by sethaxen** [JuliaPlots/Plots.jl#4218]
## Details

`permute=(:x, :y)` is a null-permutation and should be interpreted the same as `permute=:none` but is not:

```julia
julia> plot(x, sin.(x))
```
![tmp](https://user-images.githubusercontent.com/8673634/170814772-9668888d-7062-4264-8148-f610a15f0507.png)

```julia
julia> plot(x, sin.(x); permute=(:x, :y))
```
![tmp2](https://user-images.githubusercontent.com/8673634/170814776-bb1bc899-b160-4e47-a8a0-ab3649a9ab0b.png)

```julia
julia> plot(x, sin.(x); permute=(:y, :x))
```
![tmp3](https://user-images.githubusercontent.com/8673634/170814783-d07d013c-a403-4946-b21f-87394bd8b91c.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: v1.29.0
Output of `versioninfo()`:
```julia
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
```

**Comment by BeastyBlacksmith** [comment]
We have a different understanding of the semantics here. I meant `permute = (:x, :y) ` to mean "permute x and y" which is the same as `permute = (:y, :x) `

**Comment by sethaxen** [comment]
Oh interesting. Is this documented? I assumed the semantics I did by analogy to the 2nd argument of `permutedims(A, (2, 1, 3))` listing the order of dimensions.
