### ISSUE TITLE
Ideas to enhance animations

### ISSUE THREAD

**Issue by JobLeonard** [JuliaPlots/Plots.jl#423]
I was just going to propose supporting a visually stable ditherer, but then I looked up some background info to get that started and realised that this might be worth a discussion of its own. Not exactly a high-priority issue, but still a fun enhancement to discuss I think.

The starting point was that I noticed  that the (beautiful) example gifs have a lot of areas that should not change from frame to frame, yet still have different pattern noise. For example, zoom in on the grey grid in the background of the Lorenz Attractor gif:

![lorentz zoom](https://user-images.githubusercontent.com/259840/32442071-58812712-c2fa-11e7-881c-91b90a789710.gif)

This noise is due to the error diffusion methods used. However, there are stable GIF encoders that do not suffer from this. Since plots usually have few colours and change very little from frame to frame, I would expect this kind of optimisation to greatly reduce size _and_ improve visual quality at the same time. Since you're using [ImageMagick with FFMPEG as a fallback](https://github.com/tbreloff/Plots.jl/blob/91aa1d718a5a2616806ff0fdb8859e0f92daa74e/src/animation.jl#[L27-L53]) I've looked at what options they provide.

For IM  there is [this gist exploring ImageMagick's GIF encoding options](https://gist.github.com/CoolOppo/f54d86abe726bb7827e6) that has some suggestions and also warns against the default settings:

> Also if you study the resulting animation further you will find that of the 107 frames in the image, 106 frames had their own own separate local color table added. That is each and every frame in the GIF animation required there own color index table. That is while each frame has less that 256 colors (due to the GIF format limitations), the whole animation is using a total of 7525 colors.
> 
> Unfortunately the GIF format does not compress color tables, so all those extra color tables could be using up to:   256 colors \* 3 byte per color \* 106 frames;   or 81,408 bytes of file space. Not a lot for a 1Gbyte video but still an appreciable amount of space, especially as we optimize the video further.
> 
> Added to this is that the animation will not GIF frame optimize very well. Not only because the background is moving (due to the camera panning upward), but also because IM used a Error Correction Dither (Hilbert Curve Dither), which produces a pseudo-random pattern of colors that is different from frame to frame. A later example will make this 'dither noise' much more visible.

Perhaps I missed it, but glancing at the code it appears that you use the default settings so the output GIF likely suffers from the same issues.

The author then suggests to use a custom colour map based on the total, uncompressed input frames, combine that with an ordered dithering pattern to stabilise the frames, and then add transparancy to further optimise the gif.

For the FFMPEG fallback we could try the [`a_dither`](http://pippin.gimp.org/a_dither/) option - the examples also show the Bayer dithering pattern. It is fairly simple code , and also available in FFMPEG. ImageMagick does not seem to directly support it as far as I can tell, but it [lets you customise the ordered dithering option](http://www.imagemagick.org/Usage/quantize/#od_levels) so it's possible to implement something like it.

Just some thoughts to get a discussion started. I'm not suggesting one solution over the other at this point, but I think it's a topic worth exploring.

EDIT: replaced dead link with custom zoomed in gif

**Comment by tbreloff** [comment]
These sound like nice changes, but they are a very low priority for me.  If you find yourself with time to spare, any (non-breaking) improvements would be appreciated!

**Comment by JobLeonard** [comment]
Yes, I totally agree this may go on the bottom of the "low priority" pile :). If I find some time I'll definitely look into it more, but that's a big if for myself too. I'd also have to learn Julia again after not messing with it for a few years ;).

 It would be fun to try though, so I'll write down the ideas I have at the moment so I can pick them up later. I guess the best way to introduce a non-breaking change would be something like:

    @enum GIFDITHER FloydSteinberg=1 Bayer=2

    function gif(anim::Animation, fn = (isijulia() ? "tmp.gif" : tempname()*".gif"); 
                 fps::Integer = 20, dither::GIFDITHER = FloydSteinberg)

(hope I got the syntax right, like I said: it's been a while)

The default argument would keep the current behaviour. As a start we could make the calls to IM (or FFMPEG) use Bayer dithering if that is passed as an argument.

Other than that it's a matter of playing with those settings.

**Comment by mkborregaard** [comment]
@JobLeonard I think this would be cool. Note that we've changed the implementation (on master) to always use ffmpeg.

**Comment by JobLeonard** [comment]
Just to be clear: I added these changes in the Github browser, I have _not_ tested it myself, nor even checked if I set the flags up in a way that ffmpeg understands.

So I leave that part up to you ;)

**Comment by mkborregaard** [comment]
Thanks a million for this!
