### ISSUE TITLE
surface and then contour scrambles the result

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPlots/Plots.jl#4240]
This results in a scrambled contour plot (using Plots 1.30 and GR 0.64.4 or #master)

```
using Plots

x = range(-3,3,length=20)
y = range(1,7,length=25)
z = 2*x.^2 .+ (y'.-4).^2

p1 = surface( x,y,z')
display(p1)

p2 = contour(x,y,z')
display(p2)
```

Notice: must run surface() first to get the error from contour(). Also, doing `using GR` instead of `using Plots` gives a correct contour plot. Julia 1.7.3 on Win10 (64).

**Comment by PaulSoderlind** [comment]
with Plot.jl it looks like this
![fil1](https://user-images.githubusercontent.com/9378261/174094696-a18a8deb-4993-44e9-986c-713a2da2ed14.png)


but with GR like this:
![fil1_GR](https://user-images.githubusercontent.com/9378261/174094810-43848554-b18f-41ec-9359-c50ae6f224cd.png)

**Comment by jheinen** [comment]
Should now be fixed in bbs/fix-gr-is3d

**Comment by BeastyBlacksmith** [comment]
Though this shows, that we could add supprt for `contour3d` in GR
