### ISSUE TITLE
[FR] Remove that the camera view angle can only be in integer degrees in the GR backend

### ISSUE THREAD

**Issue by gijsbel** [JuliaPlots/Plots.jl#4253]
For some reason within `backends/gr.jl` at around line 1440 the camera view angles are rounded to integer degrees. This makes it so animations that depend on slow rotation VERY choppy. For example, the animated plot at https://docs.juliaplots.org/latest/ has this choppy camera issue. I suggest removing this rounding.

**Comment by gijsbel** [comment]
I just found out this is actually a limitation by the GR framework....

https://github.com/sciapp/gr/blob/master/lib/gr/gr.c line 1166

**Comment by jheinen** [comment]
This limitation in GR no longer exists. The rounding in the GR backend can be omitted.

**Comment by jheinen** [comment]
Fixed in 393cd1fe32b55a84f1ca5fb1f35571af823be23e

**Comment by gijsbel** [comment]
thanks!
