### ISSUE TITLE
plot ignores linecolor attribute with UnicodePlots backend

### ISSUE THREAD

**Issue by lopezm94** [JuliaPlots/Plots.jl#426]
`linecolor` (tried all the color attributes just in case) is completely ignored. Don't really know how to put the plot here but you can execute this and check

``` julia
using Plots
unicodeplots()
plot(rand(10),linecolor=:white)
```

Also happens with `@series`

**Comment by tbreloff** [comment]
Yup. I don't think that will change because of the way colors are handled
in UnicodePlots. PRs to fix are welcomed.

**Comment by lopezm94** [comment]
I'll try, but isn't `color` the equivalent to `linecolor` in UnicodePlots? There must something in the way but I don't see it.

**Comment by tbreloff** [comment]
I'd need a conversion from RGBA to Symbol. A "round" of sorts.

**Comment by lopezm94** [comment]
I see, would adding RGB to UnicodePlots solve it too?

**Comment by tbreloff** [comment]
Similar code needs to be written no matter where it lives.

**Comment by Evizero** [comment]
Sorry, missed this issue until now.

Well, terminal colors are not that straight forward if one wants it to easily work for most people. At some point I need to think how I could improve it for those that want more flexibility.

For example I am very much in love with this idea, which uses even more than just 256 colors https://github.com/stefanhaustein/TerminalImageViewer ... one day...

**Comment by Evizero** [comment]
by the way @tbreloff, I tried to use this TerminaImageViewer to render png's produced by other backends, such as gr and pyplot, to see if it would be readable. I am afraid not, but it would have been really really cool.
