### ISSUE TITLE
[FR] Support `FilePathsBase.AbstractPath` in `savefig`

### ISSUE THREAD

**Issue by tpgillam** [JuliaPlots/Plots.jl#4279]
Currently, `savefig` only supports a filename that is a string, referring to the local filesystem.

[FilePathsBase.jl](https://github.com/rofinn/FilePathsBase.jl) provides the `AbstractPath` abstraction, which allows for using more generic paths in I/O functions such as `open`. One concrete example is `S3Path <: AbstractPath` from [AWSS3.jl](https://github.com/JuliaCloud/AWSS3.jl).

It is possible to write a plot directly to S3 as-is, but it requires some hoop-jumping:

```julia
using AWSS3
using FilePathsBase
using Plots

plot(rand(10))

path = p"s3://my-bucket-name/moo.png"
open(path, "w") do io
    show(io, MIME("image/png"), Plots.current())
end
cp(path, p"moo.png")  # To inspect that the file has rendered correctly
```

---

From a quick play around with the code in `src/output.jl`, I think the only changes that need to be made are:

1) Change `AbstractString` -> `Union{AbstractString,AbstractPath}`
2) Adapt this:

https://github.com/JuliaPlots/Plots.jl/blob/439c3c6b45c9b0a7ce9c51e4c46e139e03bd4495/src/output.jl#L91-L95

to replace `string(fn, ".", ext)` with a more generic method to add an extension & return the appropriate type. I suspect @rofinn will know if such a thing exists & where it can be found :)

**Comment by rofinn** [comment]
I think you could probably just rewrite this as:

```
function addExtension(fp, ext::AbstractString)
     parent = dirname(fp)
     fn = basename(fp)
     oldfn, oldext = splitext(fn) 
     oldext = chop(oldext, head = 1, tail = 0) 
     get(_extension_map, oldext, oldext) == ext ? fp : joinpath(parent, string(fn, ".", ext)) 
 end 
```

This way the code can support both types without needing to depending on FilePathsBase.jl directly.
