### ISSUE TITLE
[BUG] PyPlot backend unable to find working GUI backend

### ISSUE THREAD

**Issue by hershsingh** [JuliaPlots/Plots.jl#4282]
## Details
Using the `pyplot` backend with `Plots.jl` gives me a warning and I am unable to display any plots in the GUI. To be specific, if I run:
```julia
using Plots
pyplot()
```
then I get the following warning:
```julia
** (process:1188529): WARNING **: 09:54:46.668: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: /usr/lib/libpango-1.0.so.0: undefined symbol: hb_ot_layout_get_horizontal_baseline_tag_for_script
┌ Warning: No working GUI backend found for matplotlib
└ @ PyPlot ~/.julia/packages/PyPlot/XaELc/src/init.jl:165
Plots.PyPlotBackend()
```
and whenever I try to plot something, I get
```julia
sys:1: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```

This seems like a `Plots.jl` issue rather than a `PyPlot.jl` issue since `PyPlot.jl` by itself works fine. Interestingly, if I just do `import PyPlot` before `using Plots`, then I don't get any warnings and everything works fine. This allows me to use Plots.jl with the pyplot backend without any issues. The GR backend also works without any issues.

Can anyone see what could be the source of this issue? Thank you!

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     | x   |
pyplot       |  x   |     |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x 
inspectdr    |     |     | x
gaston       |     |     | x 

### Versions

Plots.jl version:  Plots v1.31.3
Backend  version (`]st -m <backend(s)>`):  `PyPlot v2.10.0`
Output of `versioninfo()`:
```
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_EDITOR = emacsclient
```

**Comment by t-bltg** [comment]
Upstream issue (probably wrong library interaction), nothing we can do:
```
** (process:1188529): WARNING **: 09:54:46.668: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: /usr/lib/libpango-1.0.so.0: undefined symbol: hb_ot_layout_get_horizontal_baseline_tag_for_script
```

In the mean time, if you use `Conda` based `PyPlot` try to pin the `libgcc-ng` / `libstdcxx-ng` versions as explained in https://discourse.julialang.org/t/glibcxx-version-not-found/82209/13.
