### ISSUE TITLE
[FR] Areaplot should have a step form - OR - create separate line segment property

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaPlots/Plots.jl#4290]
I'd like to generate an areaplot that can have a step-function form for the line.

More generally, it might be useful to have a separate property to determine how adjacent values are joined? Instead of having a separate series type.

linear (default)
one or more smoothed options: cubic spline?
steppost
steppre
stepmid

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/4291.
