### ISSUE TITLE
Plotting BigFloats on some backends 

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#430]
The issue comes up when trying to plot BigFloats which are really small, like 1-e48. On PyPlot you get something like this plot:

![](https://files.gitter.im/tbreloff/Plots.jl/DCeP/download.png)

which just chops off at 1e-30. GR does something similar, but actually errors and only shows the axis (doing the same thing, stopping at 1e-30). Plotly works correctly, with this same plot [as the solution shown in this example](https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/examples/Feagin's%20Order%2010%2C%2012%2C%20and%2014%20methods.ipynb).

So the issue is with BigFloats on some backends. Talking with Tom, his solution is,

> Ok I'm not too surprised that super small numbers are getting rounded. There are a couple hacks you could try, namely scaling the numbers and passing your own formatter. Maybe make a type recipe for BigFloat which does this automatically? If the range is too small or too large, rescale and add a formatter
> To expand... You could make the plotting range to be closer to 0-1, then rescale when creating tick labels.

**Comment by mkborregaard** [comment]
Do we still have this issue? There isn't an MWE I can try out in practice.

**Comment by ChrisRackauckas** [comment]
`plot(1:10,big(10.0).^(-40:-30),yscale=:log10)`. That works on Plotly

![newplot 23](https://user-images.githubusercontent.com/1814174/32451187-12eff734-c2cb-11e7-8b2f-a2094eb3a837.png)

can you check GR and PyPlot?

**Comment by ChrisRackauckas** [comment]
Also try `plot(1:30,big(10.0).^(-40:-10),yscale=:log10)`

**Comment by mkborregaard** [comment]
I'm having no problems in any of the backends, so I'm closing. Thanks!
