### ISSUE TITLE
Contour Levels

### ISSUE THREAD

**Issue by AStupidBear** [JuliaPlots/Plots.jl#431]
``` julia
using Plots
x=y=-10.:.1:10.
z=Float64[x-y for x=x,y=y]
plot(x,y,z;t=:contour,levels=[0])
```

`levels=[0]` has no effect on the output?

**Comment by mauro3** [comment]
This errors for me on PyPlot.  Anyway, the behavior I expect is that just one contour line is drawn.

**Comment by yiping-huang** [comment]
Same here. I use levels=[0, 0.01] so two lines look just like one line.
