### ISSUE TITLE
[BUG] Markers in legend obscure linestyles in subplots

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaPlots/Plots.jl#4312]
## Details
 
See https://github.com/JuliaPlots/Plots.jl/issues/4092#issuecomment-1216744812.

I will look into making a PR for the scaling proposal, but it would be helpful if someone can point to where to look as I'm very unfamiliar with the codebase. 

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  X   |     |
pyplot       |     |     | X
plotlyjs     |     |     | X
pgfplotsx    |     |     | X
unicodeplots |     |     | X
inspectdr    |     |     |  X
gaston       |     |     | X

### Versions

Plots.jl version: 1.31.7
Backend  version (`]st -m <backend(s)>`): GR v0.66.0
Output of `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by t-bltg** [comment]
At first glance, it seems like the markers are drawn somewhere [here](https://github.com/JuliaPlots/Plots.jl/blob/7dcda22e12b4e2dc48e4a025f0338a8402c16d7c/src/backends/gr.jl#L1110), for the `gr` backend, but I haven't check this further.
