### ISSUE TITLE
[BUG] Line plot doesn't appear if large out-of-range values present (GR)

### ISSUE THREAD

**Issue by sjdaines** [JuliaPlots/Plots.jl#4314]
## Details

Using the GR backend, if a line plot contains values that are much larger than the specified ylim, the entire line is omitted from the plot.

This seems to depend on how large the largest values are, relative to the specified ylim. At least with the examples below, the failure seems to occur if the largest value is larger than ~1e8 x the specified ylim:
```julia
julia> using Plots
julia> plot([1e6, 1, 4e-6, 1e-6], ylim=(-1e-1, 1e-1))  # OK 
julia> plot([1e6, 1, 4e-6, 1e-6], ylim=(-1e-2, 1e-2)) # fails, no line on plot
julia> plot([1e5, 1, 4e-6, 1e-6], ylim=(-1e-2, 1e-2)) # OK
```

![image](https://user-images.githubusercontent.com/626308/185610195-5fde9b87-65ec-4ff6-9081-363d1d79d1cf.png)
![image](https://user-images.githubusercontent.com/626308/185610360-ea8730a8-eba1-44d4-8524-7ebf5c9aff67.png)
![image](https://user-images.githubusercontent.com/626308/185610442-ddeb11f5-df18-4a95-9431-e898422e96d7.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotlyjs     |     |  x   | 
pgfplotsx    |     |     | x
unicodeplots |     |  x   | 
inspectdr    |     |     | x
gaston       |     |     |  x

### Versions

Plots.jl version: v1.31.7
Backend  version (`]st -m <backend(s)>`): GR v0.66.2
Output of `versioninfo()`:
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 72 × Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, broadwell)
  Threads: 1 on 72 virtual cores
Environment:
  JULIA_NUM_PRECOMPILE_TASKS = 4
  LD_LIBRARY_PATH = /usr/local/openmpi-4.0.0/lib:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

**Comment by t-bltg** [comment]
I cannot reproduce this, neither in `Plots` not in plain `GR`.
