### ISSUE TITLE
Saving apng to .png file results in an error.

### ISSUE THREAD

**Issue by shg** [JuliaPlots/Plots.jl#4316]
## Details

I am trying out the recently added APNG output.

I got an error when I save Animation using the apng function. The error occurs only if I give a filename with ".png" extension. It seems working if the extension is ".apng". I found code that checks the file extension to choose the appropriate ffmpeg line in animation.jl.

Are there any reasons to force .apng extension? I believe .png is also commonly used as the extension for Animated PNG. I appreciate if .png is also supported.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |x     |     |
pyplot       | x    |     |
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots v1.31.7
GR v0.66.2
PyPlot v2.10.0

Output of `versioninfo()`:
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

**Comment by shg** [comment]
The error is like:

```
[NULL @ 0x133819c00] Unable to find a suitable output format for '/Users/shg/test/bugs/bug_plots_20220526/figs/plot02.pdf'
/Users/shg/test/bugs/bug_plots_20220526/figs/plot02.pdf: Invalid argument
LoadError: failed process: Process(`/Users/shg/.julia/artifacts/edc52b246257a6a584e140abf9d9658504f99264/bin/ffmpeg -v 16 -framerate 20 -i /var/folders/jj/8ql07lx11tvg2k_vy2fpvlrm0000gn/T/jl_6V1T0N/%06d.png -vf format=yuv420p -loop 0 -y /Users/shg/test/bugs/bug_plots_20220526/figs/plot02.pdf`, ProcessExited(1)) [1]

in expression starting at /var/folders/jj/8ql07lx11tvg2k_vy2fpvlrm0000gn/T/babel-3f0Av8/julia-vterm-src-XnWvph:8
```

which is apparently caused by executing the wrong ffmpeg line for apng.

**Comment by t-bltg** [comment]
@curio-sitas ?

**Comment by curio-sitas** [comment]
Im on it.

@shg can you share us the code you used to generate the error please ?
