### ISSUE TITLE
[BUG] apng and @apng are not exported

### ISSUE THREAD

**Issue by shg** [JuliaPlots/Plots.jl#4318]
## Details

This is a minor thing. I think the function apng and the macro @apng should be exported in Plots.jl but not.

### Versions

lots v1.31.7
GR v0.66.2
PyPlot v2.10.0

Output of `versioninfo()`:
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

**Comment by t-bltg** [comment]
> I think the function apng and the macro @apng should be exported in Plots.jl but not.

No, we had the discussion in https://github.com/JuliaPlots/Plots.jl/pull/4295#discussion_r933982332. Other `io` method are un-exported e.g. `Plots.pdf`.

**Comment by shg** [comment]
Thank you. I had missed that discussion. I understand that's intentional.
