### ISSUE TITLE
Spatialorder of image ignore by GR backend

### ISSUE THREAD

**Issue by Evizero** [JuliaPlots/Plots.jl#432]
Images.jl allows for different spatial-order in the underlying arrays. Although having the first dimension be `x` is the most common, there are also situations in which `y` is the first dimension.

The following two code snippets should produce the same plot

``` julia
using TestImages, Images, Plots
gr(size = (200, 150))
img = testimage("toucan")
plot(img)
```

``` julia
plot(permutedims(img, [2,1]))
```

This (almost) works with pyplot, but for GR it plots transposed

<img width="494" alt="screen shot 2016-08-04 at 20 19 37 2" src="https://cloud.githubusercontent.com/assets/10854026/17413285/e7322b20-5a80-11e6-9086-c6ca9c14e4af.png">

for reference here is the pyplot result:

<img width="489" alt="screen shot 2016-08-04 at 20 16 36 2" src="https://cloud.githubusercontent.com/assets/10854026/17413191/7e478eac-5a80-11e6-8e55-6e312c3d6db3.png">

**Comment by timholy** [comment]
It's also worth noting that---for the purposes of orientation---the Dict is going to go away relatively soon. There's a rewrite of Images underway at https://github.com/JuliaImages. It will be julia-0.5+ only, however.

(The Dict will still be available if you need to, e.g., tag by date or patient ID or whatever. But most images probably won't use the Dict anymore.)

**Comment by Evizero** [comment]
I see. Aw, man, I finally got everything to work as it should, after a week of bashing my head against the wall. Well, such is life, should have done my research on what is changing with 0.5. Lesson learned

Thanks for the link @timholy. This all looks really impressive. I'm looking forward to try it all out (and more head bashing).

**Comment by timholy** [comment]
Sorry this didn't come earlier. It's really only with 0.5 (thanks to `PermutedDimsView`, which is not exported but accessible to those in the know :wink:) that it's finally become possible to solve the orientation mess in a way that uses the type system **without** making copies of input data. Since Images has as a major goal of being able to analyze terabtye datasets, I've always been a stickler for not making copies even when you could otherwise get away with it (essentially to try to force me to make sure Images was reasonably robust about orientation...which didn't entirely work out).

**Comment by Evizero** [comment]
ohh, this sounds amazing! `PermutedDimsArray` sounds to me like exactly the thing we need in machine learning as well to solve that "what dimension should denote the observations" discussion. 

concerning dicts, I hope there will be some kind of flexible metadata storage that allows arbitrary types, since I want to log performed transformations in a way that can recreate the actual transformation pipeline. It looks like this right now and the operations are custom types:

```
RGBA Images.Image with:
  data: 64x64 Array{ColorTypes.RGBA{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    operations:  Flip x-axis. Flip y-axis. Crop to 1.5 aspect ratio. Resize to 64x64.
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1
```

But this is a bit off topic. Thanks for the info. I am excited about this.

Given this information I think this issue may solve itself by Plots adapting to the new Images when the time comes, and I will close it

**Comment by timholy** [comment]
Yes, the "array + dict" still exists and is in that organization with repo name `ImagesMeta.jl`.

**Comment by mkborregaard** [comment]
I am reopening this, because this does not appear to have been fixed by the new version of Images (see https://github.com/JuliaPlots/Plots.jl/issues/670)

**Comment by timholy** [comment]
It's pretty different now, though, because the order should always be the same; there isn't a "setting" that controls the spatial order on a per-image basis. It should just be a question of making sure that GR uses the current order.

**Comment by mkborregaard** [comment]
This works now.
