### ISSUE TITLE
[BUG] Missing last marker when using plotly and specifying `marker_color`

### ISSUE THREAD

**Issue by this-josh** [JuliaPlots/Plots.jl#4333]
## Details

The following code doesn't have a circle for the final data point

```julia
using Plots
plotly()
a= [1,2,3,25]
b = [25,9,8,4]
plot(a, b, markershape=:circle, markercolor=[1,2,3,4])
```

<img width="599" alt="image" src="https://user-images.githubusercontent.com/59419126/188311326-ba17c663-091b-4649-bae7-ef9da84110a5.png">

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |   x  |
pyplot       |     |     |x
plotlyjs     |  x   |     |
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: v1.31.7
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores

**Comment by curio-sitas** [comment]
I do not have the problem when running the whole code a second time. I think the problem comes from the backend loading

**Comment by curio-sitas** [comment]
The problem comes from the fact that the plot draws over segments. For N points there is N-1 segment. But the rendered draws one marker per segment

**Comment by puripant** [comment]
I am new to this repo but I would like to contribute for the first time. Thanks to the pointers by @curio-sitas I can fix this bug and create the following screenshot: 
<img width="620" alt="Screen Shot 2022-10-08 at 22 12 34" src="https://user-images.githubusercontent.com/115980/194714477-d53c6860-9904-4430-ba73-872250c96690.png">

However, I do it another way by checking if it is the last segment and then setting the last marker as non-transparent. If this sounds okay, I will send a pull request.
