### ISSUE TITLE
[BUG] xlabel and yticks are cropped when computer has no display

### ISSUE THREAD

**Issue by bowenszhu** [JuliaPlots/Plots.jl#4368]
## Details

On my PC, the following simple piece of code gives the desired figure.
```julia
using Plots
a = [4, 2, 3, 1]
x = 32 .>> a
y = 1 .<< a
plt = plot(x, y, xlabel = "some x label", axis = :log10, markershape = :circle)
savefig(plt, "xlabel.png")
```
![xlabel](https://user-images.githubusercontent.com/45696147/191660246-3891c4aa-d94a-459e-96fb-f5a2982f18ad.png)

However, when I run it on a computer which has no display, it delivers the following plot.
![](https://asset.cml.dev/48388e5ac2a9c1477721090bf8c6a1bd4deedc60?cml=png&cache-bypass=b1c82595-8706-418b-bc56-916235e91b39)

As we can see, the label of the x axis and the ticks of the y axis are cropped.

The log is
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)
connect: Connection refused
GKS: can't connect to GKS socket application

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
```

##  How to reproduce
I ran it using GitHub Actions.
The yml file is
https://github.com/bowenszhu/Plots.jl/blob/c455a231e04f6a349477069d99b66869ccc18a19/.github/workflows/figure_with_xlabel.yml
The result can be found in 
https://github.com/bowenszhu/Plots.jl/actions/runs/3102878558
and
https://github.com/bowenszhu/Plots.jl/commit/c455a231e04f6a349477069d99b66869ccc18a19#comments

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  `x`   |     |
pyplot       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version: v1.33.0
Backend  version (`]st -m <backend(s)>`): v0.66.2
Output of `versioninfo()`: N/A

**Comment by BeastyBlacksmith** [comment]
on headless systems you should set `ENV["GKSwstype"] = "nul"` (at least with GR). Does that help?

**Comment by t-bltg** [comment]
Alternatively, in you workflow you can prefix the julia command with `xvfb-run` avoiding the log errors.

**Comment by bowenszhu** [comment]
Thank you both.

I tested that any of the following can resolve the issue on headless computers.
- `ENV["GKSwstype"] = "nul"`
- `ENV["GKSwstype"] = "100"`
-  run command with prefix `xvfb-run`

Related issue: JuliaPlots/Plots.jl#1076
