### ISSUE TITLE
Error compiling Plots 

### ISSUE THREAD

**Issue by BaseBeginner** [JuliaPlots/Plots.jl#4372]
Hello, new user to Julia here. I am having issues installing Plots for Julia on my computer. For reference, I am using a MacBook Pro running macOS Monterey. And I installed Julia 1.8.1 using the homebrew package manager.

The actual download and installation seemed to go fine. But whenever I try to call the Plots package in Julia (with `using Plots`), I get the following error:

```
Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1662
ERROR: LoadError: UndefVarError: Display not defined

Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/Plots/JGPR6/src/types.jl:9
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [3] include(x::String)
   @ Plots ~/.julia/packages/Plots/JGPR6/src/Plots.jl:3
 [4] top-level scope
   @ ~/.julia/packages/Plots/JGPR6/src/Plots.jl:155
 [5] include
   @ ./Base.jl:419 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [7] top-level scope
   @ stdin:1
in expression starting at /Users/john/.julia/packages/Plots/JGPR6/src/types.jl:9
in expression starting at /Users/john/.julia/packages/Plots/JGPR6/src/Plots.jl:3
in expression starting at stdin:1
Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to /Users/john/.julia/compiled/v1.8/Plots/jl_VIBGSU.

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1705
  [3] compilecache
    @ ./loading.jl:1649 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] eval
    @ ./boot.jl:368 [inlined]
 [10] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1428
```

I have tried re-installing it after running both Pkg.gc() and GC.gc() like suggested in similar threads but the issue remains. Any advice would be appreciated. Thanks.

**Comment by BeastyBlacksmith** [comment]
Can you try again with a julia binary downloaded from the julia homepage?

**Comment by BaseBeginner** [comment]
Thanks for the response.

Okay, just uninstalled the brew Julia and re-installed it with the version from the homepage (also 1.8.1). I also uninstalled Plots and re-installed it (after running `Pkg.gc()` and `Gc.gc()`). And I am still getting the same error.

**Comment by BeastyBlacksmith** [comment]
That version is __very__ old. You likely have some package in your global environment that is holding you back. You can try
```
pkg> add Plots@1.33.0
```
to get an error message about which Package(s) are causing this.

**Comment by BaseBeginner** [comment]
Alright, followed your last instruction and everything seems to be working now. Thanks so much!
