### ISSUE TITLE
exported html file from jupyter notebook is huge with GR backend

### ISSUE THREAD

**Issue by andferrari** [JuliaPlots/Plots.jl#4374]
## Details

when plotting a lot of points in a jupyter notebook  with GR backend, the exported html  file is huge.

E.g., when compared to `pyplot`backend:
```julia
using Plots
pyplot()
plot(cumsum(randn(1000000)))
```
the exported html file is **600 ko**

```julia
using Plots
gr()
plot(cumsum(randn(1000000)))
```
the exported html file is **16.7 Mo**

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     | x     |

### Versions

Plots.jl version: v1.32.1
Backend  version (`]st -m <backend(s)>`): v0.66.2
Output of `versioninfo()`:
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

**Comment by t-bltg** [comment]
I don't think we do anything specific here in `Plots` regarding `GR`'s `html` output, so I believe that the issue should be reported to the backend itself [here](https://github.com/jheinen/GR.jl/issues).

**Comment by andferrari** [comment]
I have opened https://github.com/jheinen/GR.jl/issues/472#issue-1386484427
