### ISSUE TITLE
[BUG] Plot title location is ignored

### ISSUE THREAD

**Issue by ivan-boikov** [JuliaPlots/Plots.jl#4407]
## Details
Specifying location of plot title with `titleloc` fails on some backends

```julia
using Plots
test() = plot(plot([0,1],[0,1]; title="title", titleloc=:left),
              plot([0,1],[0,1]; title="title", titleloc=(0,1)))

gr()
test() # :left works, (0,1) does not

inspectdr()
test() # does not work

pgfplotsx()
test() # all OK

unicodeplots()
test() # does not work

plotly()
test() # :left works, (0,1) does not
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotly     |  x   |     | 
plotlyjs     |     |     | x
pgfplotsx    |     |  x   |
unicodeplots |  x   |     |
inspectdr    |  x   |     |
gaston       |     |     | x

### Versions

Plots.jl version: 1.35.0
Backend  version (`]st -m <backend(s)>`):
```
InspectDR v.0.4.3
PGFPlotsX v.1.5.1
Plotly v.0.4.1
UnicodePlots v.3.1.3
```
Output of `versioninfo()`:
```
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 12 virtual cores
Environment:
  JULIA_DEPOT_PATH = /home/ivan/.local/share/julia:/home/ivan/.local/share/julia:
```

**Comment by ivan-boikov** [comment]
Actually this does not seem too complicated. Will it be fine if I work on it?

**Comment by t-bltg** [comment]
> Will it be fine if I work on it

Yes, PRs always welcome ;)
