### ISSUE TITLE
[BUG]ERROR: KeyError: key :args not found

### ISSUE THREAD

**Issue by kumailhaider-cloud** [JuliaPlots/Plots.jl#4422]
## Details
using Graphs, GraphPlot
using Symbolics, Statistics, LinearAlgebra
using Plots, LaTeXStrings

@variables p
 A=[1 2+p 3+p; 2+p 1 3+p; 4+p 5+p 1]
 A_eval=Matrix{Num}(substitute.(A,(Dict([p=>0.8]),)))
 heatmap(x=1:3,y=1:3,A_eval,lims=(0.5,3.5),aspectratio=1,c=:heat)
here i get error
but if i set A_eval=[ 1    2.8  3.8
                               2.8  1    3.8
                               4.8  5.8  1]
this gives me a heat map plot 

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pyplot       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions 

Plots.jl version:
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:

**Comment by BeastyBlacksmith** [comment]
`Num` is not a numeric type. You need to convert to a numeric type first.
Symbolics could define a recipe for that, but you'd need to open an issue on their repository for that.
