### ISSUE TITLE
[BUG] No plot appears if commands follow in scripts

### ISSUE THREAD

**Issue by wg030** [JuliaPlots/Plots.jl#4424]
## Details
I figured out some really weird bug with my julia configuration. Executing the following script file does not plot anything.
```julia
using Plots
using PyPlot

x = 0:0.01:1.0
y = x.^2

pyplot()
pygui(true)
Plots.plot(x, y)

println("Are you kidding me?")
```

However, if I comment out the `println("Are you kidding me?")` command, everything is fine and works as expected.
Generally, if any command follows the `Plots.plot(x, y)` command, nothing is being plotted. Ths issue is idependent of PyPlot, which means that the following code does not work and plot anything either:

```julia
using Plots

x = 0:0.01:1.0
y = x.^2

plot(x, y)

println("Are you kidding me?")
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |   x  |     |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: Plots v1.35.2
Backend  version (`]st -m <backend(s)>`): PyPlot v2.11.0
Output of `versioninfo()`:
Julia Version 1.8.2
Commit 36034abf26 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)      
  CPU: 8 × Intel(R) Core(TM) i7-5950HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, broadwell)
  Threads: 4 on 8 virtual cores
Environment:
  JULIA_EDITOR = "C:\Users\homer\AppData\Local\atom\app-1.60.0\atom.exe"  -a
  JULIA_NUM_THREADS = 4

**Comment by t-bltg** [comment]
In a script (not running through `REPL`), you should use `display`:

```julia
plot(x, y) |> display
```
