### ISSUE TITLE
surface looks weird when surfaces overlap in PyPlot

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Plots.jl#443]
I'm trying to make a surface of rotation demo for my lecture, but the figure looks funny:

``` julia
n=50
θ=linspace(0.,2π,n)
f=x->cos(3x)+2
x=linspace(0.,1.,30)
p=surface(;legend=false)
for k=1:length(x)-1
    r=[0.,1.]*f(x[k])
    X=ones(n,2)*diagm([x[k],x[k+1]])
    y=Float64[r[2]*cos(θ) for θ in θ]
    z=Float64[r[2]*sin(θ) for  θ in θ]
    surface!(X,[y y],[z z])
end
p
```

![unknown-1](https://cloud.githubusercontent.com/assets/1229737/17550068/8e614354-5f36-11e6-9fd6-8ab2ef4b6d42.png)

**Comment by mkborregaard** [comment]
Is it the dark purple colour you find weird? I'd be very surprised of this isn't a matplotlib thing.

**Comment by SimonDanisch** [comment]
This looks like PyPlot doesn't do depth testing. I can't reproduce this, since this gives me an error:
```
ERROR: function plot! does not accept keyword arguments
Stacktrace:
 [1] kwfunc(::Any) at ./boot.jl:237
 [2] #surface!#451(::Array{Any,1}, ::Function, ::Array{Float64,2}, ::Vararg{Array{Float64,2},N} where N) at /home/s/.julia/v0.6/RecipesBase/src/RecipesBase.jl:382
 [3] macro expansion at ./REPL[7]:6 [inlined]
 [4] anonymous at ./<missing>:?
```
I guess the syntax is outdated?

**Comment by mkborregaard** [comment]
No, the syntax works for me. That's a strange error.

**Comment by mkborregaard** [comment]
Can probably be closed.
