### ISSUE TITLE
[FR] replace (`PyCall`, `PyPlot`) with (`PythonCall`, `PythonPlot`)

### ISSUE THREAD

**Issue by t-bltg** [JuliaPlots/Plots.jl#4471]
[`PythonPlot`](https://github.com/stevengj/PythonPlot.jl) is not yet registered, but this will be the future.

[`PythonCall`](https://github.com/cjdoris/PythonCall.jl) is the `julia` - `python` overhead free interface.

I'm opening this issue in case someone is interested in working on the transition for the `pyplot` backend.

**Comment by BeastyBlacksmith** [comment]
duplicate of #4181
