### ISSUE TITLE
[FR] Add support for skipmissing

### ISSUE THREAD

**Issue by bkamins** [JuliaPlots/Plots.jl#4481]
Currently the following fails:
```
plot(skipmissing(1:5))
```
It would be convenient that Plots.jl materialized `SkipMissing` objects as vectors automatically, so that users do not have to do:
```
plot(skipmissing(1:5) |> collect)
```
(this is what they have to do now.)

CC @t-bltg @nalimilan

**Comment by t-bltg** [comment]
I think this is reasonable to ask.
