### ISSUE TITLE
subplots + legends + layout broken in 1.35.6

### ISSUE THREAD

**Issue by wmkoolen** [JuliaPlots/Plots.jl#4485]
Dear all,

After updating to 1.35.6 the legends in subplots are not placed correctly anymore. This is fine with 1.35.5. Here's a minimal example:

```julia
using Plots

a = plot(1:5,1:5,label="bla", legend=:left)
b = plot(1:5,1:5,label="flu")
plot(a,b, layout=@layout [a;b])

```
![example](https://user-images.githubusercontent.com/29552933/199191794-3658424a-ebf1-46a2-a5e3-1f75eaf16ca1.svg)

Notice how the "a" plot's legend is gone. A plot(a) reveals that it is still there in the original. Also if the layout argument is omitted, the plots look fine. So the combination of subplots with layout messes things up.

**Comment by t-bltg** [comment]
Thanks for reporting, I'll have a look asap.

**Comment by t-bltg** [comment]
Found it, just an embarassing typo.
