### ISSUE TITLE
[BUG] Legend at `:top` and `:bottom` dislocated to the left

### ISSUE THREAD

**Issue by luboshanus** [JuliaPlots/Plots.jl#4491]
## Details

Legend with position at `legend=:top` and `:bottom` is dislocated to the left edge and almost out of frame.

<img width="760" alt="Screenshot 2022-11-03 at 11 37 38" src="https://user-images.githubusercontent.com/2473206/199700420-52672475-f976-470b-bd39-93d5e5bb17c7.png">

Similar appears for `legend=:bottom`.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

[91a5bcdd] Plots v1.35.7

```
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 20 × Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 1 on 20 virtual cores
```

**Comment by t-bltg** [comment]
Sorry about this. Simmilar to https://github.com/JuliaPlots/Plots.jl/issues/4485. Will fix.
