### ISSUE TITLE
[FR] Use Preferences.jl to configure default loaded backend

### ISSUE THREAD

**Issue by mkitti** [JuliaPlots/Plots.jl#4513]
Loading GR by default can cause issues since it loads so many other packages, notably JLLs.

For example, loading QT via GR can result in the PyPlot backend not working:
https://discourse.julialang.org/t/trouble-using-plots-on-linux/90061/32?u=mkitti

To simplify this, let's provide a Preferences.jl mechanism so that users can load their preferred backend by default. This will also help to minimize issues and accelerate plots by not loading unnecessary packages that we are not using.

**Comment by mkitti** [comment]
The Discourse post got moved. See https://discourse.julialang.org/t/trouble-using-plots-on-macos/90182/19?u=mkitti

**Comment by t-bltg** [comment]
This will also also speedup for the chosen default backend.
If a user only uses a declared backend, we should [precompile examples](https://github.com/JuliaPlots/Plots.jl/blob/394034718da68af036b863c5b24ece5e7cce83f2/src/precompile.jl) for that backend.

**Comment by t-bltg** [comment]
This is going to be a tough one, because of the constraints of module initialization in `__init__`, precompilation using `SnoopPrecompile` and the way we load backends (currently using `@eval` and `@require`) in `Plots` ...

I tried some things, but going nowhere atm.
