### ISSUE TITLE
[BUG] Plotting vector of matrices

### ISSUE THREAD

**Issue by luboshanus** [JuliaPlots/Plots.jl#4518]
## Details

Hi,

I have encountered a situation that if I plot vector of matrices `Vector{Matrix{Float64}}` as `y`, and have vector of indices `Vector{UnitRange{Int64}}` as `x`, the plot goes over the y within different order probably. 

In the example below, the `orange` is the **wrong** one and three other colours are **true**. It can be seen that in 1 part, the orange line is same as the red one, in the second as the blue, etc.. Meaning, that it is strangely transposed/read/accessed by Julia to plot in different order. If I use the for look for xi without selection only vector out of the matrix, it give same=wrong result.

```julia
# x sorted, similar to plot, for example, confidence intervals and median
x = [sort(randn(5,3);dims=2) for i in 1:3]
size(x)
size(x[1])
# x indices
x_ind = [i:(i+5-1) for i in 1:5:(5*3)]
size(x_ind)

# plotting arrays at once # wrong
plot(x_ind, x, line=(2, 0.9, :solid, :orange), legend=:none, size=(800,500))

# plotting arrays separately over y-dim # correct
plot!(x_ind, [xi[:,1] for xi in x], line=(2, 0.6, :dash, :red), label=:none)
plot!(x_ind, [xi[:,2] for xi in x], line=(2, 0.6, :dash, :blue), label=:none)
plot!(x_ind, [xi[:,3] for xi in x], line=(2, 0.6, :dash, :green), label=:none)
```

Example plot:
<img width="653" alt="Screenshot 2022-11-14 at 12 06 02" src="https://user-images.githubusercontent.com/2473206/201647452-832f2bfb-6e04-4e6c-a376-efa6a4d542e2.png">

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotlyjs     |     |     | x 
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version:
```julia
pkg> st -m Plots
      Status `~/My Drive/Projects/DistrEnergy/Manifest.toml`
  [91a5bcdd] Plots v1.36.1
```

Output of `versioninfo()`:
```julia
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Comment by t-bltg** [comment]
Why aren't you using a single matrix (see https://docs.juliaplots.org/stable/input_data/#columns-are-series).

```julia
julia> x = hcat((sort(randn(5,3);dims=2) for _ in 1:3)...);
julia> x_ind = [i:(i+5-1) for i in 1:5:(5*3)];
julia> plot(x_ind, x, line=(2, 0.9, :solid, :orange), legend=:none, size=(800,500))
julia> plot!(x_ind, x[:, 1:3], line=(2, 0.6, :dash, :red), label=:none)
julia> plot!(x_ind, x[:, 4:6], line=(2, 0.6, :dash, :blue), label=:none)
julia> plot!(x_ind, x[:, 7:9], line=(2, 0.6, :dash, :green), label=:none)
```
