### ISSUE TITLE
[BUG] Warning first time creating empty plot of seriestype=:shape

### ISSUE THREAD

**Issue by AsgerHB** [JuliaPlots/Plots.jl#4519]
## Details

The following line

    plot([], [], seriestype=:shape, label="foo")

Causes the following warning to appear the first time it is called

     Keyword argument letter not supported with Plots.GRBackend().  Choose from: annotations, arrow, aspect_ratio, background_color, background_color_inside, background_color_outside, [...]

It seems to list every valid keyword argument (omitted for brevity). 

Calling the same line again does not print the warning a second time, fortunately. Additionally, providing any kind of data to the plot seems to avoid the warning:

    plot([0], [0], seriestype=:shape, label="foo")

I make this call quite frequently to add colored squares to my plot's legend. This is a nice solution for having categorical values in a heatmap.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) | x  |     |
pyplot       |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version: v1.35.5
Backend  version (`]st -m <backend(s)>`): GR v0.69.5
Output of `versioninfo()`:

    Julia Version 1.8.0
    Commit 5544a0fab76 (2022-08-17 13:38 UTC)
    Platform Info:
      OS: Linux (x86_64-linux-gnu)
      CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
      Threads: 1 on 8 virtual cores

**Comment by t-bltg** [comment]
Typing the vectors works too:
```julia
plot(Int[], Int[], seriestype=:shape)
```
does not warn.
