### ISSUE TITLE
[FR]  How to specify `margins` to `0mm` in `RecipesBase`?

### ISSUE THREAD

**Issue by singularitti** [JuliaPlots/Plots.jl#4522]
If I want to create a recipe for my type with only `RecipesBase.@recipe`, I seem not to be able to specify all margins to be `0` or `0mm`, where it requires a `Measure` type, which is defined in `Plots.Measures` module. Could we move [](https://github.com/JuliaPlots/Plots.jl/blob/master/src/plotmeasures.jl) to `RecipesBase`?

```julia
using RecipesBase

@recipe function f(data::Matrix)
    margins --> 0
    return data
end

julia> heatmap(data)
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: MethodError: no method matching +(::AbsoluteLength, ::Int64)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Rational, ::Integer) at rational.jl:313
  ...
Stacktrace:
  [1] _update_min_padding!(sp::Plots.Subplot{Plots.GRBackend})
    @ Plots ~/.julia/packages/Plots/gzYVM/src/backends/gr.jl:787
  [2] iterate
    @ ./generator.jl:47 [inlined]
  [3] _collect(c::Matrix{AbstractLayout}, itr::Base.Generator{Matrix{AbstractLayout}, typeof(Plots._update_min_padding!)}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{2})
    @ Base ./array.jl:807
  [4] collect_similar
    @ ./array.jl:716 [inlined]
  [5] map
    @ ./abstractarray.jl:2933 [inlined]
  [6] _update_min_padding!(layout::Plots.GridLayout)
    @ Plots ~/.julia/packages/Plots/gzYVM/src/layouts.jl:268
  [7] prepare_output(plt::Plots.Plot{Plots.GRBackend})
    @ Plots ~/.julia/packages/Plots/gzYVM/src/plot.jl:241
  [8] display(#unused#::Plots.PlotsDisplay, plt::Plots.Plot{Plots.GRBackend})
    @ Plots ~/.julia/packages/Plots/gzYVM/src/output.jl:173
```

See: https://discourse.julialang.org/t/how-to-specify-margins-to-0mm-in-recipesbase-jl/90384

**Comment by t-bltg** [comment]
@BeastyBlacksmith, would moving the `Plots` dependency `Measures` to `RecipeBase` along with https://github.com/JuliaPlots/Plots.jl/blob/master/src/plotmeasures.jl be acceptable ?

**Comment by BeastyBlacksmith** [comment]
> @BeastyBlacksmith, would moving the `Plots` dependency `Measures` to `RecipeBase` along with https://github.com/JuliaPlots/Plots.jl/blob/master/src/plotmeasures.jl be acceptable ?

I'd say no. We don't want to depend on `Measures` in `RecipesBase`. Also I am not a fan of exposing types to the users for that reason.
I would suggest to use tuples like
```julia
using RecipesBase

@recipe function f(data::Matrix)
    margins --> (0, :mm)
    return data
end
```
And then call e.g. `getproperty(Plots, plotattributes[:bottom_margin][2])` after the recipe pipeline.
I see that the syntax might not be as comfortable, but I'd err on the side of composability here.
