### ISSUE TITLE
[BUG] twinx() with GR backend and Plots >1.35.6 have unequal width of subplots

### ISSUE THREAD

**Issue by thorek1** [JuliaPlots/Plots.jl#4533]
The rightmost subplots have a larger width than the ones to the left. With Plots < 1.35.7 all subplots had the same width. Behaviour occurs from version 1.35.7 onwards.

![plot_142](https://user-images.githubusercontent.com/13523097/203031867-35e053b3-f66f-43a4-a00b-b8fc3d4bcb5f.svg)

## Details
MWE
```julia
using Plots
p=[]
x = rand(10)
push!(p,begin plot(x)
plot!(twinx(),x) end)

x = rand(10)
push!(p,begin plot(x)
plot!(twinx(),x) end)

x = rand(10)
push!(p,begin plot(x)
plot!(twinx(),x) end)

x = rand(10)
push!(p,begin plot(x)
plot!(twinx(),x) end)

plot(p...,layout=grid(1,4))
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot       |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: 1.36.2
Backend  version (`]st -m <backend(s)>`): GR: 0.69.5
Output of `versioninfo()`: Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 4 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8

**Comment by t-bltg** [comment]
Yes, observed in https://docs.juliaplots.org/stable/gallery/gr/generated/gr-ref63/#gr_demo_63.

I couldn't find a way while working on https://github.com/JuliaPlots/Plots.jl/pull/4488.*

PRs welcome.

**Comment by thorek1** [comment]
@example in docs: there are only twinx on the left but not the right so the different size plot area makes sense but in the above MWE they all have twinx and the rightmost subplot is wider...

can you point me to the code to look at and I can give it a go

**Comment by t-bltg** [comment]
Thanks, don't bother I'm on a fix.
