### ISSUE TITLE
[BUG] `vline!` overrides previously set `formatter`

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Plots.jl#4538]
## Details

```julia
plot(rand(4) .* 10^6, rand(4) .* 10^6, xformatter=:plain, yformatter=:plain)
vline!([10^6])
```
![image](https://user-images.githubusercontent.com/4170948/203181177-954e2db2-b151-46c6-b2ce-dcaeb10a3e1b.png)

`xformatter=:plain, yformatter=:plain` is ignored.

This works fine with `hline!`:
```julia
plot(rand(4) .* 10^6, rand(4) .* 10^6, xformatter=:plain, yformatter=:plain)
hline!([10^6])
```
![image](https://user-images.githubusercontent.com/4170948/203181206-13c2c878-cb42-4ba6-9f47-a312a5c1bc63.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pyplot       |     |     | x
plotlyjs     |   x  |     |
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x 
gaston       |     |     | x

### Versions

Plots.jl version: 1.36.3
Backend  version (`]st -m <backend(s)>`): GR 0.69.5
Output of `versioninfo()`:
```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```
```

**Comment by bbejanov** [comment]
I have the same issue using the GR backend.
https://discourse.julialang.org/t/how-to-preserve-xformatter-when-adding-a-vline/92051

**Comment by pablosaa** [comment]
I would like to report that the changes to solve this bus have, however, created the following new bug: https://github.com/JuliaPlots/Plots.jl/issues/4660
