### ISSUE TITLE
[BUG] `gr - contourf` contours distorted using logarithmic scales

### ISSUE THREAD

**Issue by t-bltg** [JuliaPlots/Plots.jl#4540]
Reported in https://discourse.julialang.org/t/issues-with-plots-contourf-and-logarithmic-axes/74185, and https://github.com/JuliaPlots/PlotDocs.jl/pull/322#issuecomment-1324285196.

```julia
using Plots
g(x, y) = log(x*y)

x = y = 10 .^ range(0, 6, length=100)
z = @. g(x', y)

# oddly, this only occurs in `contourf`, not `contour`
contourf(x, y, z, scale=:log10, title="log(xy)", xlabel="x", ylabel="y")

# alternate example
xs = [10^i for i in range(-5, 5, length=50)]
data = [log(i*j) for i in xs, j in xs]

p1 = contourf(data, title="actual data")
p2 = contourf(xs, xs, data, scale=:log10, title="messed up data")
plot(p1, p2)
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pyplot       |     | x   |
plotlyjs     |     | x   |
pgfplotsx    |     | x   |
unicodeplots |     | x   |
inspectdr    |     | x   |
gaston       |     | x   |

**Comment by t-bltg** [comment]
I suspect that the problem lies on `GR` side since we pipe in the same levels as e.g. for the `gaston` (gnuplot) backend, using `contour_levels` from `src/utils.jl`.

This works fine:
```julia
using Plots
gaston()  # use gnuplot
g(x, y) = log(x*y)

x = 10 .^ range(0, 6, length=100)
y = 10 .^ range(0, 6, length=100)
z = @. g(x', y)
contour(x, y, z, scale=:log10, title="log(xy)", xlabel="x", ylabel="y")
```

**Comment by jheinen** [comment]
Strange. In plain GR it seems to work. Will have to check ...
```julia
using GR
x = 10 .^ range(0, 6, length=100)
y = 10 .^ range(0, 6, length=100)
z = log.(x' .* y)
contourf(x, y, z, xlim=(1,10^6), ylim=(1,10^6), xlog=true)
```

**Comment by t-bltg** [comment]
Thanks, I couldn't craft an immediate plain `GR` example.
Note that we use the `GR.contourf(x, y, h, z, ...)` signature in `Plots`, might be related...

```julia
using GR
x = y = 10 .^ range(0, 6, length=100);
z = log10.(x' .* y);
h = [0.0, 1.7269388197455342, 3.4538776394910684, 5.180816459236603, 6.907755278982137, 8.634694098727671, 10.361632918473205, 12.08857173821874, 13.815510557964274, 15.542449377709808, 17.269388197455342, 18.996327017200876, 20.72326583694641, 22.450204656691945, 24.17714347643748, 25.904082296183013];
contourf(x, y, z; levels=h, clabels=true);
```

**Comment by t-bltg** [comment]
Wait, even with `xlog=true`, we don't have the same contour lines for `contour` and `contourf`:

```julia
using GR
x = y = 10 .^ range(0, 6, length=100);
z = log10.(x' .* y);
contour(x, y, z; xlog=true)
contourf(x, y, z; xlog=true)  # wrong fill-in and wrong lines
```

**Comment by jheinen** [comment]
Looks like a bug then. We'll check this ...

**Comment by t-bltg** [comment]
Reported upstream instead.
