### ISSUE TITLE
[BUG] Plotly colorbar size does not scale with plot size

### ISSUE THREAD

**Issue by stevenaleung** [JuliaPlots/Plots.jl#4547]
## Details
By default, the plotly colorbar is slightly offset in the y direction:

```julia
using Plots
data = rand(3, 3);
heatmap(data)
```

<img width="50%" src="https://user-images.githubusercontent.com/4917419/203710296-cac59df0-b611-4f2d-8655-ef23be7996c3.png">

Increasing the tick font size shows that the colorbar also doesn't scale with plot size:

```julia
heatmap(data, colorbar=:right, tickfont=30, xlabel="test")
```

<img width="50%" src="https://user-images.githubusercontent.com/4917419/203709286-63e34d3c-94f1-4473-a763-36d911cd1448.png">

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     | x
pyplot       |     |     | x
plotlyjs     | x    |     |
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: 1.36.4
Backend  version (`]st -m <backend(s)>`):

Output of `versioninfo()`:
Julia Version 1.8.2
Commit 36034abf26 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 4 × Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, ivybridge)
  Threads: 1 on 4 virtual cores

**Comment by t-bltg** [comment]
Xref https://github.com/JuliaPlots/Plots.jl/issues/1180

**Comment by stevenaleung** [comment]
The main issue is the static colorbar size rather than the colorbar font - updating the title to reflect this
