### ISSUE TITLE
[FR] redesign backend dependencies

### ISSUE THREAD

**Issue by t-bltg** [JuliaPlots/Plots.jl#4567]
Some nice design ideas by @mkitti in https://github.com/JuliaPlots/Plots.jl/pull/4566#pullrequestreview-1196734092:

> Perhaps we should consider a more radical redesign in the near future?

> 1. Each of the pieces of backend glue code could be independent subpackages. GRPlotsBackend, PyPlotPlotsBackend, etc.
> 2. Most of the code currently in Plots.jl gets moved to a package named AbstractPlots.jl. All the backend packages depend on AbstractPlots.jl.
> 3. Plots.jl becomes a small package which just depends on GRPlotsBackend.jl by default. Via Preferences.jl it can optionally load any of the other backend packages and act as a proxy for that package.

> The advantage of this is that each backend now can be precompiled and has its own compiled cache. Also the project dependency tree becomes a bit clearer. One could get all the features of Plots by just doing using SomePlotsBackend.jl directly.

> For loading with Requires.jl can then just do @eval using GRPlotsBackend.jl similar to what @timholy recommended here:
https://discourse.julialang.org/t/categoricalarrays-forces-openspecfun-jll-recompilation/87759/18?u=mkitti

> The impact here for this PR is still acknowledging that the GR backend is a special case for the current architecture. That is Plots.jl has declared a dependency on GR.jl. One consequence of that special case is that we load GR.jl within Plots.jl rather than Main. Eventually we move that responsibility to GRPlotsBackend.jl.

JuliaLang/julia/pull/47040 or JuliaLang/julia/pull/47695 could help too.

**Comment by BeastyBlacksmith** [comment]
> 1. Each of the pieces of backend glue code could be independent subpackages. GRPlotsBackend, PyPlotPlotsBackend, etc.

Back in the days (6 years ago) that was how things were done, e.g. https://github.com/JuliaPlots/PlotsGR.jl

**Comment by t-bltg** [comment]
Implemented in https://github.com/JuliaPlots/Plots.jl/pull/4904.
