### ISSUE TITLE
Alternative ticks for log-plots and minor tick marks

### ISSUE THREAD

**Issue by mfalt** [JuliaPlots/Plots.jl#458]
It it possible in the current framework to show minor ticks in log plots as 2_10^x, 3_10^x .. 9*10^x as is common in for example bode plots:
![bode](https://upload.wikimedia.org/wikipedia/commons/f/fd/Bode-pt2.png)
or is there a simple way to add it in this package or in the user code?
I was able to create something similar with the following (ugly) code

```
function getLogTicks(x)
    min = ceil(log10(minimum(x)))
    max = floor(log10(maximum(x)))
    major = 10.^collect(min:max)
    majorText = ["\$10^{$(round(Int64,i))}\$" for i=min:max]
    minor = [j*10^i for i=(min-1):(max+1) for j=2:9]
    minor = minor[find(minimum(x) .<= minor .<= maximum(x))]
    ([major; minor], [majorText; fill("", length(minor))])
end
```

but I can't find a command for having different styles on the different tick lines. And when using these ticks with something like
`Plots.plot!(x, y, xscale=:log10, ticks=getLogTicks(x))`
the old ticks are overwritten when adding more plots.

**Comment by tbreloff** [comment]
The quick answer is: no, you'll need to do some hacking like you're already
doing. But you might improve the hack by using the 'formatter' attribute
and some trickery that returns an alternative format if the value is not
approximately a major tick mark.

It also might make sense to let 'ticks' accept a function mapping axis
limits to a list of ticks, so you could compute them dynamically based on
the current axis limits. This should be easy.

**Comment by mfalt** [comment]
Thanks, I will look into the formatter function. Although I think accepting a function to `ticks` is the best way to go. This would enable showing text on my "minor" tick in case the range is very small for example, or adding even more "minor" ticks based on the range. I would definitely write such a function for my toolbox and would be happy to write one for Plots.jl too if you have interest in supporting some natively in Plots.jl.

**Comment by mfalt** [comment]
A question related to the formatter, it seems like not all back-ends support latex in the tick text, is there a good way of getting around this, either by a common formatting rule, or formatting in different ways for different back-ends?

**Comment by tbreloff** [comment]
I'm open to suggestions on generic latex handling.

**Comment by mkborregaard** [comment]
@mfalt currently Latex formatting is done with the package LaTeXStrings. Can this be closed?

**Comment by mfalt** [comment]
It does not really have to do with the formatting of the ticks, but rather the positioning and grid lines corresponding to the ticks. As a reference, this is our current (horrible) implementations: https://github.com/JuliaControl/ControlSystems.jl/pull/116/commits/ee9bc1ff2d32cb7561f58b085a52a052de2647ec
I understand that an option with these specific choices of grid lines might not fit in Plots.jl, but it would be nice to be able to do this in a more robust way.

I don't really have a lot of time to commit to this so closing is fine.

**Comment by mkborregaard** [comment]
Wait, why do you need to do this? I'm pretty sure this could be done easier.

**Comment by mkborregaard** [comment]
Given that I now understand the issue better I'll reopen the issue - if you or someone else gets time in the future :-)

**Comment by mkborregaard** [comment]
BTW you likely could replace your Plots dep with one on RecipesBase - that would make the package lighter.

**Comment by mkborregaard** [comment]
Yeah, so sorry for closing this before I was aware of what was going on exactly. I visited 50 issues today and this went a bit fast. I am in fact in favour of your suggestion, both with regards to the alternative tick placements and the minor ticks. 
FWIW, this is actually the current behaviour of the plotlyjs backend:
```julia
using Plots; plotlyjs()
plot(logspace(1,3,100), 1:100, xscale = :log10)
```
<img width="581" alt="skaermbillede 2017-11-06 kl 22 06 11" src="https://user-images.githubusercontent.com/8429802/32464066-0b966774-c33f-11e7-8454-b4fe5ea3d862.png">

**Comment by joachimneu** [comment]
PyPlot/Matplotlib supports major and minor ticks and grids. This distinction improves the comprehensibility of plots a lot. Any plans to add this to Plots? For a hacky interim workaround: Is there a way to access the "underlying" PyPlot plot object when using Plots?

These urls could be helpful for future implementation:
- https://gist.github.com/gizmaa/7214002#majorminorticks
- https://stackoverflow.com/questions/9127434/how-to-create-major-and-minor-gridlines-with-different-linestyles-in-python

**Comment by mkborregaard** [comment]
It would be really cool to have. You can access the underlying object as `p = plot(...); p.o` but as you say, it's hacky.

**Comment by joachimneu** [comment]
Thanks! For reference, here is a quick example of how minor ticks/grid could be obtained:
```julia
p = plot(-15:35, -15:35)

ax = p.o[:axes][1]

ax[:minorticks_on]()

ax[:xaxis][:set_tick_params](reset=true, which="major", direction="in", bottom=true, top=false, length=5, width=1)
ax[:xaxis][:set_tick_params](reset=true, which="minor", direction="in", bottom=true, top=false, length=3, width=1)
ax[:yaxis][:set_tick_params](reset=true, which="major", direction="in", left=true, right=false, length=5, width=1)
ax[:yaxis][:set_tick_params](reset=true, which="minor", direction="in", left=true, right=false, length=3, width=1)

ax[:grid](b=true, which="major", color="black", alpha=0.1, linestyle="-", linewidth=1)
ax[:grid](b=true, which="minor", color="black", alpha=0.1, linestyle=":", linewidth=1)

p.o[:canvas][:draw]()

p.o
```

**Comment by tshort** [comment]
I just tried the `p.o` trick, and it returns `nothing`. Has this changed?

**Comment by mkborregaard** [comment]
Not in Plots, I think, but I don't know if the matplotlib 3.0 update has had some effect here
