### ISSUE TITLE
[BUG] `plot_title` with non-white background looks bad

### ISSUE THREAD

**Issue by baggepinnen** [JuliaPlots/Plots.jl#4595]
## Details
With GR, but not with Plotly, the following produces a plot with the background color above the `plot_title`
```julia
theme(:ggplot2)
plot(randn(3), title="A", plot_title="C")
```
![image](https://user-images.githubusercontent.com/3797491/207316138-2e3f7d01-24c7-4a92-8789-e692f59036ce.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pythonplot   |     |     |
plotlyjs     |     |  x   |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version:  Plots v1.37.2
Backend  version (`]st -m <backend(s)>`):  [28b8d3ca] GR v0.71.1
Output of `versioninfo()`:
julia> versioninfo()
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 5900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver3)
  Threads: 12 on 24 virtual cores
Environment:
  JULIA_NUM_THREADS = 12
  JULIA_EDITOR = code
  JULIA_SSH_NO_VERIFY_HOSTS = gitlab.cognibotics.net
  JULIA_PKG_PRECOMPILE_AUTO = 1
  JULIA_NUM_PRECOMPILE_TASKS = 20
  JULIA_PKG_USE_CLI_GIT = true

**Comment by EldarAgalarov** [comment]
This bug is related to https://github.com/JuliaPlots/Plots.jl/issues/4612 and https://github.com/JuliaPlots/Plots.jl/issues/4610
