### ISSUE TITLE
Set number of ticks without specifying their location

### ISSUE THREAD

**Issue by ahwillia** [JuliaPlots/Plots.jl#462]
Matplotlib has a nice feature ([`locator_params`](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.locator_params)) that lets you set the number of ticks on an axis without specifying their actual location.

It would be nice to have something like `plot(randn(100,2); xaxis=(3))` produce something like this by default:

<img width="598" alt="screen shot 2016-08-28 at 11 51 56 am" src="https://cloud.githubusercontent.com/assets/636625/18035980/d9780ab6-6d15-11e6-89c9-65feeb74cc87.png">

**Comment by mkborregaard** [comment]
Closed in #780
