### ISSUE TITLE
[BUG] Scatter silently discards values from longer vector

### ISSUE THREAD

**Issue by albheim** [JuliaPlots/Plots.jl#4637]
## Details

The behaviour of `scatter` and `plot` when sending different length arguments differ. Scatter will silently discard the remaining elements from the longer vector, while plot will error.
Scatter will also scale the plot based on the all the elements, even the ones that aren't shown.

```julia
julia> scatter(1:5, 1:8) # 1-5 is plotted, but y is scaled 1-8
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

julia> plot(1:5, 1:8)
Error showing value of type Plots.Plot{Plots.GRBackend}:
ERROR: BoundsError: attempt to access 5-element UnitRange{Int64} at index [1:8]
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pythonplot   |     |     |x
plotlyjs     |     |     |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: v1.38.2
Backend  version (`]st -m <backend(s)>`): GR v0.71.3
Output of `versioninfo()`:
```
Julia Version 1.9.0-beta3
Commit 24204a73447 (2023-01-18 07:20 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by BeastyBlacksmith** [comment]
duplicate of https://github.com/JuliaPlots/Plots.jl/issues/2980

**Comment by albheim** [comment]
Yeah, lazy by me to not check. Sorry for the noise!
