### ISSUE TITLE
[BUG] display of plot window always takes 2.3 seconds with GR and PGFPlotsX backends on windows

### ISSUE THREAD

**Issue by omerchiers** [JuliaPlots/Plots.jl#4638]
## Details

I posted this issue initially on discourse some time ago [(post)](https://discourse.julialang.org/t/plots-jl-gr-backend-time-to-plot-on-windows-always-2-3-seconds/74752?u=olivier_merchiers).

These timings are from the discourse post but are mostly the same on julia 1.8.5. It occurs also on julia 1.9 beta3.
OS : Windows 10

```
julia> @time using Plots; @time display(plot(rand(10)))
  3.859720 seconds (8.52 M allocations: 590.593 MiB, 7.35% gc time, 12.19% compilation time)
  7.764304 seconds (17.92 M allocations: 957.783 MiB, 2.12% gc time, 68.93% compilation time)
julia> @time display(plot(rand(10))) #I closed the window before launching this command
  2.337953 seconds (140.36 k allocations: 2.781 MiB) # after closing the window it always takes 2.3 seconds to open a new one.
```
Between the first and second time I invoke the plot() function, I close the window with the figure.
As you can see from the timing, after closing the window and invoking again plot
I always get a time to plot of approximately 2.3 seconds.

It only occurs with the GR and PGFPlotsX backends. I could not test Gaston. 
It is a bit sad since basically it cancels out native code caching in 1.9.

### Backends

This bug occurs on 

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pyplot   |     |  x   |
plotlyjs     |     |  x   |
pgfplotsx    |  x   |     |
unicodeplots |     |   x  |
inspectdr    |     |   x  |
gaston       |     |     |x

### Versions
Plots.jl version: 1.38.2
Backend  version (`]st -m <backend(s)>`): GR 0.71.3, PGFPlotsX 1.5.3
Output of `versioninfo()`: 
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores

**Comment by BeastyBlacksmith** [comment]
There is probably little we can do from the Plots side, since the window is not controlled by us. Would be interesting to see if you can reproduce with plain GR.
For pgfplotsx you could try setting another default application for opening pdfs, but I wouldn't be surprised if compiling the latex code alone takes 2s.

**Comment by omerchiers** [comment]
Hi,
Thanks for looking into this. I will have try with plain GR and report back.

**Comment by omerchiers** [comment]
Hi again,

So I tried with plain GR and indeed, I get the same issue. I will post an issue over there.

Thanks again,
Olivier
