### ISSUE TITLE
[BUG] The use of `marker --> ` in a plot recipe prevents `markershape` to be modified

### ISSUE THREAD

**Issue by rmsrosa** [JuliaPlots/Plots.jl#4644]
When using a plot recipe with `marker --> :auto` or any other value, say `marker --> :circle`, the attribute `markershape` cannot be overwritten by the user. Same with a plot with attribute `marker=:auto` or `marker=:circle`, and no specialized recipe. All other marker-related attributes can be changed by the user. This is a problem when using a package which is not owned by the user.

## Details

Here is an MWE with a recipe:

```julia
using RecipesBase, Plots

struct Foo{T}
    x::Vector{T}
    y::Vector{T}
end

@recipe function f(foo::Foo)
    xlabel --> "x"
    ylabel --> "y"
    seriestype --> :path
    marker --> :auto
    return foo.x, foo.y
end

x = collect(0.0:10.0)
foo = Foo(x, sin.(x))

plot(foo)
plot(foo, markershape=:diamond)
plot(foo, marker=:diamond)
plot(foo, marker=:diamond, markershape=:diamond)
```

All plots are equal:

<img width="864" alt="Screen Shot 2023-01-30 at 09 19 50" src="https://user-images.githubusercontent.com/17986148/215475314-e2e072bd-b40a-4212-bb56-0c74e14247aa.png">

Even without recipe, if we do
```julia
plot(0:10, sin, marker=:auto, markershape=:circle, markersize=10, markeralpha=0.4, markercolor=:red, markerstrokewidth=10, markerstrokealpha=0.6, markerstrokecolor=:black, markerstrokestyle=:dot)
```
then all visible attributes are changed except `markershape`:

<img width="860" alt="Screen Shot 2023-01-30 at 09 41 20" src="https://user-images.githubusercontent.com/17986148/215479941-c2651898-7ff1-4551-98c2-c4b0ea2ae1ec.png">

The reason for `plot(foo, markershape=:diamond)` to fail is that, at https://github.com/JuliaPlots/Plots.jl/blob/master/src/args.jl#L1442, the attribute of `markershape` is changed to that of `marker`, which in this case was set to `:auto` in the recipe.

The reason for  `plot(foo, marker=:diamond)` to fail is that actually the code goes twice through https://github.com/JuliaPlots/Plots.jl/blob/master/src/args.jl#L1442, first with the arguments passed in this command (at  https://github.com/JuliaPlots/Plots.jl/blob/master/src/plot.jl#L97) and secondly after running the recipe (at https://github.com/JuliaPlots/Plots.jl/blob/master/src/plot.jl#L102).

In the first pass, before applying the recipe, the `markershape` attribute is set to that of `marker`, which was given as `:diamond`, but immediately after that the attribute of `marker` is removed from `plotattributes` at https://github.com/JuliaPlots/Plots.jl/blob/master/src/args.jl#L1446, and later the recipe is applied and `marker` is set to `:auto` by the recipe, so that the second pass turns `:markershape` into `:auto`.

I believe this is not intended, but please let me know otherwise

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  X   |     |
pythonplot   |     |     | X
plotlyjs     |     |     | X
pgfplotsx    |     |     | X
unicodeplots |     |     | X
inspectdr    |     |     | X
gaston       |     |     | X

### Versions

Plots.jl version: [91a5bcdd] Plots v1.38.3
Backend  version (`]st -m <backend(s)>`): [28b8d3ca] GR v0.71.5
Output of `versioninfo()`:
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 6 on 6 virtual cores
Environment:
  JULIA_NUM_THREADS = auto
  JULIA_EDITOR = code

**Comment by BeastyBlacksmith** [comment]
I am tempted to deprecate usage of magic attributes in recipes

**Comment by rmsrosa** [comment]
Like `marker` and `fill` ? I agree with that.
