### ISSUE TITLE
surface() complains of identical data points even though it shouldn't

### ISSUE THREAD

**Issue by alicedb2** [JuliaPlots/Plots.jl#4646]
Currently using Plots v1.38.3 with GR backend.

Here are the steps to reproduce

```
using Plots

x = [0.8704, 0.8712, 0.8861, 0.8910, 0.8508, 0.8840]
y = [0.6070, 0.6070, 0.6159, 0.6404, 0.6293, 0.6404]

z = [0.8341, 0.82465, 0.82515, 0.4908, 0.83195, 0.83335]

surface(x, y, z)
 ***   IDENTICAL DATA POINTS.
   NDP =    6   IP1 =    1   IP2 =    2   XD=0.8704   YD=0.607
 ERROR DETECTED IN ROUTINE   IDTANG.

surface(x[2:end], y[2:end], z[2:end])
```
The last line works without complaining. So it seems like surface considers the first point (0.8704, 0.6070) as identical to the second point (0.8712, 0.6070). This is a difference of 0.0008 in the first coordinate which should be enough to be considered different no? Does the underlying triangulation algorithm used by surface() work in Float16? Of course I can multiply the x and y coordinate by 10 as a quick fix but then I have to mess with the axis tick labels and so on.

**Comment by BeastyBlacksmith** [comment]
CC: @jheinen

**Comment by jheinen** [comment]
The internally used triangulation algorithm in the `gridit` function in GR unfortunately cannot handle duplicate `x` or `y` values.

**Comment by alicedb2** [comment]
It still doesn't work after I added a small perturbation to y, which is where you have a repeat. Now there's no repeat and I get the same error. the difference between the first and second value of y is 0.0003.

```
x = [0.8704, 0.8712, 0.8861, 0.8910, 0.8508, 0.8840]
y = [0.6079, 0.6076, 0.6162, 0.6405, 0.6294, 0.6413]

z = [0.8341, 0.82465, 0.82515, 0.4908, 0.83195, 0.83335]

surface(x, y, z)
 ***   IDENTICAL DATA POINTS.
   NDP =    6   IP1 =    1   IP2 =    2   XD=0.8704   YD=0.60793
 ERROR DETECTED IN ROUTINE   IDTANG.
```
