### ISSUE TITLE
[BUG] unicodeplots() gives LoadError

### ISSUE THREAD

**Issue by Socob** [JuliaPlots/Plots.jl#4654]
## Details

Using `unicodeplots()` results in a `LoadError`, and subsequent plotting doesn’t work. Perhaps related to #4648/JuliaPlots/UnicodePlots.jl#332?

    julia> using Plots

    julia> unicodeplots()
    ┌ Warning: Error requiring `UnicodePlots` from `Plots`
    │   exception =
    │    LoadError: UndefVarError: FileIO not defined
    │    Stacktrace:
    │      [1] include(mod::Module, _path::RelocatableFolders.Path)
    │        @ Base ./Base.jl:419
    │      [2] include(x::RelocatableFolders.Path)
    │        @ Plots ~/.julia/packages/Plots/QZRtR/src/Plots.jl:1
    │      [3] top-level scope
    │        @ ~/.julia/packages/Plots/QZRtR/src/backends.jl:101
    │      [4] eval
    │        @ ./boot.jl:368 [inlined]
    │      [5] eval
    │        @ ~/.julia/packages/Plots/QZRtR/src/Plots.jl:1 [inlined]
    │      [6] (::Plots.var"#636#639")()
    │        @ Plots ~/.julia/packages/Requires/Z8rfN/src/require.jl:101
    │      [7] macro expansion
    │        @ timing.jl:382 [inlined]
    │      [8] err(f::Any, listener::Module, modname::String, file::String, line::Any)
    │        @ Requires ~/.julia/packages/Requires/Z8rfN/src/require.jl:47
    │      [9] (::Plots.var"#635#638")()
    │        @ Plots ~/.julia/packages/Requires/Z8rfN/src/require.jl:100
    │     [10] withpath(f::Any, path::String)
    │        @ Requires ~/.julia/packages/Requires/Z8rfN/src/require.jl:37
    │     [11] (::Plots.var"#634#637")()
    │        @ Plots ~/.julia/packages/Requires/Z8rfN/src/require.jl:99
    │     [12] #invokelatest#2
    │        @ ./essentials.jl:729 [inlined]
    │     [13] invokelatest
    │        @ ./essentials.jl:726 [inlined]
    │     [14] foreach(f::typeof(Base.invokelatest), itr::Vector{Function})
    │        @ Base ./abstractarray.jl:2774
    │     [15] loadpkg(pkg::Base.PkgId)
    │        @ Requires ~/.julia/packages/Requires/Z8rfN/src/require.jl:27
    │     [16] #invokelatest#2
    │        @ ./essentials.jl:729 [inlined]
    │     [17] invokelatest
    │        @ ./essentials.jl:726 [inlined]
    │     [18] run_package_callbacks(modkey::Base.PkgId)
    │        @ Base ./loading.jl:869
    │     [19] _require_prelocked(uuidkey::Base.PkgId)
    │        @ Base ./loading.jl:1206
    │     [20] macro expansion
    │        @ ./loading.jl:1180 [inlined]
    │     [21] macro expansion
    │        @ ./lock.jl:223 [inlined]
    │     [22] require(into::Module, mod::Symbol)
    │        @ Base ./loading.jl:1144
    │     [23] top-level scope
    │        @ ~/.julia/packages/Plots/QZRtR/src/backends.jl:402
    │     [24] eval
    │        @ ./boot.jl:368 [inlined]
    │     [25] _initialize_backend(pkg::Plots.UnicodePlotsBackend)
    │        @ Plots ~/.julia/packages/Plots/QZRtR/src/backends.jl:401
    │     [26] backend(pkg::Plots.UnicodePlotsBackend)
    │        @ Plots ~/.julia/packages/Plots/QZRtR/src/backends.jl:266
    │     [27] #unicodeplots#315
    │        @ ~/.julia/packages/Plots/QZRtR/src/backends.jl:87 [inlined]
    │     [28] unicodeplots()
    │        @ Plots ~/.julia/packages/Plots/QZRtR/src/backends.jl:87
    │     [29] top-level scope
    │        @ REPL[2]:1
    │     [30] eval
    │        @ ./boot.jl:368 [inlined]
    │     [31] eval_user_input(ast::Any, backend::REPL.REPLBackend)
    │        @ REPL /opt/julia-1.8.5/share/julia/stdlib/v1.8/REPL/src/REPL.jl:151
    │     [32] repl_backend_loop(backend::REPL.REPLBackend)
    │        @ REPL /opt/julia-1.8.5/share/julia/stdlib/v1.8/REPL/src/REPL.jl:247
    │     [33] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
    │        @ REPL /opt/julia-1.8.5/share/julia/stdlib/v1.8/REPL/src/REPL.jl:232
    │     [34] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
    │        @ REPL /opt/julia-1.8.5/share/julia/stdlib/v1.8/REPL/src/REPL.jl:369
    │     [35] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    │        @ REPL /opt/julia-1.8.5/share/julia/stdlib/v1.8/REPL/src/REPL.jl:355
    │     [36] (::Base.var"#967#969"{Bool, Bool, Bool})(REPL::Module)
    │        @ Base ./client.jl:419
    │     [37] #invokelatest#2
    │        @ ./essentials.jl:729 [inlined]
    │     [38] invokelatest
    │        @ ./essentials.jl:726 [inlined]
    │     [39] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    │        @ Base ./client.jl:404
    │     [40] exec_options(opts::Base.JLOptions)
    │        @ Base ./client.jl:318
    │     [41] _start()
    │        @ Base ./client.jl:522
    │    in expression starting at ~/.julia/packages/Plots/QZRtR/src/backends/unicodeplots.jl:313
    │    in expression starting at ~/.julia/packages/Plots/QZRtR/src/backends/unicodeplots.jl:277
    └ @ Requires ~/.julia/packages/Requires/Z8rfN/src/require.jl:51
    Plots.UnicodePlotsBackend()

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  X  |
pythonplot   |     |  X  |
plotlyjs     |     |  X  |
pgfplotsx    |     |  X  |
unicodeplots |  X  |     |
inspectdr    |     |  X  |
gaston       |     |  X  |

### Versions

- Plots.jl version: v1.38.4
- Backend  version (`]st -m <backend(s)>`): UnicodePlots v3.4.0
- Output of `versioninfo()`:
  >     Julia Version 1.8.5
  >     Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
  >     Platform Info:
  >       OS: Linux (x86_64-linux-gnu)
  >       CPU: 16 × AMD Ryzen 7 4800H with Radeon Graphics
  >       WORD_SIZE: 64
  >       LIBM: libopenlibm
  >       LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  >       Threads: 1 on 16 virtual cores

**Comment by t-bltg** [comment]
Oh yes, it's just that it needs a new version of Plots tagged.

**Comment by t-bltg** [comment]
A news version will be out in a moment: https://github.com/JuliaRegistries/General/pull/77404.
