### ISSUE TITLE
[FR] Support `xticks`, `yticks` with UnicodePlots

### ISSUE THREAD

**Issue by Socob** [JuliaPlots/Plots.jl#4657]
UnicodePlots supports `xticks` and `yticks` (at least as `Bool` arguments) since JuliaPlots/UnicodePlots.jl#234, but passing `xticks=false` or `yticks=false` using Plots.jl does nothing. It’s also not listed as supported in the [documentation](https://docs.juliaplots.org/stable/gallery/unicodeplots/generated/unicodeplots/). But since it’s there in UnicodePlots, it would be nice to have access to it from Plots.jl too.

**Comment by t-bltg** [comment]
PRs welcome !
