### ISSUE TITLE
[BUG] using vline() with DateTime as x-axis screws up the y-axis labels

### ISSUE THREAD

**Issue by pablosaa** [JuliaPlots/Plots.jl#4660]
## Details

I found an apparently new bug using vline and DateTime format in the x-axis:
`plot(rs[:time], tir[:IRT], size=(800,300))`
![](https://user-images.githubusercontent.com/24556480/217926409-dd862767-3b2f-4339-b3a7-5f08378f39ce.png)

but when adding a vline as :
`vline!([DateTime(2020,4,15, 12)])`
it changes the y-axis label as shown below:
![](https://user-images.githubusercontent.com/24556480/217926498-45620fd0-d3fc-4b23-9ff8-9e87c7189ee4.png)

I can confirm that I've worked with vline() and DateTime as x-axis data format regularly before and it used to work flawlessly before updating Plots.jl to v1.38.4 , for Julia Version 1.8.0

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pythonplot   |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: v1.38.4
Backend  version (`]st -m <backend(s)>`): GR v0.71.5
Output of `versioninfo()`:
```
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by NNURLYGS** [comment]
If you would have done this, while switching the values of the y bar and bar, and trying to do this same thing just with the hline!() function, would this still happen?

**Comment by ygol55** [comment]
Can you try to do the same thing, just changing the values of the y values and x values, and using the hline!() function?

**Comment by pablosaa** [comment]
If I did understand properly, you mean same plot but switching x by y axes?  I did this:
`plot(tir[:IRT], rs2[:time],  size=(800,300)); hline!([DateTime(2020,4,15, 12)])`
![image](https://user-images.githubusercontent.com/24556480/219075153-a560563d-1e08-4a39-b920-f986288bf47b.png)
it does the right thing.
>

**Comment by ygol55** [comment]
Then I think I've found the problem. That's just some typo in the code that writes the vline!() command. Here's a link for a fork of Plots.jl, where I've changed what every I thought was the problem: [](https://github.com/ygol55/Plots.jl)

**Comment by ygol55** [comment]
Then I think I've found the problem. That's just some typo in the code that writes the vline!() command. Here's a link for a fork of Plots.jl, where I've changed what every I thought was the problem: https://github.com/ygol55/Plots.jl

**Comment by ygol55** [comment]
Then I think I've found the problem. That's just some typo in the code that writes the vline!() command. Here's a link for a fork of Plots.jl, where I've changed what every I thought was the problem: https://github.com/ygol55/Plots.jl, so you could run that with git

**Comment by pablosaa** [comment]
> Then I think I've found the problem. That's just some typo in the code that writes the vline!() command. Here's a link for a fork of Plots.jl, where I've changed what every I thought was the problem: https://github.com/ygol55/Plots.jl, so you could run that with git

Thanks for the effort. Unfortunately, using Plots from your fork is still producing still the same output.

**Comment by ygol55** [comment]
Do you mind sending some link to the code? That's better testing it likewise.

**Comment by pablosaa** [comment]
Here a minimal code that reproduces the issue:
```
(mytemp) pkg> st
Status `~/Downloads/temp/mytemp/Project.toml`
  [91a5bcdd] Plots v1.38.5-dev `git@github.com:ygol55/Plots.jl.git#master`
  [ade2ca70] Dates
julia> using Dates
julia> using Plots
julia> ts = range(DateTime(today()), step=Hour(1), length=24);
julia> plot(ts, 100randn(24), size=(800,300))
``` 
![without_vline_dev](https://user-images.githubusercontent.com/24556480/220160839-7520dec9-7188-460a-a005-d34cfca7ca54.png)
```
julia> vline!([now()])
```
![with_vline_dev](https://user-images.githubusercontent.com/24556480/220160963-2b6da244-19e7-497f-80fa-1774da354d5b.png)

I hope this helps better for testing.

**Comment by pablosaa** [comment]
> It seems that the problem was with the spesific treat_y_as_x, which was only used on vline but not on hline?

not really, it is in ```src/arg.jl``` that the following line has been edited:
``` 
yformatter === :auto || (plotattributes[:xformatter] = yformatter)
xformatter === :auto || (plotattributes[:yformatter] = xformatter)
```
that fix the bug #4538 but unfortunately created this bug with DataTime in x-axis now.  In earlier versions those two lines were only like this:
```
plotattributes[:xformatter] = yformatter
plotattributes[:yformatter] = xformatter
```

**Comment by gsalinasphys** [comment]
Any progress on fixing this bug?

**Comment by pablosaa** [comment]
> Any progress on fixing this bug?

No progress, unfortunately. Still the origin of this issue is on the modifications done by solving another issue https://github.com/JuliaPlots/Plots.jl/issues/4660#issuecomment-1447048915
