### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by spaette** [JuliaPlots/Plots.jl#4662]
Left for someone else to decide if .github/workflows directory files should be typo corrected.

release

```
$ grep -nr relase Plots.jl
Plots.jl/.github/workflows/ci.yml:39:            version: '1.7'  # only test intermediate relase on `ubuntu`
$ 
```

**Comment by t-bltg** [comment]
Yeah, you could have added it in https://github.com/JuliaPlots/Plots.jl/pull/4663.

Fixed by https://github.com/JuliaPlots/Plots.jl/commit/74d8d53b91ae3dbd9d6290772515def134bba3a8.
