### ISSUE TITLE
[FR] `border` and `canvas` option for UnicodePlots

### ISSUE THREAD

**Issue by baggepinnen** [JuliaPlots/Plots.jl#4675]
I noticed that UnicodePlots has a `border` option that if set to `border = :ascii` uses only ascii characters. Trying to use this with Plots.jl does not seem to have any effect
```julia
 plot(randn(10), border=:ascii)
```
looks the same as 
```julia
 plot(randn(10))
```
and uses unicode chars. Would it be possible to make this feature work? It says here that it's supposed to work, maybe I'm doing something wrong?
https://docs.juliaplots.org/stable/backends/#Supported-:subplot-:extra_kwargs-3

**Comment by baggepinnen** [comment]
Ah, I didn't understand the syntax at first, this is how you do it :) 
```julia
extra_kwargs = Dict(:subplot=>(; border = :ascii))
plot(randn(10); extra_kwargs);
```

**Comment by BeastyBlacksmith** [comment]
```julia
 plot(randn(10), border=:ascii, extra_kwargs=:subplot)
```
should also work
