### ISSUE TITLE
[BUG] Log scale axis labels not brace-wrapped in PGFPlotsX

### ISSUE THREAD

**Issue by ivan-boikov** [JuliaPlots/Plots.jl#4676]
## Details
Log scale axis labels with a power of two symbols or more is broken
```julia
using Plots
pgfplotsx()
PGFPlotsX.latexengine!(PGFPlotsX.PDFLATEX) # doubt it's relevant, but just in case - I use it
plot(
    plot([1e-5, 1e10]; title="Automatic labels",
        yticks=[1e-5, 1e0, 1e10]),
    plot([1e-5, 1e10]; title="Manual labels",
        yticks=([1e-5, 1e0, 1e10], ["\$10^{-5}\$", "\$10^{0}\$", "\$10^{10}\$"])),
    legend=:none, yscale=:log10
)
```
![image](https://user-images.githubusercontent.com/66747290/222569916-bac205f3-0437-4826-9cd9-de95f15f8ba0.png)

Looking at the generated .tex
```julia
savefig("plot.tex")
open("plot.tex") do f
    for line in eachline(f)
        i0 = findfirst("yticklabels=", line)
        i1 = findfirst("ytick=", line)
        if !isnothing(i0)
            println(line[i0[1]:i1[1]-3])
        end
    end
end
```
```
yticklabels={{$10^-5$,$10^0$,$10^10$}}
yticklabels={{$10^{-5}$,$10^{0}$,$10^{10}$}}
```
we see that the power is not wrapped automatically. 
The behavior changed between [v1.38.1](https://github.com/JuliaPlots/Plots.jl/releases/tag/v1.38.1) and [v1.38.2](https://github.com/JuliaPlots/Plots.jl/releases/tag/v1.38.2), so I suspect #4618 was almost there - the tests only covered single-digit powers.

Looks like it can be fixed here
https://github.com/JuliaPlots/Plots.jl/blob/5f29256c5e08eca051b59c61ada27b3cce129439/src/axes.jl#L115
by changing to 
```julia
Dict{Symbol,Function}(:log10 => x -> "10^{$x}", :log2 => x -> "2^{$x}", :ln => x -> "e^{$x}")
```
though it's a low-level function and I am not confident enough to open a PR.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pythonplot   |     |     | x
plotlyjs     |     |     |  x
pgfplotsx    |  x   |     |
unicodeplots |     |  x   | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: ```v1.38.6```
Backend  version (`]st -m <backend(s)>`):
```
[28b8d3ca] GR v0.71.7
[8314cec4] PGFPlotsX v1.5.3
[b8865327] UnicodePlots v3.4.0
```
Output of `versioninfo()`:
```
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 12 virtual cores
```

**Comment by ivan-boikov** [comment]
Actually, scratch that "fix", it changes font in GR to computer modern and who knows what mayhem it causes in other backends

**Comment by ivan-boikov** [comment]
Looking at it again, I think this would be a better fix: add
```
labelfunc(scale::Symbol, backend::PGFPlotsXBackend) = labelfunc_tex(scale)
```
to ```src/backends/pgfplotsx.jl```

**Comment by t-bltg** [comment]
Ping @daschw for https://github.com/JuliaPlots/Plots.jl/pull/4618.
