### ISSUE TITLE
[BUG] Surface transparency

### ISSUE THREAD

**Issue by maucejo** [JuliaPlots/Plots.jl#4683]
## Details

I don't if it's a known issue, but I am struggling with transparency with the `gr` and `pythonplot` backends.

I am trying to plot a transparent zx-plane. Here is the MWE:
```julia
using Plots

x = LinRange(0., 100., 100)
y = ones(50)

vl = LinRange(0., 1., 50)
v = repeat(vl', length(x), 1)
z = repeat(ones(length(x)), 1, length(vl)).*v

fig = plot()
surface!(y, x, z, c = cgrad([:blue, :blue]), fillalpha = 0.1, colorbar = false)
fig
``` 

With `gr`, when setting `fillalpha` to a value other than 1, the plane is not plotted. I think it is more related `GR` itself, since I receive the following warning `points not sorted in ascending order`. Note that this issue does not appear for a xy-plane.

With `pythonplot`, `fillalpha` has no effect at all, while it works well with the `pyplot` backend. This issue does not appear when I use `PythonPlot.jl` directly. (It should be noted that the figure displayed with `Plots.jl` is quite ugly compared to that obtained with `PythonPlot.jl`, but that is probably another story). This probably means that transparency is not yet implemented for `pythonplot` backend. Am I right ?

Thank you !

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pythonplot   |  x   |     |
pyplot       |     |  x   |
plotlyjs     |     |  x   |
pgfplotsx    |     |     | 
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: 1.38.6
Backend  version (`]st -m <backend(s)>`):
PythonPlot v1.0.2
PyPlot v2.11.1
PlotlyJS v0.18.10
GR v0.71.7
Output of `versioninfo()`:
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

**Comment by t-bltg** [comment]
That's probably a bug introduced when I ported the pyplot backend to pythonplot.
I'll have a look.
