### ISSUE TITLE
[BUG] Blank plot on W11 with GR backend

### ISSUE THREAD

**Issue by elvcastelo** [JuliaPlots/Plots.jl#4688]
## Details

The execution of the (minimal working example) code below opens a window with a blank plot on Windows 11. I tested the same code on Ubuntu using WSL and it works fine.

```julia
x = [1.1, 21.2, 32.8, 2.1, 24.3, 43.1, 0.8, 21.2, 28.9];
y = [10, 10, 10, 8, 8, 8, 4, 4, 4];
z = [3.2, 2.1, 0.7, 4.3, 5.2, 1.7, 2.3, 4.2, 2.0];

surface(x, y, z)
```

Using Plots `surface`:
![image](https://user-images.githubusercontent.com/27469133/224518959-6c10226e-8ba1-4e4c-976d-3a2a15feaeb2.png)

Using GR `surface`:
![image](https://user-images.githubusercontent.com/27469133/224518973-1ff8908b-8611-4fcd-a9b7-d2dafb8ae9d8.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pythonplot   |     |  x   |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

**Plots.jl version:** v1.38.5

**Backend  version (`]st -m <backend(s)>`):** GR v0.71.6

**Output of `versioninfo()`:**
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × AMD Ryzen 7 5700X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver3)
  Threads: 1 on 16 virtual cores

**Comment by t-bltg** [comment]
@jheinen, since it is reproduced in plain GR.

**Comment by jheinen** [comment]
I'll be back in office on Tuesday and try to reproduce the issue in a Windows VM.

**Comment by IngoMeyer441** [comment]
@elvcastelo I tried your example on a fresh Windows 11 with Julia 1.8.5, Plots and GR. Both Plots and GR work for me:

![Screenshot_2023-03-14_06-55-14](https://user-images.githubusercontent.com/1449087/224932166-d4e62975-683d-4c47-87fb-f91d1e1884d6.png)

![Screenshot_2023-03-14_06-53-49](https://user-images.githubusercontent.com/1449087/224932186-552a7dab-7cbd-4ffd-aee4-718f8263631a.png)

Which version of GR are you using? You get the GR C runtime version with

```julia
using GR
version()
```

**Comment by IngoMeyer441** [comment]
Maybe it is a problem related to 3D hardware acceleration. Could you try to set the environment variable

```
set GR3_USE_SR=1
```

? This forces GR to use the integrated software renderer instead of OpenGL.

**Comment by elvcastelo** [comment]
I tried setting the environment variable as described. Nothing seems to change.

As for the version of GR: 0.71.6.

**Comment by jheinen** [comment]
Could you please try to use the latest GR run-time: `] up GR` ?

**Comment by elvcastelo** [comment]
Oh, didn't notice there was an update. It is working now :) Thanks.
