### ISSUE TITLE
[BUG] Hiding axes with PGFPlotsX leaves ticks visible

### ISSUE THREAD

**Issue by JannikMen** [JuliaPlots/Plots.jl#4696]
When using keyword attributes to hide x or y axis while using PGFPlotsx backend, the ticks on the axes stay visible. There sure is a workaround but it would be convenient to have it done with a single attribute. 
The attached picture was achieved with the following input:

`x = range(0, 10, length=100)
y = sin.(x)
plot(x, y, yaxis=false, grid=false)`

But it is the same with x axis and attributes similar to `yaxis` for example `showaxis`. 

![yaxis=false](https://user-images.githubusercontent.com/126684901/225016125-b0a79aab-6922-4530-b8bd-a8f4a83c749a.PNG)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pythonplot   |     |   x  |
plotlyjs     |     |     |x
pgfplotsx    |  x   |     |
unicodeplots |     |     |x
inspectdr    |     |    |x
gaston       |     |     |x

### Versions

Plots.jl version: 1.38.6
Backend  version (`]st -m <backend(s)>`): PGFPlotsX v1.5.3
Output of `versioninfo()`:
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 12 virtual cores

**Comment by BeastyBlacksmith** [comment]
If we do it that way, how could one create a plot that has ticklabels and tickmarks, but no axis line?
