### ISSUE TITLE
Reexporting plots from a module in Jupyter

### ISSUE THREAD

**Issue by ahwillia** [JuliaPlots/Plots.jl#470]
The following code works just fine in the REPL:

``` julia
module A
    using Reexport
    @reexport using Plots
end

using A
gr()
plot(randn(10,2))
```

But gives me this warning on Jupyter notebook (version `4.2.2`)

```
WARNING: Method definition show(IO, Base.Multimedia.MIME{:text/plain}, Plots.Plot) in module Plots at /Users/alex/.julia/v0.5/Plots/src/output.jl:168 overwritten at /Users/alex/.julia/v0.5/Plots/src/output.jl:241.
```

And then I can't seem to display any plots if I use the GR backend. PyPlot seems to work though?

<img width="1008" alt="screen shot 2016-09-01 at 11 13 05 am" src="https://cloud.githubusercontent.com/assets/636625/18179027/764179d2-7035-11e6-8fe9-8137a6e8146c.png">

**Comment by fredrikekre** [comment]
It works just fine for me on both julia 0.4.6 and 0.5-rc3:

![gr](https://cloud.githubusercontent.com/assets/11698744/18245311/cfa80c02-7364-11e6-9b62-c2f1ee2dc373.png)

Jupyter version: 4.2.2-90ff4b3

**Comment by skleinbo** [comment]
I get the same warning when simply doing 
`using Plots` on `julia-0.5.0-rc3` in a Jupyter notebook.
Doesn't happen on `julia-0.4.6`.

**Comment by ahwillia** [comment]
I'm using `v0.5.0-rc1` so it is probably related to `0.5`.

**Comment by mkborregaard** [comment]
This works for me now.
