### ISSUE TITLE
UnitfulExt not working for logarithmic units

### ISSUE THREAD

**Issue by ykonter** [JuliaPlots/Plots.jl#4700]
UnitfulExt currently does not work for logarithmic units.
Example:
```Julia
using Plots
using Unitful:m, dB, dBm
plot( (1:10)m) # works
plot( (1:10)dB ) # does not work, produces error
plot( (1:10)dBm ) # does not work, produces error
```
The error reads
```
ERROR: MethodError: no method matching isinf(::Gain{Unitful.LogInfo{:Decibel, 10, 10}, :?, Int64})
```

**Comment by t-bltg** [comment]
@gustaphe

**Comment by gustaphe** [comment]
@ykonter wrote a PR on UnitfulRecipes to fix this partially about a year ago. I don't quite remember where that landed, it's possible I got caught up in completionism and forgot to merge the parts that worked.

I can see if I can find some time to look it through this weekend.
