### ISSUE TITLE
plotattr() hangs in Jupyter [BUG]

### ISSUE THREAD

**Issue by jonasaugust** [JuliaPlots/Plots.jl#4705]
## Details
Running `julia` in Terminal on macOS Big Sur, I started a Jypyter server by entering `using IJulia; notebook()` and then started a fresh notebook tab by selecting `New -> Julia 1.8.5` on the Jupyter tab newly created in my running  Firefox window.  To trigger the hang, in the code cell of that new notebook I entered `using Plots; plotattr()`.

This hang does not occur for me from the Julia REPL run from the command line (Terminal).

I wasn't sure how to find out which backend is in use.  It's whatever is default.

Installed packages:
```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [6e4b80f9] BenchmarkTools v1.3.2
  [717857b8] DSP v0.7.8
⌃ [7a1cc6ca] FFTW v1.5.0
  [5789e2e9] FileIO v1.16.0
⌃ [587475ba] Flux v0.13.12
⌃ [e9467ef8] GLMakie v0.8.2
  [cd3eb016] HTTP v1.7.4
  [7073ff75] IJulia v1.24.0
  [f332f351] ImageContrastAdjustment v0.3.10
⌅ [787d08f9] ImageMorphology v0.3.2
  [10e51d30] ImagePhaseCongruency v0.2.2
  [916415d5] Images v0.25.2
  [6fe1bfb0] OffsetArrays v1.12.9
  [91a5bcdd] Plots v1.38.8
  [27ebfcd6] Primes v0.5.3
  [5e47fb64] TestImages v1.7.1
  [d6d074c3] VideoIO v1.0.5
⌃ [e88e6eb3] Zygote v0.6.55
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pythonplot   |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version: 1.38.8
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 8 × Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores
```

**Comment by BeastyBlacksmith** [comment]
"Fixed" by https://github.com/JuliaPlots/Plots.jl/commit/26370528ae82ea6050dde4429028e07371471433
