### ISSUE TITLE
[BUG] setting of `markersize` and `markerstrokewidth` damage marker in legend

### ISSUE THREAD

**Issue by KlausC** [JuliaPlots/Plots.jl#4710]
## Details

```
julia> x, y = rand(1000), rand(1000);

julia> scatter(x, y; markersize=0.2, markerstrokewidth=6, legend=:topleft)
```

![grafik](https://user-images.githubusercontent.com/6223854/229297075-a0204adb-c732-4e97-913f-269c8f940a8f.png)

```
julia> scatter(x, y; markersize=0.02, legend=:topleft)
```

![grafik](https://user-images.githubusercontent.com/6223854/229297235-041285aa-f8b2-480d-bdef-88032d6c53ee.png)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |    x |     |
pythonplot   |     |     |x
plotlyjs     |     |    |x
pgfplotsx    |     |     |x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: [91a5bcdd] Plots v1.38.8
Backend  version (`]st -m <backend(s)>`): [28b8d3ca] GR v0.71.8
Output of `versioninfo()`:
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 6 virtual cores
Environment:
  JULIA_CPU_THREADS = 6
  LD_LIBRARAY_PATH = :/usr/local/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64:/usr/local/intel/compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = code

**Comment by BeastyBlacksmith** [comment]
Related discussion: https://github.com/JuliaPlots/Plots.jl/issues/2655

**Comment by KlausC** [comment]
This PR is about the size of the marker symbols, which are drawn inside the legend.
But it is  *not*  about how big the marker symbols should be, but *what* the size of of marker symbol is.

The symbols are (at least in case of circle shape) composed of an inner circle with radius `msz=markersize` and a surrounding stroke of width `mws=markerstrokewidth`. If the center of the stroke line coincides with the perimeter of the circle, that compound circle has a radius of `msz + 0.5mws`.
This is used to obtain the same scaling of the inner circle and the stroke, as opposed to the buggy version, which did not scale the stroke width at all.
