### ISSUE TITLE
[BUG] failed add Plots package in julia v1.8.2

### ISSUE THREAD

**Issue by qilu521** [JuliaPlots/Plots.jl#4712]
## Details
(@v1.8) pkg> add Plots
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = Could not resolve host: pkg.julialang.org while requesting https                                                                                                                                                             ://pkg.julialang.org/registries
└ @ Pkg.Registry /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/u                                                                                                                                                             sr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:68
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = Could not resolve host: pkg.julialang.org while requesting https                                                                                                                                                             ://pkg.julialang.org/registries
└ @ Pkg.Registry /cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/u                                                                                                                                                             sr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:68
     Cloning [41fe7b60-77ed-43a1-b4f0-825fd5a5650d] Unzip from https://github.co                                                                                                                                                             m/bramtayl/Unzip.jl.git
ERROR: failed to clone from https://github.com/bramtayl/Unzip.jl.git, error: Git                                                                                                                                                             Error(Code:ERROR, Class:Net, failed to resolve address for github.com: Name or s                                                                                                                                                             ervice not known)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pythonplot   |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:

**Comment by BeastyBlacksmith** [comment]
This seems like a general connectivity problem with your machine since it complains about not being able to download the registry.
Might be related to github changig its public-key but probably not to Plots.jl
