### ISSUE TITLE
[BUG][PGFPlotsX][Unitful] exponent in unit crashes lualatex

### ISSUE THREAD

**Issue by xwjqv** [JuliaPlots/Plots.jl#4722]
## Details
Latex exponents work only in math mode, which is not used by UnitfulExt.
### Example
```julia
begin
	using Plots
	using Unitful
	import PGFPlotsX
end
pgfplotsx()
plot([1u"s",2u"s"],[1u"m/s^2",2u"m/s^2"])
```
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |   x  |
pythonplot   |     |     |x
plotlyjs     |     |x   |
pgfplotsx    |  x  |     |
unicodeplots |     |   x  |
inspectdr    |     |     |x
gaston       |     |   x  |

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`): PGFPlotsX v1.5.3
Output of `versioninfo()`:
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × AMD EPYC Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 2 on 4 virtual cores
Environment:
  JULIA_REVISE_WORKER_ONLY = 1
```

**Comment by t-bltg** [comment]
For my reference:
```
using Plots, Unitful
pgfplotsx()
pl = plot([1u"s", 2u"s"], [1u"m/s^2", 2u"m/s^2"])
Plots.tex(pl, "bug.tex")
```
