### ISSUE TITLE
[BUG][PGFPlotsX][Unitful] setting axis labels duplicates units

### ISSUE THREAD

**Issue by xwjqv** [JuliaPlots/Plots.jl#4730]
When setting axis labels while using units and the PGFPlotsX backend,
the units appear twice in the label.

This probably happens because of the changes in #4723.
The units are also incorrectly italicized (maybe use [UnitfulLatexify.jl](https://github.com/gustaphe/UnitfulLatexify.jl) for it)
### Example 
```julia
using Plots, Unitful
pgfplotsx()
plot([1u"s",2u"s"],[1u"m",2u"m"],xlabel="t",ylabel="r")
````
![svg-image](https://user-images.githubusercontent.com/35635774/234439558-9ad5a851-0160-474f-8893-59016acbdca1.png)
#### crashing example
This has probably the same cause as #4722
```julia
using Plots, Unitful
pgfplotsx()
plot([1u"s",2u"s"],[1u"m/s^2",2u"m/s^2"],xlabel="t", ylabel="a")
```
### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     | x    |
pythonplot   |     |     |x
plotlyjs     |     |    x |
pgfplotsx    | x    |     |
unicodeplots |     |   x  |
inspectdr    |     |  x   |
gaston       |     |  x   |

### Versions

Plots.jl version: master
Backend  version (`]st -m <backend(s)>`): PGFPlotsX v1.5.3
Output of `versioninfo()`:
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 1700 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver1)
  Threads: 8 on 16 virtual cores
Environment:
  JULIA_REVISE_WORKER_ONLY = 1
```

**Comment by BeastyBlacksmith** [comment]
CC: @t-bltg

**Comment by t-bltg** [comment]
Hum sorry for this.

Unitful was written for GR and we never tested it on PGFPlotsX. So everything is left to be to be correctly implemented here.

There are choice to be made. I'd say that the units should be in math mode for handling braces/parens (hence rendered slightly italicized). But it's to be discussed.

Contributions welcome 🙂.

**Comment by gustaphe** [comment]
UnitfulLatexify has a recipe for `(label, unit)` tuples, so `plot(rand(5)u"m", rand(5)u"s"; unitformat=latexify, xguide="x", yguide="t")` looks good in GR. I have not tried it in pgfplotsx but perhaps that's the solution here? One of these days I may find some time to look at it.

**Comment by gustaphe** [comment]
I can't find where, but somewhere the `UnitString` guide is transformed into a `String` when using pgfplotsx.

**Comment by gustaphe** [comment]
Nvm, found it in the fix to the linked issue.

The overloading of the guide attribute is a bit of a problem: UnitfulExt uses it to store information about the axis units. It's clever, but not necessarily in the good way. 
Either pgfplotsx should change to storing the UnitfulString and transforming it at the printing point, or we should think of a less cludge way to keep track of axis units. I have no good suggestions.
