### ISSUE TITLE
[BUG] julia 1.9 - running plotly() causes all jupyter cell output to be supressed

### ISSUE THREAD

**Issue by bryaan** [JuliaPlots/Plots.jl#4739]
## Details

If you run this in a jupyter notebook cell, then nothing will show in any other cell.

Using julia 1.9-rc3

```
using Plots
plotly()
plot(x, y)
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pythonplot   |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:

**Comment by ajw-free** [comment]
I have the same problem with the Julia 1.9.0 release.
[My platform is Ubuntu Mate 23.04. Tested on Firefox browser version 113 and also Brave browser v1.51.118.]

If I load Jupyter notebook, then use Plots with plotly() backend, the code below does not display the plot object - nothing appears.

using Plots
plotly()
display(plot(rand(10)))

If I use the gr() backend, the plot image does display in the noteboook.

I should add that if I use Plots with plotly() from the command line REPL, it does work - a tab on my browser opens and displays the plot.

**Comment by ajw-free** [comment]
I compared the html code created by Jupyter Notebook (which displays nothing) with the html created from the REPL (which display properly in a browser tab).

To do this, I used savefig() to save to an html file which can be viewed in an editor.

There are differences in the first few lines which suggest that some header information is not being written.

(For gr() the files are the  same, as expected.)

To see the differences:

(1) Run this following code via the REPL:
using Plots
plotly()
p=plot(1:10)
savefig(p, "plot_from_REPL.html")
display(p)  # works and show plot in a browser tab.

(2) Run this code via Jupyter Notebook:
using Plots
plotly()
p=plot(1:10)
savefig(p, "plot_from_jupyter.html")
display(p)  # shows no display.

RESULTS 

(1) File "plot_from_REPL.html" starts with:

"<script src="https://cdn.plot.ly/plotly-2.6.3.min.js"></script>   
<div id="30958384-5167-44fe-a20a-402d93f86b5d" style="width:800px;height:300px;"></div>
etc"

(2) File "plot_from_jupyter.html" starts with:

"<div id="4708b2af-0fcd-48d0-8e3b-d902f2ca4bb6" style="width:600px;height:400px;"></div>
etc."

Clearly something is missing at the start of the html created from within the notebook.

I hope that someone can soon be allocated to fix this show-stopping bug!

**Comment by ajw-free** [comment]
As a temporary solution, one can install and use the plotlyjs() backend instead of plotly().  
It works with Julia 1.9.0 and Jupyter Notebook, and allows interactive plots.

using Pkg
Pkg.add("PlotlyJS")

From Jupyter Notebook:
using Plots
plotlyjs()
plot(rand(10))

**Comment by ajw-free** [comment]
This bug has now been fixed.  
IJulia + Plots + plotly() backend now works again after updating Ijulia from v1.24.0 to v1.24.2

You can read discussion about it here on the IJulia github issues site:
https://github.com/JuliaLang/IJulia.jl/issues/1073

**Comment by ajw-free** [comment]
This bug is currently present on MS Windows (tested 6 Sep 2023), but not on Linux.

Plotly backend does not display a plot in Jupyter notebook.

I tested on three PCs, running MS Windows 10, MS Windows 11, and Ubuntu Linux.

I did a fresh install of Julia 1.9.3 with added packages: IJulia v1.24.2 and Plots v1.32.0

On MS Windows, no output is shown within Jupyter notebook if I execute:

using Plots
plotly()
display(plot(rand(10)))

Oddly, on my Ubuntu Linux installation, running the same version of Julia 1.9.3 and updated packages, it correctly displays the plot.

I have opened a new issue on the IJulia github site https://github.com/JuliaLang/IJulia.jl/issues/1094

**Comment by Cglezf** [comment]
I have the same issue, works with gr() but not with plotly()

Julia 1.10.2
  [ad839575] Blink v0.12.9
  [7073ff75] IJulia v1.24.2
  [c601a237] Interact v0.10.5
  [f3b207a7] StatsPlots v0.15.7

MacBookPro M2
Darwin  23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:45:49 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6020 arm64

VSCode Version:
1.87.2 - arm64

Julia Extension Version:
v1.75.2 - julia-vscode.org
