### ISSUE TITLE
[BUG] Opportunity to greatly speed up plotting of many series?

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaPlots/Plots.jl#4742]
## Details
It seems like this line in [update_clims](https://github.com/JuliaPlots/Plots.jl/blob/32e2b7bcd0481bd00b05e5e78c74b5911e540640/src/colorbars.jl#L68) becomes a severe bottleneck for performance when plotting many series (according to `@profview`).

Example: 
```julia
julia>  let x = randn(20, 30000)
        @time pp = plot(x; color=:blue, label=nothing)
        @time display(pp) 
        end
137.126383 seconds (39.71 M allocations: 866.631 MiB, 0.19% gc time)
  2.766159 seconds (2.55 M allocations: 127.795 MiB)
```

From my understanding of the code, it seems that there should be some opportunity to refine the [logic which determines whether to update the colorbar](https://github.com/JuliaPlots/Plots.jl/blob/32e2b7bcd0481bd00b05e5e78c74b5911e540640/src/args.jl#L1939) since many plottypes (such as the one in the example above) does not use a colorbar.

Here is the example above when I just commented out `_update_subplot_colorbar` from the line above:
```julia
julia>  let x = randn(20, 30000)
        @time pp = plot(x; color=:blue, label=nothing)
        @time display(pp)
        end
  2.214301 seconds (39.65 M allocations: 864.800 MiB, 8.37% gc time)
  2.348212 seconds (2.55 M allocations: 127.796 MiB, 3.76% gc time)
```

Given the magnitude of the speedup it could perhaps be worth it with a little more complicated logic for the colorbar update. I haven't checked if there are better ways to improve this, such as speeding up the `update_clims` function itself. The line above does not seem to do much, but is marked as dynamic dispatch by the profiler (maybe because the properties dicts have valuetype `Any`?).

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   X  |     |
pythonplot   |     |     | X
plotlyjs     |     |     | X
pgfplotsx    |     |     | X
unicodeplots |     |     | X
inspectdr    |     |     | X
gaston       |     |     | X

### Versions

Plots.jl version:
```julia
(jl_WFAYd1) pkg> status
Status `..AppData\Local\Temp\jl_WFAYd1\Project.toml`
  [91a5bcdd] Plots v1.38.11-dev `...\.julia\dev\Plots`
```
Backend  version (`]st -m <backend(s)>`):
```julia
(jl_WFAYd1) pkg> st -m GR
Status `...AppData\Local\Temp\jl_WFAYd1\Manifest.toml`
  [28b8d3ca] GR v0.72.4
```
Output of `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.9.0-rc3
Commit 1853b90328 (2023-04-26 15:51 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 4 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by BeastyBlacksmith** [comment]
@BioTurboNick knows the most about this

**Comment by BioTurboNick** [comment]
I'll take a look today. At least in my tests I thought it was no longer the bottleneck. But also wouldn't be surprised if there was a situation where it was still a problem.

**Comment by BioTurboNick** [comment]
This is a 1.8.5 -> 1.9 regression.

```
using BenchmarkTools
const xx = randn(20, 3000)
@btime plot(xx; color = :blue, label = nothing);

# 1.8.5
# 1.214 s (392640 allocations: 31.88 MiB)

# 1.9-rc3
# 1.166 s (3964617 allocations: 86.43 MiB)
```

It doesn't take more time, oddly, but it produces 10x more allocations -- which with larger amounts would lead to GC.

Dynamic dispatch happens in both though. So that may be the primary problem. But that may not be the end of the story.

**Comment by BioTurboNick** [comment]
`@profview_allocs` output for 1.8.5 (by count):
![Screenshot 2023-05-09 105724](https://github.com/JuliaPlots/Plots.jl/assets/1438610/2c23efc5-1d12-4d00-9b03-2868e9201a48)

And for 1.9-rc3:
![Screenshot 2023-05-09 105936](https://github.com/JuliaPlots/Plots.jl/assets/1438610/5ede973c-a2af-469e-a9e2-cecf6ea62c1b)

I see `getproperty` showing up a lot, with UnknownType allocations, in 1.9-rc3.

**Comment by BioTurboNick** [comment]
The fraction of time used by `update_clims` does not scale that much with number of series - 20x3000 => 81%, 20x30000 => 95%, so at least that hasn't reverted.

I had a lot of trouble optimizing the offending method further in the past to avoid the dynamic dispatch. I'll take another stab at it though.

**Comment by BioTurboNick** [comment]
Though the ideal solution, in a future Plots 2.0, would be for colorbar data to be processed the same way as series data, with basic statistics (like extrema, quantiles, etc.) for each series computed up front. Also, moving away from the Any Dict approach.

**Comment by BioTurboNick** [comment]
Here's an example of the conundrum: If I add type annotations in `update_clims`, I can cut execution for 20x3000 input from 1.6 seconds to 1.1 seconds. But the allocation count climbs by ~ 4 million (both 1.8.5 and 1.9-rc3) and the GC runs every time.

**Comment by DrChainsaw** [comment]
It is probably hard to avoid the type instability without doing something about the untyped Dict which seems like a massive undertaking.

My angle when I wrote the issue was more that the entire operation can be skipped. Most of the code seems to be doing things with z-axes and colorbars which are not present in all plots. Isn't there somewhere in the processing where one can just bail out before touching the attribute dict?
