### ISSUE TITLE
[BUG] PGFPlotsX made breaking change in minor version -> Backend broken

### ISSUE THREAD

**Issue by xwjqv** [JuliaPlots/Plots.jl#4748]
## Details
PGFPlotsX.jl v1.6.0 does not work with Plots.jl.
I think this is because of https://github.com/KristofferC/PGFPlotsX.jl/pull/311.
They say its a braking change released it as a minor change.

## Example
This will throws an error:
```julia
using Plots
using PGFPlotsX
pgfplotsx()
plot([1,2],[3,4])
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |    x |
pythonplot   |     |  x   |
plotlyjs     |     |  x   |
pgfplotsx    |  x   |     |
unicodeplots |     |x     |
inspectdr    |     |  x   |
gaston       |     |  x   |

### Versions

Plots.jl version:v1.38.11
Backend  version : PGFPlotsX v1.6.0
Output of `versioninfo()`:
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × AMD EPYC Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 2 on 4 virtual cores
Environment:
  JULIA_REVISE_WORKER_ONLY = 1
```

**Comment by BeastyBlacksmith** [comment]
Its https://github.com/KristofferC/PGFPlotsX.jl/issues/317. Thats fixed on master and will be released once documentation is fixed
