### ISSUE TITLE
Ordering of plot elements with PGFPlotsX

### ISSUE THREAD

**Issue by gdbeck** [JuliaPlots/Plots.jl#4751]
## Details

I'm having trouble controlling the order in which series and lines are rendered using the PGFPlotsX backend.  I would like to create a plot where lines appear on top of the symbols.  The symbols seem to appear on top of the lines, however, regardless of the order in which the commands are entered.  

With GR it seems to work correctly.  This produces a plot with the symbols above the lines, as expected,

```
using Plots

x = 0:pi/8:2*pi
y = sin.(x)

gr()

p1 = plot(x,y)
p1 = scatter!(x,y)

savefig(p1,"symbols_over_lines_gr.png")
```
![symbols_over_lines_gr](https://github.com/JuliaPlots/Plots.jl/assets/20192704/26f57231-b765-4f6d-a817-56b137e222af)

and this produces a plot with the lines over the symbols, as expected.

```
p2 = scatter(x,y)
p2 = plot!(x,y)

savefig(p2,"lines_over_symbols_gr.png")
```

![lines_over_symbols_gr](https://github.com/JuliaPlots/Plots.jl/assets/20192704/c8338fe9-2f92-48b3-8420-21c2962df92f)

With PGFPlotsX, however, while this still plots the symbols over the lines, as expected,

```
pgfplotsx()

p1 = plot(x,y)
p1 = scatter!(x,y)

savefig(p1,"symbols_over_lines_pgfplotsx.png")
```
![symbols_over_lines_pgfplotsx](https://github.com/JuliaPlots/Plots.jl/assets/20192704/9f45d017-13c5-4217-8130-682d77015d70)

 this _also_ plots the symbols over the lines.

```
p2 = scatter(x,y)
p2 = plot!(x,y)

savefig(p2,"lines_over_symbols_pgfplotsx.png")
```

![lines_over_symbols_pgfplotsx](https://github.com/JuliaPlots/Plots.jl/assets/20192704/cfa175fd-76a8-42e9-acfc-966e4a87749b)

Any suggestions?  Thanks in advance for any help!

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |  x   |
pythonplot   |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |   x  |     |
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     |  x

### Versions

Plots.jl version: 1.38.8
Backend  version (`]st -m <backend(s)>`): PGFPlotsX 1.5.3
Output of `versioninfo()`: Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 8 × Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 8 virtual cores

**Comment by BeastyBlacksmith** [comment]
This is an inherent limitation of pgfplots (cf. https://github.com/pgf-tikz/pgfplots/issues/15#issuecomment-586752913).
