### ISSUE TITLE
[BUG] build GR fails on windows julia 1.9.0

### ISSUE THREAD

**Issue by mackrol** [JuliaPlots/Plots.jl#4755]
## Details
`]build GR` fails to build on windows julia 1.9 due to wrong path to 7z. In official julia 1.9 distribution for windows 7z is located in .\libexec\julia while GR expects 7z to be in .\libexec. 

```
[ Info: Downloading pre-compiled GR 0.49.0 Windows binary
ERROR: LoadError: IOError: could not spawn `'d:\Apps\julia\bin\..\libexec/7z' x downloads/gr-0.49.0-Windows-x86_64.tar.gz -y`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Union{RawFD, Base.Libc.WindowsRawSocket, IO}})
   @ Base .\process.jl:128
 [2] #760
   @ .\process.jl:139 [inlined]
 [3] setup_stdios(f::Base.var"#760#761"{Cmd}, stdios::Vector{Union{RawFD, Base.Libc.WindowsRawSocket, IO}})
   @ Base .\process.jl:223
 [4] _spawn
   @ .\process.jl:138 [inlined]
 [5] _spawn
   @ .\process.jl:133 [inlined]
 [6] success(cmd::Cmd)
   @ Base .\process.jl:536
 [7] top-level scope
   @ d:\Apps\julia\local\share\julia\packages\GR\cRdXQ\deps\build.jl:128
 [8] include(fname::String)
   @ Base.MainInclude .\client.jl:478
 [9] top-level scope
   @ none:5
in expression starting at d:\Apps\julia\local\share\julia\packages\GR\cRdXQ\deps\build.jl:74
```

Copying 7z to .\libexec "fixes" the problem.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     | 
pythonplot   |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     |x
inspectdr    |     |     |x
gaston       |     |     |x

### Versions

Plots.jl version: `[91a5bcdd] Plots v1.15.2`
Backend  version (`]st -m GR`): `[28b8d3ca] GR v0.49.1`
Output of `versioninfo()`:
```
Julia Version 1.9.0
Commit 8e63055292 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
  JULIA_DEPOT_PATH = d:\Apps\julia\local\share\julia;D:\Apps\julia\share\julia
```

**Comment by mackrol** [comment]
Upgrade to `[91a5bcdd] Plots v1.38.12` fixed the problem

**Comment by niclasmattsson** [comment]
For future users who find this thread and need to install older versions of Plots: another workaround is to copy the `libexec` folder with its `7z.exe` executable and dll from a previous Julia version into the 1.9.1 folder. So like this on Windows, assuming you installed to the default path: `C:\Users\myusername\AppData\Local\Programs\Julia-1.9.1\libexec\7z.exe`. Then builds of GR (and Blink) should succeed.
