### ISSUE TITLE
[BUG] Incorrect axes range when using `bar` with `orientation = :horizontal`

### ISSUE THREAD

**Issue by matteorossini** [JuliaPlots/Plots.jl#4756]
When using `bar` with the `orientation = :horizontal` argument, the range of the axes are not calculated correctly. This is a regression in Plots 1.38.12.

### Minimal example 1

```julia
bar(0:10:100; orientation = :horizontal)
```

Output of Plots v1.38.12:

![Plots_v1 38 12](https://github.com/JuliaPlots/Plots.jl/assets/4463904/2e76d033-d171-4852-b71e-bdec1b68636e)

Output of Plots v1.38.11:

![Plots_v1 38 11](https://github.com/JuliaPlots/Plots.jl/assets/4463904/4d512a48-fbfe-4339-9c40-3b275214ed5a)

### Minimal example 2

```julia
bar(0:0.1:1; orientation = :horizontal)
```

Output of Plots v1.38.12:

![Plots_v1 38 12_2](https://github.com/JuliaPlots/Plots.jl/assets/4463904/cabd664e-0789-49f6-b394-4cf9b185754a)

Output of Plots v1.38.11:

![Plots_v1 38 11_2](https://github.com/JuliaPlots/Plots.jl/assets/4463904/dd0c93b9-2106-4bdc-90cb-bd675635c985)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|:---:|:---:|:-------:
gr (default) |  x   |     |
pythonplot   |     |     | x
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: `1.38.12`
Backend  version (`]st -m <backend(s)>`): `GR v0.72.5`
Output of `versioninfo()`:
```
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
  DYLD_FALLBACK_LIBRARY_PATH = [...]
```

**Comment by BeastyBlacksmith** [comment]
`orientation` is deprecated, please use `permute`:
```julia
bar(0:10:100; permute = (:x, :y))
```

**Comment by themantra108** [comment]
https://themantra108.github.io/kaggle/src/bar_charts_and_Heatmaps_03x03.html
![Uploading Screenshot 2023-06-01 212826.png…]()
![Uploading Screenshot 2023-06-01 212842.png…]()

**Comment by matteorossini** [comment]
Sadly, there seem to be some problems using `permute`, too. See #4761.
