### ISSUE TITLE
PDF saving issue with GR backend

### ISSUE THREAD

**Issue by ianpgm** [JuliaPlots/Plots.jl#477]
I'm using Plots v 0.9.1, Julia 0.5 rc3 on Mac OS 10.11.6.

I make the following plot:

```
using Plots; gr()
bar(0.5:1:80.5,rand(1:1e6,80),xaxis=("%identity",(0,100),0:10:100), yaxis=("Reads",(1,1e6)), label="0-81% identity",left_margin=35px,right_margin=10px,fillcolor=:lightgrey)
```

and get the following result:
![screen shot 2016-09-09 at 10 40 02](https://cloud.githubusercontent.com/assets/2492956/18381020/7033f2fe-767a-11e6-84a2-20847870d21b.png)

When I save this as a PDF:

```
savefig("test.pdf")
```

something weird happens to the shading on the bars - they're all triangles instead of being solid light grey:
[test.pdf](https://github.com/tbreloff/Plots.jl/files/463570/test.pdf)
This is the same issue whether I look at the plot in MacOS preview, Adobe Acrobat Reader, or Inkscape.

This is only a problem when saving as PDF - saving as PNG or SVG make the plot appear correctly.

**Comment by joshday** [comment]
I'm also seeing some strange pdf behavior with GR, involving the fill alpha with ribbons.  

- Displayed:
<img width="1198" alt="screen shot 2016-12-07 at 10 00 59 am" src="https://cloud.githubusercontent.com/assets/8075494/20972828/244bbc70-bc64-11e6-8735-885f28633460.png">

- Saved to pdf:
<img width="920" alt="screen shot 2016-12-07 at 10 01 12 am" src="https://cloud.githubusercontent.com/assets/8075494/20972836/272e360c-bc64-11e6-8225-369b71cb34d1.png">

**Comment by jheinen** [comment]
This bug should finally be fixed with the latest GR master runtime.
```julia
Pkg.checkout("GR")
ENV["GRDIR"] = ""
Pkg.build("GR")
```
I'm still not satisfied with the axes layout (margins, tick marks, labels, etc.). Will be fixed (hopefully) next week ...

**Comment by jheinen** [comment]
@joshday : Could you check whether this problem still exist with `Plots` + `GR` master?

**Comment by joshday** [comment]
Yes, it looks like this is fixed.  Thank you!

**Comment by ianpgm** [comment]
This is fixed for me too.
