### ISSUE TITLE
Plotly/PlotlyJS no longer work in Jupyter

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Plots.jl#481]
The following code doesn't work in Jupyter:

``` julia
using Plots
plotly()
plot(1:10)
```

The error message is

```
Javascript error adding output!
ReferenceError: Can't find variable: Plotly
See your browser Javascript console for more details
```

It still works from the command line.  The following also works:

``` julia
using Plotly
plot(1:10)
```

**Comment by tbreloff** [comment]
Works for me.  I suspect you might need a `Pkg.build("Plots")` which downloads the plotly.js javascript file.  This will also be run if you do `using Plots; add_backend(:plotly)` in a recent Plots.  I'm trying to do "standard installs" for the backends there (especially useful for glvisualize!!)

**Comment by dlfivefifty** [comment]
Still not working.  This is on 0.4.6.  Here's the Javascipt console error:

```julia
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (plotly-latest.min.js, line 0)
[Error] SyntaxError: Unexpected token '<'
	eval (main.min.js:87:4233)
	globalEval (main.min.js:87:4233)
	text script (main.min.js:89:7066)
	fn (main.min.js:89:6715)
	k (main.min.js:89:5033)
	(anonymous function) (main.min.js:89:9154)
	send
	send (main.min.js:89:9349)
	ajax (main.min.js:89:4809)
	_evalUrl (main.min.js:88:23158)
	domManip (main.min.js:88:21382)
	append (main.min.js:88:18994)
	_safe_append (main.min.js:20238)
	append_execute_result (main.min.js:20265)
	append_output (main.min.js:20111)
	handle_output (main.min.js:20058)
	output (main.min.js:21699)
	_handle_output_message (main.min.js:23317)
	i (main.min.js:87:5494)
	_handle_iopub_message (main.min.js:23344)
	_finish_ws_message (main.min.js:23181)
	(anonymous function) (main.min.js:23172)
	promiseReactionJob
[Log] ReferenceError: Can't find variable: Plotly (main.min.js, line 20240)
eval code
eval
globalEval — main.min.js:231:163
domManip — main.min.js:1935:150
append — main.min.js:1852
_safe_append — main.min.js:36395
append_execute_result — main.min.js:36422
append_output — main.min.js:36263
handle_output — main.min.js:36210
output — main.min.js:37912
_handle_output_message — main.min.js:39614
i — main.min.js:300
_handle_iopub_message — main.min.js:39641
_finish_ws_message — main.min.js:39458
(anonymous function) — main.min.js:39446
promiseReactionJob
```

**Comment by rand5** [comment]
I am getting this same error as @dlfivefifty with the `plotlyjs()` backend. It seemed to come out of nowhere, as Plots had been working fine minutes previously. After restarting Julia and returning to the same notebook, the error was still there, however when I opened a new notebook and reran the plot commands, the backend was back to functionality

**Comment by awd97** [comment]
I get the same error message as the OP in Jupyter but at a different time, and with both plotly and plotlyjs backends. Everything works fine until I exit the notebook. On opening it again, all of the plots show this "ReferenceError: Can't find variable: Plotly" error. If I run the cells, the plots show again (replacing the error messages). If I try to view the notebook with nbviewer, no plots show (e.g. [see here](http://nbviewer.jupyter.org/github/biospi/seamass/blob/mzMLb_refactor/julia/plotly.ipynb))

I'm using Julia 0.5 and with a barebones environment of IJulia 1.3.2 and Plots 0.9.3.

**Comment by threaz** [comment]
Well, I have no idea why is this solution working, but when I'm launching jupyter notebook with `ijs` command it always seems to work. You can try it by yourself.

**Comment by ChrisRackauckas** [comment]
> This is on 0.4.6.

Probably a v0.4 error? I cannot reproduce on v0.5.

**Comment by mkborregaard** [comment]
Fixed.
