### ISSUE TITLE
[FR] Make `PythonPlot v1.0.3` compatible

### ISSUE THREAD

**Issue by jamblejoe** [JuliaPlots/Plots.jl#4841]
Starting a fresh Julia-1.9 session with adding `Plots` and `PythonPlot` shows an incompatibility warning: 
```
PythonPlot` 1.0.3 is not compatible with this version of `Plots`. The declared compatibility is 1 - 1.0.2.
```
Can we extend the compatibility to `PythonPlot v1.0.3`?

**Comment by BeastyBlacksmith** [comment]
depends on if the reasons of https://github.com/JuliaPlots/Plots.jl/pull/4815 still apply

**Comment by isentropic** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/4861

**Comment by isentropic** [comment]
Yeah I don't know why is it failing https://github.com/JuliaPlots/Plots.jl/pull/4864

**Comment by isentropic** [comment]
@yha any help would be appreciated

**Comment by BeastyBlacksmith** [comment]
See https://github.com/JuliaPy/PythonPlot.jl/pull/26#issuecomment-1556799332, it's not something we can fix on the Plots side of things. However, we still need to find a way to pin the matplotlib version used.
