### ISSUE TITLE
Warning: _display is not defined for this backend.[BUG]

### ISSUE THREAD

**Issue by dtxl** [JuliaPlots/Plots.jl#4857]
## Details
Installed julia 1.10.0 (on macOS Ventura 13.6.3).

Running a code via Visual Studio Code 1.85.1, the Plot by "plotlyjs()" doesn't appear, but the error message

Warning: _display is not defined for this backend.
@Plots ~/.julia/packages/Plots/sxUvK/src/output.jl:211

With the Julia version 1.9.4 it worked yesterday.

### Backends
I run: test _backend_ and for "test UnicodePlots", "test PythonPlot", "test PGFPlotsX", "test InspectDR", "test Gaston" it gives:

Error: The following package names could not be resolved:
* _package_ (not found in project or manifest)

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
GR (default) |     |   x  |
PythonPlot   |     |     | x
PlotlyJS |     |   x  |
PGFPlotsX    |     |     | x
UnicodePlots |     |     | x
InspectDR    |     |     | x
Gaston       |     |     | x

### Versions

Plots.jl version: 1.39
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:

Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-apple-darwin22.4.0)
  CPU: 12 x Intel(R) Core(TM) i9-8950HK CPU @ 2.490GHz
  WORD SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
  DYLD_FALLBACK_LIBRARY_PATH = /Users/admin/.julia/artifacts/979f68ce65b087a39297a97d21aec04b1d4e9d24/lib:/Users/admin/.julia/artifacts/1e901863cf8fbb1ee50a5d0976114a2371899331/lib:/Users/admin/.julia/artifacts/dcc1b7719d5a106fba77bbc272d231e163d15fe5/lib:/Applications/Julia-1.10.app/Contents/Resources/julia/lib/julia:/Users/admin/.julia/artifacts/a60754b0168c9c5f8d34486c57ce80321b8754bf/lib:/Users/admin/.julia/artifacts/397fee52d94fc3404c3e466a6a8277ad9fdde715/lib:/Users/admin/.julia/artifacts/d2ea466e9d726fe2dc83e2179336f2098f5724a2/lib:/Users/admin/.julia/artifacts/ffdee4f2c5c1a970450976825cd6df5b97916b5d/lib:/Users/admin/.julia/artifacts/442f23eefa35ed5c63dc3f9611371b3121d7ceff/lib:/Users/admin/.julia/artifacts/e5ac181e50b3e64030971ff097b6543cdb2b341b/lib:/Users/admin/.julia/artifacts/20698543a2b5e0bb910a56e8d969e88813ecc411/lib:/Users/admin/.julia/artifacts/4bebc91892ecb81a8854e8b28747c03f9ee97628/lib:/Users/admin/.julia/artifacts/2cb0d96a63120d1a0868c905452895a59add9a0d/lib:/Users/admin/.julia/artifacts/f9fc72c9167a476e5c5fec8942270c90e0ffc796/lib:/Users/admin/.julia/artifacts/ed6b32736e29cb60fa5bf838e140f50a6f4e09e6/lib:/Users/admin/.julia/artifacts/946f590bc9f9b0b0b7978a8481f067c6e611c522/lib:/Users/admin/.julia/artifacts/fb5ebcbea6d2f03cf79fe1bf6aa237f4929b1d2d/lib:/Users/admin/.julia/artifacts/3a10d140fdfe84ac9bebb570319e9d173d5c7e6c/lib:/Users/admin/.julia/artifacts/f9f9209aaba179c03a71fa49432487fbe41daac8/lib:/Users/admin/.julia/artifacts/d4387ba5551f47f3733c2b041a7745c29b35c26e/lib:/Users/admin/.julia/artifacts/fe0276d289339d47a28d300125365cc9bcd019b7/lib:/Users/admin/.julia/artifacts/13d72f9c10469b24ae6ed7dd1a3b2ab5338ae2ab/lib:/Users/admin/.julia/artifacts/572714f8bb8cb23efde4bcd230b638bc3cd7ef00/lib:/Users/admin/.julia/artifacts/e82fc967ae7f655963b97d4565e3a93c74bd38fa/lib:/Users/admin/.julia/artifacts/966098580a6feebc43e729bf20dbb97848be4663/lib:/Users/admin/.julia/artifacts/bbb69711f9eab313bab4f202da8fbae8c1914a96/lib:/Users/admin/.julia/artifacts/35f6deff925776aba1b5eebcf8a2105f89887d70/lib:/Users/admin/.julia/artifacts/a50227ae6f693d36e10f6515b7b5d601791f2d20/lib:/Users/admin/.julia/artifacts/ab49fb08fb4494ca6d30bd5124515c4b34ca6c9b/lib:/Users/admin/.julia/artifacts/9fc071d4d02693a94bf56670806ecdb81b3a2d5d/lib:/Users/admin/.julia/artifacts/bafe3cd52ce2d05cf3aade22f2290fc0d3841de8/lib:/Users/admin/.julia/artifacts/d3f66a1beb37e7d6778ecff998c64c2807d19c9f/lib:/Users/admin/.julia/artifacts/fcce09ea10f6f2d6e185d17a8123a0054d18c1b4/lib:/Users/admin/.julia/artifacts/ea3868d6f6440a23ac0ae1de3f0585928fe93ed3/lib:/Users/admin/.julia/artifacts/20ac6b26294e1f68a703d5d75d1364ce3ec14c2d/lib:/Users/admin/.julia/artifacts/912eff7e041876f3994e732ccdfe3cd44b7664e2/lib:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtConcurrent.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtCore.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtDBus.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtGui.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtNetwork.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtOpenGL.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtPrintSupport.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtSql.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtTest.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtWidgets.framework/Versions/A:/Users/admin/.julia/artifacts/ad6d90720961deee1ccd3b65a3695c856b32595a/lib/QtXml.framework/Versions/A:/Users/admin/.julia/artifacts/d9bcd57b8aec083a17e5ed7efd1ea8c723618613/lib:/Applications/Julia-1.10.app/Contents/Resources/julia/bin/../lib/julia:/Applications/Julia-1.10.app/Contents/Resources/julia/bin/../lib:

**Comment by dtxl** [comment]
With the same installation of julia 1.10.0, on Win10 when loading PlotlyJS, the error message is

┌ Warning: Kaleido is not available on this system. Julia will be unable to save images of any plots.
└ @ PlotlyJS C:\Users\lothomas\.julia\packages\PlotlyJS\qhYQ5\src\kaleido.jl:65
┌ Warning: ErrorException("Could not start Kaleido process")
└ @ PlotlyJS C:\Users\lothomas\.julia\packages\PlotlyJS\qhYQ5\src\kaleido.jl:66

But kaleido.exe is in C:\Users\_username_\.julia\artifacts\7914a56da888d6a06d00c87f97e873c60e97acc7\bin

**Comment by dtxl** [comment]
During julia code execution on macOS, the message

┌ Warning: backend 'PlotlyJS' is not installed
└ @ Plots ~/.julia/packages/Plots/sxUvK/src/backends.jl:43

but PlotlyJS is installed and has been loaded.

**Comment by BioTurboNick** [comment]
Hmm, I tried to reproduce on Windows 11 and it seems that Julia hangs when loading PlotlyJS. When I interrupt I get the "Kaleido is not available" message. But that may be a PlotlyJS.jl issue, not a Plots.jl issue.

Which is reported here: https://github.com/JuliaPlots/PlotlyJS.jl/issues/479

**Comment by dtxl** [comment]
Yes, that is a  PlotlyJS issue. I have reinstalled Julia 1.9.4 and the error message is now under Win10 and macOS
┌ Warning: backend `PlotlyJS` is not installed.
└ @ Plots C:\Users\username\.julia\packages\Plots\sxUvK\src\backends.jl:43
but PlotlyJS works.

**Comment by dtxl** [comment]
Since https://github.com/JuliaPlots/PlotlyJS.jl/issues/479 has been closed, I'm closing it here too.
