### ISSUE TITLE
Not compatible with julia 1.10, Last update is August 30 2023.

### ISSUE THREAD

**Issue by MrBenzWorld** [JuliaPlots/Plots.jl#4858]
It looks like julia developers stopped working or not working on it. plot.jl was updated on August 30. 

There is no update till Today December 30th. 

It is extremely worrying for julia users

**Comment by BioTurboNick** [comment]
This isn't that helpful an issue. Not compatible in what way? I'm using it on Julia 1.10 as we speak.

Can you please be more specific about what isn't working, error messages, etc.?

**Comment by MrBenzWorld** [comment]
Plots.jl is not precompiling, artifacts access denied. etc. ( windows 11)
![Screenshot 2024-01-10 230043](https://github.com/JuliaPlots/Plots.jl/assets/113277019/fa8010f6-4a52-4c37-9bfc-c589ff1547b4)

"
 Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to "C:\\Users\\Sky\\.julia\\compiled\\v1.10\\Plots\\jl_C13D.tmp".
ERROR: LoadError: InitError: could not load library "C:\Users\Sky\.julia\artifacts\13606487e48c4dea9d20813adf4f03a3edea59fd\bin\libgio-2.0-0.dll"
Access is denied.
"
@BioTurboNick

**Comment by BioTurboNick** [comment]
Thanks for the detail! "Access is denied" suggests a folder permissions issue... Is it just Plots? If you remove Plots and try to just install, say FFMPEG, would it do the same thing?

**Comment by MrBenzWorld** [comment]
It is a problem with Plots.jl  only. PlotlyJS.jl is working well. 
Removed all packages , reinstalled , but no use. 

1.10 rc2 was working well with Plots.jl.

**Comment by BioTurboNick** [comment]
The reason I bring up FFMPEG is because it is shown as failing in the screenshot, and it is an depedency of Plots. There may be a broader issue with the`_jll` dependencies.

**Comment by MrBenzWorld** [comment]
Correct , There is a problem with its dependaries.  All red cross marked dependent package artifacts are access denied.

**Comment by BioTurboNick** [comment]
Right, so it probably is a problem with your Julia install. There may be a more careful way to address this, and you could ask over on Discourse (https://discourse.julialang.org/) or in Slack `#heldesk`, but my personal instinct would be to exit Julia, delete (or rename) the `.julia` folder and then let Julia regenerate it from scratch.

**Comment by BioTurboNick** [comment]
And just to be sure, make sure Julia isn't running as Administrator.

**Comment by MrBenzWorld** [comment]
I found the problem. I have deleted all julia related folders after uninstalling. I have installed many versions in the past, 1.10 rc1, rc2 .... 

Have done a fresh install, now it is working. There must be a "delete all" or  "complete clean" option. 
Anyway thank you.
