### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ivanuricardo** [JuliaPlots/Plots.jl#4859]
**Describe the bug**
I have recently upgraded to Julia 1.10 and installed Plots 1.39.0 along with PlotlyJS 0.18.11. Then running 
`JULIA_PKG_PRECOMPILE_AUTO=0 julia -e 'import Plots; Plots.set_default_backend!(:plotlyjs)'`
gives me the error 
```
LoadError: Creating a new global in closed module `Main` (`PlotlyJS`) breaks incremental compilation because the side effects will not be permanent.
```

I then can not change back to the default gr() backend and I am unable to use the Plots package for anything. 
On the other hand, running 
```
using PlotlyJS
plot(randn(10))
```
does run fine with no errors, and I can plot with this. 

**Version info**
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 13th Gen Intel(R) Core(TM) i5-1340P
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, goldmont)
  Threads: 1 on 16 virtual cores

Status `~/.julia/environments/v1.10/Project.toml`
⌅ [28b8d3ca] GR v0.72.10
  [23fbe1c1] Latexify v0.16.1
  [f0f68f2c] PlotlyJS v0.18.11
  [91a5bcdd] Plots v1.39.0
  [49802e3a] ProgressBars v1.5.

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |     |     |
pythonplot   |     |     |
plotlyjs     |  x   |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

**Comment by BioTurboNick** [comment]
Related to #4865. Workaround is to use GR as default but switch after loading, as you saw.
