### ISSUE TITLE
PythonCall.pyisnone() does not exist, please remove it from source code

### ISSUE THREAD

**Issue by Deduction42** [JuliaPlots/Plots.jl#4906]
I'm running into an issue where the PythonPlot.jl backend is unusable. I keep getting the error 
```ERROR: UndefVarError: `pyisnone` not defined```
Sure enough, PythonCall.pyisnone does not exist. It was used in the following line.
https://github.com/JuliaPlots/Plots.jl/blob/2e9b16c87254ee7b588927d932782ad506db0f6a/src/backends/pythonplot.jl#L219

**Comment by BoundaryValueProblems** [comment]
@Deduction42, see the thread #4905 for the possible solution.
