### ISSUE TITLE
[BUG] Huge vertical margin of `plot_title`

### ISSUE THREAD

**Issue by abehersan** [JuliaPlots/Plots.jl#4912]
## Details

I updated `Plots` and `StatsPlots`. Now there is a massive separation between a general title and the rest of the grid.
See for example:

```julia
using Plots

p1 = scatter(rand(5, 1), title = "Subplot 1")
p2 = scatter(rand(5, 1), title = "Subplot 2")
plot(p1, p2, layout=(1, 2), plot_title="Plot title")
```

![bug](https://github.com/JuliaPlots/Plots.jl/assets/60815415/ae678af0-fa5e-47b3-addb-a9e8056f1f94)

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |   x  |     |
pythonplot   |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version:
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`: v0.73.3

**Comment by zauster** [comment]
+1

**Comment by zauster** [comment]
That must be the version of GR, as I have the same:

`
st -m GR
`

yields

`
  [28b8d3ca] GR v0.73.3
`

and `versioninfo()` yields for me

```
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 6 × AMD Ryzen 5 4500U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 6 virtual cores)
Environment:
  JULIA_ERROR_COLOR = red
  JULIA_NUM_THREADS = 1
```

**Comment by abehersan** [comment]
My bad, `v0.73.3` is indeed of GR.

**Comment by BeastyBlacksmith** [comment]
What is your Plots Version?

**Comment by zauster** [comment]
> I have this same issue with Plots **v1.40.3**.
> 
> EDIT: I don't seem to have this issue with _v1.40.2_.

I can confirm this. I downgraded to 1.40.2 and this huge vertical space is no longer included in my plots.

**Comment by ktitimbo** [comment]
Any way to fix this other than downgrading? I added a full-width phantom plot with only the title, it gives the desired output, but this is far from the ideal
