### ISSUE TITLE
Automate color changing line plot creation on pyplot and plotly

### ISSUE THREAD

**Issue by lstagner** [JuliaPlots/Plots.jl#492]
Right now its a bit of a pain to create a color changing line plot

``` julia
using Plots; pyplot()
n = 10; x = linspace(0,1,n); y=cumsum(rand(n));
newx = vec(hcat(x[1:end-1],x[2:end],fill(NaN,n-1))');
newy = vec(hcat(y[1:end-1],y[2:end],fill(NaN,n-1))');
plot(newx,newy,line_z=1:n, w=5)
```

![image](https://cloud.githubusercontent.com/assets/4305891/18598787/866790f0-7c09-11e6-8bfb-4f36577b991b.png)

This process could probably be automated

**Comment by SimonDanisch** [comment]
Btw, GLVisualize supports to pass colors for every point in the line ;) This is why I have `color_map` and `color` to be different keys, so I can differentiate between these two use cases. Should we expose this in Plots.jl in the same manner?

**Comment by daschw** [comment]
With GR this is now possible on master with just
```julia
using Plots; pyplot()
n = 10; x = linspace(0,1,n); y=cumsum(rand(n));
plot(newx,newy,line_z=1:n, w=5)
```
cf. https://github.com/JuliaPlots/Plots.jl/pull/1110

**Comment by mkborregaard** [comment]
Nice! close?

**Comment by daschw** [comment]
It's not working on pyplot yet, my fault, it only works on gr:
```julia
using Plots; gr()
n = 10; x = linspace(0,1,n); y=cumsum(rand(n));
plot(newx,newy,line_z=1:n, w=5)
```

**Comment by mkborregaard** [comment]
This works now
