### ISSUE TITLE
[BUG] Misleading behaviour when plotting complex numbers when real part may be 0

### ISSUE THREAD

**Issue by macmyn** [JuliaPlots/Plots.jl#4944]
## Details
My script produces a set of complex numbers where the imaginary part is caused by statistical noise in the system. Some of my simulations have precisely zero noise and I couldn't understand the results. It turns out that these simulations produced real numbers, and the default behaviour of `scatter()` is different two cases:
``` julia
using Plots

reals = [1.1,2.2,3.3,4.4]
comps = [1.1+0im, 2.2+0im, 3.3+0im, 4.4+0im]

scatter(reals)
scatter!(comps)
```

I understand the reason for these outcomes separately (plotting complex numbers giving the complex plane; plotting a sequence of reals giving integers on the x-axis) so I don't know what the best solution is here. 

More rigorous type-checking on my part might have caught this for me, but it does feel misleading when the numerical values that are being plotted are precisely the same. Perhaps this just has to be left as-is, but maybe this could be an example/warning in the docs?

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x   |     |
pythonplot   | x    |     |
plotlyjs     |     |     | x
pgfplotsx    |     |     | x
unicodeplots |     |     | x
inspectdr    |     |     | x
gaston       |     |     | x

### Versions

Plots.jl version: v1.40.4
Backend  version (`]st -m <backend(s)>`): GR v0.73.5, PyPlot v2.11.2
Output of `versioninfo()`:

**Comment by isentropic** [comment]
It's better to check the tolerances and create a wrapper of your array on your end.
Plots just checks the type of the container and dispatches on the corresponding recipe

**Comment by isentropic** [comment]
something like
```julia
is_actually_real(array) = ... # check if its real
wrap_array(array) = is_actually_real(array) ? real.(array) : array

reals = [1.1,2.2,3.3,4.4]
comps = [1.1+0im, 2.2+0im, 3.3+0im, 4.4+0im]

scatter(wrap_array(reals))
scatter!(wrap_array(comps))

```
