### ISSUE TITLE
Remove individual axis borders 

### ISSUE THREAD

**Issue by grero** [JuliaPlots/Plots.jl#500]
Setting border=false removes all borders, but it would be useful to be able to remove only some borders, e.g. only the upper and right border, in a plot. My personal preference is to only show the left and bottom border. In Winston, I'd do this

```
p = Winston.plot([1,2,3],[3,4,5])
Winston.setattr(p.frame, "draw_axis", false)
```

**Comment by mkborregaard** [comment]
I'd say this has been fixed by the new `framestyle` keyword https://github.com/JuliaPlots/Plots.jl/pull/1029
