### ISSUE TITLE
[BUG] Installing `Plots.jl` still leaves files behind

### ISSUE THREAD

**Issue by giordano** [JuliaPlots/Plots.jl#5020]
## Details

> Why this is still an issue in [v1.40.8](https://github.com/JuliaPlots/Plots.jl/releases/tag/v1.40.8) which was released 7 months after #4870 was merged?

_Originally posted by @giordano in https://github.com/JuliaPlots/Plots.jl/issues/4869#issuecomment-2465651644_

### Backends

Irrelevant

### Versions

Plots.jl version: v1.40.8
Backend  version (`]st -m <backend(s)>`): irrelevant
Output of `versioninfo()`: irrelevant

**Comment by t-bltg** [comment]
Could you precise which files are left behind in which context ?

> The way you're using tempname(), by not using the name as is but appending an extension, causes the cleanup of the file to never happen, and so repeatedly precompiling the package causes lots of files to pile up, especially on shared systems which are reboot infrequently.

We are using `tempname()` here together with [`mktempdir`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.mktempdir-Tuple{AbstractString}) with the default `cleanup = true` option set:
`scratch_dir = mktempdir()` ... `fn = joinpath(scratch_dir, tempname())`, so AFAIK, `scratch_dir` is deleted upon exit, hence no files are left behind ?

**Comment by t-bltg** [comment]
I see, we probably miss `tempname(parent = scratch_dir)` instead.

**Comment by giordano** [comment]
> Could you precise which files are left behind in which context ?

When I install `Plots.jl` and it has to be precompiled, two files with temporary base names and extension png are still left in `/tmp`, which is the issue described in #4869: attaching an extension to `tempname()` makes it so the file is never cleaned up automatically by Julia. To reproduce it: precompile `Plots.jl` and observe that there are leftovers in tempdir.

This issue is particularly annoying on shared systems which are rebooted infrequently and so the temporary files only keep accumulating.

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/5023, also tested locally by inspecting `/tmp`.

The claimed fix implemented in https://github.com/JuliaPlots/Plots.jl/pull/4870 was wrong.

Please try the new version `1.40.9` and report ?

**Comment by giordano** [comment]
I confirm this seems to be fixed now, thanks!
