### ISSUE TITLE
Bar Plots gone Awry in v0.6

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#504]
Something's up with bar plots. Test command:

``` julia
bar(randn(99))
```

 Plotly and PlotlyJS work. But in PyPlot I get:

![bar](https://cloud.githubusercontent.com/assets/1814174/18826316/ac6785ba-8381-11e6-82ee-d57faa879bb9.png)

I get similar blankness from GR.

**Comment by tbreloff** [comment]
Works for me...

**Comment by ChrisRackauckas** [comment]
I was thinking it was on the Plots master. Turns out, it's a v0.6 issue: it's working for me on v0.5.

**Comment by mkborregaard** [comment]
This is still an issue, rendering bar plots and histograms unusable in 0.6

**Comment by mkborregaard** [comment]
Fixed now.
