### ISSUE TITLE
Add `widen` keyword argument

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#511]
Bar plots in the pyplot and gr backends fit the bars exactly to the sides of the subplot, which is not very aesthetically nice. I would suggest adding an option to
- [ ] widen the plot along the x axis to give a little space on each side of the bars
- [ ] widen the plot along the top, but not the bottom of the y axis for bar plots and histograms, to give a little space there.

On gitter I mentioned the specification for this general type of behaviour in R:

```
‘xaxs’ The style of axis interval calculation to be used for the
x-axis. Possible values are ‘"r"’, ‘"i"’, ‘"e"’, ‘"s"’,
‘"d"’. The styles are generally controlled by the range of
data or ‘xlim’, if given.
Style ‘"r"’ (regular) first extends the data range by 4
percent at each end and then finds an axis with pretty labels
that fits within the extended range.
Style ‘"i"’ (internal) just finds an axis with pretty labels
that fits within the original data range.
Style ‘"s"’ (standard) finds an axis with pretty labels
within which the original data range fits.
Style ‘"e"’ (extended) is like style ‘"s"’, except that it is
also ensures that there is room for plotting symbols within
the bounding box.
Style ‘"d"’ (direct) specifies that the current axis should
be used on subsequent plots.
(Only ‘"r"’ and ‘"i"’ styles have been implemented in R.)
```

One issue is that the seriestype is not always known at the time of calling the backend(?), so it is difficult to give barplots a special behaviour (in this case, not giving space on the bottom of the y axis) compared to other plot types.

An example here of a really simple barplot as they often look (from today's Nature)
![simple barplot example](https://cloud.githubusercontent.com/assets/8429802/18989981/5ad9cd2a-870f-11e6-8073-d0cc7645ca00.png)

**Comment by mkborregaard** [comment]
gr() leaves no space between bars either, which is misleading - that should be standard behaviour for histograms, but never bar plots, as bars represent categorical variables.

**Comment by tbreloff** [comment]
This was my earlier thinking:

> maybe it can be an axis attribute widen, defaulting to :auto which keeps current behavior, true would always widen, false would never, and a number would widen by that percentage?

**Comment by mkborregaard** [comment]
Oh, yes, that bit from our gitter chat was important to include here. That is a great interface I think. `:top_and_sides` might be the interface for what I suggest for bar plots?

**Comment by pfitzseb** [comment]
What would you think about doing this the like css: `widen` is a tuple with either 
- length 1: use that value on all sides
- length 2: use the first value for top/bottom, second one for left/right
- (length 3): specify top and bottom separately, use the second value for left/right
- length 4: specify top/right/bottom/left separately

Either of those entries could then be `:auto` as well. So `(:auto, 0.04)` to widen horizontally by four percent and keep the default vertically.

**Comment by tbreloff** [comment]
Yes I think `widen = (:auto, 0.04)` is the right sort of interface, where `widen = x` maps to `widen = (x,x)`.  The length 3/4 are unnecessary because this would be an **axis** attribute, which means each axis can have its own values.  To set all 4, you'd do: `xwiden = (left,right), ywiden = (bottom,top)`

**Comment by mkborregaard** [comment]
I don't think the user needs so fine control in most cases. I think the defaults would be the most important, as in the cases where the users wants control he can use the xlim and ylim argument explicitly. A value such as `widen = (:auto, 0.04)` would most likely be most used in setting global plot defaults. In most cases the y axis should have a top value of some equal tick mark, eg 50 or 1000. In bar plots, the lowest should always be 0 - always starting the 0 axis at zero could be an easily set option - it is actually in practice used too little, as it is often appropriate!

**Comment by tbreloff** [comment]
> I don't think the user needs so fine control in most cases

1) Don't assume what people will want
2) Remember this needs to support everything the user will want to explicitly set **and**  everything we might set inside a recipe

**Comment by mkborregaard** [comment]
1) OK I can see the wisdom in that.
2) I didn't think of that, recipes are a really good reason to give the user deep control.
Still, I'd say that a number of semiautomatic (magic) default setting options to handle the most common use cases, in addition to that fine control, would be really nice.

**Comment by tbreloff** [comment]
> Still, I'd say that a number of semiautomatic (magic) default setting options to handle the most common use cases, in addition to that fine control, would be really nice.

Well that sums up the goal of Plots :+1:

**Comment by mkborregaard** [comment]
Close as everything is now widened by default?
