### ISSUE TITLE
UnicodePlot Backend in Jupyter Notebook

### ISSUE THREAD

**Issue by cc7768** [JuliaPlots/Plots.jl#525]
The `UnicodePlots` backend might be having some trouble in the notebook.

I couldn't find an issue, so I thought I'd raise a new one. Could totally be just me though.

```
using Plots
unicodeplots()
plot(rand(10))
```

This gives me an SO error in a notebook, but produces a plot in the REPL (`UnicodePlots.scatterplot(rand(10))` successfully produces something in the notebook).

**Comment by jssk6** [comment]
Plot{Plots.UnicodePlotsBackend() n=1} 
I got like this but in cmd window it is working
