### ISSUE TITLE
julia 1.9.4 crashes with corrplot >11 columns

### ISSUE THREAD

**Issue by smartinsightsfromdata** [JuliaPlots/Plots.jl#5288]
I run the code below:

```
using MLDatasets: BostonHousing
using DataFrames
using StatsPlots

dataset = BostonHousing()

df = dataset.features


gr(size = (1400,1400))
@df df corrplot(cols(1:11), grid = false)
```
The code above works fine (apart  issue https://github.com/JuliaPlots/Plots.jl/issues/5443  with no colors on the right end side - the workaround works only partially), but the dataframe df has 14 columns (and R manages to produce correct corr plots with all of the columns for this notorious dataset),

If I try with 12 columns ```@df df corrplot(cols(1:12), grid = false)```

**julia crashes and hangs** with the following messages:
```
double free or corruption (!prev)

[358911] signal (6.-6): Aborted
in expression starting at none:0
```
I run julia on ubuntu 23.04 on a single thread.  After the above message julia REPL becomes completely unresponsive.

**Comment by jheinen** [comment]
With the following command, I get the same plot in `GR` as with `PythonPlot`:
```
@df df corrplot(cols(1:13), grid = false, fillcolor=:viridis)
```
Does not crash or freeze.
