### ISSUE TITLE
How to close the plot window from command line

### ISSUE THREAD

**Issue by pagnani** [JuliaPlots/Plots.jl#532]
Dear Tom and the rest,

Thanks for this very useful package. Is there a way to close window from command-line? Something like close("all") or close() in PyPlot. I tried hard to figure out from docs with no success.

Thanks 

Andrea

**Comment by tbreloff** [comment]
There wasn't, but I just added `closeall()` to the dev branch.  It will only work on GR/PyPlot until I figure out how to do it for the others.

**Comment by pagnani** [comment]
Thanks Tom,

I will checkout the development version

A

**Comment by spencerlyon2** [comment]
For PlotlyJS you can do `close(p::SyncPlot)` to close the display

**Comment by SimonDanisch** [comment]
for GLVisualize you can do destroy!(plot.o) .... I think I should rename this function to close as well, though ;)
