### ISSUE TITLE
Plots.gui() doesn't display the GUI window in Juno

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#537]
`Plots.gui()` no longer opens up a GUI for GR and PlotlyJS in Juno. Looks like there was a change to the rendering which makes the console now capture and "display" it? @MikeInnes @pfitzseb

![output](https://cloud.githubusercontent.com/assets/1814174/19410923/3cd2bfe6-92ac-11e6-946d-88b4aa99d541.PNG)

**Comment by pfitzseb** [comment]
I've only checked for the GR case, but it seems like the right methods in Plots.jl are called (meaning [`_display(plt::Plot{GRBackend})`](https://github.com/tbreloff/Plots.jl/blob/d291582ad974dd9c8ee9c54884d88b8cd1123b7f/src/backends/gr.jl#L1063)).
So yeah, not sure what's wrong here, but for once it might not be Juno's fault...

**Comment by ChrisRackauckas** [comment]
Fixed.
