### ISSUE TITLE
Using scientific formatter results in missing unicode symbols

### ISSUE THREAD

**Issue by Tyde** [JuliaPlots/Plots.jl#551]
I want to plot really small numbers as in this example:

``` julia
using Plots
pyplot()
x = linspace(0,10,1000);
y = sin(x)*5e-6;
plot(x,y,formatter=:scientific)
```

What results from this is the following graphic:

![index](https://cloud.githubusercontent.com/assets/1103207/19645825/0ef51478-99f7-11e6-8f8e-90bd3603a6ec.png)

As you can see, it does not show the exponents of the ticks correctly.

This happens on windows with an IJulia notebook.

**Comment by daschw** [comment]
This seems to be fixed.
