### ISSUE TITLE
Ribbon functionality in plotlyjs()

### ISSUE THREAD

**Issue by rand5** [JuliaPlots/Plots.jl#565]
Basic ribbon functionality such as `plot(rand(10),ribbon=rand(10))` works in `gr()` and `pyplot()`, but is ignored in `plotlyjs()` with `WARNING: fillrange ignored... plotly only supports filling to zero. fillrange:...`

**Comment by tbreloff** [comment]
For whoever tries to fix this (probably me :(, the likely solution is going to be to add a `:shape` series with `primary=false` with the fill/ribbon.

**Comment by piever** [comment]
I had the same issue and there is a possible work-around, as PlotlyJS.jl can do area plots (which can be called from Plots.jl). So the following will draw a shaded error-bar (but is not an ideal solution):

```
using Plots
plotlyjs()

function get_contour(x,y,d)
    xline = vcat(x,x[end:-1:1],x[1])
    yline = vcat(y-d,(y+d)[end:-1:1],(y+d)[1])
    return xline, yline
end

function myplot!(fig, x, y, d, color)
    plot!(fig, x, y, color= color)
    plot!(fig, get_contour(x,y,d)..., line = 0, alpha = 0.5, fill=(0,color), label = "")
end

fig = plot()
myplot!(fig,-pi:0.1:pi,sin(-pi:0.1:pi), 0.1, "blue")
```

**Comment by mkborregaard** [comment]
Closed in https://github.com/JuliaPlots/Plots.jl/pull/1023
