### ISSUE TITLE
GLVisualize pngs in Atom plotpane mirrored

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#582]
Using `glvisualize()` , master version installed with MetaGL, I run
```julia
using Plots
glvisualize()
scatter(1:100, randn(100))
```
and get
![skaermbillede 2016-11-22 kl 12 32 41](https://cloud.githubusercontent.com/assets/8429802/20523537/da2872b4-b0b5-11e6-8284-1d2b5e08ba69.png)

**Comment by SimonDanisch** [comment]
@tbreloff is MetaGL up to date?
@mkborregaard, do you have new versions of Images and ImageMagick installed by any chance? (see: https://github.com/JuliaGL/GLVisualize.jl/issues/123)
What OS are you on?

**Comment by mkborregaard** [comment]
I am on MacOS (Sierra). Images is version 0.5.14, ImageMagick version 0.1.8.

**Comment by tbreloff** [comment]
> @tbreloff is MetaGL up to date?

Only you would know.

```
julia 0.5
    GLPlot
    GLWindow
    GLAbstraction
    GLVisualize
    ModernGL
    SignedDistanceFields

    tagged:
        Contour
        GeometryTypes
        FixedSizeArrays
        FreeType
        Reactive
```

If there are dependencies that are not covered by the normal REQUIRE file, they should be in here.  The "tagged" packages are the ones that can be on a tagged release, even when you've checked out the rest of them.  It's best to keep things in tagged if you're not actively developing them (though if they're already in the REQUIRE file of something else on the list then they don't need to be in here at all).

FYI... you can have system-optional packages in your REQUIRE file, like:

```
@osx QuartzImageIO
```

**Comment by SimonDanisch** [comment]
hmm... Seems like `FileIO` uses `QuartzImageIO` nowadays to write an image to the Atom stream... and seems like `QuartzImageIO` does this differently compared to `ImageMagick` -.-
@tbreloff all is tagged now ;)

**Comment by tbreloff** [comment]
> @tbreloff all is tagged now ;)

Yes... for the next hour or so... until the next killer feature.  The idea is that the "tagged" list is for those packages that you aren't really developing but that for some reason aren't already a dependency (maybe they are normally optional dependencies, for example).  I suspect the tagged section of MetaGL can be removed...

**Comment by SimonDanisch** [comment]
@timholy @rsrock, is this by any chance known behavior?

**Comment by rsrock** [comment]
Hey, that's fun.  I see it here too.  I'm not using Atom, instead I have TerminalExtensions/iTerm2.

`testimages("mandrill")` and `testimages("fabio_color_256.png")` show up fine.

**Comment by mkborregaard** [comment]
The current behaviour is that GLVisualize doesn't use the Atom plot pane at all.

**Comment by SimonDanisch** [comment]
Is it? I think it does display the plot as an image

**Comment by mkborregaard** [comment]
Huh, now it does, yes. I tried it out earlier today, and it wouldn't use the plotpane. Now it does - looks a little  strange though.
<img width="1001" alt="skaermbillede 2017-09-05 kl 17 38 16" src="https://user-images.githubusercontent.com/8429802/30075582-763c1910-9276-11e7-8fa9-d5b572c674d0.png">

**Comment by daschw** [comment]
Closing as GLVisualize is no longer supported.
