### ISSUE TITLE
twinx does not appear when searching the documentation

### ISSUE THREAD

**Issue by mzaffalon** [JuliaPlots/Plots.jl#594]
Not sure if this is the correct place to report this.

The search box of https://juliaplots.github.io/ is not able to find the function `twinx` which is implemented.

**Comment by tbreloff** [comment]
This is one of many "bonus features" which I'm not sure I want to officially support.  But I suppose it would be nice to have a bonus-features page in the docs. :)

**Comment by mzaffalon** [comment]
Yet it is nice to be able to superimpose two traces with different scales, sharing one axis. Is there another way of doing this?

(Two minor nitpicks: twinx plots the axes frame twice, resulting in a thicker frame. And cycling of e.g. the title shows up by plotting the titles on top of each other.)

**Comment by tbreloff** [comment]
>  it is nice to be able to superimpose two traces with different scales, sharing one axis

That's why I wrote the function.

> Two minor nitpicks:

That's (partly) why it's not in the documentation :)

**Comment by mzaffalon** [comment]
> That's why I wrote the function.
> That's (partly) why it's not in the documentation :)

@tbreloff you are killing me!

**Comment by mzaffalon** [comment]
And also, setting the `xlim` in the first axis have no effect on the shared axis:
```
plot!(p1, xlim=(-2,2))
p1_shared = twinx(p1)
plot!(p1_shared, ...)
```
the `p1_shared` x-axis may not have limits (-2,2).

**Comment by randy3k** [comment]
It seems that `twinx` doesn't play nicely with `PlotlyJS`. Particularly, the second axis location is on the wrong side.

```julia
plotlyjs()
y1 = randn(10)
y2 = randn(10)
plot(y1)
plt = twinx()
plot!(plt, y2, color=:red)
```
<img width="671" alt="screen shot 2017-06-21 at 3 50 54 pm" src="https://user-images.githubusercontent.com/1690993/27403713-6d985a4e-5699-11e7-9956-2c67d350016a.png">

While the `PyPlot` backend yields
![unknown](https://user-images.githubusercontent.com/1690993/27403736-83dd8d06-5699-11e7-99ee-152c04f33fc5.png)

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/Plots.jl/pull/4488.
