### ISSUE TITLE
deprecation warning on transpose of array of strings

### ISSUE THREAD

**Issue by mzaffalon** [JuliaPlots/Plots.jl#601]
I guess your examples in [Advanced Layouts](https://juliaplots.github.io/layouts/#advanced-layouts) should have the command `["($i)" for i=1:11]'` replaced by `hcat(("($i)" for i=1:11)...)`?

**Comment by mkborregaard** [comment]
Yes, you're right, or `["($i)" for j = 1:1, i=1:11]`. Feel like making the PR [here](https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/layouts.md)?

**Comment by mzaffalon** [comment]
Apologies, I missed your comment.
