### ISSUE TITLE
Margins after colorbar

### ISSUE THREAD

**Issue by tcovert** [JuliaPlots/Plots.jl#603]
Any idea how I might make this figure wide enough so that the text on the colorbar is not cutoff for the negative values?

![sih](https://cloud.githubusercontent.com/assets/4276172/20951004/ddefacc6-bbe8-11e6-889d-0484921f348c.png)

When I try to adjust margins using, `right_margin`, all that does is move the colorbar further to the right of the contour, without adding extra padding after the colorbar itself.

**Comment by mkborregaard** [comment]
Should be fixed
