### ISSUE TITLE
rotate z axis label in surface plot

### ISSUE THREAD

**Issue by floswald** [JuliaPlots/Plots.jl#606]
i was looking for 

```
surface(rand(10,10),xlabel="x",ylabel="y",zlabel="a too long z label")
surface(rand(10,10),xlabel="x",ylabel="y",zlabel="a too long z label",zrotation=90) # nope
```

is that a feature you could implement or is there a way to achieve this already?

**Comment by mkborregaard** [comment]
The zrotation keyword exists, it just isn't implemented.

**Comment by nico202** [comment]
Hi, any luck on this?

Thanks, Nicolò

**Comment by gaomrx** [comment]
Here is a trick that I use to get a "rotated" zlabel. You may have better luck asking on the Gitter channel
```surface(rand(10,10),xlabel="x",ylabel="y",zlabel="a too long z label")```

**Comment by gaomrx** [comment]
A trick to get "rotated" zlabel if you know the range of your zaxis. You may get more responses asking on Gitter to finally implement rotation for the labels.
```surface(rand(10,10),xlabel="x",ylabel="y", zticks = (0:0.2:1, ["0.2"; "0.4"; "a too long z label";"0.8";"1"]), colorbar = false)```

**Comment by isentropic** [comment]
The argument you are looking for is `zguidefontrotation`
Although, only pyplot backend implements it I believe
