### ISSUE TITLE
coordinates does not appear in Plots.jl with PyPlot backend

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [JuliaPlots/Plots.jl#607]
`julia> using PyPlot; plot([1,2,3])`
[PyPlot](https://owncloud.usask.ca/index.php/s/jnyBVpgi9yrtGmf)
`julia> using Plots; plot([1,2,3])`
[Plots](https://owncloud.usask.ca/index.php/s/usJdJMQegYMBd4m)

I have Arch linux, Julia 0.5, and python is installed via Conda. I also have #593 if this matters.
matplotlib uses qt5agg backend (at least it is indicated in matplotlibrc)
```
$ julia -e 'using Plots; pyplot(); println(PyPlot.matplotlib[:matplotlib_fname]())'
/home/kosh/.config/matplotlib/matplotlibrc
$ julia -e 'using PyPlot; println(PyPlot.matplotlib[:matplotlib_fname]())'
/home/kosh/.config/matplotlib/matplotlibrc
```

but fonts in matplotlibrc is ignored.

I do not know how to diagnose this issue. Probably it is related to #593 ?

**Comment by mkborregaard** [comment]
Does adding the preamble here https://github.com/JuliaPlots/Plots.jl/issues/997 address your problem?
