### ISSUE TITLE
document 3D surface API

### ISSUE THREAD

**Issue by ggggggggg** [JuliaPlots/Plots.jl#614]
Searching docs for `surface` turn up nothing useful. I'm trying to figure out how to set the color of the surface, rather than get the default heatmap behavior.

**Comment by JackDevine** [comment]
I agree that the documentation is a little lacking, although to be fair `surface` is just a convenience function for `plot(arr, seriestype = :surface)`. The default color gradient is inferno, but you can change that through the color key word argument. Try these

```julia
surface(randn(10, 10), color = :rainbow)
surface(randn(10, 10), color = :plasma)
```

[Here](http://matplotlib.org/examples/color/colormaps_reference.html) is a list of color gradients available in matplotlib.

**Comment by t-bltg** [comment]
Fixed.
