### ISSUE TITLE
ffmpeg Windows path

### ISSUE THREAD

**Issue by achugb** [JuliaPlots/Plots.jl#615]
Line 87 in [animation.jl](https://github.com/tbreloff/Plots.jl/blob/master/src/animation.jl)
```run(`ffmpeg -v 0 -framerate $fps -loop $loop -i $(animdir)/%06d.png -y $fn`)```

The forward slash causes ffmpeg to fail on Windows.

PS: First ever issue submission. Please excuse formatting.

**Comment by YongHee-Kim** [comment]
which windows are you using? 
you can view your system info by typing `versioninfo()` on julia REPL

works on my machine. with `pyplot(), gr()` backend 
>System: NT (x86_64-w64-mingw32
```
using Plots
pyplot()
anim = @animate for i=1:75
    plot(rand(10))
end
fn = "$(dirname(@__FILE__))\\anim.gif"
loop = 0
fps = 20
run(`ffmpeg -v 0 -framerate $fps -loop $loop -i $(anim.dir)/%06d.png -y $fn`)

gif(anim, "$PATH\\anim.gif", fps = 15)
```

and now it seems [ImageMagick is supporting windows.](https://github.com/JuliaIO/ImageMagick.jl/pull/67)

**Comment by mkborregaard** [comment]
I'm guessing this can be closed?
