### ISSUE TITLE
Offset shows if ticks=nothing (pyplot)

### ISSUE THREAD

**Issue by mauro3** [JuliaPlots/Plots.jl#617]
```
plot((101:110)+10000, ticks=nothing, size=(10,100))
```
gives (using pyplot)
![f](https://cloud.githubusercontent.com/assets/4098145/21319537/ea7263ec-c60d-11e6-8b4e-3c169ebc4f4c.png)

Expected: no `1.0101e4` showing.

**Comment by t-bltg** [comment]
That's a `matplotlib` feature, nothing we can do here.

e.g. https://stackoverflow.com/questions/53878397/change-matplotlib-offset-notation-from-scientific-to-plain

**Comment by isentropic** [comment]
Actually this has been patched at some point, so currently it is fixed, and we did something about it :smile:

**Comment by t-bltg** [comment]
I've closed about `60+` (old) issues in a row last we, this one was one of them, we should do that more often to be able to focus on real issues :wink.
