### ISSUE TITLE
Grid xticks lines color

### ISSUE THREAD

**Issue by rakeshvar** [JuliaPlots/Plots.jl#620]
I am trying to get the xtick vertical lines in red (say).

```julia
using Plots
default(bg=:transparent)
n, p = 10, 4
y = (cumsum(randn(n, p)))
x = sort(10 * abs(randn(n)));
plot(x, y, xaxis=("b", x, :red))
```

I get a warning: using Plots

> WARNING: Skipped xaxis arg red

![newplot](https://cloud.githubusercontent.com/assets/2840906/21387217/a22fd3f4-c79c-11e6-9bac-2b6dc50a70fb.png)

As you can see, the vertical lines are in white/grey.
Also I do not want the numbers at the bottom. What I want is vertical lines at each `x` point. (Without using an extra call to `vline!`). Thanks.

**Comment by mkborregaard** [comment]
I think this was fixed in https://github.com/JuliaPlots/Plots.jl/pull/1006
