### ISSUE TITLE
RFC: InspectDR Backend?

### ISSUE THREAD

**Issue by ma-laforge** [JuliaPlots/Plots.jl#624]
I was wondering if there was any interest in having InspectDR as a backend to Plots.jl:
https://github.com/ma-laforge/InspectDR.jl

I noticed many backends are now deprecated because they did not add sufficient functionality to warrant their maintenance - even Gadfly/Immerse is deprecated now.

About InspectDR:
 - 👎  InspectDR does not support more advanced features like heat maps & 3D.  It mostly targets line/scatter plots.
 - 👍 Last I checked: InspectDR has very quick plot times.  Overall, I find it most closely resembles GR in that respect.
 - 👍 It maintains reasonable speed with large datasets: It can handle moderate datasets (>200k points) with visibly less slowdown than other more poplular backends.
 - 👍 Its GUI has better interactivity than most packages: built-in mouse/keybindings make it somewhat pleasant to pan/zoom.
 - 👍 Pan/zoom exhibits good, interactive response times: You don't usually need to wait 1/2 second+ for the GUI to refresh.

@tbreloff:
Have you tried out InspectDR?  Do you think it would be worth adding it as a backend for Plots?

I don't really feel like putting energy into this if you don't see InspectDR differentiating itself sufficiently.

**Comment by tbreloff** [comment]
I don't see myself spending time on it, because it seems so similar to GR,
but less features. So I leave it to you whether you'd like the backend.
Certainly I would merge a PR that supports it.

**Comment by skanskan** [comment]
I've been looking for a backend able to plot large datasets and found GR and InspectDR.
Between the two InspectDR seems to be much faster, though the latest version is not completly compatible with Plots.jl

**Comment by ma-laforge** [comment]
Thanks for that test.

I am curious: Does "much faster" mean something like just 20% faster... or more like 200%?

Also: I will figure out what to do about that incompatibility with Plots.jl...
