### ISSUE TITLE
0.6 precompile failure

### ISSUE THREAD

**Issue by nbecker** [JuliaPlots/Plots.jl#627]
julia-0.6.0-0.20161231.fc25.x86_64

julia> using Plots
INFO: Precompiling module FixedSizeArrays.
WARNING: Module Compat with uuid 217261403971897 is missing from the cache.
This may mean module Compat does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
Stacktrace:
 [1] anonymous at ./<missing>:2
while loading /home/nbecker/.julia/v0.6/FixedSizeArrays/src/FixedSizeArrays.jl, in expression starting on line 4
ERROR: LoadError: Failed to precompile FixedSizeArrays to /home/nbecker/.julia/lib/v0.6/FixedSizeArrays.ji.
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 in macro expansion at ./REPL.jl:97 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:66
while loading /home/nbecker/.julia/v0.6/Plots/src/Plots.jl, in expression starting on line 5

**Comment by KristofferC** [comment]
Delete your `.julia/lib/v0.6/Plots.ji` file.

**Comment by mkborregaard** [comment]
Fixed
