### ISSUE TITLE
heatmap and inset histogram

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#628]
Am I doing something wrong?

```julia
using Plots
heatmap(randn(100,100))
histogram!(randn(100), inset=bbox(0.05,0.05,0.5,0.25,:bottom,:right))
```

![download](https://cloud.githubusercontent.com/assets/3345261/21595065/8be07354-d108-11e6-8b08-fdedd121387d.png)

**Comment by tbreloff** [comment]
Hard to know without the result of those commands.

**Comment by juliohm** [comment]
@tbreloff you mean the preview? Perhaps you are seeing the issue from your email without the preview that I attached?

**Comment by tbreloff** [comment]
You're right the image didn't download at first. Is this GR? Probably a
bug.

**Comment by juliohm** [comment]
This is PyPlot, yes, I believe it is a bug.
