### ISSUE TITLE
Plot is not shown in Jupyter notebook sometimes with PlotlyJS backend

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#629]
`Chromium Version 55.0.2883.87 (64-bit)`
`Julia v0.5`
`Plots 0.10.2`

![screenshot from 2017-01-02 21-42-52](https://cloud.githubusercontent.com/assets/3345261/21598090/af4a534c-d134-11e6-8508-b8aed41be9a1.png)

What can be the cause of the issue?

**Comment by juliohm** [comment]
This is probably not related to `Plots.jl` but to the way Jupyter notebooks display output.

**Comment by piever** [comment]
Have you tried:
`Pkg.checkout("Plots")` ?

I had a similar issue and #604 fixed it.

**Comment by juliohm** [comment]
I have tried to checkout both `Plots` and `PlotlyJS`, the issue is still happening.

**Comment by juliohm** [comment]
I will close the issue since it happens sporadically, if I figure out the root, I will reopen.

**Comment by RaulDurand** [comment]
I have the same problem. Did you figure out what was the root?

**Comment by mkborregaard** [comment]
There's a duplicate issue here: https://github.com/JuliaPlots/Plots.jl/issues/725
It happens when you delete the cell that had the plotlyjs() call

**Comment by mkborregaard** [comment]
sorry, clicking all over the place
