### ISSUE TITLE
Problems getting up and running

### ISSUE THREAD

**Issue by orswan** [JuliaPlots/Plots.jl#644]
I just took to Plots.jl, and as I was going through the documentation and trying to reproduce the examples, I ran into several issues:

1) Plotly and PlotlyJS clip off the bottom of the figure: 
![image](https://cloud.githubusercontent.com/assets/17443294/21947926/b133841a-d99c-11e6-9c4a-b45ef56ecbf2.png)

2) If I close the GR gui (by hitting the 'x' in the upper right), it apparently cannot open again.  I tried calling `gui()`, `display(plt)`, and `plt(...,show=true)` (as per the "Output" page of the manual), but to no avail.

3) The example `plot(rand(10,4), color = [:red, :blue])`, given in the "Input Data" page of the manual, throws an error for every backend I've tried.

4) If I call `workspace()` and then do `using Plots` after already loading Plots in the previous workspace, I get a bunch of warnings and then an error.

Here's my system info:

    julia> versioninfo()
    Julia Version 0.5.0
    Commit 3c9d753 (2016-09-19 18:14 UTC)
    Platform Info:
      System: NT (x86_64-w64-mingw32)
      CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas64_
      LIBM: libopenlibm
      LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

    julia> Pkg.status("Plots")
     - Plots                         0.10.2

**Comment by piever** [comment]
1) You can set a margin below the plot, like this:

`plot(rand(10,4), bottom_margin = Measures.Length(:mm,5))`

<img width="596" alt="screenshot 2017-01-14 13 49 28" src="https://cloud.githubusercontent.com/assets/6333339/21955307/7463a3e8-da60-11e6-933a-d807a1c8ca89.png">

If you find it annoying to always specify this for each plot you can set it as a default when calling the backend. If you start plotlyjs with:

`plotlyjs(bottom_margin = Measures.Length(:mm,5))`

that margin will be the default every time you make a plot. If you specify a new one on the plot command, the new one will be used.

3) The attributes have to be specified as a 1xn Array, which I think makes sense. The lines you are plotting are M[:,1], M[:,2], M[:,3], M[:,4] where M = rand(10,4), so the attributes will also be split by columns: c[1,1], c[1,2], c[1,3], c[1,4], where c = [:red :blue :green :magenta] for example. If it's shorter than that, the color will cycle among the possible options. Simply typing:

`plot(rand(10,4), color = [:red :blue])`

gets you what you want, whereas `plot(rand(10,4), color = [:red, :blue])` probably tries to set the color of the single trace as` [:red, :blue]` which is not a color, so I'm not sure what behavior one should expect. In this case we get an error.

As for 2., it's been mentioned that an improved GR GUI is being developed for julia, but I'm not sure about the timeframe. In the meantime maybe you can use other backends (or different programming environments: both in Juno and in Jupyter Notebook GR works just fine and is actually very fast and reliable).

**Comment by tbreloff** [comment]
Quick note that you can do "5mm" instead of constructing a Length.

**Comment by ChrisRackauckas** [comment]
@jheinen are you aware of this GUI issue? When I close the GR gui it doesn't open again too. Windows 10, Julia v0.5.2

**Comment by mkborregaard** [comment]
I think he is, it's all going to change with the new gksterm

**Comment by mkborregaard** [comment]
closing the gr gui segfaults on my machine

**Comment by jheinen** [comment]
@mkborregaard : the segfault happens on Linux (X11) ?

BTW: the new "terminals" (Qt5, JS) will be an option, not a replacement. But I suppose, most users will like them ...

**Comment by mkborregaard** [comment]
On Mac. I guess Plots will have to choose one standard terminal for GR?

**Comment by mkborregaard** [comment]
WRT to the original issue:

1. Solved by https://github.com/JuliaPlots/Plots.jl/pull/811
2. A well-known issue originating outside Plots
3. That example is fixed in the docs
4. I'd expect that to cause problems - the `workspace` command is wonky and probably interacts with Plots' `eval` in a funny way. I've always seen such a workflow with `workspace` generally discouraged.

I think in all this issue can safely be closed.
