### ISSUE TITLE
Different heatmap behaviour in PlotlyJS compared to GR

### ISSUE THREAD

**Issue by dpsanders** [JuliaPlots/Plots.jl#646]
```
heatmap(rand(5, 5), aspect_ratio=:true)
```
PlotlyJS:
<img width="427" alt="screen shot 2017-01-16 at 3 39 21 pm" src="https://cloud.githubusercontent.com/assets/191822/21974470/119fa61e-dc02-11e6-8673-e38e4ff87b96.png">

GR:
<img width="388" alt="screen shot 2017-01-16 at 3 39 49 pm" src="https://cloud.githubusercontent.com/assets/191822/21974481/1da38e08-dc02-11e6-80fc-832e3c9dd1c3.png">

- PlotlyJS plots from 0.5 to 5.5
- GR plots from 1 to 5 only

Neither is quite square, but GR is worse.

**Comment by mkborregaard** [comment]
Solved
