### ISSUE TITLE
latex label: integers appear as symbols.. 

### ISSUE THREAD

**Issue by LaurentPlagne** [JuliaPlots/Plots.jl#652]
Hi, 
the `1` and `2` values in the latex label appear as \Delta and N in the label.
Do I miss something ?
`using Plots`
`using LaTeXStrings`
`pyplot()`
`a=[1,2,3,4]`
`b=[10,9,8,7]`
`plot(title = "New Title", xlabel = "New xlabel", ylabel = "New ylabel")`
`plot!(a,b,label=L"\frac{1}{2}")`
`png("output")`

![output](https://cloud.githubusercontent.com/assets/24976886/22175422/c8938020-dff4-11e6-9416-5630214b6ccb.png)

**Comment by LaurentPlagne** [comment]
Hi again,
I run the same program on another machine (on windows) and the output is OK ;)
I suspect that I have an installation problem on my Ubuntu distribution (maybe with fonts) but there is no error/warning message and my Julia/Plots knowledge is to low to debug it. 
I will try to reinstall Julia...
The Plots module load is rather long on my machine. Is it supposed to be optimized in future releases (pre-compiled modules..) ?

**Comment by BeastyBlacksmith** [comment]
I can't reproduce on Plots 1.3.5, please reopen if still present.
