### ISSUE TITLE
Travis build failing due to pyplot fix?

### ISSUE THREAD

**Issue by ma-laforge** [JuliaPlots/Plots.jl#657]
I am no longer able to use PyPlot - ever since master has merged with https://github.com/JuliaPlots/Plots.jl/pull/650 .
(Using Ubuntu)

Message:
```
WARNING: Couldn't initialize pyplot.  (might need to install it?)
...
```

It also appears Travis is failing CI tests with the same problem.

I don't understand the details, but it appears the workaround provided by @huckl3b3rry87 is causing the issue.  In particular, the following condition is considered a failure:
```
if (!haskey(kw,"qt") || (qt_version=get(kw,"qt",0)[1]!=v"4.8.5"))
```

I find that if I comment out the contents of this entire if statement - everything works quite fine (even after I updated my version of Matplotlib).

Whatever this condition is checking, it seems too restrictive.

**Comment by ma-laforge** [comment]
Ah... I think I might understand the problem:

My system works by commenting out the if stmt because I first ensure I use the `:tk` backend (instead of `:qt`).

The bug with the PR submitted by @huckl3b3rry87 is relatively simple to fix:
**Replace line:**
```
add_backend_string(backend())
```
with:
```
print(add_backend_string(PyPlotBackend()))
```

Apparently `backend()` throws an error or something when called @ `__init__()` time.  Better off explicitly specifying the backend.

(also might be a good idea to print the message).

If the Travis tests don't use a graphics backend (i.e. the problematic version of qt)... there should be no issue - and the tests should succeed.

**Comment by mkborregaard** [comment]
close this?

**Comment by ma-laforge** [comment]
Yes.  I just was not sure if the team preferred to close issues themselves.
