### ISSUE TITLE
Where to add docstrings in Plots.jl source?

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#660]
Whenever I try to lookup the source code understand what a function is doing, I never find it under `src/`. Suppose I want to add a docstring to `vline`, where should it go?

I can try help adding documentation to Plots.jl.

**Comment by tbreloff** [comment]
I'm not sure it's possible. Those methods are generated when I define the
series recipes.

And to be clear ALL of those just get funneled to the 'plot' or 'plot!'
methods.

**Comment by juliohm** [comment]
Got it, this explains the lack of documentation too. I don't know what is the syntax for `vline()` for instance, the examples in the docs only call it once with `vline([3,5])`.
