### ISSUE TITLE
Custom confidence interval for step plot

### ISSUE THREAD

**Issue by alexhallam** [JuliaPlots/Plots.jl#661]
Hi,

I am working on a time to even analysis plot and I can't seem to get the confidence intervals right. I calculated the intervals already so it should just be a matter of adding them to a plot, but this is what I am getting

![2017-01-27-022704_916x929_scrot](https://cloud.githubusercontent.com/assets/9298693/22358573/23c0af30-e438-11e6-8c6f-edbc8434ee48.png)

My data frame is `whas`. `time` is the x axis. `estimate` is the y axis. I think the problem is in fillrange, but I am not sure. 

Also, just so you can see that it is not the calculations.

![2017-01-27-023012_916x929_scrot](https://cloud.githubusercontent.com/assets/9298693/22358664/bdf09db8-e438-11e6-99d4-bff0b9c636dd.png)

Thanks for the help.

**Comment by tbreloff** [comment]
You probably want to use 'error', not 'fillrange'. Also make sure you pass
in a tuple if the intervals aren't symmetric.

**Comment by alexhallam** [comment]
Thanks for the quick response.

**Comment by alexhallam** [comment]
The error bars are very dense in some areas and are dominating the plot. Is there a way to add transparency to just the error bars without affecting the estimate line?

Thanks

**Comment by tbreloff** [comment]
Oh my mistake. You actually want 'ribbon'

**Comment by alexhallam** [comment]
Ribbon looks perfect, but I am getting the same problem I was getting with `fillrange`. If I could get `ribbon` to fit around my line like 'err` that would be perfect. 

![2017-01-27-041035_891x929_scrot](https://cloud.githubusercontent.com/assets/9298693/22360386/16a98556-e447-11e6-8f42-aa47a4f2009d.png)

**Comment by tbreloff** [comment]
Looks like your arrays aren't the same size? Looks to be cycling values.

**Comment by alexhallam** [comment]
I will take a look at my values again. I am sure I am doing something wrong. Should `err` and `ribbon` give the same output?

**Comment by mkborregaard** [comment]
@alexhallam can this be closed? This functionality should be working.

**Comment by alexhallam** [comment]
Yes, all well.
