### ISSUE TITLE
PGFPlots updates - Feb 2017

### ISSUE THREAD

**Issue by ma-laforge** [JuliaPlots/Plots.jl#671]
@sebastianpech: RE https://github.com/JuliaPlots/Plots.jl/pull/667
(Nice additions: PGFPlots output looks good).

Just a few comments you may/not want to address (Nothing critical):

1. You might want to execute `srand(1234)` before each of your Notebook test.  That would yield the same "random" output as found in: https://juliaplots.github.io/examples/pgfplots/ (Easier to assess correct operation).

2. Is there a way to plot the entire polar grid instead of stopping where the phase data stops?  I find the appearance of a partial (sector) polar grid a bit odd.

3. Now that PGFPlots supports `:shapes`: I think you can add test 30 (Box Plot and Violin series recipes) to your notebook as well.  The output will probably look good.

4. "Bar" test:  You run `rand(99)` instead of `randn(99)`.  All values in the bar plot are positive.

**Comment by sebastianpech** [comment]
Thanks for your suggestions, I changed the notebook accordingly.

ad 2. You can set the values for `xmin` and `xmax`. Generally the polar axis seems to have a few bugs even in the latex pgfplots package [[link](http://tex.stackexchange.com/questions/294668/partial-polar-plot-with-pgfplots)]. I'll look into that. Another thing that came to my mind is unit consistency. PGFPlots uses deg all the other backends use rad so it would be nice to implement a conversion.

ad 3. It works, not perfectly but it does. Currently the markers setting affects the boxes but should rather affect the outliers. I'll look into that too.

Updated Notebook: [PGFExamples.ipynb](https://github.com/sebastianpech/share/blob/master/julia/PGFExamples.ipynb)

**Comment by ma-laforge** [comment]
A bit easier to compare now...

Might I also point out that the justification of the text annotation in `Out[17]` ("Annotations" example) seems opposite to the output generated by PyPlot?

Are you sure there is not an inversion when controlling left <--> right justification?

**Comment by ma-laforge** [comment]
> @sebastianpech: You can set the values for xmin and xmax.

Very cool (you get the best of both worlds).  Too bad doing so leaves odd looking pie segments on the polar grid.

**Comment by sebastianpech** [comment]
> @ma-laforge Might I also point out that the justification of the text annotation in Out[17] ("Annotations" example) seems opposite to the output generated by PyPlot?

You are right, there should be an inversion. I fixed it. Will create a pull request.

**Comment by mkborregaard** [comment]
Can this be closed, friends?

**Comment by sebastianpech** [comment]
Yes. Can be closed
