### ISSUE TITLE
close a window

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/Plots.jl#672]
PyPlot is really a big step forward in API over matplotlib. Plots promises to be another such step.  But, only with long use of matplotlib in Python and PyPlot do I know to issue close() or close("all") or figure().  You don't seem to document any of the corresponding functionality for plots.  display(), show(), and some of the PyPlot control commands also need to be there.  There seem to be a lot of these prosaic housekeeping things either missing or undocumented.

close() and close("all") don't work with the plotlyjs backend.  Manually closing the plot window lead to lots of julia runtime errors that could only be stopped with ^C.  I'll stick with PyPlot.  

Unrelated: Can I still PyCAll to Seaborn if I am using Plots?

This is awesome work and it has to be very hard to support so many backends that are only at a distance very similar if you squint (they all do lines, bars, etc.--but the devil is in the details).

**Comment by lwabeke** [comment]
Not sure if this is related, but I also got numerous errors when closing plotlyjs windows manually. 
I believe I found a workaround, although I don't really understand why the transpose was in the code in the first place, see:
https://github.com/JunoLab/Blink.jl/pull/81
However, nothing happening on that PR as yet.

**Comment by mkborregaard** [comment]
What's the question exactly - is it a request to document `display` etc?
