### ISSUE TITLE
Generating a gif with collection of images 

### ISSUE THREAD

**Issue by ereday** [JuliaPlots/Plots.jl#677]
Hi, I wonder if I can generate a gif by using a couple of images rather than plots by using Plots.jl.  If possible, could you point where can I find an example on the documentation. Thanks.

**Comment by timholy** [comment]
```julia
julia> using FileIO, TestImages

julia> img = testimage("mandrill");

julia> img2 = flipdim(img, 1);

julia> save("flipping.gif", cat(3, img, img2))
```

**Comment by ereday** [comment]
Is there a way to specify the time for per image ? I mean, in default version, I cannot fallow the images, they changes so fast and I'd like to make transaction slower.

**Comment by timholy** [comment]
There is now :smile:. https://github.com/JuliaIO/ImageMagick.jl/pull/73
