### ISSUE TITLE
How to draw shapes on image by using pyplot backend

### ISSUE THREAD

**Issue by ereday** [JuliaPlots/Plots.jl#680]
Hi ! 

I tried to find a way to draw regular shapes like rectangle on top of image by using Plots.jl. As initial steps, I've done followings to open the image:

```
using Images
using Plots
pyplot()
img = load("lenna.png")
plot(img',leg=false) 
# I have to take transpose here. If I did not take transpose, the
# image visualized as rotated 90  degree in counterclockwise. 
#I also would appreciate if there is a solution for that too
```

At this point, I stuck. It is not clear in documentation how could I draw a rectangle on top of that image. Let's say  dimension of img is 200(width)x300(height) and I want to draw an rectangle at the position of (4,10) and its width need to be 10 and height is 30 pixels. Is there a way to do that in Plots.jl ?

**Comment by tbreloff** [comment]
```julia
using Plots, TestImages
pyplot()
img = testimage("cameraman")
plot(img)
x1,x2,y1,y2 = 10,200,10,100
plot!([x1,x2,x2,x1,x1],[y1,y1,y2,y2,y1],st=:shape,alpha=0.5,c=:blue)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/22837847/5ee03500-ef90-11e6-8d45-407761dbf936.png)
