### ISSUE TITLE
How to plot series of (x, y) pairs of varying lengths

### ISSUE THREAD

**Issue by rakeshvar** [JuliaPlots/Plots.jl#686]
I have say three `(x, y)` pairs. With the paired `x` and `y` having the same length. I want to plot them on one graph. Is there a better way to do it than this? I want to use **only one call to plot**.

```julia
xsys = collect((cumsum(rand(1:9, len)), rand(1:99, len)/10) for len in (3, 4, 5))
xs, ys = collect(zip(xsys...))
#  xs = ( [1,8,9], [5,13,18,26], [7,13,21,22,29] )                 
#  ys = ( [0.6,7.1,6.0], [2.5,9.2,8.3,6.3], [3.8,6.2,8.9,4.0,3.1] )
p = plot(xs[1], ys[1])
for i in 2:length(xs)
    plot!(xs[i], ys[i])
end
display(p)
```

![newplot](https://cloud.githubusercontent.com/assets/2840906/23086553/7b901566-f522-11e6-85db-c370a420f3e1.png)

**Comment by mkborregaard** [comment]
You can't always use just one call to plot

**Comment by pkofod** [comment]
This is probably the best you can do
```
xsys = collect((cumsum(rand(1:9, len)), rand(1:99, len)/10) for len in (3, 4, 5))
xs, ys = collect(zip(xsys...))
#  xs = ( [1,8,9], [5,13,18,26], [7,13,21,22,29] )
#  ys = ( [0.6,7.1,6.0], [2.5,9.2,8.3,6.3], [3.8,6.2,8.9,4.0,3.1] )
p = plot()
map(x->plot!(x[1],x[2]), zip(xs, ys))
display(p)
```

**Comment by Godisemo** [comment]
You can do this using the group keyword argument if you layout your data differently. Concatenate all xs and ys to one single vector, and add a vector for indicating which group the sample belongs to. Following your initial example:

```julia
xsyszs = collect((cumsum(rand(1:9, len)), rand(1:99, len)/10, fill(id, len)) for (id,len) in enumerate((3, 4, 5)))
xs, ys, zs = map(t -> vcat(t...), collect(zip(xsyszs...)))
# xs = [3,12,20,7,14,20,23,5,7,9,15,17]                 
# ys = [5.0,5.7,3.9,2.5,6.9,3.1,3.1,9.9,8.5,6.7,1.6,4.0]
# zs = [1,1,1,2,2,2,2,3,3,3,3,3]   
plot(xs, ys, group=zs)
```
I suggest this issue can be closed, since the functionality already exists.
