### ISSUE TITLE
Labels?

### ISSUE THREAD

**Issue by kmundnic** [JuliaPlots/Plots.jl#688]
Hi,

I've been trying without success to change the labels in the key of a plot with two signals. Using the Plotly backend, I'm doing the following (followed this [link](https://lectures.quantecon.org/jl/julia_plots.html#plotsjl-jl) since I have been unsuccessful to find it in the documentation):

```plot(1:10,[rand(10) rand(10)], label = ["rand1", "rand2"])```

It shows the following labels (trace 0, trace 1):

![unknown](https://cloud.githubusercontent.com/assets/4093769/23096993/cbcc8904-f5dd-11e6-8e6d-333eb4f8d266.png)

I haven't found any clear example in the documentation on how to include key labels, and the error that I have shown doesn't seem reasonable.

Thanks for any advice

**Comment by YongHee-Kim** [comment]
Instead of  `label = ["rand1", "rand2"]`

you should do `label = ["rand1" "rand2"]`

**Comment by kmundnic** [comment]
Thanks. This solves the problem. Nevertheless, I believe the documentation is lacking a labels section, and that at least a warning should be thrown if the labels are not being given in the right way.

**Comment by tbreloff** [comment]
See the "attributes" page

**Comment by mmagnuski** [comment]
I've also found this a bit surprising and the docs are not explicit enough about this IMO (attributes page does not say anything about the correct orientation).

**Comment by joshday** [comment]
From "Basics" (page 3 of docs):

> If the argument is a "matrix-type", then each column will map to a series, cycling through columns if there are fewer columns than series. In this sense, a vector is treated just like an "nx1 matrix".

and

> Tip: A common error is to pass a Vector when you intend for each item to apply to only one series. Instead of an n-length Vector, pass a 1xn Matrix.

**Comment by tbreloff** [comment]
Also from https://juliaplots.github.io/input_data/

> Columns are series

> In most cases, passing a (n x m) matrix of values (numbers, etc) will create m series, each with n data points. This follows a consistent rule... vectors apply to a series, matrices apply to many series. This rule carries into keyword arguments. scatter(rand(10,4), markershape = [:circle, :rect]) will create 4 series, each assigned the markershape vector [:circle,:rect]. However, scatter(rand(10,4), markershape = [:circle :rect]) will create 4 series, with series 1 and 3 having markers shaped as :circle and series 2 and 4 having markers shaped as :rect (i.e. as squares). The difference is that in the first example, it is a length-2 column vector, and in the second example it is a (1 x 2) row vector (a Matrix).

**Comment by tbreloff** [comment]
This behavior isn't specific to labels... it would be pretty silly to repeat this information for every single attribute.

**Comment by kmundnic** [comment]
I noticed that most (if not all) of the examples do not consider more than one label in the key. This caught my attention, as most of them are left with labels "y1" and "y2" if there is more than one signal being plotted. 

I understand the point that there shouldn't be repeated info (and now I see where the information was), and I agree with it. Nevertheless, I still think that including how to use more than one label in one example would be useful for people who are starting, even more considering people who are trying to make the transition from MATLAB.

**Comment by tbreloff** [comment]
I think the current examples section should be scrapped entirely, and replaced with a more cohesive set of examples.  But no one has done that yet...

**Comment by mkborregaard** [comment]
close?

**Comment by kmundnic** [comment]
The problem is solved for me.
