### ISSUE TITLE
Show available color gradients

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlots/Plots.jl#691]
It would be convenient to have a method which "plots" a color library from PlotUtils.  See:

- https://github.com/JuliaPlots/PlotUtils.jl/issues/2#issuecomment-253901643
- https://github.com/JuliaPlots/PlotUtils.jl/pull/5

**Comment by mkborregaard** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/692

**Comment by mkborregaard** [comment]
I will merge #692 once the color libraries PR is merged.
