### ISSUE TITLE
Scatter plot legend marker duplicate with gr() backend

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaPlots/Plots.jl#693]
```
using Plots; gr()
scatter(eye(2), 1:2, label = ["a" "b"])
```
![image](https://cloud.githubusercontent.com/assets/7087745/23192364/61a0250c-f8e6-11e6-8ecf-d9c6b91a4359.png)

```
using GR
scatter(eye(2), 1:2, labels=["a", "b"])
```
![image](https://cloud.githubusercontent.com/assets/7087745/23192325/29c4700c-f8e6-11e6-853d-3f7410bf4299.png)

`GR` legend works fine so, I figured it's a bug from Plots.jl. And I'm planning to resolve this issue myself(If possible...)
But I found that there is [another gr backend is WIP](https://github.com/JuliaPlots/PlotsGR.jl) 

@tbreloff are you planning to change `GR` backend to `PlotsGR.jl`? and if that's the case, is it not necessary to resolve this?

**Comment by tbreloff** [comment]
I'm confused. What's wrong with the output?

As for the backend questions, please see the new "contributing" page of the
docs

**Comment by YongHee-Kim** [comment]
It's duplicated 

`plotlyjs()` backend 
![image](https://cloud.githubusercontent.com/assets/7087745/23193064/54ab1e20-f8ea-11e6-89c2-df313c96126d.png)

`gr()` backend
![image](https://cloud.githubusercontent.com/assets/7087745/23193071/5d4d9f80-f8ea-11e6-984c-ff773634eb80.png)

**Comment by tbreloff** [comment]
That behavior was certainly intentional, so I don't think there's anything to fix.  Vote: does anyone think this should be changed to a single marker in the center?

**Comment by mkborregaard** [comment]
I do. I have been confused by this as well. What is the purpose of duplicating the marker on gr?

**Comment by joshday** [comment]
My vote is single marker, but my opinion hasn't been strong enough to bring it up before.

**Comment by tbreloff** [comment]
Ok. I vote single marker too actually :)  who wants to change it?

**Comment by joshday** [comment]
Assuming it's in gr.jl, can you give me a pointer/search term to find the relevant code?

**Comment by mkborregaard** [comment]
try https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/gr.jl#L1020

**Comment by mkborregaard** [comment]
I also vote for reducing the marker size
