### ISSUE TITLE
Use "label" as a prefix when printing from dataframes using "group" 

### ISSUE THREAD

**Issue by sylvaticus** [JuliaPlots/Plots.jl#700]
Consider the following example:

```
using DataFrames, Plots, StatPlots
df = DataFrame(
  product = ["orange","orange","orange","orange","banana","banana","banana","banana"],
  year = [2010,2011,2012,2013,2010,2011,2012,2013],
  prod = [120,150,170,160,100,130,165,158],
  cons = [70,90,100,95,   80,95,110,120]
)
plotlyjs() 
mycolors = [:blue, :red ]
fruits_plot = plot(df, :year, :prod, group=:product, linestyle = :solid, linewidth=3, linecolor=:match, color_palette = mycolors)
fruits_plot = plot!(df, :year, :cons, group=:product, linestyle = :dot, linewidth=3, linecolor=:match, color_palette = mycolors)
```
This print (forget here the [colour issue](https://github.com/JuliaPlots/Plots.jl/issues/701)):

![fruits_plot](https://cloud.githubusercontent.com/assets/2077159/23253088/84f6fd96-f9b3-11e6-8a7c-52f937455d4c.png)

It would be nice to have the possibility to label the first group of series differently than the second one, while still retaining the individual serie label.
If I add to the first group of series `label="Production of "` or to the second one `label="Consumption of "`  this will be substituted to the one coming from the dataframe using group.
This proposal is to consider label as a prefix and concatenate it with the label coming from the dataframe when `group` is used.
Alternatively a `label_suffix` and/or a `label_postfix` attribute could be introduced.

**Comment by mkborregaard** [comment]
I can see how it's helpful in the current example, but not that it is a general functionality we need. It would be nice with a general design for how legends should work that considers all the possibilities, but this does not seem generally useful.

In the current example, you can just do `label = ("Production of " * sort(unique(df[:product]))')` to get the behaviour you want.

**Comment by sylvaticus** [comment]
Hello, in Julia 0.6 this workaround doesn't work any more.. nor using `reshape(sort(unique(df[:product])), (1, :))` works, as the object produced 
(`1×2 Base.ReshapedArray{String,2,DataArrays.DataArray{String,1},Tuple{}}`) is not the one expected by plots..

**Comment by daschw** [comment]
`label = "Porduction of " .* reshape(sort(unique(df[:product])), (1, :))` works for me.

**Comment by sylvaticus** [comment]
yep that works, thank you..
