### ISSUE TITLE
Altered colours from subsequent use of a custom palette

### ISSUE THREAD

**Issue by sylvaticus** [JuliaPlots/Plots.jl#701]
Hello, when trying to plot multiple groups of series from a dataframe and reuse the same colour palette for the individual series, the subsequent series use an "altered" version of the colours:

```
using DataFrames, Plots, StatPlots
x = [110,120,130,140, 105,115,125,135]
df = DataFrame(
  fruit   = ["orange","orange","orange","orange","banana","banana","banana","banana"],
  year    = [2010,2011,2012,2013,2010,2011,2012,2013],
  prod    = x,
  cons    = x - 20,
  exports = x - 40,
  imports  = x - 60,
)
plotlyjs() # same with pyplot() backend..
mycolors = [:red, :green  ] # same with mycolors = [:yellow, :orange ]
fruits_plot = plot(df, :year, :prod, group=:fruit, linestyle = :solid, linewidth=3, linecolor=:match, color_palette = mycolors)
fruits_plot = plot!(df, :year, :cons, group=:fruit, linestyle = :dot, linewidth=3, linecolor=:match, color_palette = mycolors)
fruits_plot = plot!(df, :year, :exports, group=:fruit, linestyle = :dash, linewidth=3, linecolor=:match, color_palette = mycolors)
fruits_plot = plot!(df, :year, :imports, group=:fruit, linestyle = :dashdot, linewidth=3, linecolor=:match, color_palette = mycolors)
```
Results in:
![fruits_plot](https://cloud.githubusercontent.com/assets/2077159/23255513/3254220e-f9bc-11e6-9c95-c61933b7c8b4.png)

As you can see, the problem is that the subsequent groups of series  use the palette with somehow "distorted" (or sometimes inverted) colours.

This is independent from the specific backend used.

**Comment by sylvaticus** [comment]
In the [documentation ](https://juliaplots.github.io/colors/) it is stated that:

> color_palette determines the colors assigned when seriescolor == :auto:
> 
>     If passed a vector of colors, it will force cycling of those colors

This is what I want, as I am using it for a _group_ of series, not for an individual one (an I am using the keywork `group`)
In fact, it works well on the first usage. The problem is when I add to the same plot other group of series.

Bdw, I did try to set `linecolor` directly, but it accepts only a scalar, not arrays..

**Comment by tbreloff** [comment]
Use a 1x2 matrix when setting colors for 2 series

**Comment by sylvaticus** [comment]
yep, using `fruits_plot = plot(df, :year, :prod, group=:fruit, linestyle = :solid, linewidth=3, linecolor=[[:red] [:yellow]])` works, thanks..
