### ISSUE TITLE
pyplot heatmap not working for randn(1,3) or randn(3,1)

### ISSUE THREAD

**Issue by baggepinnen** [JuliaPlots/Plots.jl#712]
```julia
using Plots
pyplot()
julia> heatmap(randn(1,3))
julia> heatmap(randn(3,1))
```
both produce a blank plot on pyplot, works well on plotly

**Comment by dsweber2** [comment]
for what it's worth, I tried this in PyPlot directly, and got the same result, so I think it may be a problem with the backend

**Comment by pkofod** [comment]
Close as pyplot bug? If issue is still in PyPlot we could be kind and open an issue for them.

**Comment by mkborregaard** [comment]
Thanks for your keen observations here @pkofod
