### ISSUE TITLE
Recipe for more "natural" `TimeType` xtick positions

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/Plots.jl#714]
Hi @tbreloff and @mkborregaard, I wrote a recipe to choose more "natural" (in my opinion) xtick positions if the first input to plot() is a `Date` or `DateTime` array. More "natural" means that full seconds/minutes/hours/days/months/years are chosen (depending on the time span) - see the figures below for comparison:

standard:
![std_ticks](https://cloud.githubusercontent.com/assets/16589944/23474844/757a17e8-feb5-11e6-8507-fe6c25ccfe2a.png)

with `TimeType` recipe:
![opt_ticks](https://cloud.githubusercontent.com/assets/16589944/23474855/7f731b50-feb5-11e6-879e-ae4ef73b8f34.png)

I'm not sure if this is  of interest/use for anyone. If it is, where would be the best place to put the code?

**Comment by tbreloff** [comment]
This is cool!  If you post the code I might have a better idea of where it would fit.  I get the feeling this can't be added to the existing type recipes.

**Comment by daschw** [comment]
```
using Base.Dates, RecipesBase

# Round DateTime dt to the next "round" DateTime with respect to (Period)Type P
function _round_up(dt::DateTime, P::Type)
    period_hierarchy = [Millisecond, Second, Minute, Hour, Day, Month, Year]
    i = findfirst(period_hierarchy .== P)
    DateTime((PH(dt) for PH in period_hierarchy[end:-1:i])...) + P(1)
end

function _get_ticks(x_min::DateTime, x_max::DateTime, P::Type, steplength::Integer)
    period_hierarchy = [Millisecond, Second, Minute, Hour, Day, Month, Year]
    i = findfirst(period_hierarchy .== P)
    showtype = i >= 5 ? Date : DateTime
    ticks = _round_up(x_min, P):P(steplength):x_max
    return Integer.(ticks), string.(showtype.(ticks))
end

function _get_ticks(x_min::DateTime, x_max::DateTime)
    Δt = x_max - x_min
    # number of ticks is not very flexible and may be set here:
    m = 4 # expected number of ticks
    n = 2 #
    if Δt > Day(365n)
        P = Year
        steplength = Δt / (m * Millisecond(Day(365)))
    elseif Δt > Day(30n)
        P = Month
        steplength = Δt / (m * Millisecond(Day(30)))
    elseif Δt > Day(n)
        P = Day
        steplength = Δt / (m * Millisecond(Day(1)))
    elseif Δt > Hour(n)
        P = Hour
        steplength = Δt / (m * Millisecond(Hour(1)))
    elseif Δt > Minute(n)
        P = Minute
        steplength = Δt / (m * Millisecond(Minute(1)))
    elseif Δt > Second(n)
        P = Second
        steplength = Δt / (m * Millisecond(Second(1)))
    else
        P = Millisecond
        steplength = Δt / (m * Millisecond(1))
    end
    _get_ticks(x_min, x_max, P, max(1, Integer(round(steplength))))
end

@recipe function f{T<:TimeType}(dt::AbstractArray{T}, y)
    xticks --> _get_ticks(DateTime(minimum(dt)), DateTime(maximum(dt)))
    Integer.(DateTime.(dt)), y
end
```

**Comment by daschw** [comment]
At first I was thinking about modifying the optimize_ticks method for TimeTypes in PlotUtils. But I think it never gets called because TimeTypes are converted to Integers before (correct me if I'm wrong - I'm not that familiar with the Plots pipeline). So I just made this recipe ... probably there's a far more elegant way to do this ;-)

**Comment by tbreloff** [comment]
Actually it might be possible to add an `else if ticks == :datetime` section [here](https://github.com/JuliaPlots/Plots.jl/blob/master/src/axes.jl#L167) which calls your logic?

**Comment by tbreloff** [comment]
then you don't need to call a special recipe... you can do this for any "date axis"

**Comment by daschw** [comment]
Seems reasonable! And `ticks = :datetime` would be set by the user? Or within the existing `DateTime` recipe?

**Comment by tbreloff** [comment]
Maybe either?  Not sure, but you're welcome to experiment with it!

**Comment by mkborregaard** [comment]
This is great! I think this could be the default for TimeType x axis.

**Comment by daschw** [comment]
OK, I will. Just two more questions (for now):
- At this point in the code (the link you posted) are the `TimeTypes` already converted to Integers (`amin` and `amax`)?
- Would you put my logic in PlotUtils like optimize_ticks or in axes.jl

**Comment by daschw** [comment]
Thanks @mkborregaard !

**Comment by tbreloff** [comment]
> At this point in the code (the link you posted) are the TimeTypes already converted to Integers

Yes (I think)

> Would you put my logic in PlotUtils like optimize_ticks or in axes.jl

Maybe put the generic methods in PlotUtils and call them from axes.jl?

**Comment by daschw** [comment]
Hm, setting `ticks --> :datetime` in the `DateTime` Type recipe [here](https://github.com/JuliaPlots/Plots.jl/blob/master/src/recipes.jl#L796) sets `ticks = :datetime` for all axes.
Is it possible to only set the ticks of the axis where the Type occurs in a Type recipe?

**Comment by tbreloff** [comment]
Maybe the right  solution is to use a functor for the formatter and check
the type of the formatter instead of checking "ticks"
