### ISSUE TITLE
GR backend: legend doesn't match markersize? 

### ISSUE THREAD

**Issue by xiaoweiz** [JuliaPlots/Plots.jl#717]
Not sure if this is a bug, but I couldn't find a way to fix it. 

```julia
using Plots
gr()
x = linspace(0, 5)
plot(x, sin(x), markershape=:square, markersize=3)
```

The marker in the legend doesn't change regardless the specs in the plotting command. 

![test](https://cloud.githubusercontent.com/assets/4540215/23589411/68ecfb58-0207-11e7-8a3c-77d734cb2507.png)

**Comment by tbreloff** [comment]
It's not a bug. The legend marker is a fixed size.

**Comment by xiaoweiz** [comment]
Thanks for clarifying this. Is there a workaround to change it? I find the current size is too large.

**Comment by tbreloff** [comment]
I think this has been changed on master?

**Comment by xiaoweiz** [comment]
I've checked out the master branch and can confirm it's fixed. Thanks!
