### ISSUE TITLE
slightly exaggerated PyPlot example in the manual

### ISSUE THREAD

**Issue by stevengj** [JuliaPlots/Plots.jl#719]
The PyPlot [example in the manual](https://juliaplots.github.io/pipeline/ seems a lot more complicated than necessary.  The simplest analogue of the `using Plots; plot(...)` example in the manual would be
```jl
using PyPlot
figure(figsize=(4,3), dpi=100)
plot(x, y[:,1], alpha = 0.5, "steelblue", linewidth = 4)
scatter(x, y[:,2], alpha = 0.5, marker = "+", s = 100, c="orangered")
plt[:hist](y[:,3], orientation = "horizontal", alpha = 0.5,
                   normed = true, bins=30, color="green",
                   linewidth = 0)
grid()
title("My title")
legend(["y1","y2"])
```

**Comment by stevengj** [comment]
Also, a lot of the complexity here is simply that Matplotlib has different defaults than Plots.  If you are willing to accept Matplotlib's defaults (since you were willing to accept Plots' defaults), you can do:
```
using PyPlot
plot(x, y[:,1], alpha = 0.5, linewidth = 4)
plot(x, y[:,2], alpha = 0.5, "r+")
plt[:hist](y[:,3], orientation = "horizontal", alpha = 0.5,
                   normed = true)
grid()
title("My title")
legend(["y1","y2"])
```

**Comment by stevengj** [comment]
(Plots is a great package, but I don't think the current comparison to PyPlot is informative.)

**Comment by tbreloff** [comment]
I'll merge a PR which changes this

**Comment by tbreloff** [comment]
And to be clear... that specific section was to be explicit about what is
happening "inside" Plots, in that it's not "just calling PyPlot's plot
method".  It was not meant to be "look at how much better Plots is".  So
accepting PyPlot's defaults would be completely against the intention of
the section.

**Comment by stevengj** [comment]
Fair enough.
