### ISSUE TITLE
Colors cannot be specified in Pie charts - make it a `series recipe`

### ISSUE THREAD

**Issue by arnim** [JuliaPlots/Plots.jl#723]
Hi,

I'm looking for a way to set the color in Pie charts.

Given the example in the manual
```
x = ["Nerds","Hackers","Scientists"]
y = [0.4,0.35,0.25]
pie(x,y,title="The Julia Community",l=0.5)
```
I tested a some variations to set some custom colors e.g.
```
pie(x,y,title="The Julia Community",color=[:yellow,:black, :red])
pie(x,y,title="The Julia Community",fillcolor=[:yellow,:black, :red])
...
```
Yet, none of which seemed to have a effect.

Is there a way to to use custom colors?
I'm currently on the `gr()` backend.

Thanks

**Comment by pkofod** [comment]
I might be wrong, but I don't think this is possible, you could certainly add the functionality though. Also, remember to do horizontal concatenation `[:yellow :black :red]` when doing stuff like this.

**Comment by arnim** [comment]
@pkofod thanks for your reply.
At least I will keep the horizontal concatenation in mind ;)

**Comment by tbreloff** [comment]
Pie charts should be a plot recipe, which creates a shape series and
removes axes. It should be relatively easy to make... anyone up for it?

**Comment by arnim** [comment]
@tbreloff sounds great ... maybe I would give it a shot.
What shapes do you have in mind for the "pie slices" ?

**Comment by tbreloff** [comment]
Ummm. Pie shapes?? :)

**Comment by mkborregaard** [comment]
@arnim something like
```julia
theta = 1
plot([(0,0); Plots.partialcircle(0,theta)], seriestype = :shape, aspectratio = 1)
```

**Comment by arnim** [comment]
@mkborregaard Perfect... thanks Michael!
