### ISSUE TITLE
heatmap seriestype not defined for UnicodePlots

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#724]
I guess the heatmap seriestype could be defined using UnicodePlots' `densityplot`.

**Comment by btmit** [comment]
UnicodePlots now appears to have heatmap defined explicitly. 

Any chance that could be leveraged by Plots?

**Comment by mkborregaard** [comment]
Yes I think you just have to add heatmap to the list of supported seriestypes
