### ISSUE TITLE
Animation fail 

### ISSUE THREAD

**Issue by olegmikul** [JuliaPlots/Plots.jl#728]
For both frame(anim) in plotlyjs animation examples and @gif in attractor example I have errors: 

MethodError: no method matching handle_new_from_data(::Dict{String,Any})
Closest candidates are:
  handle_new_from_data(::AbstractString) at /home/username/.julia/v0.5/Rsvg/src/calls.jl:69
  handle_new_from_data(::AbstractString, ::Gtk.GLib.GError) at /home/username/.julia/v0.5/Rsvg/src/calls.jl:61

Ffmpeg is installed. 

My Julia and Package versions are as follows: 
16 required packages:
 - GLVisualize                   0.2.2
 - GR                            0.19.0
 - IJulia                        1.4.1
 - ImageMagick                   0.2.2
 - InspectDR                     0.1.6
 - JuliaParser                   0.7.4
 - Knet                          0.8.2
 - Mocha                         0.2.0
 - ParallelAccelerator           0.2.2              6da2e374 (dirty)
 - PlotRecipes                   0.2.0
 - PlotlyJS                      0.5.2
 - Plots                         0.10.3
 - RDatasets                     0.2.0
 - Rsvg                          0.0.2
 - StatPlots                     0.2.1
 - Winston                       0.12.1
117 additional packages:
 - AbstractTrees                 0.1.0
 - AutoGrad                      0.0.6
 - AxisAlgorithms                0.1.6
 - AxisArrays                    0.0.6
 - BaseTestNext                  0.2.2
 - BinDeps                       0.4.7
 - Blink                         0.5.1
 - Blosc                         0.2.0
 - Cairo                         0.2.35
 - Calculus                      0.2.1
 - CatIndices                    0.0.2
 - Codecs                        0.3.0
 - ColorTypes                    0.3.5
 - ColorVectorSpace              0.4.0
 - Colors                        0.7.3
 - Compat                        0.20.0
 - CompilerTools                 0.2.1
 - ComputationalResources        0.0.2
 - Conda                         0.5.1
 - CoordinateTransformations     0.4.0
 - CustomUnitRanges              0.0.4
 - DataArrays                    0.3.12
 - DataFrames                    0.8.5
 - DataStructures                0.5.2              402a6d45 (dirty)
 - Dates                         0.4.4
 - DiffBase                      0.0.4
 - Distributions                 0.12.1
 - DocOpt                        0.2.1
 - DocStringExtensions           0.3.1
 - DualNumbers                   0.3.0
 - FFTViews                      0.0.2
 - FileIO                        0.3.0
 - FixedPointNumbers             0.3.5
 - FixedSizeArrays               0.2.5
 - ForwardDiff                   0.4.0
 - FreeType                      1.2.0
 - GLAbstraction                 0.3.1
 - GLFW                          1.3.0
 - GLWindow                      0.3.2
 - GZip                          0.2.20
 - GeometryTypes                 0.2.2
 - Graphics                      0.1.4
 - Gtk                           0.12.0
 - HDF5                          0.7.3
 - Hiccup                        0.1.1
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.7
 - ImageAxes                     0.1.1
 - ImageCore                     0.1.5
 - ImageFiltering                0.1.2
 - ImageMetadata                 0.2.1
 - ImageTransformations          0.1.0
 - Images                        0.8.0
 - IndirectArrays                0.1.1
 - IniFile                       0.2.5
 - Interpolations                0.3.8
 - IntervalSets                  0.0.3
 - Iterators                     0.3.0
 - JLD                           0.6.9
 - JSON                          0.8.3
 - Juno                          0.2.7
 - KernelDensity                 0.3.2
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.5
 - LegacyStrings                 0.2.0
 - LineSearches                  0.1.5
 - Logging                       0.3.1
 - MacroTools                    0.3.6
 - MappedArrays                  0.0.6
 - MbedTLS                       0.4.3
 - Measures                      0.0.3
 - Media                         0.2.5
 - MeshIO                        0.0.6
 - ModernGL                      0.1.1
 - Mustache                      0.1.3
 - Mux                           0.2.3
 - NaNMath                       0.2.2
 - Nettle                        0.3.0
 - NetworkLayout                 0.0.1
 - NumericIO                     0.1.0
 - OffsetArrays                  0.2.14
 - Optim                         0.7.8
 - PDMats                        0.5.6
 - Packing                       0.0.4
 - PlotThemes                    0.1.1
 - PlotUtils                     0.3.0
 - PositiveFactorizations        0.0.4
 - QuadGK                        0.1.1
 - Quaternions                   0.1.1
 - RData                         0.0.4
 - RangeArrays                   0.1.2
 - Ratios                        0.0.4
 - Reactive                      0.3.7
 - RecipesBase                   0.1.0
 - Reexport                      0.0.3
 - Rmath                         0.1.6
 - Rotations                     0.3.5
 - SHA                           0.3.2
 - SIUnits                       0.1.0
 - ShowItLikeYouBuildIt          0.0.1
 - Showoff                       0.0.7
 - SignedDistanceFields          0.1.0
 - SimpleTraits                  0.3.0
 - SortingAlgorithms             0.1.0
 - SpecialFunctions              0.1.1
 - StaticArrays                  0.3.0
 - StatsBase                     0.13.1
 - StatsFuns                     0.4.0
 - TexExtensions                 0.0.3
 - TiledIteration                0.0.2
 - Tk                            0.4.0
 - URIParser                     0.1.7              df52383c (dirty)
 - UnicodeFun                    0.0.2
 - WebSockets                    0.2.1
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.4.1

**Comment by tbreloff** [comment]
Please open in Rsvg instead?

**Comment by olegmikul** [comment]
Sorry, I am a new in Plots (while very enthusiastic) - how to open in Rsvg ?

**Comment by tbreloff** [comment]
Sorry. I meant that this sounds like an error in the Rsvg package, not in
Plots, and that you're more likely to get your error resolved if you post
the issue there.

**Comment by olegmikul** [comment]
I see. Thanks!

**Comment by lobingera** [comment]
@tbreloff, 

> I meant that this sounds like an error in the Rsvg package

Why?

**Comment by tbreloff** [comment]
Because that's where the error was? At a minimum it's because something
changed in PlotlyJS? Either way, highly unlikely to require a fix in Plots

**Comment by pkofod** [comment]
also, remember to put backticks around macros like this `@gif` . You pinged a user with the name gif :) Not a very active user, but..

**Comment by lobingera** [comment]
@tbreloff Did you test with PlotlyJS?

I tend to disagree the error is in Rsvg, as Rsvg provides a correct handler_new_from_data and a Dict would make no sense in this argument, so i'd conclude the issue is in the caller.

**Comment by mkborregaard** [comment]
I cannot reproduce this error with plotlyjs() - the lorenz gif example works correctly (if very slowly). I do get an ImageMagick error on gr (but ImageMagick errors are common on my machine).

**Comment by mkborregaard** [comment]
Should this issue be closed?

**Comment by lobingera** [comment]
@olegmikul ?
