### ISSUE TITLE
Polar heatmap

### ISSUE THREAD

**Issue by aborzunov** [JuliaPlots/Plots.jl#732]
I don't know whether this is my misunderstanding or bag but i dare to create this issue with polar heatmaps.
I want to get a heatmap of paraboloid in polar coordinates. Something like this:
https://i.stack.imgur.com/L1pto.png
```julia
using Plots
pyplot()
z = [  (i)^2 for i=linspace(0, 5, 50) , k = linspace(0, 2*pi, 50) ]
heatmap(z,proj=:polar,leg=false)
```
https://imgur.com/a/StWxh
which results in heatmap with some artefacts near outer border.
If i decrease discretisation  i obtain some polygon inscribed in circle.
` z = [  (i)^2 for i=linspace(0, 5, 10) , k = linspace(0, 2*pi, 10) ] `
https://imgur.com/a/l4ckz]

With PyPlot i managed to achieve desired result:
```julia
using PyPlot
using QuantEcon: meshgrid
rad = linspace(0, 5, 50)
azm = linspace(0, 2 * pi, 50)
z = [  (i)^2 for i in rad , k in azm ]

fig = figure(figsize=(8,6))
ax = fig[:gca](projection="polar")
xgrid, ygrid = meshgrid(azm,rad)
ax = plt[:contourf](xgrid,ygrid,z)
```
[http://imgur.com/a/urzL3](url)

**Comment by zsoerenm** [comment]
I'm getting the same artifacts. Any news on this?

**Comment by BeastyBlacksmith** [comment]
close in favor of #1007
