### ISSUE TITLE
Annotations not working with PGFPlots

### ISSUE THREAD

**Issue by jebej** [JuliaPlots/Plots.jl#735]
As per the [example](https://juliaplots.github.io/examples/pgfplots/#annotations), and in my own trials as well.

**Comment by daschw** [comment]
The problem is the `#3` sign in the text, which LaTeX interprets as parameter.
```julia
plot(y,annotations=(3,y[3],text("this is \\#3",:left)),leg=false)
```
works.
Maybe we should edit the example.

**Comment by BeastyBlacksmith** [comment]
Thats fixed in pgfplotsx
