### ISSUE TITLE
Grid lines change

### ISSUE THREAD

**Issue by samdeetwo** [JuliaPlots/Plots.jl#736]
Hello
rerunning a series of plots this morning to correct the titles, and all grid lines are suddenly plain black (they were dash grey yesterday). Only thing I can figure is it is linked to this new warning I got:

sys:1: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.

I use Plots with the Pyplot backend. Any clues as to how to change the grid lines back?

**Comment by daschw** [comment]
cf https://github.com/JuliaPlots/Plots.jl/issues/704
this has been fixed on master by https://github.com/JuliaPlots/Plots.jl/pull/721

**Comment by mkborregaard** [comment]
Closed as dup of #704
