### ISSUE TITLE
LatexStrings not working with PlotlyJS backend

### ISSUE THREAD

**Issue by jebej** [JuliaPlots/Plots.jl#737]
Plotly itself supports latex, so I'm sure it's just a matter of passing the right string. Where would the code for that be?

**Comment by mkborregaard** [comment]
The information you are providing is a little sparse.
Having tried it out, I can say that latex-strings works on every first plot to a plotlyjs window, but not subsequent ones, in the REPL. And they don't work in Atom. If you want to try to dig into this, you'd look in `plotlyjs.jl` or `plotly.jl` in the src/backends folder of Plots.

**Comment by Godisemo** [comment]
I believe this issue is located outside of the Plots.jl package, as I experienced the same bug when using PlotlyJS.jl directly.

**Comment by mkborregaard** [comment]
@jebej could you try enquiring on PlotlyJS.jl?

**Comment by jebej** [comment]
Yes, this is an issue with PlotlyJS, on IJulia: [#60](https://github.com/sglyon/PlotlyJS.jl/issues/60)

I'll close the issue here.
