### ISSUE TITLE
No transparency for surface plots

### ISSUE THREAD

**Issue by dpsanders** [JuliaPlots/Plots.jl#738]
Changing `alpha` seems to have no effect on surface plots with PlotlyJS and GR.
It does work with PyPlot.

**Comment by lnacquaroli** [comment]
For me the `alpha` parameter it does work for `PyPlot` standalone, but not for `pyplot()` inside `Plots`.

**Comment by hervasa2** [comment]
I have also run into this issue with gr(). Have also tried `fillalpha` and using `color = RGBA()`. Alpha is not respected in either case. In pyplot() `color = RGBA()` works.

**Comment by LinusSch** [comment]
I've stumbled on this too, with GR, first in a Pluto notebook but also from a fresh REPL. I have tried `alpha`, `color = RGBA()`, `fillalpha` and `fillcolor = RGBA()` just to be thorough on at least one detail.
