### ISSUE TITLE
World Age 

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaPlots/Plots.jl#745]
On
```julia
julia> versioninfo()
Julia Version 0.6.0-pre.alpha.220
Commit 89609cf* (2017-03-22 20:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

I run into this error using Plots and IJulia on master:
```julia
using Plots # in IJulia

InitError: MethodError: no method matching set_ijulia_output(::String)
The applicable method may be too new: running in world age 21616, while current world is 21619.
Closest candidates are:
  set_ijulia_output(::AbstractString) at /Users/Mikael/.julia/v0.6/Plots/src/output.jl:261 (method too new to be called from this world context.)
during initialization of module Plots

Stacktrace:
 [1] setup_ijulia() at /Users/Mikael/.julia/v0.6/Plots/src/output.jl:274
 [2] __init__() at /Users/Mikael/.julia/v0.6/Plots/src/Plots.jl:229
 [3] _include_from_serialized(::String) at ./loading.jl:157
 [4] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:194
 [5] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:224
 [6] require(::Symbol) at ./loading.jl:409
```

Changing line 274 in output.jl:
```julia
        set_ijulia_output("text/html")
```
to:
```julia
        @eval set_ijulia_output("text/html")
```
fixes the issue.

**Comment by barche** [comment]
The following also triggers this, when including it as a file from the REPL and using GR as default backend:

```julia
using Plots
display(plot(rand(4,4)))
```

Error trace:
```
ERROR: LoadError: MethodError: no method matching clearws()
The applicable method may be too new: running in world age 21672, while current world is 21673.
Closest candidates are:
  clearws() at /home/user/.julia/v0.6/GR/src/GR.jl:369 (method too new to be called from this world context.)
Stacktrace:
 [1] gr_display(::Plots.Plot{Plots.GRBackend}) at /home/user/.julia/v0.6/Plots/src/backends/gr.jl:464
 [2] _display(::Plots.Plot{Plots.GRBackend}) at /home/user/.julia/v0.6/Plots/src/backends/gr.jl:1120
 [3] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Plots.Plot{Plots.GRBackend}) at /home/user/.julia/v0.6/Plots/src/output.jl:138
 [4] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::Plots.Plot{Plots.GRBackend}) at ./REPL.jl:125
 [5] display(::Plots.Plot{Plots.GRBackend}) at ./multimedia.jl:194
 [6] include_from_node1(::String) at ./loading.jl:539
 [7] include(::String) at ./sysimg.jl:14
while loading /home/user/tmp/test.jl, in expression starting on line 2
```

**Comment by mkborregaard** [comment]
@MikaelSlevinsky Feel like making a PR?

**Comment by mkborregaard** [comment]
The original (IJulia) issue is fixed now. @barche the current workaround for your issue is to call the backend explicitly before the plot call.
```julia
using Plots
gr()
display(plot(rand(4,4)))

**Comment by mkborregaard** [comment]
One suggested solution here: https://github.com/JuliaPlots/Plots.jl/pull/808

**Comment by stevengj** [comment]
I just noticed a missing `invokelatest` in IJulia (https://github.com/JuliaLang/IJulia.jl/commit/1b17812b9ee2a544821fe4d00cfd9ac93a2491e5) ... can you check whether this fixes the Plots issue if you check out the latest IJulia master?

**Comment by mkborregaard** [comment]
Thanks @stevengj ! In fact, somewhat confusingly, the IJulia world-age issue was fixed a while ago - we left this issue open because @barche 's unrelated issue just above here still isn't fixed. @barche could you make a new issue and we'll close this one? Thanks!

**Comment by oschulz** [comment]
I  can confirm this issue on Julia 0.6, with PyPlot (used by default, no other backend installed), with a fresh minimal JULIA_PKGDIR (only ```Pkg.add.(["Plots", "PyPlot"])```).

```
julia> using Plots
julia> plot(size=(800,500), legendfont=font(20))
INFO: Precompiling module PyPlot.
ERROR: MethodError: no method matching gcf()
The applicable method may be too new: running in world age 23992, while current world is 24001.
```

**Comment by mkborregaard** [comment]
Yeah, you currently mostly need to call the backend explicitly, e.g. `using Plots; pyplot()`

**Comment by oschulz** [comment]
Jup, that workaround helps. Any idea why? Is it something easy to fix, or some deeper issue?

**Comment by mkborregaard** [comment]
Not sure in fact :confused: but I think it must be that the 'world' of Plots is changed by eval after pickDefaultBackend is called.

**Comment by mkborregaard** [comment]
It'd be much appreciated if you can see a solution.

**Comment by stevengj** [comment]
One option would be to call all backend functions via `invokelatest`.

**Comment by mkborregaard** [comment]
Yes there's a PR for that https://github.com/JuliaPlots/Plots.jl/pull/808 . It doubles the time it takes to call `plot` though.

**Comment by oschulz** [comment]
That would be a steep price to pay, considering the fact that calling plot (the first time) already takes a very long time ...

**Comment by mkborregaard** [comment]
It's only the price for subsequent plots, thankfully.

**Comment by oschulz** [comment]
Ah, that's not quite so horrible, then. I haven't really kept track - what's become of the project of splitting Plots into a core and backend-specific packages, to get rid of these things (and possibly speed up the first plot in a session)?

**Comment by mkborregaard** [comment]
It's being revived in the sense that I promised to do it but haven't done it yet...

**Comment by oschulz** [comment]
Thanks!

**Comment by ChrisRackauckas** [comment]
Is this done?

**Comment by mkborregaard** [comment]
I get it from time to time

**Comment by mkborregaard** [comment]
No longer an issue
