### ISSUE TITLE
Improper handling of very large and very small exponents with PyPlot 

### ISSUE THREAD

**Issue by stillyslalom** [JuliaPlots/Plots.jl#749]
Axis markers are not especially useful for large-magnitude numbers:

- Insufficient numbers of ticks
- No use of scientific notation
- Lower limit not set to zero when sensible (ymax >> ymin) and padded slightly below

```julia
xx = rand(1000) ./ sqrt.(rand(1000))
yy = xx.^(-1)*1e-20
scatter(xx,yy)
```
![oddaxis](https://cloud.githubusercontent.com/assets/4324760/24376954/4994074e-1303-11e7-9a4e-d115b16bb0d2.png)

Matplotlib's native behavior handles this correctly:

```
import numpy as np
from numpy.random import rand
import matplotlib.pyplot as plt

xx = rand(1000)/np.sqrt(rand(1000))
yy = (1e-20)*1./xx
plt.plot(xx, yy, "o")
```
![image](https://cloud.githubusercontent.com/assets/4324760/24377070/af56fc44-1303-11e7-90cd-9838246de851.png)

**Comment by ChrisRackauckas** [comment]
Same as https://github.com/JuliaPlots/Plots.jl/issues/430

**Comment by mkborregaard** [comment]
Nicely spotted.

**Comment by t-bltg** [comment]
Seems fixed.
