### ISSUE TITLE
Plot to specific Blink.Window() 

### ISSUE THREAD

**Issue by bluehope** [JuliaPlots/Plots.jl#755]
Is there a way to perform a plot in a specific Blink.Window?

For example If I have Blink.window [w1, w2].
```Julia
import Plots
Plots.plotlyjs()

import Blink
w1 = Blink.Window()
w2 = Blink.Window()
```
Can I plot separately in a [w1,w2] window?
```Julia
Plots.plot(rand(10,1)) # Plot to w1
Plots.plot(rand(10,3)) # Plot to w2
```
Thanks in advance.

**Comment by mkborregaard** [comment]
I know this does not answer your question - but you can achieve what the example does by
```julia
using Plots
plot(rand(10,1))
plot(rand(10,3), reuse = false)
```

**Comment by WeiMXi** [comment]
I'm try to it now, but I using Plotly
```
using Plotly
using Blink
fig1 = plot(rand(10, 1));
fig2 = plot(rand(10, 3));
w1 = Window()
w2 = Window()
body!(w1, fig1.scope)
body!(w2, fig2.scope)
# now exchange them
body!(w1, fig2.scope)
body!(w2, fig1.scope)
```
but it seem plotly [not update for julia 1.3.1](https://github.com/plotly/graphing-library-docs/issues/16)(my version), some function can't use.
