### ISSUE TITLE
How to build offline Plots docs?

### ISSUE THREAD

**Issue by AStupidBear** [JuliaPlots/Plots.jl#756]

**Comment by ChrisRackauckas** [comment]
See https://github.com/JuliaDocs/Documenter.jl/pull/288

**Comment by AStupidBear** [comment]
But, there's no make.jl in [docs](https://github.com/JuliaPlots/PlotDocs.jl/tree/master/docs)

**Comment by ChrisRackauckas** [comment]
Oh it's not using Documenter.jl? Then I don't know.

**Comment by AStupidBear** [comment]
I just want to build offline html version docs of Plots for [Zeal](https://zealdocs.org/)

**Comment by mkborregaard** [comment]
can't you just clone the repo and run the code?

**Comment by AStupidBear** [comment]
@mkborregaard The grabbed version dosen't support search. Yesterday I looked for ```make.jl``` or ```Makefile```, bacause I hadn't used ```mkdocs``` previously, but couldn't find one. I have successfully built it today.
