### ISSUE TITLE
GR and rotated text on the x-axis

### ISSUE THREAD

**Issue by tcovert** [JuliaPlots/Plots.jl#757]
When I use text-based values for the x-axis in GR and rotate them 90 degrees using `plot(...,xrotation=90)`, these x values are _centered_ on the x axis, as opposed to having the left end of the text line up on the x axis.

![gr](https://cloud.githubusercontent.com/assets/4276172/24677794/a80512c8-194d-11e7-8039-2ffb3689e6d3.png)

PyPlot does not seem to have this problem.
![pyplot](https://cloud.githubusercontent.com/assets/4276172/24677801/aedf33f8-194d-11e7-8516-260c4c0d2fd8.png)

is there a way to fix this?

**Comment by mkborregaard** [comment]
This is a known issue in GR https://github.com/JuliaPlots/Plots.jl/issues/314#issuecomment-278296274
@jheinen described the issue in that thread, which appears to be inside GR itself.

**Comment by mkborregaard** [comment]
Awesome! Will that fix it automatically in Plots as well?

**Comment by jheinen** [comment]
I forgot. It was fixed in eb7534d319afc07782277984460fb2ea0504cb9a . But there's still some room for optimisation if `|rotation_angle| >= 90` ...

**Comment by mkborregaard** [comment]
so @tcovert you should have this working if you checkout master of GR and Plots

**Comment by jheinen** [comment]
@tcovert, did you check this with GR and Plots master ?

**Comment by ssfrr** [comment]
I can confirm this is fixed as of the latest Plots release.
