### ISSUE TITLE
Feature request: Text labels for xticks in heatmaps

### ISSUE THREAD

**Issue by lissonc** [JuliaPlots/Plots.jl#765]
Strings as xticks do not seem to be available for heatmaps yet. Perhaps this could be implemented? Passing an `Array{String,1}` as `label` returns `MethodError: no method matching isless(::String, ::Float64)`.

**Comment by mkborregaard** [comment]
Just pass them to the call as the x/y args (the Matrix is z), e.g. `heatmap(["$x" for x in 1:10], (1:10)+5, randn(10,10))`

**Comment by lissonc** [comment]
I'm not sure I understand. I'm trying to visualize a correlation matrix for financial asset returns and want to display the asset tickers as xticks and yticks; so I have to pass the correlation matrix to the function call. How could I "pass [the asset names] as x and y args" when all I've got is a string array of asset names?

**Comment by mkborregaard** [comment]
Could you post an MWE?

**Comment by mkborregaard** [comment]
I am happy to reopen if this is a feature that is indeed missing, but if you post the code you're working with it'd be a lot easier for me to tell.

**Comment by lissonc** [comment]
Consider, for example, this:

```
tickers = ["AAPL", "TSLA", "AMZN"]
heatmap(randn(3, 3), xticks = tickers, yticks = tickers)
```
Here, the `randn(3, 3)` represents a (not very realistic) correlation matrix between the assets' returns.

Passing `tickers` as `xticks` returns the error I mentioned...

**Comment by mkborregaard** [comment]
Just do `heatmap(tickers, tickers, randn(3,3))`, like I did in my example above. The locations of the xticks are slightly off on GR but should work on the other backends.
