### ISSUE TITLE
lw=0 no longer removes black shape edge in GR

### ISSUE THREAD

**Issue by dpsanders** [JuliaPlots/Plots.jl#788]
Using the option `lw=0` (i.e. `linewidth = 0`) used to remove the black boundary drawn around shapes. It no longer seems to do so. 

(I'm using the GR backend with Plots.jl latest master.)

**Comment by dpsanders** [comment]
This seems to be unique to the GR backend; `lw=0` works correctly with `PlotlyJS`.

**Comment by dpsanders** [comment]
cc @jheinen

**Comment by jheinen** [comment]
Sorry for the late response - it doesn't work with any backend (for me). So, it's probably a Plots issue. I'll check this ...

**Comment by mkborregaard** [comment]
For me it works in pyplot and plotlyjs

**Comment by daschw** [comment]
same here

**Comment by jheinen** [comment]
That's what I tried (with `PyPlot` and `plotlyjs`)
```julia
using Plots
scatter(randn(5),randn(5),lw=0,ms=10)
```
![screen shot 2017-05-03 at 08 53 13](https://cloud.githubusercontent.com/assets/5718244/25650541/f46ec6f8-2fdd-11e7-896f-0a9c51b53d6a.png)
... and that's the `gr()` result:
![screen shot 2017-05-03 at 08 54 58](https://cloud.githubusercontent.com/assets/5718244/25650577/3e481266-2fde-11e7-9d5f-9c07157612eb.png)
It seems that `GR` does never plot any marker boundaries, which is a bug :-(

**Comment by daschw** [comment]
I think for scatter plots the keyword is `markerstrokewidth` and not `linewidth`.
`bar(rand(10), lw = 0)` works as expected with `pyplot()`.

**Comment by daschw** [comment]
I have the same issue with `gr()` and marker boundaries.

**Comment by dpsanders** [comment]
I was referring to data plotted with the `:shape` attribute.

**Comment by jheinen** [comment]
@dpsanders : could you poivide a simple example script (which works fine with `pyplot` / `plotlyjs`_?

**Comment by daschw** [comment]
@jheinen I think replacing `GR.setlinewidth(max(1, lw / ((w + h) * 0.001)))` with `GR.setlinewidth(max(0, lw / ((w + h) * 0.001)))` [here](https://github.com/JuliaPlots/Plots.jl/blob/master/src/backends/gr.jl#L341) would solve the issue. At least it solves the issue for `bar(rand(10), lw = 0)`. Do you see any problem with this change?

**Comment by jheinen** [comment]
No, This looks reasonable. I should have looked into the change history :-)

Thanks for the hint. I'll fix it soon.

**Comment by mkborregaard** [comment]
This is fixed and can be closed, right?
