### ISSUE TITLE
ERROR: KeyError: key "set_facecolor" not found, using pyplot

### ISSUE THREAD

**Issue by stefesse** [JuliaPlots/Plots.jl#813]
Hi,
I have problem in plotting using pyplot. My code is:
```
using Plots
pyplot()

plot(rand(100))
```
and it gives the following error: 

> Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
> ERROR: KeyError: key "set_facecolor" not found

I checked and all my packages are updated:
> 7 required packages:
>  - IJulia                        1.5.0+             master
>  - JLD                           0.6.10
>  - Plotly                        0.1.1
>  - PlotlyJS                      0.6.2
>  - Plots                         0.10.3+            master
>  - PyPlot                        2.3.1
>  - RDatasets                     0.2.0

and also mathplotlib is updated to version 1.5.3
Do you have any suggestion? Thanks

**Comment by mkborregaard** [comment]
Yes, your matplotlib should be version 2.0 - are there some dependencies keeping this from updating?

**Comment by stefesse** [comment]
I thought it was updated, now it is and the code works. Thank you!

**Comment by diegozea** [comment]
Thanks! 

I solved it in *Ubuntu* (system-wide installation) using:

```bash
pip install matplotlib --upgrade
```

For a *Conda.jl* installation the solution is:
```julia
using Conda; Conda.update()
```

**Comment by fbruetting** [comment]
On Fedora 25 there is no v2 of Matplotlib available. How do I get this to working again?

**Comment by mkborregaard** [comment]
You probably have no choice but to `Pkg.pin("Plots", "0.10.2")`

**Comment by fbruetting** [comment]
I tried several Python update commands but none of them worked (seems that it updated via py3, but not via py2 since some header is missing). It's really shitty, having to mess around with Python just for getting JuliaPlots to work again (I have absolutely no clue of Python). I'll pin it back then, thanks for the hint!

**Comment by mkborregaard** [comment]
Oh but you don't by any means need to fiddle around with Python to get Plots in Julia to work. Only if want to plot via a python package! Maybe time to check out PlotlyJS or GR, or PGFPlots?

**Comment by fbruetting** [comment]
Yes, you're right, but PyPlot prints the nicest plots for me and coherent plots would be nice for my work. Hopefully this will work again in Fedora 26. :)
