### ISSUE TITLE
Change in histogram PlotReferenceImages

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/Plots.jl#817]
I wanted to run the VRT today and got the following:

![pyplot10_newissue](https://cloud.githubusercontent.com/assets/16589944/25964291/a608e662-3684-11e7-935c-297eec070d5c.png)

![pyplot15_new](https://cloud.githubusercontent.com/assets/16589944/25964100/fe307586-3683-11e7-83be-d612843af4b7.png)

Not only for PyPlot but also for GR:

![gr_10](https://cloud.githubusercontent.com/assets/16589944/25964146/222ae4bc-3684-11e7-984c-3749838c77df.png)

I looks like the automatically chosen number of bins has changed.
@oschulz I'm sorry that I am the one who has to bother you again, but is this related to your big histogram PR

Also, is this a regression or an expected change?

**Comment by daschw** [comment]
The change must have happened after https://github.com/JuliaPlots/Plots.jl/pull/794, because there you can see the old behavior

**Comment by oschulz** [comment]
@daschw, the default number of bins shouldn't have changed - it was 30 bins before, and it's 30 bins again now (with the new histogram implementation). The default axis range may have changed a bit, as we're using the `StatsBase.histrange(...)` for that, now.

**Comment by oschulz** [comment]
@daschw Ah, wait - actually, StatsBase.histrange(...) does adjust the number of bins, to make sure that the bin width is a number suitable for decimal scales.

**Comment by mkborregaard** [comment]
Exactly. This is an expected, and in my view, desired change. Thanks @daschw for the sharp eye, though!

**Comment by oschulz** [comment]
Agreed - thanks, @daschw. You're more than welcome to report any other changes in behaviour!

**Comment by daschw** [comment]
Ok, perfect, closing, since it is not an issue!
