### ISSUE TITLE
Warning from exporting single character identifiers

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#821]
```julia
h = 1; w = 2
using Plots
```
>WARNING: using Plots.w in module Main conflicts with an existing identifier.
WARNING: using Plots.h in module Main conflicts with an existing identifier.

**Comment by mkborregaard** [comment]
Yes

**Comment by juliohm** [comment]
@mkborregaard do you agree with the warning behavior?

**Comment by mkborregaard** [comment]
I just mean, yes, Plots exports h and w. Is that a problem for you downstream? I am not really aware of the details in this, but IIRC @ChrisRackauckas has discussed this with @tbreloff several times in the past.

**Comment by juliohm** [comment]
I just find it strange that single characters are being exported. Name conflicts are almost certain, specially with characters such as `w` and `h` for width and height.

**Comment by ChrisRackauckas** [comment]
>I just find it strange that single characters are being exported. Name conflicts are almost certain, specially with characters such as w and h for width and height.

I agree. I think if it needs to stay exported, it should have a more informative name.

**Comment by tbreloff** [comment]
My recommendation would be to put the measures stuff into an inner module
Measures, importall within Plots. Then if others want those variables in
their namespace they can do using Plots.Measures.

Of course this will break code (as will removing the export), but you'd
give users a one-line change to get the old exports back.

**Comment by ChrisRackauckas** [comment]
That makes a lot of sense.

**Comment by mkborregaard** [comment]
I agree with @tbreloff 's suggestion.

**Comment by mkborregaard** [comment]
So, can it be implemented along the lines as this https://github.com/JuliaPlots/Plots.jl/pull/855 ?

**Comment by mkborregaard** [comment]
Wait - I thought I agreed, but now I realise I have no idea why we can't just not export w and h?

**Comment by mkborregaard** [comment]
And then people can `import Plots: w, h` to get them back in the workspace with a single line? There is something about module scoping in Julia I am not 100% sharp on.

**Comment by ChrisRackauckas** [comment]
Yes

**Comment by rsidd** [comment]
Just ran into this issue.  Seriously, Plots exports variables called "w" and "h"?  Terrible idea. Please rename!

**Comment by mkborregaard** [comment]
Thanks for the feedback. There's on open PR for you to comment on, if you like.
