### ISSUE TITLE
yaxis limits cut in muliple series bar plots - unable to set ylims

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/Plots.jl#826]
```julia
using Plots
bar([2 1; 2 1])
```
produces this:
![bar_cropped](https://cloud.githubusercontent.com/assets/16589944/26058641/042c874c-397f-11e7-8d35-66deed76336f.png)
The yaxis limits are set based on the last series and not based on the one with the highest input.
```julia
bar([2 1; 2 1], ylims = (0, 2))
```
does not change anything. The only workaround is:
```julia
bar([2 1; 2 1])
ylims!((0, 2))
```
cc: @oschulz

**Comment by oschulz** [comment]
I'll look into it - it should, of course, be possible to override the ylims.

**Comment by oschulz** [comment]
See #827.

**Comment by oschulz** [comment]
Now looks like this:

```julia
bar([2 1; -2 -1])
```

![bars-two-plots](https://cloud.githubusercontent.com/assets/546147/26080397/b078b876-39c6-11e7-8a98-e902cbfde0c9.png)

**Comment by oschulz** [comment]
Thanks for reporting, @daschw!

**Comment by daschw** [comment]
Awesome
