### ISSUE TITLE
Make GR Tests Pass

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/Plots.jl#838]
I've been trying to tackle #670 again and most of the pyplot examples look quite ok.
However, since that issue has been created, there has also been a new GR binary release and some Plots look quite different. So I decided to open this issue and ask for your advice @jheinen and @mkborregaard:

1. Generally, the lines seem thicker now in most images and the marker sizes seem to have increased:
`test_examples(:gr, 11)`
![gr_line_marker](https://cloud.githubusercontent.com/assets/16589944/26165578/bf2bd5ae-3b30-11e7-9593-abc3c44a86f8.png)
`test_examples(:gr, 20)`
![gr_markersize](https://cloud.githubusercontent.com/assets/16589944/26165655/08c6a8ba-3b31-11e7-815c-ba85d82efa61.png)
Is this an issue or expected?

2. I already reported this in #670 but then forgot to create an issue. The custom marker shapes in this example are weirdly stretched:
`test_examples(:gr, 21)`
![gr_custom_markers](https://cloud.githubusercontent.com/assets/16589944/26165826/a52441fe-3b31-11e7-923f-43b27ac50ff0.png)

3. Here the axis ticklabels and the colorbar labels are cropped:
`test_examples(:gr, 24)`
![gr_colorbar_cropped](https://cloud.githubusercontent.com/assets/16589944/26165889/e415d10c-3b31-11e7-9d0f-572bb2bf8fc6.png)

4. And here the axis limits of the polar plot have changed:
`test_examples(:gr, 27)`
![gr_polar](https://cloud.githubusercontent.com/assets/16589944/26165858/c4f02b2e-3b31-11e7-9ec3-88df85e216c6.png)

Which of these changes would you consider issues and which would you consider expected or minor, in the sense that I should just save the new image?

**Comment by mkborregaard** [comment]
IMO we should reduce the markersize so they align better with the other backends and resolve the axis issue (is that just the margin that needs adjusting or is it something more fundamental). The polar plot limits are important too. So let's try to fix them. @jheinen you're the expert but are there any of these issues you'd like us to look at?

**Comment by jheinen** [comment]
I'll check these issues ASAP (I'm on the way for the next days). Some things (e.g. marker size), have to be emulated. In GR, the marker and text sizes are specified relatively (in normalized device coordinates) - in Plots, they are interpreted as absolute values (in the style of matplotlib), which IMO is **not** a good solution, as the apoearance of plots changes during resize operations. Moreover, all settings may vary in different backends.

May be, we should discuss this in the Gitter channel ...

**Comment by mkborregaard** [comment]
cf #733 , #740 and #742

**Comment by jheinen** [comment]
I started fixing bugs. Unfortunately, I have some trouble with the axes, which are no longer plotted using the `GR.axes()` function but using basic (discrete) `GR` drawing functions within `Plots.jl`. In the meantime I've come to the conclusion that it's easier to implement the missing functionality in the GR framework C API, which will be a major change.

**Comment by mkborregaard** [comment]
Ah, such is the nature of fixing bugs :-/
