### ISSUE TITLE
Failing to install on v0.6 rc 1

### ISSUE THREAD

**Issue by cormullion** [JuliaPlots/Plots.jl#842]
I had a go at installing the current release of Plots.jl on a new installation of Julia v0.6 rc1. It hasn't gone well. I think the error is here:
 
```
ERROR: MethodError: no method matching ioff()
The applicable method may be too new: running in world age 23854, while current world is 23874.
Closest candidates are:
  ioff(::Any...; kws...) at /Users/me/.julia/v0.6/PyPlot/src/PyPlot.jl:169 (method too new to be called from this world context.)

```

but there were so many warning I wasn't sure what was relevant. 😞

Full install log [here](https://gist.github.com/cormullion/2282e543426db27022f5bbc8ee3a6c65).

(I don't need to get it working soon, but I thought perhaps it might be useful to see what a new installation looks like...)

**Comment by mkborregaard** [comment]
Argh - that is the 'world age issue' with PyPlot #745 . It doesn't affect the other backends once Plots is installed, but a bit surprised that it affects a fresh install.
We'll try to get Plots master 0.6 ready within the month but this particular issue we don't really have a good solution for atm.

**Comment by cormullion** [comment]
No worries (from me at least...). I also got this

`ERROR: invalid redefinition of constant pycolors`

(somewhere around line 1198) which probably happens because I made more than one attempt at installing everything.

**Comment by mkborregaard** [comment]
By the way, this is not an installation issue - it is an issue with loading the pyplot backend. There's a PR (https://github.com/JuliaPlots/Plots.jl/pull/843) to change the default backend to one that works. `Pkg.rm("PyPlot")` or setting `ENV["PLOTS_DEFAULT_BACKEND"]` to `"GR"` will solve the issue for now.

**Comment by RalphAS** [comment]
A workaround (at least for REPL users):
```
import PyPlot
PyPlot.pygui(true)
using Plots
# now plot away
```

It appears that `pygui(false)` also works (one can call again later with `true` for displaying).  I don't understand Plots infrastructure well enough to know if it would work to invoke one or the other at backend initialization.

**Comment by mkborregaard** [comment]
Nice, that's worth investigating. It is caused by Plots using `eval` to conditionally import other modules.

**Comment by mkborregaard** [comment]
This is currently fixed.
