### ISSUE TITLE
Plotly labels in log scale don't use scientific notation

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#846]
```julia
plot(1.//2.^(7:-1:1),[2.22045e-16, 5.26246e-14, 1.55809e-12, 4.00526e-11, 7.00529e-10, 9.29049e-9, 1.74723e-6],xscale=:log10,yscale=:log10)
```

![](https://files.gitter.im/tbreloff/Plots.jl/L1Kw/newplot-_3_.png)

**Comment by mkborregaard** [comment]
Funny that both x and y scales are weird, but each in their different ways.

**Comment by mkborregaard** [comment]
I just checked out an 8 months old Plots version (release 9.2) and Plotly had the same behaviour. Either this has never worked on Plotly, or there has been a recent change to Plotly itself. @ChrisRackauckas have you had this working on the plotly backend before?

**Comment by ChrisRackauckas** [comment]
Yes, this used to just give scientific notation I believe. I at least have some old convergence charts which had it somewhere.

**Comment by juliohm** [comment]
I think it is fine to have log scale represented with the exponents. As soon as an option is made available that allows users to switch from scientific to log-notation, that would be ok. What concerns me is the actual numbers shown in the log scale in PlotlyJS, I think they are wrong? I may also be confused with log-scale conversions, but check this comparison:

## PyPlot:
![image1](https://user-images.githubusercontent.com/3345261/34704205-74f60b68-f4ac-11e7-8fd4-fb589258f837.png)

## PlotlyJS
![screenshot from 2018-01-08 19-38-03](https://user-images.githubusercontent.com/3345261/34704211-817e78fc-f4ac-11e7-9f6f-8431ff408f9f.png)

Notice that the numbers in the x axis in PlotlyJS don't match those in PyPlot. The way I am trying to match them is by taking a reading from PlotlyJS, let's say x=3, and calculating 10^3 = 1000. In PyPlot, the same point is just 10^1.5. It looks like the axis label is off by orders of magnitude? Or maybe I am reading things incorrectly? Is the x axis log_10 in PlotlyJS?

**Comment by juliohm** [comment]
Yes, I am probably reading the x axis wrong, always get confused with log scales. It doesn't make sense to just read x=3 and do 10^3 as there are multiple reading of 3 in the axis. Will Google it more carefully.

**Comment by juliohm** [comment]
Just sharing in casing someone is confused as well, the way to read it is to check the major labels like 10, 100, and then add this unit forward. For example, the first 2 after 10 is actually 2*10 = 20, the 3 I was reading before is 3*10 = 30. Anyways, sorry for the noise, this scale is definitely confusing :)

**Comment by omerchiers** [comment]
Hello,
I'm still having the same problem with the labels as shown in the first post.

doing 

`
using Plots; plotly()
x = 10 .^range(-2,2,length=100)
plot(x, exp.(x), xaxis = :log10, yaxis =:log10)
`
I get

![newplot(3)](https://user-images.githubusercontent.com/22425082/58955415-3841e000-879c-11e9-99c9-859912f202a4.png)

I'm on julia 1.1
Versions: 
- Plots: v0.25.1
- Plotly: v0.2.0

PlotlyJS is doing something similar. GR does print correctly scientific notations.
Any recommendations?
Many thanks
