### ISSUE TITLE
plot(img) has opposite orientation for display as Images

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Plots.jl#854]
I'm not sure if this is intentional, but the orientation of `plot(img)` is opposite of Images default display:
<img width="776" alt="untitled" src="https://cloud.githubusercontent.com/assets/1229737/26288440/e145c930-3ed5-11e7-9b74-e94411d8aa10.png">

**Comment by timholy** [comment]
This could be Images' "fault." We used to plot "horizontal-major" but there was a strong consensus that this was the wrong choice. So we switched in the 0.6 release.

**Comment by mkborregaard** [comment]
I'd say this means Plots needs to update the image orientation. It is controlled within the files for each backend by the `transpose_z` function, that needs to be applied (if it isn't) or have the third argument changed, for image types.

**Comment by mkborregaard** [comment]
Fixed for GR in https://github.com/JuliaPlots/Plots.jl/pull/874

**Comment by mkborregaard** [comment]
And works for the other backends.
