### ISSUE TITLE
Errors installing Plots.jl

### ISSUE THREAD

**Issue by albi3ro** [JuliaPlots/Plots.jl#861]
I'm trying to use `Plots.jl` for the first time.  Upon running

`Pkg.build("Plotly")`

I get 
`INFO: Building Plots
INFO: Cannot find deps/plotly-latest.min.js... downloading latest version.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
=================================================================================================[ ERROR: Plots ]==================================================================================================

LoadError: failed process: Process(`curl -o /home/antares/.julia/v0.5/Plots/deps/plotly-latest.min.js -L https://cdn.plot.ly/plotly-latest.min.js`, ProcessExited(77)) [77]
while loading /home/antares/.julia/v0.5/Plots/deps/build.jl, in expression starting on line 7

===================================================================================================================================================================================================================

=================================================================================================[ BUILD ERRORS ]==================================================================================================

WARNING: Plots had build errors.

 - packages with build errors remain installed in /home/antares/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Plots")`
 - build a single package by running its `deps/build.jl` script

===================================================================================================================================================================================================================
`

Upon trying to plot something, I get
`ERROR: KeyError: key "set_facecolor" not found
`

I'm running Julia 0.5.2 , though I think my jupyter notebook kernel might still be on 0.5.1 .  Ubuntu Gnome Computer.  PyPlot works fine.

**Comment by ChrisRackauckas** [comment]
Are you behind a firewall? The problem is that it couldn't download the javascript file for Plotly. Maybe try it again later, or somewhere else?

**Comment by mkborregaard** [comment]
There are a number of different issues, so it's hard to troubleshoot.
1. Do you mean `Pkg.build(Plots)`?  Plotly is a different package. Some of your errors report plotly, other Plots.
2. As @ChrisRackauckas your plotly issues look like something with web connectivity.
3. The `key "set_facecolor"` error is thrown from the pyplot backend. This is due to your matplotlib being of an outdated version (1.5 rather than 2.0). Do you know why that is? Did you follow advice to try to keep `qt` at 4.8? (that's an old suggestion that shouldn't apply anymore). The solution is `import Conda; Conda.update()`.
4. When installing a new julia version you should always run `Pkg.build("IJulia")` or Jupyter is very likely to fail. That should be unrelated to this, though.

**Comment by albi3ro** [comment]
Typo, that was Pkg.build("Plots") that had that error, and not Pkg.build("Plotly")

**Comment by albi3ro** [comment]
1) I discovered for `curl -o /home/antares/.julia/v0.5/Plots/deps/plotly-latest.min.js -L https://cdn.plot.ly/plotly-latest.min.js`, I needed to run that command on the command line with `sudo` attached to it.  That downloaded the file I needed, and then I could proceed from there.

 2) @mkborregaard was also correct about my matplotlib being out of date.  I updated it, and now I have successfully plotted.  

Thanks as well for the tip about updating `IJulia`.

**Comment by mkborregaard** [comment]
Great, happy plotting!

**Comment by jeff-regier** [comment]
I started getting this error from Plots.jl too, after running `Pkg.update()` in Julia. Running
```
sudo pip install matplotlib --upgrade
```
fixed it for me. I didn't have to do anything with `curl`. Just thought I'd mention it in case others with the same problem find this thread.

**Comment by ymer** [comment]
I'm getting this issue also. And I haven't succeeded with any of the suggestions here. Tried on multiple systems, and with both Julia 0.5 and 0.6.

**Comment by mkborregaard** [comment]
@ymer Plots isn't compatible with matplotlib 1.5. We should print a warning.
