### ISSUE TITLE
GLVisualize plot does not correspond with window.

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#880]
The plot created by glvisualize does not fit the window, and resizing the window makes it worse: 
Some screenshots:
Default popup-window:
<img width="601" alt="skaermbillede 2017-05-25 kl 09 43 55" src="https://cloud.githubusercontent.com/assets/8429802/26440932/d278af48-412e-11e7-8e3a-4122b316d991.png">
After resizing the window by dragging with the mouse:
<img width="293" alt="skaermbillede 2017-05-25 kl 09 44 10" src="https://cloud.githubusercontent.com/assets/8429802/26440952/e1eedbf0-412e-11e7-8df1-c9b0fcd5390b.png">
Plotting again to the resized window:
<img width="290" alt="skaermbillede 2017-05-25 kl 09 44 24" src="https://cloud.githubusercontent.com/assets/8429802/26440966/f1afb92e-412e-11e7-91f8-d81c354b1342.png">

I wonder if part of the strange behaviour could be due to the 'pixel doubling' on my retina screen?

**Comment by mkborregaard** [comment]
@daschw you've been using glvisualize, do you see this behaviour too? If not it sounds probable this could be a retina issue.

**Comment by daschw** [comment]
The default plot fits on my linux but resizing does not work properly

**Comment by SimonDanisch** [comment]
yeah resizing doesn't work, since Plots.jl isn't aware of that, but it basically handles what to draw for a specific window size. So GLVisualize just doesn't do anything right now.

**Comment by daschw** [comment]
Closing as GLVisualize is no longer supported.
