### ISSUE TITLE
Add label/legend title 

### ISSUE THREAD

**Issue by arturgower** [JuliaPlots/Plots.jl#882]
Would be great to specify a label/legend title. For publications this can be a necessity. 

[Here is an example](https://matplotlib.org/examples/pylab_examples/legend_demo3.html) from matplotlib

![legend_demo3](https://cloud.githubusercontent.com/assets/24454863/26721852/6ed38852-4785-11e7-9c45-41137582e344.png)

**Comment by daschw** [comment]
`plot(rand(10, 3), legendtitle = "My Awesome Title")` works now on master for GR and PyPlot
