### ISSUE TITLE
RFC: Thickness Scaling

### ISSUE THREAD

**Issue by ma-laforge** [JuliaPlots/Plots.jl#891]
It would appear that at least a handful of people would like the ability to more easily beef up line thicknesses and font sizes using a single "control knob".

Some seem to want to do this using the Plots.jl "`dpi`" setting:
Ref: https://github.com/JuliaPlots/Plots.jl/issues/742

*And I do not think they are alone:*

Given the original implementation of the `dpi` setting, I suspect the authors might also have wanted this feature.

### Proposal
I propose we have a separate control value called `thicknessscaling` to achieve this goal instead of hijacking the `dpi` setting.

Though the two properties are not completely orthogonal (there is some overlap in what they control), they are very much independent.

For one, changing the DPI (or PPI) value should not change line thicknesses relative to the total image size.  Instead, DPI is supposed to ***proportionally*** change the number of pixels that make up a given line wrt the number of pixels that make up the entire image.  Note that DPI is purely a rasterization property (applies only when generating a pixel-based image).

### Naming
I am also open to having the name of this property changed to something more succinct.  `thicknessscaling` is an unpleasant key word to read.

**Comment by ma-laforge** [comment]
Please note that it might be best to consolidate this feature with `resetfontsizes` and `scalefontsizes`.

References:
https://github.com/JuliaPlots/Plots.jl/issues/836
https://github.com/JuliaPlots/Plots.jl/pull/837
https://github.com/JuliaPlots/Plots.jl/issues/739

**Comment by mkborregaard** [comment]
Thanks for bringing this up. This is part of a larger discussion about how to specify sizes in Plots, but it's nice to also have this opinion represented.
