### ISSUE TITLE
GR Legend Marker for Ribbons

### ISSUE THREAD

**Issue by joshday** [JuliaPlots/Plots.jl#896]
I believe https://github.com/JuliaPlots/Plots.jl/pull/885 changed the markers for ribbons (it used to just show a line).  Should a line also be part of the marker here?

<img width="690" alt="screen shot 2017-06-06 at 10 51 14 am" src="https://cloud.githubusercontent.com/assets/8075494/26835326/161f2ba2-4aa6-11e7-8807-ea8e41978b3b.png">

**Comment by mkborregaard** [comment]
I think in this case just the line would be ideal?

**Comment by daschw** [comment]
Thanks for the hint @joshday. I agree that for this use case showing just the line (like with the pyplot backend) would better. Are there maybe other such cases?
