### ISSUE TITLE
Histogram do not respect ylim

### ISSUE THREAD

**Issue by innerlee** [JuliaPlots/Plots.jl#899]
Julia 0.5.2
OS Ubuntu

Repro:
```julia
julia> using Plots

julia> pyplot()
Plots.PyPlotBackend()

julia> histogram(rand(1:10,100),bins=0:11,normed=true,xlim=[1,15],ylim=[0,1])
INFO: binning = 0:11
```

![figure_1](https://user-images.githubusercontent.com/9464825/26861053-de91ac90-4b73-11e7-9525-c9a7ed3f4234.png)

We can see that `ylim` do not have effect.

**Comment by mkborregaard** [comment]
Pretty sure this is fixed on master. Could you try `Pkg.checkout("Plots")`?

**Comment by innerlee** [comment]
👍 Master is ok, thanks!
