### ISSUE TITLE
`savefig` failure with GR

### ISSUE THREAD

**Issue by pfitzseb** [JuliaPlots/Plots.jl#902]
On 0.6.0-rc2, Plots master, GR master, Windows,
```julia
plot([1,2,3], [1,2,3], xlabel="# of operands", ylabel="time in µs")
savefig("~/test.png")
```
produces something like
![test](https://user-images.githubusercontent.com/6735977/26875587-e6a53546-4b82-11e7-97b0-4a5aa5ec3c12.png)

It does look fine in the Juno preview though:
![testjuno](https://user-images.githubusercontent.com/6735977/26875618-172047c4-4b83-11e7-9da4-c9750f3d773c.PNG)

**Comment by mkborregaard** [comment]
cc @jheinen

**Comment by jheinen** [comment]
Ok. The problem is with the "µ" character - I'll check this ...

**Comment by mkborregaard** [comment]
Solved by @jheinen  on GR master
