### ISSUE TITLE
Adding markers to the legend with pyplot

### ISSUE THREAD

**Issue by ttparker** [JuliaPlots/Plots.jl#911]
As discussed at https://stackoverflow.com/questions/44401976/how-do-you-add-markers-to-the-legend-of-a-plots-jl-plot/44405883#44405883, for a line/scatter plot with `marker = true`, there is no way to display both the marker and the line together in the legend.  This would be a nice feature to add.

**Comment by cortner** [comment]
I wouldn't really call this a feature but a bug :)

**Comment by mkborregaard** [comment]
It should be fairly straightforward to implement, if you'd like to make a PR? It needs to be done on a backend-by-backend basis, though.

**Comment by ttparker** [comment]
@mkborregaard Sorry, are you talking to me or to cortner? I have no idea how the Plots package's internals work, and don't know how to implement this feature ...

**Comment by mkborregaard** [comment]
To @cortner who I believe could definitely do it. It is also fine to wait - we will get to it eventually.

**Comment by cortner** [comment]
Not sure how I've deserved your optimism. I briefly looked at the pyplot backend - not all that straightforward for somebody who has worked on neither `Plots.jl` nor `PyPlot`. One would probably need to combine the `if series[:markershape] != :none` block with the `if series[:linewidth] > 0` block.

If I find the time (and care enough) I will have a go.

**Comment by mkborregaard** [comment]
I've update to reflect that this is only a problem on pyplot - on GR and plotlyjs it works:
```julia
plot(rand(10,4), markershape = :auto)
```
<img width="589" alt="skaermbillede 2017-10-03 kl 08 23 34" src="https://user-images.githubusercontent.com/8429802/31112531-8a74f1e6-a814-11e7-9d8e-765a1709868c.png">

**Comment by JackDevine** [comment]
Should we close this issue? Or do we wait until the next tag?

**Comment by daschw** [comment]
Closing with #1133 
Thanks @JackDevine!

**Comment by JackDevine** [comment]
Thanks @daschw , it is always a pleasure to work with the people at Plots.jl :smiley:
