### ISSUE TITLE
pyplot: Heatmap legend cut off on top

### ISSUE THREAD

**Issue by SaschaMann** [JuliaPlots/Plots.jl#925]
The legend of the resulting heatmap is cut off on top for large numbers.

Example:
```julia
using Plots; pyplot()
x = y = 1:10
z = 600000 * x * y'
heatmap(x, y, z, aspectratio = true)
```
![image](https://user-images.githubusercontent.com/20866761/27044660-a7ad2cf2-4f9e-11e7-9ff2-f93f565b561b.png)
You can see a part of `1e7` above the legend.

Exists in both Julia 0.5.2 & Plots 0.11 and Julia 0.6, Plots 0.12.

In an older version, there was a similar bug where the right side was cut off.

(cc @daschw)

**Comment by daschw** [comment]
Thanks!

**Comment by daschw** [comment]
see https://github.com/JuliaPlots/Plots.jl/pull/926

**Comment by SaschaMann** [comment]
That was really quick, thanks @daschw!
