### ISSUE TITLE
build in .travis with PGFplots.jl

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaPlots/Plots.jl#927]
this issues started here https://github.com/sisl/PGFPlots.jl/issues/75#issuecomment-307651227 but I think it may be because PGFplots.jl has build errors in conjunction with Plots.jl. So, I am sharing it here

**Comment by BeastyBlacksmith** [comment]
the pgfplots backend is now deprecated. Please reopen, if the issue persists with the pgfplotsx backend
