### ISSUE TITLE
% unsanitized for pgfplot

### ISSUE THREAD

**Issue by tpapp** [JuliaPlots/Plots.jl#928]
% in strings is written to LaTeX, where it acts as a comment. MWE:
```julia
using Plots
pgfplots()
p = plot(1:5, 1:5, title = "unsanitized %")
savefig(p, "/tmp/x.pdf")
```
I would be happy to contribute a PR, possibly for a general LaTeX string escape function, but need a bit of guidance:
1. which function should call it,
2. does it belong in Plots.jl or PGFPlots.jl?

**Comment by ChrisRackauckas** [comment]
>possibly for a general LaTeX string escape function

Is there an issue with using the `@L_str` macro from LaTeXStrings.jl?

**Comment by pedm** [comment]
Hi @tpapp, I just came across this same issue. Have you found a work around for this problem?

**Comment by BeastyBlacksmith** [comment]
Fixed in the pgfplotsx backend
