### ISSUE TITLE
Discrepancy in histogram plots compared with PyPlot

### ISSUE THREAD

**Issue by mbeltagy** [JuliaPlots/Plots.jl#930]
If one was to compare the histogram output straight out or PyPlot and Plots with `pyplot` backend, the difference is quite stark. 

Here is a minimal example 
First using Plots.jl
```julia
using Distributions, Plots
pyplot()
srand(15); x=rand(Exponential(4),200);
histogram(x,bins=30)
savefig("TestPlotFigPlts.png")
```
![testplotfigplts](https://user-images.githubusercontent.com/4301151/27142047-38f69b30-512a-11e7-9bef-46e916138d27.png)

Now using PyPlot
```julia
using Distributions, PyPlot
srand(15); x=rand(Exponential(4),200);
plt[:hist](x,bins=30)
savefig("TestPlotFigPyPlot.png")

```
![testplotfigpyplot](https://user-images.githubusercontent.com/4301151/27142048-38f8de90-512a-11e7-8a94-023fd67f9334.png)

The data is identical, but the distributions look very different. I am not sure how they can be brought in line.

**Comment by getzdan** [comment]
looks like the first histogram has only 20 bins (although parameter specifies 30)

**Comment by dpsanders** [comment]
The parameter is called `nbins` in Plots.jl, not `bins`.

**Comment by dpsanders** [comment]
And I believe that that is only a suggestion: Plots.jl determines the "best" number using some heuristics.

**Comment by dpsanders** [comment]
(Or maybe `bins` is an alias to `nbins`? If not, then it should be.)

**Comment by tamasgal** [comment]
Which version are you using? It works for me fine with your example code, I get 30 bins and both histograms look similar.

**Comment by mbeltagy** [comment]
@dpsanders 
I believe it. If I could trust the [attributes table](https://juliaplots.github.io/attributes/) 

@tamasgal 
I am using 0.12.0
```julia
julia> Pkg.status("Plots")
 - Plots                         0.12.0
```
Running on Julia 0.6.0-rc3.0

**Comment by daschw** [comment]
Plots is using `StatsBase.histrange` to determine the number of ticks based on the input. I don't know about the heuristics used there, but I think this is expected behaviour, right @oschulz ?

**Comment by mkborregaard** [comment]
This is expected, yes - I answered the question here: https://discourse.julialang.org/t/how-to-set-histogram-alignment-in-plots-jl/4273/4

**Comment by oschulz** [comment]
Yes, it's expected.
