### ISSUE TITLE
can't disable the colorbar in heatmap with plotly()

### ISSUE THREAD

**Issue by ko56** [JuliaPlots/Plots.jl#932]
I am trying to display a heatmap without the colorbar. In Julia 0.5.1 (on FreeBSD), with the plotly backend, neither legend=false, nor colorbar=false, nor both of these succeed in eliminating the colorbar.

The problem does not occur with the PyPlot backend: legend=false works as expected.

**Comment by daschw** [comment]
Thanks for reporting this! This is now possible on Plots master with julia 0.6.

**Comment by ko56** [comment]
Hi Daniel,

I updated to Julia 0.6 yesterday, so re-installed all packages, but this 
issue is still there.  Do I need to do something else?

**Comment by daschw** [comment]
This feature is not yet included in a tagged release. It should work on master (`Pkg.checkout("Plots")`) for now and will be included in the next release.
