### ISSUE TITLE
RFC: "Stylesheets" - or presets for plot appearances

### ISSUE THREAD

**Issue by ma-laforge** [JuliaPlots/Plots.jl#937]
I was just wondering if other people would like the idea of having presets to quickly control plot appearances.  For example, we could have a high-level API looking somewhat like:

```
Plots.default(Plots.stylesheets[:IEEEPub_1col])

#or,
Plots.default(Plots.stylesheets[:JAMAPub])

#or even simply
Plots.default(Plots.stylesheets[:3D_azure])
```

Where `Plots.stylesheets` could simply be a `Dict` of curated presets
(NOTE: I *think* this correspond to what people call "stylesheets")

For a long time now, Grace/xmgrace (xwindows plotting tool) has used "templates" (.par) files that can easily be saved/re-loaded - allowing users to maintain a uniform appearance for publications.  I made sure to provide an Julia API when I developed my own https://github.com/ma-laforge/GracePlot.jl wrapper.

I really like this feature... but I am not certain how necessary it is to persist these stylesheets to a file.  I think that having a `Dict` of pre-defined stylesheets would be sufficient.

Any comments?  Is this something that would be useful?  Would there be a better way to implement this feature?

**Comment by mkborregaard** [comment]
This sounds like a natural extension of the functionality in PlotThemes (which presently only sets colors, but there's no reason for that), and could live there.

**Comment by ma-laforge** [comment]
Good point.  I had not thought of that, for some reason.

Hmmm... Still not sure how to allow for user-defined "themes", given how PlotThemes.jl is implemented (more of a closed environment)....

**Comment by mkborregaard** [comment]
Today, user-defined themes are either implemented by e.g. `default(ms = 4, msw = 0, mc = :black, seriescolor = :coolwarm, lw = 1.5)` or by setting those values in the juliarc.jl file. I'd like to see a use  case where that didn't work. If you did want set styles in PlotThemes I guess they could be addressed by having a `style` function that takes a style name and calls default?

**Comment by ma-laforge** [comment]
That's true.  Instead of building a "theme" object, we could define a/multiple "theme" function(s) that changed the values in `default`... or even overwite the settings in the provided plot object.

Maybe it is more about having use cases in the documentation - and possibly a few example "themes" that people might like (instead of adding more complexity to Plots)...

**Comment by t-bltg** [comment]
I guess we have this in https://github.com/JuliaPlots/PlotThemes.jl now.
