### ISSUE TITLE
Time series plots, crash

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaPlots/Plots.jl#946]
Since a few days, the following gives a lot of messages and no plot. (Julia 0.6, Win7 64, Plots 0.12.0)  
```
using Plots
dN = Date(2015,12,4):Dates.Day(1):Date(2016,12,31)
y  = randn(length(dN),1)
plot(dN,cumsum(y))
```

The messages start with
```
WARNING: convert{R <: Real}(::Type{R}, x::Dates.Date) is deprecated, use R(Dates.value(x)) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] convert(::Type{Int64}, ::Date) at .\deprecated.jl:57
...
ERROR: LoadError: syntax: extra token "is" after end of expression
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:569
 [2] include(::String) at .\sysimg.jl:14
...
```

**Comment by daschw** [comment]
Thanks for reporting this @PaulSoderlind! It should now work again on PlotUtils and Plots master.

**Comment by PaulSoderlind** [comment]
Thanks,
that works now. However, I see a similar issue with using
```
xTicks = [Date(2016,1,1);Date(2016,7,1)] 
plot(dN,cumsum(y),xticks=xTicks)
```

**Comment by daschw** [comment]
`xticks = Dates.value.(xTicks)` should work
... but I guess this could either be documented or the functionality you expected could be implemented

**Comment by PaulSoderlind** [comment]
>```xticks = Dates.value.(xTicks)```  should work.

Yes, it does. Thanks.
