### ISSUE TITLE
GR testimage 10 fails

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/Plots.jl#948]
The travis tests fail, because the testimage 10 is not working properly:
```julia
using Plots; gr()
test_examples(:gr, 10)
```
produces
![gr_testimage10](https://user-images.githubusercontent.com/16589944/27450412-ebf3ba26-578b-11e7-9212-1902558fc513.png)

Here's the comparison:
![gr_test_ref10](https://user-images.githubusercontent.com/16589944/27450457-0c413786-578c-11e7-9a22-718f8b6c790a.png)

@jheinen Could this be caused by https://github.com/JuliaPlots/Plots.jl/pull/944? (the tests were working before)

**Comment by jheinen** [comment]
... should be fixed now.

**Comment by daschw** [comment]
Wow, fast as always ;-)

The borders of the image/axes seem a little cut though:
![gr_testimage10_fix1](https://user-images.githubusercontent.com/16589944/27454335-c7f2e38c-5799-11e7-8dd8-161a3ac2b8f5.png)

This also happens for testimage 28:
![gr_testimage28](https://user-images.githubusercontent.com/16589944/27454392-0561bb80-579a-11e7-8f3e-617a93f79024.png)

**Comment by jheinen** [comment]
I just realized, that the problem is not finally solved. I need both the axis limits and the x/y extrema to provide the correct arguments to the GR.drawimage() function. But the extrema (data_lims) seem to be overwritten in gr.jl - no idea yet.

**Comment by jheinen** [comment]
It's also a general question, whether the axes should automatically be "extended" by half the size of a cell.

**Comment by daschw** [comment]
I think they should if this would draw the full cells - unless there are axes limits set by the user probably.

**Comment by daschw** [comment]
Fixed by #951, Thanks @jheinen!
