### ISSUE TITLE
After updating, Plots can't load

### ISSUE THREAD

**Issue by orswan** [JuliaPlots/Plots.jl#950]
I just did a `Pkg.update()`, and it seems to have broken Plots.  This is what I get when trying to use the package now:

    julia> using Plots
    INFO: Precompiling module Plots.
    WARNING: could not import RecipesBase.plot into Plots
    WARNING: could not import RecipesBase.animate into Plots
    ERROR: LoadError: LoadError: UndefVarError: AbstractBackend not defined
     in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
     in macro expansion; at .\none:2 [inlined]
     in anonymous at .\<missing>:?
     in eval(::Module, ::Any) at .\boot.jl:234
     in process_options(::Base.JLOptions) at .\client.jl:239
     in _start() at .\client.jl:318
    while loading C:\Users\swan\.julia\v0.5\Plots\src\types.jl, in expression starting on line 32
    while loading C:\Users\swan\.julia\v0.5\Plots\src\Plots.jl, in expression starting on line 138
    ERROR: Failed to precompile Plots to C:\Users\swan\.julia\lib\v0.5\Plots.ji.
     in compilecache(::String) at .\loading.jl:593
     in require(::Symbol) at .\loading.jl:422
    
    julia>

I'm in Julia version 0.5.0.

Moreover, when I try to run `Pkg.update()` again, it now tells me the following:

    julia> Pkg.update()
    INFO: Updating METADATA...
    [...]
    INFO: Updating Plots master...
    INFO: Computing changes...
    WARNING: julia is fixed at 0.5.0 conflicting with requirement for Plots: [0.6.0-pre,∞)
    [...]

Where the [...] are some irrelevant bits I've omitted.  It's not clear to me how to resolve this.

**Comment by joshday** [comment]
I think you're on the master branch of plots, which doesn't support Julia 0.5.  What is your `Pkg.status()`?

**Comment by orswan** [comment]
Yeah, it's showing master.  What branch should I be on?  (A tip on how to switch to that branch would also be appreciated.)

**Comment by joshday** [comment]
`Pkg.free("Plots")` puts it back into the hands of the package manager.  You may need to do the same for Plots-related packages like RecipesBase and PlotUtils.
