### ISSUE TITLE
Make aspect_ratio=:equal the default when possible

### ISSUE THREAD

**Issue by dpsanders** [JuliaPlots/Plots.jl#952]
I almost always want `aspect_ratio=:equal`.
Can this somehow be made the default?

**Comment by daschw** [comment]
You can make it your default by adding
```julia
PLOTS_DEFAULTS = Dict(:aspect_ratio => :equal)
```
to your `.juliarc.jl` file. Of course you can also add other default values for Plots attributes to this `Dict`.

**Comment by daschw** [comment]
Considering simple cases like `plot(rand(100), aspect_ratio = :equal)` or `histogram(randn(1000), aspect_ratio = :equal)`, I think it should not be the Plots default.

**Comment by dpsanders** [comment]
Yes, you're right - my suggestion was too loose. There should be a check on the ratio of the actual figure being drawn; if it's within some threshold, then the aspect ratio should be equal.

There are *so* many plots out there of circles etc. that look completely wrong because the plotting package fixes the aspect ratio in an arbitrary way.

**Comment by dpsanders** [comment]
(I didn't know about `PLOTS_DEFAULTS`, thanks!)

**Comment by mkborregaard** [comment]
Sorry, I don't agree with this suggestion, so for now I've added a "wontfix" label.

**Comment by alanedelman** [comment]
not sure if this is a new issue, but I don't really get aspect_ration=:equal

When I write:
```
t = π*(0:.01:.4)
plot(cos,sin,t,aspect_ratio=:equal,legend=false)
```

I get something that is not quite what I expected 


![image](https://user-images.githubusercontent.com/862530/29148894-532c5220-7d3e-11e7-8c6d-2e3ef46dc64a.png)

**Comment by pkofod** [comment]
wontfix -> close?

**Comment by mkborregaard** [comment]
why not
