### ISSUE TITLE
Error: "key :html_output_format not found" when using pyplot() backend in Juno

### ISSUE THREAD

**Issue by lissonc** [JuliaPlots/Plots.jl#958]
I'm using the `pyplot()` backend in Juno and frequently get the following error message when plotting:

`key :html_output_format not found`

Everything seems to work just fine; it's just that this message keeps coming up. Have you got some more information on this error message and where it might originate from (or whether it is indeed a bug)?

**Comment by daschw** [comment]
Could you provide a minimal example to reproduce this error?

**Comment by mkborregaard** [comment]
does this persist or can the issue be closed?
