### ISSUE TITLE
Colorbar label is flipped when yflip=true

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#961]
To reproduce the issue:

```julia
using Plots

X = rand(100,100)
heatmap(X, yflip=true)
```
![screenshot from 2017-07-01 20-34-30](https://user-images.githubusercontent.com/3345261/27767053-beb1083a-5e9c-11e7-8831-1cecc5dd38b3.png)

**Comment by juliohm** [comment]
Can you please assign the label bug to this issue?

**Comment by daschw** [comment]
I think this issue only appears with the GR backend, right? And this is a duplicate of #889.

**Comment by juliohm** [comment]
Thank you @daschw , yes it is only with GR. I am closing this duplicate.
