### ISSUE TITLE
additional deprecations for Julia v0.6

### ISSUE THREAD

**Issue by RalphAS** [JuliaPlots/Plots.jl#966]
To avoid the indignity of trivial PRs, let us make a list of remaining deprecations so they can be fixed together in time for the next tag.  Here is a start:

`round` in `src/backends/gr.jl`, line 856, should be broadcast.

`abs` in `src/backends/pyplot.jl`, line 929, should be broadcast.

**Comment by daschw** [comment]
Thanks for these hints.
I personally, however, don't think there's anything wrong with small "trivial" PRs fixing deprecations.

> `abs` in `src/backends/pyplot.jl`, line 929, should be broadcast.

is fixed in #967.

**Comment by daschw** [comment]
> `round` in `src/backends/gr.jl`, line 856, should be broadcast.

is fixed in #975.

**Comment by RalphAS** [comment]
Since you don't mind small PRs and no more deprecations have been reported, I'll close. Thanks.
