### ISSUE TITLE
PlotlyJS: Inconistent numeric format on logarithmic axis labels

### ISSUE THREAD

**Issue by AndiMD** [JuliaPlots/Plots.jl#973]
Hi all,

When using backend plotlyjs, I see inconistent numeric formats for axis labels:
Result (plotlyjs):     10e+21, 100e+21, 1e+24, 10e+24, 100e+24, 1e+27
Expected (gr): 1e+22, 1e+23, 1e+24, 1e+25, 1e+26, 1e+27

I'm on Linux, Julia 0.6 with Plots 0.12.0,PlotlyJS 0.6.4.

Code:
`using Plots;`
`xdata = logspace(22,27,100);`
`ydata = 1./log(xdata);`
`plotlyjs();`
`p1=plot(xdata,ydata,xscale=:log10);`
`display(p1)`
`gr();`
`p2=plot(xdata,ydata,xscale=:log10);`
`display(p2)`

<img width="596" alt="bugreportplots" src="https://user-images.githubusercontent.com/24719218/28365732-f50ebb48-6c89-11e7-898c-90d08559e1fc.png">

**Comment by daschw** [comment]
I suspect that's a Plotly or PlotlyJS, rather than a Plots issue:
```julia
using PlotlyJS
xdata = logspace(22, 27, 100)
ydata = 1 ./ log.(xdata)
plot(scatter(; x = xdata, y = ydata, mode = "lines"), Layout(xaxis_type = "log"))
```
produces the same xticks format.

**Comment by mkborregaard** [comment]
@AndiMD thanks for spotting this - would you mind opening an issue describing this on PlotlyJS?

**Comment by AndiMD** [comment]
CrossRef: [https://github.com/sglyon/PlotlyJS.jl/issues/132](https://github.com/sglyon/PlotlyJS.jl/issues/132)
