### ISSUE TITLE
Error loading GLVisualize backend

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Plots.jl#974]
This is what I get with the latest stable versions:

```julia
using GLVisualize
glvisualize()
WARNING: Couldn't initialize glvisualize.  (might need to install it?)
if !Plots.is_installed("GLVisualize")
    Pkg.add("GLVisualize")
end



INFO: To do a standard install of glvisualize, copy and run this:

ArgumentError: Module Contour not found in current path.
Run `Pkg.add("Contour")` to install the Contour package.
```

It seems that Contour is no longer a dependency in GLVisualize.jl, but it is being loaded in Plots.jl?

**Comment by SimonDanisch** [comment]
Yeah the optional requirements are a bit messy... Contour.jl is only needed in the intersection of Plots + GLVisualize, but not actually used by them alone, so no package has it in their requirements.
Note, that you'll need: https://github.com/JuliaPlots/Plots.jl/pull/970

**Comment by daschw** [comment]
This should be fixed on master now, right?

**Comment by juliohm** [comment]
@daschw Plots.jl master or GLVisualize.jl master? What is the configuration that is working?

**Comment by daschw** [comment]
Plots.jl master. I don't think GLVisualize.jl master is required.

**Comment by juliohm** [comment]
Thanks, it is fixed now. Closing the issue.

**Comment by daschw** [comment]
Great!
