### ISSUE TITLE
requires Matplotlib 2?

### ISSUE THREAD

**Issue by stevengj** [JuliaPlots/Plots.jl#978]
7aca2b1584503c28dd9660d15f13630d9b690ef3 calls `set_facecolor`, which apparently was introduced in Matplotlib 2.0 (previously it was called [set_axis_bgcolor](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_axis_bgcolor.html), I guess?)

Apparently this is causing problems [for users who still have Matplotlib 1.5](https://discourse.julialang.org/t/pyplot-keyerror-with-simple-plot-in-julia-0-6/4985?u=stevengj).

If you don't want to support Matplotlib 1.5, you should check `PyPlot.version` (this is the Matplotlib version) on startup and print an informative error message.

**Comment by mkborregaard** [comment]
I agree with the error message solution, thanks for the suggestion.

**Comment by stevengj** [comment]
Fixed by #982.

**Comment by mkborregaard** [comment]
great!
