### ISSUE TITLE
pyplot(): Missing data coordinate (x,y) from plots on hover

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaPlots/Plots.jl#979]
I just could not find any issue related to this and although it may not be a priority, I found it very useful. 

When I plot using the `PyPlot` backend itself the data coordinate is shown properly when hovering with the mouse pointer. However, when I call `pyplot()` after `using Plots`, the (x,y) data coordinate is missing. For example:

`using PyPlot`
`plot(rand(10))`

![pyplot](https://user-images.githubusercontent.com/26485264/28467329-92f3c622-6dfd-11e7-812d-da4bede85307.png)

This works fine, I can see the coordinates when hovering on the plot at the bottom left. Now,

`using Plots`
`pyplot()`
`plot(rand(10),show=true)`

![pyplot](https://user-images.githubusercontent.com/26485264/28467345-975aeb64-6dfd-11e7-84e1-b104c30818de.png)

does not work. I tried without the `show=true` argument using `gui()` and still the same. There is maybe a trick I am missing. 

Thanks!

**Comment by isentropic** [comment]
This happens because ticks are provided by plots. You should use `ticks=:native` to get the data points when hovering
