### ISSUE TITLE
turn on appveyor?

### ISSUE THREAD

**Issue by jverzani** [JuliaPlots/Plots.jl#991]
We were noticing an issue with 32-bit windows machines with Plots (`InexactError`) and I noticed `v0.6.0` was not being tested in `appveyor.yml`. PR #990 was to test this, but it seems that appveyor is not enabled.

**Comment by mkborregaard** [comment]
Yes I think everyone in the organization are on either Ubuntu or Mac, so noone would notice. You're welcome to turn it on in #990 if you like.

**Comment by mkborregaard** [comment]
I merged the PR, but the appveyor build fails. It looks as if we're not compatible with 32-bit windows? Also is there a way to test against nightly for information, but allow failures (like we do on Travis) so we don't have all the builds failing because of changes to Julia nightly?

**Comment by timholy** [comment]
Yes, you can allow failures on AppVeyor. [Example](https://github.com/JuliaImages/Images.jl/blob/master/appveyor.yml).

Second, for debugging 32-bit failures, if you have access to a Linux machine it's not hard to build a 32-bit version. See https://github.com/JuliaLang/julia/pull/23330#issuecomment-323499824 and comments below that. At least on Ubuntu there are pre-built packages for 32 bit for all the required dependencies to build Julia.

**Comment by mkborregaard** [comment]
Thanks a lot, I'll try it out!

**Comment by mkborregaard** [comment]
Closed, as appveyor is now turned on.
