### ISSUE TITLE
pyplot(): latex preamble as in PyPlot

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaPlots/Plots.jl#997]
When `Using PyPlot` I can call the following:

`using PyCall`
`PyDict(pyimport("matplotlib")["rcParams"])["text.usetex"] = [true]`
`PyDict(pyimport("matplotlib")["rcParams"])["text.latex.preamble"] = ["\\usepackage[utf8]{inputenc}", "\\usepackage[sfdefault, scaled=0.85, lf]{FiraSans}", "\\usepackage[T1]{fontenc}", "\\usepackage{amsmath,amsthm}", "\\usepackage[cmintegrals,slantedGreek]{newtxsf}", "\\usepackage{siunitx}",]`

`plot(rand(100))`
`xlabel(L"$\sigma=2\mu$")`

![pyplot](https://user-images.githubusercontent.com/26485264/28935629-31e2f60e-7853-11e7-8554-11976d7f231a.png)

It works fine. The fonts are all the same over the whole picture. But, when I do the same (kind of) with Plots:

`Using Plots, LaTexStrings`
`Using PyCall`
`PyDict(pyimport("matplotlib")["rcParams"])["text.usetex"] = [true]`
`PyDict(pyimport("matplotlib")["rcParams"])["text.latex.preamble"] = ["\\usepackage[utf8]{inputenc}", "\\usepackage[sfdefault, scaled=0.85, lf]{FiraSans}", "\\usepackage[T1]{fontenc}", "\\usepackage{amsmath,amsthm}", "\\usepackage[cmintegrals,slantedGreek]{newtxsf}", "\\usepackage{siunitx}",]`
`pyplot()`

`plot(rand(100))`
`xlabel!(L"$\sigma=2\mu$")`

![plots](https://user-images.githubusercontent.com/26485264/28935699-63510906-7853-11e7-9122-15cc0a47e714.png)

it doesn't call properly the whole preamble. Actually, the `siunitx` package isn't call at all as the commands don't work, and the fonts in the labels render with a different size.

I am not using matplotlibrc.

**Comment by lnacquaroli** [comment]
OK, I just figured it out (in the Plots documentation) by changing the fonts size through the axis parameters:

`xlabel!(L"$\sigma=2\mu$", xaxis=(font(14)))`

And the whole preamble is also working with units included.

**Comment by mkborregaard** [comment]
Yes, it is undefined to mix Plots calls with direct PyCall calls. Glad you worked it out. This can be closed again, right?

**Comment by lnacquaroli** [comment]
I see,  so would you say the best way to use the preamble using pyplot is through matplotlibrc? Is actually Plots looking at that file every time?

**Comment by mkborregaard** [comment]
I don't know enough about the matplotlib interface to answer that - @ChrisRackauckas you're very sharp on PyPlot, aren't you?

**Comment by lnacquaroli** [comment]
After a few tests I can say `Plots` actually calls matplotlibrc. 

Just to notice that the comma separated properties for each latex package are wrongly split when using matplotlibrc (https://github.com/matplotlib/matplotlib/issues/4371). So, this will work using packages without options. Out of the scope of `Plots` at to this point I guess. However, when using the `PyCall` without matplotlibrc, things work fine. 

Thanks!

**Comment by lnacquaroli** [comment]
We can close this unless @ChrisRackauckas has something else.

**Comment by ChrisRackauckas** [comment]
Nope, I don't have anything.

**Comment by ChrisRackauckas** [comment]
Nice to hear that it uses matplotlibrc though.
