### ISSUE TITLE
Plot Numbering and Labeling

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Plots.jl#998]
For publications you usually need label plots like `(a)` `(b)` `(c)`. It would be nice if there was a way these kinds of annotations could automatically be added when using subplots/layouts.

**Comment by lnacquaroli** [comment]
+1

Considering all the effort put in Plots for customization it would really be a nice thing to have. Is there maybe a recipe for that? I am not totally into how they work though.

**Comment by mkborregaard** [comment]
What syntax do you suggest?

At the moment we have "title", e.g. `plot(randn(10,2),layout = 2, title = ["a" "b"], titlepos = :left)`, though that only allows defining the title outside the plot window. You can also use `annotations`, maybe a short-format argument to `annotations` could be the way to go.

**Comment by ChrisRackauckas** [comment]
`corner_label = ["(a)" "(b)" "(c)"]` and puts that in the upper left corners.

**Comment by ChrisRackauckas** [comment]
Or `plot_id`

**Comment by mkborregaard** [comment]
> Considering all the effort put in Plots for customization it would really be a nice thing to have

Absolutely. I'd say though that I use Plots every day, and every day I think of something that'd be nice to have :-) The mode of Plots development is very much through PRs from interested users.

BTW, a good overview of recipes is given in the new tutorial: https://juliaplots.github.io/tutorial/

**Comment by mkborregaard** [comment]
I'd say this is really a type of `annotation`, and it'd be nice to set it automatically with the `annotations` keyword. The interface to that is horrible, IMHO. It'd be great to rethink `annotations` so it would make something like this easy (it really should be).

**Comment by lnacquaroli** [comment]
I don't feel the interface of `annotations` is that bad, maybe not intuitive enough. Legends are not allowed outside the plot area either, right? 

At this point I wonder what would the difference be between 

`plot(randn(10,2),layout = 2, title = ["a" "b"], titlepos = :left)`

And something like

`corner_label = ["(a)" "(b)" "(c)"]`.

Because in the end if you have to use `layout` anyway, you just pass the string to the title kwarg. In terms of coding, I don't see more or less complexity between them. Just a thought now.

**Comment by lnacquaroli** [comment]
Sorry, legends are allowed outside the plot area.

**Comment by mkborregaard** [comment]
I agree. The point about using `annotations` would be to have a higher degree of control. I should probably elaborate on my issues with the syntax in an issue that proposes a solution...

**Comment by lnacquaroli** [comment]
I still think the chance to have `annotations` with fixed positioning options (`:topleft`, etc ) is great. I tend to use the (a), (b), (c) subplots labeling inside the plot area, and spent quite sometime when I have different axis limits to place those labels and get them aligned with the current (x, y) control.

**Comment by apalugniok** [comment]
I managed to make something like this, still needs a bit of work to make it pretty and more customisable but here's its current state.
```
plot(rand(10,4), anns = :top, layout = grid(2,2))
```
would give 
![annotations](https://user-images.githubusercontent.com/22132297/34161836-b88a48be-e4c9-11e7-8334-aaa9c8763a74.png)
The questions I have:
- Do we want to just be able to pass a symbol specifying location into `annotations` a get lettered labels on each subplot or do we want to pass in our own annotations and place them according to a symbol?
- Where should the subplot labels be placed?

**Comment by lnacquaroli** [comment]
That looks great!

- I guess if we could pass our own annotations would be the best (same way as `title` right now).
- It would be nice to have the ability to place them at each subplot independently, considering the characteristics of the data might differ from one subplot to another, and possibly interfering with the label, as in your example (b). It might look a bit disorganized as well though...
